### ISSUE TITLE
$HEAP_BASE, load/store, JS linking semantics

### ISSUE THREAD

**Issue by magcius** [AssemblyScript/assemblyscript#100]
Hi. I'm trying to use AssemblyScript in my project. I notice that AssemblyScript can reserve static data at the start of the binary, in the form of `memoryBase`, and static data can be included for e.g. assert. However, as far as I can tell, `load` and `store` addresses are not affected by this offset, and $HEAP_BASE isn't exported to JavaScript, JS has no idea where to start its heap.

This seems unsafe. load/store should probably be relative to $HEAP_BASE, and it should be exported so that JavaScript can fill in a heap without chance of corruption. You can see this in action if you modify the game-of-life example to include an assert.

**Comment by dcodeIO** [comment]
At this point, `HEAP_BASE` is just an implicitly generated global that can be accessed like any other global. Intention is to tell a dynamic memory manager like TLSF where to [place itself](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/allocator/tlsf.ts#L445) into linear memory and there haven't been a lot of thoughts on [dynamic linking](https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md) yet.

One way to let the JS-side know about it could be something like this:

```ts
export function getHeapBase(): usize {
  return HEAP_BASE;
}
```

Similarily, the game of life example assumes that there is no static memory and thus doesn't make use of `HEAP_BASE`, but it could of course be extended to take it into account.

**Comment by magcius** [comment]
Right. So, from my integration, I was using assert(), which tries to allocate static memory, and I was stomping on it with my load/stores. Right now those two pieces of functionality aren't able to be combined, because the load/stores have no way of knowing what the correct offset is. I think it makes sense for load/store to be relative to HEAP_BASE, and assume that anything under it is either static data or scratch (e.g. stack) memory.

I've pushed a branch with a sketch of these ideas over here: https://github.com/magcius/assemblyscript/commits/issue100 , though I haven't fixed any tests or examples yet.

**Comment by dcodeIO** [comment]
There are legit use cases though where accessing something before HEAP_BASE is necessary. Say, for example, you'd intentionally leave a few kilobytes of memory free for something you know the size of, like wasmBoy does for the rom. You'd not want negative offsets there I think.

**Comment by magcius** [comment]
Aha, that makes sense. For now, I'll remove use of static data in my script. The first two commits on the branch might make sense separately, though.

**Comment by dcodeIO** [comment]
The idea behind using 4/8 as the default HEAP_BASE in WASM32/64 respectively is leaving space for a potential null reference pointing at zero. Also functions as a sentinel, that is if something is stored there, there's most likely something wrong. Mostly exists because other compilers I've toyed around with did this.

Exporting HEAP_BASE seems reasonable, but it would prevent an optimizer from eliminating it if not used. My guess is that most programs won't need it, but not sure.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
