### ISSUE TITLE
Broken link on npm

### ISSUE THREAD

**Issue by kripken** [AssemblyScript/assemblyscript#101]
https://www.npmjs.com/package/assemblyscript links to http://dcode.io/AssemblyScript/ which gives a "page not found" error.

**Comment by dcodeIO** [comment]
Yeah, just moved all related repos to the AssemblyScript GitHub org and haven't published a new version to npm yet. Should be fixed with the next publish!

For reference, the new link is http://assemblyscript.org/try/

**Comment by dcodeIO** [comment]
Fixed now with 0.3.0, thanks!
