### ISSUE TITLE
Fail to run ugc example

### ISSUE THREAD

**Issue by mleprince** [AssemblyScript/assemblyscript#101]
Hi,

I'm playing with this wonderful project and I wanted to try the GC feature. When a run the test of the [UGC example](https://github.com/AssemblyScript/assemblyscript/tree/master/examples/ugc) as described in the readme and I have the following error : 

```
> @assemblyscript/ugc@1.0.0 test /home/maximelerince/sandbox/assemblyscript/examples/ugc
> node tests

/home/maximelerince/sandbox/assemblyscript/examples/ugc/tests/index.js:5
var ugc = new WebAssembly.Instance(new WebAssembly.Module(fs.readFileSync(__dirname + "/../ugc.untouched.wasm"))).exports;
          ^

TypeError: WebAssembly Instantiation: Imports argument must be present and must be an object
    at Object.<anonymous> (/home/maximelerince/sandbox/assemblyscript/examples/ugc/tests/index.js:5:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! Test failed.  See above for more details.
```
I didn't change anything in the code. As I understand, this is because we import : `import "allocator/tlsf";` in the module.js.

I use Typescript 2.8 and node 8.10.

Any idea ? 

Thanks

**Comment by dcodeIO** [comment]
Thanks, should be possible to build and run it again. Note that it doesn't do anything useful yet because it relies on compiler integration, but feel free to experiment! :)

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
