### ISSUE TITLE
"assertion failed" when using @unmanaged classes and inheritance

### ISSUE THREAD

**Issue by vladimir-tikhonov** [AssemblyScript/assemblyscript#1013]
Hi,

I've created a repo where you can easily reproduce this issue: https://github.com/vladimir-tikhonov/as-bug. Seems like every line there is needed in order to get an exception, including inheritance and empty constructor.

**Comment by dcodeIO** [comment]
Can you try to use `AssemblyScript/assemblyscript` as a dependency? That should obtain a development install of master with proper stack traces, pointing at the origin of the assertion if everything goes well.

**Comment by dcodeIO** [comment]
Appears the assertions is [here](https://github.com/AssemblyScript/assemblyscript/blob/899e97ab28a857da07a533551eb937d771677f93/src/compiler.ts#L5774) when dealing with unmanaged `super()` calls. Since these aren't managed, there are no autoreleases there.

**Comment by vladimir-tikhonov** [comment]
@dcodeIO, a little bit late to the party, but I can confirm that #1014 fixed this error for both test repo and the original project. Thanks a lot!
