### ISSUE TITLE
Wrong pointer offsets?

### ISSUE THREAD

**Issue by creationix** [AssemblyScript/assemblyscript#1015]
I'm trying a very basic technique where I expose an AssemblyScript `Uint32Array` to JavaScript, let JS write to it, then have AS change it, and then JS read it back (think core hash/permutation algorithms).

But my problem is the offset is wrong by 32 bytes!  What am I missing?

```ts
// assembly/main.ts
export const state = new Uint32Array(12);

export function count(): void {
  for (let i = 0; i < 12; i++) {
    state[i] = i + 1;
  }
}
```

```js
// src/main.js
async function main() {
  const { instance: { exports } } = await WebAssembly.instantiateStreaming(fetch("../out/main.wasm"), {
    env: {
      abort(_msg, _file, line, column) {
        console.error("abort called at main.ts:" + line + ":" + column);
      }
    },
  });

  const statePtr = exports.state.value;
  console.log("statePtr", statePtr);

  const state = new Uint32Array(exports.memory.buffer, statePtr, 3 * 4);

  console.log(state);
  exports.count();
  console.log(state);
}
main().catch(console.error)
```

The output is clearly wrong.

```
statePtr,2064
2096,2096,48,0,48,1,0,48,0,0,0,0
2096,2096,48,0,48,1,0,48,1,2,3,4
```

But if I add `32` to the offset pointer...
```js
// src/main.js
...
  const statePtr = exports.state.value + 32
...
```
It works correctly.
```
statePtr,2096
0,0,0,0,0,0,0,0,0,0,0,0
1,2,3,4,5,6,7,8,9,10,11,12
```
Why do I need this 32 byte offset?  Is it always 32 bytes?

**Comment by MaxGraey** [comment]
See how loader read `Uint32Array` array: https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/index.js#L220

Also you could find additional information about memory layout in docs:
https://docs.assemblyscript.org/details/memory#arraybufferview-layout

**Comment by creationix** [comment]
Ahh thanks.  I didn't realize that typed arrays were represented with runtime headers in memory.
