### ISSUE TITLE
asc.compileString options

### ISSUE THREAD

**Issue by lastmjs** [AssemblyScript/assemblyscript#1019]
I was looking at the documentation here: https://docs.assemblyscript.org/details/compiler

It shows an example of passing options into the `compileString` function: 

```typescript
const { binary, text, stdout, stderr } = asc.compileString(`...`, { optimize: 2 })
```

This makes it seem like `compileString` takes a JavaScript object that resembles the command line parameters of `asc`, but when I look at the `compileString` TypeScript types, I see that the options look like this:

```typescript
/** Compiler API options. */
interface CompilerOptions {
  /** Standard output stream to use. */
  stdout?: OutputStream;
  /** Standard error stream to use. */
  stderr?: OutputStream;
  /** Reads a file from disk (or memory). */
  readFile?: (filename: string, baseDir: string) => string | null;
  /** Writes a file to disk (or memory). */
  writeFile?: (filename: string, contents: Uint8Array, baseDir: string) => void;
  /** Lists all files within a directory. */
  listFiles?: (dirname: string, baseDir: string) => string[] | null;
}

/** Convenience function that parses and compiles source strings directly. */
export function compileString(sources: { [key: string]: string } | string, options?: CompilerOptions): {
  /** Standard output. */
  stdout: OutputStream,
  /** Standard error. */
  stderr: OutputStream,
  /** Emitted binary. */
  binary: Uint8Array | null,
  /** Emitted text format. */
  text: string | null
}
```

And indeed passing `optimize: 2` in as a parameter breaks the Wasm compilation. So, I think the documentation needs to be updated, but also, I would love to see `compileString` able to take in the same options as on the command line so that I can have a fully programmatic `asc`. Thanks!

**Comment by willemneal** [comment]
[It is defined here](https://github.com/AssemblyScript/assemblyscript/blob/14ac21c2f6df8e07ad8b644033a5aebe77051c76/cli/asc.js#L99).  It's currently more of a simple way to compile small examples.  As you can see you cannot actually pass command line options.  Just checkout how it uses main and and then you change that to your needs.

However, I've been interested in creating a real REPL, which will improve this function for your needs.  You're welcome to create a PR that improves it, but otherwise it's a simple change to use the main function.

**Comment by lastmjs** [comment]
Ah, that is very helpful! The documentation here should be updated then, it seems incorrect: https://docs.assemblyscript.org/details/compiler

**Comment by dcodeIO** [comment]
Just noticed this has been closed. The information here is wrong, it's the type definitions that are incorrect.
