### ISSUE TITLE
asc.compileString imports

### ISSUE THREAD

**Issue by lastmjs** [AssemblyScript/assemblyscript#1020]
It doesn't seem like imports are supported in the `asc.compileString` function. It fails with `ERROR: Import file 'file-name.ts' not found.` It would be nice to support this with the native filesystem in Node.js, and I'm not sure how it would be handled in the browser. `compileString` could have a parameter to pass in the path to the file that all imports should be relative to.

**Comment by dcodeIO** [comment]
The recommended API to do more complex things than quickly compiling a string is `asc.main`. That's the full command line as an API, with access to stdout, stderr, options, and a virtual file system one can implement ([see](https://github.com/AssemblyScript/assemblyscript/blob/14ac21c2f6df8e07ad8b644033a5aebe77051c76/cli/asc.d.ts#L51)).

**Comment by lastmjs** [comment]
This is perfect! Thanks for the information, I think I have a good direction to move in now
