### ISSUE TITLE
Pushing to array initialized in the global scope causes runtime error

### ISSUE THREAD

**Issue by vladimir-tikhonov** [AssemblyScript/assemblyscript#1023]
Hi,

Here's the repo where you can easily reproduce this issue: https://github.com/vladimir-tikhonov/as-bug

The following code produces a runtime error:
``` typescript
const initializedArray: i32[] = [];

export function willFail(): void {
    initializedArray.push( 1 );
}
```

It seems to be related to arrays with combined declaration and initialization. For example, the following code works just fine:

``` typescript
let initializedArray: i32[] = [];
initializedArray = [];

export function willNotFail(): void {
    initializedArray.push( 1 );
}
```

**Comment by MaxGraey** [comment]
Btw you could use WebAssembly Studio for share reproduced bug:
https://webassembly.studio/?f=wqp77buhm5d

**Comment by vladimir-tikhonov** [comment]
@MaxGraey seems much easier, thanks!
