### ISSUE TITLE
which option is better?

### ISSUE THREAD

**Issue by blooddy** [AssemblyScript/assemblyscript#103]
```
export function test1(p:boolean):i32 {
  return p ? 1 : 0;
}
export function test2(p:boolean):i32 {
  return select<i32>( 1, 0, p );
}
```
compiled to
```
  (func $main/test1 (export "test1") (type $t0) (param $p0 i32) (result i32)
    get_local $p0
    i32.const 1
    i32.and
    if $I0 (result i32)
      i32.const 1
    else
      i32.const 0
    end
    return)
  (func $main/test2 (export "test2") (type $t0) (param $p0 i32) (result i32)
    i32.const 1
    i32.const 0
    get_local $p0
    i32.const 1
    i32.and
    select
    return)
  (memory $memory (export "memory") 1)
```
if the second option is better, then can it cost to put the appropriate optimization?

**Comment by dcodeIO** [comment]
I asked a similar question [here](https://github.com/WebAssembly/binaryen/issues/1355#issuecomment-356774311).

> the short answers are: if/br_if are expected to be faster than a two-way br_table, and select is expected to be faster than if/br_if when the inputs are cheap and the condition is "random" (making branch prediction ineffective).

**Comment by blooddy** [comment]
thx
