### ISSUE TITLE
RuntimeError in lib/rt/tlsf/allocateBlock

### ISSUE THREAD

**Issue by vladimir-tikhonov** [AssemblyScript/assemblyscript#1030]
Sorry for the convoluted code example, I'm having a hard time extracting this from a real project code. Seems like the amount / order of properties are important to reproduce this issue.

**Note**: this needs to be compiled using the latest master branch, which is b37cf1a77596c00dcdc79af03b3601ebd4d247f7 ATM, otherwise it will hit other issues

Link to the webassembly studio: https://webassembly.studio/?f=j9ldc9539e

Code:
```typescript
class A1 {
    private i32_0!: i32;
    private i32_1!: i32;
    private c1_0!: C1;
    private i32_2!: i32;
    private c1_1!: C1;
}

class A2 extends A1 { }

class B1 {
    private a1!: A1;
}

class C1 {
    private a2!: A2;
}

const poolB: B1[] = [];
const poolA: A2[] = [];
poolA.push( new A2() );
```

Stack trace:
```
Uncaught RuntimeError: unreachable
    at ~lib/rt/tlsf/allocateBlock
    at ~lib/rt/tlsf/reallocateBlock
    at ~lib/rt/tlsf/__realloc
    at ~lib/array/ensureSize
    at ~lib/array/Array<src/index/A2>#push
    at start:src/index
    at start
```

**Comment by MaxGraey** [comment]
Minimal example:
```ts
class A {
  a: i32 = 0
}
const arr: A[] = [];
arr.push(new A());
```

**Comment by vladimir-tikhonov** [comment]
@MaxGraey I believe that you are hitting the error fixed in #1025. This bug report is for the `master` branch, where you code example works just fine and my is still failing

**Comment by MaxGraey** [comment]
you're right

**Comment by dcodeIO** [comment]
Appears that this leads to a false `__alloc` of size 0 somehow that would otherwise be like 20 bytes, yet storing data there corrupting a block header. Very strange, perhaps a bug in class size calculation involving nesting.

**Comment by MaxGraey** [comment]
It still relate to `[]`. If use `new Array()` this issue disappears!

See modified fiddle (use latest nightly builds in setup.js):
https://webassembly.studio/?f=42q3dt2guyt

**Comment by dcodeIO** [comment]
I think this might as well be due to a slightly different memory layout that just so happens to produce no meaningful overwrite an assert would observe. My current guess is:

The additional recursive check obtains the existing instance if resolving the base class triggered it, instead of creating a new instance. But the instance is inserted into bookkeeping before its memory has been layed out and its final size is known, in turn leading to the zero size alloc being emitted. At least having a zero size alloc for something that actually has size is a strong indicator for that.

**Comment by vladimir-tikhonov** [comment]
@dcodeIO not sure if it helps, but in the original code there are no zero allocation as far as I can see (by checking all `$~lib/rt/tlsf/__alloc` calls in the `.wat` file), and it still crashes with the same exception. There are plenty of calls with a `id` being zero though, not sure if it's ok or not

**Comment by dcodeIO** [comment]
> There are plenty of calls with a id being zero though, not sure if it's ok or not

That's fine, ArrayBuffer has id 0.

> not sure if it helps, but in the original code there are no zero allocation as far as I can see

Might well be that the `A2` counterpart in the original code has own fields, so that wouldn't be zero but the size of `A2` without the size of the `A1` counterpart. Just a guess.
