### ISSUE TITLE
Arithmetic expressions produce "unexpected" results because of wrapping

### ISSUE THREAD

**Issue by magcius** [AssemblyScript/assemblyscript#104]
I was porting some code from another project, and came across this peculiarity.

```typescript
function avg(a: u8, b: u8): u8 {
    return (a + b) >>> 1;
}
```

This, to me, looks like it should be correct, however, the `(a + b)` happens in a wrapping context, so e.g. `<u8>0x9a + <u8>0xa0` produces an intermediate result of `0x3a`, not `0x13a`. This is unexpected to me, and caused me a bug that took me quite a while to find.

This can be worked around by casting the intermediate expression to u32:

```typescript
function avg(a: u8, b: u8): u8 {
    let tmp: u32 = a + b;
    return tmp >>> 1;
}
```

However it's quite a bit clunkier, and initially unobvious. Consider adding some sort of arithmetic promotion rules, perhaps inspired by C's.

**Comment by MaxGraey** [comment]
This is normal behaviour. For example `Rust` generate exactly the same output:
```wat
(func $avg (export "avg") (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    get_local $p1
    get_local $p0
    i32.add
    i32.const 255
    i32.and
    i32.const 1
    i32.shr_u)
```
By the way this affect also for `i32 / u32`. For avoid `a + b` overflowing during average we have got several approaches:

```ts
var avg = a + ((b - a) >>> 1);
```
or
```ts
var avg = (a >>> 1) + (b >>> 1) + (a & b & 1);
```
or
```ts
var avg = (b & a) + ((b ^ a) >>> 1);
```

**Comment by dcodeIO** [comment]
For reference, in C

```c
typedef unsigned char u8;

WASM_EXPORT
u8 avg(u8 a, u8 b) {
    return (a + b) >> 1;
}
```

```wat
(func $avg (export "avg") (type $t1) (param $p0 i32) (param $p1 i32) (result i32)
  get_local $p1
  get_local $p0
  i32.add
  i32.const 1
  i32.shr_u)
```

**Comment by MaxGraey** [comment]
This little bit strange, because for int32 we should use the same tricks: https://stackoverflow.com/questions/3816446/how-can-i-safely-average-two-unsigned-ints-in-c

**Comment by MaxGraey** [comment]
What if average function would be generic?

```ts
function avg<T>(a: T, b: T): T {
    return (a + b) / 2;
}
```
will be wrong for big u32 / u64, but this should works for any case and arithmetic types:
```ts
function avg<T>(a: T, b: T): T {
    return a + (b - a) / 2;
}
```

**Comment by dcodeIO** [comment]
> What if average function would be generic?

That's a good point.

My impression so far is that not having integer promotion is more consistent and predictable for someone without a strong background in C. Does this integer promotion thing exist for performance reasons in the first place, or why is C doing it?

**Comment by MaxGraey** [comment]
I tend to trust Rust more in this case as a more type-safed language.

**Comment by MaxGraey** [comment]
By the way this integer promotion can cause to Vulnerabilities, see `Related Vulnerabilities` in this [doc](https://wiki.sei.cmu.edu/confluence/display/c/INT02-C.+Understand+integer+conversion+rules)

**Comment by magcius** [comment]
Yes, I put "unexpected" in quotes because it was unexpected to me, not because it's necessarily wrong or a bug. I just found the language design confusing, and it hit me three separate times in my port.

If I were to design a language, I would promote intermediates arithmetic to precision high enough for the expression, and either wrap or do an overflow check on assignment. So u8+u8 = u9, (next highest is u16).

But that's just my personal taste. I'm sure if I was coming from Rust, their behavior would make sense. There seems to be [a thread about possibly changing that behavior](https://internals.rust-lang.org/t/implicit-widening-polymorphic-indexing-and-similar-ideas/1141/65) (but fairly old and dead, and without consensus).

Here are the other real-world examples that came :

```typescript
function s3tcblend(a: u32, b: u32): u8 {
    // 3/8*a + 5/8*b
    return (((a << 1) + a) + ((b << 2) + b)) >>> 3;
}
```

```typescript
let windowLength: u16 = ((bits >> 12) + 2) & 0xFF;
if (windowLength == 2) {
    let extra: u8 = fetchExtra();
    windowLength += extra + 0x10;
}
```

**Comment by MaxGraey** [comment]
Ok, let's look to `bool` to `int` conversion.
In C/C++ this going implicitly:
> If the source type is bool, the value false is converted to zero and the value true is converted to one.
In JavaScript/TypeScript `boolean` to `number` conversion strongly require explicit cast.

In my opinion if propagate this behaviour to other small types not only `boolean` we need same explicit casts for all these small types as well.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Please create a new issue if the improvements we made meanwhile aren't yet sufficient.
