### ISSUE TITLE
How to override typeRoots and types?

### ISSUE THREAD

**Issue by webmaster128** [AssemblyScript/assemblyscript#1064]
TypeScript supports setting `typeRoots` and `types` [as command line flags](https://www.typescriptlang.org/docs/handbook/compiler-options.html) and [in tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types). I want to utilize this to tell my AssemblyScript program that an import will exist globally at `env.log` with the following declaration:

```ts
declare const env: {
  readonly log: (messagePtr: usize) => void
};
```

This is the setup I'd use with TypeScript and it already works to make the language server in VSCode happy:

```sh
mkdir as-custom-env && cd as-custom-env
npm init --yes
npm install --save-dev assemblyscript asinit
npm run asinit .
npm run asbuild # all good
mkdir -p types/myenv
echo 'declare const env: { readonly log: (messagePtr: usize) => void };' > types/myenv/index.d.ts
jq '.compilerOptions = { typeRoots: ["../node_modules/assemblyscript/std/types", "../types"], types: ["assembly", "myenv"]}' < assembly/tsconfig.json > assembly/mytsconfig.json
mv assembly/mytsconfig.json assembly/tsconfig.json
echo "\n\nenv.log(0);" >> assembly/index.ts
npm run asbuild # cannot find env
```

However, it looks like `asc` does not read `typeRoots`/`types` from `tsconfig.json`:

```
// ...
> as-custom-env@1.0.0 asbuild:untouched /Users/simon/opensource/as-custom-env
> asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug

ERROR TS2304: Cannot find name 'env'.

 env.log(0);
 ~~~
 in assembly/index.ts(7,0)

ERROR: Compile error
// ...
```

I suspect that `asc` is not reading `tsconfig.json` at all and we only maintain it for the IDE. Do I understand that correctly?

What would be the process to add custom global types to the compiler?

**Comment by dcodeIO** [comment]
The recommended way to do this in AS is to import the file with the ambient declaration, since the AS compiler also has to compile the import so it becomes part of the binary (not just type checking):

```ts
// myenv.ts
export declare namespace env {
  export log(messagePtr: usize): void;
};
```

```ts
// index.ts
import { env } from "./myenv.ts";
env.log(...);
```

**Comment by webmaster128** [comment]
Thanks for the quick reply!

The first version fails because of

> LinkError([ImportNotFound { namespace: "myenv", name: "env.log" }]

The second version works.

**Comment by dcodeIO** [comment]
Ah, right, the import naming of the first version changed a while ago. It's now always

`filenameWithoutTs ('.' namespaceIfAny)* '.' element`
