### ISSUE TITLE
Can't override abort

### ISSUE THREAD

**Issue by webmaster128** [AssemblyScript/assemblyscript#1065]
I want to [override abort as documented](https://docs.assemblyscript.org/details/debugging#overriding-abort). My implementation is

```
// in index.ts

export function logAndCrash(
  message: string | null,
  fileName: string | null,
  lineNumber: u32,
  columnNumber: u32,
): void {
  const msg = `Aborted with message '${message}' (in '${fileName}', line ${lineNumber}, column ${columnNumber})`;
  log(msg);
  unreachable(); // crash hard
}
```

and I compile with `--use abort=index/logAndCrash`. Unfortunately, the symbol is not found:

```
$ yarn build:untouched
yarn run v1.21.1
$ asc src/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --runtime stub --use abort=index/logAndCrash --validate --debug
ERROR: no such global element: index/logAndCrash
    at T.initialize (/project/node_modules/assemblyscript/dist/assemblyscript.js:1:46033)
    at m.compile (/project/node_modules/assemblyscript/dist/assemblyscript.js:1:208472)
```

Am I missing something here? Are the docs outdted?

**Comment by dcodeIO** [comment]
If your entry point is `assembly/index.ts`, the global name of the function is `assembly/index/logAndCrash`. Also note that template literals are not yet supported.

**Comment by webmaster128** [comment]
> If your entry point is src/index.ts, the global name of the function is src/index/logAndCrash. 

Ah, perfect, thanks. I think a typical prefix like `src/index/myAbort` or `assembly/index/myAbort` in the docs would have made that clear.

> Also note that template literals are not yet supported.

Thanks! It compiles but the substitution is not performed. Will implement differently.
