### ISSUE TITLE
Uint8Array.wrap throws "Index out of range" for length 0

### ISSUE THREAD

**Issue by webmaster128** [AssemblyScript/assemblyscript#1066]
When I call `Uint8Array.wrap(buffer, 0, 0)` on a buffer of length 0, I get an "Index out of range" error. For Other sizes this works as expected.

If I understand correctly, this code is buggy: https://github.com/AssemblyScript/assemblyscript/blob/v0.8.1/std/assembly/typedarray.ts#L1694-L1696.

**Comment by webmaster128** [comment]
This was fixed in #1067 (and #1070?) on current master, right? Should it be closed?

**Comment by MaxGraey** [comment]
It should be in `0.9` already. So you could check how this work and close if everything right

**Comment by webmaster128** [comment]
Fixed in 0.9.0. Thanks!
