### ISSUE TITLE
Custom exports limited to 5 since 0.9.0?

### ISSUE THREAD

**Issue by webmaster128** [AssemblyScript/assemblyscript#1078]
Using assemblyscript 0.8.1 my wasm has the exports

```json
[
  "__alloc",
  "__retain",
  "__release",
  "__collect",
  "init",
  "handle",
  "deallocate",
  "allocate",
  "query",
  "cosmwasm_api_0_6"
]
``` 

and after upgrading to 0.9.0 the list changed to 

```json
[
  "__alloc",
  "__retain",
  "__release",
  "__collect",
  "__reset",
  "init",
  "handle",
  "deallocate",
  "allocate",
  "query"
]
```

The order in this list is the same as in my `src/index.ts` and I can change the included exports by changing the order of the functions in `src/index.ts`.

Did the new `__reset` kick out my last custom export? Is it possible to increase the number of exports?

**Comment by dcodeIO** [comment]
Exports shouldn't kick each other out, no. Can you provide a reproducible example for me to investigate?

**Comment by MaxGraey** [comment]
@webmaster128 could you provide example? I tried this simplified example and "cosmwasm_api_0_6" still present for `--runtime full`:
https://webassembly.studio/?f=iepfmde4p1s

and `--runtime stub`:
https://webassembly.studio/?f=vlzcddsyv2b

**Comment by webmaster128** [comment]
After @dcodeIO's message I realized that the missing export is part of the .wat:

```
 (export "__argumentsLength" (global $~argumentsLength))
 (export "memory" (memory $0))
 (export "__alloc" (func $~lib/rt/stub/__alloc))
 (export "__retain" (func $~lib/rt/stub/__retain))
 (export "__release" (func $~lib/rt/stub/__release))
 (export "__collect" (func $~lib/rt/stub/__collect))
 (export "__reset" (func $~lib/rt/stub/__reset))
 (export "__rtti_base" (global $~lib/rt/__rtti_base))
 (export "init" (func $src/index/init))
 (export "handle" (func $src/index/handle))
 (export "query" (func $src/index/query))
 (export "cosmwasm_api_0_6" (func $src/index/cosmwasm_api_0_6))
 (export "allocate" (func $src/cosmwasm/allocate))
 (export "deallocate" (func $src/cosmwasm/deallocate))
```

Thus I now assume the missing symbol(s) are droped by Wasmer. So most likely, this was a false alarm, sorry! I'll investigate more and either come up with a reproducible example or close.

**Comment by webmaster128** [comment]
This is most likely some kind of bug in [wasm-nm](https://github.com/fitzgen/wasm-nm), which builds on a [very old version of parity-wasm from January 2018](https://github.com/paritytech/parity-wasm/tree/19494e9e4ff7a4106666febd5b0c10948a94f2e3). Cannot reproduce yet.

**wasm-nm**

```
$ ~/.cargo/bin/wasm-nm -e build/untouched.wasm 
e __alloc
e __retain
e __release
e __collect
e __reset
e init
e handle
e deallocate
e allocate
e query
```

**wasm-objdump**

```
$ wasm-objdump -j export -x build/untouched.wasm

untouched.wasm: file format wasm 0x1

Section Details:

Export[14]:
 - global[16] -> "__argumentsLength"
 - memory[0] -> "memory"
 - func[3] <~lib/rt/stub/__alloc> -> "__alloc"
 - func[4] <~lib/rt/stub/__retain> -> "__retain"
 - func[5] <~lib/rt/stub/__release> -> "__release"
 - func[6] <~lib/rt/stub/__collect> -> "__collect"
 - func[7] <~lib/rt/stub/__reset> -> "__reset"
 - global[18] -> "__rtti_base"
 - func[36] <src/index/init> -> "init"
 - func[37] <src/index/handle> -> "handle"
 - func[171] <src/index/query> -> "query"
 - func[172] <src/index/cosmwasm_api_0_6> -> "cosmwasm_api_0_6"
 - func[132] <src/cosmwasm/allocate> -> "allocate"
 - func[39] <src/cosmwasm/deallocate> -> "deallocate"
```
