### ISSUE TITLE
hh

### ISSUE THREAD

**Issue by suanlebanislbn** [AssemblyScript/assemblyscript#109]
# 本月要做的任务
- [ ] 完成图片
- [x] 完成部署工具的设置
- [ ] 实现抽签功能

**Comment by jiyinyiyong** [comment]
Spam?

**Comment by Eeems** [comment]
Seems to be spam to me: ![screenshot](https://screenshots.firefoxusercontent.com/images/691e2727-c231-40a5-9ba5-c88a8a968428.png)

**Comment by jiyinyiyong** [comment]
should close the issue now...

**Comment by jiyinyiyong** [comment]
any updates on AssemblyScript in the past month by the way?

**Comment by jiyinyiyong** [comment]
any updates on AssemblyScript in the past month by the way?

**Comment by dcodeIO** [comment]
Sure: [NEXT](https://github.com/AssemblyScript/next).
