### ISSUE TITLE
Compiler emits import statement with wrong WASI module name

### ISSUE THREAD

**Issue by mhonert** [AssemblyScript/assemblyscript#1098]
When using the WASI bindings, the compiler currently emits import statements for "wasi_snapshot" instead of "wasi_snapshot_preview1".

This makes it incompatible with WebAssembly runtimes that support WASI (e.g. [wasmer](https://github.com/wasmerio/wasmer/) or [WAVM](https://github.com/WAVM/WAVM)).

AssemblyScript version: 0.9.1

**Comment by MaxGraey** [comment]
This should be fixed and landed in v0.9.1-nightly.20200210. You could give it a try

**Comment by mhonert** [comment]
Yes, it works now in wasmer and WAVM.
Thanks for the quick fix!
