### ISSUE TITLE
tlsf memory allocator throws runtime exception when wasm file gets loaded

### ISSUE THREAD

**Issue by Tarnadas** [AssemblyScript/assemblyscript#110]
When importing `allocator/tlsf` and loading the compiled WASM file via `const wasmModule = await WebAssembly.instantiateStreaming(fetch(...))`, I get the following runtime error:

```
AppView.tsx:22 Uncaught (in promise) LinkError: WebAssembly Instantiation: Import #0 module="env" function="abort" error: function import requires a callable
```

My .ts file only looks like this:
```
import 'allocator/tlsf';

class Test {}
```

Using another memory allocator like arena and buddy doesn't throw the error.

**Comment by dcodeIO** [comment]
There are a couple assertions in TLSF that call the imported `env.abort` function on failure. The function looks like this:

```js
function abort(msg, file, line, column) {
  ...
}
```

Importing it as part of the imports object will prevent the error, as will compiling with `--noAssert` so it doesn't become imported.

**Comment by dcodeIO** [comment]
> I did not quite understand why abort is called here

It is not called actually, but because it might be called potentially (and thus abort being imported), the function must be present on the import object.

**Comment by Tarnadas** [comment]
Ok, thanks for the explanation. This can be closed
