### ISSUE TITLE
getDependee can't resolve path with numbers

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#1100]
For example `bindings/wasi_snapshot_preview1.ts` cause to this error:
```
Error: Import file '~lib/bindings/wasi_snapshot_preview1.ts' not found.
      at parseBacklog (....../assemblyscript/cli/asc.js:482:34)
      at Object.main (....../assemblyscript/cli/asc.js:535:16)
```
But if rename it to `bindings/wasi_snapshot_preview.ts` issue is gone.
Relate to #1099

**Comment by dcodeIO** [comment]
Seems the issue is [here](https://github.com/AssemblyScript/assemblyscript/blob/master/cli/util/find.js#L19). That should be something more along the lines of

```ts
exports.TS_EXCEPT_DTS = /((?!\.d).{2}|^.{0,1})\.ts$/;
```

**Comment by MaxGraey** [comment]
Thanks! Seems proposed `TS_EXCEPT_DTS` fixed issue
