### ISSUE TITLE
[bug?] instanceof check with Set using indexof fails 

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#1105]
Given a type `T` of any kind, the following lines of code yield a compiler error that points to `~lib/set.ts`

```ts
function example<T>(ref: T): void {
  if (ref instanceof Set<indexof<T>>) {  // problem here

  }
}
```

```
ERROR TS2304: Cannot find name 'T'.

       if (ref instanceof Set<indexof<T>>)  {
                                      ~
 in assembly/internal/Reflect.ts(61,38)

**Comment by jtenner** [comment]
Ideally, because types can be inferred really well, I could settle for an `isSet<T>()` and `isMap<T>()` builtin to perform comparisons.

**Comment by dcodeIO** [comment]
Looks like the resolver doesn't pick up contextual types properly there. So, yeah, seems like a bug.

**Comment by jtenner** [comment]
```
ERROR TS2329: Index signature is missing in type 'assembly/__tests__/setup/Vec3/Vec3'.

       if (left instanceof Set<indexof<T>>) {
                                       ~
 in assembly/internal/Reflect.ts(61,38)
```

Now, the `T` when it's a `Set<Vec3>` works  properly. The issue is that at some point, `T` becomes `Vec3`, and it has no index signature and it bombs out.

Options That don't work:

1. `instanceof Set<indexof<T>>` fails because it's possible T might not have an index signature
2. `instanceof Set` fails because it lacks a generic parameter
3. Runtime check for `idof<Set<indexof<T>>>` which fails for the same reason as number 1

Once again `isSet<T>()` and `isMap<T>()` would be incredibly helpful in this case, because then I can garuntee the Map or Set prototype is in the prototype chain and perform a strict equals check. In the case of using the `indexof<T>` primitive, it appears I can't do anything about it.

**Comment by MaxGraey** [comment]
But `Vec3` I guess really hasn't index signature. So probably makes sense at first check `isArray<T>()` and after that only check `left instanceof Set<indexof<T>>`. As @dcodeIO mentioned in Slack instead `isSet<T>/isMap<T>` better has `a instanceof Set` and `a instanceof Map`

**Comment by jtenner** [comment]
```
     if (isArray<T>()) {
        // set match
        if (left instanceof Set<indexof<T>>) {
           WARNING("Compiled to this point");
```

This is not a working solution.

**Comment by jtenner** [comment]
`instanceof Set` is more TypeScript-y.

If you want to be consistent in philosophy, we should remove `isArray()` for `instanceof Array` without generic parameters.

**Comment by jtenner** [comment]
The fourth option is to use

```ts
if (isDefined(val[0]) { // will safely evaluate an expression to make sure it's "defined"
   if (val instanceof Set<indexof<T>>) {}
}
