### ISSUE TITLE
__retain() quietly reuses previously alloc'd memory

### ISSUE THREAD

**Issue by monktastic** [AssemblyScript/assemblyscript#1114]
I had written something like this in my .js:

```
# (N is a fairly large int)
var ptrArr1 = module.__retain(module.__allocArray(module.FLOAT32ARRAY, new Float32Array(N));
const arr1 = module.__getFloat32ArrayView(ptrArr1);
# ... do stuff with arr1

var ptrArr2 = module.__retain(module.__allocArray(module.FLOAT32ARRAY, new Float32Array(N));
```

After the second `__retain`, `arr1` became invalid (though I don't remember the exactly error). It took a lot of debugging to discover that the problem was not enough memory allocated to my module (which I fixed with `memory.grow()`).

**Comment by MaxGraey** [comment]
Yes `module.__getFloat32ArrayView` is unsafe. You should use `__getFloat32Array` or mediately use/copy data of `ptrArr1` before next allocataion/release

**Comment by monktastic** [comment]
Thanks. I'm using `view` because it's a large array that I'm repeatedly operating on, so copying is infeasible. Is there a safe(r?) way to share memory?

**Comment by MaxGraey** [comment]
As I mentioned before you could use `__getFloat32ArrayView` which not use copy internally but you should immediately use it like put in Image data, process it and do something else before next touch of wasm memory (which implicitly do via __alloc / __allocArray, __release or another call of function from wasm).

**Comment by monktastic** [comment]
So if I keep `ptrArr1` around and call `...View` before each use, that should be okay (and quick)?

**Comment by MaxGraey** [comment]
```ts
const arr1 = module.__getFloat32ArrayView(ptrArr1);
   ... do something with arr1...
module.__release(arr1);
// now arr1 not used anymore

v
const arr2 = module.__getFloat32ArrayView(ptrArr1);
   ...do something with arr2...
module.__release(arr2);
... 
```

Otherwise
```ts
var ptrArr1 = module.__retain(module.__allocArray(....));
...
const arr1 = module.__getFloat32Array(ptrArr1);
...
var ptrArr2 = module.__retain(module.__allocArray(....));
...
const arr2 = module.__getFloat32Array(ptrArr2);

... process with arr1 and arr2...

module.__release(arr2);
module.__release(arr1);
```

**Comment by monktastic** [comment]
Okay, so I'm doing this:
```
    module.colorShift(shift, imgPtr, hsvsPtr);
    const imgAry = module.__getFloat32ArrayView(imgPtr);
    imgData.data.set(imgAry);
    ctx.putImageData(imgData, 0, 0);
    module.__release(imgAry);
```

Repeatedly, as quickly as possible. It is incredibly slow, and getting slower on each iteration. Did you mean to have this in your last comment?
```
const arr2 = module.__getFloat32ArrayView(ptrArr1);
```

It looks like you're reusing `ptrArr1`, which is what I want because I certainly can't alloc new memory on each iteration. If it's a typo and you meant it to be a view on `ptrArr2`, then this doesn't match my use case. I want to alloc once and repeatedly use that memory in both AS and JS.

**Comment by MaxGraey** [comment]
Much faster approach don't alloc array on wasm side at all. See this example how do this in better way: https://github.com/jtiscione/webassembly-wave/tree/master/as

Demo: https://jtiscione.github.io/webassembly-wave/index.html

**Comment by monktastic** [comment]
Okay, thanks! I will check that out.

In the mean time, do you see anything wrong with my code above? Why is it getting slower on each iteration? Am I leaking memory somewhere?

**Comment by MaxGraey** [comment]
Without see full source of code I can't figure out what's happening but my assumption you are forgot release `hsvsPtr` or you don't use `-O3` opt flag

**Comment by dcodeIO** [comment]
The problem there might be that the second `__alloc` leads to the module automatically growing its memory, in which case the backing buffer of the old memory becomes "detached", invalidating any previous views. Quite an unfortunate mechanism. Could that be it?

**Comment by monktastic** [comment]
@MaxGraey I only create one view on `hsvsPtr` and release it before this loop. I'm using `optimized.wasm`. Not using `-O3` might explain why it's slow, but not why it's getting _slower_ on each iteration, right?

**Comment by monktastic** [comment]
@dcodeIO Yes, thanks, that would explain it. Now that I'm grabbing the view on each iteration, I'm not sure what the problem is.

**Comment by monktastic** [comment]
(I'm also not sure _why_ I would need to grab and release it on each iteration now that I'm not alloc'ing anything new. I'm just trying it on Max's suggestion.)

**Comment by dcodeIO** [comment]
I think in the example above it's `ptrArr1/2` that need to be released, once the views aren't needed anymore. Essentially tells the Wasm side that there's still an external reference, and once that's released, the Wasm module can collect it if there is no reference to the array inside Wasm anymore.

**Comment by monktastic** [comment]
@dcodeIO Thanks, that makes sense. With that in mind, I've changed my code so that I fetch both `imgAry` and `hsvsAry` just once (after everything has been alloc'd), simplifying my "loop" (repeated event) to:
```
    module.colorShift(shift, imgPtr, hsvsPtr);
    imgData.data.set(imgAry);
    ctx.putImageData(imgData, 0, 0);
```
It's still slowing down monotonically over at least the first thousand iterations, and is never faster than the pure JS version (even with `-O3`). Do either of those make sense to you?

**Comment by monktastic** [comment]
@dcodeIO I'm an idiot, I think I see the leak in my AS. Let me fix that....

**Comment by monktastic** [comment]
0.9.2 has reference counting, right? I shouldn't have to explicitly free a `new`ed Array in my AS?

**Comment by dcodeIO** [comment]
The AS side does reference counting automatically, yeah, but when a reference leaves to the JS side, external code has to do manual reference counting. Typical slowdowns here can be are that the memory is continuously growing, leading to some overhead (would explain why it becomes slower with memory becoming larger), and that GC is part of the single main thread in AS, whereas a JS engine can do GC in parallel threads, or even not all and just free everything once the program ends.

**Comment by monktastic** [comment]
@dcodeIO I don't alloc any memory in my loop on the JS side, and have now removed all allocs on the AS side. So there should be neither memory growth nor GC overhead. There may still be some reasons why the wasm version is slower, but the fact that it's consistently slowing down over time seems to suggest a leak or other bug, right?

My AS code isn't very interesting, but here it is for reference:
```
export const FLOAT32ARRAY = idof<Float32Array>();
var rgbAry: Array<f32> = new Array<f32>(3);

export function colorShift(shift: f32, data: Float32Array, hsvs: Float32Array): void {
  var h: f32, s: f32, v: f32;

  for (var i:i32 = 0; i < hsvs.length/3; i++) {
    h = hsvs[3*i];
    s = hsvs[3*i+1];
    v = hsvs[3*i+2];

    h = (h + shift) % 1;
    hsv2rgb(h, s, v, rgbAry);

    data[4*i+0] = rgbAry[0];
    data[4*i+1] = rgbAry[1];
    data[4*i+2] = rgbAry[2];
    data[4*i+3] = 255.0;
  }  
}

export function hsv2rgb(h: f32, s: f32, v: f32, ret: Array<f32>): void {
  var r: f32;
  var g: f32;
  var b: f32;

  var i: f32 = NativeMathf.floor(h * 6);
  var f: f32 = h * 6 - i;
  var p = v * (1 - s);
  var q = v * (1 - f * s);
  var t = v * (1 - (1 - f) * s);

  switch (<i32>i % 6) {
    case 0: r = v, g = t, b = p; break;
    case 1: r = q, g = v, b = p; break;
    case 2: r = p, g = v, b = t; break;
    case 3: r = p, g = q, b = v; break;
    case 4: r = t, g = p, b = v; break;
    case 5: r = v, g = p, b = q; break;
  }

  ret[0] = r * 255;
  ret[1] = g * 255;
  ret[2] = b * 255;
}
```

**Comment by MaxGraey** [comment]
You could speed-up you code. It's still not optimal but should be little faster

```ts

var R: f32 = 0;
var G: f32 = 0;
var B: f32 = 0;

export function colorShift(shift: f32, data: Uint8Array, hsvs: Float32Array): void {
  var h: f32, s: f32, v: f32;
  for (let i = 0, len = hsvs.length / 3; i < len; i++) {
    h = unchecked(hsvs[3 * i + 0]);
    s = unchecked(hsvs[3 * i + 1]);
    v = unchecked(hsvs[3 * i + 2]);

    h = Mathf.min(1, Mathf.max(0, h + shift));
    hsv2rgb(h, s, v);

    unchecked(data[4 * i + 0] = <u8>(R * 255));
    unchecked(data[4 * i + 1] = <u8>(G * 255));
    unchecked(data[4 * i + 2] = <u8>(B * 255));
    unchecked(data[4 * i + 3] = 255);
  }  
}

@inline
function hsv2rgb(h: f32, s: f32, v: f32): void {
  var i = <u32>Mathf.floor(h * 6);
  var f: f32 = h * 6 - i;
  var p = v * (1 - s);
  var q = v * (1 - f * s);
  var t = v * (1 - (1 - f) * s);

  switch (i % 6) {
    case 0: R = v, G = t, B = p; break;
    case 1: R = q, G = v, B = p; break;
    case 2: R = p, G = v, B = t; break;
    case 3: R = p, G = q, B = v; break;
    case 4: R = t, G = p, B = v; break;
    case 5: R = v, G = p, B = q; break;
  }
}
```

**Comment by dcodeIO** [comment]
One way to check if memory is still growing for some reason, which might happen if something isn't released correctly on the JS side, can be to check if `module.memory.buffer.byteLength` changes. If that doesn't happen and it's still slowing down, that's be very strange.

**Comment by MaxGraey** [comment]
Also you shouldn't alloc and destroy arrays in each frame. Just do this once and watch is canvas size changes and reallocate arrays only in this case.

**Comment by monktastic** [comment]
@MaxGraey Thanks, I'll try those optimizations.
@dcodeIO I did think to check that, and confirmed that `byteLength` is not changing. The _only_ difference between the AS and JS versions is the call to `colorShift`. The JS version of that function is fundamentally identical.

If you'd like, I can try to create a repo for you to repro (though you can probably create a simple case yourself even quicker).

**Comment by monktastic** [comment]
I'm not sure if this is new functionality (since this issue was last open), but the answer now seems to be to use `WebAssembly.Memory` (e.g., as demonstrated here: https://github.com/AssemblyScript/examples/blob/main/game-of-life/index.html).
