### ISSUE TITLE
How to support function callback and Polymorphism

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#113]
As the wasm spec supported the table,  does the assemblyscript support Polymorphism or function callback?

**Comment by LiaoPeng** [comment]
@MaxGraey Thanks for your replay.  I tested that function supported. 
`class Base{

	constructor() { };

	say():void{
		prints("Base say");
	}
}

class Concrete extends Base {
	constructor(){
	}
	say():void {
		prints("Concrete say");
	}
}

function saySomething(base: Base) :void{
	base.say();
}

export function say():void{
	saySomething(new Base());
	saySomething(new Concrete());
}`

That's my code, I compile it to wast and run wasm vm. I got the result "Base sayBase say".
It seem that it's not supporting Polymorphism.

**Comment by MaxGraey** [comment]
@LiaoPeng Yah, some inheritance stuffs still not complete.

**Comment by dcodeIO** [comment]
This should work:

```ts
function saySomething<T>(base: T) :void{
  base.say();
}
```

**Comment by LiaoPeng** [comment]
@MaxGraey @dcodeIO  Thanks for your reply.  @dcodeIO  The generic method works fine.
But I still have a issue to construct the super class. 
```
class Base {
	age: u32;
	constructor(age: u32) { this.age = age; };
	say(): void {
		Log.s("Base say").flush();
	}
}


class Concrete extends Base {
	constructor(age: u32){
		super(age);
	}
	say():void {
		Log.s("Concrete say").flush();
	}
}

function saySomething<T>(base: T): void {
	base.say();
}
@action
export function say():void{
	let age = 32;
	saySomething(new Concrete(age));
}
```
It hits that:
```
ERROR AS100: Operation not supported.

 		super(age);
   ~~~~~~~~~~

```

**Comment by Tarnadas** [comment]
Could you tell us how you resolved your issue?
I have the same problem with class inheritance and super() calls.

Here's a workaround I found:

```js
class A {
  protected attr: u32;
  constructor(attr: u32) {
    this.attr = attr;
  }
}

class B extends A {
  constructor(attr: u32) {
    // super(attr); fails with 'ERROR AS100: Operation not supported.'
    this.attr = attr; // workaround. This gives a TS error, since it wouldn't be valid TypeScript, but it compiles with the AssemblyScript compiler
  }
}
```

**Comment by MaxGraey** [comment]
As I know @dcodeIO currently hard work on this feature.
