### ISSUE TITLE
Investigate randomly failing non-null checks

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#1139]
While working on #1129 I noticed that flows and/or assignments do sometimes not correctly pick up non-null state after assigning to a local from a function call in a conditional branch:

```ts
      if (tn.skip(Token.COLON)) {
        type = this.parseType(tn);
        if (!type) return null;
      } else {
        type = Node.createOmittedType(tn.range(tn.pos)); // returns non-null
        type = type!; // FIXME: WHY?
      }
      // otherwise type is considered nullable here leading to follow-up errors
     someFuncWantingNonNullable(type); // cannot assign Type | null to Type
```

There are 8 code locations in the compiler currently with that `FIXME: WHY?` comment that all look similar, but I didn't yet manage to reproduce this in a smaller code sample. If someone else manages to, that would be super helpful :)

**Comment by jtenner** [comment]
```ts
class Ref {
}

let result: Ref | null = null;

function test(input: bool): void {
  if (input) {
    return;
  } else {
    result = new Ref();
  }
  func(result);
}

function func(input: Ref): void {
  trace("something", 1, <f64>changetype<usize>(input));
}

test(false);
```

Not exactly minimal, and it probably could be better, but this seems to get the compiler error.

**Comment by dcodeIO** [comment]
This one seems different, being caused by `result` being a global, which flows don't yet null-check.

**Comment by jtenner** [comment]
Got it!

```ts
class Ref {
}

function useRef(aRef: Ref): void {}

class ExampleClass {
  member(conditional: bool): void {
    let something: Ref | null;
    if (conditional) {
      return;
    } else {
      something = new Ref();
    }
    useRef(something);
  }
}

{
  let a = new ExampleClass();
  a.member(true);
}
```

**Comment by dcodeIO** [comment]
This one is interesting, but unlike the cases in the compiler can't be solved with a `something = something!` right after the assignment. Strange, might be another bug.
