### ISSUE TITLE
Better handle keywords used as variable names

### ISSUE THREAD

**Issue by alangpierce** [AssemblyScript/assemblyscript#115]
Here are two abbreviated code snippets from my codebase that are valid TypeScript but crash the compiler:

This code:
```typescript
function tsParsePropertyOrMethodSignature(readonly: boolean): void {
}
```
gives this error:
```
ERROR TS1042: 'readonly' modifier cannot be used here.

 function tsParsePropertyOrMethodSignature(readonly: boolean): void {
                                           ~~~~~~~~
```
and this code:
```typescript
  let type = code === charCodes.asterisk ? tt.star : tt.modulo;
  if (code === charCodes.asterisk && nextChar === charCodes.asterisk) {
    type = tt.exponent;
  }
```
gives this error:
```
ERROR TS1003: Identifier expected.

     type = tt.exponent;
     ~~~~
```

Both `readonly` and `type` (and plenty of others) have special meaning in TypeScript but are also valid variable names. Note that the AS compiler is ok with the declaration of a variable called `type`, and only fails later when parsing an assignment statement.

Looking at the the TS parser implementation (and from my experience with other parsers), you end up needing a lot of complexity to handle these cases. In the first case, when you're parsing parameters and see `readonly`, you need to look ahead to distinguish between `readonly` as a variable and `readonly` as a modifier. In the second case, when you're at the start of a statement and see `type`, you need to look ahead to determine whether it's an assignment to a variable named `type` or the start of a type declaration. The worst one I've seen is the arbitrary lookahead required to distinguish an async arrow function from a function call when seeing the tokens `async (a, b, c ...`.

Given that AssemblyScript is a subset of TypeScript and porting TypeScript to AssemblyScript already requires real effort, I think it may make sense to explicitly disallow these variable names for the sake of parser simplicity, at least for now. In that case, the parser should be changed to treat all of these TypeScript keywords as regular reserved words so that they're caught earlier with more useful error messages. Another option is to add the stricter checking to the TSLint plugin.

Another option is to fix these cases as needed, although in my case it's pretty easy to just rename these variables, so I don't need either of these two cases fixed.

**Comment by dcodeIO** [comment]
The latest commit should fix these two occasions (I think). To me it seems that fixing these as needed could actually work, because `type` and `readonly` for example are exactly one of the cases in their respective checks.

**Comment by MaxGraey** [comment]
It seems this could be close
