### ISSUE TITLE
Enum types don't resolve correctly for top-level variable declarations

### ISSUE THREAD

**Issue by alangpierce** [AssemblyScript/assemblyscript#116]
This code:
```typescript
enum TestEnum {
  A
}
let value: TestEnum;
```
fails to compile, with this error:
```
ERROR TS2304: Cannot find name 'TestEnum'.

 let value: TestEnum;
            ~~~~~~~~
 in main.ts(4,11)
```

In every other context that I've tried, the `TestEnum` type resolves fine, it's just top-level declarations that seem broken. The error also occurs for classes with enum fields where the class is used as the type of a top-level declaration.

**Comment by dcodeIO** [comment]
I wonder how this didn't surface earlier. Nonetheless, this should resolve to `i32` now :)

**Comment by alangpierce** [comment]
Thanks! Seems to be working for me.
