### ISSUE TITLE
Why do AST Node classes use T[] | null?

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1166]
For example, why do `DeclaredElement`s have `decorators: DecoratorNodes[] | null`.  Couldn't this just be an empty list?

**Comment by MaxGraey** [comment]
I guess the main reason is reduce GC/memory preasure. not every function has decorators so make sense create this array lazily: https://github.com/AssemblyScript/assemblyscript/blob/03aff6e87a7d7a52308de50206c6358c8e1e59b8/src/parser.ts#L180

**Comment by willemneal** [comment]
An empty array shouldn't be that expensive.  And it results in more verbose source code down the line that has to always check the nullity or use `decorators?`, etc.

**Comment by MaxGraey** [comment]
As I remember it wasn't lazy at the beginning and during serial performance tunings of compiler we decide use lazy array initialization pattern wherever possible and this speedup parsing stage

**Comment by dcodeIO** [comment]
The intent there is to keep memory consumption low since there can be a huge amount of AST nodes and IR elements in larger programs, and what appears to be just an innocent empty array can up to triple their memory requirement (node or element + array header + array backing buffer, 1->3 allocations, 32->96b, potential cyclics add GC pressure).

**Comment by willemneal** [comment]
You could use a singleton empty array instance.  Then when adding an element then create a new array.

**Comment by dcodeIO** [comment]
While something like that might help external users, it makes the situation worse internally. For instance, we still have to check `if (decorators == EMPTY) decorators = [decorator]`, so nothing won there, and it also introduces a surface for subtle errors where code might push to `EMPTY` when forgetting to check. If it's `null`, one has to check.
