### ISSUE TITLE
Malloc with Data Segments

### ISSUE THREAD

**Issue by jacobp100** [AssemblyScript/assemblyscript#118]
If I have a module that has some of its memory initialised with data segments, is there a way to ensure `malloc` will not override it?

The data might be from another wasm module from the assemblyscript module, and just share memory with the assemblyscript module.

**Comment by dcodeIO** [comment]
Current memory layout is described here: https://github.com/AssemblyScript/runtime

There is no real linking, yet, though. Once Binaryen allows iterating static memory segments, it would become become possible to load a base module, similar to how the compiler does with the runtime atm, and reuse its memory.

**Comment by jacobp100** [comment]
Didn’t realise this also had to set memory—makes sense now. Thanks for the links!

**Comment by jacobp100** [comment]
I didn’t realise the JS API returned a Binaryen module. I was able to get what I wanted done by just working on top of that.

Great work on the project—it was super easy to see what was going on and how to use the compiler instance to get what I needed to!
