### ISSUE TITLE
Assertion failed when modifying a variable from within init

### ISSUE THREAD

**Issue by pitust** [AssemblyScript/assemblyscript#1186]
Here is a sample:
```typescript
let a = (a = 4, 3);
```

**Comment by pitust** [comment]
#1190 doesn't fix this. This still is valid JS:
```js
var a = (a = 4, 3);
```

**Comment by MaxGraey** [comment]
@pitust On typescript this not valid:
https://www.typescriptlang.org/play/index.html?ssl=1&ssc=19&pln=1&pc=1#code/G4QwTgBCELwQFNOAmANBAzASiA

**Comment by pitust** [comment]
Oh, i didn't know that. I don't do a lot of typescript normally.
