### ISSUE TITLE
RegExp support

### ISSUE THREAD

**Issue by mariopmartins** [AssemblyScript/assemblyscript#1188]
Hello, 

I've been playing around with AssemblyScript and I noticed it still doesn't have RegExp object implemented: https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/regexp.ts

I am able to compile the following code: 
`const regex : RegExp = new RegExp('hi');//return true;
  return regex.test('hi, i am peter');`
But not able to execute it:

> /Users/m0m02y0/as/assembly/node_modules/@assemblyscript/loader/index.js:72
>     throw Error("abort: " + getString(memory, mesg) + " at " + getString(memory, file) + ":" + line + ":" + colm);
>     ^
> 
> Error: abort: unreachable at ~lib/regexp.ts:4:53
>     at abort (/Users/m0m02y0/as/assembly/node_modules/@assemblyscript/loader/index.js:72:11)
>     at ~lib/regexp/RegExp#constructor (wasm-function[15]:0xb3b)
>     at assembly/index/test1 (wasm-function[17]:0xb6d)
>     at Object.curr.<computed> [as test1] (/Users/m0m02y0/as/assembly/node_modules/@assemblyscript/loader/index.js:407:18)
>     at Object.<anonymous> (/Users/m0m02y0/as/assembly/tests/index.js:4:23)
>     at Module._compile (internal/modules/cjs/loader.js:1158:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
>     at Module.load (internal/modules/cjs/loader.js:1002:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
> npm ERR! Test failed.  See above for more details.

Is this in your roadmap? Is there another way to use regular expressions in AS?

Thank you

**Comment by dcodeIO** [comment]
[RegExp](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/regexp.ts#L7) isn't implemented yet. Plan is to derive something from a battle-tested C library eventually, but until then all one can do is to call out to JS or use a different mechanism, like string methods, if that's an option.

**Comment by mariopmartins** [comment]
Thanks Daniel for the quick reply. 
This is probably a dealbreaker for our team since we are exploring languages to write Envoy WASM Filters. I will circle back with the team to hear what they think.
By any chance, do you guys already have this in your roadmap?

**Comment by MaxGraey** [comment]
> By any chance, do you guys already have this in your roadmap?

Not a high priority in roadmap at the moment.

**Comment by mariopmartins** [comment]
Ok, thanks for the quick response guys. I spoke to my team and this is a showstopper for us. 
Either way, the whole idea of AssemblyScript is awesome and I'm eager to see it when it's ready and fully functional.

**Comment by piersdeseilligny** [comment]
Should this issue really be closed? It seems like a fairly big missing chunk of assemblyscript :/
