### ISSUE TITLE
can not compile an aliased generic function

### ISSUE THREAD

**Issue by NefarioDr** [AssemblyScript/assemblyscript#119]
I aliased a generic function type as :  
`type Operator<T> = (t: T) =>boolean`  
but it can not be compiled,   
```
ERROR TS2304: Cannot find name 'T'.

type TObjOperator<T> = (t: T) => void;
```

**Comment by dcodeIO** [comment]
Tests for function types like yours that might help: https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/function-types.ts

Note that `T` must be known at compile time for a function to be compilable ahead of time, like so:

```ts
function hello<T>(fn: Operator<T>): void {}

var myOperator = ...;
hello<i32>(myOperator);
```

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
