### ISSUE TITLE
Incorrect result in normal `for` loop [Question]

### ISSUE THREAD

**Issue by aminya** [AssemblyScript/assemblyscript#1191]
I am trying to build this function, but its result is always 0. What am I doing wrong?

wasm.ts
```ts
export function for_array(arr: Array<f32>): f32 {
  let sum: f32 = 0.0
  for (let i: i32 = 0, l: i32 = arr.length; i < l; ++i) {
    sum += arr[i]
  }
  return sum
}
```
loader.ts:
```ts
const fs = require("fs")
const loader = require("@assemblyscript/loader")
export const myWasm = loader.instantiateSync(
    fs.readFileSync("./build/release.wasm")
)
```
index.ts
```ts
import {myWasm} from './loader'
console.log('AS =', myWasm.for_array(arr));
```

scripts commands:
```
    "start": "node --experimental-modules --experimental-wasm-modules ./dist/index.js",
    "asbuild ": "asc wasm.ts -b build/release.wasm -t build/release.wat --validate -O3",
    "copy": "shx rm -rf dist/build/ && shx cp -r build dist/build/",
    "build": "npm run asbuild && tsc -p ./tsconfig.json && npm run copy",
```

**Comment by dcodeIO** [comment]
This works for me on master:

```ts
function for_array(arr: Array<f32>): f32 {
  let sum: f32 = 0.0
  for (let i: i32 = 0, l: i32 = arr.length; i < l; ++i) {
    sum += arr[i]
  }
  return sum
}

assert(for_array([1, 1]) == 2)
```

Are you trying to pass a normal JS array here?

```js
console.log('AS =', myWasm.for_array(arr));
```

**Comment by aminya** [comment]
> Are you trying to pass a normal JS array here?
> 
> ```js
> console.log('AS =', myWasm.for_array(arr));
> ```

Yes. Do I need to convert it or something?

**Comment by dcodeIO** [comment]
> Yes. Do I need to convert it or something?

Yes, the array must first be allocated in the Wasm module's memory. The [loader](https://docs.assemblyscript.org/basics/loader) provides the necessary utility to do so:

```ts
export const ArrayF32_ID = idof<Array<f32>>();
...
```

```js
var arrPtr = myWasm.__retain(myWasm.__allocArray(myWasm.ArrayF32_ID, [1, 2, 3]));
console.log('AS =', myWasm.for_array(arrPtr));
myWasm.__release(arrPtr);
```

**Comment by aminya** [comment]
> 
> 
> > Yes. Do I need to convert it or something?
> 
> Yes, the array must first be allocated in the Wasm module's memory. The [loader](https://docs.assemblyscript.org/basics/loader) provides the necessary utility to do so:
> 
> ```ts
> export const ArrayF32_ID = idof<Array<f32>>();
> ...
> ```
> 
> ```js
> var arrPtr = myWasm.__retain(myWasm.__allocArray(myWasm.ArrayF32_ID, [1, 2, 3]));
> console.log('AS =', myWasm.for_array(arrPtr));
> myWasm.__release(arrPtr);
> ```

Thank you!

 Could you add all these information to the documentation? A main section for interoperability with JavaScript. The documentation is a little spread all over the place and vague in this regard.

**Comment by aminya** [comment]
@dcodeIO I get a different result from the typescript code if I use `f32`. If I use `f64` this is solved. 
Why is this happening?
```ts
const arrPtr = myWasm.__retain(myWasm.__allocArray(myWasm.ArrayF64_ID, arr));
console.log('AS64 =', myWasm.for_array(arrPtr));
myWasm.__release(arrPtr);

const arrPtr32 = myWasm.__retain(myWasm.__allocArray(myWasm.ArrayF32_ID, arr));
console.log('AS32 =', myWasm.for_array(arrPtr32));
myWasm.__release(arrPtr32);

console.log('TS =', for_array_ts(arr));
```

**Comment by MaxGraey** [comment]
`f32` has lower precision and dynamic range so it expected behaviour

**Comment by aminya** [comment]
Other than my request for more documentation and examples in the docs, I have no other question. Thank you for your help.

> Could you add all these information to the documentation? A main section for interoperability with JavaScript. The documentation is a little spread all over the place and vague in this regard.
