### ISSUE TITLE
inline 2

### ISSUE THREAD

**Issue by blooddy** [AssemblyScript/assemblyscript#12]
Is it possible to add support for inline functions?
```
export function test(x:i32, y:i32):i32 {
    x = add( x, 1 );
    y = add( y, 1 );
    return add( x, y );
}

inline function add(x:i32, y:i32):i32 {
    return x + y;
}
```
That should be optimized to
```
export function test(x:i32, y:i32):i32 {
    x = x + 1;
    y = y + 1;
    return x + y;
}
```

**Comment by dcodeIO** [comment]
Yeah, [this comment](https://github.com/AssemblyScript/assemblyscript/issues/14#issuecomment-357520824) applies here as well.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
