### ISSUE TITLE
Improve Webpack loader

### ISSUE THREAD

**Issue by xtuc** [AssemblyScript/assemblyscript#120]
With the new wasm pipeline in Webpack (> 4.8.0), loader can now directly emit a wasm binary. 

I have a very simple demo here: https://github.com/xtuc/c-webpack-demo.

The idea would be to allow:

```js
  module: {
    rules: [
      {
        test: /\.ts$/,
        loader: "@assemblyscript/loader",
        type: "webassembly/experimental"
      }
    ]
  },
```

and the user would just:

```js
import("./foo.ts").then(...)
```

**Comment by dcodeIO** [comment]
Thanks for the insights! Does the `import` in this case return a `WebAssembly.Module` one can instantiate? Ultimately I'd like [@assemblyscript/loader](https://github.com/AssemblyScript/assemblyscript/tree/master/lib/loader) to provide the utility mentioned in the README and *also* integrate with webpack. The challenge here seems to be to return something that can a) be instantiated by providing the necessary imports and b) matches the `.d.ts` generated by the compiler by running the demangler on the WASM exports first.

**Comment by xtuc** [comment]
> Does the import in this case return a WebAssembly.Module one can instantiate

No it will return the `WebAssembly.Module`.`exports` basically.

> Ultimately I'd like @assemblyscript/loader to provide the utility mentioned in the README

We'll use instantiateStreaming when available and fallback if not. 

For `demangle` you have the object with the exports, is that ok?

> be instantiated by providing the necessary imports

Webpack will do the linking, you need to emit and require local files.

**Comment by dcodeIO** [comment]
I see, thanks. So proper integration with webpack will require support for external imports in AssemblyScript first because there is no other way to specify imports :)

**Comment by xtuc** [comment]
Yeah, maybe we can keep it internal just to test the integration but that would also enable a better integration with the user's JavaScript code.

**Comment by dcodeIO** [comment]
Yeah, one of the reasons why it's currently using the `declare` syntax and picking imports from ambient contexts is that this way both import styles can be supported eventually, with `import`s mapping to what will become es module integration (as now in webpack, I suppose), and `declare` remaining as a more direct mechanism to specifiy import namespaces manually (i.e. for non-web embeddings).

**Comment by trusktr** [comment]
> Does the import in this case return a WebAssembly.Module one can instantiate? 

I think it'd be great (if this isn't the case already) that an AssemblyScript module could export a `class` or `function`, and that the JS side could use it like a `class` or `function` with the same types as defined on the AssemblyScript side (internally the module would wrap the WASM Module and make the wrapper methods call into the WASM module, etc).

Eventually the internal implementation could be replaced with references and object types to make it fast.

**Comment by trusktr** [comment]
Using the example from [assemblyscript-typescript-loader](https://www.npmjs.com/package/assemblyscript-typescript-loader), if we have some AS code:

```ts
var w: u32, // width
    h: u32, // height
    s: u32; // total size
 
/** Initializes width and height. */
export function init(w_: u32, h_: u32): void {
  w = w_;
  h = h_;
  s = w * h;
}
 
/** Performs one step. */
export function step(): void {
  var hm1 = h - 1,
      wm1 = w - 1;
  for (var y: u32 = 0; y < h; ++y) {
    var ym1 = select<u32>(hm1, y - 1, y == 0),
        yp1 = select<u32>(0, y + 1, y == hm1);
    for (var x: u32 = 0; x < w; ++x) {
      var xm1 = select<u32>(wm1, x - 1, x == 0),
          xp1 = select<u32>(0, x + 1, x == wm1);
      var n = (
        load<u8>(ym1 * w + xm1) + load<u8>(ym1 * w + x) + load<u8>(ym1 * w + xp1) +
        load<u8>(y   * w + xm1)                         + load<u8>(y   * w + xp1) +
        load<u8>(yp1 * w + xm1) + load<u8>(yp1 * w + x) + load<u8>(yp1 * w + xp1)
      );
      if (load<u8>(y * w + x)) {
        if (n < 2 || n > 3)
          store<u8>(s + y * w + x, 0);
      } else if (n == 3)
        store<u8>(s + y * w + x, 1);
    }
  }
}
```

then instead of importing like this:

```ts
import asmPromise from "./assemblyscript/moduleEntry.ts";
asmPromise().then(function(asmModule){
  // here you can use the wasm.exports
  asmModule.step();
})
```

we'd import it like the following (which will work with top-level await):

```ts
import {step} from "./assemblyscript/moduleEntry.ts";

// use the wasm.exports
step()
```

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because it has been lingering for quite some time without being resolved. If it's still an issue important to you, feel free to open a new one!
