### ISSUE TITLE
How can get an Array like string[]  with  __retain

### ISSUE THREAD

**Issue by yjf28852** [AssemblyScript/assemblyscript#1204]
Hello，
I'm pretty new in assemblyscript and webassembly and I have a small problem.How I can get Array like string[]  from JavaScript.Here is my code:
```
//index.js
...
 let css = ['className1','className2']
 let ptr = mod.__retain(mod.__allocArray(mod.I32ARRAY_ID,css.map(item=>mod.__allocString(item))))
mod.pushData(ptr)
let n  = mod.__getArray(ptr)
console.log(n)
```

```
//index.ts
export const I32ARRAY_ID = idof<i32[]>();
export function pushData(arr: string[]): void {
  arr.push('newClassName');
}
```
But the result is not what I want.
what I expect
```
['className1','className2','newClassName']
```

**Comment by MaxGraey** [comment]
Could you clarify your question?

**Comment by yjf28852** [comment]
> Could you clarify your question?


Could you please take a look at it for me?

**Comment by MaxGraey** [comment]
I guess you just forgot unpack strings:
```ts
...
let arr  = mod.__getArray(ptr);
let n = arr.forEach(strPtr => mod.__getString(strPtr));
console.log(n);
```

**Comment by yjf28852** [comment]
> I guess you just forgot unpack strings:
> 
> ```ts
> 
> ...
> 
> mod.pushData(ptr);
> 
> let arr  = mod.__getArray(ptr);
> 
> let n = arr.map(strPtr => mod.__getString(strPtr));
> 
> console.log(n);
> 
> ```
> 
> Btw don't forget release `ptr`

thanks
