### ISSUE TITLE
Argument count confusion in nested varargs calls

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#1210]
Let's say we have

```ts
function foo(a: i32, b: i32 = 0): void {
}
function bar(a: i32 = 10): i32 {
  return a;
}
foo(bar());
```

if the initializers above were dynamic (here constant for simplicity) we'll generate

```wat
global.set $argumentsLength 1
 global.set $argumentsLength 0 ;; :(
 i32.const 0
 call $bar|trampoline
 i32.const 0
call $foo|trampoline
```

where `argumentsLength` becomes confused due to execution order. Unfortunately, we can't just fix this by changing execution order because Binaryen's IR is a tree, not stacky, so the most straight forward way to fix this is to use (potentially lots of) temporary locals:

```wat
i32.const 0
local.set $t1
global.set $argumentsLength 1
local.get $t1
call $bar|trampoline
local.set $t2
i32.const 0
local.set $t3
global.set $argumentsLength 0
local.get $t2
local.get $t3
call $foo|trampoline
```

**Comment by MaxGraey** [comment]
How about special (AS-specific) elimination pass for `argumentsLength` for Binaryen?

**Comment by dcodeIO** [comment]
Currently thinking if we can somehow get rid of `argumentsLength` at least internally and make it an additional function parameter only trampolines have. Might well be that this optimizes well using argument elimination, but also raises questions regarding indirect calls where the trampoline would no longer be interchangeable with the unmodified function, hmm...

**Comment by dcodeIO** [comment]
Found a fine solution for this. Instead of setting `argumentsLength` before the entire call, setting it can be injected into the last operand, if a direct call, respectively the index argument, if an indirect call (here: the last expression becoming executed before executing the call). Doing so is straight forward for direct calls, since we know that the last operand has been omitted and is a `0` anyway, while indirect calls need a single temporary local so the index expression cannot mess with `argumentsLength`.

**Comment by dcodeIO** [comment]
Fixed in https://github.com/AssemblyScript/assemblyscript/pull/1208/commits/661866d60cf1420edcb8dc3fa8df22ea3e7701e3
