### ISSUE TITLE
Request for instruction on how to help

### ISSUE THREAD

**Issue by bryanrideshark** [AssemblyScript/assemblyscript#1221]
We are hoping that one day, AssemblyScript will be able to replace the state management of our current application. We would like to help as much as possible in encouraging this transition.

Currently, we use 
 - `rxjs`
 - `immer`

What features need to be developed to make it possible to use the es5 implementation of immer (no Proxies) and the raw sourcecode of rxjs/6 in AssemblyScript? Is there a way for more regular developers who have never written a compiler to help achieve this goal?

**Comment by MaxGraey** [comment]
First of all it #798 and #292. Next one is iterators and functions with variable arguments. But even after that you can hardly use `rxjs` or `immer` without any modifications due to some `any` and dynamic (meta) aspects in source code of that libraries.

**Comment by jtenner** [comment]
This is always a challenge. Porting a library to obtain a proper level of performance involves understanding the environment the code is running in. This is always a challenge, even for me, after developing `as-pect` in it's entirety. If I'm not mistaken, `immer` is immutable data right? That should be something worth exploring in terms of usefulness for AssemblyScript developers. 

I would also like to say that JavaScript is very good at being JavaScript, and using it is still a very valid thing to do.
