### ISSUE TITLE
Default exports broken

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#1223]
Minimal repro here: https://webassembly.studio/?f=i7lefl19ym9

Looks like it has to do with the parser treating default exports as regular exports.

**Comment by MaxGraey** [comment]
duplicate: #98

**Comment by dcodeIO** [comment]
The minimal repro there seems to work. Did we do something about that already?

**Comment by MaxGraey** [comment]
Hmm, yeah it seems this already repaired

**Comment by MaxGraey** [comment]
Could we close this?

**Comment by dcodeIO** [comment]
Closing, as the initial repro seems to work and https://github.com/AssemblyScript/assemblyscript/pull/1257 fixes something that seems related. Feel free to reopen if there are still issues :)
