### ISSUE TITLE
Will AS have support for pointers and references?

### ISSUE THREAD

**Issue by mariopmartins** [AssemblyScript/assemblyscript#1228]
Hey guys, 

I was just curious about this and I wanted to hear your thoughts.
Do you guys intend to add support for * and & to the language? 

I understand that this might have consequences with the GC implementation and to TS Portability, but there are situations in which we need to call another application ABI and they take pointers as parameters. 

See this example from Yuval Kohavi (@yuval-k) here: 
https://github.com/solo-io/proxy-runtime/blob/master/assembly/runtime.ts#L207-L212
In order to make this work, he had to create a Reference object like so:
https://github.com/solo-io/proxy-runtime/blob/master/assembly/runtime.ts#L33-L39

This was a clever workaround, but do you guys intend to provide better syntax for such things? What are your thoughts about it?

Thanks, 
Mario

**Comment by MaxGraey** [comment]
Refs / pointers could be emulated via arrays:
https://github.com/jedisct1/as-wasi/pull/21/files#diff-5858db0a3a9b21c5aeba457de2d3b702R55

or via using `const outPtr = __alloc(sizeof<u32>(), 0)`

**Comment by dcodeIO** [comment]
One aspect there is that AssemblyScript doesn't have a stack on its own (in linear memory) but exclusively relies on Wasm's execution stack, which one can't take an address of / into. So, typically, one would either make a heap allocation or reserve some space in static memory to reuse for this purpose, as Max pointed out. Open to suggestions on how to improve this :)

**Comment by dcodeIO** [comment]
Related: https://github.com/AssemblyScript/assemblyscript/pull/1233 Might be useful here since it works very much like `static` in C/C++.

**Comment by mariopmartins** [comment]
Well, I had something like this in my mind. But, to be honest, I don't really understand all the implications...

Add the following global functions:
```
@global @unsafea
export function __pointer(reference: any): usize;

@global @unsafe
export function __reference(pointer: usize): any;
```

After that, * and & could be syntactic sugar that calls these functions in the background.

**Comment by MaxGraey** [comment]
WebAssembly hasn't shadow stack. It means only heap or objects in static sections could be interpret as references. In this case only objects could reference and dereference via `ptr = changetype<usize>(obj)` / `obj = changetype<Obj>(ptr)`. That's quite sufficient for all unsafe stuffs.

**Comment by MaxGraey** [comment]
Btw if you want more high-level and safe pointer (and zero-cost btw) you may interested in this experiment: https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/std/pointer.ts#L3
