### ISSUE TITLE
Thoughs on "managed" objects, non-virtual members, and GC

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#123]
At this point in time, instance members on classes are all final and thus do not behave like one might expect from a JS-perspective. For example:

```ts
class Foo {
  baz(): void {}
}
class Bar extends Foo {
  baz(): void {}
}
export function test(foo: Foo): void {
  foo.baz(); // always calls `Foo#baz` because that's the type annotated on the var, even if `foo` is a `Bar`
}
```

The current behavior resembles that of C# (instance members are final by default) but not that of Java/JS (instance members are virtual by default).

The usual implementation strategy for virtual members is to generate a lookup table per class, that then resolves to the respective possibly overloaded memory or function table index, but that'd require an id on each class instance as an indicator which lookup table to use. We'll most likely want JS-like behavior long-term, possibly with decorators forcing a specific behavior (i.e. `@final` and `@virtual`), but introducing a class id as the first 4 bytes of each *managed* class doesn't yet fit into the broader picture yet because of the lack of GC (those two things usually introduce a dependency on some sort of bundled runtime, justifying the term *managed*). Also, in the current state of the GC spec, I cannot spot ways to make structures living in linear memory become interoperable with managed objects (i.e. there is no way to describe a segment of linear memory to the host so that it can naturally flow out of WASM as something useful).

To me this eventually leads to the more fundamental question of how a possible implementation of *managed* classes in AssemblyScript is going to look like. Or: How far do we want to go with classes living in linear memory? My preference, at this point, is to rely exclusively on the future GC spec when it comes to managed objects (no need for a bundled runtime, smaller binaries in general, best possible interoperability with the host), while still supporting the current `@unmanaged` decorator to define "C-like structs with methods". The downside of this is that unmanaged classes will always work differently, as in the example above, (unless we decide to go overboard with these) and, more importantly, that the reliance on the GC spec will force the use of those unmanaged classes whenever the host does not support GC (might hurt blockchain, as GC is a common source of non-determinism?).

What are your thoughts?

**Comment by torch2424** [comment]
Thanks for this issue. Very good thoughts and ideas here. 😄 

First, let me admit, I am no expert at compilers or designing languages, but I 100% that trying to get this to "as close to JS as possible" is a good way looking forward. I think offering a decorator for now, that could be eventually deprecated would be a good idea, once we finally get GC and other things in the official wasm spec. Though, I am sure they are other pressing issues to get done. Perhaps, we can put this on the backburner for now as a "nice to have", and hopefully things get moved along especially since wasm is "heating up" across hobby and production projects?
