### ISSUE TITLE
Static memory segment idea

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#1232]
So we have `StaticArray` now, which is great on its own but still a managed object, and it would be even greater if there'd also be a way to get some raw static memory. Proposing the following:

Extend the `memory` namespace to be also a function, that one can use like

```ts
const myMem = memory(64);
```

yielding a static pointer to 64 bytes of reserved static memory. When using this in a function

```ts
function foo(): i32 {
  const ptr = memory(4);
  var value = load<i32>(ptr);
  store<i32>(ptr, value + 1);
  return value;
}
```

the segment will always be exactly the same, so calling the function above multiple times would yield 0, 1, 2, 3, ... quite similar to what `static` in C does. This can then be used for various things, like as an alternative to (temporary) stack allocation as long as one makes sure that it is not being accessed in parallel. The argument must be a compile-time constant.

Thoughts?

**Comment by MaxGraey** [comment]
How about `const mem = memory.init(64)`?

**Comment by jtenner** [comment]
Yes! This would help reduce globals and enable creating threaded memory allocators.

**Comment by dcodeIO** [comment]
> How about const mem = memory.init(64)?

`memory.init` is a legitimate instruction specified by bulk-memory that copies "a region from a data segment". Just `memory` is relatively safe in that it cannot conflict with an instruction by design.

**Comment by MaxGraey** [comment]
alright, May be `memory.reserve` or `memory.alloc`? Because `memory(64)` looks slightly inconsistent

**Comment by dcodeIO** [comment]
An alternative might be `memory.data` which is a section, but not an instruction?

**Comment by MaxGraey** [comment]
`memory.data` also lgtm

**Comment by dcodeIO** [comment]
For the record, I liked `memory` since it semantically says "give me `n` bytes within `memory`" :)

**Comment by jedisct1** [comment]
This is a very useful addition!
