### ISSUE TITLE
Can it be used for production now?

### ISSUE THREAD

**Issue by liangzeng** [AssemblyScript/assemblyscript#126]
hi  , I am a javascript programmer
can it be used for production now?

**Comment by dcodeIO** [comment]
Depends. Low-level, C-like code doing manual memory management / not relying on a GC should work fine, but OOP is still pretty much a [work in progress](https://github.com/AssemblyScript/assemblyscript/issues/123).

**Comment by liangzeng** [comment]
@dcodeIO thanks!
