### ISSUE TITLE
"Orphaned Decrement Error" on big loops

### ISSUE THREAD

**Issue by alexvictoor** [AssemblyScript/assemblyscript#1261]
Hello all,
I have found a strange behaviour, maybe a bug, with the following code:
```
const nbLoop = 14828;
let index: i32 = 0;
while (index < nbLoop) {
  const count = Math.abs(index++);
  if (count < 0) {
    throw new Error("blabla, should never happen" + count.toString());
  }
}
```
With nbLoop set to 14828 I get an "Orphaned Decrement Error" at runtime while there is none if nbLoop is set to a lower value. 
Also there is no error if I increment 'index' before computing 'count' or if I remove the 'if' block.
Let me know if you need more information

**Comment by MaxGraey** [comment]
Can confirm. Also if replace to `++index` issue is gone

**Comment by dcodeIO** [comment]
Appears to be a problem with `throw` not properly ending the respective flow there, leading to releases of integers at the bottom of the loop. Once these integers become larger than the end offset of static memory, stuff goes boom.

**Comment by alexvictoor** [comment]
In my codebase, the issue happens even if I remove the _throw_ :(
The code is quite complex, unfortunately I have not figure out yet a simple testcase "without throw" that reproduces the issue

**Comment by dcodeIO** [comment]
The problem specific to `throw`s should be fixed now. Removing the `bug` label, but keeping this in mind. Feel free to add a follow-up snippet where something goes wrong without throw.

**Comment by alexvictoor** [comment]
Thanks for the quick fix. I guess @dcodeIO you are right, I missed a second throw in my codebase and without it I do not get errors anymore. 
Quite eager to test a nightly build :)

**Comment by dcodeIO** [comment]
Closing this issue as it appears to be solved, but if it isn't, feel free to reopen :)
