### ISSUE TITLE
__allocArray with @assemblyscript/loader v0.10

### ISSUE THREAD

**Issue by alexvictoor** [AssemblyScript/assemblyscript#1278]
Hello
I have tried to upgrade a project using assemblyscript loader 0.9.4 to 0.10.
The __allocArray function seems to have disappeared. Has the assemblyscript loader changed with version 0.10?
Thanks a lot for your help

**Comment by dcodeIO** [comment]
What you might be seeing there is that the loader now returns an object with an `.exports` property upon instantiate, instead of the exports directly, to align more with the WebAssembly spec.

**Comment by alexvictoor** [comment]
Thanks a lot for the quick answer. Indeed it works much better using the exports property :) I was a little bit misleaded by the toString output of the export object that contains __alloc but not __allocArray.
Thanks anyway for your help

**Comment by MeirionHughes** [comment]
I guess that explains why I'm struggling so much - docs and examples are out-of-date. :/
