### ISSUE TITLE
Object memory model

### ISSUE THREAD

**Issue by vdeturckheim** [AssemblyScript/assemblyscript#128]
Hey,

I have been through the doc (and especially the great https://github.com/AssemblyScript/assemblyscript/wiki/Memory-Layout-&-Management) but I can't find how objects are stored in memory.
Given a simple class
```
class Item {
    a: string = 'string';
    b: i32 = <i32>99;
    key: string = 'right'
}

export function getItem(): Item {
    return new Item();
}
``` 
I could find where the values were stored but I could not get where the keys are.
Am I missing something?

Thanks a lot!

**Comment by dcodeIO** [comment]
The keys are not stored, but just a way to reference such a field at compile-time (similar to C/C++). Class layout is currently performed by starting at `this` + `0`, aligning for the next field, and putting it there. So if you have, let's say:

```ts
class Item {
  a: i16; // align to 2 bytes => offset 0
  b: i32; // align to 4 bytes => offset 4 (not 2, as another 2 bytes are skipped due to alignment)
  key: string; // align to 4 bytes (wasm32) => offset 8
}
```

**Comment by vdeturckheim** [comment]
@dcodeIO thanks for this quick answer!

Side question, would you be open to a PR on loader to add `getArray(ptr: number): Array` ?

**Comment by dcodeIO** [comment]
Sure, why not. Fwiw, I didn't implement it yet because it requires knowledge of the underlying type (i.e. 2 bytes for arrays of i16's, 8 bytes for arrays of f64's) and thus the API might not be that great.

**Comment by vdeturckheim** [comment]
Fair point, I'll see what I can do then.
