### ISSUE TITLE
AssemblyScript 0.10.0 : Imports that specify a file extension no longer work

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#1282]
Noticed this behavior after upgrading some more projects to `0.10.0`. I would use syntax like:

```typescript
import { exportedFunc } from "./export.ts";
import {add} from "my-other-package";

export function hello(): i32 {
  return add(exportedFunc(), exportedFunc);
}
```

However, imports with a file extension, (or external packages that import with a file extension), no longer can be found, and you will get errors like:

![Screenshot from 2020-05-18 14-48-37](https://user-images.githubusercontent.com/1448289/82263194-39b9d900-9917-11ea-8c30-affbb3230bae.png)
![Screenshot from 2020-05-18 14-47-55](https://user-images.githubusercontent.com/1448289/82263197-3a526f80-9917-11ea-8d87-d86086e4085a.png)

Made a quick little test case at: https://github.com/torch2424/as-playground/tree/master/import-file-extension

I feel this is probably due how we can now specify the file extension in the CLI itself :smile: 

And if you point me to where in the project this could probably be fixed, would be happy to open a PR for this. Thanks! :smile: :+1: 

cc @MaxGraey @dcodeIO

**Comment by dcodeIO** [comment]
Appears TypeScript doesn't support this as well, and has a special error for it:

```ts
"An import path cannot end with a '{0}' extension. Consider importing '{1}' instead.": {
  "category": "Error",
  "code": 2691
},
```

What do you think of leaving it as an error to avoid ambiguity (i.e. there is an `export.ts` and an `export.ts.ts`), but improve the error message?

**Comment by torch2424** [comment]
@dcodeIO Ah! If typescript doesn't support it, let's go ahead and just improve the error here :smile: Thank you!
