### ISSUE TITLE
Bug with TypedArray.set() when the code is optimized?

### ISSUE THREAD

**Issue by alexvictoor** [AssemblyScript/assemblyscript#1288]
Hello all,
I have found a strange behaviour with TypedArray.set().
The following code fragment works fine in an as-pect test or when the code is compiled without the "--optimize" flag:
```
  let buffer = new Uint8Array(1);
  buffer[0] = 42;
  const oldBuffer = buffer;
  buffer = new Uint8Array(2);
  buffer.set(oldBuffer);
  buffer[1] = 1;
  // buffer[0] === 42
```

However, when the "--optimize" flag is used, buffer[0] is set to 0 at the end...
Here is a link to see this bug in action: https://webassembly.studio/?f=wtzfbyvd2q
Let me know if you need anything else!

**Comment by MaxGraey** [comment]
Its seems it issue with ARC optimizer.
If add extra `__retain(changetype<usize>(buffer))` this problem disappear: 
https://webassembly.studio/?f=p1c75u3i9yr

**Comment by alexvictoor** [comment]
@MaxGraey thanks a lot for the workaround!

**Comment by MaxGraey** [comment]
Don't forget remove this when issue will fixed. Otherwise you got memory leak

**Comment by alexvictoor** [comment]
Thanks @MaxGraey . Just to be sure tu understand: the workaround leaks memory already with assemblyscript v0.10 or just in upcoming versions of assemblyscript?

**Comment by MaxGraey** [comment]
not sure about leaknes with this workaround but after fixing it definitely could so just leave `TODO:` / `NOTE:` comment in your code I guess

**Comment by dcodeIO** [comment]
Very strange. To recap, on

```ts
{
  let buffer = new Uint8Array(1);
  buffer[0] = 42;
  const oldBuffer = buffer;
  buffer = new Uint8Array(2);
  buffer.set(oldBuffer);
  buffer[1] = 1;
  assert(buffer[0] === 42);
}
```

before optimizations we get

```wat
  i32.const 0
  i32.const 1
  call $~lib/typedarray/Uint8Array#constructor
  local.set $0
  local.get $0
  i32.const 0
  i32.const 42
  call $~lib/typedarray/Uint8Array#__set
  local.get $0
  call $~lib/rt/pure/__retain ;; (1)
  local.set $1
  i32.const 0
  i32.const 2
  call $~lib/typedarray/Uint8Array#constructor
  local.set $2
  local.get $0
  call $~lib/rt/pure/__release
  local.get $2
  local.set $0
  local.get $0
  local.get $1
  i32.const 0
  call $~lib/typedarray/Uint8Array#set<~lib/typedarray/Uint8Array>
  local.get $0
  i32.const 1
  i32.const 1
  call $~lib/typedarray/Uint8Array#__set
  local.get $0
  i32.const 0
  call $~lib/typedarray/Uint8Array#__get
  i32.const 42
  i32.eq
  i32.eqz
  if
   i32.const 0
   i32.const 432
   i32.const 8
   i32.const 3
   call $~lib/builtins/abort
   unreachable
  end
  local.get $0
  call $~lib/rt/pure/__release
  local.get $1
  call $~lib/rt/pure/__release ;; (2)
```

expecting (2) to eliminate (1), which appears to happen, but after optimizations we are left with

```wat
  i32.const 1
  call $~lib/typedarray/Uint8Array#constructor
  local.tee $1
  i32.const 0
  i32.const 42
  call $~lib/typedarray/Uint8Array#__set
  i32.const 2
  call $~lib/typedarray/Uint8Array#constructor
  local.set $0
  local.get $1
  call $~lib/rt/pure/__release ;; too early
  local.get $1
  i32.load offset=8
  local.get $0
  i32.load offset=8
  i32.gt_s
  if
   i32.const 1312
   i32.const 1376
   i32.const 1775
   i32.const 47
   call $~lib/builtins/abort
   unreachable
  end
  local.get $0
  i32.load offset=4
  local.get $1
  i32.load offset=4
  local.get $1
  i32.load offset=8
  call $~lib/memory/memory.copy
  local.get $0
  i32.const 1
  i32.const 1
  call $~lib/typedarray/Uint8Array#__set
  i32.const 0
  local.get $0
  i32.load offset=8
  i32.ge_u
  if
   i32.const 1312
   i32.const 1376
   i32.const 152
   i32.const 45
   call $~lib/builtins/abort
   unreachable
  end
  local.get $0
  i32.load offset=4
  i32.load8_u
  i32.const 42
  i32.ne
  if
   i32.const 0
   i32.const 1440
   i32.const 8
   i32.const 3
   call $~lib/builtins/abort
   unreachable
  end
  local.get $0
  call $~lib/rt/pure/__release
```

Quite strange since there are no complicated branches involved. My immediate intuition would be that the ARC passes aren't early enough in the pass pipeline.

**Comment by dcodeIO** [comment]
On a second look it becomes clear that the post-as pass is indeed not able to handle this. The first `__release` depends on the earlier `__retain` to be valid, but the inference cannot be observed due to dealing with aliases, in turn leading to invalid elimination of the `__retain`. As such this makes me wonder if https://github.com/AssemblyScript/assemblyscript/pull/1260 would help, or if we really need actual alias analysis.

**Comment by dcodeIO** [comment]
To be sure, I also tested with the Binaryen PR linked above, and found that it doesn't solve the issue.

**Comment by dcodeIO** [comment]
Have been looking into a fix that would have been a breaking change, but after inspecting the fixtures figured that the particular approach I tried is not worth it compared to just disabling the pass. So, the linked PR above instead disables aggressive ARC optimizations for now, which seems reasonable to do given that there's still no fix in sight.

**Comment by dcodeIO** [comment]
This issue should have been resolved a while ago by switching to a new GC implementation.
