### ISSUE TITLE
RuntimeError: memory access out of bounds (string.length)

### ISSUE THREAD

**Issue by CalebOh01** [AssemblyScript/assemblyscript#1291]
This line is raising an error:
https://github.com/AssemblyScript/assemblyscript/blob/5c9cd70ecf4c62b188930a8c8a9a910ae67b893f/std/assembly/string.ts#L48

I am trying to run this code in a WebAssembly module and am getting an error in string.ts:48. I modified my code to remove any reference to string.length, but I am still receiving the same error after clearing my cache. 

```typescript
// The entry file of your WebAssembly module.

export function squiggle(sequence: string, length: i32): Array<Array<number>> {
  let x = [0.0]
  let y = [0.0]
  let yCoord = 0.0
  let xCoord = 0.0

  for (let _i: number = 0; _i < length; _i++) {
    let character = sequence.charAt(i32((_i)))
    x.push(xCoord+0.5)
    x.push(xCoord + 1.0)
    xCoord+=1
    if (character == "A") {
      y.push(yCoord + 0.5)
      y.push(yCoord)
    } else if (character == "C") {
      y.push(yCoord - 0.5)
      y.push(yCoord)
    } else if (character == "T") {
      y.push(yCoord - 0.5)
      y.push(yCoord - 1)
      yCoord -= 1.0
    } else if (character == "G") {
      y.push(yCoord + 0.5)
      y.push(yCoord + 1)
      yCoord += 1.0
    } else {
      y.push(yCoord)
      y.push(yCoord)
    }
  }
  let result: Array<Array<number>> = []
  result.push(x)
  result.push(y)
  return result
}

```

I am running AssemblyScript Version 0.10.0-nightly.20200517

**Comment by MaxGraey** [comment]
First of all you could simplify your example:
https://webassembly.studio/?f=mhqquo8pi8i

Could you provide additional info? How you call `squiggle` on host side? Perhaps you don't properly use loader or interop.

**Comment by Benjamin-Lee** [comment]
Here's a simple example which doesn't reproduce the error but also fails to work:

https://webassembly.studio/?f=u0ovkasz86

In this, we're using as-bind and have converted the function to return a single f64 array. When calling it, we're getting an int, not an array as expected.

We might be missing something really obvious here, since @CalebOh01 and I are new to AssemblyScript. Do you have any pointers (pun intended) for what we can do?

**Comment by MaxGraey** [comment]
@Benjamin-Lee 
I guess instead
```ts
let result = new Float64Array((2 * length) + 2)
for (let i = 0; i < length; i++){
  result[i] = x[i]
  result[i] = y[i]
}
return result
```
it should be
```ts
let result = new Float64Array(2 * length)
for (let i = 0; i < length; i++) {
  result[2 * i + 0] = x[i]
  result[2 * i + 1] = y[i]
}
return result
```

**Comment by Benjamin-Lee** [comment]
Ah yes, my mistake.

**Comment by Benjamin-Lee** [comment]
Good catch. Fixed in the fork: https://webassembly.studio/?f=v6m85lsgbtd

Still getting the same issue, though.

**Comment by MaxGraey** [comment]
I created fiddle with some method from `loader` for simulate full environment and don't see any issues:
https://webassembly.studio/?f=pf7yo5pymc
