### ISSUE TITLE
Strange Error Involving Resolver?

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#1292]
I am documenting the issue here so I can remember to get around to it.

Running as-pect tests on this commit file tree in the file Object3D.spec.ts file creates the problem. For some reason, it tries to assert that properties are on a parent class, when they obviously aren't.

https://github.com/lume/glas/pull/44/commits/96c965ea950ae31dc22bd70c1eacceec5759d50c

The console output is here:

https://github.com/lume/glas/runs/705122109

Not that the ranges here are off for some reason>

One thing to note: I went into one of the reflection functions while trying to debug this problem to do some logging, and I added a few branches for `isNullable<T>()` which yielded a strange error:

```ts
        if (isNullable(value)) {
          value!.__aspectAddReflectedValueKeyValuePairs(
            reflectedObjectID,
            seen,
            [] as StaticArray<i64>,
          );
        } else {
          value.__aspectAddReflectedValueKeyValuePairs(
            reflectedObjectID,
            seen,
            [] as StaticArray<i64>,
          );
        }
```

Which yielded some strange results. 

```ts
INFO AS210: Expression is never 'null'.

           value!.__aspectAddReflectedValueKeyValuePairs(
           ~~~~~
 in node_modules/@as-pect/assembly/assembly/internal/Reflect.ts(352,11)
```

Now of course, it could be possible that `value` in a previous flow eliminated the possibility for `T | null` but it had me very concerned that the resolver is somehow not resolving `T` correctly. Bugs like this are obviously very hard to debug so I will have to swing around to this again tomorrow.

**Comment by dcodeIO** [comment]
I know that you want to get back to it and I appreciate that you investigate the problem, but can you next time do so before opening an issue? Since it was opened, I tried to see if I can help already, but after fiddling with the code sample for some time was unable to unfortunately, figuring that I shouldn't have tried, but then started to question if we perhaps should make it more clear in the contributing guidelines that the tracker isn't for unfinished notes?

**Comment by jtenner** [comment]
Ah yeah. Good point. I will try not to use the issue tracker for personal notes.
