### ISSUE TITLE
global const optimization

### ISSUE THREAD

**Issue by blooddy** [AssemblyScript/assemblyscript#13]
```
const A:i32 = 1;
const B:i32 = A + 1;

export function test():i32 {
    return B;
}
```
output
```
// module.ts(2,15): warning TS/AS121: Compiling global with unsupported constant initializer expression as mutable.

(module
 (type $i (func (result i32)))
 (type $v (func))
 (global $B (mut i32) (i32.const 0))
 (memory $0 1)
 (export "test" (func $test))
 (export "memory" (memory $0))
 (start $.start)
 (func $test (; 0 ;) (type $i) (result i32)
  (get_global $B)
 )
 (func $.start (; 1 ;) (type $v)
  (set_global $B
   (i32.const 2)
  )
 )
)
```

**Comment by dcodeIO** [comment]
This seems like a bug and should actually be supported.

**Comment by dcodeIO** [comment]
Wait, are you using the prototype from npm? In master it should be `start` instead of `.start`.

**Comment by blooddy** [comment]
im using web http://assemblyscript.org/try/

**Comment by dcodeIO** [comment]
I see, that's still the prototype as well.

**Comment by blooddy** [comment]
Are you going to update the web version?

**Comment by dcodeIO** [comment]
Sure, going to do that eventually. Ideally once arrays and strings are implemented.

**Comment by dcodeIO** [comment]
AssemblyScript is now available as a template in [WebAssembly Studio](http://webassembly.studio/). Basically a better playground :)
