### ISSUE TITLE
Class support?

### ISSUE THREAD

**Issue by liangzeng** [AssemblyScript/assemblyscript#130]
```
class A{
  private money:int32;
  constructor(money:int32){
    this.money = money;
  }
}

var a:A = new A(222); // Cannot read property 'type' of undefined
```

**Comment by dcodeIO** [comment]
This works for me when I `import "allocator/arena"` as explained [here](https://github.com/AssemblyScript/assemblyscript/wiki/Memory-Layout-&-Management#heap). Are you using latest master? Note that the version currently on npm is the old prototype.

**Comment by liangzeng** [comment]
can i use `npm i AssemblyScript/assemblyscript`  installed?

**Comment by dcodeIO** [comment]
Yes, that's the recommended way atm.
