### ISSUE TITLE
[HELP] Types extendability

### ISSUE THREAD

**Issue by bakasura980** [AssemblyScript/assemblyscript#1302]
Hi,
I need your help to understand if the following is possible?
```
type byte = u8;

const a: u8 = 1;
const b: byte = 0x01;

getInstance(a) => returns CustomU8
getInstance(b) => also returns CustomU8

function getInstance(value: T): string {
  if(nameof(value) === "u8"){
    return new CustomU8(value).toString();
  }

  if(nameof(value) === "byte"){
    return new CustomByte(value).toString();
  }

}
```

I need to declare a "byte" type or how I could know that my value is from type/alias "byte".

PS. If I create "byte" as a class then I should do the following, but I don't want this way of instantiation
```
// Will work but not wanted
const b: byte = new byte(0x01);

// Desired way of instantiation
const b: byte = 0x01;
```

**Comment by dcodeIO** [comment]
> `type byte = u8;`

This is possible, yeah. However, the underlying type will still be `u8` in this case, and there is no way to distinguish the alias from the aliased type, at least as far as I'm aware. Of course boxing an `u8` in different classes is possible as well, but the decision which class to make cannot depend on the basic type name.

**Comment by bakasura980** [comment]
@dcodeIO 
It depends on type name because of the abstraction. I need a base type to be assignable to my class

```
const value: CustomBool = true

//Need above to do
const values : Array<CustomBool> = [true, true ] 

Instead of

const values : Array<CustomBool> = [
new CustomBool(true), 
new CustomBool(true) 
]
```

**Comment by willemneal** [comment]
Best you can do is:

```ts
function customBoolArr(a: Array<boolean>): Array<CustomBool> {
  return a.map<CustomBool>(b => new CustomBool(b));
}
```
As currently you can't box a primitive by declaring it to be the boxed type.

**Comment by MaxGraey** [comment]
This will be a lot easier if TS support [nominal types by design](https://github.com/microsoft/TypeScript/issues/202)

**Comment by MaxGraey** [comment]
Btw we could implement this as experimental feature. @wdyt?
Syntax is not really meaningful. This for example suggested by me:
https://github.com/microsoft/TypeScript/issues/202#issuecomment-570842911
