### ISSUE TITLE
Investigate switching all of AS to ESM

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#1306]
While the CommonJS and ESM compatibility story in node appears to be a disaster still, ESM is getting more and more traction and since AS requires relatively modern environments anyway, we should aim at making the switch rather sooner than later.

Related issues: https://github.com/AssemblyScript/assemblyscript/issues/1207

**Comment by michailVestnik** [comment]
At the moment, this is still a very relevant question!
Deno supports TypeScript out of the box and a simpler and more concise solution for working with Web Assembly!
Is it possible to have two versions of AS, one for Node.js, and another for Deno?
where can I keep up-to-date information on this issue?

**Comment by vamsivishnu** [comment]
The vision is to be able to build/run Deno binaries from TypeScript and AssemblyScript source files, arbitrarily importing modules, supported natively in Deno. Really looking forward to seeing that vision realized.

**Comment by vjpr** [comment]
`npx asinit .` generates a commonjs Node package.

What is the status of Node.js ESM support? I expect there would need to be an [`--experimental-loader=xxx`](https://nodejs.org/api/esm.html#esm_resolve_specifier_context_defaultresolve) created. Has this been done?

**Comment by RefinedSoftwareLLC** [comment]
This might be related: 
[https://github.com/WebAssembly/binaryen/pull/4280](https://github.com/WebAssembly/binaryen/pull/4280)
[https://github.com/AssemblyScript/binaryen.js/releases/tag/v102.0.0-nightly.20211028-esm](https://github.com/AssemblyScript/binaryen.js/releases/tag/v102.0.0-nightly.20211028-esm)
