### ISSUE TITLE
[HELP] Reflection

### ISSUE THREAD

**Issue by bakasura980** [AssemblyScript/assemblyscript#1312]
Hello,

Is there a way to get class properties 
```
public f<T> (struct: T) {
      for(const key in struct) { // not compiled
            doSmth(struct[key])
      }
}
```

**Comment by MaxGraey** [comment]
Currently we don't support reflection like `Object.keys`. Btw `for in` / `for of` also is not supported yet.

**Comment by bakasura980** [comment]
@MaxGraey, there is no way to get class properties, right ?

**Comment by bakasura980** [comment]
Is there a way at least to figure out the type of class properties

**Comment by MaxGraey** [comment]
It depend on your needs. You could use `nameof<T>()` or `instanceof`

**Comment by willemneal** [comment]
If you really want it you have to add a transform pass checkout: https://github.com/near/near-sdk-as/blob/master/bindgen/src/transformer.ts

It's a bit messy, but the core of what you want to see is in JSONBindingsBuilder.  If you want to make your own I suggest: https://github.com/willemneal/visitor-as it helps with the tricker bits of making transformers. (though I still need to update it for version 0.10.0)
