### ISSUE TITLE
Maximum call stack size exceeded when compiling optimised code

### ISSUE THREAD

**Issue by alexvictoor** [AssemblyScript/assemblyscript#1324]
I get a weird error when compiling my code with optimisation flags **-O3 --noAssert**
Unfortunately I have not succeed reproducing the issue with a simple code fragment...
My codebase is in this repository:  https://github.com/alexvictoor/HdrHistogramJS

If I run "npm run asbuild:optimized" adding a **--noAssert** flag compilation fails.
If I remove the [call to clz()](https://github.com/alexvictoor/HdrHistogramJS/blob/master/assembly/Histogram.ts#L263) and replace it by the commented code fragment below, everything is fine...

**Comment by dcodeIO** [comment]
@MaxGraey Is this a Binaryen issue or is there something wrong on our end?

**Comment by MaxGraey** [comment]
I don't know. It was my guess. Didn't play with it yet

**Comment by alexvictoor** [comment]
Thanks for your responses!
@MaxGraey compilation works fine with `--noAssert` and `-O3z`
Let me know if I can do something else to help

**Comment by alexvictoor** [comment]
> ```ts
> Math.abs(x - reinterpret<f64>(reinterpret<u64>(x) ^ 1))
> ```

Thanks for the tip!

**Comment by alexvictoor** [comment]
I have just tried v0.11
I get the same "Maximum call stack..." compilation error when I only use the `-O3` flag without the `--noAssert` flag.

**Comment by MaxGraey** [comment]
It will be really help if you somehow isolate a problem to minimal example. Your project is pretty big

**Comment by MaxGraey** [comment]
Btw it seems it's problem with generate sourcemaps. If I remove `--sourcemap` issue is gone.
@alexvictoor did you try this?

**Comment by MaxGraey** [comment]
So it seems this part in `std/portable.js`:
```
String["fromCharCodes"] = function fromCharCodes(arr) {
  return String.fromCharCode.apply(String, arr);
};
```
Cause to problem. Going to fix this.

**Comment by MaxGraey** [comment]
@alexvictoor btw [this](https://github.com/alexvictoor/HdrHistogramJS/blob/master/assembly/PercentileIterator.ts#L92) could be also optimized as:
```ts
const percentileReportingTicks = 
  this.percentileTicksPerHalfDistance *
  f64(1 << (31 - clz(i32(100 / (100 - this.percentileLevelToIterateTo))) + 1);
```
if `this.percentileLevelToIterateTo`  guaranteed in range [0, 99.9999999]. Btw I guess `percentileLevelToIterateTo` should have `i32` type.

**Comment by alexvictoor** [comment]
I have just tested v0.12 and the issue seems to have disappeared. 
Sorry again, it was quite difficult to isolate the problem...
Thanks @MaxGraey for the tips
