### ISSUE TITLE
Benchmark performance question

### ISSUE THREAD

**Issue by ncave** [AssemblyScript/assemblyscript#1326]
Not really an issue, more of a quick question. I'm probably doing something wrong, just wondering what am I doing wrong.

Testing performance with one of the samples `n-body` shows that running the same code on `TypeScript`-generated `JavaScript` is almost twice as fast than on `webassembly` generated by `AssemblyScript`:
```
Steps: 20_000_000, increment: 0.01

    JavaScript: Elapsed: 3.0 sec
AssemblyScript: Elapsed: 5.6 sec
```
Env: Node.js 14.4.0, Win10, AssemblyScript 0.10.0

Test repo: https://github.com/ncave/webasm-bench

Test steps: ```npm install && npm test```

P.S. I know `n-body`'s not a real benchmark, sorry about the clickbait.

**Comment by ncave** [comment]
@MaxGraey Since you mentioned it, here are the Rust-webasm results (without `--runtime none` for AS):
```fs
Steps: 20_000_000, increment: 0.01
    JavaScript: Elapsed: 2.932 sec, Energy: -0.16903264767107579
AssemblyScript: Elapsed: 3.509 sec, Energy: -0.16893859207630157
Rust to webasm: Elapsed: 1.700 sec, Energy: -0.16903264767107579
```
Thanks again for your help, I appreciate it!

**Comment by MaxGraey** [comment]
I see you use `f32` instead `f64`:
https://github.com/ncave/webasm-bench/blob/master/assembly/nbody_as.ts#L4

I guess better compare when all version use `f64` / number

**Comment by MaxGraey** [comment]
That's by the way pretty interesting! When type of float equal to `f32` instead `f64` on latest Chrome and FF it actually slower!

You could play in this fiddle: https://webassembly.studio/?f=yp7hc6vnct

For `type float = f32` on Chrome 83.0.4103.97:
```
dt: 2007.0299999788404 ms
```

For `type float = f64` on Chrome 83.0.4103.97:
```
dt: 1735.0549999973737 ms
```
So f64 math faster on `15%`. Similar on FF 77.

**Comment by MaxGraey** [comment]
I found why this actually happened. General code use `<float>Math.sqrt(...)` and when type float eqal to f32 that code translates to `f32(f64.sqrt(...))` instead `f32.sqrt(...)` that's why it slowdown compare to f64. So if you want using `f32` instead `f64` better use `Mathf.sqrt(...)` and even better and more generic intrinsic - `sqrt<float>(...)`

**Comment by ncave** [comment]
@MaxGraey Thanks, switching to f64 fixed the precision.
```
Steps: 20_000_000, increment: 0.01

    JavaScript: Elapsed: 2.9 sec, Energy: -0.16903264767107579
AssemblyScript: Elapsed: 3.4 sec, Energy: -0.16903264767107579
AS--no-runtime: Elapsed: 1.7 sec, Energy: -0.16903264767107579
Rust to webasm: Elapsed: 1.7 sec, Energy: -0.16903264767107579
```
For some reason Chrome 83 is quite slow for me in this benchmark, about 2x slower than FF 76.
But somehow Node.js is much closer to FF perf.

**Comment by MaxGraey** [comment]
btw in future with scalar replacement optimization we could avoid alloc / dealloc for such spenario at all and performance for full runtime will be the same as `AS--no-runtime` and Rust
