### ISSUE TITLE
How about add pedantic warning for twice initialized property? 

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#1344]
I noticed that some users often use the following pattern:
```ts
class Foo {
  constructor(public a: i32) {
    this.a = a;  // PEDANTIC: redundant assignment?
  }
}
```

**Comment by dcodeIO** [comment]
Looks like this depends on strict field initialization somewhat, so we know that it's already initialized in the first place. Would still be tricky in scenarios like the following, unless we can somehow represent this in flows.

```ts
  constructor(public a: i32) {
    a = somethingElse;
    this.a = a;
  }
```

**Comment by MaxGraey** [comment]
Yeah, perhaps without SSA form it could be hard to do, so perhaps it good candidate for eslint
