### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by liangzeng** [AssemblyScript/assemblyscript#135]
I want to contribute.
have any suggestions?  I am a typescript/javascript programmer.

I am reviewing compilers principles 😂

**Comment by dcodeIO** [comment]
You should have received an invite to the slack channel a while ago. Feel free to join the discussion :) Other than that, there are some [open issues](https://github.com/AssemblyScript/assemblyscript/issues) one could tackle, but just toying around with the compiler and reporting issues will also help a lot.
