### ISSUE TITLE
[Feature Request] isType<A,B>

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1352]
Currently you can write the following function:

```ts
@inline
function isType<A,B>(): bool {
  return nameof<A>() == nameof<B>();
}
```

This will be optimized to be a constant, however, it still allocates the string that ends up never being read.

**Comment by jtenner** [comment]
This is not a good way to determine type equality. You can use `idof<T>()`. It requires a few more compile time constants.

**Comment by jtenner** [comment]
```ts

function isType<A, B>(): bool {
  // if both sides are references
  if (isReference<A>() && isReference<B>()) {
    // if both are functions, idof is safe, no conflicts
    if (isFunction<A>() && isFunction<B>()) return idof<A>() == idof<B>();
    // if they are both not functions, idof is safe
    else if (!isFunction<A>() && !isFunction<B>()) return idof<A>() == idof<B>();
    // if both are references, and their ids don't match, they aren't the same type
    return false;
  }

  // floats only need to check size
  if (isFloat<A>() && isFloat<B>()) return sizeof<A>() == sizeof<B>();
  
  // booleans are the same type
  if (isBoolean<A>() && isBoolean<B>()) return true;

  // integers that aren't booleans can be the same type if their alignment and signed status are the same
  if (isInteger<A>() && !isBoolean<A>()) {
    // false positives for i32 and isize. How to fix this?
    if (isInteger<B>() && !isInteger<B>()) return alignof<A>() == alignof<B>() && isSigned<A>() == isSigned<B>();
  }
  
  return false;
}
```

**Comment by MaxGraey** [comment]
thinking about this again I guess this will be more optimal especially for when compare subclassed objects:
```ts
function isType<T, U>(): bool {
  if (isReference<T>() && isReference<U>()) {
    return idof<T>() == idof<U>();
  } else {
    let x: T;
    return x instanceof U;
  }
}
```

**Comment by jtenner** [comment]
> thinking about this again I guess this will be more optimal especially for when compare subclassed objects:
> 
> ```ts
> function isType<T, U>(): bool {
>   if (isReference<T>() && isReference<U>()) {
>     return idof<T>() == idof<U>();
>   } else {
>     let x: T;
>     return x instanceof U;
>   }
> }
> ```

This is incorrect, since function references pull from a different pool of ids.

Comparing a function type to a class type can have overlaps.

**Comment by MaxGraey** [comment]
>  since function references pull from a different pool of ids

Right! Fixed
