### ISSUE TITLE
[Help] Function reference from assemblyscript to importObject

### ISSUE THREAD

**Issue by apiel** [AssemblyScript/assemblyscript#1354]
Hello,

I am trying to get the reference of a callback function in assemblyscript passed as argument to an imported function, but doesn't work.

```ts
declare namespace core {
    function setTimeout(cb: () => void, ms: i32): i32;
}

export function main(): void {
    core.setTimeout(function cb() {
        // do something
    }, 1000);
}
```
Then I compile it `asc index.ts -b index.wasm --sourceMap --optimize`.
After I use `wabt` tools to convert my code to C with `wasm2c index.wasm -o index.c`.

If I search for the setTimeout declaration I get `u32 (*Z_indexZ_coreZ2EsetTimeoutZ_iii)(u32, u32);`.
As you can see the `cb` parameter became u32, seem to make sense [base on](https://www.assemblyscript.org/exports-and-imports.html#on-values-crossing-the-boundary):
> ![image](https://user-images.githubusercontent.com/5873198/85691703-0831eb80-b6d5-11ea-9b19-ddf3351f704b.png)

Now, if I try to read `cb` value, I get 1, this seem to be wrong for a reference. When I read the reference of a string, I always get much bigger number and never the same. I also tried to execute the reference in C but I get segmentation fault (that is not surprising):
```C
  void (*buf)();
  buf = (void (*)(void *))(WASM_RT_ADD_PREFIX(Z_memory)) + cb;
  (*buf)();
```
So either I miss understood the documentation and we can't have function as parameter of an imported function, or I made a mistake in the way to access the reference to the `cb` function.

Does anyone know what I am doing wrong?

**Comment by dcodeIO** [comment]
The value you are seeing there is the `WebAssembly.Table` index of the function, not a pointer into memory like is the case for strings. If the table contains just one function, `1` is the expected value with `0` representing `null`.

**Comment by apiel** [comment]
@dcodeIO it make sense ;-) Thx for the hint. Now I might ask you a question out of scope from AssemblyScript, but maybe you have an idea. Do you know how to access this `WebAssembly.Table`? Is it part of the shared memory (represented in wabt by Z_memory)? Would you even know how I could fix:

```C
  void (*buf)();
  buf = (void (*)(void *))(WASM_RT_ADD_PREFIX(Z_memory)) + cb;
  (*buf)();
```
I know it is completely out of scope and not easy. But I still give a try with asking, we never know :p

**Comment by dcodeIO** [comment]
I don't know how it can be accessed from C, but just like the memory the table can be exported with `--exportTable` if that helps. Might also be that there are `WASM_RT_` builtins to call a function indirectly, by function index, but just guessing.

**Comment by apiel** [comment]
@dcodeIO `--exportTable` did the trick, now I can see it in the code: `extern wasm_rt_table_t (*WASM_RT_ADD_PREFIX(Z_table));`

I still have to understand how this table work, but you already helped me a lot ;-) Thx

**Comment by apiel** [comment]
To fully answer my question:

```c
wasm_rt_table_t * table = WASM_RT_ADD_PREFIX(Z_table);
((void (*)(void))table->data[cb].func)();
```
Where cb is the index of the function.
