### ISSUE TITLE
[Question] Type Assertions as Compile Errors

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1356]
Consider the following:

```ts
getPrimitive<T>(key: string, defaultValue: T): T {
    if (isInteger<T>()) {
      const strValue = this.getString(key);
      return strValue == null ? defaultValue : util.parseFromString<T>(<string>strValue);
    } else {
      throw new Error("Operation not supported. Please use storage.get<T> for non-primitives");
    }
  }
```

If it is called with say `getPrimitive<string>("hello", "world")`, it compiles to always throw if called.  However, since the type assertion is made at compile time it should fail then and not at runtime.  Is there currently a way to ensure that type assertions become compile time errors?

**Comment by jtenner** [comment]
Use the `ERROR()` macro.
