### ISSUE TITLE
Feature request: encodeInto

### ISSUE THREAD

**Issue by RReverser** [AssemblyScript/assemblyscript#1359]
Currently there is a `decodeUnsafe` method in the Encoding API that allows to decode strings directly from a given pointer, but there isn't a way to encode a string directly into a given pointer, without an intermediately allocated `ArrayBuffer`.

I believe such API would be useful for performance reasons when frequently dealing with strings. `TextEncoder::encodeInto` Web API can be used as an inspiration / motivational example.

**Comment by RReverser** [comment]
Just after submitting the issue, I've looked at the code, and it appears that `encodeUnsafe` already exists? https://github.com/AssemblyScript/assemblyscript/blob/0c02d019a2f9e7dade1293cb21d333645e7c6132/std/assembly/string.ts#L687

In that case this becomes a documentation issue, since it's not mentioned under https://www.assemblyscript.org/stdlib/string.html#encoding-api.

**Comment by dcodeIO** [comment]
Thanks, the unsafe encoding API has indeed been added somewhat later down the road, and I missed to add it to the docs. PR above adds it!
