### ISSUE TITLE
[QUESTION/BUG] [RuntimeError: unreachable] JS when exporting Array

### ISSUE THREAD

**Issue by bakasura980** [AssemblyScript/assemblyscript#1365]
Hello,

**Version**: assemblyscript@0.12.5 / @assemblyscript/loader@0.10.1
**Summary**: Everything compiles and tests pass but when WASM get loaded into JS and started, the result is always 
```
RuntimeError: unreachable
```
**Occurrence**: That behavior happens only when I export Array. If my class does not extend Array, the code works

**Code**: 
**npm-my-package**
```
export class MyArr extends Array<u8>{

    constructor () {
        super(32);
    }

    public doSmth (): u8[] {
        return [1, 2, 3];
    }
   
     /* Skip warnings */
     // @ts-ignore
     map (callbackfn: (value: u8, index: i32, array: Array<u8>) => u8): Array<u8> {
        return super.map<u8>(callbackfn);
     }

     // @ts-ignore
     reduce (callbackfn: (previousValue: u8, currentValue: u8, currentIndex: i32, array: Array<u8>) => u8, initialValue: u8): u8 {
        return super.reduce<u8>(callbackfn, initialValue);
     }

      // @ts-ignore
      reduceRight (callbackfn: (previousValue: u8, currentValue: u8, currentIndex: i32, array: Array<u8>) => u8, initialValue: u8): u8 {
        return super.reduceRight<u8>(callbackfn, initialValue);
      }
}
```
**another-project**
```
import { MyArr } from "npm-my-package";

export function doSmth (): u8[] {
    const myArr = new MyArr();
    return myArr.doSmth();
}
```

**JavaScript**
```
const fs = require("fs");
const loader = require("@assemblyscript/loader");

const imports = {
    env: {
        abort (_msg, _file, line, column) {
            console.error("abort called at index.ts:" + line + ":" + column);
        }
    }
};

const instance = loader.instantiateSync(fs.readFileSync(__dirname + "/build/example.wasm"), imports).exports;

(async () => {
    console.log(doSmth());
})();

function doSmth () {
    let fnPtr = instance.doSmth();
    let result = instance.__getArray(fnPtr);
    instance.__release(fnPtr);

    return result;
}
```

**Comment by MaxGraey** [comment]
What if you don't call `instance.__release(fnPtr)` on JS side?

**Comment by bakasura980** [comment]
It throws on this row and does not even hit `instance.__release(fnPtr)`

```
let fnPtr = instance.doSmth();
```

**Comment by bakasura980** [comment]
If they are in the same package, the error is gone

**Comment by MaxGraey** [comment]
cc @willemneal could you look at this?

**Comment by MaxGraey** [comment]
Also I have assumption it could be some mess with class ids.
@bakasura980  could you try `instance.__getUint8Array` instead `instance.__getArray`?

**Comment by willemneal** [comment]
Do you have repo for this?  If so I'd check it out.  I tried using webassemblystudio, but it doesn't use the loader so it doesn't have `__getArray` etc, however, I was able to make it past the line you are failing on.

**Comment by bakasura980** [comment]
Here you can play with that - https://github.com/LimeChain/as-scale-codec/tree/upgrade-packages
Clone it and change to upgrade-packages branch.
There is 'example' folder inside. Once dependencies are installed, try to run it and you will see the error

**Comment by bakasura980** [comment]
Hey guys @willemneal, @MaxGraey , did you have time to check out the repo? I am not sure if the error is because of the loader or maybe there are some changes in the way allocation works. I mean, this example used to work with v0.9.4

**Comment by willemneal** [comment]
I just dug into it a little bit but didn't get the same error you did.

```
abort called at index.ts:122:14
(node:29955) UnhandledPromiseRejectionWarning: RuntimeError: unreachable
    at ~lib/rt/pure/decrement (wasm-function[39]:0x1ae3)
    at ~lib/rt/pure/__visit (wasm-function[40]:0x1bb0)
    at ~lib/rt/pure/decrement (wasm-function[39]:0x1b41)
    at ~lib/rt/pure/__release (wasm-function[11]:0x8b1)
    at assembly/index/encodeString (wasm-function[30]:0x14c6)
    at Object.curr.<computed> [as encodeString] (/Users/willem/c/tmp/as-scale-codec/example/node_modules/@assemblyscript/loader/index.js:418:18)
    at encodeString (/Users/willem/c/tmp/as-scale-codec/example/index.js:29:26)
    at /Users/willem/c/tmp/as-scale-codec/example/index.js:16:17
    at Object.<anonymous> (/Users/willem/c/tmp/as-scale-codec/example/index.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
(node:29955) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29955) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After examining the code my suspicion is that the error is due to how the new virtual table/abstract classes, handle the Ref Counting.

Also I had to fix the index.js file so that the instance is 
```
const instance = loader.instantiateSync(fs.readFileSync(__dirname + "/build/example.wasm"), imports).exports;
```

**Comment by willemneal** [comment]
I've been lucky that my use case doesn't require RC and garbage collection so I'm not the best to help with this. However, I did make a PR with my fixes https://github.com/LimeChain/as-scale-codec/pull/43

**Comment by bakasura980** [comment]
Hello guys @MaxGraey  and @willemneal , we played a lot and I believe we managed to find the problem. In our case to run the example, we have to use  
```
__retain();
```
By doing this we skip being garbage collected. Looking at the error message from above is it possible garbage collector to try releasing an undefined pointer or try releasing the same pointer twice ?

**Comment by ezdiy** [comment]
@bakasura980 You need to retain all instances that escape ASC, and release them explicitly when the js copy disappears. 

ASC and JS gc are separate, it doesn't "magically" work. For that, you'd need js proxy that wraps the ASC, with finalizer calling the __release. Neither ASC nor JS has standard support for this (can be hacked up if you have node.js finalizers, or ABI access at a lower level).
