### ISSUE TITLE
[BUG] `asc --version` now returns 0.0.0

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1379]
As the title says since the new semantic publishing was set up the version returned is `0.0.0`.

**Comment by dcodeIO** [comment]
The SDK had a similar issue that I was able to solve by building it [upon postversion](https://github.com/AssemblyScript/assemblyscript/blob/68db67947de8f114d1614566091dfefe7f8e4363/package.json#L70). Ideally there'd be a way to determine and update the version prior to publishing using semantic-release, but not sure if they support that.

**Comment by MaxGraey** [comment]
How about add custom script (or npm hook) which will trigger after `semantic-release` publish and write ver string to some `version.json` file for example? Or is there an easier way?

**Comment by dcodeIO** [comment]
We can'd modify the package anymore after it has been published, unfortunately. Also, dist files can't load a separate file via `require` or similar but must bundle everything for browser usage. Best integration point I found so far is `postversion`, which executes exactly in between determining the version and publishing the package during execution of semantic-release.

**Comment by dcodeIO** [comment]
Their docs for reference: [How can I use a npm build script that requires the package.json’s version ?](https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-use-a-npm-build-script-that-requires-the-package-jsons-version)
