### ISSUE TITLE
Releasing reference to array of strings pointer throws error

### ISSUE THREAD

**Issue by sidx1024** [AssemblyScript/assemblyscript#1387]
I'm calling a function that takes an array of strings and returns an array of strings. The issue occurs when I release reference to the array.

```ts
// AssemblyScript
export function reverseArray(arr: string[]): string[] {
  return arr.reverse()
}
export const StringArray_ID = idof<string[]>()
```
```js
function doReverseArray(values) {
  const strPtr = values.map((string) => __retain(__allocString(string)))
  const arrPtr = __retain(__allocArray(StringArray_ID, strPtr))

  const outArrPtr = reverseArray(arrPtr)

  strPtr.forEach(__release)
  __release(arrPtr)

  const outStrPtr = __getArray(outArrPtr)
  const output = outStrPtr.map(__getString)

  outStrPtr.forEach(__release)
  __release(outArrPtr)
      // ^ Error: abort:  at ~lib/rt/pure.ts:122:14
      //     at abort (/project/node_modules/@assemblyscript/loader/index.js:73:11)
      //     at ~lib/rt/pure/decrement (wasm-function[29]:0x18a5)
      //     at ~lib/rt/pure/__visit (wasm-function[30]:0x1946)
      //     at ~lib/array/Array<~lib/string/String>#__visit_impl (wasm-function[31]:0x1985)
      //     at ~lib/rt/__visit_members (wasm-function[33]:0x1a0b)
      //     at ~lib/rt/pure/decrement (wasm-function[29]:0x18b7)
      //     at ~lib/rt/pure/__release (wasm-function[13]:0xbfd)
      //     at curr.<computed> (/project/node_modules/@assemblyscript/loader/index.js:418:18)
      //     at doReverseArray (/project/index.js:107:7)
      //     at /projectindex.js:112:17

  return output
}

console.log(doReverseArray(['April', 'March', 'February', 'January']))
```

**Comment by MaxGraey** [comment]
Just don't `outStrPtr.forEach(__release)`. `__release` already decrement and deallocate all children associated to root reference.

[See playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWZ1bGwKZXhwb3J0IGZ1bmN0aW9uIHJldmVyc2VBcnJheShhcnI6IHN0cmluZ1tdKTogc3RyaW5nW10gewogIHJldHVybiBhcnIucmV2ZXJzZSgpCn0KCmV4cG9ydCBjb25zdCBTdHJpbmdBcnJheV9JRCA9IGlkb2Y8c3RyaW5nW10+KCkKIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KCmZ1bmN0aW9uIGRvUmV2ZXJzZUFycmF5KHZhbHVlcywgCiAgewogICAgU3RyaW5nQXJyYXlfSUQsIAogICAgX19hbGxvY1N0cmluZywKICAgIF9fYWxsb2NBcnJheSwKICAgIF9fZ2V0QXJyYXksCiAgICBfX2dldFN0cmluZywKICAgIF9fcmV0YWluLAogICAgX19yZWxlYXNlLAoKICAgIHJldmVyc2VBcnJheQogIH0pIHsKICBjb25zdCBzdHJQdHIgPSB2YWx1ZXMubWFwKHN0ciA9PiBfX3JldGFpbihfX2FsbG9jU3RyaW5nKHN0cikpKQogIGNvbnN0IGFyclB0ciA9IF9fcmV0YWluKF9fYWxsb2NBcnJheShTdHJpbmdBcnJheV9JRCwgc3RyUHRyKSkKCiAgY29uc3Qgb3V0QXJyUHRyID0gcmV2ZXJzZUFycmF5KGFyclB0cikKCiAgLy8gc3RyUHRyLmZvckVhY2goX19yZWxlYXNlKQogIF9fcmVsZWFzZShhcnJQdHIpCgogIGNvbnN0IG91dFN0clB0ciA9IF9fZ2V0QXJyYXkob3V0QXJyUHRyKQogIGNvbnN0IG91dHB1dCA9IG91dFN0clB0ci5tYXAoX19nZXRTdHJpbmcpCgogIG91dFN0clB0ci5mb3JFYWNoKF9fcmVsZWFzZSkKICBfX3JlbGVhc2Uob3V0QXJyUHRyKQoKICByZXR1cm4gb3V0cHV0Cn0KCmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwge30pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0Jyk7CiAgICBjb25zdCBpbnB1dEFyciA9IFsnQXByaWwnLCAnTWFyY2gnLCAnRmVicnVhcnknLCAnSmFudWFyeSddOwogICAgY29uc3Qgb3V0cHV0QXJyID0gZG9SZXZlcnNlQXJyYXkoaW5wdXRBcnIsIGV4cG9ydHMpOwogICAgb3V0cHV0LnZhbHVlID0gb3V0cHV0QXJyLnRvU3RyaW5nKCk7CiAgfSkKPC9zY3JpcHQ+)

**Comment by dcodeIO** [comment]
The only references the JS side needs to hold on to in the snippet above are `arrPtr` and `outArrPtr`, because __getArray and __getString copy from Wasm memory to JS objects, so no refs on the JS-side there. Also, __allocArray already retains the elements one adds, so the allocation part can be simplified:

```ts
function doReverseArray(values) {
  const arrPtr = __retain(__allocArray(StringArray_ID, // wants release
    values.map((string) => __allocString(string))
  ))
  const outArrPtr = reverseArray(arrPtr) // wants release
  const output = __getArray(outArrPtr).map(__getString)
  __release(arrPtr)
  __release(outArrPtr)
  return output
}
```

**Comment by sidx1024** [comment]
@MaxGraey @dcodeIO Got it. Thanks for the quick response!
