### ISSUE TITLE
How can i get ptr of a string?

### ISSUE THREAD

**Issue by mohanson** [AssemblyScript/assemblyscript#1390]
My host environment provides the following extern functions for system call(It was written by ASM, and I am sure that this function signature cannot be modified), [source code here](https://github.com/mohanson/wasc/blob/update/src/platform/ckb_vm_assemblyscript.h#L69):

```ts
export declare function syscall(n: i64, a: i64, b: i64, c: i64, d: i64, e: i64, f: i64): i64;
```

Now I need to pass a string into this function, If I use c language and gcc to compile wasm code, then I can write c code as

```c
char *s = "Hello World!";
syscall(xx, &s[0], strlen(s), 0, 0, 0, 0);
```

They can be correctly executed by the wasm virtual machine after compilation, and the host can get the string's ptr and length, then restores the string from memory. 

But When I tried to use assemblyscript, the problem happened, I couldn't get the address of the string (or there is, but I don't know), Is there a solution?

Thanks!

**Comment by mohanson** [comment]
I tried as followings, but it could not be compiled.

```ts
// AssemblyScript code
export declare function syscall(n: i64, a: i64, b: i64, c: i64, d: i64, e: i64, f: i64): i64;

export function _start(): i32 {
  syscall(2192, "foo", 3, 0, 0, 0, 0);
  return 0;
}
```

**Comment by MaxGraey** [comment]
If your host environment expect non-null terminated UTF8 strrings:
```ts
const str = "Hello World!";
let strEncoded = String.UTF8.encode(str);
syscall(xx, , changetype<usize>(strEncoded), strEncoded.byteLength, 0, 0, 0);
```
with null termination:
```ts
const str = "Hello World!";
let strEncoded = String.UTF8.encode(str, true);
syscall(xx, , changetype<usize>(strEncoded), 0, 0, 0, 0);
```

**Comment by mohanson** [comment]
Great! It solved, thanks again.
