### ISSUE TITLE
start function optimization

### ISSUE THREAD

**Issue by blooddy** [AssemblyScript/assemblyscript#14]
```
function init():void {
}
init();
```
output
```
(module
 (type $v (func))
 (memory $0 1)
 (export "memory" (memory $0))
 (start $.start)
 (func $init (; 0 ;) (type $v)
  (nop)
 )
 (func $.start (; 1 ;) (type $v)
  (call $init)
 )
)
```
an unnecessary $.start function is created. 
most likely this will automatically be corrected if you add inline function support (#12)

**Comment by dcodeIO** [comment]
Yeah, the start function is automatically generated from all the top level statements. Running Binaryen's inlining pass will most likely optimize this away.

Once [this PR](https://github.com/WebAssembly/binaryen/pull/1357) lands in Binaryen, `asc` can support different optimization levels like `-O3` etc., which then include inlining.

**Comment by MaxGraey** [comment]
I think this can already be closed

**Comment by dcodeIO** [comment]
What' still happening, though, is that if the start function becomes empty after optimizations, it is not removed by the optimizer. Looks like:

```
  (func $start (type $t0)
    nop
  )
```

**Comment by MaxGraey** [comment]
Sorry. I checked in WebAssembly Studio and this true. But in Assembleash I use this config:
```js
 module.runPasses([ "trap-mode-clamp" ]);
 module.setOptimizeLevel(3);
 module.setShrinkLevel(2);
```

And this inlined perfectly. You can check

**Comment by dcodeIO** [comment]
Just checked: Try to compile just `;` (emulates the rest of the body being optimized away) - this results in the empty start function mentioned above.

**Comment by MaxGraey** [comment]
I try in my playground and this is result:

<img width="1025" alt="2018-02-28 17 38 49" src="https://user-images.githubusercontent.com/1301959/36796473-526853e2-1cae-11e8-98a4-84223e40d9d3.png">

**Comment by dcodeIO** [comment]
I see, yeah, the inlining works, but the start function is still there.

**Comment by MaxGraey** [comment]
But this is normal... or not?

**Comment by dcodeIO** [comment]
It is not required that it's there, so imho it should be removed.

**Comment by dcodeIO** [comment]
See: https://github.com/WebAssembly/binaryen/pull/1449

**Comment by MaxGraey** [comment]
Cool!

**Comment by dcodeIO** [comment]
Alright, the last remaining bits should be fixed as well using latest Binaryen. Closing for good.
