### ISSUE TITLE
Math.random Functionality

### ISSUE THREAD

**Issue by CFix-Ollie** [AssemblyScript/assemblyscript#140]
Pinpointed my crash to using Math.random(), and then I realised it's not included with the built-in Math class.

Any idea when/if it will be there, or if there's some kind of work around I could use to achieve the same functionality?

Sorry, I'm new to Web Assembly so not sure what the rules are..

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by trusktr** [comment]
Can we make the runtime by default call `NativeMath.seedRandom()` with a value from JSMath.random() times a big number and floored, or something? That way, we don't get an error by default, and if someone really wants to call seedRandom manually then they still can.

**Comment by fr33roam3r** [comment]
@CFix-Ollie I was looking around to find a solution to this very issue, and I found this section of code in lines `835`-`843` on the page of [this link](https://github.com/AssemblyScript/assemblyscript/blob/17f908f7005513b46c677147dedbc6598db8b912/tests/compiler/std/array.ts). It has worked for me, and I hope it does the same for you!

```javascript
NativeMath.seedRandom(reinterpret<u64>(JSMath.random()));

function createRandomOrderedArray(size: i32): Array<i32> {
  var arr = new Array<i32>(size);
  for (let i = 0; i < size; i++) {
    arr[i] = <i32>(NativeMath.random() * size);
  }
  return arr;
}
```

**Comment by MaxGraey** [comment]
If you use `loader` you don't need this explicit `seedRandom` call. But if you doesn't use AS outside of browser and can't use loader that's probably simplest solution.

**Comment by fr33roam3r** [comment]
_[Here's the reference for said `loader`.](https://www.assemblyscript.org/loader.html)_

**Comment by MaxGraey** [comment]
https://www.assemblyscript.org/exports-and-imports.html#anatomy-of-a-module
