### ISSUE TITLE
Add an AS Equivalent to Option in Rust to the AS Standard Library

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#1410]
One thing about AS is that [basic types cannot be nullable](https://www.assemblyscript.org/types.html#nullability). However, I've been designing some APIs that need some nullable Basic types, and I've been working around them. But I think it'd be cool just to write up a quick equivalent to [C#'s Nullable](https://docs.microsoft.com/en-us/dotnet/api/system.nullable-1?view=netcore-3.1) or [Rust's Option](https://doc.rust-lang.org/std/option/enum.Option.html).

I could super easily add this myself. I personally like C#'s interface more, but I think it should be named `Optional`. That way, it doesn't conflict with our already exisiting idea of nullability in the docs. 

What do y'all think @dcodeIO @MaxGraey @jtenner @sirwillem ? :smile:

**Comment by jtenner** [comment]
I believe that this feature requires multi-value returns, if I am not mistaken.

**Comment by MaxGraey** [comment]
> One thing about AS is that basic types cannot be nullable

It's just temporary limitation. And as @jtenner mentioned it's depend on multi-value proposal

**Comment by willemneal** [comment]
Here was what I made a year ago when I was working with WASI and wanted to get the result and the error:
https://github.com/WebAssemblyOS/wasmos/blob/a454ec8bd5b39253557745747c5d9120e18b9049/packages/assemblyscript/assembly/wasa/index.ts

As @jtenner points out multi-value means that we don't have to deal with an allocation each time, but that might be okay for now.

**Comment by torch2424** [comment]
Ahhhh that makes sense. I'll wait for that than, thanks everyone! :smile: :+1:
