### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by bartoszkrawczyk2** [AssemblyScript/assemblyscript#1413]
Hello!

I'm wondering about performance of AssemblyScript WASM. I'm trying to loop over an image to change pixel colors. On 4763 x 3175 image (Uint8Array length is 60490100) it takes **~140ms in js implementation**, and  **~300ms in AssemblyScript**.
I would expect around the same performance in WASM, but I'm probably doing something wrong.

Here is my pure js implementation:
```typescript
private draw = (exposure: number) => {
    const pow = Math.pow(2, exposure);

    for (let i = 0; i < this.newBuffer.length; i += 4) {
        this.newBuffer[i] = this.pixelData[i] * pow;
        this.newBuffer[i + 1] = this.pixelData[i + 1] * pow;
        this.newBuffer[i + 2] = this.pixelData[i + 2] * pow;
    }

    this.ctx.putImageData(new ImageData(this.newBuffer, this.state.width, this.state.height), 0, 0);
}
```
`this.pixelData` is `Uint8ClampedArray` with original image data and `this.newBuffer` is a copy.

Here is my AssemblyScript implementation:
```typescript
function clamp(value: f64): u8 {
    return u8(Math.max(Math.min(255, value), 0));
}

export function process(exposure: f64): void {
    const pow = JSMath.pow(2, exposure);
    const newImageIndex = endImageIndex + 1;
    
    for (let i: u32 = 0; i < endImageIndex; i = i + 4) {
        store<u8>(i + newImageIndex, clamp(load<u8>(i) * pow));
        store<u8>(i + 1 + newImageIndex, clamp(load<u8>(i + 1) * pow));
        store<u8>(i + 2 + newImageIndex, clamp(load<u8>(i + 2) * pow));
    }
}
```
Before that I'm filling the memory on js side (but it's done only once, so not counting when testing performance):
```typescript
this.memory = new Uint8Array(wasmModule.exports.memory.buffer);
const pixelData = new Uint8ClampedArray(this.ctx.getImageData(0, 0, this.img.width, this.img.height).data);

for (let i = 0; i < pixelData.length; i++) {
    this.memory[i] = pixelData[i];
}
```
And when I'm calling `process` function on js side I read from the memory:
```typescript
this.wasmModule.exports.process(exposure);
const index = this.wasmModule.exports.getEndIndex() + 1;
this.imageData.data.set(this.memory.slice(index, index + index)); // next chunk of memory with processed copy
this.ctx.putImageData(this.imageData, 0, 0);
```

Btw, when I tried to pass the data as an argument like this it was even worse (~1600ms):
```typescript
export function process(data: Uint8ClampedArray, exposure: f64): Uint8ClampedArray {
    const pow = JSMath.pow(2, exposure);
    let result = new Uint8ClampedArray(data.length);
    
    for (let i = 0; i < result.length; i = i + 4) {
        result[i] = clamp(data[i]) * pow;
        result[i + 1] = clamp(data[i + 1]) * pow;
        result[i + 2] = clamp(data[i + 2]) * pow;
        result[i + 3] = 255;
    }
    return result;
}
```

I'm new to AssemblyScript and WASM in general so I would appreciate any help.

**Comment by MaxGraey** [comment]
That's looks really unoptimal:
```ts
function clamp(value: f64): u8 {
    return u8(Math.max(Math.min(255, value), 0));
}

export function process(exposure: f64): void {
    const pow = JSMath.pow(2, exposure);
    const newImageIndex = endImageIndex + 1;
    
    for (let i: u32 = 0; i < endImageIndex; i = i + 4) {
        store<u8>(i + newImageIndex, clamp(load<u8>(i) * pow));
        store<u8>(i + 1 + newImageIndex, clamp(load<u8>(i + 1) * pow));
        store<u8>(i + 2 + newImageIndex, clamp(load<u8>(i + 2) * pow));
    }
}
```
try mutable `process`:
```ts
export function process(data: Uint8ClampedArray, exposure: f64): Uint8ClampedArray {
    const pow = JSMath.pow(2, exposure);
    
    for (let i = 0, len = result.length; i < len; i += 4) {
        unchecked(data[i + 0] = i32(data[i + 0] * pow));
        unchecked(data[i + 1] = i32(data[i + 1] * pow));
        unchecked(data[i + 2] = i32(data[i + 2] * pow));
    }
    return data;
}
```

Also compile with `-O3 --noAssert` instead `--optimize` for optimized (production) version

**Comment by MaxGraey** [comment]
There is also a possibility that it will not be possible to speed up this at all due to the fact that the interop between wasm <-> js will be much more expensive than you expected. Usually interop overhead is main bottleneck for such cases.

**Comment by bartoszkrawczyk2** [comment]
@MaxGraey Thanks for the reply. I was already using `-03` flag, after adding `--noAssert` I don't see much difference.

I understand that sharing data between wasm and js can be bottleneck, that's why I tried to fill the memory first and then just operate directly on memory.

Unfortunately I can't mutate it in this case, need non-destructive editing (each call of `process` should apply changes from the original data). Still, when tested it was similar performance to my implementation, so still a bit slower than js.

Thanks again for the help.

**Comment by MaxGraey** [comment]
You could usually speedup convolutions / blur but not filtering:
<img width="654" alt="Снимок экрана 2020-07-24 в 23 05 42" src="https://user-images.githubusercontent.com/1301959/88431104-559f9680-ce02-11ea-8bbd-b362c84ee80e.png">


From https://wasm-image-playground.now.sh/image-editor

**Comment by bartoszkrawczyk2** [comment]
That makes sense. I understand that real benefits can come when using more complex operations. Didn't expect much improvement, I was expecting around the same performance :) I will definitely test it on convolutions.

Thanks
