### ISSUE TITLE
decorator gets not called

### ISSUE THREAD

**Issue by exellian** [AssemblyScript/assemblyscript#1423]
```typescript
function sealed<T>(_constructor: T): void {
    console.log("Hallo welt!");
}

@sealed
class Lol {}
```
The assemblyscript file compiles successfully but I don't get an output. Are decorators even supported?

**Comment by MaxGraey** [comment]
Currently only [built-in decorators](https://www.assemblyscript.org/peculiarities.html#annotations) are supported

**Comment by exellian** [comment]
Is there a plan that someone can write custom decorators?

**Comment by MaxGraey** [comment]
Yes but It's not high priority in different reasons currently. First of all JS/TS decorators is not yes standardized. Next reason it's required some kind of macro system deeply integrated with AST which require some efforts for design and implementation. But AssemblyScript already has access to AST in slightly different manner - it's called transforms and already used by many projects for implement custom decorators. See offficial example:
https://github.com/AssemblyScript/examples/tree/master/transform

Also you may interesting in some utils like visitor helper:
https://github.com/willemneal/visitor-as

**Comment by exellian** [comment]
Thank you very much I think this will work!
