### ISSUE TITLE
Are tuples supported?

### ISSUE THREAD

**Issue by maskon** [AssemblyScript/assemblyscript#1425]
I installed AssemblyScript and found out that tuple support is missing.

Here is my code:

```ts
const data: [i32, f64] = [2, 9.9];
```

Are there any workarounds?

**Comment by MaxGraey** [comment]
No, tuples not supported yet.

> Are there any workarounds?

Any of next variants:
```ts
const data = [2, 9.9];  // deduced as `data: f64[]`
const data: f64[] = [2, 9.9];  // explicit declare of type
const data = [2, 9.9] as f64[];  // ^
const data = [2 as f64, 9.9]; // ^

// more efficient fixed sized arrays:
const data: StaticArray<f64> = [2, 9.9];
```

**Comment by maskon** [comment]
Thanks for the reply! Are there any plans to enable built-in support?

**Comment by MaxGraey** [comment]
Sure, but for efficiently implement tuples / records we waiting wide support for [multi-values](https://webassembly.org/roadmap/)

**Comment by maskon** [comment]
Great. Thanks for the help.

**Comment by trusktr** [comment]
[array](https://github.com/AssemblyScript/assemblyscript/pull/1788) [destructuring](https://github.com/AssemblyScript/assemblyscript/pull/2008) would be so so useful!
