### ISSUE TITLE
[Feature] Allow decorators on exports

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1426]
Currently I want to add a `@deprecated` to an export as a API was canged.

for example:

```ts
@deprecated
export { Storage as storage };
```
I expected that I could then check the export's node to see if it was decorated, however, before even getting to that I got the following error.

```ts
ERROR TS1206: Decorators are not valid here.

 @deprecated
 ~~~~~~~~~~~~
 in ../assembly/sdk/storage.ts(261,1)

```

**Comment by MaxGraey** [comment]
Isn't better use such decorator for `Storage` class instead over `export` keyword?

**Comment by willemneal** [comment]
But that suggests that the class is deprecated.  Though I could do,
```ts
@deprecated
export class storage extends Storage {}
```

However, in this case `Storage` has static methods, which wouldn't be imported.

**Comment by MaxGraey** [comment]
Ah, you want deprecate only alias `storage` but not `Storage`?

**Comment by MaxGraey** [comment]
How about this?
```ts
/** @deprecated */
type foo = Foo;

export { foo };
```

Btw it should support by TS language server.
