### ISSUE TITLE
How do I get this to work in visual studio?

### ISSUE THREAD

**Issue by Griffork** [AssemblyScript/assemblyscript#1428]
I have a custom build setup in visual studio (thus I can't use vs code) but I use typescript's normal language service. Adding assemblyscript to my build pipeline should be easy, but I'm stuck on how I could get assemblyscript's language service to be used by visual studio's intellisense? 

If there's a plugin for Visual Studio so that it can compile assembly script the same way typescript works that would be best (because I can override it in the project's build script).

Thanks!

**Comment by willemneal** [comment]
I'm familiar with VS code, but not visual studio, so I don't know the differences.  However, could you post your setup? You can now use `asconfig.json`, which could include the entry file you want to compile and its output file.  Then it's as simple as making the editor invoke `asc` in the project directory.

Not sure if this answers your question.  You can also use [asbuild](https://github.com/willemneal/asbuild), which makes assumptions about your project setup and should again be as easy as just invoking `asb` once it is on your path.

**Comment by Griffork** [comment]
@willemneal Visual Studio uses a closed-source typescript plugin to hook typescript's language service into intellisense as well as provide extra capabilities such as more language-specific refactor commands. Afaik it's not customisable outside of writing a plugin for Visual Studio, which is what I'm asking for.
