### ISSUE TITLE
Fixed size array

### ISSUE THREAD

**Issue by Tarnadas** [AssemblyScript/assemblyscript#143]
Apparently there is no support for fixed size arrays, e.g.

```js
class A {
  attr: [ int16, int16 ] = [ 0, 0 ];
}
```

won't compile.

Is support for this planned?

**Comment by dcodeIO** [comment]
Fixed size arrays like `int16[2]` are hard to get right due to TypeScript's syntax, but tuple types like `[i16, i16]` as in your example are something I'd like to have as well.

**Comment by Avamander** [comment]
I just stumbled upon the same issue.

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) as it seems to be fixed by the introduction of `StaticArray<T>`, even though that's not really tuples.
