### ISSUE TITLE
CapNProto support

### ISSUE THREAD

**Issue by unicomp21** [AssemblyScript/assemblyscript#1441]
Protobuf support would be nice as well, but think this will be easier and run faster.

Ideally the CapNProto schema w/ annotations can be used to codegen the await'able (fiber based) channels referenced in:
https://github.com/AssemblyScript/assemblyscript/issues/1440

**Comment by dcodeIO** [comment]
I don't see how CapNProto, or protobuf for that matter, are going to help the compiler specifically. Once we'll need serialization, we're likely going to build an optimized domain-specific implementation, and I'd expect CapNProto or protobuf to remain third-party packages. If you are interested in building such a package independently, that'd be great of course :)
