### ISSUE TITLE
Getting Started Guide - usage of asinit fails at npm test

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#1452]
The getting started guide starts by [creating a new project](https://www.assemblyscript.org/quick-start.html#setting-up-a-new-project):

~~~
npm init
npm install --save @assemblyscript/loader
npm install --save-dev assemblyscript
~~~

This creates a `package.json` file, and `node_modules` with the various AS dependencies installed.

The next step is asinit:

~~~
npx asinit .
~~~

This creates a scaffold project - updating `package.json` as part of the process. However, if a `tests` script already exists, this is untouched:

https://github.com/AssemblyScript/assemblyscript/blob/master/bin/asinit#L347

However, the `npm init` at the very start of the guide creates the following 'standard' script:

~~~
 "test": "echo \"Error: no test specified\" && exit 1"
~~~

As a result `npm test` fails after running `asinit`

**Comment by dcodeIO** [comment]
Oh, yeah, `asinit` skips updating fields in package.json that already have been set. Might want to make an exception for this exact pattern generated by npm.
