### ISSUE TITLE
How to create co-dependent classes?

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#1453]
Let's say I have two classes, each depending on the other:

~~~
export class Foo {
  bar: Bar;
};

export  class Bar {
  foo: Foo;
};
~~~

This yields the following error:

~~~
ERROR TS2564: Property 'assembly/foo/Bar.foo' has no initializer and is not assigned in the constructor before 'this' is used or returned.
~~~

I've tried converting to optional properties, but that fails as follows:

~~~
ERROR AS219: Optional properties are not supported.
~~~

**Comment by dcodeIO** [comment]
Definitive assignment should help in this case:

```ts
export class Foo {
  bar!: Bar;
};

export  class Bar {
  foo!: Foo;
};
```

Alternatively, a constructor can be provided to ensure that the fields are assigned.

**Comment by ColinEberhardt** [comment]
Definitive assignment is a TypeScript feature I was not aware of - works perfectly here, thanks.
