### ISSUE TITLE
Erroneously implementing Interface doesn't throw an error

### ISSUE THREAD

**Issue by Tarnadas** [AssemblyScript/assemblyscript#146]
```js
interface SomeInterface {
  someMethodWhichShouldBeImplemented: () => void;
}

class SomeClass implements SomeInterface {
  // no implementation of 'someMethodWhichShouldBeImplemented' here
}
```

This code would still compile instead of throwing an error.

**Comment by MaxGraey** [comment]
In Typescript world yes. But AS is ahead of time compiler and all methods should allow in compile time

**Comment by dcodeIO** [comment]
Note that interfaces aren't implemented yet. In order to be able to annotate them already (i.e. when sharing code with TS) the compiler simply doesn't emit errors.

**Comment by andy-hanson** [comment]
This is also a problem with `extends` in templates:
```ts
interface HasX { x: i32 }
function f<T extends HasX>(x: T): i32 {
	return x.x;
}

class C { x: i32; }
class D { D: boolean; }

export function test(c: C, d: D): i32 {
	return f(c) + f(d);
}
```

There is a compile error, but it happens inside the body of the function rather than at the call site `f(d)` which could be confusing if you don't know which caller is the problem.

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because seems to be outdated. Consider opening a new issue if necessary!
