### ISSUE TITLE
Generating C source code

### ISSUE THREAD

**Issue by jarble** [AssemblyScript/assemblyscript#1462]
Does AssemblyScript have an option to generate C source code instead of WebAssembly?

It seems that it would be possible to do this using [wasm2c](https://github.com/WebAssembly/wabt/tree/master/wasm2c), if AssemblyScript doesn't already have this feature.

**Comment by MaxGraey** [comment]
Currently not. Why not is already discussed in this similar issue: https://github.com/AssemblyScript/assemblyscript/issues/1429

**Comment by dcodeIO** [comment]
Other than that it's possible of course to use `wasm2c` on a WebAssembly binary generated using AssemblyScript, but it's not directly integrated.
