### ISSUE TITLE
Async/Await Support in the future

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#1468]
Was chatting with @RReverser after they gave their awesome Asyncify talk from Wasm Live! 

[Asyncify](https://kripken.github.io/blog/wasm/2019/07/16/asyncify.html) is a tool that binaryen provides. And given the nature of our JS background, would be cool if we could utilize Asyncify in some way to implement Async/Await.

More of an idea, that something actionable today. But worth considering for the future! :smile:

**Comment by MaxGraey** [comment]
Hey, I guess we already discuss about this [here](https://github.com/AssemblyScript/assemblyscript/issues/376) or in slack long time ago. Asyncify  definitely useful but only for cross module boundary. Internally we picked use asymmetric stackless coroutines which first of all be a construction block for generators which will utilize by async/await =)

**Comment by torch2424** [comment]
@MaxGraey 

Ah! Thanks for calling out #376 ! And thanks for expanding on it! I'll close this issue as a duplicate! Thanks :smile:

**Comment by MaxGraey** [comment]
No problem)
