### ISSUE TITLE
Add Error Index

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1472]
Currently rust provides a page that has examples for each compiler error: https://doc.rust-lang.org/error-index.html

For example,

# E0107
An incorrect number of generic arguments were provided.

Erroneous code example:

```rust
struct Foo<T> { x: T }

struct Bar { x: Foo }             // error: wrong number of type arguments:
                                  //        expected 1, found 0
struct Baz<S, T> { x: Foo<S, T> } // error: wrong number of type arguments:
                                  //        expected 1, found 2

fn foo<T, U>(x: T, y: U) {}
fn f() {}

fn main() {
    let x: bool = true;
    foo::<bool>(x);                 // error: wrong number of type arguments:
                                    //        expected 2, found 1
    foo::<bool, i32, i32>(x, 2, 4); // error: wrong number of type arguments:
                                    //        expected 2, found 3
    f::<'static>();                 // error: wrong number of lifetime arguments
                                    //        expected 0, found 1
}
```

They even let you run the code in a sandbox to see the error in action!

**Comment by Suket-shah** [comment]
Hey! I am a CS student in college and I am interested in contributing to the open-source community. This is my first time trying to make contributions and I came across this issue due to its good first issue label. I wanted to see if there was a more in-depth explanation of what I could do to resolve this issue!

**Comment by willemneal** [comment]
Hey @Suket-shah!  Glad to see you want to help. Here [are the diagnostic messages](https://github.com/AssemblyScript/assemblyscript/blob/master/src/diagnosticMessages.json)

and you can open a pull request to the [website.](https://github.com/AssemblyScript/website/blob/master/src/examples/snippets.md)

**Comment by OAyomide** [comment]
hi @willemneal any update on this? new to assemblyscript and i'd like to contribute. please let me know if this is still open or someone else is working on a PR. if still open, i'd love to make a PR for this.

**Comment by willemneal** [comment]
@OAyomide You're welcome to open a PR here: https://github.com/AssemblyScript/website 

Let me know if there is anything I can do to help.  The snippets link above should be a good example of how to add a new section to the website and use code snippets.

**Comment by OAyomide** [comment]
Hi @willemneal yes, the link above is helpful. However, i am confused. i created a file under src called error-index.md but i cannot see it show up anywhere in the browser when i refreshed the page.

am i missing anything? i cannot even see what i am doing to start with. sorry if this is a dumb question, i really dont understand.

**Comment by OAyomide** [comment]
Hi again @willemneal i've figured it out. i feel dumb right now. thank you. i'll ping you again if i need some help.
