### ISSUE TITLE
Runtime Error: Unreachable when using interface as variable type.

### ISSUE THREAD

**Issue by AfflatusX** [AssemblyScript/assemblyscript#1478]
I've create a simple repro here: https://webassembly.studio/?f=z7zujvqu2b

Say we have interface I, an abstract class A implements I, a concrete class C extends A.

if I do following:
```
let instance: I | null = null;

function run(): void {
  instance = new C();
  let temporary = instance;
  if (temporary != null) {
    temporary.call_some_function();
  }
}

run();
```

it would throw: Runtime Error: Unreachable.

However if I define instance as A instead of interface I, the code runs fine.

Is this a known problem?

**Comment by MaxGraey** [comment]
You got runtime error? When I try fiddle I got compiler error:
```
ERROR TS2322: Type 'main/IFace | null' is not assignable to type 'main/IFace'.

   let temp: IFace = instance;
                     ~~~~~~~~
 in main.ts(20,21)
```
As I know interfaces not implemented for some scenarios yet. Perhaps this one of unimplemented piece.

**Comment by AfflatusX** [comment]
Ah looks like save doesn't update the fork itself. I updated and re-forked:

https://webassembly.studio/?f=z7zujvqu2b

**Comment by MaxGraey** [comment]
Btw if it's not global everything works properly:
https://webassembly.studio/?f=qqt0jekrj7p

**Comment by AfflatusX** [comment]
@MaxGraey - I think that's because now the variable has Base as the type instead of the interface type. 

If you add : IFace on line 19, the same error happens. So I guess this is not a global vs. local issue?

**Comment by MaxGraey** [comment]
This works:
```ts
let instance: Instance = new Instance();
```
and this fail:
```ts
let instance: IFace = new Instance();
```
So it's definitely some unimplemented part of interfaces.
@dcodeIO know much more about this

**Comment by AfflatusX** [comment]
While I can use abstract class to work around this particular issue, https://github.com/AssemblyScript/assemblyscript/issues/1479 seems to be related but harder to work around.
