### ISSUE TITLE
Custom names for exports

### ISSUE THREAD

**Issue by lastmjs** [AssemblyScript/assemblyscript#1482]
Hey, I'm pretty new to AssemblyScript, and not sure how to achieve what I want and if AssemblyScript already supports this. Essentially I am trying to compile AssemblyScript to Wasm to deploy to ICP (DFINITY). They have their own language Motoko that they have good support for, and they are coming out with Rust and C SDKs. I think I can get this to work for AssemblyScript, following one of the C examples they've open-sourced. Here's what I'm trying to achieve: https://github.com/dfinity/examples/blob/master/c/qr/qr.c#L67

I do not understand the syntax there exactly. It seems as if the go function's export name is being set to "canister_update go". How can I achieve this in AssemblyScript? I have successfully compiled my AssemblyScript and deployed it to a local ICP node, but now I can't call into my function because I have not adequately marked it as a canister update function.

**Comment by MaxGraey** [comment]
AssemblyScript support custom external names only for imports via `@external(module, name)`. So you could do similar:
```ts
@external("canister_update go")
export function go(): void {
  ...
}
```
But this not support by AS currently. But you can write custom transform routine which made possible use `external` decorator for exports.

Useful examples how to use `transform`:
https://github.com/AssemblyScript/examples/tree/master/transform
https://github.com/willemneal/visitor-as

**Comment by lastmjs** [comment]
Perfect, so I simply have to change the export name? That's all that the C example I linked to is doing?

**Comment by MaxGraey** [comment]
yes, they are just replace `(export "go")` to `(export "canister_update go")`
