### ISSUE TITLE
Assertion error in `for` loop compilation

### ISSUE THREAD

**Issue by eventualbuddha** [AssemblyScript/assemblyscript#1483]
Some simple code I [transliterated from C](https://github.com/dlbeer/quirc/blob/7e7ab596e4d0988faf1c12ae89c354b114181c40/lib/identify.c#L178-L227) is failing to compile with an assertion error.

### Code

([load in assemblyscript.org editor](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPW5vbmUmaW1wb3J0TWVtb3J5JnVzZT1NYXRoPUpTTWF0aApjb25zdCBVSU5UOF9NQVggPSAoc2l6ZW9mPHU4PigpIDw8IDgpIC0gMQoKZXhwb3J0IGZ1bmN0aW9uIHRocmVzaG9sZChkYXRhOiBVaW50OEFycmF5KTogdTggewogIGNvbnN0IG51bVBpeGVscyA9IGRhdGEubGVuZ3RoCgogIC8vIENhbGN1bGF0ZSBoaXN0b2dyYW0KICBjb25zdCBoaXN0b2dyYW0gPSBuZXcgVWludDMyQXJyYXkoPGkzMj5VSU5UOF9NQVggKyAxKQogIGxldCBwdHIgPSAwCiAgbGV0IGxlbmd0aCA9IG51bVBpeGVscwogIHdoaWxlIChsZW5ndGgtLSkgewogICAgY29uc3QgdmFsdWUgPSBkYXRhW3B0cisrXQogICAgaGlzdG9ncmFtW3ZhbHVlXSsrCiAgfQoKICAvLyBDYWxjdWxhdGUgd2VpZ2h0ZWQgc3VtIG9mIGhpc3RvZ3JhbSB2YWx1ZXMKICBsZXQgc3VtOiB1MzIgPSAwCiAgZm9yIChsZXQgaTogdTggPSAwOyBpIDw9IFVJTlQ4X01BWDsgKytpKSB7CiAgICBzdW0gKz0gaSAqIGhpc3RvZ3JhbVtpXQogIH0KCiAgLy8gQ29tcHV0ZSB0aHJlc2hvbGQKICBsZXQgc3VtQjogaTMyID0gMAogIGxldCBxMTogaTMyID0gMAogIGxldCBtYXg6IGYzMiA9IDAKICBsZXQgdGhyZXNob2xkOiB1OCA9IDAKICBmb3IgKGxldCBpOiB1OCA9IDA7IGkgPD0gVUlOVDhfTUFYOyArK2kpIHsKICAgIC8vIFdlaWdodGVkIGJhY2tncm91bmQKICAgIHExICs9IGhpc3RvZ3JhbVtpXQogICAgaWYgKHExID09IDApIGNvbnRpbnVlCgogICAgLy8gV2VpZ2h0ZWQgZm9yZWdyb3VuZAogICAgcTIgPSBudW1QaXhlbHMgLSBxMQogICAgaWYgKHEyID09IDApIGJyZWFrCgogICAgc3VtQiArPSBpICogaGlzdG9ncmFtW2ldCiAgICBjb25zdCBtMTogZjMyID0gPGYzMj5zdW1CIC8gPGYzMj5xMQogICAgY29uc3QgbTI6IGYzMiA9IDxmMzI+KHN1bSAtIHN1bUIpIC8gPGYzMj5xMgogICAgY29uc3QgbTFtMjogZjMyID0gbTEgLSBtMgogICAgY29uc3QgdmFyaWFuY2U6IGYzMiA9IG0xbTIgKiBtMW0yICogPGYzMj5xMSAqIDxmMzI+cTIKICAgIGlmICh2YXJpYW5jZSA+PSBtYXgpIHsKICAgICAgdGhyZXNob2xkID0gaQogICAgICBtYXggPSB2YXJpYW5jZQogICAgfQogIH0KCiAgcmV0dXJuIHRocmVzaG9sZAp9CiMhaHRtbAo8Y2FudmFzIGlkPSJjYW52YXMiIHN0eWxlPSJ3aWR0aDogMTAwJTsgaGVpZ2h0OiAxMDAlIj48L2NhbnZhcz4KPHNjcmlwdD4KCi8vIFNldCB1cCB0aGUgY2FudmFzIHdpdGggYSAyRCByZW5kZXJpbmcgY29udGV4dApjb25zdCBjYW52YXMgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgiY2FudmFzIik7CmNvbnN0IGJvdW5kaW5nUmVjdCA9IGNhbnZhcy5nZXRCb3VuZGluZ0NsaWVudFJlY3QoKTsKY29uc3QgY3R4ID0gY2FudmFzLmdldENvbnRleHQoIjJkIik7CgovLyBDb21wdXRlIHRoZSBzaXplIG9mIHRoZSB2aWV3cG9ydApjb25zdCByYXRpbyAgPSB3aW5kb3cuZGV2aWNlUGl4ZWxSYXRpbyB8fCAxOwpjb25zdCB3aWR0aCAgPSAoYm91bmRpbmdSZWN0LndpZHRoICB8IDApICogcmF0aW87CmNvbnN0IGhlaWdodCA9IChib3VuZGluZ1JlY3QuaGVpZ2h0IHwgMCkgKiByYXRpbzsKY29uc3Qgc2l6ZSA9IHdpZHRoICogaGVpZ2h0Owpjb25zdCBieXRlU2l6ZSA9IHNpemUgPDwgMTsgLy8gZGlzY3JldGUgY29sb3IgaW5kaWNlcyBpbiByYW5nZSBbMCwgMjA0N10gKDIgYnl0ZXMgcGVyIHBpeGVsKQoKY2FudmFzLndpZHRoICA9IHdpZHRoOwpjYW52YXMuaGVpZ2h0ID0gaGVpZ2h0OwoKY3R4LnNjYWxlKHJhdGlvLCByYXRpbyk7CgovLyBDb21wdXRlIHRoZSBzaXplIChpbiBwYWdlcykgb2YgYW5kIGluc3RhbnRpYXRlIHRoZSBtb2R1bGUncyBtZW1vcnkuCi8vIFBhZ2VzIGFyZSA2NGtiLiBSb3VuZHMgdXAgdXNpbmcgbWFzayAweGZmZmYgYmVmb3JlIHNoaWZ0aW5nIHRvIHBhZ2VzLgpjb25zdCBtZW1vcnkgPSBuZXcgV2ViQXNzZW1ibHkuTWVtb3J5KHsgaW5pdGlhbDogKChieXRlU2l6ZSArIDB4ZmZmZikgJiB+MHhmZmZmKSA+Pj4gMTYgfSk7CmNvbnN0IGJ1ZmZlciA9IG5ldyBVaW50MTZBcnJheShtZW1vcnkuYnVmZmVyKTsKY29uc3QgaW1hZ2VEYXRhID0gY3R4LmNyZWF0ZUltYWdlRGF0YSh3aWR0aCwgaGVpZ2h0KTsKY29uc3QgYXJnYiA9IG5ldyBVaW50MzJBcnJheShpbWFnZURhdGEuZGF0YS5idWZmZXIpOwoKbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7CiAgZW52OiB7CiAgICBtZW1vcnkKICB9Cn0pLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CgogIC8vIFVwZGF0ZSBzdGF0ZQogIGV4cG9ydHMudXBkYXRlKHdpZHRoLCBoZWlnaHQsIDQwKTsKCiAgLy8gVHJhbnNsYXRlIDE2LWJpdCBjb2xvciBpbmRpY2VzIHRvIGNvbG9ycwogIGZvciAobGV0IHkgPSAwOyB5IDwgaGVpZ2h0OyArK3kpIHsKICAgIGNvbnN0IHl4ID0geSAqIHdpZHRoOwogICAgZm9yIChsZXQgeCA9IDA7IHggPCB3aWR0aDsgKyt4KSB7CiAgICAgIGFyZ2JbeXggKyB4XSA9IGNvbG9yc1tidWZmZXJbeXggKyB4XV07CiAgICB9CiAgfQoKICAvLyBSZW5kZXIgdGhlIGltYWdlIGJ1ZmZlci4KICBjdHgucHV0SW1hZ2VEYXRhKGltYWdlRGF0YSwgMCwgMCk7Cn0pOwoKLyoqIENvbXB1dGVzIGEgbmljZSBzZXQgb2YgY29sb3JzIHVzaW5nIGEgZ3JhZGllbnQuICovCmZ1bmN0aW9uIGNvbXB1dGVDb2xvcnMoKSB7CiAgY29uc3QgY2FudmFzID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgiY2FudmFzIik7CiAgY2FudmFzLndpZHRoID0gMjA0ODsKICBjYW52YXMuaGVpZ2h0ID0gMTsKICBjb25zdCBjdHggPSBjYW52YXMuZ2V0Q29udGV4dCgiMmQiKTsKICBjb25zdCBncmQgPSBjdHguY3JlYXRlTGluZWFyR3JhZGllbnQoMCwgMCwgMjA0OCwgMCk7CiAgZ3JkLmFkZENvbG9yU3RvcCgwLjAwLCAiIzAwMDc2NCIpOwogIGdyZC5hZGRDb2xvclN0b3AoMC4xNiwgIiMyMDY4Q0IiKTsKICBncmQuYWRkQ29sb3JTdG9wKDAuNDIsICIjRURGRkZGIik7CiAgZ3JkLmFkZENvbG9yU3RvcCgwLjY0MjUsICIjRkZBQTAwIik7CiAgZ3JkLmFkZENvbG9yU3RvcCgwLjg1NzUsICIjMDAwMjAwIik7CiAgY3R4LmZpbGxTdHlsZSA9IGdyZDsKICBjdHguZmlsbFJlY3QoMCwgMCwgMjA0OCwgMSk7CiAgcmV0dXJuIG5ldyBVaW50MzJBcnJheShjdHguZ2V0SW1hZ2VEYXRhKDAsIDAsIDIwNDgsIDEpLmRhdGEuYnVmZmVyKTsKfQoKY29uc3QgY29sb3JzID0gY29tcHV0ZUNvbG9ycygpOwo8L3NjcmlwdD4=))
```ts
const UINT8_MAX = (sizeof<u8>() << 8) - 1

export function threshold(data: Uint8Array): u8 {
  const numPixels = data.length

  // Calculate histogram
  const histogram = new Uint32Array(<i32>UINT8_MAX + 1)
  let ptr = 0
  let length = numPixels
  while (length--) {
    const value = data[ptr++]
    histogram[value]++
  }

  // Calculate weighted sum of histogram values
  let sum: u32 = 0
  for (let i: u8 = 0; i <= UINT8_MAX; ++i) {
    sum += i * histogram[i]
  }

  // Compute threshold
  let sumB: i32 = 0
  let q1: i32 = 0
  let max: f32 = 0
  let threshold: u8 = 0
  for (let i: u8 = 0; i <= UINT8_MAX; ++i) {
    // Weighted background
    q1 += histogram[i]
    if (q1 == 0) continue

    // Weighted foreground
    q2 = numPixels - q1
    if (q2 == 0) break

    sumB += i * histogram[i]
    const m1: f32 = <f32>sumB / <f32>q1
    const m2: f32 = <f32>(sum - sumB) / <f32>q2
    const m1m2: f32 = m1 - m2
    const variance: f32 = m1m2 * m1m2 * <f32>q1 * <f32>q2
    if (variance >= max) {
      threshold = i
      max = variance
    }
  }

  return threshold
}
```

### Failure

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1938/94950219-1c854180-0497-11eb-8e15-471b7ddacdb8.png">

### Notes

I tried converting to a `while` loop, which also has an assertion failure. I tried refactoring to remove the `break` and `continue` statements, but that version also has an assertion failure. I tried hoisting the variable declarations out of the loop, but it still fails. Removing the line indicated by surrounding comments, `threshold = i`, makes it compile.

I'm assuming there are issues with my types, but this feels like a bug with AssemblyScript. Or a sub-par error message 😉

**Comment by MaxGraey** [comment]
Reduced example:
```ts
export function threshold(): void {
  let y: u8 = 0
  for (let i: u8 = 0; i < 255; ++i) {
    y = i
  }
}
```
Interesting part if you change type of `y` (threshold) from `u8` to `i32` it will compile properly

cc @dcodeIO

**Comment by MaxGraey** [comment]
Btw instead `const UINT8_MAX = (sizeof<u8>() << 8) - 1` you could just use `u8.MAX_VALUE`

**Comment by dcodeIO** [comment]
Hmm, the unification failing in simple scenarios like these is worrisome. In fact that mechanism is something we should get rid of in favor of something better, because recompiling code under different assumptions is, as can be seen here, fragile. Like, this used to work I believe, and I can't tell what unrelated change broke it.

For SMI wrapping, a better mechanism would be to inject a SMI wrap at the top of the loop body to unify. Unfortunately this doesn't work for nullability, where it is necessary to reevaluate the body to see if something became null within the loop that must now trigger a diagnostic:

```ts
var maybeNull: string | null = "a";
while (condition) {
  maybeNull.length; // first iteration is ok, second is an error
  maybeNull = null;
}
```

One reliable mechanism would be to unroll the first iteration of the loop if incompatible local states are detected, like so:

```ts
var maybeNull: string | null = "a";
if (condition) {
  maybeNull.length; // ok
  maybeNull = null;
  while (condition) {
    maybeNull.length; // error
    maybeNull = null;
  }
}
```

but this comes at a code size hit if the loop body is large. Alternatively, perhaps a way to do a dry recompile of a code region itself not affecting state, for the sole purpose of triggering potential diagnostics, and use an injected SMI wrap for wrapping states.

**Comment by dcodeIO** [comment]
Fwiw, a workaround for the time being should be:

```ts
export function threshold(): void {
  let y: u8 = 0
  for (let i: u8 = 0; i < 255; ++i) {
    y = i & 255 // compiles knows that y is wrapped
  }
}
```

**Comment by dcodeIO** [comment]
So what's happening here is:

```
first (before):
y = 0 / WRAPPED, NONNULL
i = 0 / WRAPPED, NONNULL

first (after):
y = i / WRAPPED, NONNULL
i = ++i / NONNULL ... losing WRAPPED state because ++i may overflow

triggers recompile with i not WRAPPED

second (before):
y = y1 / WRAPPED, NONNULL
i = i1 / NONNULL

second (after):
y = i / NONNULL ... losing WRAPPED state because i is not wrapped
i = ++i / NONNULL

triggers recompile with y not WRAPPED
assertion fails
```

Is a cascading effect between locals depending on each other, and it seems that if we keep this logic, we need to keep recompiling up to the point where local flags are unified. The `assert` is the bug.
