### ISSUE TITLE
Cannot instantiate AS class from JS

### ISSUE THREAD

**Issue by letmaik** [AssemblyScript/assemblyscript#1500]
https://www.assemblyscript.org/exports-and-imports.html#classes says that one can easily instantiate an AssemblyScript class from JS using:
```js
var bar = new myModule.foo.Bar()
bar.a = 2
console.log(bar.a)
```

I tried this but it doesn't seem to work. Accessing any field of the class instance returns `undefined`. The constructor call succeeds though. I slapped a `trace('foo')` inside it and that gets printed.

EDIT: I'm using as-bind, could that be the reason? Would it work without it?

**Comment by MaxGraey** [comment]
`as-bind`can't do this [according to supported-data-types on README (scroll to rightmost position of table)](https://github.com/torch2424/as-bind#supported-data-types). But better ask @torch2424

**Comment by torch2424** [comment]
@MaxGraey thanks for the ping! 😀

Yeah Max is correct, AsBind doesn't work with classes as it's not a supported type.

However, if your looking for a good workflow, @battlinegames wrote up and awesome wasmbyexample, example: https://wasmbyexample.dev/examples/classes/classes.assemblyscript.en-us.html

**Comment by letmaik** [comment]
OK I figured out what the issue was. My class has members that are typed arrays, and those I cannot access without as-bind, but as-bind doesn't support classes. This means I'm kinda stuck, except if I do my own plumbing to access the arrays. I think the AS docs are a bit misleading here as they give the impression that everything works magically, but in fact that's only the case for a few primitive types.

**Comment by torch2424** [comment]
> I think the AS docs are a bit misleading here as they give the impression that everything works magically, but in fact that's only the case for a few primitive types.

Which docs? The AsBind docs? Or the AssemblyScript docs? :o And which paragraph or section is misleading? :thinking:

**Comment by letmaik** [comment]
@torch2424 See the first post in this thread. I think the sample should have a note that this won't magically work with strings, typed arrays etc. Similar to https://www.assemblyscript.org/loader.html#custom-classes I guess.

**Comment by torch2424** [comment]
Ahhhh forsure! So this is more of a loader issue, awesome! Yeah that could be updated :smile: Feel free to open a PR with: 

https://github.com/AssemblyScript/website/edit/master/src/exports-and-imports.md
