### ISSUE TITLE
__setArgumentsLength is not exported with --runtime none

### ISSUE THREAD

**Issue by kungfooman** [AssemblyScript/assemblyscript#1502]
I am using `--runtime none` with a class that accepts one default argument, but `__setArgumentsLength` is not exported to deal with optional arguments.

I also tried this:

```ts
export { __alloc, __realloc, __retain, __setArgumentsLength };
```

It works for `__alloc`/`__realloc`/`__retain`, but not for `__setArgumentsLength`

Is `__setArgumentsLength` for `--runtime none` broken or is there any other way to specify the amount of arguments?

**Comment by MaxGraey** [comment]
`__setArgumentsLength` exported optionally only if exported function has optional arguments (actually with default vlaues).

**Comment by kungfooman** [comment]
Yea, that is the case for `--runtime full`, but `--runtime none` does not expose `__setArgumentsLength` for me

**Comment by dcodeIO** [comment]
Does `--runtime stub` expose it?

**Comment by kungfooman** [comment]
Yep, `--runtime stub` shows it!

**Comment by kungfooman** [comment]
I am not sure what happened, switching back to `--runtime none` + rebuild and `__setArgumentsLength` is exported, maybe I just didn't see it
