### ISSUE TITLE
Function Names Obfuscation?

### ISSUE THREAD

**Issue by Mistik** [AssemblyScript/assemblyscript#1530]
Hi I generated a .wasm file and when debugging the file I noticed that the function names stay the same, which will make it easy for some people to reverse engineer my wasm.

Is there any way to obfuscate the function names in the wasm?

**Comment by MaxGraey** [comment]
If you want "mangle" name you shoudn't use `--debug` and `--sourceMap` flags. In this case `optimized.wasm` shouldn't contain de-mangled names. Also you probably see `optimized.wat` which is always contain readable names, bur you should check only `.wasm` file

**Comment by MistikSenpa** [comment]
> If you want "mangled" names you shouldn't use `--debug` and `--sourceMap` flags. In this case `optimized.wasm` shouldn't contain any readable names except exported functions. Also you probably see on `optimized.wat` which is always contain readable names, but you should check only `.wasm` file

Is it not possible to scramble exported function names also?

**Comment by MrBot45** [comment]
It's easy to reverse engine with the functions name lol

**Comment by MaxGraey** [comment]
> Is it not possible to scramble exported function names also?

You could minify imported and exported functions with add `minify-imports-and-exports` flag to asc as `--runPasses minify-imports-and-exports`.
