### ISSUE TITLE
Unable to change the `this` context of an exported function

### ISSUE THREAD

**Issue by tyronedougherty** [AssemblyScript/assemblyscript#1535]
Hi there!

I'm attempting to call a function exported from compiled assemblyscript using the `Function.prototype.call` method. 

This should allow you to change the `this` context to be anything you want, however with assembly script it appears that no matter what you do - you're unable to change the context.

Here's a contrived example:

```
function testFunction (a, b) {
        return a + b + this.y;
    }

    class ExampleContext {
        constructor() {
            this.y = 10;
        }
    }

    const newContext = new ExampleContext();

    var importObject = { env: { testFn: testFunction, abort: () => {} } };


    WebAssembly.instantiateStreaming(fetch('./build/untouched.wasm'), importObject)
              // Here I'm trying to call the exported `testFn` and change the `this` context to `newContext`
             // Unfortunately this doesn't work and the output of this call is `0` due to the missing `this.y`
        .then(obj => console.log(obj.instance.exports.testFn.call(newContext, 1, 2)));
```

Am I doing something wrong? Is there another way I'm able to change the execution context of the exported function?

**Comment by tyronedougherty** [comment]
This seems to suggest that I should be able to use `call` as per usual:

> You can then go on to do pretty much anything to this function that you can do to other functions in JavaScript — call(), bind(), etc.

https://developer.mozilla.org/en-US/docs/WebAssembly/Exported_functions

Curious to know if this is something that needs to be implemented into AssemblyScript? 🤔

**Comment by dcodeIO** [comment]
What might happen there is that the JS function passed into Wasm is converted to some sort of wrapper function when passing it from Wasm to JS, which then doesn't behave as one would expect when `.call`ed. Just a guess, though, and I'm not sure that I fully understand your example.

> Exported WebAssembly functions are basically just JavaScript wrappers that represent WebAssembly functions in JavaScript.

**Comment by tyronedougherty** [comment]
> I'm not sure that I fully understand your example.

Essentially I'm just trying to change the `this` context of an exported WASM function, but for some reason it seems that the regular method of doing this (calling it using the `.call` or `.bind` methods) don't seem to work.

> What might happen there is that the JS function passed into Wasm is converted to some sort of wrapper function when passing it from Wasm to JS, which then doesn't behave as one would expect when .called.

I think this would make sense... I still don't really understand why the context is unable to be changed though - it's really strange.
