### ISSUE TITLE
Incorrect compiler output for nested min/max builtins

### ISSUE THREAD

**Issue by lexaknyazev** [AssemblyScript/assemblyscript#1537]
```ts
function max3(a: i32, b: i32, c: i32): i32 {
  return max(a, max(b, c));
}

export function foo(): i32 {
  // Returns 2 instead of 3.
  return max3(3, 2, 1);
}
```

Similar issue with `min`.

**Comment by MaxGraey** [comment]
Can confirm. Btw this works fine:
```ts
function max3(a: i32, b: i32, c: i32): i32 {
  let t = max(b, c);
  return max(a, t);
}
```

@dcodeIO could this be a issue with `flow`?

**Comment by dcodeIO** [comment]
Might be a local reuse issue, with the inner expression using a temporary local, freeing it, then the outer expression using the same temporary local, but using it in a way that is not properly sequential. Didn't check in detail yet.

**Comment by lexaknyazev** [comment]
> ```ts
> function max3(a: i32, b: i32, c: i32): i32 {
>   let t = max(b, c);
>   return max(a, t);
> }
> ```

This fixes the result but somehow makes the app ~8% slower while using the same amount of compiled instructions.

**Comment by MaxGraey** [comment]
> This fixes the result but somehow makes the app ~8% slower while using the same amount of compiled instructions.

incorrect codegen for `max(a, max(b, c))` probably use less allocated registers when lowering to actual machine instructions
