### ISSUE TITLE
Unable to extend from Map (`class Foo extends Map<A, B>`)

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1538]
This doesn't work:

```ts
export class MaterialProperties extends Map<Material, MatProps> {
	get(mat: Material): MatProps {
		let props: MatProps

		if (!this.has(mat)) this.set(mat, (props = new MatProps()))
		else props = super.get(mat)

		return props
	}
}
```

but this works:

```ts
export class MaterialProperties {
	readonly map: Map<Material, MatProps> = new Map()

	get(mat: Material): MatProps {
		let props: MatProps

		if (!this.map.has(mat)) this.map.set(mat, (props = new MatProps()))
		else props = this.map.get(mat)

		return props
	}
}
```

**Comment by dcodeIO** [comment]
What's the error there?

**Comment by MaxGraey** [comment]
Will be great get reproducible example on WebAssembly Studio for example: https://webassembly.studio/?f=ybtifahy4d

Currently I can't reproduce any compile time error.

**Comment by trusktr** [comment]
I was on AS 0.10.0. Maybe that's been fixed already. Let me see...

**Comment by trusktr** [comment]
When I hit "build and run" on that wasm studio example, I see the error

```
[error]: TypeError: exports.add is not a function
```

Is it exercising the code?

**Comment by MaxGraey** [comment]
> [error]: TypeError: exports.add is not a function

Pay no attention to it. Or just remove `exports.add(...)` call in `index.js`

**Comment by trusktr** [comment]
as-pect will support latest AssemblyScript, it's in a PR. Once I update, I'll circle back and try again. I was on AS 0.10 which is a bit old.
