### ISSUE TITLE
null check not narrowing in OR expression

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1539]
This doesn't work:

```ts
class Test {
  possiblyFoo: Foo | null = null
  definitelyFoo: Foo = new Foo
}

const t = new Test

const receiveFoo: Foo = t.possiblyFoo || t.definitelyFoo
```

The error is something like `Foo | null can not be assigned to Foo`

This works:

```ts
class Test {
  possiblyFoo: Foo | null = null
  definitelyFoo: Foo = new Foo
}

const f: Foo | null = t.possiblyFoo

if (!f) f = t.definitelyFoo

const receiveFoo: Foo = f
```

This also works (with non-null assertion):

```ts
class Test {
  possiblyFoo: Foo | null = null
  definitelyFoo: Foo = new Foo
}

const t = new Test

const receiveFoo: Foo = t.possiblyFoo! || t.definitelyFoo
```

**Comment by dcodeIO** [comment]
The compiler propagates nullability states for locals, but doesn't for fields yet. For instance, there are certain edge cases that TS accepts, but aren't actually type safe. It's likely that we can do better in at least some situations of course, but that hasn't been attempted yet.

See also: https://www.assemblyscript.org/basics.html#nullability-checks
