### ISSUE TITLE
[Question] Are imported functions stored in memory?

### ISSUE THREAD

**Issue by tyronedougherty** [AssemblyScript/assemblyscript#1542]
Are imported functions stored in memory? If so, how do you get a pointer to that memory location?

If not, is it possible to store a function in memory?

I essentially want to read the byte value of an imported function (if that's even possible!)

Thanks 😄

**Comment by dcodeIO** [comment]
Functions aren't stored in a Wasm module's memory. The only mechanism there is right now is to store a reference to a function in the Wasm module's function table, so one can `call_indirect` the function for example by the index in that table.

**Comment by tyronedougherty** [comment]
Thanks for that info - super interesting!

The end goal I'm reaching for is to assess the difference (implementation wise) between two different javascript functions. For example, function `x` and function `y` both return a `string`. I want to know if function `x` and function `y` are the exact same from an implementation standpoint, or if there is a difference between the two.

Do you think this is possible using WebAssembly?

I thought this might be possible if both were stored in memory, because you may be able to compare the memory values to see if they are the same or different, but it seems like this may not be a route forwards.

**Comment by MaxGraey** [comment]
> The end goal I'm reaching for is to assess the difference (implementation wise) between two different javascript functions

WebAssembly definitely can't do this. The one of main goals of wasm is isolation between host and other modules. Also all values passing between wasm and js host converting to numbers. No js strings or compound objects.
