### ISSUE TITLE
more specific static type check functions (isInt8, isUint8, isFloat32, isFloat64, etc)

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1549]
We currently have `isInteger` and `isFloat`.

I think we can benefit from additional ones:

- [ ] `isInt8`
- [ ] `isUint8`
- [ ] `isInt16`
- [ ] `isUint16`
- [ ] `isInt32`
- [ ] `isUint32`
- [ ] `isFloat32`
- [ ] `isFloat64`

This can make things easier, for example, when working with types that match those of the `TypedArray`s, among other things.

**Comment by trusktr** [comment]
This may be added to the [Standard library](https://github.com/AssemblyScript/assemblyscript/projects/2) project

**Comment by MaxGraey** [comment]
You could do this in more TS way:
```ts
val instanceof i8
val instanceof f64
```

> This can make things easier, for example, when working with types that match those of the TypedArrays, among other things.

Just use `arr instanceof Uint16Array` or `arr instanceof Array<u8>`

**Comment by trusktr** [comment]
> `arr instanceof Array<u8>`

Oh wow, I didn't know that works.

What about TS portability? (also aiming to compile to JS)

**Comment by trusktr** [comment]
A problem with TypeScript and `n instanceof u32`:

![Screenshot from 2020-11-19 20-53-48](https://user-images.githubusercontent.com/297678/99760825-7a9ed000-2aa9-11eb-870c-9385a8bef342.png)
