### ISSUE TITLE
Support for `new this` in static methods

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1555]
For example:

```ts
class Foo {
  static makeFoo(): Foo {
    return new this
  }
}

export function test(): void {
  Foo.makeFoo()
}
```

[AS Editor example](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWhhbGYKY2xhc3MgRm9vIHsKICBzdGF0aWMgbWFrZUZvbygpOiBGb28gewogICAgcmV0dXJuIG5ldyB0aGlzCiAgfQp9CgpleHBvcnQgZnVuY3Rpb24gdGVzdCgpOiB2b2lkIHsKICBGb28ubWFrZUZvbygpCn0KIyFodG1sCg==)

**Comment by dcodeIO** [comment]
Unfortunately we have to draw a line where things become too dynamic. For example, while it seems trivial to special-case `new this` there, that's likely to either introduce unexpected edge cases when not consequently followed the entire way through or become inefficient when trying to make it perfect. In JS for instance, `this` dynamically respects the prototype chain (e.g when a method is inherited), while in AS attempting to emulate such behavior will affect perf and code size one way or another (monorphizing based on `this` context, or additional vtables and lookups, not sure). Typical trade-off is: Sticking to where Wasm excels gives us lean and mean code that runs fast, while trying to support too much of the dynamicness of JS leads to something that may be easier to pick up but is probably bloated and slow.

**Comment by trusktr** [comment]
Thanks for explaining that. I can't imagine yet how it would be done (even if it were inefficient).
