### ISSUE TITLE
Check `instanceof SomeClass` without requiring generic args

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1557]
It'd be a lot more convenient in some cases to run code like `foo instanceof Foo` and not `foo instanceof Foo<SpecificType>`.

In plain TypeScript, we can do so.

**Comment by trusktr** [comment]
In TypeScript, `f instanceof Foo<any>` is [not valid syntax](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD28A8AVAfNA3gKGn6AZogFzQq77DwB2EALgE4Cuwd8DAFEfKSgJRZodABYBLCADpu0ALyFE0AL7Zl2KrTqFZ0agFMA7nEQcAjACYAzH2xqaEeCF0SQ8AOZdoojWGrBd8AiN4AQB6EOgXVxhGJl0bdXtHZzcPL3ofPwCgpB8ATzRQ8K8ANzAQUQATaAhc6jowAA8gA).

Has this part departed too far from TS compatibility?

**Comment by dcodeIO** [comment]
Unless there's a bug, [both](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/instanceof-class.ts) notations should work.

**Comment by trusktr** [comment]
Hmm, looks like you're right now that I tried again. I think I may have misconstrued an error.
