### ISSUE TITLE
Performance with arrays

### ISSUE THREAD

**Issue by munsocket** [AssemblyScript/assemblyscript#1560]
Hello, I am expected that with AS I will have better performance than with JS. But I can't improve my result. I am tried to decrease interoperation, inlining, StaticArray and unchecked limits. First three techniques decreased execution time, but unchecked doesn't give significant change for me.

<img src="https://habrastorage.org/webt/o8/zv/jx/o8zvjxf7gqf5atr9nr9c0uwsnqo.png" width="450"/>

Results in this benchmark robust, you can try it in your browser here: https://github.com/munrocket/jampary
In this repo I just creating a lot of arrays after each operation and it seems that problem with memory consumption.

Something the same I reported in #997, but that issues I solved it with two variables.

**Comment by ZoeDreams** [comment]
have you considered trying and alternative approach to using Math.abs(), like bitwise operations which are a bit faster. as for memory your sort of at the mercy of JS garbage collection. interesting project

**Comment by MaxGraey** [comment]
I take a look at your tests and came to the conclusion that you have the same situation as last time. You just need to scalarise your vectors (as I understand it 4-element tuples). JavaScript do scalar replacement optimization for such cases but AS can't yet apply this so you should do this manually if you want best performance

**Comment by munrocket** [comment]
> like bitwise operations which are a bit faster
I thought that function `abs()` already optimized under the hood. I am not importing it from JS, because it can be a bottleneck.

> as I understand it 4-element tuples
Yea, I took 4 elements for benchmark, but it can be any amount right now. You suggesting to create 20 type of functions with different amount of arguments? Huh, it will be look like codegen.

**Comment by MaxGraey** [comment]
> Yea, I took 4 elements for benchmark, but it can be any amount right now. You suggesting to create 20 type of functions with different amount of arguments? Huh, it will be look like codegen.

Yes you can use "special" optimized versions for small but realistic sizes likes [1, 2, 4, 8] with fallback to slow general arbitrary sized Vecs. Or you could make other benchmark which compare JS and wasm versions which use vector with bigger than 32 size of vector (or this unrealistic size?)
