### ISSUE TITLE
[Question] How to make on_abort print out stack trace?

### ISSUE THREAD

**Issue by AfflatusX** [AssemblyScript/assemblyscript#1571]
Apologize in advance in case I missed something obvious. As title states - I want to let on_abort print the full stack trace when an exception is thrown. I got it working at one point but couldn't remember what exactly I did...

My build command: asc assembly/index.ts --sourceMap --target debug --use abort=assembly/index/on_abort --debug

I also tried to call trace() manually, but it says the method could not be found (I'm using WASM in a native C application).

**Comment by dcodeIO** [comment]
AssemblyScript itsself does not maintain stack frames, but leaves this up to the host running the Wasm binary. In a browser for example, when a trap occurs, that's essentially an `Error("unreachable")` being thrown with a stack attached that also shows the respective Wasm functions. When debug info is enabled, as in your build step, the trace also includes function names.

Regarding a custom `abort` function, as soon as it executes an `unreachable` or, if it is an import, throws an error, the stack trace is captured and shown by the engine if uncaught, or can be evaluated if caught. Does that help? :)

**Comment by AfflatusX** [comment]
I see, that's very helpful! I'll reach out to the engine lib community see if they know a way to get the stack frame and print it out then. Thanks a lot!
