### ISSUE TITLE
[Question] how to import class/type defined in AssemblyScript in typescript?

### ISSUE THREAD

**Issue by philxia** [AssemblyScript/assemblyscript#1577]
The class/type defined in AS works well in JavaScript but does not work in typescript. Any idea? Thanks.

D:/gits/sketchtool.js/src/Geometries/SketchPlane.ts
TypeScript error in D:/gits/sketchtool.js/src/Geometries/SketchPlane.ts(22,24):
Object is of type 'unknown'.  TS2571

    19 |     console.log(myModule);
    20 |     const { Sketch } = results.exports;
  > 21 |     const sketch = new Sketch();

**Comment by dcodeIO** [comment]
Perhaps [generating and using a TypeScript definition for your module](https://www.assemblyscript.org/loader.html#typescript-definitions) can help.
