### ISSUE TITLE
example of calling js from wasm ?

### ISSUE THREAD

**Issue by jeromeetienne** [AssemblyScript/assemblyscript#158]
hello, im trying to learn how to call js function from assemblyscript.

is there a working example i could look at ?

thanks

**Comment by MaxGraey** [comment]
Hi, Jerome.
You can define functions inside typescript like:

main.ts
```ts
declare namespace console {
   function logi(val: i32);
}

// also you can do this
@external("env", "log")
declare function logf(val: f64);

console.logi(123);
logf(1e10);

// if you not specify this via namespace of @external decorator external will be imported with name of module i.e "main" in this case.
```

On javascript side you should write something like this:
```js
WebAssembly.instantiateStreaming(fetch("build/main.wasm"), {
  env: {
    logf(value) {
      console.log("logf: " + value);
    },
    abort: function(msg, file, line, column) {
      console.error("abort called at main.ts:" + line + ":" + column);
    }
  },
  console: {
    logi(value) {
      console.log("logi: " + value);
    }
  }
}).then(result => {
  // const exports = result.instance.exports
});
```

**Comment by MaxGraey** [comment]
Arguments which can be passed between JS <-> WASM is pretty limit it's just `i32` and `f64`. For passing strings, arrays and etc you can use [this package](https://github.com/AssemblyScript/assemblyscript/tree/master/lib/loader)

**Comment by MaxGraey** [comment]
By the way after approved [this PR](https://github.com/wasdk/WebAssemblyStudio/pull/326#issuecomment-402860402) AssemblyScript in WebAssembly Studio works again

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by trusktr** [comment]
For the life of me, I can't figure this out. I posted more details in https://github.com/AssemblyScript/assemblyscript/issues/384

**Comment by PaperPrototype** [comment]
for a scripting playground do I have the user specify externs or is there a way to not need to declare them but instead have them simply exist in the global scope?

Or I guess in other words how do I instantiate the standard library. Maybe I could manually add the declare before the user code with string combine?
