### ISSUE TITLE
[ BUG ] String compare broken on sub-strings

### ISSUE THREAD

**Issue by thisisjoshford** [AssemblyScript/assemblyscript#1582]
[Here is an example](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1ub25lJnJ1bnRpbWU9bm9uZQovKiogQ2FsY3VsYXRlcyB0aGUgbi10aCBGaWJvbmFjY2kgbnVtYmVyLiAqLwpleHBvcnQgZnVuY3Rpb24gZmliKG46IGkzMik6IGkzMiB7CiAgbGV0IG9uZSA9ICIxIjsKICBsZXQgdGVuID0gIjEwIjsKICByZXR1cm4gb25lIDwgdGVuIHx8IG9uZSA+IHRlbiB8fCBvbmUgPT0gdGVuOwp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==) of comparing the string "1" and "10", and it is never the case that is either less than, greater than, or equal to.  I would expect "1" to be less than "10" :)

**Comment by MaxGraey** [comment]
Good catch!
