### ISSUE TITLE
Array pop throws a runtime error if the array is empty

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#1584]
The documentation doesn't make it clear what happens if you pop an empty array:

~~~
function pop(): T
Removes and returns the last value of the array. Modifies Array#length.
~~~

From looking at the implementation it appears that a runtime error occurs. The standard JavaScript `Array.pop` returns undefined in this case:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/pop

Should the AssemblyScript array follow the same convention?

(as an aside, I'm trying to run my AS code via the TS compiler, using the Portable Stdlib - differences like this cause issues!)

**Comment by MaxGraey** [comment]
Yeah, that's temporary limitation due to AS hasn't nullable primitive types. Will be great describe this in docs
