### ISSUE TITLE
Length of the array returned from __newArray.

### ISSUE THREAD

**Issue by synxroform** [AssemblyScript/assemblyscript#1588]
Maybe i miss something, but for arrays created with __newArray, value of length is always 44. For example ...
> test.ts
```typescript
export function test_length(arr: f64[]) : i32 {
    return arr.length;
}
export const F64A = idof<Float64Array>()
```
> test.js
```javascript
let arr = m.__retain(m.__newArray(m.F64A, [1, 2, 3, 4, 5]))
console.log(m.test_length(arr))
m.__release(arr)
```
> output is 44

This is not the case for arrays created within AssemblyScript and returned as pointers.

**Comment by MaxGraey** [comment]
I guess this should be fixed after #1586

**Comment by dcodeIO** [comment]
The code snippet is mixing two incompatible types: `Array<f64>` (with a mutable .length) and `Float64Array` (with a fixed .length that is computed). Try to change `F64A` to `idof<f64[]>` or `arr`'s type to `Float64Array` so both are the same. Let me know if that fixes it :)

**Comment by MaxGraey** [comment]
@dcodeIO nice catch. Playgrpund which demonstrate proper work: https://bit.ly/3msIzq3

**Comment by synxroform** [comment]
Yes, changing export `const F64A = idof<f64[]>()` fixes issue.

**Comment by dcodeIO** [comment]
If resizing the array is not necessary, `Float64Array` should be slightly more efficient. An `Array<f64>` for example does a check for whether it needs to resize the backing buffer when assigning an element, which `Float64Array` does not need.
