### ISSUE TITLE
Question: how doses Classes impact the Arraybuffer?

### ISSUE THREAD

**Issue by adrian-goe** [AssemblyScript/assemblyscript#1593]
Hi, I am trying to learn assamblyscript and have run into a problem.
In my `variance-average-brightness.ts` I have the function `grayscale()` I calculate the grey value and then try to write to the shared memory. As it is at the moment, it works:
```ts
// assembly/variance-average-brightness.ts  
const CONST_R = 0.3;
const CONST_G = 0.59;
 const CONST_B = 0.114;
for (let i = 0; i < byteSize; i += 4) {
    const writeIndex = byteSize + i;

    const avg = i32(CONST_R * load<u8>(i) + CONST_G * load<u8>(i + 1) + CONST_B * load<u8>(i + 2));
    store<u8>(writeIndex + 0, avg);
    store<u8>(writeIndex + 1, avg);
    store<u8>(writeIndex + 2, avg);
    store<u8>(writeIndex + 3, 255);
```

I have created a class `Color` for the colour
```ts
// assembly/utils.ts
export class Color {
    constructor(public r: i32, public  g: i32, public b: i32, public  a: i32) {
    }
}
```

I would like to use them like that:
```ts
// assembly/variance-average-brightness.ts  
const color: Color = new Color(avg, avg, avg, 255);
store<u8>(writeIndex + 0, color.r);
store<u8>(writeIndex + 1, color.g);
store<u8>(writeIndex + 2, color.b);
store<u8>(writeIndex + 3, color.a);
```

When I execute the function, I get the following error:
```
Uncaught TypeError: Cannot perform Construct on a detached ArrayBuffer
```
I've been able to break it down to the point where I'm sure it has something to do with the colour.

In another function I do the same and it works:
```ts
// assembly/drawCross.ts
export function drawCross(byteSize: i32, imageWidth: i32, imageHeight: i32, crossWidth: i32): i32 {
// ...
        const pink: Color = new Color(253, 0, 255, 255);

        for (let row = 0; row < imageHeight; row++) {
            for (let col = 0; col < imageWidth; col++) {
                const readIndex = ((row * imageWidth) + (col)) * Util.COLOR_WIDTH;
                const writeIndex = byteSize + readIndex;
                if (row > crossHeightBeginning && row < crossHeightEnding || col > crossWidthBeginning && col < crossWidthEnding) {
                    Util.fill(writeIndex, pink);
// ...
// -------------------------------
// assembly/utils.ts
    export function fill(writeIndex: i32, color: Color): i32 {
        store<u8>(writeIndex, color.r);
        store<u8>(writeIndex + 1, color.g);
        store<u8>(writeIndex + 2, color.b);
        store<u8>(writeIndex + 3, color.a);
        return 0;
    }
```
I would like to understand why this does not work in dey `grayscale()` function.
Here is the link to the branch to see the whole thing:
https://github.com/adrian-goe/cg-2/tree/testing-more

**Comment by dcodeIO** [comment]
> Uncaught TypeError: Cannot perform Construct on a detached ArrayBuffer

This doesn't sound like an error produced by AS or the Wasm module specifically, but instead might have something to do with the module's memory being accessed externally using a cached view after it has grown. At least that's typically produces "detached" errors.

```ts
// external JS
var view = new Uint8Array(exports.memory.buffer, ...);
exports.doSomething(); // grows memory
view[123]; // detached error
```

Workaround:

```ts
// external js
exports.doSomething(); // grows memory
new Uint8Array(exports.memory.buffer, ...)[123]; // uses current memory buffer
```

**Comment by adrian-goe** [comment]
okey thanks, so i'm using that now before i read this out.
```js
mem = new Uint8Array(instance.exports.memory.buffer)
```
But when I first call the `grayscale()` function I get this as a result. The second time it looks right. What could be the reason?
![Bildschirmfoto 2020-12-19 um 18 00 08](https://user-images.githubusercontent.com/17064122/102694920-6d9a0b80-4224-11eb-944d-aa8f54730064.png)
![Bildschirmfoto 2020-12-19 um 18 03 17](https://user-images.githubusercontent.com/17064122/102694931-83a7cc00-4224-11eb-9f56-a152ff885bf2.png)
