### ISSUE TITLE
"TypeError: alloc is not a function" when calling __allocArray()

### ISSUE THREAD

**Issue by Odisseuss** [AssemblyScript/assemblyscript#1595]
Hello. I am trying to use assemblyscript, and ran into a problem when trying to use the __allocArray() function. 
I have a function YIN() written in AssemblyScript which is loaded in this component:

```
// WasmLoader.tsx
import { instantiateStreaming } from "@assemblyscript/loader";
import ModuleTypes from "../asTypes";

export default instantiateStreaming<typeof ModuleTypes>(
  fetch("optimized.wasm")
).then(({ exports }) =>
  Object.assign({}, exports, {
    YinDetector: (
      arrayValues: Float32Array,
      threshold: number,
      sampleRate: number,
      probabilityThreshold: number
    ) => {
      const pInput = exports.__retain(
        exports.__allocArray(exports.Float32AudioBuffer_ID, arrayValues)
      );
      const pOutput = exports.YIN(
        pInput,
        threshold,
        sampleRate,
        probabilityThreshold
      );
      exports.__release(pInput);
      exports.__release(pOutput);
      return pOutput;
    },
  })
);
```
After awaiting the result from the loader, i try to call the function YinDetector() with the corresponding args, and i get the following error: 
![Screenshot_1](https://user-images.githubusercontent.com/44244648/102717178-4bb68c80-42e9-11eb-8f9e-8a603d4177d5.png)

After a bit of searching i found that in the docs there is not __allocArray() function, but instead it is called __newArray(). I don't know for sure if the functions are the same, but they do look like it. Did anyone run into this issue as well?

**Comment by MaxGraey** [comment]
Are you use `--runtime half` or `--runtime stub`? It should be `--runtime full` or remove this flag at all which equal to full runtime by default

**Comment by dcodeIO** [comment]
If there is `__newArray` in the binary (new API), but `__allocArray` in the loader (old API), then the loader package is probably outdated and needs to be updated to match the compiler's version again.

**Comment by Odisseuss** [comment]
@MaxGraey Hello and thanks for the answer. These are my build targets. I am not using the --runtime flag when compiling.
![image](https://user-images.githubusercontent.com/44244648/102717456-098e4a80-42eb-11eb-958c-da8c01cd2958.png)

**Comment by MaxGraey** [comment]
@dcodeIO is right, `__allocArray` is old api. Try to update to latest AS and loader and use `__newArray`

**Comment by Odisseuss** [comment]
@MaxGraey @dcodeIO Indeed, it seems that when i installed it the first time it defaulted to version 0.0.0. I will update and let you know if that fixed it

**Comment by Odisseuss** [comment]
@dcodeIO @MaxGraey That fixed the error. Thanks a lot!
