### ISSUE TITLE
quick start show: Unexpected token export

### ISSUE THREAD

**Issue by cary1179** [AssemblyScript/assemblyscript#1597]
when I run
```
npm test
```
and ..., I got this from `"@assemblyscript/loader": "^0.17.11"`
![image](https://user-images.githubusercontent.com/6409011/102980796-0beae180-4543-11eb-851e-bba667c571bd.png)

**Comment by dcodeIO** [comment]
Looks like your node.js version is a bit old. Try upgrading :)

**Comment by cary1179** [comment]
I try node.js version `v10.15.1` and `v12.14.1`, and not work.
I got the same error.

**Comment by dcodeIO** [comment]
Try node 14 (current LTS) or 15 (current stable).

**Comment by cary1179** [comment]
thx, it works.
Is it possible make it works on node.js version forwards compatible, like node 12 or node 10.

**Comment by dcodeIO** [comment]
Iirc it starts working somewhere within the node 12.X version line. Not sure at which X exactly.
