### ISSUE TITLE
Any idea for compiling of asc2tsc or tsc2asc?

### ISSUE THREAD

**Issue by cary1179** [AssemblyScript/assemblyscript#1602]
We have a large repo wrote by typescript and wish to be compiled to assemblyscript. Is there any loader for compiling assemblyscript to typescript or typescript to assemblyscript ?

**Comment by dcodeIO** [comment]
It's not trivially possible to automatically convert TS to AS. One can do a lot of dynamic things in TS, just like in JS, while AS does not allow for the same level of dynamicness, typically requiring porting by hand.

One can, however, write new code that compiles to both JS with `tsc` and Wasm with `asc` ([see also](https://www.assemblyscript.org/portability.html)). One example for a portable codebase is the compiler itself.
