### ISSUE TITLE
"memory access out of bounds" with Float64Array

### ISSUE THREAD

**Issue by hexxone** [AssemblyScript/assemblyscript#1603]
**Hi everyone,**

I am relatively new to WebAssembly and AssemblyScript butwanted to try doing some basic array processing with it.

For this purpose I've read _a lot_ about "best practices" and finally ended up using "Float64Array" because it can also be efficiently passed to WebWorkers and has a neat ".set" and ."fill" function, in comparison to "Array<f64>".

So generally:
1. I initialize some Arrays in the module, export the pointers and get the Arrays using memory.buffer in JS.
2. I write the data I want to process directly into the memory.buffer using the Array-Impl.
3. I call the update function in the module, which does the processing and read the resulting data afterwards.

However, for some reason I always end up with the following error:
```
    RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[21]:0x13e6
    at update (<anonymous>:wasm-function[25]:0x1b60)
```

Sadly, due to my lack of knowledge how to read/debug .wasm modules, I am not able to pin the issue down.
I have quadruple-checked the code and tested different things for 6 hours but couldn't make out any obvious cause...

Maybe it's a runtime issue, or an issue of understanding on my part?, but anyways I would really appreciate any kind of help, hint or idea at this point.

Thanks is advance and Merry X-Mas :)

[Issue demonstration Code can be found here](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWZ1bGwKLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8KIC8vICAgICBDVVNUT00gQVBJCiAvLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLwoKLyoKQGV4dGVybmFsKCJlbnYiLCAibG9nZiIpCmRlY2xhcmUgZnVuY3Rpb24gbG9nZih2YWx1ZTogZjY0KTogdm9pZDsKCkBleHRlcm5hbCgiZW52IiwgImxvZ2kiKQpkZWNsYXJlIGZ1bmN0aW9uIGxvZ2kodmFsdWU6IHUzMik6IHZvaWQ7CgpAZXh0ZXJuYWwoImVudiIsICJsb2dVMzJBcnJheSIpCmRlY2xhcmUgZnVuY3Rpb24gbG9nVTMyQXJyYXkoYXJyOiBVaW50MzJBcnJheSk6IHZvaWQ7CgpAZXh0ZXJuYWwoImVudiIsICJsb2dGNjRBcnJheSIpCmRlY2xhcmUgZnVuY3Rpb24gbG9nRjY0QXJyYXkoYXJyOiBGbG9hdDY0QXJyYXkpOiB2b2lkOwoKZXhwb3J0IGZ1bmN0aW9uIGFsbG9jRjY0QXJyYXkobGVuZ3RoOiBpMzIpOiBGbG9hdDY0QXJyYXkgewogIHJldHVybiBuZXcgRmxvYXQ2NEFycmF5KGxlbmd0aCk7Cn0KCmV4cG9ydCBmdW5jdGlvbiBhbGxvY1UzMkFycmF5KGxlbmd0aDogaTMyKTogVWludDMyQXJyYXkgewogIHJldHVybiBuZXcgVWludDMyQXJyYXkobGVuZ3RoKTsKfQoqLwoKQGlubGluZQpmdW5jdGlvbiBkZWFsbG9jQXJyYXk8VD4oYXJyOiBUW10pOiB2b2lkIHsKICBtZW1vcnkuZnJlZShjaGFuZ2V0eXBlPHVzaXplPihhcnIuYnVmZmVyXykpOwogIG1lbW9yeS5mcmVlKGNoYW5nZXR5cGU8dXNpemU+KGFycikpOwp9CgogLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8KIC8vICAgICBNYWluIFByb2dyYW0KIC8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vCgpjb25zdCBEQVRfTEVOOiBpMzIgPSAxMjg7CmNvbnN0IEhMRl9MRU46IGkzMiA9IDY0Owpjb25zdCBRUlRfTEVOOiBpMzIgPSAzMjsKCmNvbnN0IHBOb2lzZSA9IFsxLjE3NjAzNjc0NzAzMDUsIDAuODUyMDczNzk0MTgyNDMsIDAuNjg4NDI0MzcyMjc4NTIsIDAuNjM3Njc5MDI1NzA4MjksCiAgICAwLjU0NTIzNDg5NDk2NTQsIDAuNTA3MjMzMjU4NjQxNjcsIDAuNDY3NzcyNjIzNDY4MiwgMC40NDIwNDE4Mjc0ODc2NywgMC40MTk1NjUxNzgwMjE1NywKICAgIDAuNDE1MTczNzUwNDAwMDIsIDAuNDEzMTIxMTg1Nzc5MzQsIDAuNDA2MTgzNjM5NjA0NDYsIDAuMzk5MTM3MDc0NzQ5NzUsIDAuMzgyMDcwMDg2MTQ1MDgsCiAgICAwLjM4MzI5Nzg5MTA2NDg4LCAwLjM3NDcyMTM2NjA2MjQ1LCAwLjM2NTg2NDI4NDEyOTY4LCAwLjM3NjAzMDE3MzM1MTA1LCAwLjM5NzYyNTkwNzYxNTczLAogICAgMC4zOTM5MTgyODg1ODU5MSwgMC4zNzkzMDYwMzc2OTYyMiwgMC4zOTQzMzM2NTc2NDU2MywgMC4zODUxMTUwNDYxMzg1OSwgMC4zOTA4MjU3OTI0MTgzNCwKICAgIDAuMzgxMTg1MjcyMDUwNCwgMC40MDIzMTQ1MzcyNzE2MSwgMC40MDI0NDE1MTEzMzE3NSwgMC4zOTk2NTM2Njg4NDUyMSwgMC4zOTc2MTEwMzgyNzU0NSwKICAgIDAuNTExMzY0MDA0MjIyMTIsIDAuNjYxNTEyMTIwMzg5NTQsIDAuNjYzMTIyMDUyMjY2NzksIDAuNzQxNjI3NjY5MDk5NSwgMC43NDYxNDk3MTMwMTEzMywKICAgIDAuODQ3OTcwMDc1Nzc0ODMsIDAuODU3MzU4MzkxMDQ2OSwgMC45NjM4Mjk5NzgxMTY2MywgMC45OTgxOTM3NzU3NzE4NSwgMS4wNjI4NjkyNjE1ODE0LAogICAgMS4xMDU5MDgzOTY5NzUxLCAxLjE4MTk4MDg0OTczMzUsIDEuMjU3MDkyMjk3MjA4LCAxLjMyMjY1MjE0NjQ3NTMsIDEuMzczNTk5MjUzMjkwNSwKICAgIDEuNDk1MzIyMzcwNTg4OSwgMS41MzEwMDY0OTQyMzczLCAxLjYxOTM5MjM1ODQ4MDgsIDEuNzA5NDgwNTUyNzEzNSwgMS43NzA2NjA0NTUyMjE4LAogICAgMS44NDkxOTg3OTQxNDI4LCAxLjkyMzg0MTg4NDk0MDYsIDIuMDE0MTU5NjkyMTMzMywgMi4wNzg2NDI5NTA4ODI3LCAyLjE1NzU1MjI1MTg2NDYsCiAgICAyLjIxOTYzNTU1MjYwMDUsIDIuMjY2MDExMjUwOTcwNSwgMi4zMjA3NjIxNzE3NDksIDIuMzU3NDg0ODI1NDUxMywgMi4zOTg2MTI3OTc2NTM3LAogICAgMi40MDQzNTY2MTc2NDc0LCAyLjQyODA0NzY3Nzc4NDIsIDIuMzkxNzQ3NzM5NzMzNiwgMi40MDMyNTIyNTQ2NjIyLCAyLjM2MTQxODAxNTA2NzhdOwoKY29uc3QgcGlua05vaXNlID0gbmV3IEZsb2F0NjRBcnJheShITEZfTEVOKTsKcGlua05vaXNlLnNldChwTm9pc2UpOwoKCi8vIGNvcnJlY3QgcGluayBub2lzZSBmb3IgZmlyc3QgYW5kIHNlY29uZCBoYWxmCmZ1bmN0aW9uIGNvcnJlY3RQaW5rTm9pc2UoZGF0YTogRmxvYXQ2NEFycmF5KTogdm9pZCB7CiAgICB2YXIgY29ycmVjdCA9IG5ldyBGbG9hdDY0QXJyYXkoREFUX0xFTik7CiAgICBmb3IgKHZhciBpID0gMDsgaSA8IEhMRl9MRU47IGkrKykgewogICAgICAgIGNvcnJlY3RbaV0gPSBkYXRhW2ldIC8gcGlua05vaXNlW2ldOwogICAgICAgIGNvcnJlY3RbSExGX0xFTiArIGldID0gZGF0YVtITEZfTEVOICsgaV0gLyBwaW5rTm9pc2VbaV07CiAgICB9CiAgICBkYXRhLnNldChjb3JyZWN0KTsKfQoKLy8gbWVyZ2UgZmlyc3QgYW5kIHNlY29uZCBoYWxmIGludG8gZnVsbCByYW5nZQpmdW5jdGlvbiBzdGVyZW9Ub01vbm8oZGF0YTogRmxvYXQ2NEFycmF5KTogdm9pZCB7CiAgICB2YXIgbW9ubyA9IG5ldyBGbG9hdDY0QXJyYXkoREFUX0xFTik7CiAgICB2YXIgbUlkeCA9IDA7CiAgICBmb3IgKHZhciBpID0gMDsgaSA8IEhMRl9MRU47IGkrKykgewogICAgICAgIG1vbm9bbUlkeCsrXSA9IGRhdGFbaV07CiAgICAgICAgbW9ub1ttSWR4KytdID0gZGF0YVtITEZfTEVOICsgaV07CiAgICB9CiAgICBkYXRhLnNldChtb25vKTsKfQoKLy8gc3dpdGNoIGZyb250IHdpdGggYmFjayBpbiBmaXJzdCBoYWxmCmZ1bmN0aW9uIGludmVydEZpcnN0KGRhdGE6IEZsb2F0NjRBcnJheSk6IHZvaWQgewogICAgZm9yICh2YXIgaSA9IDA7IGkgPCBRUlRfTEVOOyBpKyspIHsKICAgICAgICB2YXIgYSA9IGRhdGFbaV07CiAgICAgICAgZGF0YVtpXSA9IGRhdGFbSExGX0xFTiAtIGldOwogICAgICAgIGRhdGFbSExGX0xFTiAtIGldID0gYTsKICAgIH0KfQoKLy8gc3dpdGNoIGZyb250IHdpdGggYmFjayBpbiBzZWNvbmQgaGFsZgpmdW5jdGlvbiBpbnZlcnRTZWNvbmQoZGF0YTogRmxvYXQ2NEFycmF5KTogdm9pZCB7CiAgICBmb3IgKHZhciBpID0gMDsgaSA8IFFSVF9MRU47IGkrKykgewogICAgICAgIHZhciBiID0gZGF0YVtITEZfTEVOICsgaV07CiAgICAgICAgZGF0YVtITEZfTEVOICsgaV0gPSBkYXRhW0RBVF9MRU4gLSBpXTsKICAgICAgICBkYXRhW0RBVF9MRU4gLSBpXSA9IGI7CiAgICB9Cn0KCi8vIHN3aXRjaCBmcm9udCB3aXRoIGJhY2sgaW4gZnVsbCByYW5nZQpmdW5jdGlvbiBpbnZlcnRBbGwoZGF0YTogRmxvYXQ2NEFycmF5KTogdm9pZCB7CiAgICBmb3IgKHZhciBpID0gMDsgaSA8IEhMRl9MRU47IGkrKykgewogICAgICAgIHZhciBhID0gZGF0YVtpXTsKICAgICAgICBkYXRhW2ldID0gZGF0YVtEQVRfTEVOIC0gaV07CiAgICAgICAgZGF0YVtEQVRfTEVOIC0gaV0gPSBhOwogICAgfQp9CgovLyBmaWx0ZXIgcGVha3MgZm9yIGZ1bGwgcmFuZ2UKZnVuY3Rpb24gcGVha0ZpbHRlcihhcnJheTogRmxvYXQ2NEFycmF5LCBhbW91bnQ6IGY2NCk6IHZvaWQgewogICAgdmFyIG9sZE1heDogZjY0ID0gMDsKICAgIHZhciBuZXdNYXg6IGY2NCA9IDA7CiAgICB2YXIgbmV3QXJyYXkgPSBuZXcgRmxvYXQ2NEFycmF5KERBVF9MRU4pOwogICAgdmFyIGkgPSAwOwogICAgLy8gcG93IHRoaXMgc2hpdAogICAgZm9yICg7IGkgPCBEQVRfTEVOOyBpKyspIHsKICAgICAgICBpZiAoYXJyYXlbaV0gPiBvbGRNYXgpIG9sZE1heCA9IGFycmF5W2ldOwogICAgICAgIG5ld0FycmF5W2ldID0gTWF0aC5wb3coYXJyYXlbaV0gKiBhbW91bnQsIGFtb3VudCkgYXMgZjY0OwogICAgICAgIGlmIChuZXdBcnJheVtpXSA+IG5ld01heCkgbmV3TWF4ID0gbmV3QXJyYXlbaV07CiAgICB9CiAgICAvLyByZS1zY2FsZSAmIGFwcGx5CiAgICB2YXIgZGl2aWRlOiBmNjQgPSBuZXdNYXggLyBvbGRNYXg7CiAgICBmb3IgKGkgPSAwOyBpIDwgREFUX0xFTjsgaSsrKQogICAgICAgIGFycmF5W2ldID0gbmV3QXJyYXlbaV0gLyBkaXZpZGU7Cn0KCi8vIHNtb290aCB2YWx1ZXMgZm9yIGZ1bGwgcmFuZ2UKZnVuY3Rpb24gc21vb3RoQXJyYXkoYXJyYXk6IEZsb2F0NjRBcnJheSwgc3RlcHM6IGkzMik6IHZvaWQgewogICAgdmFyIG5ld0FycmF5ID0gbmV3IEZsb2F0NjRBcnJheShEQVRfTEVOKTsKICAgIC8vIG1ha2Ugc21vb3RoZWQgYXJyYXkKICAgIGZvciAodmFyIG91dGVyID0gMDsgb3V0ZXIgPCBEQVRfTEVOOyBvdXRlcisrKSB7CiAgICAgICAgdmFyIHN1bTogZjY0ID0gMDsKICAgICAgICBmb3IgKHZhciBpbm5lciA9IG91dGVyIC0gc3RlcHM7IGlubmVyIDw9IG91dGVyICsgc3RlcHM7IGlubmVyKyspIHsKICAgICAgICAgICAgdmFyIGlkeCA9IGlubmVyOwogICAgICAgICAgICBpZiAoaWR4IDwgMCkgaWR4ICs9IERBVF9MRU47CiAgICAgICAgICAgIHN1bSArPSBhcnJheVtpZHggJSBEQVRfTEVOXTsKICAgICAgICB9CiAgICAgICAgbmV3QXJyYXlbb3V0ZXJdID0gc3VtIC8gKCgoc3RlcHMgKiAyKSArIDEpIGFzIGY2NCk7CiAgICB9CiAgICBhcnJheS5zZXQobmV3QXJyYXkpOwp9CgovLyBmdW5jdGlvbiB3aWxsIGFwcGx5IHNldHRpbmctZGVmaW5lZCBkYXRhIHNtb290aGluZwpmdW5jdGlvbiBhcHBseVZhbHVlTGV2ZWxpbmcoY3VycjogRmxvYXQ2NEFycmF5LCBwcmV2OiBGbG9hdDY0QXJyYXksIGluYzogZjY0LCBkZWM6IGY2NCk6IHZvaWQgewogICAgZm9yICh2YXIgaSA9IDA7IGkgPCBEQVRfTEVOOyBpKyspIHsKICAgICAgICB2YXIgZGlmZjogZjY0ID0gY3VycltpXSAtIHByZXZbaV07CiAgICAgICAgdmFyIG1sdDogZjY0ID0gMTAwIC0gKGRpZmYgPiAwID8gaW5jIDogZGVjKTsKICAgICAgICBjdXJyW2ldIC09IGRpZmYgKiBtbHQgLyAxMDA7CiAgICB9Cn0KCi8vIFRIRVcgSU5QVVQgVkFMVUUgVE8gV1JJVEUgVE8KZXhwb3J0IGNvbnN0IGlucHV0RGF0YSA9IG5ldyBGbG9hdDY0QXJyYXkoREFUX0xFTik7CmlucHV0RGF0YS5maWxsKDAuMCk7CgovLyB0aGlzIHdpbGwgaG9sZCB0aGUgY3VycmVudCBwcm9jZXNzZWQgYXVkaW8gZGF0YQovLyBlaXRoZXI6ICBCLUggIHwgIEgtQiAgfCAgSEwtQkwtQlItSFIgIHwgIEJMLUhMLUhSLUJSCi8vIHdoZXJlICggQj1iYXNzLCBIPWhpZ2gsIEw9bGVmdCwgUj1yaWdodCApCi8vIGluIHJhbmdlID4gMC4wIGFuZCB+PCAxLjUKZXhwb3J0IGNvbnN0IG91dHB1dERhdGEgPSBuZXcgRmxvYXQ2NEFycmF5KERBVF9MRU4pOwpvdXRwdXREYXRhLmZpbGwoMC4wKTsKCi8vIHRoaXMgd2lsbCBob2xkIHRoZSBjdXJyZW50IHByb2Nlc3NlZCBwcm9wZXJ0aWVzOgpleHBvcnQgY29uc3QgYXVkaW9Qcm9wcyA9IG5ldyBGbG9hdDY0QXJyYXkoMTApOwphdWRpb1Byb3BzLmZpbGwoMC4wKTsKZW51bSBQcm9wcyB7CiAgICBiYXNzID0gMCwKICAgIG1pZHMgPSAxLAogICAgaGlnaHMgPSAyLAogICAgc3VtID0gMywKICAgIG1pbiA9IDQsCiAgICBtYXggPSA1LAogICAgYXZlcmFnZSA9IDYsCiAgICByYW5nZSA9IDcsCiAgICBzaWxlbnQgPSA4LAogICAgaW50ZW5zaXR5ID0gOQp9CgovLyB0aGlzIHdpbGwgaG9sZCB0aGUgY3VycmVudCBwcm9jZXNzaW5nIHNldHRpbmdzCmV4cG9ydCBjb25zdCBhdWRpb1NldHRpbmdzID0gbmV3IEZsb2F0NjRBcnJheSg4KTsKYXVkaW9TZXR0aW5ncy5maWxsKDAuMCk7CmVudW0gU2V0dCB7CiAgICBlcXVhbGl6ZSA9IDAsCiAgICBtb25vX2F1ZGlvID0gMSwKICAgIGF1ZGlvX2RpcmVjdGlvbiA9IDIsCiAgICBwZWFrX2ZpbHRlciA9IDMsCiAgICB2YWx1ZV9zbW9vdGhpbmcgPSA0LAogICAgYXVkaW9faW5jcmVhc2UgPSA1LAogICAgYXVkaW9fZGVjcmVhc2UgPSA2LAogICAgbWluaW11bV92b2x1bWUgPSA3Cn0KCi8vIGNoZWNrIGhlbHBlcgpmdW5jdGlvbiBpc09uKGE6IGY2NCk6IGJvb2xlYW4gewogICAgcmV0dXJuIGEgPiAwOwp9CgovLyB0aGlzIHdpbGwgdXBkYXRlIGFuZCBwcm9jZXNzIG5ldyBkYXRhCmV4cG9ydCBmdW5jdGlvbiB1cGRhdGUoKTogdm9pZCB7CgogICAgLy8gZml4IHBpbmsgbm9pc2U/CiAgICBpZiAoaXNPbihhdWRpb1NldHRpbmdzW1NldHQuZXF1YWxpemVdKSkKICAgICAgICBjb3JyZWN0UGlua05vaXNlKGlucHV0RGF0YSk7CgogICAgLy8gd3JpdGUgYm90Y2ggY2hhbm5lbHMgdG8gbW9ubwogICAgaWYgKGlzT24oYXVkaW9TZXR0aW5nc1tTZXR0Lm1vbm9fYXVkaW9dKSkKICAgICAgICBzdGVyZW9Ub01vbm8oaW5wdXREYXRhKTsKCiAgICBpZiAoaXNPbihhdWRpb1NldHRpbmdzW1NldHQuYXVkaW9fZGlyZWN0aW9uXSkpIHsKICAgICAgICAvLyBmbGlwcGVkIGhpZ2ggJiBsb3cgbWFwcGluZwogICAgICAgIGlmIChpc09uKGF1ZGlvU2V0dGluZ3NbU2V0dC5tb25vX2F1ZGlvXSkpCiAgICAgICAgICAgIC8vIGZsaXAgd2hvbGUgcmFuZ2UKICAgICAgICAgICAgaW52ZXJ0QWxsKGlucHV0RGF0YSk7CiAgICAgICAgZWxzZSB7CiAgICAgICAgICAgIC8vIG9ubHkgZmxpcCBmaXJzdCBoYWxmIG9mIHN0ZXJlbwogICAgICAgICAgICBpbnZlcnRGaXJzdChpbnB1dERhdGEpOwogICAgICAgIH0KCiAgICB9CiAgICBlbHNlIHsKICAgICAgICAvLyBub3JtYWwgaGlnaCAmIGxvdyBtYXBwaW5nCiAgICAgICAgaWYgKGlzT24oYXVkaW9TZXR0aW5nc1tTZXR0Lm1vbm9fYXVkaW9dKSkgewogICAgICAgICAgICAvLyBvbmx5IGZsaXAgdGhlIHNlY29uZCBoYWxmIG9mIHRoZSBkYXRhCiAgICAgICAgICAgIGludmVydFNlY29uZChpbnB1dERhdGEpOwogICAgICAgIH0KICAgIH0KCiAgICAvLyBwcm9jZXNzIHBlYWtzPwogICAgaWYgKGlzT24oYXVkaW9TZXR0aW5nc1tTZXR0LnBlYWtfZmlsdGVyXSkpCiAgICAgICAgcGVha0ZpbHRlcihpbnB1dERhdGEsIGF1ZGlvU2V0dGluZ3NbU2V0dC5wZWFrX2ZpbHRlcl0gKyAxKTsKCiAgICAvLyBzbW9vdGggZGF0YT8KICAgIGlmIChpc09uKGF1ZGlvU2V0dGluZ3NbU2V0dC52YWx1ZV9zbW9vdGhpbmddKSkKICAgICAgICBzbW9vdGhBcnJheShpbnB1dERhdGEsIGF1ZGlvU2V0dGluZ3NbU2V0dC52YWx1ZV9zbW9vdGhpbmddIGFzIGkzMik7CgogICAgLy8gcHJvY2VzcyBjdXJyZW50IGZyZXF1ZW5jeSBkYXRhIGFuZCBwcmV2aW91cyBpZiBnaXZlbgogICAgdmFyIHN1bTogZjY0ID0gMCwKICAgICAgICBtaW46IGY2NCA9IDEsCiAgICAgICAgbWF4OiBmNjQgPSAwLAogICAgICAgIGJhc3M6IGY2NCA9IDAsCiAgICAgICAgbWlkczogZjY0ID0gMCwKICAgICAgICBwZWFrczogZjY0ID0gMDsKCiAgICBmb3IgKHZhciBpbmR4ID0gMDsgaW5keCA8IERBVF9MRU47IGluZHgrKykgewogICAgICAgIC8vIHBhcnNlIGN1cnJlbnQgZnJlcSB2YWx1ZQogICAgICAgIHZhciBpZGF0YTogZjY0ID0gaW5wdXREYXRhW2luZHhdOwogICAgICAgIC8vIHByb2Nlc3MgbWluIG1heCB2YWx1ZQogICAgICAgIGlmIChpZGF0YSA8IG1pbikgbWluID0gaWRhdGE7CiAgICAgICAgaWYgKGlkYXRhID4gbWF4KSBtYXggPSBpZGF0YTsKICAgICAgICAvLyBwcm9jZXNzIHJhbmdlcwogICAgICAgIGlmIChpbmR4IDwgKDQyIC8gMykpIGJhc3MgKz0gaWRhdGEgKiBhdWRpb1Byb3BzW1Byb3BzLmJhc3NdOwogICAgICAgIGVsc2UgaWYgKGluZHggPiA2OSkgcGVha3MgKz0gaWRhdGEgKiBhdWRpb1Byb3BzW1Byb3BzLmhpZ2hzXTsgCiAgICAgICAgZWxzZSBtaWRzICs9IGlkYXRhICogYXVkaW9Qcm9wc1tQcm9wcy5taWRzXTsgCiAgICAgICAgLy8gY2FsYyBwZWFrIGF2ZXJhZ2UKICAgICAgICBzdW0gKz0gaWRhdGE7CiAgICB9CgogICAgLy8gY2FsYyBhdmVyYWdlIHdpdGggcHJldmlvdXMgZW50cnkKICAgIHZhciBhdmVyYWdlOiBmNjQgPSBzdW0gLyAoREFUX0xFTiBhcyBmNjQpOwogICAgdmFyIHNpbGVudDogZjY0ID0gKG1heCA8IGF1ZGlvU2V0dGluZ3NbU2V0dC5taW5pbXVtX3ZvbHVtZV0gLyAxMDAwKSA/IDAuOTk5OSA6IDAuMDA7CiAgICB2YXIgaW50ZW5zaXR5OiBmNjQgPSAoYmFzcyAqIDggLSBtaWRzICsgcGVha3MpIC8gNiAvIGF2ZXJhZ2U7CiAgICB2YXIgcmFuZ2U6IGY2NCA9IG1heCAtIG1pbjsKCiAgICAvLyBBcHBseSBEYXRhCiAgICBvdXRwdXREYXRhLnNldChpbnB1dERhdGEpOwogICAgCiAgICAvLyBET05FCn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQoKICAgIC8vIHB1dCBzZXR0aW5ncwogICAgY29uc3Qgc3RuZ3MgPSBuZXcgRmxvYXQ2NEFycmF5KGV4cG9ydHMubWVtb3J5LmJ1ZmZlciwgZXhwb3J0cy5hdWRpb1NldHRpbmdzLCA4KTsKICAgIHN0bmdzLmZpbGwoMC4xKTsKCiAgICAvLyBwdXQgaW5wdXQgYXVkaW8gZGF0YQogICAgY29uc3QgdHJhbnNmZXIgPSBuZXcgRmxvYXQ2NEFycmF5KGV4cG9ydHMubWVtb3J5LmJ1ZmZlciwgZXhwb3J0cy5pbnB1dERhdGEsIDEyOCk7CiAgICB0cmFuc2Zlci5maWxsKDAuMikKCiAgICAvLyBjYWxsIHRoZSBwcm9jZXNzaW5nIGZ1bmN0aW9uCiAgICAvLyB0aGlzIGNhdXNlcyB0aGUgZXJyb3IKICAgIGV4cG9ydHMudXBkYXRlKCk7CgogICAgLy8gcHJpbnQgLSBuZXZlciByZWFjaCBoZXJlIDooIAogICAgb3V0cHV0LnZhbHVlICs9ICdzdG5nczogJyArIHN0bmdzLmxlbmd0aCArICIsIHRyYW5zZmVyOiAiICsgdHJhbnNmZXIubGVuZ3RoOwogIH0pCjwvc2NyaXB0Pg==)

**Comment by dcodeIO** [comment]
When exporting a `Float64Array` to the host, what JS sees there is the pointer to the `Float64Array` header, not a pointer to its backing buffer containing the data.

```ts
// AS
export const audioProps = new Float64Array(10);
```

```js
// JS
exports.audioProps // points at header, not data
```

This is easy to fix though by utilizing the [loader](https://www.assemblyscript.org/loader.html) instead:

```js
exports.__getArrayView(exports.audioProps)
```

**Comment by MaxGraey** [comment]
> exports.__getArrayView(exports.audioProps)

Or little bit more performant:
```ts
exports.__getFloat64ArrayView(exports.audioProps)
```

**Comment by hexxone** [comment]
> When exporting a `Float64Array` to the host, what JS sees there is the pointer to the `Float64Array` header, not a pointer to its backing buffer containing the data.
> 
> ```ts
> // AS
> export const audioProps = new Float64Array(10);
> ```
> 
> ```js
> // JS
> exports.audioProps // points at header, not data
> ```
> 
> This is easy to fix though by utilizing the [loader](https://www.assemblyscript.org/loader.html) instead:
> 
> ```js
> exports.__getArrayView(exports.audioProps)
> ```

Thanks for the quick response!
This seems to work 👍 

However, now I get a different error which says: "index out of range"
```
Error: abort: Index out of range at ~lib/typedarray.ts:1304:64
    at abort (VM63 index.js:78)
    at <anonymous>:wasm-function[19]:0x1397
    at update (<anonymous>:wasm-function[23]:0x1c7e)
```
which I also experienced earlier... so I think this was actually my initial issue...

Do you perhaps also have a clue regarding this? 
Or how I could debug this? Many thanks :)

**Comment by hexxone** [comment]
> > exports.__getArrayView(exports.audioProps)
> 
> Or little bit more performant:
> 
> ```ts
> const arr = exports.__getFloat64ArrayView(exports.audioProps)
> ```
> 
> Also note. If you use `exports.__get....View` methods you should immediate use or clone buffer. Otherwise it could be detouched with next wasm call. So if you you not sure better use `exports.__getFloat64Array(exports.audioProps)` (without `View` suffix) which always make copy of array's buffer

Ok Thanks, good to know.

I have read somewhere, when using big enough initial module memory, it usually shouldn't resize?
In my project environment for example, I have set it to 32k for now.
But I guess that's something to look out for...

**Comment by dcodeIO** [comment]
The error indicates that a `Float64Array` is accessed out of bounds, which would result in `undefined` in JS, but produces an error in AS. You probably already know :). I'd debug this by placing `assert(arr.length >= X)` at places where I'd expect the error to happen, and if the assertion triggers, add a `trace("arr.length", 1, arr.length)` to inspect the value. Btw, to get a bit more useful stack traces, you may enable debug information in binaries. That shows actual function names then instead of `wasm-function[19]`.

**Comment by hexxone** [comment]
> The error indicates that a `Float64Array` is accessed out of bounds, which would result in `undefined` in JS, but produces an error in AS. You probably already know :). I'd debug this by placing `assert(arr.length >= X)` at places where I'd expect the error to happen, and if the assertion triggers, add a `trace("arr.length", 1, arr.length)` to inspect the value. Btw, to get a bit more useful stack traces, you may enable debug information in binaries. That shows actual function names then instead of `wasm-function[19]`.

Great Tip!
I can't say for sure **why**, but I figured out the"Sett" and "Prop" **enums** were probably the culprits.
The values did not resolve correctly at runtime... And simply replacing them directly with their indexes works like a charme...
Even though it's not as pretty in code ^^

Thanks again. Cheers
