### ISSUE TITLE
Testing AssemblyScript function with Jest results in error "TextDecoder is not defined"

### ISSUE THREAD

**Issue by Odisseuss** [AssemblyScript/assemblyscript#1608]
Hello. I am not really sure if this is the right place to ask this question, but here I go.

I am trying to test an AssemblyScript function, but when running my Jest tests, I get the following error which seems to have something to do with the AssemblyScript loader.

![image](https://user-images.githubusercontent.com/44244648/103568790-de9d1c80-4ece-11eb-8799-ee29f37bb502.png)

 Did anyone manage to test his/her code with Jest? 

Thanks

**Comment by dcodeIO** [comment]
What's your node.js version?

**Comment by Odisseuss** [comment]
@dcodeIO I am working with node 12.18

**Comment by dcodeIO** [comment]
Hmm, according to the node.js docs, `TextDecoder` was added as a global in v11.0.0. May be a problem with Jest not exposing it then.

**Comment by dcodeIO** [comment]
Found this thread with a potential solution at the end: https://github.com/facebook/jest/issues/10523

**Comment by Odisseuss** [comment]
Hm, it seems that after following the steps in the thread, the error message changed: 

![image](https://user-images.githubusercontent.com/44244648/103570050-0f7e5100-4ed1-11eb-8135-091f8111b857.png)

**Comment by MaxGraey** [comment]
I recommend update node.js at least to 13.0 (better to latest version)

**Comment by dcodeIO** [comment]
The error seems to indicate that Jest refuses to load the loader as an ES module. The first bullet point appears to offer a solution, or you can try `import { ... } from "@assemblyscript/loader/umd";`.

**Comment by Odisseuss** [comment]
Updating node.js to version 14 and changing the assemblyscript loader import from
``import { instantiateStreaming } from "@assemblyscript/loader";`` to ``import { instantiateStreaming } from "@assemblyscript/loader";`` fixed that issue. 

Now it seems that i cannot load the .wasm files because jest-fetch-mock does not support relative URLs. I am using fetch in a component that loads the AssemblyScript module as follows: 

```
import { instantiateStreaming } from "@assemblyscript/loader";
import ModuleTypes from "../asTypes";

export const loadWasm = instantiateStreaming<typeof ModuleTypes>(
  fetch("optimized.wasm")
).then(({ exports }) =>
  Object.assign({}, exports, {
    YinDetector: (
      arrayValues: Float32Array,
      threshold: number,
      sampleRate: number,
      probabilityThreshold: number
    ) => {
      const pInput = exports.__retain(
        exports.__newArray(exports.Float32AudioBuffer_ID, arrayValues)
      );
      const pOutput = exports.YIN(
        pInput,
        threshold,
        sampleRate,
        probabilityThreshold
      );
      exports.__release(pInput);
      return pOutput;
    },
  })
);
```

I am getting this following error:
![image](https://user-images.githubusercontent.com/44244648/103576349-ad771900-4edb-11eb-9da8-9dc2cf510c91.png)

**Comment by MaxGraey** [comment]
Btw did you know we have nice jest compatible testing library written on AS for AS which works should works without any problems and don't even require loader and passing data from and back to host?
https://github.com/jtenner/as-pect

**Comment by MaxGraey** [comment]
Regarding your jest error. It seems node-fetch can't resolve relative path somehow. Try to use absolute path for your `optimized.wasm`

**Comment by Odisseuss** [comment]
@MaxGraey 

> Btw did you know we have nice jest compatible testing library written on AS for AS which works should works without any problems and don't even require loader and passing data from and back to host?
> https://github.com/jtenner/as-pect

Yes, I stumbled upon as-pect on some threads regarding AS testing. I wanted to use Jest for writing some tests that compare two algorithms in terms of speed and accuracy. But I dropped that and wrote the comparison tests in pain TSX. 

Thanks  a lot for all the support. This issue can be closed now

**Comment by mrchantey** [comment]
Adding this to my `jest.config` solved it for me

```
module.exports = {
	testEnvironment: 'node'
}
```
