### ISSUE TITLE
String.fromCharCodes() takes an u16[], but asc fails because of type mismatch

### ISSUE THREAD

**Issue by SebastianSpeitel** [AssemblyScript/assemblyscript#1609]
The typing for `String.fromCharCodes()` says:

https://github.com/AssemblyScript/assemblyscript/blob/caa58015062dbccba7de9133c3d09138eec93e85/std/assembly/index.d.ts#L1623
and
https://github.com/AssemblyScript/assemblyscript/blob/caa58015062dbccba7de9133c3d09138eec93e85/std/assembly/string.ts#L22

In VSCode the tooltip shows `u16[]`, which is the one I would expect since strings are UTF-16.
But when trying to compile, it fails:
```
ERROR TS2322: Type '~lib/array/Array<u16>' is not assignable to type '~lib/array/Array<i32>'.

   return String.fromCharCodes(arr);
                               ~~~
```

[Live example](https://bit.ly/3rTiPHh)

**Comment by emmanuelm41** [comment]
Hello there. It is still happening on AssemblyScript latest version. Docs says u16 too.
