### ISSUE TITLE
[FR] Automatic Wasm/TypeScript compiling using decorators

### ISSUE THREAD

**Issue by aminya** [AssemblyScript/assemblyscript#1614]
I have been thinking about an idea for a while which I think might be worthwhile discussing with you.
Can we use decorators to allow writing mixed Wasm and JS code in AssemblyScript? 

`asc` should be able to use the decorators to automatically compile this file to a wasm-js combination. This can be really beneficial for making it easier to write wasm.

Say we have a file like this:
```ts
@wasm
function wasm_code() {
 // ...

 // calling js function here (through imports)
  some_dom_code()
}

@js
function dom_code() {
  // ...

  // calling wasm functions here (through imports)
  wasm_code()
}
```
Something similar can be applied to the files
```ts
@js_module
// the top_level scope of this file is a js_module
```
```ts
@wasm_module
// the top_level scope of this file is a wasm_module
```

This may increase the complexity for the compiler, but it will definitely result in more adoption of Wasm. Imagine I could just write wasm functions like how I would write JavaScript functions, and show my intentions using a simple decorator.

Currently, I need to keep everything in completely separate files, and I have to write an instantiation code manually. If we could write in one file, there was no need for this boilerplate code and concerns for the file management.

The compiler can take these decorators and generate a file like this, and then automatically share/import them where needed:
```ts
// nodejs example
async function instantiate() {
  const { AsBind } = await import('as-bind')
  const { promises } = await import('fs')
  const { join } = await import('path')
  const data = await promises.readFile(join(__dirname, 'build', 'index_wasm.wasm'))
  const wasmModule = await AsBind.instantiate(data)
  return wasmModule.exports
}
export const wasm = instantiate()
```

**Comment by aminya** [comment]
I didn't get any response regarding this issue.

**Comment by dcodeIO** [comment]
In general I think that the better Wasm<->JS interop becomes, the more feasible it becomes to explore these options.

For example, [wapi](https://github.com/dcodeIO/wapi) is a related idea into this direction, that is not quite the same, but a lower level building block that, if bound to say a `@js` decorator on a method, would feel very similar. There, the JS would be shipped as part of the Wasm binary, targeting as little glue code in between as possible.
