### ISSUE TITLE
Question: is there a way to get the name of function value?

### ISSUE THREAD

**Issue by synote** [AssemblyScript/assemblyscript#1616]
I need to get function name as a parameter, is there a way to get the name of function?

As `nameof(functionInstance)` can return the type string "Function", is there a similar way to get it's function name?

**Comment by jtenner** [comment]
We would need a runtime table, and a way to implement a `Function.prototype.name` property. Right?

This might be fun to do.

**Comment by dcodeIO** [comment]
Yeah, for `Function.prototype.name` I think we'd need to generate reflection information for all the functions in the function table, including the name but potentially more info that's also on the prototype, like `.length`. The respective first-class function could then point at the info blob of the function placed into static memory by the compiler. Probably not too hard to implement, but has the implication reflection typically has, in that we'd start shipping potentially unnecessary reflection data with modules that either don't need it or just query a subset of it.

**Comment by jtenner** [comment]
Agreed. Given that it would be excess to store all the function names on a table, is there a way to do this without the help of the std lib? If no, there needs to be a way to do that.

I can only speak on behalf of myself, because this would be very useful for `as-pect`. The runtime reflection information would be used pretty much all the time.

I'm open to ideas.

**Comment by synote** [comment]
I suppose the only way at the moment to retrieve the function name is to define `transform`. It's useful to have a builtin interface for function name as some application's feature depend on function name.

**Comment by CrimsonCodes0** [comment]
Surely the data can be lazily generated at compile time? If a function is never referenced dynamically (e.g.: stored in an array, passed to a function, stored in a variable), then no reflection data would ever have to be emit.

Also, IMHO, it wouldn't be nearly as bad to store the .length and .name, but .toString() will be a whole different story.
