### ISSUE TITLE
Missing wrap() method in generated definition files. Prevents compilation.

### ISSUE THREAD

**Issue by forcepusher** [AssemblyScript/assemblyscript#1617]
Minimal reproduction project attached.
[ASWrapDefinitionRepro.zip](https://github.com/AssemblyScript/assemblyscript/files/5792289/ASWrapDefinitionRepro.zip)

1. Use `npm run all` to compile and see the output: `42`.
2. Modify index.ts file by removing `// @ts-ignore`
3. `npm run all` again and observe the error:
`index.ts:10:74 - error TS2339: Property 'wrap' does not exist on type 'typeof SomeClass'.`

Here's a short overview of the attached repro:
```
// assembly/index.ts

export class SomeClass {
  public somefield: i32 = 42;
}
export function getSomeClass() : SomeClass {
  return new SomeClass();
}
```
```
// index.ts

import SomeModule from './build/module';
import * as Loader from '@assemblyscript/loader';
import * as fs from 'fs';

const wasmModule = Loader.instantiateSync<typeof SomeModule>(fs.readFileSync(__dirname + "/build/module.wasm"));
const someClassPointer = wasmModule.exports.getSomeClass();

// Try removing @ts-ignore, it will no longer compile.
// @ts-ignore
const someClass: SomeModule.SomeClass = wasmModule.exports.SomeClass.wrap(someClassPointer);
console.log(someClass.somefield);
```
The generated definition file needs to have the `wrap` method defined for classes, like so:
![image](https://user-images.githubusercontent.com/5948501/104132662-61cbe000-53b1-11eb-9884-956ee46bc0b7.png)

I was told to fix it somewhere around here, but I'm barely two month into web development, so it's a little bit over my head.
https://github.com/AssemblyScript/assemblyscript/blob/97dcab6ebfbd7beef17918b36803649851b6beac/src/definitions.ts#L499

**Comment by forcepusher** [comment]
Well, at least I tried.
![image](https://user-images.githubusercontent.com/5948501/104132208-54f9bd00-53ae-11eb-9b7b-e85f3f9a519b.png)

**Comment by dcodeIO** [comment]
The code location to add just the missing definition is around here: https://github.com/AssemblyScript/assemblyscript/blob/master/src/definitions.ts#L480

Agree that we should fix this :)

**Comment by forcepusher** [comment]
@dcodeIO Ready for review.
