### ISSUE TITLE
Adding memoization for Fibonacci [Question]

### ISSUE THREAD

**Issue by hipstermojo** [AssemblyScript/assemblyscript#162]
I was trying to make a Fibonacci calculator that was to use an Object Literal as a cache for the results but since the TypeScript configuration does not allow the `any` type, I am unable to define an Object Literal whose keys are any number from 0 to ~200. I wanted to know if there may be a way around this

**Comment by dcodeIO** [comment]
Have you tried using a `Map<i32,i32>`?

**Comment by hipstermojo** [comment]
So I tried using `Map<i32,i32>` but then now the compiler brings up different errors concerning the `get` method in `Map`. I am using TypeScript v 2.9.

Here's the code I implemented. Maybe you could let me know where I went wrong

```
let cache: Map<i32, i32> = new Map();
export function fib(num: i32): i32 {
  if (!cache.has(num)) {
    let a: i32 = 0,
      b: i32 = 1,
      tmp: i32;
    for (let i = 0; i < num; i++) {
      // Array destructuting presents an error so I must use a third variable for value swapping
      tmp = a;
      a = b;
      b = tmp + b;
    }
    cache.set(num, a);
  }
  return cache.get(num);
}

```

**Comment by MaxGraey** [comment]
Everything works fine. Just see [this example](https://webassembly.studio/?f=cx7da608c6g)
By the way AssemblyScript doesn't depend on TypeScript package.

**Comment by MaxGraey** [comment]
By the way for huge input numbers you can use analytical fib implementation:
```ts
const SQRT5 = Math.sqrt(5.0);
const C1    = Math.log((SQRT5 + 1.0) * 0.5);
const C2    = Math.log((SQRT5 - 1.0) * 0.5);

function fib(n: i64): i64 {
  if (n <= 0) return 0;
  var a = Math.exp(C1 * n);
  var b = Math.exp(C2 * n);
  return <i64>((n & 1 ? a + b : a - b) * (1.0 / SQRT5));
}
```

**Comment by hipstermojo** [comment]
Well now it compiles for sure however now the JavaScript code fails to "recognize" the exported code as either functions or objects. This seems to only happen when I have the global `cache` variable in the code. I am running this code on Node v 10, not on a browser.


The error from the terminal
```
TypeError: WebAssembly Instantiation: Import #0 module="env" error: module is not an object or function

```

**Comment by MaxGraey** [comment]
You JS side should looks like:
```js
WebAssembly.instantiateStreaming(fetch("build/fib.wasm"), {
  env: {
    abort(msg, file, line, column) {
      console.error("abort called at main.ts:" + line + ":" + column);
    }
  },
  console: {
    logi(value) { console.log('logi: ' + value); }
  }
}).then(result => {
  const { fib } = result.instance.exports;
  fib(123);
});
```

**Comment by hipstermojo** [comment]
Everything works now. On the browser at least. Thanks.

**Comment by dcodeIO** [comment]
> an Object Literal whose keys are any number from 0 to ~200

Just noticed: From a performance perspective, an array with 200 elements will most likely yield better results:

```js
var cache = new Array<i32>(200);
```

Now, when accessing a value, you can use `value = unchecked(cache[num])`, which also disables the usual range check where `num` is already know to be in range. Note that the array is initialized with all `0` values.

**Comment by hipstermojo** [comment]
Well the 200 maximum limit was just for an example but that seems like an interesting approach to caching.

I seem to be facing a new problem however. When I try calculating the fibonacci of 50, it returns `-298632863` which is because it already exceeds the `i32` maximum limit since the fibonacci of 50 is `12,586,269,025` but when I try to use the `i64` integers I get this type error


> Uncaught (in promise) TypeError: wasm function signature contains illegal type
at WebAssembly.instantiateStreaming.then.result


The code hasn't changed much from my previous implementation

```js
import "allocator/arena";

 let cache: Map<i64, i64> = new Map();
 export function fib(num: i64): i64 {
   if (!cache.has(num)) {
     let a: i64 = 0,
       b: i64 = 1,
       tmp: i64;
     for (let i = 0; i < num; i++) {
       tmp = a;
       a = b;
       b = tmp + b;
     }
     cache.set(num, a);
   }
   return cache.get(num);
 }

```

**Comment by MaxGraey** [comment]
It seems you try call `fib` from JS, but JavaScript doesn't support interop with i64 types yet. So you can do 2 variants:
1. use `fib(num: f64): f64` instead `fib(num: i64): i64`.
2. Do similar like this:
```ts
var __fib_lo: u32 = 0;
var __fib_hi: i32 = 0;
export function fib(lo: u32, hi: i32): void {
   var num = (<i64>hi << 32) + <i64>lo;
   ...
   var result: i64 = cache.get(num);
   __fib_lo = <u32>(result & 0xFFFFFFFF);
   __fib_hi = <i32>(result >> 32);
}

export function getFibLoResult(): u32 {
  return __fib_lo;
}

export function getFibHiResult(): u32 {
  return __fib_hi;
}
```
in JS:
```js
import Long from "long";
...
exports.fib(123, 0);
var lo = exports.getFibLoResult();
var hi = exports.getFibHiResult();
var result = new Long(lo, hi);
```

**Comment by hipstermojo** [comment]
These solutions work fine. But the last two seem to need quite some wrapping code obviously.
Seems I might have to be using `f64` for all my operations for good measure.

Is the interop a problem with AssemblyScript or browser engines for JavaScript? (If it's AssemblyScript related are there plans to fix it?)

Also, is there provided documentation on how to mitigate such problems? Because your wiki did not have these details.

**Comment by MaxGraey** [comment]
This interop limitation comes from browsers and WebAssembly spec. Currently there is [one big-int proposal which in Stage 3](https://github.com/tc39/proposal-bigint) but not all browsers support BigInt yet.

**Comment by dcodeIO** [comment]
There is a [Binaryen pass](https://github.com/WebAssembly/binaryen/blob/master/src/passes/LegalizeJSInterface.cpp) that can transform i64 on the boundaries to a pair of i32s as well. To enable it, it should be sufficient to add `--runPasses legalize-js-interface` to the command line when invoking `asc`.
