### ISSUE TITLE
How to debug compile time assertion error?

### ISSUE THREAD

**Issue by AfflatusX** [AssemblyScript/assemblyscript#1621]
Hi all - one thing I encountered a couple times when using AS is that the compiler could throw AssertionError on correct typescript code.

Of course, correct TS code is not correct AssemblyScript code. However, when that happens, the compiler usually just say Error [AssertionError]: assertion failed, with some minimized code stack/context. Whenever that happens I have zero clue in terms of which line of my code is triggering that or how to fix it.

Is there a good way to get more debugging info from the error message?

**Comment by dcodeIO** [comment]
When an assertion is hit, the `env.abort` import is called with the message, if any, file name, line and column number. It may also help to compile with debug info, potentially disabling optimizations, so stack traces include function names.

**Comment by AfflatusX** [comment]
@dcodeIO thanks for the reply. Are you talking about compile time or runtime assertion error?

This is what I'm talking about when running yarn asbuild:untouched :

`Error [AssertionError]: assertion failed
    at i.assert (.../node_modules/assemblyscript/dist/assemblyscript.js:7:701080)
    at T.finalizeVirtualStub (.../node_modules/assemblyscript/dist/assemblyscript.js:7:291905)
    at T.compile (.../node_modules/assemblyscript/dist/assemblyscript.js:7:194494)
    at Object.t.compile (.../node_modules/assemblyscript/dist/assemblyscript.js:7:438198)
    at .../node_modules/assemblyscript/cli/asc.js:715:29
    at measure (.../node_modules/assemblyscript/cli/asc.js:1099:3)
    at Object.main (.../node_modules/assemblyscript/cli/asc.js:714:24)
    at .../node_modules/assemblyscript/bin/asc:21:47
.../node_modules/binaryen/index.js:54
function Ka(){var b=a.preRun.shift();Fa.unshift(b)}var L=0,La=null,Ma=null;a.preloadedImages={};a.preloadedAudios={};function q(b){if(a.onAbort)a.onAbort(b);v(b);wa=!0;throw new va("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function Na(b){var d=Oa;return String.prototype.startsWith?b.startsWith(d):0===b.indexOf(d)}var Oa="data:application/octet-stream;base64,",Pa="<<< WASM_BINARY_FILE >>>";if(!Na(Pa)){var Qa=Pa;Pa=a.locateFile?a.locateFile(Qa,p):p+Qa}var Ra,Sa;`

I guessed this one (related to using interface), but not sure I would be that lucky next time.

**Comment by MaxGraey** [comment]
It will be great have minimal example which reproduce this assert error. Covering all possible unsupported cases with proper error is quite hard

**Comment by dcodeIO** [comment]
Oh I see, this is happening during compilation. The distribution ships with source maps, and we rely on `source-map-support` as a dependency to make sense of these. You could try to `npm i source-map-support`.

**Comment by AfflatusX** [comment]
> It will be great have minimal example which reproduce this assert error. Covering all possible unsupported cases with proper error in compiler is quite hard

The actual issue was similar to https://github.com/AssemblyScript/assemblyscript/issues/1469 so I ended up using abstract class instead.

I'm not familiar with the compiler, but if it can point to the line of code triggering the assertion error, that would probably be sufficient. But of course, depending on the compiler this could be impossible as well.

**Comment by AfflatusX** [comment]
> Oh I see, this is happening during compilation. The distribution ships with source maps, and we rely on `source-map-support` as a dependency to make sense of these. You could try to `npm i source-map-support`.

source-map-support does give a better stack trace. Feel free to close this issue if adding source code line number/file name is impossible during compile assertion.
