### ISSUE TITLE
Assigning compatible concrete class to generic base class typed variable errors out during compile time.

### ISSUE THREAD

**Issue by AfflatusX** [AssemblyScript/assemblyscript#1622]
```
abstract class Base<T> {
  abstract doSomething(val: T): void;
}

class A extends Base<i32> {
  doSomething(val: i32): void {

  }
}

let refA: Base<i32> | null = new A(); 
```

Repro: https://webassembly.studio/?f=bk298o1egu7

would throw `Task build failed: type argument count mismatch`

Known problem? Any way to work around it?

**Comment by AfflatusX** [comment]
Looks like changing A to A<i32> passes compilation... Is it just making sure the number of type args needs to match? or there are some more reasoning behind that?

**Comment by dcodeIO** [comment]
Whenever an assertion is hit or an exception thrown where there should be a diagnostic instead, it's most likely a bug. Something around [here](https://github.com/AssemblyScript/assemblyscript/blob/485cfee144f8a682ec41e3952b7e0dc5d91d6952/src/program.ts#L4218-L4231) it seems.

**Comment by AfflatusX** [comment]
Yup - I'm poking around that section of code as you commented lol However, I don't have much context on why that check exists in first place (line 4219).

**Comment by dcodeIO** [comment]
When a concrete `Class` is instantiated, for example an `A<i32>` from a `ClassPrototype` `A<T>`, it fills in the concrete type parameters. For that it checks that both the number of abstract parameters and concrete arguments matches, which seems to fail, hmm.

**Comment by AfflatusX** [comment]
Looks like the statement failed was actually the first part: `if (!typeParameters ...`. Indeed in my example A doesn't have type params, but that's expected right?
