### ISSUE TITLE
Does AssemblyScript remove JS quirks?

### ISSUE THREAD

**Issue by stephanoparaskeva** [AssemblyScript/assemblyscript#1624]
Does AssemblyScript make the language better by removing quirks. Does it make the language more like python in that it can handle numbers of any length (instead of capping and rounding in JS) and prevent the quirks that come from actions like adding NaN and Arrays etc ?

**Comment by forcepusher** [comment]
A short response to this would be "Yes".

Long answer:
Fast 64 bit integers were one of the main reasons for me to use AssemblyScript along with classic TypeScript code. The "bigint" type from modern JS is a bit too slow for some use cases.
AssemblyScript has an upcoming solution for going over 64 bits as well https://github.com/MaxGraey/as-bignum
Quirks like adding NaN to Arrays don't exist in WebAssembly altogether, unless someone deliberately took their time to implement them. AssemblyScript doesn't do that - it's strictly typed.

**Comment by stephanoparaskeva** [comment]
> A short response to this would be "Yes".
> 
> 
> 
> Long answer:
> 
> Fast 64 bit integers were one of the main reasons for me to use AssemblyScript along with classic TypeScript code. The "bigint" type from modern JS is a bit too slow for some use cases.
> 
> AssemblyScript has an upcoming solution for going over 64 bits as well https://github.com/MaxGraey/as-bignum
> 
> Quirks like adding NaN to Arrays don't exist in WebAssembly altogether, unless someone deliberately took their time to implement them. AssemblyScript doesn't do that - it's strictly typed.

I see, that's great.

Also -- why does AssemblyScript focus on a OOP approach and not a functional approach?

**Comment by forcepusher** [comment]
That's more in-depth question, I won't risk answering it myself. You can either wait for core developer team to respond or try [AssemblyScript Discord](https://discord.gg/vSBbJ5T) for a follow-up.
