### ISSUE TITLE
Is there a linter for assemblyscript ?

### ISSUE THREAD

**Issue by nvuillam** [AssemblyScript/assemblyscript#1628]
Hi, I'm the maintainer of [Mega-Linter](https://github.com/nvuillam/mega-linter) and I love to add new linters that can be of use to the open source community :)

Is there a linter for AssemblyScript ? :)

**Comment by forcepusher** [comment]
Hello. From what I've seen, most AssemblyScript developers use Prettier.
I've rolled an opinionated [ESLint config](https://gist.github.com/forcepusher/735ae80a5715af68846920627e22ad6b) as well.
But I don't think we have much actually designed for AssemblyScript mind.

**Comment by nvuillam** [comment]
Prettier is more a formatter, and is already integrated within Mega-Linter:)
Opinionated ESlint config is great, saves a lot of time in manual configuration and enforces a common style :)

Did you consider publishing one for AssemblyScript ? It seems pretty easy ^^
https://eslint.org/docs/developer-guide/shareable-configs

If you do that please let me know and I can integrate it in Mega-Linter :)
