### ISSUE TITLE
Postfixed number literals not recognized in declaration section of for loop

### ISSUE THREAD

**Issue by 00ff0000red** [AssemblyScript/assemblyscript#1630]
It seems that, when using a named integer literal in the start of a for loop, ASC throws an error.

I assigning a variable in the first part of a for loop using a "named" number literal. (what are these actually called?)
ASC gave the following:
> ```
> INFO asc module.ts --textFile module.wat --binaryFile module.wasm -O3 --runtime none --noExportMemory --enable reference-types
> ;; ERROR TS1005: ';' expected.
> ;; 
> ;;    for (let i = 2i64; i < n; ++i) {
> ;;                 ~
> ;;  in module.ts(2,16)
> ```

```as
export function nop(n: i64): void {
  for (let i = 2i64; i < n; ++i) {
    // nop
  }
}
```

TypeScript itself doesn't give an error, if I use, say, a bigint literal there.

I believe that it's not expecting the `i64` part of `2i64`, instead, it's just searching for the next semi-colon?

**Comment by MaxGraey** [comment]
`2i64` is not TypeScript compatible literal. It only support for BigInts. You should use `2 as i64` instead

**Comment by 00ff0000red** [comment]
@MaxGraey But, it applies to any number followed by an identifier.

Ex:
```js
export function nop(n: i64): void {
  for (let i = 2n; i < n; ++i) {
    // nop
  }
}
```

still fails, while using valid TS syntax.

**Comment by MaxGraey** [comment]
No, I meant in TS =) On AssemblyScript BigInts doesn't support yet. But you could use i64/u64.
I mean postfixed literals in TS world support only for bigints. For the rest you should use `as`. Same for AS.

```ts
export function nop(n: i64): void {
  for (let i = 2 as i64; i < n; ++i) {
    // nop
  }
}
```

**Comment by 00ff0000red** [comment]
So, will this eventually be supported, or are there no plans to support it?

**Comment by MaxGraey** [comment]
> are there no plans to support it?

I don't think so
