### ISSUE TITLE
V128.load isn't defined, even with simd flags

### ISSUE THREAD

**Issue by 00ff0000red** [AssemblyScript/assemblyscript#1632]
I was writing into memory and trying to read it back as a V128, but I'm getting an error suggesting that V128.load isn't defined at all.
```
;; ERROR TS2339: Property 'load' does not exist on type '~lib/vector/V128'.
;; 
;;      const _temp = V128.load(temp.dataStart);
;;                         ~~~~
```

According to the website's [V128 section](https://www.assemblyscript.org/environment.html#low-level-webassembly-operations), this function does exist. Is this a bug?

**Comment by MaxGraey** [comment]
SIMD is experimental in AS and browsers. It mean you should turn it on as `--enable simd` for asc.
Also it should be `v128` not `V128`. See [playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWhhbGYmZW5hYmxlPXNpbWQKY29uc3QgX3RlbXAgPSB2MTI4LmxvYWQoMCk7CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==)

**Comment by 00ff0000red** [comment]
I'm passing the ASC simd flags, I've got about every experimental flag that Chromium offers enabled, but I did not know that it was a lower-case 'V', I misread the site's "v128.load" as "V128.load," that's on me, sorry.
