### ISSUE TITLE
Compiler hangs on returning postfixed number literal from a function with mismatching types

### ISSUE THREAD

**Issue by 00ff0000red** [AssemblyScript/assemblyscript#1637]
[Reproduction link](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWhhbGYKZXhwb3J0IGZ1bmN0aW9uIGJ1ZygpOiBpMzIgewogIGNvbnN0IHggPSAxdTg7CgogIHJldHVybiB4Owp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==).
```ts
export function bug(): i32 {
  const x = 1u8;

  return x;
}
```
The compiler hangs when using a postfixed literal (does ASC even have these?), but only if it's in a position other than the return value.

I.e., this compiles fine:
```ts
export function probably_still_a_bug(): i32 {
  return 1u8;
}
```

**Comment by MaxGraey** [comment]
duplicate with #1630

**Comment by MaxGraey** [comment]
I guess `1u8` accidentally support here as side effect of `parseInt('1u8') == 1`
