### ISSUE TITLE
Annotations @inline error in vscode

### ISSUE THREAD

**Issue by nuintun** [AssemblyScript/assemblyscript#1640]
I download examples from https://github.com/AssemblyScript/examples

But:

![企业微信截图_20210128172914](https://user-images.githubusercontent.com/1730277/106117965-8b954d00-618e-11eb-9373-52d6f1d301b3.png)

Is there any way to fix this?

**Comment by dcodeIO** [comment]
Since AssemblyScript allows decorators like `@inline` on functions, but TypeScript does not, silencing the error can be achieved by adding a `// @ts-ignore` comment on the previous line. What's visually more appealing depends a bit on personal preference.

**Comment by nuintun** [comment]
Thanks~
