### ISSUE TITLE
Minimal runtime GC collects pinned objects.

### ISSUE THREAD

**Issue by forcepusher** [AssemblyScript/assemblyscript#1646]
UPDATE: See the [short version of the repro](https://github.com/AssemblyScript/assemblyscript/issues/1646#issuecomment-770170161).
However this one might still be useful because it has to pass the test.
----
Repro: [MinimalGCBugRepro.zip](https://github.com/AssemblyScript/assemblyscript/files/5897493/MinimalGCBugRepro.zip)
Steps to reproduce:
1. `npm run asbuild:incremental` then `npm test`.
2. Observe the expected repeating trace `123456`.
3. `npm run asbuild:minimal` then `npm test`.
4. Observe the unexpected traces with random numbers.

Reproduction overview:
```
export class SomeClass {
  public someArray: StaticArray<SomeNestedClass>;

  public constructor() {
    this.someArray = new StaticArray<SomeNestedClass>(1);
    this.someArray[0] = new SomeNestedClass();
  }

  public growArray(): void {
    const resizedArray = new StaticArray<SomeNestedClass>(this.someArray.length * 2);
    memory.copy(changetype<usize>(resizedArray), changetype<usize>(this.someArray),
      offsetof<SomeNestedClass>() * this.someArray.length);
    this.someArray = resizedArray;
  }

  public outputFirstArrayElement(): void {
    trace(this.someArray[0].someField.toString());
  }
}

class SomeNestedClass {
  public someField: i32 = 123456;
}
```

```
const myModule = require("..");

const someClass = new myModule.SomeClass();
myModule.__pin(someClass);
someClass.growArray();
someClass.outputFirstArrayElement();
myModule.__collect();
someClass.growArray();
someClass.outputFirstArrayElement();
```

**Comment by forcepusher** [comment]
After playing a little bit more with the reproduction, seems like none of the memory copying magic is needed to break it. StaticArray drops the references to classes anyway. Simplier repro incoming soon.

**Comment by forcepusher** [comment]
Another update: Array doesn't have to be static. It fails with a regular array as well on the second `__collect` call.
Repro v3: [MinimalGCBugReproV3.zip](https://github.com/AssemblyScript/assemblyscript/files/5897522/MinimalGCBugReproV3.zip)
Same reproduction steps, now it dies with an error after second `__collect`.
```
export class SomeClass {
  public someArray: Array<SomeNestedClass>;

  public constructor() {
    this.someArray = new Array<SomeNestedClass>(1);
    this.someArray[0] = new SomeNestedClass();
  }

  public outputFirstArrayElement(): void {
    trace(this.someArray[0].someField.toString());
  }
}

class SomeNestedClass {
  public someField: i32 = 123456;
}
```

**Comment by dcodeIO** [comment]
Thanks for digging through this, the repro was super helpful :) Should be fixed with the next release at 0 UTC.
