### ISSUE TITLE
Do not use `__` before garbage collection API 

### ISSUE THREAD

**Issue by aminya** [AssemblyScript/assemblyscript#1648]
_Copied from https://github.com/AssemblyScript/assemblyscript/pull/1559#issuecomment-758299586_

### Description

I want to propose to use a better notation for the **public** assembly script functions. There is no need to prepend `__` before the end of the functions. 

### Reasoning

Usually, `__` is used before something that should not be used, not something that every developer needs to call manually. TypeScript provides many ways to prevent name conflicting that are better than prefixing underscores.

I would recommend renaming `__collect` to `collect`. If someone wants these functions to have different names (rare), they can do:
```ts
import { collect as as_collect } from '...'
```

Using `__` and similar notations are used in languages like C that do not have any notion of namespace or module and the names conflict with each other. This is not certainly the case for AssemblyScript.

### Example from other languages

Julia, the only language I know that allows triggering garbage collection manually, uses GC.gc() function for triggering garbage collection. GC is a module (namespace) and gc is the function name.

https://docs.julialang.org/en/v1/base/base/#Base.GC.gc

### Potential Methods

1) There was one suggested by @MaxGraey here: 
https://github.com/AssemblyScript/assemblyscript/pull/1559#issuecomment-758316798

2) If I was the one who makes the decision, I would just use the power of TypeScript namespaces and modules. In TypeScript it is already possible to rename the functions using `as` when importing.

**Comment by dcodeIO** [comment]
The expectation is that the runtime helpers are temporary and will go away once Wasm GC becomes available. As such I am not in favor of changing their names, since that is an avoidable intermediate breaking change. Also, the current naming scheme reliably avoids name collections in practice, while alternative's do not.

**Comment by 00ff0000red** [comment]
Namespacing would always prevent the naming collison, afaik, that's quite literially it's *sole* purpose. How would it not prevent collisions in practice?

**Comment by aminya** [comment]
Are namespaces supported by assemblyscript? If that is true, there is no point in using these old workarounds for name collisions.

**Comment by 00ff0000red** [comment]
@aminya [I think so](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKLyoqIENhbGN1bGF0ZXMgdGhlIG4tdGggRmlib25hY2NpIG51bWJlci4gKi8KZXhwb3J0IG5hbWVzcGFjZSBteU1hdGggewogIGV4cG9ydCBmdW5jdGlvbiBmaWIobjogaTMyKTogaTMyIHsKICAgIHZhciBhID0gMCwgYiA9IDEKICAgIGlmIChuID4gMCkgewogICAgICB3aGlsZSAoLS1uKSB7CiAgICAgICAgbGV0IHQgPSBhICsgYgogICAgICAgIGEgPSBiCiAgICAgICAgYiA9IHQKICAgICAgfQogICAgICByZXR1cm4gYgogICAgfQogICAgcmV0dXJuIGEKICB9Cn0KCmV4cG9ydCBjb25zdCB6ZXJvX3RoX2ZpYiA9IG15TWF0aC5maWIoMCk7CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==)

Btw, another example, when calling V8 internals from JS, one can just call `globalThis.gc(true)` or `%collectGarbage(true)`, but it's not namespaced.

**Comment by dcodeIO** [comment]
Regarding namespacing, this can conflict:

```ts
// in library code, implicit
export { gc }; // with gc.collect() for example

// in user code, explicit
export const gc = true; // primitive, cannot have a `.collect()` property
```

The `__` naming is not pretty but more robust. Overall doesn't seem worth to break the API for something that isn't clearly an improvement.

**Comment by 00ff0000red** [comment]
@dcodeIO That cannot possibly conflict, since the user code has to *explicitly* import the library's gc variable, it can't end up there on accident.

This, on the other hand would be a problem:
```ts
import { gc } from "./library.as";
export const gc = true;
```

Actually, wait, no; JavaScript allows declaring global lexicially scoped variables that can shadow imports.

Anyway, one could easily do:
```ts
import { gc as garbageCollection } from "./library.as";
export const gc = true;
```

**Comment by dcodeIO** [comment]
When the `--exportRuntime` option is used, it may, since user code doesn't have to import it and can happily shadow. Providing the option is useful, however, so one doesn't have to bake that into code.
