### ISSUE TITLE
DataView getUint32 and getUint64 returns was wrong

### ISSUE THREAD

**Issue by nuintun** [AssemblyScript/assemblyscript#1657]
See: [Assembly Script Editor](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWImaW1wb3J0TWVtb3J5JnVzZT1NYXRoPUpTTWF0aApleHBvcnQgZnVuY3Rpb24gdWludDMyKHZhbHVlOiB1MzIpOiB1MzIgewogIGNvbnN0IGR2ID0gbmV3IERhdGFWaWV3KG5ldyBVaW50OEFycmF5KDQpLmJ1ZmZlcik7CgogIGR2LnNldFVpbnQzMigwLCB2YWx1ZSk7CgogIHJldHVybiBkdi5nZXRVaW50MzIoMCk7Cn0KCmV4cG9ydCBmdW5jdGlvbiB1aW50NjQodmFsdWU6IHU2NCk6IHU2NCB7CiAgY29uc3QgZHYgPSBuZXcgRGF0YVZpZXcobmV3IFVpbnQ4QXJyYXkoOCkuYnVmZmVyKTsKCiAgZHYuc2V0VWludDY0KDAsIHZhbHVlKTsKCiAgcmV0dXJuIGR2LmdldFVpbnQ2NCgwKTsKfQojIWh0bWwKPHA+UHJlc3MgRjEyIHNlZSBDb25zb2xlPC9wPgo8c2NyaXB0PgogIGNvbnN0IHUzMiA9IDQyNjExNDk0MzY7CiAgY29uc3QgdTY0ID0gMTg0NDY0NjAzODY3NTcyNDMzNzZuOwogIGNvbnN0IG1lbW9yeSA9IG5ldyBXZWJBc3NlbWJseS5NZW1vcnkoeyBpbml0aWFsOiAoKDUxMiArIDB4ZmZmZikgJiB+MHhmZmZmKSA+Pj4gMTYgfSk7CgogIGZ1bmN0aW9uIHVpbnQzMih2YWx1ZSkgewogICAgY29uc3QgZHYgPSBuZXcgRGF0YVZpZXcobmV3IFVpbnQ4QXJyYXkoNCkuYnVmZmVyKTsKCiAgICBkdi5zZXRVaW50MzIoMCwgdmFsdWUpOwoKICAgIHJldHVybiBkdi5nZXRVaW50MzIoMCk7CiAgfQoKICBmdW5jdGlvbiB1aW50NjQodmFsdWUpIHsKICAgIGNvbnN0IGR2ID0gbmV3IERhdGFWaWV3KG5ldyBVaW50OEFycmF5KDgpLmJ1ZmZlcik7CgogICAgZHYuc2V0QmlnVWludDY0KDAsIHZhbHVlKTsKCiAgICByZXR1cm4gZHYuZ2V0QmlnVWludDY0KDApOwogIH0KCiAgY29uc29sZS5sb2coJ0Jyb3dzZXIgdTMyOicsIHUzMiwgdWludDMyKHUzMikpOwogIGNvbnNvbGUubG9nKCdCcm93c2VyIHU2NDonLCB1NjQsIHVpbnQ2NCh1NjQpKTsKCiAgbG9hZGVyCiAgICAuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgZW52OiB7IG1lbW9yeSB9IH0pCiAgICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgICAgY29uc29sZS5sb2coJ0Fzc2VtYmx5IHUzMjonLCB1MzIsIGV4cG9ydHMudWludDMyKHUzMikpOwogICAgICBjb25zb2xlLmxvZygnQXNzZW1ibHkgdTY0OicsIHU2NCwgZXhwb3J0cy51aW50NjQodTY0KSk7CiAgICB9KTsKPC9zY3JpcHQ+)

```ts
export function uint32(value: u32): u32 {
  const dv = new DataView(new Uint8Array(4).buffer);

  dv.setUint32(0, value);

  return dv.getUint32(0);
}

export function uint64(value: u64): u64 {
  const dv = new DataView(new Uint8Array(8).buffer);

  dv.setUint64(0, value);

  return dv.getUint64(0);
}
```

![image](https://user-images.githubusercontent.com/1730277/106590416-05ab4480-6588-11eb-86e2-be56b16581df.png)

**Comment by dcodeIO** [comment]
That's expected. WebAssembly only has an `i32` type, but no native `u32` type to indicate to JavaScript that the value is unsigned. 

```js
var a = -33817860;
console.log(a >>> 0); // 4261149436
```

**Comment by MaxGraey** [comment]
It's not error. Just behaviour of interop of js <-> wasm. Wasm can pass and accept only integer types from host, so when you return `u32` it's actually `i32`. But `-33817860 >>> 0 == 4261149436`

**Comment by nuintun** [comment]
@dcodeIO @MaxGraey 

How to convert `u64 -> i64` and `i64 -> u64` ?

```
num -> u8: num & 0xff
num -> u16: num & 0xffff
num -> u32: num >>> 0

num -> i8: (num << 24) >> 24
num -> i16: (num << 16) >> 16
num -> i32: num | 0
```

**Comment by MaxGraey** [comment]
> How to convert u64 -> i64 and i64 -> u64 ?

On javascript side it's BigInt, so:
1) u64 -> i64

```ts
function i64(x) { // x should be BigInt
  return BigInt.asIntN(64, x);
}
```
2) i64 -> u64
```ts
function u64(x) { // x should be BigInt
  return BigInt.asUintN(64, x);
}
```

**Comment by nuintun** [comment]
@MaxGraey  3Q~
