### ISSUE TITLE
Instantiation without semicolons causes crash

### ISSUE THREAD

**Issue by lrettig** [AssemblyScript/assemblyscript#167]
Calling `new Class` without parentheses in a function without semicolons seems to cause the compiler to crash.

Code sample: https://webassembly.studio/?f=w3e7cc0usm

Snippet:

```javascript
class Foo {}

function add(x: i32, y: i32): i32 {
  var foo = new Foo
  return x + y
}

add(1, 2)
```

Try to build and you'll see the browser freeze. I get the same issue on the commandline:

```
<--- Last few GCs --->

[55172:0x102802a00]    15393 ms: Mark-sweep 1281.2 (1337.4) -> 1281.2 (1337.4) MB, 3052.1 / 0.0 ms  allocation failure GC in old space requested
[55172:0x102802a00]    18417 ms: Mark-sweep 1281.2 (1337.4) -> 1281.2 (1306.4) MB, 3024.0 / 0.0 ms  last resort
[55172:0x102802a00]    21426 ms: Mark-sweep 1281.2 (1306.4) -> 1281.2 (1306.4) MB, 3009.3 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3b0b503a8799 <JSObject>
    1: /* anonymous */ [/Users/user/folder/ewasm-as-multisig/node_modules/assemblyscript/dist/assemblyscript.js:~1] [pc=0x1514097510fd](this=0x2392fb4c6959 <t map = 0x2f9686c8c1d9>,e=1109,t=2,r=0x12c46ede0719 <e map = 0x2f9686c8c7b1>,n=0x3f65f4882201 <null>,i=0x3f65f4882201 <null>,a=0x3f65f4882201 <null>)
    2: /* anonymous */ [/Users/user/folder/ewasm-as-multisig/node_modules/ass...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/user/.nvm/versions/node/v8.6.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/user/.nvm/versions/node/v8.6.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/user/.nvm/versions/node/v8.6.0/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/Users/user/.nvm/versions/node/v8.6.0/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/user/.nvm/versions/node/v8.6.0/bin/node]
 6: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/user/.nvm/versions/node/v8.6.0/bin/node]
 7: 0x1514095846fd
sh: line 1: 55021 Abort trap: 6           npm run asbuild:untouched
```

**Comment by dcodeIO** [comment]
With master, on the command line I get:

```
ERROR AS100: Operation not supported.

   var foo = new Foo
                 ~~~
```

Anything else I need to know to reproduce?

**Comment by lrettig** [comment]
Do you see the freezing behavior I described in WebAssembly studio? Try to build this: https://webassembly.studio/?f=w3e7cc0usm

**Comment by dcodeIO** [comment]
Yes, I am also seeing the freezing behavior there. Actually, there have been a few issues lately that worked on the command line but not in WASM studio, so that'll require some investigation as well.

**Comment by lrettig** [comment]
Strange. When I simply `npm install AssemblyScript/assemblyscript` I encounter this issue. When I instead manually checkout the repo and `npm link` it, I don't. I assumed this would do the same thing.

**Comment by dcodeIO** [comment]
When saving the source file with "\n" line endings, it results in an infinite loop on the command line as well.

**Comment by dcodeIO** [comment]
That should, theoretically, fix the rogue crash.

**Comment by lrettig** [comment]
Thanks, I'll give this a try

**Comment by lrettig** [comment]
I'm still seeing the infinite loop using the most recent commit:

```
> grep assemblyscript package-lock.json
    "assemblyscript": {
      "version": "github:AssemblyScript/assemblyscript#585d2461657ffd9a82688c0a0f620e3a7e748767",
      "from": "github:AssemblyScript/assemblyscript",
```

**Comment by lrettig** [comment]
When I `npm install` from github, I get the infinite loop. When I `npm link` against a local repo, I don't get an infinite loop but it cannot find the stdlib:

```
> ls -la node_modules/assemblyscript/std
ls: node_modules/assemblyscript/std: No such file or directory
> npm install --save-dev AssemblyScript/assemblyscript
npm WARN ewasm-as-multisig No description
npm WARN ewasm-as-multisig No repository field.
npm WARN ewasm-as-multisig No license field.

+ assemblyscript@0.5.0
updated 1 package and audited 18 packages in 17.385s
found 0 vulnerabilities

> ls -la node_modules/assemblyscript/std
total 24
drwxr-xr-x   8 lanerettig  staff  256 Jul 10 18:46 .
drwxr-xr-x  15 lanerettig  staff  480 Jul 10 18:46 ..
-rw-r--r--   1 lanerettig  staff  188 Oct 26  1985 README.md
drwxr-xr-x  22 lanerettig  staff  704 Jul 10 18:46 assembly
-rw-r--r--   1 lanerettig  staff  218 Oct 26  1985 assembly.json
drwxr-xr-x   5 lanerettig  staff  160 Jul 10 18:46 portable
-rw-r--r--   1 lanerettig  staff  278 Oct 26  1985 portable.json
drwxr-xr-x   4 lanerettig  staff  128 Jul 10 18:46 types
```

**Comment by MaxGraey** [comment]
@lrettig In WAS works fine after latest fixes: https://webassembly.studio/?f=w3e7cc0usm

**Comment by lrettig** [comment]
The full code is here, in case it compiles for you! https://github.com/lrettig/ewasm-as-multisig

**Comment by MaxGraey** [comment]
bwt [this](https://github.com/lrettig/ewasm-as-multisig/blob/master/assembly/index.ts#L36) doesn't support yet.

**Comment by lrettig** [comment]
No problem. The `super` call doesn't do anything yet but I added it because I was getting this error:

```
 31   constructor(
      ~~~~~~~~~~~~
 32     owners: Address[],
    ~~~~~~~~~~~~~~~~~~~~~~
...
 42     write<Set>("isOwner", isOwner)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 43   }
    ~~~

assembly/index.ts(31,3): error TS2377: Constructors for derived classes must contain a 'super' call.
```

**Comment by MaxGraey** [comment]
Yah, this error from TS diagnostics. For current stage you can ignore this. I mean `super` not works properly without vtable. Just keep in mind. You can check this in WAS: https://webassembly.studio/?f=w3e7cc0usm

**Comment by lrettig** [comment]
Thanks. If this error can be safely ignored maybe it could be relabeled a warning instead of an error!

**Comment by dcodeIO** [comment]
`TS2377` is not defined in `diagnosticMessaages.json`. Are you sure you are getting this from asc?

**Comment by lrettig** [comment]
Looks that way to me:

```
> npm link assemblyscript
~/ewasm-as-multisig/node_modules/assemblyscript -> ~/.nvm/versions/node/v8.6.0/lib/node_modules/assemblyscript
> npm run asbuild

> @ asbuild ~/ewasm-as-multisig
> npm run asbuild:untouched && npm run asbuild:optimized


> @ asbuild:untouched ~/ewasm-as-multisig
> asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate


16 import { Set } from "internal/set"
                       ~~~~~~~~~~~~~~

assembly/index.ts(16,21): error TS2307: Cannot find module 'internal/set'.


 32   constructor(
      ~~~~~~~~~~~~
 33     owners: Address[],
    ~~~~~~~~~~~~~~~~~~~~~~
...
 44     write<Set>("isOwner", isOwner)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 45   }
    ~~~

assembly/index.ts(32,3): error TS2377: Constructors for derived classes must contain a 'super' call.
```

**Comment by dcodeIO** [comment]
Seems that this is using the old prototype, somehow. If you didn't install just `assemblyscript` (old prototype) from npm instead of `AssemblyScript/assemblyscript` (master from GitHub), that might be because there's still an old install of the prototype somewhere in your path.

**Comment by lrettig** [comment]
As I described in https://github.com/AssemblyScript/assemblyscript/issues/167#issuecomment-403890731 when I `npm install AssemblyScript/assemblyscript` I run into the infinite loop issue. When I instead `git checkout AssemblyScript/assemblyscript` and then `npm link` into it (which is what I've done here) I don't run into the infinite loop issue but instead it can't find the std lib.

**Comment by dcodeIO** [comment]
My assumption would be that, even if you do `npm link` the new one, that there's still an old prototype somewhere on your system that takes precedence over the new linked `asc` in your path, hence you end up invoking the old prototype with `asc`.

You could try `npm -g remove assemblyscript`, in case there is an old global install. If that doesn't work, make sure there is no `asc` in your global npm directory (Win: `C:\Users\USER\AppData\Roaming\npm`, Linux might be: `/home/USER/npm` or similar).

**Comment by MaxGraey** [comment]
It seems I figured out your problem. Try declare constructor in MultiSigWalletFactory:

```ts
class MultiSigWalletFactory extends Contract {
  constructor() {}  // <<<< Add constructor
  create(owners: Address[], required: i32): Address {
     ...
  }
}
```

**Comment by lrettig** [comment]
It's working, thanks!
