### ISSUE TITLE
unable to import from library (ascMain not working?)

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1679]
Code is here: https://github.com/lume/glas/pull/111

`asc v0.17.7`

I believe `ascMain` is set up correctly, but it doesn't seem to work.

From that example, here is the `aswebglue` `ascMain` field pointing to `src/WebGL.ts`:

> https://github.com/lume/ASWebGLue/blob/9499782e0d7b3b9f51bbe3c7238abf0838f51c71/package.json#L4
> ```js
>   "ascMain": "src/WebGL.ts",
> ```

Here is `src/WebGL.ts` which is located exactly where `ascMain` points to:

> https://github.com/lume/ASWebGLue/blob/9499782e0d7b3b9f51bbe3c7238abf0838f51c71/src/WebGL.ts

Here is the file that tries to `import` stuff from `'aswebglue'` but it doesn't work:

> https://github.com/lume/glas/blob/8f56ae0bb0d5796d4202fbfab7a352e00bc44600/src/as/test.ts#L2
> ```js
> import {SHORT} from 'aswebglue'
> ```

# Steps to reproduce:

```sh
git clone git@github.com:lume/ASWebGLue.git
cd ASWebGLue
git checkout assemblyscript-issue-1679
cd src/examples/CubeNodejs
npm install
npm start
```

That will output the following error:

```
❯ npm start

> @ prestart /home/trusktr/src/battlelinegames+ASWebGLue/src/examples/CubeNodejs
> npm run build


> @ build /home/trusktr/src/battlelinegames+ASWebGLue/src/examples/CubeNodejs
> asc cube.ts -b cube.wasm

ERROR TS6054: File '~lib/aswebglue/src/WebGL.ts' not found.

 import {WebGLRenderingContext, WebGLShader, WebGLProgram} from 'aswebglue/src/WebGL'; // does not work
                                                                ~~~~~~~~~~~~~~~~~~~~~
 in cube.ts(2,64)

FAILURE 1 parse error(s)
```

**Comment by ZoeDreams** [comment]
I was able to reproduce the bug. I found a work around by explicitly declaring the relative path. Looks like its using the LIBRARY_PREFIX path regardless if its a defined as a USER when creating a new Source for use by the parser.ts.

work around:
```typescript
import {SHORT} from '../../node_modules/aswebglue/src/webgl'
```

**Comment by dcodeIO** [comment]
When I follow the reproduction steps, I get a version of `aswebglue` in `node_modules` that has `"ascMain": "webgl.ts",`. Could this be a dependency problem?

**Comment by trusktr** [comment]
The commit hashes to use are above in the OP links.

lume/glas repo: 8f56ae0bb0d5796d4202fbfab7a352e00bc44600

aswebglue: 9499782e0d7b3b9f51bbe3c7238abf0838f51c71

If you checkout line/glas to that hash, you can modify package.json to have the exact hash for the `aswebglue` dependency

**Comment by trusktr** [comment]
@dcodeIO simple reproduction:

```sh
git clone git@github.com:lume/ASWebGLue.git
cd ASWebGLue/src/examples/CubeNodejs
npm install
npm start
```

You will see this output:

```
❯ npm start

> @ prestart /home/trusktr/src/battlelinegames+ASWebGLue/src/examples/CubeNodejs
> npm run build


> @ build /home/trusktr/src/battlelinegames+ASWebGLue/src/examples/CubeNodejs
> asc cube.ts -b cube.wasm

ERROR TS6054: File '~lib/aswebglue/src/WebGL.ts' not found.

 import {WebGLRenderingContext, WebGLShader, WebGLProgram} from 'aswebglue/src/WebGL'; // does not work
                                                                ~~~~~~~~~~~~~~~~~~~~~
 in cube.ts(2,64)

FAILURE 1 parse error(s)
```

**Comment by trusktr** [comment]
Updated the previous comment, the reproduction is reproducible and won't change.

**Comment by torch2424** [comment]
Per @trusktr request, I was able to try to import using `import {myExport} from 'my-npm-lib/some-folder-in-the-lib/some-file'`, and it didn't work for me either in my project:

![Screenshot from 2021-02-26 12-58-34](https://user-images.githubusercontent.com/1448289/109354377-921cf000-7832-11eb-9935-d2e3f81f4391.png)
![Screenshot from 2021-02-26 12-57-31](https://user-images.githubusercontent.com/1448289/109354382-92b58680-7832-11eb-8bc7-3c2e674db295.png)

(Also, as a quick note, I don't require this behavior for my library, just wanted to help @trusktr reporduce, since they had asked :smile: :+1: )

**Comment by dcodeIO** [comment]
@trusktr For some reason the second repro also doesn't work on my machine. Can't install glfw-raub or something.

**Comment by trusktr** [comment]
@dcodeIO

Yeah, I tried all approaches. @torch2424 listed one approach (direct file post-fixed onto the library name). But it fails on more approaches:

```js
// ascMain in some-lib is "src/index.js" which re-exports from "./path/to/direct/foo.ts"

import {foo} from 'some-lib' // error
import {foo} from 'some-lib/src/path/to/direct/foo.ts' // error

// With this one I expect it to read `ascMain` from package.json in the `some-lib/` folder,
// but I wouldn't be surprised if this particular case hasn't been implemented yet, as
// people most likely won't be trying this unless they are working around the original issue.
import {foo} from '../../../node_modules/some-lib' // error

// This one works:
import {foo} from '../../../node_modules/some-lib/src/path/to/direct/foo.ts' // good
```

I didn't try to remove `src/`, but my guess is it won't work either.

I'm in Linux. Maybe `glfw-raub` has an issue on another OS or flavor of Linux.

Let me see about making a reproduction with only one dependency.

**Comment by ZoeDreams** [comment]
> @trusktr For some reason the second repro also doesn't work on my machine. Can't install glfw-raub or something.
> 
> Btw, did you try if it works if you remove the `/src/` from the import? I believe the root directory is `dir(ascMain)` essentially.

ruab doesnt work on my windows or linux machines either.

**Comment by JairusSW** [comment]
Got the same error... :(

**Comment by JairusSW** [comment]
Hey, @trusktr @torch2424 @ZoeDreams , it seems to be fixed!

**Comment by trusktr** [comment]
I just tried this on 0.19.5 and I get an error still:

```ts
import {...} from 'asdom/assembly/index'
```

```
> asc assembly/index.ts --target debug --exportRuntime --exportTable

ERROR TS6054: File '~lib/asdom/assembly/index.ts' not found.

 } from 'asdom/assembly/index'
        ~~~~~~~~~~~~~~~~~~~~~~
 in assembly/index.ts(9,8)

FAILURE 1 parse error(s)
```

**Comment by trusktr** [comment]
Reproduction:

```sh
git clone https://github.com/lume/asdom.git
cd asdom
npm i
cd example
npm i
npm run dev // ERROR
```

**Comment by trusktr** [comment]
This works, but TypeScript shows re squigglies and intellisense breaks because AssemblyScript projects are not set up to follow a default TypeScript node resolution lookup:

```js
import {...} from 'asdom' // red squigglies!
```

This doesn't work in AS, but it is proper, and TypeScript will see the correct import and you will get intellisense:

```js
import {...} from 'asdom/assembly/index' // Intellisense works, but not AS
```

**Comment by trusktr** [comment]
There's still an issue, so I continued in https://github.com/AssemblyScript/assemblyscript/issues/1954
