### ISSUE TITLE
Function table not generated when crossing the boundary

### ISSUE THREAD

**Issue by bkolobara** [AssemblyScript/assemblyscript#1689]
Hi, together with @jtenner I'm working on AssemblyScript support for [Lunatic](https://github.com/lunatic-solutions/lunatic).

Lunatic allows you to pass function table indexes to an imported function and then spawns a new "process" (green thread) using this function as the entry point.

I'm running now into an issue where AssemblyScript doesn't generate a table when passing a closure to an imported function.

The following example:
```ts
@external("env", "callback")
declare function callback(callback: () => void): void;

callback(() => { 42 });
```

doesn't generate a table. The import just gets passed a memory address with a value inside that can't be used from the runtime.

According to [the documentation](https://www.assemblyscript.org/exports-and-imports.html#on-values-crossing-the-boundary) it should be the index of the function.

**Comment by dcodeIO** [comment]
The documentation is actually outdated on this, in that the value passed to `callback` is a pointer to a first-class function nowadays. A first-class function is a structure in memory looking like [this](https://github.com/AssemblyScript/assemblyscript/blob/6fe4b288d31b9e08895e80e06c53c7cf426eda90/std/assembly/function.ts#L3):

| Offset | Type| Description
|--------|-------|-----
| 0         | u32   | Function index
| 4         | usize | Function environment pointer

So the function index is stored at the address in memory that is passed. One can load the index, and along the `--exportTable` compiler option, can then obtain the respective function from `exports.table`.

**Comment by bkolobara** [comment]
Thanks, this clarifies it!

Just for reference, I ended up passing a closure to the runtime doing this:
```ts
let closure = (): void => {
  Console.log("Hello thread!\r\n");
};
let table_index = load<u32>(<u32>changetype<usize>(closure));
let pid = spawn_with_context(table_index, 0, 0);
```

and using the `--exportTable` compiler option.
