### ISSUE TITLE
compileString does not output runnable code

### ISSUE THREAD

**Issue by domoritz** [AssemblyScript/assemblyscript#1697]
I am trying to compile AssmeblyScript on Observable but my compiled instance says `Cannot read property 'add' of undefined` and the code does not seem to have the `add` method. 

https://observablehq.com/d/7e3f207437d2a10c 

<img width="1061" alt="Screen Shot 2021-02-23 at 00 31 47" src="https://user-images.githubusercontent.com/589034/108783883-16196400-7523-11eb-8569-990c605e2846.png">

**Comment by dcodeIO** [comment]
> RuntimeError: abort(Assertion failed: curr, at: /home/runner/work/binaryen.js/binaryen.js/binaryen/src/wasm-traversal.h,89,visit). Build with -s ASSERTIONS=1 for more info.

This error makes me wonder, as it shouldn't typically happen, especially not on a simple input like an add function. Is it possible maybe that the Binaryen version is different from what the compiler wants? Asking because there have been some opcode renumberings lately that may yield this error when using a newer (or older) Binaryen version.

**Comment by domoritz** [comment]
Thanks for looking into this. I used the versions from https://cdn.jsdelivr.net/npm/assemblyscript@0.18.10/dist/sdk.js. My developer console shows that I am getting the right version.

**Comment by dcodeIO** [comment]
Hmm, to debug this further, I guess I'd need a crash course to ObservabaleHQ. Not quite sure what the site and the code snippets there are doing, unfortunately.

Fwiw, there is [some documentation](https://github.com/AssemblyScript/assemblyscript/tree/master/lib/sdk) on how to use the SDK with an AMD loader, which is what [the AS website does](https://github.com/AssemblyScript/website/blob/c8ad89632dccf528b456a7c4b00c58c75dc95783/src/.vuepress/public/editor.html#L377) to make it work.

**Comment by domoritz** [comment]
Observable is almost JS. Promises are automatically resolved and require is d3-require instead of require js. 

An older version of assemblyscript pre 0.18 worked fine: https://observablehq.com/compare/6d895cdfab0a8df1@422...6fa7dfa54e5f64e7@423

**Comment by dcodeIO** [comment]
Seeing two problems there. One is a typo in `binarygen` instead of `binaryen` and another is `instance.exports` instead of `instance.instance.exports` I think. Didn't get it to work, but fixing these gets rid of some of the errors.

**Comment by domoritz** [comment]
binarygen was the issue 🤦 

I copied the typo from https://observablehq.com/@stwind/hello-assemblyscript and sent them a suggestion to fix it.

Thank you!

**Comment by domoritz** [comment]
Now it all works: https://observablehq.com/@domoritz/hello-assemblyscript. Thank you!

Time to play with it in the browser 🎉

**Comment by AurelienRibon** [comment]
Also, you just need to require `dist/asc.js`, no need for the whole sdk.js just to compile strings.

**Comment by domoritz** [comment]
I wasn't able to get it working on Observable yet (https://observablehq.com/d/f8c784d3979a845a).

<img width="571" alt="Screen Shot 2021-02-23 at 14 12 26" src="https://user-images.githubusercontent.com/589034/108848334-b9a35c80-7595-11eb-9639-ba04851d9deb.png">

Let me know if you have ideas (e.g. following https://observablehq.com/@observablehq/how-to-require-stubborn-modules).

**Comment by AurelienRibon** [comment]
Yes, forget about it, it's the classic issue. All this is discussed in this PR. I want to be able to load asc.js real bad ^^ (or at least understand how to call the low-level functions from assemblyscript.js to compile a program without asc.js).
https://github.com/AssemblyScript/assemblyscript/pull/1687

**Comment by domoritz** [comment]
Thanks for the link. I subscribed to the discussion.
