### ISSUE TITLE
Is there any API can build `as` source code from AST ?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1698]
The AST seems have not any method build source text if user want to transform the code. For example code format tool needs such API. 

Should such API included in as compiler ?

**Comment by AurelienRibon** [comment]
Of course there is :)
Look for class `ASTBuilder` in `ast.ts`. It is exported in the main bundle `assemblyscript/dist/assemblyscript.js` too.
Just pass it a Node instance and it outputs a textual version of the AST, starting from the node you give it.
Source to source transformations are very easy. Just keep in mind that there is no sourceMap generation, so runtime errors may look funky.

**Comment by AurelienRibon** [comment]
```js
const as = require('assemblyscript/dist/assemblyscript');

const options = as.newOptions();
const program = as.newProgram(options);

const code = '<f64>a';

program.parser.parseFile(code, 'script.ts', true);
const ast = program.sources[0];

const result = as.ASTBuilder.build(ast);
```

**Comment by yjhmelody** [comment]
> Of course there is :)
> Look for class `ASTBuilder` in `ast.ts`. It is exported in the main bundle `assemblyscript/dist/assemblyscript.js` too.
> Just pass it a Node instance and it outputs a textual version of the AST, starting from the node you give it.
> Source to source transformations are very easy. Just keep in mind that there is no sourceMap generation, so runtime errors may look funky.

It looks good, but unfortunately it seems that it cannot be configured

**Comment by AurelienRibon** [comment]
It's not `escodegen` equivalent yet, and is mainly useful for debugging. Still, its code is also super easy, so writing your own if you need should be no trouble. Write a big switch-case with all AST cases, and recursively generate a string by traversing those nodes. There are 63 `NodeKind` possibilities.
