### ISSUE TITLE
Implement standard Set and Map

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#17]
Besides a filler implementation of sets, there's not much implemented in this regard yet.

See: [std/assembly/set.ts](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/set.ts)
See: [std/assembly/map.ts](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/map.ts)

Useful resources:

* [Set - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)
* [Map - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
* [ECMAScript® 2018 Language Specification](https://tc39.github.io/ecma262/)

**Comment by enjoythelive1** [comment]
I want to implement this. I have the time (kinda).

**Comment by alperr** [comment]
is there anyone actively working on this ?

**Comment by dcodeIO** [comment]
> is there anyone actively working on this ?

Not that I am aware of :)

**Comment by MaxGraey** [comment]
I don't think so anyone working on this. It will be great implent this via [Determenistic Hash Table](https://github.com/jorendorff/dht)

**Comment by dcodeIO** [comment]
Anyone already working on this? Seems like an open or close table from the link provided by MaxGraey shouldn't be too hard to implement. Might give it a shot otherwise.

**Comment by MaxGraey** [comment]
What about me, I focused on reimplementing argument reduction for sin/cos/tan.
Close table looks very promising and it seems using by Mozilla's Map/Set with some modifications.

**Comment by dcodeIO** [comment]
The commit above adds a variant of the previously mentioned CloseTable implementation to tests, so feel free to give it a try. Once stable, it should be straight forward to derive a Set implementation from it, and start thinking about iterators.
