### ISSUE TITLE
Expose compiler version as magic global

### ISSUE THREAD

**Issue by surma** [AssemblyScript/assemblyscript#1708]
In the [spirit] of `ASC_TARGET`, `ASC_FEATURE_SIMD` et al, what do you think about exposing `ASC_VERSION_MAJOR` `ASC_VERSION_MINOR` and `ASC_VERSION_PATCH`?

**Comment by dcodeIO** [comment]
Implemented in https://github.com/AssemblyScript/assemblyscript/pull/1765 :)
