### ISSUE TITLE
Math.sign operation returns a float value despite being generic

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#1709]
In [this example](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKZXhwb3J0IGZ1bmN0aW9uIHRlc3QobjogaTMyKTogaTMyIHsKICByZXR1cm4gTWF0aC5zaWduKG4pOwp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGB0ZXN0KCR7aX0pID0gJHtleHBvcnRzLnRlc3QoaSl9XG5gCiAgICB9CiAgfSkKPC9zY3JpcHQ+) I'd expect that the generic `Math.sign` function returns an `i32` value and that it would compile without errors:

~~~
export function test(n: i32): i32 {
  return Math.sign(n);
}
~~~

However, the compiler reports:

~~~
; ERROR AS200: Conversion from type 'f64' to 'i32' requires an explicit cast.
;; 
;;    return Math.sign(n);
;;           ~~~~~~~~~~~~
;;  in module.ts(2,10)
~~~

**Comment by MaxGraey** [comment]
`Math` and `Mathf` is not generic currently and accept only `f64` and `f32` respectively. But I plan on making all Math methods polymorphic in the future.

If you need integer `sign` you could use this approach:
```ts
export function sign(x: i32): i32 {
  return i32(x > 0) - i32(x < 0);
}
```

**Comment by ColinEberhardt** [comment]
Ah, ok - might be worth updating the docs as these indicate a generic function https://github.com/AssemblyScript/website/blob/master/src/stdlib/math.md
