### ISSUE TITLE
No --watch mode for the CLI

### ISSUE THREAD

**Issue by JerryGreen** [AssemblyScript/assemblyscript#1713]
`tsc` has cool feature watching files, so it will automatically recompile when input file change:

```txt
 -w, --watch                                        Watch input files.
```

It would be cool if `asc` would have that too.

**Comment by willemneal** [comment]
I think that this should be handled by something like [asbuild](https://github.com/AssemblyScript/asbuild).  But I agree this would be a useful feature.

**Comment by ZoeDreams** [comment]
try using this. https://www.npmjs.com/package/nodemon.

**Comment by JerryGreen** [comment]
@ZoeDreams yup, thank you for reminding there's such a cool project! I made it work with further config:

```json
{
  "$schema": "https://github.com/SchemaStore/schemastore/raw/master/src/schemas/json/nodemon.json",
  "exec": "asc",
  "watch": ["./src/**/*.as.ts"],
  "ext": ".as.ts"
}
```

That's unfortunate though I can't list wildcard paths in `asconfig.json` to, and I have to list each file manually currently: https://github.com/AssemblyScript/assemblyscript/issues/1712
