### ISSUE TITLE
Getting error while exporting a class: Module not found: Can't resolve 'env'

### ISSUE THREAD

**Issue by JerryGreen** [AssemblyScript/assemblyscript#1721]
When I'm using this simple AssemblyScript:

```ts
const test = 123

export { test }
```

All works fine and cool and I can extract my data from WASM module:

![image](https://user-images.githubusercontent.com/13215662/110326081-fd886e00-8039-11eb-8c7c-b504fc9d10d1.png)

But when I'm trying to export a class:

```ts
class World {}

export { World }
```

I'm now getting this error:

```
Failed to parse source map: TypeError: Cannot read property 'start' of undefined
    at getNotFoundError (C:\Users\Jerry\projects\project-x\node_modules\next\dist\build\webpack\plugins\wellknown-errors-plugin\parseNotFoundError.js:1:810)
...
error - ./src/asm/dist/optimized.wasm
Module not found: Can't resolve 'env' in 'C:\Users\Jerry\projects\project-x\src\asm\dist'
```

It says it failed to parse source map, I tried using both settings `"sourceMap": true` and `"sourceMap": false` in my `asconfig.json`, but neither fixes the error.

I have current's latest version: `"assemblyscript": "0.18.13"`

Can someone tell what might be wrong and how do I debug this? I'm still quite new to AssemblyScript and WebAssembly, trying to get it all going so I can use it for some real-world tasks and projects.

**Comment by MaxGraey** [comment]
Could you repeat this on playground?

I cant' reproduce [any errors](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWImZXhwb3J0UnVudGltZQpjbGFzcyBXb3JsZCB7CiAgdGVzdEZpZWxkOiBpMzIgPSAyCn0KCmV4cG9ydCB7IFdvcmxkIH0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKTsKCiAgICBjb25zdCB0ZXN0RmllbGQgPSBleHBvcnRzLldvcmxkLndyYXAobmV3IGV4cG9ydHMuV29ybGQoKSkudGVzdEZpZWxkOwogICAgb3V0cHV0LnZhbHVlICs9IGBXb3JsZCN0ZXN0RmllbGQgPSAke3Rlc3RGaWVsZH1cbmA7CiAgfSkKPC9zY3JpcHQ+)

**Comment by dcodeIO** [comment]
Since the error includes `env`, my guess is that it is caused by an unimplemented `env.abort` import. See also: [Anatomy of a module](https://www.assemblyscript.org/exports-and-imports.html#anatomy-of-a-module).

**Comment by MaxGraey** [comment]
Also note exporting / importing classes, strings and other references required `loader` and `--exportRuntime` flag for `asc`

**Comment by JerryGreen** [comment]
Uh, I forgot to mention I haven't used this loader, and I'm trying to use Node built-in `.wasm` support. It works for simple cases (like numbers, etc) but doesn't work for classes by some reason. I made kind of a minimal reproducible repo, though I turned out it to show different error than in I posted in this issue, but it has exact same problem (classes don't work):

https://gist.github.com/JerryGreen/b1fbca9092c0802fa734aa906d74ce6e

To run all that in quick manner:

```bash
git clone https://gist.github.com/JerryGreen/b1fbca9092c0802fa734aa906d74ce6e test-as-class
cd test-as-class
yarn
yarn test:number
yarn test:class
```

**Comment by MaxGraey** [comment]
So you try to use `--experimental-wasm-modules` and native `import('module.wasm')`. AssemblyScript required `{ env: { abort() {} }}` for imports. So you need to figure outing how to pass `env` object in this case. Or don't use `experimental-wasm-modules`

**Comment by MaxGraey** [comment]
According to docs it seems you need create `env.mjs` file which should contain:
```js
export function abort(_msg, _file, line, column) {
  console.error("abort called at main.ts:" + line + ":" + column);
}
```
and 
```ts
import { World } from './dist/asm.wasm';
```

But note. `World` will be just a number (pointer) in this case and you need something like this: https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/index.js#L350
to wrap it to real js class

**Comment by JerryGreen** [comment]
> Acording to docs it seems you need create env.mjs file which should contain:

I tried adding this `env.mjs` file but this didn't change anything. Still getting:

```txt
UnhandledPromiseRejectionWarning: SyntaxError: Identifier '$World' has already been declared
    at createDynamicModule (internal/modules/esm/create_dynamic_module.js:39:13)
```

> But note. World will be just a number (pointer) in this case and you need ...

Oh, I actually think right now that maybe I can just forget about classes and this problem, and just use pure functions. It doesn't worth fixing :\ Pure functions still good, and they work
