### ISSUE TITLE
Can I use `import` statement in AssemblyScript?

### ISSUE THREAD

**Issue by JerryGreen** [AssemblyScript/assemblyscript#1723]
I just read "Exports and [Imports](https://www.assemblyscript.org/exports-and-imports.html#imports)" doc section but it's not clear what imports I may use. Particularly interesting sub-questions:

- Can I import other AssemblyScript? `.ts` / `.as` / `.as.ts`
- Can I import WASM module? `.wasm`
- Can I import TypeScript? `.ts`
- Can I import js packages? `import cowsay from 'cowsay'`
- I've seen mention of `import "wasi"`, - can I import that? Does it require anything else installed?

**Comment by willemneal** [comment]
- Yes! The compiler front end uses node resolution to find your import (e.g. `node_moudles/a/assembly/index.ts` will equate to `import ... "a"`, also can have `ascMain: ./path/to/entry`.). For `.as` or other extensions you need to pass a CLI argument.
- No, but with Interface Types this could become a thing
- Not in the general case, though your TS could be AS compliant.
- No.
- Importing a file like `import "wasi"` has the effect of loading in the file and adding any of definitions that were global.  In this case it adds the declared WASI functions that you can use which are provided by the host when running a WASI binary.
