### ISSUE TITLE
Default function arguments lead to `unreachable` runtime error

### ISSUE THREAD

**Issue by JerryGreen** [AssemblyScript/assemblyscript#1724]
I have this code

```ts
export function generateWorld(seed: i32, size: i32, level: i32 = 0): i32 {
  return 123
}
```

It perfectly compiles, but later when I execute the function like so:

```ts
async () => {
  const wasm = await import('./dist/optimized.wasm')
  const res = wasm.generateWorld(0, 0, 0)
  console.log({ res })
})()
```

I'm getting this error:

```js
RuntimeError {
  message: 'unreachable',
}
```

If I remove default value:

```ts
export function generateWorld(seed: i32, size: i32, level: i32): i32 {
  return 123
}
```

Then it outputs my 123:

```js
{ res: 123 }
```

Aren't default argument supported?

**Comment by MaxGraey** [comment]
default args not support by WebAssembly as is and required trampoline which need properly handled. Please use [AssemblyScript loader](https://www.assemblyscript.org/loader.html#installation) for that. loader also handle many other things

**Comment by dcodeIO** [comment]
The loader uses the `exports.__setArgumentsLength` helper under the hood to inform the call on the Wasm side of the number of actual arguments provided. Without the loader, one can also call the helper manually, like so:

```js
exports.__setArgumentsLength(0);
exports.generateWorld();
```

The called function on the Wasm side will then insert default values according to the given number of arguments.

**Comment by JerryGreen** [comment]
Huh, it seems this loader has like _a lot_ of logic
I don't really like it honestly

**Comment by dcodeIO** [comment]
Yeah, hopes are that we can get rid of it eventually, once Wasm supports what we need it for out of the box.
