### ISSUE TITLE
No support for closures in lambdas ?

### ISSUE THREAD

**Issue by feedthejim** [AssemblyScript/assemblyscript#173]
Hi,

I'm trying to understand AssemblyScript by doing a little project. Is there no closure on lambdas ? 

`  trace(rayOrigin: Vector3, rayDirection: Vector3, depth: f64): Vector3 {
    let tnear: f64 = Infinity;
    let sphere: Sphere | null = null;

    this.elements.forEach(
      (sphere: Sphere): void => {
        let hitInfo: Intersection | null = sphere.intersect(
          rayOrigin,
          rayDirection,
        );
`
This bit of code doesn't compile, it throws this error. 

`ERROR TS2304: Cannot find name 'rayOrigin'.

           rayOrigin,
           ~~~~~~~~~
 in assembly/RayTracer.ts(16,1`

Do i need to pass them as parameters to the lambda ?

**Comment by MaxGraey** [comment]
Hi,
Inferring for closures has some limits for now, so if you want using functional methods your should declare full signature for closure like:
```ts
this.elements.forEach((sphere: Sphere, index: i32, array: Array<Element>): void => {
   ...
});
```

**Comment by dcodeIO** [comment]
> And I'm not sure about rayOrigin which should capture from lexical environment.

Can't capture yet. Reason is that closures like these usually need GC-support to attach an outer scope to the function being called, so if the inner function changes a value, the outer function sees the change as well. This is especially important for functions being assigned to values that can be called at any time, i.e. when the parent function already finished executing.

To work around this for now you could use a global variable that you assign the value to first, read the value from there in the inner function, and maybe set the updated value back in the parent function afterwards.

**Comment by MaxGraey** [comment]
@dcodeIO Thanks!
I think better workaround for this current case switch from functional `forEach` to `for (...) {}`.

**Comment by dcodeIO** [comment]
> I think better workaround for this current case switch from functional forEach to for (...) {}.

This makes me think. One optimization we could theoretically do is to compile the `forEach` and its argument inline, allowing the inner function to access the parent scope. Would also eliminate the indirect call. Not sure how complicated that'd be, and it won't work in every case, but in this one here it should.
