### ISSUE TITLE
the loader’s `__newArray()` doesn’t work with type ID 0 (i.e. ArrayBuffer)

### ISSUE THREAD

**Issue by surma** [AssemblyScript/assemblyscript#1730]
`getArrayInfo` fails with `Error: not an array: 0, flags=32`.

I feel like this should work?

**Comment by dcodeIO** [comment]
Type id `0` is more like an untyped buffer currently, not making assumptions about structure, including its element type. Only the typed array views, which work with `getArrayInfo`, give the data meaning. Does that make sense?

**Comment by surma** [comment]
> Type id 0 is more like an untyped buffer currently, not making assumptions about structure, including its element type

Sounds pretty much like an `ArrayBuffer` to me :D I expected it to just be a “chunk of memory” (somewhat equivalent to `Uint8Array`). I worked around it for now, but wondering if it’s worth patching into the loader itself

**Comment by dcodeIO** [comment]
Hmm, is there a particular reason why `__new(0, SIZE)` cannot be used to create ABs? That's what the compiler and loader currently do.

**Comment by dcodeIO** [comment]
For a bit of background maybe, one reason for not treating ABs like arrays is that `Map`s and `Set`s for example have ABs as non-array backing storage. These are more like buffers of a C-like sequence of structs, whereas a proper array would be a sequence of basic values or pointers. So ABs can be used for quite everything, so I tend to treat them like that. I am mostly looking at internals here of course that may not be super relevant when it comes to improving general usability. Hmm...

**Comment by surma** [comment]
`__new(0, size)` totally works, that is my current workaround, but looking at the loader docs I _expected_ `__newArray(0, [...])` to work as well. So maybe it’s just worth explicitly mentioning :D

**Comment by surma** [comment]
For context from my end: I am running into this because WebGL’s [`gl.bufferData()`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bufferData) accepts an `ArrayBuffer` (but also an `ArrayBufferView`). Since you often mix floats and integers in WebGL, I usually create a raw `ArrayBuffer` and fill it using `DataView`. I am now encountering that scenario from within AssemblyScript and I’m looking to pass an `ArrayBuffer` to an imported `gl.bufferData()` call (with `as-bind` in the middle).

**Comment by dcodeIO** [comment]
I see, yeah, so there is value in being able to handle both ABs and TAs with a common API. Would it be sufficient if ABs would be conveniently treated like arrays of `u8`s externally, or would there be a need to use other element types as well?

**Comment by surma** [comment]
I’d only ever expect ArrayBuffers to be treated as a “sequence of bytes”, which `u8` seems to embody perfectly :)
