### ISSUE TITLE
Feature Request: numeric separators

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#1736]
as per: https://github.com/tc39/proposal-numeric-separator

i.e. allow numeric literals of the form `1_000_000`. Should be a 'good first issue' for someone.

**Comment by MaxGraey** [comment]
AssemblySAcript should already support numeric separators for integers and floats =)

**Comment by ColinEberhardt** [comment]
My bad - must have been a different issues that cause compilation errors
