### ISSUE TITLE
Object literals with default values result in TS errors

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#1737]
The following is valid AS:

```
class DateLike {
  year: i32 = -1;
  month: i32 = -1;
  day: i32 = -1;
}

const foo: DateLike = { year: 2019 };
```

However, this results in a TypeScript error:

```
"Argument of type '{ year: number; }' is not assignable to parameter of type 'DateLike'
Type '{ year: number; }' is missing the following properties from type 'DateLike': month, day"
```

I can suppress with `@ts-ignore`, but that is not ideal

**Comment by willemneal** [comment]
I don't see a way around this from a TS perspective.  It just sees casting an incomplete object literal.  Perhaps a static `fromYear`?

`const foo = DateLike.fromYear(2019);`

I know this isn't what you you were asking for, but personally I think that object literals can be confusing.  Like in this example, there is an implied constructor that adds fields to the literal.
