### ISSUE TITLE
Null as a type

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1744]
The following example is valid TS:

```ts

function getNull(): null {
  return null;
}

export function isNullNull(): boolean {
  return getNull() == null
}

```
[See example here](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKLyoqIENhbGN1bGF0ZXMgdGhlIG4tdGggRmlib25hY2NpIG51bWJlci4gKi8KCmZ1bmN0aW9uIGdldE51bGwoKTogbnVsbCB7CiAgcmV0dXJuIG51bGw7Cn0KCmV4cG9ydCBmdW5jdGlvbiBpc051bGxOdWxsKCk6IGJvb2xlYW4gewogIHJldHVybiBnZXROdWxsKCkgPT0gbnVsbAp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==)

And gets the following compiler error:

```ts
ERROR TS2304: Cannot find name 'null'.
 
  function getNull(): null {
                      ~~~~
  in module.ts(3,21)
 
 WARNING AS226: Expression resolves to unusual type 'usize'.
 
    return getNull() == null
                        ~~~~
  in module.ts(8,23)
```

**Comment by dcodeIO** [comment]
Thinking about this a bit, a `null` type seems challenging because it could either be an internal reference that is `<usize>0` or an external references that is `ref.null`, but then we are missing the necessary information to decide which one it is. A nullable type like `Something | null` has this information within `Something`.

**Comment by yjhmelody** [comment]
But null should be a type T | null when comparing to type T | null. 

Now type inference cannot achieve this, nor does it narrow the type T |null to T when t != null
