### ISSUE TITLE
Cannot find module 'assemblyscript/cli/asc'

### ISSUE THREAD

**Issue by bitmage** [AssemblyScript/assemblyscript#1747]
Fresh install of Node v14.16.0 NPM 6.14.11.

Following guide [here](https://www.sitepen.com/blog/getting-started-with-assemblyscript), I ran:

```
npm install --save-dev AssemblyScript/assemblyscript
npx asinit .
npm run asbuild
```

And I get:

```
Cannot find module 'assemblyscript/cli/asc'
Require stack:
- /home/bitmage/.npm/_npx/39126/lib/node_modules/asbuild/dist/cli.js
- /home/bitmage/.npm/_npx/39126/lib/node_modules/asbuild/dist/main.js
- /home/bitmage/.npm/_npx/39126/lib/node_modules/asbuild/bin/asb
```

The files in the require stack seem to be temporary.  They aren't there when I try to read them.

**Comment by willemneal** [comment]
Are you sure you didn't do `npx asbuild` because it looks like it's trying to call `asbuild`, but not finding `assemblyscript` since it's not installed globally.  Also any reason not to install via npm instead of github, e.g. `npm install --save-dev assemblyscript`?
