### ISSUE TITLE
Dynamic property access

### ISSUE THREAD

**Issue by CrimsonCodes0** [AssemblyScript/assemblyscript#1752]
JavaScript allows accessing arbitrary objects via arbitrary strings or symbols in the property access operator (`[]`), TypeScript improves upon this by allowing subsets of arbitrary strings/symbols, by, for example, allowing only accessing via an enum of strings which are known to map to properties of the object.

Example TS:
```ts
class Point {
  x: number;
  y: number;
};

type Key = 'x' | 'y';

function lookupFromObject(target: Point, key: Key): number {
    return target[key];
}
```

Here's an example of currently invalid AS, that could potentially be compiled, should this be implemented: [link](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmNsYXNzIFBvaW50IHsNCiAgeDogZjY0Ow0KICB5OiBmNjQ7DQp9Ow0KDQp0eXBlIEtleSA9ICd4JyB8ICd5JzsNCg0KZXhwb3J0IGZ1bmN0aW9uIG1ha2VLZXkoDQogIGNvbmRpdGlvbjogYm9vbGVhbg0KKTogS2V5IHsNCiAgcmV0dXJuIGNvbmRpdGlvbg0KICAgID8gJ3gnDQogICAgOiAneSc7DQp9DQoNCmV4cG9ydCBmdW5jdGlvbiBhY2Nlc3NGcm9tS2V5KA0KICAgIHRhcmdldDogUG9pbnQsDQogICAga2V5OiBLZXkNCiAgKTogZjY0IHsNCiAgcmV0dXJuIHRhcmdldFtrZXldOw0KfQ0KDQpleHBvcnQgZnVuY3Rpb24gbWFpbigpOiB2b2lkIHsNCiAgY29uc3QgdGFyZ2V0OiBQb2ludCA9IHsNCiAgICB4OiAxLjAsDQogICAgeTogMi4wDQogIH07DQoNCiAgY29uc3Qga2V5OiBLZXkgPSBtYWtlS2V5KGZhbHNlKTsNCg0KICBjb25zdCB2YWx1ZTogZjY0ID0gdGFyZ2V0W2tleV07DQp9CiMhaHRtbAo=).

There was a previous issue by someone else on the Repo about allowing arbitrary string accessors (`[key: string]: T`), but this is more scoped to properies that are known to exist on an object.

While one *could* argue that this wouldn't be able to be compiled efficiently, if contraints similar to those in C++ were applied to what keys could be accessed, then type safety could be ensured at compile time, with less overhead. I recommend restricting a variable to contain keys that would return the same value if accessed on the object, in this case, `x` and `y` both yield an f64 upon accessing an object of type `Point`.

Equivalent C++:
```c++
struct Point {
  double x;
  double y;
};

using Key = double (Point::*);

auto lookup_from_object(
    Point const& target,
    Key key
) -> double {
    return target.*key;
}
```

**Comment by dcodeIO** [comment]
How is `lookup_from_object` invoked, and how does C++ compile this if `key` can be any (dynamic) string? My C++ foo isn't the best, unfortunately.

**Comment by CrimsonCodes0** [comment]
Example call-site:
```c++
auto const graph_roots = Point {
    .x = 1,
    .y = 0
};

Key const dimension = &Point::x;

double const _ = lookup_from_object(
    graph_roots,
    dimension
);
```
They aren't 100% dynamic keys, they are associated with the class that are are used to access, but they can be passed around at runtime.

Arbitrary strings would be bad, we can both agree that we should leave that to Map.

C++ can compile it because the following are laid out in memory the same:
```c++
using Point = double[2];
// vs
struct Point {
    double x, y;
};
```

Because of that, we can see x and y as 0 and 1 respectively, and treat it like memory access with an offset.
```c++
double array[2] = { 1, 0 };
constexpr size_t x = 0, y = 1;
array[x];
```
And there we go, dynamic property access!

If only it were so easy, AssemblyScript is in a bit of a different situation, being based off of TypeScript, it would be much harder to add C++-like key signatures.

I'd suggest implementing key access as something more like a hashmap, with the keys being hashed at compile-time, and denying all key access to keys that exist on the object.

My question is, how would one handle code like this:
```ts
class T {
    x: i32,
    y: i64
}

const obj: T = { ... };

let key: "x" | "y" = ...;

obj[key]; // What is this return type, how do you compile that?
```

**Comment by CrimsonCodes0** [comment]
Could a minimal subset of this idea be implemented as an MVP? It would definitely bring AS much closer to TS/JS, and support would definately help allow porting more code to AS/Wasm.
Even runtime exceptions for key mismatches would be better than lacking support entirely.

**Comment by dcodeIO** [comment]
> I'd suggest implementing key access as something more like a hashmap, with the keys being hashed at compile-time, and denying all key access to keys that exist on the object.
> 
> Of course, the performance wouldn't be as optimal as raw C pointer arithmetic and memory access, but JS developers should be used to dynamic access being (slightly) slower.

My expectation there would be that it is not just slightly slower, but significantly slower, as in a single memory load instruction vs a hash map lookup - and that on each access. The benefits from declaring the object statically are pretty significant, so I'd always recommend it. Perhaps this [philosophy paragraph](https://www.assemblyscript.org/status.html#philosophy) can shed some light on why that's currently not necessarily in scope.

**Comment by CrimsonCodes0** [comment]
> > I'd suggest implementing key access as something more like a hashmap, with the keys being hashed at compile-time, and denying all key access to keys that exist on the object.
> > Of course, the performance wouldn't be as optimal as raw C pointer arithmetic and memory access, but JS developers should be used to dynamic access being (slightly) slower.
> 
> My expectation there would be that it is not just slightly slower, but significantly slower, as in a single memory load instruction vs a hash map lookup - and that on each access. The benefits from declaring the object statically are pretty significant, so I'd always recommend it. Perhaps this [philosophy paragraph](https://www.assemblyscript.org/status.html#philosophy) can shed some light on why that's currently not necessarily in scope.

Okay, let's assume that this really does end up having worse performance and thatnit takes a few more CPU cycles than a plain memory load. Even if it reduces performance, it would only reduce performance when using *dynamic* keys, not static access.
```as
obj.x; // fast; old code is unaffected
obj['x']; // fast; constant key
obj[x]; // slow; runs though dynamic mapping to get memory offset
```
People can still get fast code, so it should be okay anyways. But, we're assuming that it's slow to begin with, which may not even be true.

Next, it is expected that an optimizing compiler should be able to cache multiple, local, dynamic lookups:
```as
declare foo: Point;
declare bar: Point;

foo[key] = 0;
bar[key] = 0;
```
this should look through a hashmap only **once** to calculate a memory offwet usable for both objects, as they are of the same type. For the same object it should cache a pointer to the exact memory location! And of course, there are plenty more optimizations that could be done, ensuring that code remains performant.

**Comment by jtenner** [comment]
I've had to get around issues like these using transforms. These transforms mitigate speed issues usually and provide a loopless way of iterating over the keys of an object.
