### ISSUE TITLE
Should the corresponding packing type be provided for the basic type ?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1766]
When I use `T | null`, primitive type cannot be passed to.  In js, number has its packing type `Number` which is object.  Is assemblyscript planning to provide the corresponding type ?

**Comment by dcodeIO** [comment]
I am not aware of any immediate plans. For the time being, it is possible to work around this limitation with a `Box<T>` class:

```ts
class Box<T> {
  constructor(public value: T) {}
}

function myFunction(value: Box<i32> | null): void { ... }
```

This is about what the compiler would do to support it, but this way around the cost involved (allocation + indirection) is more obvious.

**Comment by yjhmelody** [comment]
I feel strange that if T is not null by default, why primitive type such as u32 cannot be generic in such situations?

**Comment by yjhmelody** [comment]
we need unwrap box if we want to do something with the value.  Maybe need a special built-in `Box<T>` type that can be converted to T automaticly when use T. Yeah, It's auto unpacking or auto deref.
