### ISSUE TITLE
Support object literal anonymous class to implement declaration and parameter interface

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1769]
Now, `as` cannot use object literal to do something. The feature is so import that make `as` more like `ts` rather than old `java`.
```ts
export interface Bar {
    readonly bar: string;
}

let bar: Bar = {
    bar: "bar",
};
```
The above code will be an error.

**Comment by ColinEberhardt** [comment]
Object literals are valid, if defined as a class without a constructor:

~~~
class Bar {
    bar: string;
}

let bar: Bar = {
    bar: "bar",
};
~~~

I think this is such an important feature that it should be included in the AS documentation, I can't recall seeing a section that covers this?

**Comment by yjhmelody** [comment]
> Object literals are valid, if defined as a class without a constructor:
> 
> ```
> class Bar {
>     bar: string;
> }
> 
> let bar: Bar = {
>     bar: "bar",
> };
> ```
> 
> I think this is such an important feature that it should be included in the AS documentation, I can't recall seeing a section that covers this?

Oh, you're right. If someone need an interface as a config, supporting Object literals for interface is also important IMO.
