### ISSUE TITLE
Exported generic function or class has no concrete instances

### ISSUE THREAD

**Issue by JerryGreen** [AssemblyScript/assemblyscript#1770]
I have further code:

```as.ts Entity
export type Component = Map<string, String>

export default class Entity<C extends Component = Component> {
  id: string
  components: Array<string>
  props: C
  constructor(public prop: string) {
    this.id = ''
  }
}
```

Which gives me the following warning, "AS232: Exported generic function or class has no concrete instances":

![image](https://user-images.githubusercontent.com/13215662/112958881-53919280-915c-11eb-8d8f-15cf7868cabb.png)

But why it's a warning? Can't I export a class? Should I only export class instances in AssemblyScript? (That would be unfortunate)

**Comment by MaxGraey** [comment]
It's warning because if you export non-concreate class to host it will be invalid but if you have plan to use this code as AS library it will be ok and you could ignore this warning. AS hasn't kind for code like execution module / library module / that's why it produce warning.

**Comment by JerryGreen** [comment]
Wait, you mean I can only use it from another AssemblyScript module? But if I import it from JavaScript with [Loader](https://www.assemblyscript.org/loader.html), it won't work???

Btw, once I know about the warning, how do I suppress it? Is there some `// @as-ignore` or something? I don't want it to pollute my output when compiling, - that is breaking focus

**Comment by MaxGraey** [comment]
> Wait, you mean I can only use it from another AssemblyScript module? But if I import it from JavaScript with Loader, it won't work???

If it's **generic class** it will not work properly because it's not concrete class. But if you export ordinal class like:
```ts
export default class EntityComponent {
  id: string
  components: Array<string>
  props: C
  constructor(public prop: string) {
    this.id = ''
  }
}
```
it will work properly

**Comment by JerryGreen** [comment]
Oh, generics, indeed! That all is making sense, since of course I can't pass some types from TypeScript into AssemblyScript/WASM.

But another questions is still there: how do I suppress the warning? Since I actually want to use generic classes only from within another AssemblyScript modules, not from JS/TS, so I actually want to export generic class, but I don't wanna see this warning

**Comment by MaxGraey** [comment]
I guess you cannot be able suppress such warnings. But @dcodeIO may be know more

**Comment by dcodeIO** [comment]
I'd probably use two distinct entry files, where the one used when compiling the package standalone does not have exports that don't do anything useful in this case. That second one could look like

```ts
// index-standalone.ts
export { SomethingActuallyUseful } from "./index"; // except Entity<T>
```

**Comment by JerryGreen** [comment]
@dcodeIO I'm trying to implement ECS pattern in AssemblyScript so I can build some game logic in AssemblyScript (and then later render it on a canvas in JS/TS), so I need a few base classes that I'll be extending from.

I wrote an article about implementing ECS in TypeScript here:

https://jerrygreen.me/blog/making-custom-game-engine

And actually wanted to make a step further, and make same exact thing but now in AssemblyScript (except the rendering part ofc), and see how it would affect the performance. I expected it to be even better than I already did, and be able to run it all with x6 throttled CPU without any frame drops, and from that point continue developing some real-world thing since I have a good base

So I kinda wanted to make some structure like this:

```bash
./src/asm/engine/Entity.as
./src/asm/engine/System.as
./src/asm/engine/World.as
./src/asm/systems/MovableSystem.as # which extends from base Entity.as
./src/asm/entities/Rat.as # which extends from base Entity.as
# etc etc
```

**Comment by dcodeIO** [comment]
It should be possible to use any structure. The warning is only displayed however when compiling your library, if I understand correctly, as a standalone program, since `Entity<T>` would become a module-level Wasm export, which won't do anything useful. So, if there were an extra entry file for the standalone build (I guess that's only used in testing anyhow?), then that'd be separate while not affecting the intended use case of being a library.

**Comment by JerryGreen** [comment]
Oh, you mean it's simply unused that is why! Sorry. AssemblyScript compiler seems to be more smart than I thought.

Once I added another file where I import this generic class, the warning disappeared. Thanks!
