### ISSUE TITLE
Any good idea or example to do unit tests for `transform` code ?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1771]
I cannot find a good way to let Transform subclass to run normally just like  `transform` hook.

**Comment by yjhmelody** [comment]
I find a way to do this. I define a test class extends the orignal and support a program as arg to its constructor. And then I pass `newProgram(newOptions())` to it.

**Comment by dcodeIO** [comment]
Could you explain what you are trying to accomplish in a bit more detail? :)

**Comment by yjhmelody** [comment]
I want to implement a `transform` which refactor AST according @decorator. So I need to check new code after refactoring.

**Comment by dcodeIO** [comment]
Doesn't modifying the AST during `afterParse`, so the changes become compiled later down in the pipeline, work?

**Comment by yjhmelody** [comment]
I do want to let the new AST to be compiled after parsing.

**Comment by yjhmelody** [comment]
I wrote some conversions to perform AST conversion to derive some functions. The generated AST can be converted to text and can be compiled normally, but only one AST can be directly compiled by the compiler, and other ASTs will generate an error `Whoops, the AssemblyScript compiler has crashed during compile :-(`

**Comment by yjhmelody** [comment]
I suddenly realized that `range` is a very important field because there is a Source under it. I did not fill in the range field of the old AST for all new ASTs. As a result, the assert often fails.
