### ISSUE TITLE
Unable to use "this" in functions

### ISSUE THREAD

**Issue by JerryGreen** [AssemblyScript/assemblyscript#1772]
I was unable to export classes: https://github.com/AssemblyScript/assemblyscript/issues/1770, so I wanted to emulate a class via function, but stuck into AssemblyScript not knowing what's "this". Here's a simple example:

```as.ts Entity
export type Component = Map<string, String>

interface EntityInstance {
  id: string
  props: Component
}

export default function Entity(
  this: EntityInstance,
  component: Component
): void {
  this.id = ''
  this.props = component
}
```

Here's TypeScript playground showing no error is emitted, i.e. it can parse the types from `this: EntityInstance`, i.e. it's valid JS/TS:

[typescriptlang.org/play](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDCEC2kB2wfwC8cAsgIZgA8AzjFAJY4DmANHAMp2NMB8AUH0YxgUAGZkAxqgCiBekgCSOWmRxS4Abz5w49ACYAuOLQbNtcMFAhhqRjNgh4CfAL4DQkWHD3BxAVwAbeFE-NRh6RzhZcKQACnMYAAt6Wyi5RWUYVSkWcwksXHwYOwLHIr4ASiMANwh9TQTk6gA6euIAcnbGlObLa2o4YnyHJxhXIA)

And a screenshot of AssemblyScript compiler that is having errors:

![image](https://user-images.githubusercontent.com/13215662/112967773-08c84880-9165-11eb-830d-25580c11b336.png)

**Comment by MaxGraey** [comment]
You could export this:
```ts
export type Component = Map<string, String>

export class EntityInstance {
  id: string
  props: Component
  
  constructor(component: Component) {
    this.id = ''
    this.props = component
  }
}
```

**Comment by JerryGreen** [comment]
Since the parent issue resolved, yes, I can indeed use it. Thx!
