### ISSUE TITLE
What is the difference between == and ===

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1774]
I meet compile error when using `==`, and compile success with `===`.

```ts
ERROR TS2322: Type 'assembly/box/Box<~lib/string/String> | null' is not assignable to type 'assembly/box/Box<~lib/string/String>'.

         assert(this.val != null, msg);
```
When I change `!=` to `!==` it's ok.

Why the error is `not assignable to type` ? It's the reason that Box's `==` have been overloaded by me, but it cannot accept null type ?

**Comment by yjhmelody** [comment]
I find it in docs.
> The === operation cannot be overloaded (is identity equality)

**Comment by yjhmelody** [comment]
But what's the difference for use it for comparing to null ?

**Comment by dcodeIO** [comment]
When the overload is defined as `@operator("!=") ne(other: Box): bool` then it can only be called with non-nullable values, i.e. `Box` but not `Box | null`, so when writing `val != null` that would fail, unless the overload is changed to take `other: Box | null`.

**Comment by yjhmelody** [comment]
> so when writing val != null that would fail, unless the overload is changed to take other: Box | null

Yes, But if want to do such as `null == val`, the overload cannot match it

```
ERROR TS2365: Operator '==' cannot be applied to types 'usize' and '~lib/string/String | null'.

         return  null == this.val;
```

**Comment by dcodeIO** [comment]
You can try to use a static overload instead that allows to specify both input types:

```ts
@operator("!=") static ne(a: Box | null, b: Box | null): bool { ... }
```

**Comment by yjhmelody** [comment]
If I want to comparing the ref equality, it seems that it's always need to use `!==` and `===` to avoid using `==` overload

**Comment by yjhmelody** [comment]
> You can try to use a static overload instead that allows to specify both input types:
> 
> ```ts
> @operator("!=") static ne(a: Box | null, b: Box | null): bool { ... }
> ```

But I need define it in generic class.It's unsupported like you mentioned at  #1767 before
