### ISSUE TITLE
NPM: Tarball seems to be corrupted 

### ISSUE THREAD

**Issue by dievardump** [AssemblyScript/assemblyscript#1777]
While trying to install an npm module depending on this one, I am meeting this errors:

> npm WARN tarball tarball data for assemblyscript@git+ssh://git@github.com/AssemblyScript/assemblyscript.git#36040d5b5312f19a025782b5e36663823494c2f3 (sha512-+bxj80L18f0GP6bb5GKUTMpkQRl2bRqHcl1iPi86arWYaLxO2oYAvWYj5SWLXd7IXmtlRij6hZb7z/hbzEaZYQ==) seems to be corrupted. Trying again.
> npm WARN tarball tarball data for assemblyscript@git+ssh://git@github.com/AssemblyScript/assemblyscript.git#36040d5b5312f19a025782b5e36663823494c2f3 (sha512-+bxj80L18f0GP6bb5GKUTMpkQRl2bRqHcl1iPi86arWYaLxO2oYAvWYj5SWLXd7IXmtlRij6hZb7z/hbzEaZYQ==) seems to be corrupted. Trying again.
> npm ERR! code EINTEGRITY
> npm ERR! sha512-+bxj80L18f0GP6bb5GKUTMpkQRl2bRqHcl1iPi86arWYaLxO2oYAvWYj5SWLXd7IXmtlRij6hZb7z/hbzEaZYQ== integrity checksum failed when using sha512: wanted sha512-+bxj80L18f0GP6bb5GKUTMpkQRl2bRqHcl1iPi86arWYaLxO2oYAvWYj5SWLXd7IXmtlRij6hZb7z/hbzEaZYQ== but got sha512-4HrP/qQ7bQ2nBLYYben0HM94oA2fHOjk1hQ/6K4nPzThB4W4XCCTJd/W+XSx7xm1zMuPijyd3qpE2Uw1k0H12A==. (880047 bytes)

which you can imagine is a bit blocking

# Command executed

`npm install @graphprotocol/graph-cli @graphprotocol/graph-ts`

# Expected Result

The modules and their dependencies should be installed without any problem

# Current Result

An error is thrown and stop the modules installation

# More information

I do not get any error when installing modules not depending on AssemblyScript, which seems to indicate the problem might not come from my side

**Comment by MaxGraey** [comment]
Hi. Please open this issue in graphprotocol/graph-cli repo

**Comment by dievardump** [comment]
The problem is about your tarball on NPM, have you read the bug report?

**Comment by dievardump** [comment]
> Hi. Please open this issue in graphprotocol/graph-cli repo

I see. Thank you.

Next time explaining "because they are the one referencing the specific assemblyscript git" might help to understand why it's there that I should open an issue when the error with the tarball problem pint to your repo.
