### ISSUE TITLE
There is problem with some classes whose parent class have @operator decorated

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1779]
See my repo https://github.com/yjhmelody/as-container/blob/overload-for-subclass/assembly/__tests__/box.spec.ts#L112

The test is always passed.

## How to test
```sh
yarn

yarn test
```

**Comment by dcodeIO** [comment]
Thanks for reporting this, but may I ask for a description of the problem, and perhaps a code sample to reproduce without cloning?

**Comment by MaxGraey** [comment]
Could you try:
```ts
 expect(b3 == b4).toStrictEqual(true);
 expect(b3 != b4).toStrictEqual(false);
```
Does it change something?

**Comment by yjhmelody** [comment]
Please wait a minute.

> Could you try:
> 
> ```ts
>  expect(b3 == b4).toStrictEqual(true);
>  expect(b3 != b4).toStrictEqual(false);
> ```
> 
> Does it change something?

Yes, I meet compiling errors.

```
ERROR TS2322: Type 'bool' is not assignable to type 'assembly/box/Box<bool>'.

         expect(b3 == b4).toStrictEqual(true);
                                        ~~~~
 in assembly/__tests__/box.spec.ts(120,40)

ERROR TS2322: Type 'bool' is not assignable to type 'assembly/box/Box<bool>'.

         expect(b3 != b4).toStrictEqual(false);
                                        ~~~~~
 in assembly/__tests__/box.spec.ts(121,40)
```

The True/False are Box version of true/false.

**Comment by yjhmelody** [comment]
I try to write a minimal example to reproduce it but I failed. I don't know why. 

BTW, the static method `from`  in Box2 return Box rather than Box2.

**Comment by MaxGraey** [comment]
Hmm, but why you return `eq:: Box -> Box -> Box` intead `eq:: Box -> Box-> bool` ?

**Comment by yjhmelody** [comment]
> Hmm, but why you return `eq:: Box -> Box -> Box` intead `eq:: Box -> Box-> bool` ?

Because primitve cannot be null, So I always return box version.

**Comment by MaxGraey** [comment]
Rust for example always return bool for [Ord/PartialOrd](https://doc.rust-lang.org/src/alloc/boxed.rs.html#1081)

**Comment by yjhmelody** [comment]
> Rust for example always return bool for [Ord/PartialOrd](https://doc.rust-lang.org/src/alloc/boxed.rs.html#1081)

Well, when I change the APIs to rust style, the problem disappeared. But still need to know why there is such a problem.

**Comment by yjhmelody** [comment]
> Rust for example always return bool for [Ord/PartialOrd](https://doc.rust-lang.org/src/alloc/boxed.rs.html#1081)

But it impls for PartialOrd not Box. I think the API means to deref box internally, so it return bool. But in `as` if we want to operate in generic class, I think always keep it Box version is fine and more consistent.

**Comment by MaxGraey** [comment]
Basically Box container makes sense only for Rust-like languages which alloc all variables on stack by default. In TS/Kotlin/Swift/Haskell hasn't this container in stdlib

**Comment by yjhmelody** [comment]
> Basically Box container makes sense only for Rust-like languages which alloc all variables on stack by default. In TS/Kotlin/Swift/Haskell hasn't this container in stdlib

yeah, I see.

**Comment by yjhmelody** [comment]
> Rust for example always return bool for [Ord/PartialOrd](https://doc.rust-lang.org/src/alloc/boxed.rs.html#1081)

I have thought about it these days, and it is indeed better to return a Boolean value than its Box version.
Anyway, thank you for your suggestion
