### ISSUE TITLE
[stdlib portable] parsing @external for support

### ISSUE THREAD

**Issue by StEvUgnIn** [AssemblyScript/assemblyscript#1784]
Hi, 
As far, I experienced `@external` is not supported by portable stdlib, which forces `tsc` to wipe declarations from the code.

I am proposing to replace these decorators by constants:
```typescript
@external("foo", "bar")
declare function bar(...args);
```

would turn into
```typescript
...bar = foo.bar; // ... represent actual namespace or module in the context
```

**Comment by dcodeIO** [comment]
Makes me wonder: Is it even possible to use decorators on functions in TS? If so, are these just deleted, or can they have actual logic? I guess the latter would be necessary to do something like the above.

**Comment by StEvUgnIn** [comment]
This is easy to add in Typescript. No need for any WebAssembly input
https://www.typescriptlang.org/docs/handbook/decorators.html#decorators
