### ISSUE TITLE
Strange output of memset polyfill

### ISSUE THREAD

**Issue by lexaknyazev** [AssemblyScript/assemblyscript#1785]
_All WAT snippets were taken from the editor on the AssemblyScript's front page._

#### Redundant operations
```ts
export function foo(): void {
  memory.fill(16, 255, 3);
}
```

```wat
;; INFO asc module.ts --textFile module.wat --binaryFile module.wasm -O3 --runtime stub
(module
 (type $none_=>_none (func))
 (memory $0 0)
 (export "foo" (func $module/foo))
 (export "memory" (memory $0))
 (func $module/foo
  i32.const 16
  i32.const 255
  i32.store8
  i32.const 18
  i32.const 255
  i32.store8
  i32.const 17
  i32.const 255
  i32.store8
  i32.const 18
  i32.const 255
  i32.store8
  i32.const 17
  i32.const 255
  i32.store8
  i32.const 16
  i32.const 255
  i32.store8
 )
)
```

#### Negative offsets
```ts
export function foo(): void {
  memory.fill(0, 0, 2);
}
```

```wat
;; INFO asc module.ts --textFile module.wat --binaryFile module.wasm -O3 --runtime stub
(module
 (type $none_=>_none (func))
 (memory $0 0)
 (export "foo" (func $module/foo))
 (export "memory" (memory $0))
 (func $module/foo
  i32.const 0
  i32.const 0
  i32.store8
  i32.const -2
  i32.const 0
  i32.store8 offset=3
 )
)
```

**Comment by MaxGraey** [comment]
Interesting. Actually all this correct but redundant. Like in first version equivalent to:
```ts
store<u8>(16, 255, 0);
store<u8>(18, 255, 0);
store<u8>(17, 255, 0);

store<u8>(18, 255, 0);
store<u8>(17, 255, 0);
store<u8>(16, 255, 0);
```

second version equivalent to:
```ts
store<u8>(0, 0, 0);
store<u8>(-2, 0, 3); // which the same as store<u8>(1, 0, 0)
```

All this optimizations performs by binaryen. And it seems will be great have Dead Store Elimination (DSE) pass for Binaryen.

**Comment by lexaknyazev** [comment]
The following snippet fails both in Chrome and Safari with OOB memory access.
```ts
export function bar(): void {
  memory.grow(1);
  store<u8>(-2, 0, 3);
}
```

**Comment by MaxGraey** [comment]
> The following snippet fails in Chrome, Firefox, and Safari with OOB memory access.

Binaryen perform this transform only when memoryBase >= 1024 as I remember.

**Comment by MaxGraey** [comment]
Btw `memset(0, 0, 2)` invalid (unreachable) in C++:
https://godbolt.org/z/TTsnhr631

**Comment by lexaknyazev** [comment]
The WebAssembly execution spec [defines](https://webassembly.github.io/spec/core/exec/instructions.html#t-mathsf-xref-syntax-instructions-syntax-instr-memory-mathsf-store-xref-syntax-instructions-syntax-memarg-mathit-memarg-and-t-mathsf-xref-syntax-instructions-syntax-instr-memory-mathsf-store-n-xref-syntax-instructions-syntax-memarg-mathit-memarg) the effective address as `i + memarg.offset`, so `store<u8>(-2, 0, 3)` and `store<u8>(1, 0, 0)` must be semantically equal. It's interesting why all three browsers treat these two instructions differently.

Btw, this fails as well:
```ts
export function bar(): void {
  memory.grow(1);
  store<u8>(-1, 0, 9);
}
```

**Comment by MaxGraey** [comment]
I guess most engines use bound checking which exclude constant offset (last argument). Not sure is it problem of engines or spec

**Comment by lexaknyazev** [comment]
Even if it's a bug with engines, It's probably safe to assume that it will remain as-is (because some platforms no longer receive updates).

For better compatibility, the compiler shouldn't knowingly produce negative offsets such as in the following case:
```ts
export function foo(): void {
  memory.grow(1);
  memory.fill(8, 0, 9);
}
```

**Comment by dcodeIO** [comment]
Relevant code section: https://github.com/AssemblyScript/assemblyscript/blob/057ce465f0c1b8c5346d4b28df8e47089f9db9c9/std/assembly/util/memory.ts#L202-L212

Indeed looks like a bug, since offset operands do wrap around, while offset immediates do not, so a `store(-1, 0, 2)` for example is invalid and will always trap. To be correct, the `memset` polyfill should not use offset immediates where the offset operand may be negative.

**Comment by lexaknyazev** [comment]
> since offset operands do wrap around

What does it mean? `-1` becomes `4294967295`?

The spec defines offset as signed and seems to throw only on `offset + immoffset` being OOB.

**Comment by dcodeIO** [comment]
If I'm not mistaken, `offset` does wrap around like a 32-bit integer, while `immoffset` is always added without wrapping, so that a `store<T>(-offset, x, immoffset)` will always trap if `immoffset >= offset + sizeof<T>()`.

**Comment by lexaknyazev** [comment]
Just verified with `wasm-interp`.

The first offset value is indeed casted to u64 thus `store<u8>(-1, 0, 1)` tries to write to `4294967296`.

**Comment by dcodeIO** [comment]
The PR linked above fixes invalid store offsets within `memset` leading to a trap, but I didn't yet look into reducing duplicate stores as seen in the first snippet, which appears to be a result of `memset` trying very hard to avoid unnecessary branches even if that means a redundant store here or there for small `n`s.
