### ISSUE TITLE
Error parsing WebAssembly text file:

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#179]
Pardon again, I compiled my assemblyscript program to wasm text. Then I deploy the code on a webassembly virtual machine.  It throws the below exceptions when it running.

Error parsing WebAssembly text file:
invalid stack access
     (if (result i32)
```
(if (result i32)
      (i64.eq
       (call $token/CurrencyStats#primaryKey
        (get_local $1)
       )
       (call $token/CurrencyStats#primaryKey
        (i32.load offset=12
         (call $~lib/array/Array<DataItem<CurrencyStats>>#__get
          (i32.load offset=24
           (get_local $0)
          )
          (get_local $3)
         )
        )
       )
      )
```

stack was not empty at end of control structure: stack.size() > controlStack.back().outerStackSize
  (block $break|0
```
(block $break|0
   (loop $repeat|0
    (br_if $break|0
     (i32.ge_u
      (get_local $1)
      (get_local $4)
     )
    )
```

I used the interface in my code. Because of  the  project and code is too long, so I don't paste the code. Can you give me some advice to solve this problem?

**Comment by dcodeIO** [comment]
If you append `--validate` to the asc command when compiling, does it also emit an error?

**Comment by LiaoPeng** [comment]
@dcodeIO  I append `--validate`  to the asc command when compiling, the compiling progress works fine. And the running progress is also emit an error. The `asc` options `--optimize, -O        Optimizes the module. Also has the usual shorthands:`, what's the difference between the different optimize level?

**Comment by dcodeIO** [comment]
Which VM are you using to run the binary? This looks like an issue with either the VM or Binaryen to me, if `--validate` works.

The only optimization presets you'll most likely care about are either `-O3` if you'd like to optimize for speed. or `-Oz` if you'd like to optimize for binary size. The number corresponds to `optimizeLevel` (speed) and the letter to `shrinkLevel` (size).

**Comment by LiaoPeng** [comment]
Thanks for your answer. I using the WAVM to run the binary. https://github.com/AndrewScheidecker/WAVM

**Comment by dcodeIO** [comment]
I'd suggest to create an issue at WAVM with the text format in question. Afaik they have their own text format parser and my first guess would be that it doesn't yet handle something Binaryen emits with AssemblyScript as the generator, but I might of course be wrong.

**Comment by LiaoPeng** [comment]
I really appreciate you answer with patient. I had found my issue code.
```
   for (; idx < len; ++idx) {
            if (newobj.primaryKey() == this._items_vector[idx]._value.primaryKey()) {
                item = this._items_vector[idx];
                break; // if removed, works find
            }
        }
```
I  remove the  break, so it works fine. 

I run another test case
```
let arr:Array<u64> = [12];
        let idx: i32 = 0;
        for (; idx < arr.length; ++idx) {
            if (arr[idx] == owner) {
                break; // not removed
            } 
 }
```
It works also fine. I think the `newobj.primaryKey() == this._items_vector[idx]._value.primaryKey()` leaded the binary generated unusual.

**Comment by dcodeIO** [comment]
I don't think that there is anything wrong with code generation on the AssemblyScript side when `--validate` does not report any issues. You can also try to validate the resulting binary or text format with [WABT](https://github.com/WebAssembly/wabt) to double-check.

**Comment by LiaoPeng** [comment]
Thank you for your advise.
I checked the wast text, a exception was threw.

![image](https://user-images.githubusercontent.com/4305499/43198221-71910074-9040-11e8-8fbc-7caa047b19e8.png)

My assembly script code:
```
	function pwr(a: i32, b: i32): i32 {
		
		if (a == b) {
			return a;
		} else  {
			return b;
		} 
	}
```

The wast code :
```
(module
 (type $iii (func (param i32 i32) (result i32)))
 (type $v (func))
 (global $~lib/internal/allocator/AL_BITS i32 (i32.const 3))
 (global $~lib/internal/allocator/AL_SIZE i32 (i32.const 8))
 (global $~lib/internal/allocator/AL_MASK i32 (i32.const 7))
 (global $~lib/internal/allocator/MAX_SIZE_32 i32 (i32.const 1073741824))
 (global $~lib/allocator/arena/startOffset (mut i32) (i32.const 0))
 (global $~lib/allocator/arena/offset (mut i32) (i32.const 0))
 (global $HEAP_BASE i32 (i32.const 8))
 (memory $0 0)
 (export "memory" (memory $0))
 (export "pwr" (func $safemath/pwr))
 (start $start)
 (func $safemath/pwr (; 0 ;) (type $iii) (param $0 i32) (param $1 i32) (result i32)
  (if
   (i32.eq
    (get_local $0)
    (get_local $1)
   )
   (return
    (get_local $0)
   )
   (return
    (get_local $1)
   )
  )
 )
 (func $start (; 1 ;) (type $v)
  (set_global $~lib/allocator/arena/startOffset
   (i32.and
    (i32.add
     (get_global $HEAP_BASE)
     (get_global $~lib/internal/allocator/AL_MASK)
    )
    (i32.xor
     (get_global $~lib/internal/allocator/AL_MASK)
     (i32.const -1)
    )
   )
  )
  (set_global $~lib/allocator/arena/offset
   (get_global $~lib/allocator/arena/startOffset)
  )
 )
)

```

It seem that multi-if condition with return statements compiled incorrectly.
```
(func $safemath/pwr (; 0 ;) (type $iii) (param $0 i32) (param $1 i32) (result i32)
  (if
   (i32.eq
    (get_local $0)
    (get_local $1)
   )
   (return
    (get_local $0)
   )
   (return
    (get_local $1)
   )
  )
 )
```
If I use `asc a.ts -t a.wast` without option `--optimize`, it works like below.
If I compiled with  option `--optimize`, it works fine.

**Comment by MaxGraey** [comment]
That's really strange. I recreate your code in WebAssembly Studio:
https://webassembly.studio/?f=pllmt6sb6n

And get current output with `-O0` (disable optimization):
```wat
(module
  (type $t0 (func (param i32 i32) (result i32)))
  (func $main/pwr (export "pwr") (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    get_local $p0
    get_local $p1
    i32.eq
    if $I0
      get_local $p0
      return
    else
      get_local $p1
      return
    end
    unreachable)
  (memory $memory (export "memory") 0)
  (global $g0 i32 (i32.const 8)))
```
Which looks normally.
And with default optimization:
```wat
(module
  (type $t0 (func (param i32 i32) (result i32)))
  (func $main/pwr (export "pwr") (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    get_local $p0
    get_local $p1
    get_local $p0
    get_local $p1
    i32.eq
    select)
  (memory $memory (export "memory") 0))
```

**Comment by dcodeIO** [comment]
Issue seems to be that a terminating `unreachable` must be generated if all prior branches `return`.

**Comment by MaxGraey** [comment]
No it seems problem in double return in [code below](https://github.com/AssemblyScript/assemblyscript/issues/179#issuecomment-407726552) (See $safemath/pwr function). Version in WebAssembly studio produce different (right) result.

**Comment by dcodeIO** [comment]
The output above is that of Binaryen writing a binary, read back with WABT (as can be seen from the stack syntax). The issue, however, is in Binaryen writing just text, where the `unrechable` isn't inserted.

**Comment by MaxGraey** [comment]
Hmm, I read about some binaryen issue adressed to same problem with skipped `unreachable` in text format which present in binary. It was couple month ago... May be the same?

**Comment by dcodeIO** [comment]
Yeah, that came up before. I think a proper fix is to explicitly emit the `unreachable` in the compiler, not relying on any postprocessing.

**Comment by LiaoPeng** [comment]
@dcodeIO @MaxGraey 
Pardon again. I found another case that was not passed.
```
function checkBreak():void{
    let item:i32;
    for (let idx:i32=0; idx < 32; ++idx) {
        if (idx == 12) { 
            item = idx + 32;
            break;
        }
    }
    assert(item == 32);
}
checkBreak();
```
The  compile command `asc break.ts -O -t break.wast --validate`
The compiled wast content.
```
(module
 (type $v (func))
 (type $iiiiv (func (param i32 i32 i32 i32)))
 (import "env" "abort" (func $~lib/env/abort (param i32 i32 i32 i32)))
 (global $~lib/allocator/arena/startOffset (mut i32) (i32.const 0))
 (global $~lib/allocator/arena/offset (mut i32) (i32.const 0))
 (memory $0 1)
 (data (i32.const 8) "\08\00\00\00b\00r\00e\00a\00k\00.\00t\00s")
 (export "memory" (memory $0))
 (start $start)
 (func $break/checkBreak (; 1 ;) (type $v)
  (local $0 i32)
  (local $1 i32)
  (block $break|0
   (loop $repeat|0
    (br_if $break|0
     (i32.ge_s
      (get_local $0)
      (i32.const 32)
     )
    )
    (set_local $1
     (if (result i32)
      (i32.eq
       (get_local $0)
       (i32.const 12)
      )
      (i32.add
       (get_local $0)
       (i32.const 32)
      )
      (block
       (set_local $0
        (i32.add
         (get_local $0)
         (i32.const 1)
        )
       )
       (br $repeat|0)
      )
     )
    )
   )
  )
  (if
   (i32.ne
    (get_local $1)
    (i32.const 44)
   )
   (block
    (call $~lib/env/abort
     (i32.const 0)
     (i32.const 8)
     (i32.const 33)
     (i32.const 4)
    )
    (unreachable)
   )
  )
 )
 (func $start (; 2 ;) (type $v)
  (set_global $~lib/allocator/arena/startOffset
   (i32.const 32)
  )
  (set_global $~lib/allocator/arena/offset
   (get_global $~lib/allocator/arena/startOffset)
  )
  (call $break/checkBreak)
 )
)

```
```
Error: validate failed:
test.wast:39:9: error: type mismatch in if false branch, expected [i32] but got []
       (br $repeat|0)
```

**Comment by MaxGraey** [comment]
I tried generate it in WAS and export binary to wabt which generate valid wast:
```wast
(module
  (type $t0 (func))
  (type $t1 (func (param i32 i32 i32 i32)))
  (import "env" "abort" (func $~lib/env/abort (type $t1)))
  (func $main/checkBreak (type $t0)
    (local $l0 i32) (local $l1 i32)
    (block $B0
      (loop $L1
        (br_if $B0
          (i32.ge_s
            (get_local $l0)
            (i32.const 32)))
        (set_local $l1
          (if $I2 (result i32)
            (i32.eq
              (get_local $l0)
              (i32.const 12))
            (then
              (i32.add
                (get_local $l0)
                (i32.const 32)))
            (else
              (set_local $l0
                (i32.add
                  (get_local $l0)
                  (i32.const 1)))
              (br $L1))))))
    (if $I3
      (i32.ne
        (get_local $l1)
        (i32.const 32))
      (then
        (call $~lib/env/abort
          (i32.const 0)
          (i32.const 8)
          (i32.const 11)
          (i32.const 4))
        (unreachable))))
  (func $start (type $t0)
    (set_global $g0
      (i32.const 32))
    (set_global $g1
      (get_global $g0))
    (call $main/checkBreak))
  (memory $memory (export "memory") 1)
  (global $g0 (mut i32) (i32.const 0))
  (global $g1 (mut i32) (i32.const 0))
  (start 2)
  (data (i32.const 8) "\07\00\00\00m\00a\00i\00n\00.\00t\00s"))
```

So what kind of tools you are validate?

**Comment by MaxGraey** [comment]
Also I tried build binary from your wast file as via binaryen and wabt in WAS:
https://webassembly.studio/?f=j2buxckf3o

All variants is valid as well.

**Comment by LiaoPeng** [comment]
I recognized that your pasted code was the "main.wat.wasm" file
I pasted code was "main.wat" file. And I checked the "main.wat" file on the website.
https://cdn.rawgit.com/WebAssembly/wabt/aae5a4b7/demo/wat2wasm/

it hits error
![image](https://user-images.githubusercontent.com/4305499/43254620-66791f72-90fa-11e8-9109-d281f0be5b47.png)

**Comment by MaxGraey** [comment]
I don't recommend use online tools from wabt because it pretty old (last updated 2 month ago). WebAssembly Studio has much more newer versions for binaryen and wabt.

**Comment by dcodeIO** [comment]
Is the new case a Binaryen issue maybe?

Before optimizations:

```wat
 (func $tests/compiler/empty/checkBreak (; 1 ;) (type $v)
  (local $0 i32)
  (local $1 i32)
  (block $break|0
   (set_local $1
    (i32.const 0)
   )
   (loop $repeat|0
    (br_if $break|0
     (i32.eqz
      (i32.lt_s
       (get_local $1)
       (i32.const 32)
      )
     )
    )
    (if
     (i32.eq
      (get_local $1)
      (i32.const 12)
     )
     (block
      (set_local $0
       (i32.add
        (get_local $1)
        (i32.const 32)
       )
      )
      (br $break|0)
     )
    )
    (set_local $1
     (i32.add
      (get_local $1)
      (i32.const 1)
     )
    )
    (br $repeat|0)
   )
  )
  (if
   (i32.eqz
    (i32.eq
     (get_local $0)
     (i32.const 44)
    )
   )
   (block
    (call $~lib/env/abort
     (i32.const 0)
     (i32.const 8)
     (i32.const 9)
     (i32.const 2)
    )
    (unreachable)
   )
  )
 )
```

After -O:

```wat
 (func $tests/compiler/empty/checkBreak (; 1 ;) (type $v)
  (local $0 i32)
  (local $1 i32)
  (block $break|0
   (loop $repeat|0
    (br_if $break|0
     (i32.ge_s
      (get_local $0)
      (i32.const 32)
     )
    )
    (set_local $1
     (if (result i32)
      (i32.eq
       (get_local $0)
       (i32.const 12)
      )
      (i32.add
       (get_local $0)
       (i32.const 32)
      )
      (block ;; this is wrong, not i32
       (set_local $0
        (i32.add
         (get_local $0)
         (i32.const 1)
        )
       )
       (br $repeat|0)
      )
     )
    )
   )
  )
  (if
   (i32.ne
    (get_local $1)
    (i32.const 44)
   )
   (block
    (call $~lib/env/abort
     (i32.const 0)
     (i32.const 8)
     (i32.const 9)
     (i32.const 2)
    )
    (unreachable)
   )
  )
 )
```

And `--validate` also doesn't catch this. @kripken ?

**Comment by LiaoPeng** [comment]
@MaxGraey Thanks for your advice.
I build the 'build.ts' on the webassembly studio, I also got a error hit. Does I operator wrong?


![image](https://user-images.githubusercontent.com/4305499/43257635-e6c15912-9102-11e8-813d-6635744aa719.png)

**Comment by MaxGraey** [comment]
Yah, it seems this some issue with text represantation in binaryen. If you assemble and disassemble again your example works well: https://webassembly.studio/?f=ww420199o3t

**Comment by kripken** [comment]
```
 (block ;; this is wrong, not i32
```
That block has no branches to it (no name, too), and ends in `(br $repeat|0)`, so it has type `unreachable`. That is a valid type in Binaryen IR, but not in wasm. When Binaryen emits wasm it will fix that up (by emitting an `unreachable` after the block, which makes it valid to consume in the outside wasm).

**Comment by dcodeIO** [comment]
Ah, so this is valid Binaryen IR even though it's part of an `(if (result i32 ...)`, hmm. I somewhat expected that when optimizations are performed, that the text format wouldn't become any more invalid than the untouched code was before. This is unfortunate, as there is no way to fix this from the AssemblyScript side then, except always piping Binaryen-generated text format through WABT, correct?

**Comment by kripken** [comment]
In general, yeah, binaryen optimizations can do arbitrary changes, and the printed text format may not be valid wasm text. In the immediate term, using wabt for guaranteed valid wasm text makes sense. But we should probably just improve binaryen's Stack IR printing - that IR is 100% valid wasm, so it's just a matter of refactoring the printing code a little, I'll look into that.

**Comment by kripken** [comment]
I did some quick hacking in [a branch](https://github.com/WebAssembly/binaryen/commits/stack4), and this was easier than I thought. Not heavily tested yet, but simple text format outputs look, and wabt accepts them as input.

To check it out, run `--generate-stack-ir --print-stack-ir` (you don't need the first if you run optimizations that generate stack IR anyhow, like `-O`).

**Comment by dcodeIO** [comment]
Nice, thanks! Quickly tested with the case above, and the same func in stack IR now looks like:

```wat
 (func $empty/checkBreak (; 1 ;) (; has Stack IR ;) (type $v)
  (local $0 i32)
  (local $1 i32)
  block $break|0
   loop $repeat|0
    get_local $0
    i32.const 32
    i32.ge_s
    br_if $break|0
    get_local $0
    i32.const 12
    i32.eq
    if (result i32)
     get_local $0
     i32.const 32
     i32.add
    else
     ;; <no explicit block>
     get_local $0
     i32.const 1
     i32.add
     set_local $0
     br $repeat|0
     ;; </no explicit block>
    end
    set_local $1
   end
  end
  get_local $1
  i32.const 44
  i32.ne
  if
   i32.const 0
   i32.const 8
   i32.const 9
   i32.const 2
   call $~lib/env/abort
   unreachable
  end
 )
```

Mostly identical, except that it's valid due to omitting the explicit `(block ...)` as it seems. That explains the previous validation error of `0:0: error: type mismatch in if false branch, expected [i32] but got []`. Btw, blocky IR would be valid as well if that block was `(block (result i32) ...)`, according to WABT, even without the use of an `unreachable` instruction.

But anyway, being able to produce spec-compliant text format will be very useful over here :)

**Comment by dcodeIO** [comment]
I think this should be fixed by now. Feel free to reopen if I'm wrong.
