### ISSUE TITLE
Bus error when trying to run AssemblyScript output in Node.js

### ISSUE THREAD

**Issue by okyanusoz** [AssemblyScript/assemblyscript#1797]
I am trying to implement the Levenshtein Distance algorithm in AssemblyScript. Here's assembly/index.ts:

     export function levenshteinDistance(s: string, t: string): i32 {
      if(!s.length) {
        return t.length
      }
      if(!t.length) {
        return s.length
      }
      const arr: Array<Array<i32>> = []
      for (let i = 0; i <= t.length; i++) {
        arr[i] = [i]
        for (let j = 1; j <= s.length; j++) {
          arr[i][j] =
            i === 0
            ? j
            : min([
              arr[i - 1][j] + 1,
              arr[i][j - 1] + 1,
              arr[i - 1][j - 1] + (s[j - 1] === t[i - 1] ? 0 : 1)
            ])
        }
      }
      return arr[t.length][s.length]
    }
    
    export function min(array: Array<i32>) : i32 {
      return array.reduce((a: i32, b: i32) => {
        const floatA = <f64>a
        const floatB = <f64>b
        const i32Result = <i32>Math.min(floatA, floatB)
        return i32Result
      }, array[0])
    }

It builds fine.

But when I try to run it with the AssemblyScript loader in Node.js, it crashes:
``loader.instantiateSync(require("fs").readFileSync("build/optimized.wasm")).exports.levenshteinDistance("duck", "door")
``

`[1]    11409 bus error  node`

What I might be doing wrong?

Thanks!

**Comment by okyanusoz** [comment]
UPDATE: It seems like the problem is the function accepting strings. Not sure why

**Comment by okyanusoz** [comment]
It works now, but it always returns 5 when I run:
`mod.exports.levenshteinDistance(mod.exports.__newString("hello"), mod.exports.__newString("helo"))`

My new code:

```
export function levenshteinDistance(s: string, t: string): i32 {
  trace("levenstheinDistance called")
  
  const arr: Array<Array<i32>> = []
  for (let i = 0; i <= t.length; i++) {
    trace("iter[i]")
    arr[i] = [i]
    for (let j = 1; j <= s.length; j++) {
      trace("iter[j]")
      arr[i][j] =
        i === 0
        ? j
        : min([
          arr[i - 1][j] + 1,
          arr[i][j - 1] + 1,
          arr[i - 1][j - 1] + (s[j - 1] === t[i - 1] ? 0 : 1)
        ])
    }
  }
  return arr[t.length][s.length]
}

export function min(array: Array<i32>) : i32 {
  trace("called min")
  return array.reduce((a: i32, b: i32) => {
    const floatA = <f64>a
    const floatB = <f64>b
    const i32Result = <i32>Math.min(floatA, floatB)
    return i32Result
  }, array[0])
}
```

**Comment by MaxGraey** [comment]
Problem here: `arr[i - 1][j - 1] + (s[j - 1] === t[i - 1] ? 0 : 1)`. In AssemblyScript tripple equal `===` have special meaning and compare raw pointers instead overloaded equal (in current case it's string comparison). See docs: https://www.assemblyscript.org/basics.html#triple-equals

So if you change `===` to `==` it will solve your problem.

Also you could significantly speed-up your code:
https://bit.ly/3uM6Ls9

**Comment by dcodeIO** [comment]
@MaxGraey Didn't we see the `[1] 11409 bus error node` error a while ago? Do you remember what it indicated?

**Comment by MaxGraey** [comment]
It usually indicate OOB. node.js skip sandbox mode that's why it usually fallback to low level `bus error`. In browser it usually OOB

**Comment by okyanusoz** [comment]
It works now!

Thank you.
