### ISSUE TITLE
asm.js

### ISSUE THREAD

**Issue by blooddy** [AssemblyScript/assemblyscript#18]
Is it possible to generate asm.js ?

**Comment by dcodeIO** [comment]
Technically, yes (the `-a` option in asc), but there's [this open issue](https://github.com/WebAssembly/binaryen/issues/1384) on the Binaryen side blocking it.

**Comment by dcodeIO** [comment]
There has been [some progress on the Binaryen side](https://github.com/WebAssembly/binaryen/pull/1433) in order to fix identifiers. While not a 100% safe yet, it should work for most programs now.
