### ISSUE TITLE
Should all consts be lazy be default?

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1800]
Is there any reason that constants aren't lazy by default?  Consumers of libraries might be confused when they discover globals they didn't use in the final binary.

**Comment by dcodeIO** [comment]
To determine whether a `const` is indeed constant in a Wasm-sense, we have to evaluate it, but its value may depend on ordering, resulting in a different value when evaluating it at a later time.

```ts
const a = 1 + other; // evaluates
```

```ts
@lazy const a = 1 + other;
...
// evaluates late, and other may change
```

In the final binary, optimizations should eliminate these.
