### ISSUE TITLE
Such an inheritance relationship cannot be achieved

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1803]
A class C1 cannot implement interface I1, when its parent class C2 has implemented interface I2, I1 is a sub-interface of I2.

```ts
interface Foo {
    foo(): void;
}

interface Foo2 extends Foo {
    foo2(): void;
}

class Bar implements Foo {
    foo(): void {
        throw new Error("Method not implemented.");
    }
}

class Bar2 extends Bar implements Foo2 {
    foo2(): void {
        throw new Error("Method not implemented.");
    }
}

let b = new Bar2();
```

or 
```ts
interface Foo {
    foo(): void;
}


class Bar implements Foo {
    foo(): void {
        throw new Error("Method not implemented.");
    }
}

class Bar2 extends Bar implements Foo {
    foo(): void {
        throw new Error("Method not implemented.");
    }
}
```

```
ERROR TS2394: This overload signature is not compatible with its implementation signature.

     foo(): void {
     ~~~~~~~~~~~
 in foo.ts(10,5)

     foo(): void;
     ~~~~~~~~~~~
 in foo.ts(2,5)

FAILURE 1 compile error(s)
```

**Comment by yjhmelody** [comment]
This problem seriously affects the inability to reimplement some interfaces when deriving subclasses from the parent class

**Comment by MaxGraey** [comment]
What if you replace interfaces by abstract classes? Does this solve your problem for now?

**Comment by yjhmelody** [comment]
> What if you replace interfaces by abstract classes? Does this solve this problem for now?

Sorry, although it can be compiled by changing to an abstract class, I need to implement multiple interfaces in my code scenario.

**Comment by MaxGraey** [comment]
Sorry, I'll revisit this in future. But currently I should work in many other stuffs, so I cant' promise it will solve soon. You could try refactor your code or try to inverstigate and fix this by yourself. PR is welcome!

**Comment by yjhmelody** [comment]
Oh, I found that I only need to remove the `implements Foo` of the subclass, and then all the superclass methods can be rewritten normally. Maybe this error is just a problem with the compiler checking implementation, I will try to investigate this problem

**Comment by yjhmelody** [comment]
Oh, I found that I only need to remove the `implements Foo` of the subclass, and then all the superclass methods can be rewritten normally. Maybe this error is just a problem with the compiler checking implementation, I will try to investigate this problem

**Comment by yjhmelody** [comment]
I find `isCompatibleOverride` need to check `FUNCTION_PROTOTYPE`, But sorry, the code is more complicated, I don’t know how to modify it.
