### ISSUE TITLE
AssemblyScript to WASM compiler in Javascript

### ISSUE THREAD

**Issue by photopea** [AssemblyScript/assemblyscript#1805]
Hi, I see your current AssemblyScript to WASM compilation requires a native app. I am not used to use any native programs in my web development (except a text editor and a web browser).

Could you implement your compiler as a javascript function, which will take a string as a parameter, and would return the Uint8Array containing a WASM program? I think it requires only parsing the AssemblyScript code, and then, processing a syntax tree. I think it could be under 50 kB of minified JS.

I would like to upload AssemblyScript directly to my web server over the FTP, and the website would load both the compiler JS file and the AssemblyScript file, and would generate the WASM each time the website is opened.

**Comment by dcodeIO** [comment]
We provide a browser SDK that can be used to run the compiler on the Web, some docs here: https://github.com/AssemblyScript/assemblyscript/tree/master/lib/sdk

The editor component on the website is using it for example.
