### ISSUE TITLE
Loader __getArray, "unsupported align: -1"

### ISSUE THREAD

**Issue by data-ux** [AssemblyScript/assemblyscript#1807]
I'm following along the [Loader documentation examples](https://www.assemblyscript.org/loader.html#reading-arrays) about reading arrays from AssemblyScript. While trying to implement the example exactly as in the documentation, calling `__getArray` produces the error "unsupported align: -1". 

An minimal project reproducing the problem is here:
https://github.com/data-ux/unsupported-align

I have tried importing the loader both from node_modules and from jsdelivr with the same effects. I'm on Assemblyscript version 0.18.25

**Comment by MaxGraey** [comment]
Make sure you add `exportRuntime: true` to debug and release configs: https://github.com/data-ux/unsupported-align/blob/master/asconfig.json#L3. It described in `NOTE` section of Loader's documentation

**Comment by data-ux** [comment]
Thanks. I saw the note but somehow understood it as "Allocating objects [...] externally requires..." and thought that allocating objects on the AssemblyScript side would not need the `exportRuntime: true` flag.

It seems the relevant thing exportRuntime does in this case is adding the `__rtti_base` export to the module. The export is then used in the loader in `getInfo()`, `getBase()` and `__instanceof()`. I'm wondering if there is any valid case where calling these functions when `__rtti_base==-1`? Or could we just always  `throw Error(E_NOEXPORTRUNTIME)` when the the value is -1 within these functions? It would be alot more helpful to get the error "Operation requires compiling with --exportRuntime" than "unsupported align: -1".
