### ISSUE TITLE
It seems that assemblyscript did not upload the compiler part of the code

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1809]
See https://github.com/willemneal/visitor-as/pull/12 . Some code maybe need to use this part of code in `as`. 

But sorry, when writing the AS library, I can’t seem to import the compiler code.

**Comment by yjhmelody** [comment]
Hi, guys. How to deal with this problem?

**Comment by MaxGraey** [comment]
all `utils` of compiler is internal helpers mostly needed for polyfill gap between assemblyscript js and assemblyscript wasm (bootstraped) versions. Generally all this code will not need in the future.

So I'm not sure it's worth exporting all this.

**Comment by yjhmelody** [comment]
I personally think that the Parser /Program/Module that needs to be written for transform should be exported
