### ISSUE TITLE
Access modifiers like private and protected are not currently enforced

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1810]
The private modifier is invalid, and subclasses can still access private fields.

**Comment by MaxGraey** [comment]
Can confirm. Minimal example:
```ts
class Base {
  private foo(): void {}
}

class Derived extends Base {
  constructor() {
    super();
    this.foo(); // valid?
  }
}

new Derived();
```
Expected:
```
Property 'foo' is private and only accessible within class 'Base'.
```
Actual:
```
compiled successfully
```

**Comment by yjhmelody** [comment]
Sorry, I feel there are more problems here @MaxGraey

```ts
class Foo {
    private foo: bool = false;
}

class Bar {
    bar(): bool {
        return new Foo().foo;
    }
}

let b: Bar = new Bar();
b.bar();
```

```ts
class Foo {
    private static foo: bool = false;
}

class Bar {
    bar(): bool {
        return Foo.foo;
    }
}

let b: Bar = new Bar();

b.bar();
```
The aboves can be compiled successfully

**Comment by yjhmelody** [comment]
It seems that `private` always fails

**Comment by dcodeIO** [comment]
See also: https://www.assemblyscript.org/status.html#classes-and-interfaces

> Access modifiers like private and protected are not currently enforced. Likely to be enforced in the future.

**Comment by yjhmelody** [comment]
At present, is the problem of the same name of the parent and child class fields affecting the implementation progress of the visibility modifier, or is it due to other considerations?

**Comment by yjhmelody** [comment]
I closed it.

**Comment by saulecabrera** [comment]
> See also: https://www.assemblyscript.org/status.html#classes-and-interfaces
> 
> > Access modifiers like private and protected are not currently enforced. Likely to be enforced in the future.

@dcodeIO is there any technical reason behind this behavior? Coming from the angle of real-world APIs this doesn't seem ideal.
