### ISSUE TITLE
Is it possible to provide a non-element copy version of Array ?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1811]
Provide a non-element copy version of Array, similar to slice in golang.
The current various Arrays are close to JS Arrays, and when the slice method is called on them, copy overhead will always be incurred. I don't know whether the runtime of AS can realize this kind of Array

**Comment by MaxGraey** [comment]
What you mean calling this "non-element copy"? AS has `StaticArray<T>` which doesn't have backing store and very similar to ordinal array in C and slices to Go and Rust

**Comment by yjhmelody** [comment]
But in doc:
> function slice<T>(source: StaticArray<T>, start?: i32, end?: i32): StaticArray<T>
Like the instance member slice, but returning a StaticArray
I don't know if it will copy elements.

`subarray` is what I want to express, but it only exists in TypedArray and does not support any type
