### ISSUE TITLE
New `transforms` option doesn’t instantiate transform

### ISSUE THREAD

**Issue by surma** [AssemblyScript/assemblyscript#1813]
In #1786, y’all kindly added a new `transform` options to the cli’s `main()` because of our discussion in torch2424/as-bind#75. However, I didn’t realize that the new code path doesn’t actually instantiate the transform or fixes up the prototype.

Transforms passed via `--transform` get this code path:
https://github.com/AssemblyScript/assemblyscript/blob/7d0690d91877a43a000bf17035c08acecaa93a25/cli/asc.js#L519-L529

while the new `main()` parameter gets:

https://github.com/AssemblyScript/assemblyscript/blob/7d0690d91877a43a000bf17035c08acecaa93a25/cli/asc.js#L505

I think it’d be great if both ways to pass in transforms get the same fix-ups applied.

**Comment by MaxGraey** [comment]
Thanks for report. If you know for better fix this then PR is welcome!

**Comment by surma** [comment]
Created PR #1814 :D
