### ISSUE TITLE
ts does not support such a syntax

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1819]
it's ok in `as`, but will meet parser error in `ts`.
```ts
1 instanceof Array<string>
```

So, some linters such as eslint cannot handle it good.

**Comment by MaxGraey** [comment]
Basically we have many thing which non-combatible with ts-like linters. That's why we need our own linter or at least add some plugins for eslint.

**Comment by MaxGraey** [comment]
See related issue: https://github.com/AssemblyScript/assemblyscript/issues/991

**Comment by yjhmelody** [comment]
Ok
