### ISSUE TITLE
Need a memory aligned version of `offsetof`

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1822]
If I want to implement a general shallow copy, I need to know the byte size of a type aligned, and then use memory.copy to copy, but it seems that I can't do it currently. Forgive me if i got it wrong.

**Comment by MaxGraey** [comment]
not sure I'm understand orrectly but you should have all utils for that. `offsetof` could get total size of struct/class which always aligned to 16 bytes (in address)

**Comment by yjhmelody** [comment]
The doc:
> function offsetof<T>(fieldName?: string): usize
Determines the offset of the specified field within the given class type. Returns the class type's end offset (means: where the next field would be located, before alignment) if field name has been omitted. Compiles to a constant. The fieldName argument must be a compile-time constant string because there is no information about field names anymore in the final binary. Hence, the field's name must be known at the time the returned constant is computed.

I personally understand that the documentation in parentheses implies that the offset obtained here is not the real offset.

Does it actually mean that the field obtained by offsetof is always the actual size of this type, not the filled size?

**Comment by MaxGraey** [comment]
> Does it actually mean that the field obtained by offsetof is always the actual size of this type, not the aligned size?

Yes. all fields have aligned offsets [according to their sizes](https://doc.rust-lang.org/reference/type-layout.html#primitive-data-layout). Ordering also preserved.

**Comment by yjhmelody** [comment]
Thanks!.
