### ISSUE TITLE
`@global` don't support namespace

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1826]
For example:
```ts
@global 
export * as foo from "./assembly/index";
```

The `global` doc is `Annotates an element as a program global.`

**Comment by MaxGraey** [comment]
Global decorator shouldn't support namespace. It put function or variable/constant to global scope and allow call it without from any place. Like:

foo.ts:
```ts
@global let foo: i32 = 1;
@global function boo(a: i32): i32 {
  return a;
}
```

in index.ts:
```ts
import "./foo.ts" // just import this file

// now use can access to "foo" and "boo"
log(boo(foo)); // => 1
```

**Comment by willemneal** [comment]
@yjhmelody This can be faked by using the `lib` CLI option to a file that exports as you suggest.

The near-sdk handles this by adding the lib option to `asconfig.json`: https://github.com/near/near-sdk-as/blob/master/sdk/asconfig.json

And `json.lib.ts` is:

```ts

import { JSON } from "assemblyscript-json";

export { JSON };

```

Which could be `import * as x from ".."`.
