### ISSUE TITLE
Is there any way to import new modules in `afterParse`?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1827]
Is there any way to import new modules in `afterParse`?
Because the code generated by my transform needs to import the dependency library I wrote.
Or any suggestions and good practices to archive the same thing? Thank you

**Comment by willemneal** [comment]
Does this not work for you: https://github.com/AssemblyScript/assemblyscript/blob/d610f0125d122d30750788321965a4c56f52177f/src/parser.ts#L129

**Comment by yjhmelody** [comment]
> Does this not work for you:
> 
> https://github.com/AssemblyScript/assemblyscript/blob/d610f0125d122d30750788321965a4c56f52177f/src/parser.ts#L129

In fact, I don't know, this function is to modify the state of Parser. If I want to modify a Source, then I will have problems using this method directly. However, there is currently no method similar to `updateSource`

**Comment by willemneal** [comment]
This is how I handled updating the source; I remove it and then add it back.

**Comment by yjhmelody** [comment]
> This is how I handled updating the source; I remove it and then add it back.
> 
> https://github.com/near/near-sdk-as/blob/master/bindgen/src/transformer.ts

I will have a try.

**Comment by yjhmelody** [comment]
> This is how I handled updating the source; I remove it and then add it back.
> 
> https://github.com/near/near-sdk-as/blob/master/bindgen/src/transformer.ts

Thanks, I feel feasible. But you did not consider path cross-platform here https://github.com/near/near-sdk-as/blob/master/bindgen/src/transformer.ts#L37
`as`'s internalPath and normalizedPath use `/` as sep. But path.join use `\` in windows
