### ISSUE TITLE
`APIOptions` cannot be implemented normally

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1832]
APIOptions cannot be implemented normally.
When I defined a class to implement APIOptions and pass it to `asc.main`, I found that `this` of class is undefined.

**Comment by yjhmelody** [comment]
In asc.js, functions like `writeFile` are not called through methods, but through function calls, which leads to problems with this point

**Comment by yjhmelody** [comment]
@MaxGraey 
Now we need to implement static binding `this` for the custom APIOptions, because this has changed when it is called. I think this problem can be fixed, always use the passed object as `this`.

**Comment by MaxGraey** [comment]
I don't understand. Could you share example what are you trying to do with this object? `APIOptions` is plain object (not a class). You shouldn't extends it. See this example:
https://github.com/AssemblyScript/examples/blob/main/sdk/index.html#L44

**Comment by yjhmelody** [comment]
But maybe some users are not clear, I fell into the trap before.
Because APIOptions is an interface, users will be accustomed to implementing it in a class, and the encapsulation state is in the class, which leads to dependence on this of this class. 

I thought about it. Maybe APIOptions should be more precise:
Replace 
```ts
export interface APIOptions {
  /** Standard output stream to use. */
  stdout?: OutputStream;
  /** Standard error stream to use. */
  stderr?: OutputStream;
  /** Reads a file from disk (or memory). */
  readFile?: (filename: string, baseDir: string) => string | null;
  /** Writes a file to disk (or memory). */
  writeFile?: (filename: string, contents: Uint8Array, baseDir: string) => void;
  /** Lists all files within a directory. */
  listFiles?: (dirname: string, baseDir: string) => string[] | null;
  /** Handler for diagnostic messages. */
  reportDiagnostic?: DiagnosticReporter;
  /** Additional transforms to apply. */
  transforms?: Transform[];
}

type DiagnosticReporter = (diagnostic: DiagnosticMessage) => void;

```

To
```ts
export interface APIOptions {
  /** Standard output stream to use. */
  stdout?: OutputStream;
  /** Standard error stream to use. */
  stderr?: OutputStream;
  /** Reads a file from disk (or memory). */
  readFile?: (this:any, filename: string, baseDir: string) => string | null;
  /** Writes a file to disk (or memory). */
  writeFile?: (this:any,filename: string, contents: Uint8Array, baseDir: string) => void;
  /** Lists all files within a directory. */
  listFiles?: (this:any,dirname: string, baseDir: string) => string[] | null;
  /** Handler for diagnostic messages. */
  reportDiagnostic?: DiagnosticReporter;
  /** Additional transforms to apply. */
  transforms?: Transform[];
}

type DiagnosticReporter = (this:any, diagnostic: DiagnosticMessage) => void;
```

**Comment by MaxGraey** [comment]
> But maybe some users are not clear, I fell into the trap before.

That's well known behaviour of JavaScript. I don't think we should force bind for all methods and overload logic just because not everyone understands how JavaScript works.

**Comment by yjhmelody** [comment]
But doesn't the TS interface promise the point of this? Asc internally modified the context and did not reflect in this interface.

Could it be said that the default semantics of interface never guarantees the value of `this`?

**Comment by MaxGraey** [comment]
> But doesn't the TS interface promise the point of this?

TS is just type descriptions + checker. It doesn't change JS at all. All semantics stay the same

**Comment by yjhmelody** [comment]
Well, I'm just very depressed and can't tell from the interface definition whether we need static or explicit binding. This is really not a problem of `APIOptions` definition.
