### ISSUE TITLE
[Feature] Macros or transforms written in AS

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1833]
This issue is to track adding the feature of Macros or at least transforms written in AssemblyScript source. @yjhmelody is currently working on this as part of a NEAR grant.

This involves the following:

- Adding the parser and AST as a library, e.g. `import { Parser } from "compiler/parser"`.
    I'm about to push up a branch where I was able to do this by creating a linked directory `shared_lib`, which then had a symbolic link named `compiler` to link to `../src`. then `--lib shared_lib` allowed this to work. Though I think this should rather be done by `asc.js`.

- Add a macro expansion stage which would compile the macros (perhaps files with function @macro decorators) into a single binary.

- During a transform pass, each call site looks up the corresponding export.  The AST node is passed to the macro (how this is done is up for debate, but my thoughts are pass a string and reparse internally) which returns an AST node (again perhaps a string which needs to be reparsed) which replaces the previous. (I am also about to push a transform visitor, which will make this easy).

Perhaps the easiest next step is to not compile to Wasm, but rather have macros be portable typescript since ts-node is already a dependency. 

While I was able to get the compiler components to be a library, I ran into the issue that the AST now has a dependency to `module.ts`, which in turn depends on `binaryen`.  This means the the generated binary requires `binaryen` imports.

**Comment by yjhmelody** [comment]
> While I was able to get the compiler components to be a library, I ran into the issue that the AST now has a dependency to `module.ts`, which in turn depends on `binaryen`. This means the the generated binary requires `binaryen` imports.

In the parsing stage, I think it is possible to directly remove the `CompiledExpression`.
