### ISSUE TITLE
Support resolving index sub-modules 

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#184]
Project structure:

```
assembly
  - main.ts
  integer
     - index.ts
     - foo.ts
     - boo.ts
```

assembly/main.ts:
```ts
import { foo, boo } from './integer';
```
assembly/integer/index.ts:
```ts
import { foo } from './foo';
import { boo } from './boo';
export { foo, boo };
```

Example on [WebAssembly Studio](https://webassembly.studio/?f=yqv8hp1ivgd)

**EDIT**
> Btw. the Wasm Studio fiddle is missing the exports in integer/index.ts.

Fixed. Fiddle updated. Issue still actual

**Comment by dcodeIO** [comment]
Is this only an issue with index files? Asking because the `reexport` test should actually cover this.

**Comment by MaxGraey** [comment]
Actually I got this problem in that [project](https://github.com/MaxGraey/bignum.wasm/blob/master/assembly/index.ts#L4). And make workaround just directly importing for each module separately. So this:
```ts
import { u128, u256 } from "./integer";
export {
  u128,
  u256,
};
```
Didn't work for me.

**Comment by dcodeIO** [comment]
@MaxGraey  Is this still an issue?

**Comment by dcodeIO** [comment]
Any news on this? :)

**Comment by dcodeIO** [comment]
Feel free to reopen if it turns out that there are remaining issues :)
