### ISSUE TITLE
Provide a Map version that hashes the referenced value, not the address

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1840]
The current Map imitates the semantics of TS, but unfortunately. Many times we need to hash based on the value. If we don't have a reference to the key in the map, we will never be able to access it unless we traverse it.

Or need to provide annotations to overload the hash operation.

@willemneal  Hi, Wouldn't you encounter such a problem in your project?

**Comment by MaxGraey** [comment]
I suggested this on official TC39 forum but it seems nobody interested in this:
https://es.discourse.group/t/custom-hash-and-equal-functions-for-map-and-set-collections/673

**Comment by yjhmelody** [comment]
Oh, that's really embarrassing. Does AS have its own considerations?

**Comment by MaxGraey** [comment]
We can. But nobody will use it if it's non-standard operation. Also it's nearly impossible to polyfill in JS (we should keep portable mode consistent as well)

**Comment by MaxGraey** [comment]
But you can go to that forum and give more arguments in topic. Perhaps you will be more convincing than me

**Comment by yjhmelody** [comment]
> But you can go to that forum and give more arguments in topic. Perhaps you will be more convincing than me

I will have a try.

**Comment by yjhmelody** [comment]
Maybe we can write a third-party Set/Map library to support Custom hash and equal functions

**Comment by jtenner** [comment]
Hi @yjhmelody. I have experience with codegen. Please message me on discord and I can help you out.

**Comment by yjhmelody** [comment]
I closed it because no one cares about me at tc39

**Comment by jtenner** [comment]
@yjhmelody it should be possible to do this with a transform. Do you have an algorithm in mind?

**Comment by yjhmelody** [comment]
@jtenner Sorry, I think we need built-in value comparison operators instead of reference address comparison. If the std does not support it, I think it is always difficult to do it. Can you implement it like as-pect?

**Comment by jtenner** [comment]
Yes. We can do hash based comparisons with a transform. Can you message me on the discord server? Would be happy to help develop a proper library for this.
