### ISSUE TITLE
Nullability check outside function

### ISSUE THREAD

**Issue by teleclimber** [AssemblyScript/assemblyscript#1843]
```
$ asc -v
Version 0.18.30
```

I'm just getting into WASM (like, today), so forgive me if I am way off, but I was surprised by this behavior:

```
import "wasi";
import { Console, Environ } from "as-wasi";

let env = new Environ();
let home = env.get("HOME");

if( home ) {
  Console.log(home);
}
else {
  Console.log( "no home" );
}
```

Compiling results in :

```
ERROR TS2322: Type '~lib/string/String | null' is not assignable to type '~lib/string/String'.

   Console.log(home);
               ~~~~
 in assembly/index.ts(12,15)

FAILURE 1 compile error(s)
```

Expected behavior: compiles successfully.

This version compiles fine:

```
import "wasi";
import { Console, Environ } from "as-wasi";

let env = new Environ();
let home = env.get("HOME");

printIt(home);

function printIt( it :string|null) :void {
  if( it ) {
    Console.log(it)
  }
  else {
    Console.log("nada");
  }
}
```

So it seems nullability checks only work inside of functions. I don't know if this is expected behavior or not, but the docs make no mention of this caveat.

Thanks!

**Comment by MaxGraey** [comment]
just exclamation mark inside branch like:
```ts
if( home ) {
  Console.log(home!); // add "!"
}
```

It's well known issue

**Comment by teleclimber** [comment]
Sorry I failed to find an issue about this prior to filing this one. I'll close since it's apparently a dupe.
