### ISSUE TITLE
`offsetof` lacks type checking

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1846]
```ts
export class Result<O, E> implements Resultable<O, E> {
    private constructor(
        protected readonly _ok: O | null,
        protected readonly _err: E | null
    ) {}
}

 expect(offsetof<Result<i32, i8>>()).toBe(5); // ok
```

But we know that primitive type cannot be null.

**Comment by willemneal** [comment]
Strange this doesn't happen in the website [sandbox](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKLyoqIENhbGN1bGF0ZXMgdGhlIG4tdGggRmlib25hY2NpIG51bWJlci4gKi8KZXhwb3J0IGZ1bmN0aW9uIGZpYihuOiBpMzIpOiBpMzIgewogIHZhciBhID0gMCwgYiA9IDEKICBpZiAobiA+IDApIHsKICAgIHdoaWxlICgtLW4pIHsKICAgICAgbGV0IHQgPSBhICsgYgogICAgICBhID0gYgogICAgICBiID0gdAogICAgfQogICAgcmV0dXJuIGIKICB9CiAgcmV0dXJuIGEKfQppbnRlcmZhY2UgUmVzdWx0YWJsZTxPLCBFPiB7CiAgb2soKTogTyB8IG51bGw7CiAgZXJyKCk6IEUgfCBudWxsOwp9CgpjbGFzcyBSZXN1bHQ8TywgRT4gaW1wbGVtZW50cyBSZXN1bHRhYmxlPE8sIEU+ICB7CiAgICBwcml2YXRlIGNvbnN0cnVjdG9yKAogICAgICAgIHByb3RlY3RlZCByZWFkb25seSBfb2s6IE8gfCBudWxsLAogICAgICAgIHByb3RlY3RlZCByZWFkb25seSBfZXJyOiBFIHwgbnVsbAogICAgKSB7fQp9Cgphc3NlcnQob2Zmc2V0b2Y8UmVzdWx0PGkzMiwgaTg+PigpID09IDUsICI0ICsgMSA9IDUiKTsKIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQogICAgZm9yIChsZXQgaSA9IDA7IGkgPD0gMTA7ICsraSkgewogICAgICBvdXRwdXQudmFsdWUgKz0gYGZpYigke2l9KSA9ICR7ZXhwb3J0cy5maWIoaSl9XG5gCiAgICB9CiAgfSkKPC9zY3JpcHQ+).

**Comment by yjhmelody** [comment]
It's strange that it happen in test file.
