### ISSUE TITLE
Rounding issue with toString on f64 values 

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#1850]
This works as expected:

~~~
const fraction = f64(1 / 1_000_000_000);
log(fraction.toString()); 
// 0..000000001
~~~

Adding one also gives the expected result:

~~~
const fraction = f64(1 / 1_000_000_000);
log((1.0 + fraction).toString()); 
// 1..000000001
~~~

However, add a larger number, and the precision is lost:

~~~
const fraction = f64(1 / 1_000_000_000);
log((31622400.0 + fraction).toString()); 
// 31622400.0
~~~

**Comment by MaxGraey** [comment]
Checked in V8 and it return the same result:
```js
31622400.0 + 1 / 1_000_000_000; 
//  > 31622400.0
```

**Comment by MaxGraey** [comment]
I recommend article "What Every Computer Scientist Should Know About IEEE754": 
https://www.itu.dk/~sestoft/bachelor/IEEE754_article.pdf

**Comment by ColinEberhardt** [comment]
Oh yes, of course it's exceeded the floating point precision 🤦
