### ISSUE TITLE
a small bug in Math.round with some values between 2**52 and 2**53

### ISSUE THREAD

**Issue by Yaffle** [AssemblyScript/assemblyscript#1856]
`Math.round(2**53 - 1)` should return `2**53 - 1`

**Comment by MaxGraey** [comment]
Thanks! I created PR for this

**Comment by Yaffle** [comment]
@MaxGraey hi, I have tested all other math functions and found another small issue:
Math.acosh is not returning NaN for some negative values
Example:
Math.acosh(-9784.820766473835)

**Comment by MaxGraey** [comment]
@Yaffle Hmm, that's interesting. Basically AssemblyScript uses port of libm from musl. So pretty interesting how this handled by libmusl. `Math.acosh(-9784.820766473835)` should definitely a NaN

**Comment by MaxGraey** [comment]
btw some fix done for [floating point version](https://git.musl-libc.org/cgit/musl/commit/src/math?id=c4c38e6364323b6d83ba3428464e19987b981d7a) but not for double version
