### ISSUE TITLE
 Duplicate identifiers in function signature is considered valid code

### ISSUE THREAD

**Issue by saulecabrera** [AssemblyScript/assemblyscript#1864]
The following should not compile 

```ts
function id<T>(a: T, a: T): T {
  return a;
}

export const a = id<i32>(1, 2);
```

**Expected**
Duplicate identifier 'a'

**Actual**
Compiles successfully.

**Comment by willemneal** [comment]
Out of curiosity what does it return?

**Comment by saulecabrera** [comment]
The last param will override any of the previous ones, in this case, it returns 2.
