### ISSUE TITLE
asc does not play nice with the .as file extension

### ISSUE THREAD

**Issue by wrnrlr** [AssemblyScript/assemblyscript#1866]
When I use `.as` instead of `.ts` the `asc` tool fails to find the correct file

    asc assembly/index.as --target debug
    ERROR TS6054: File 'assembly/index.as.ts' not found.

    asc assembly/index --target debug
    ERROR TS6054: File 'assembly/index.ts' not found.

**Comment by wrnrlr** [comment]
The main reason I use `.as` is to avoid confusing vs code.

I tried a workaround with just adding the `.ts` extension to the  index file, but it turns out `asc` has the same behaviour when importing other files:

    asc assembly/index.ts --target debug
    ERROR TS6054: File 'assembly/gunn.as.ts' not found.
    
    import {Plane,plane} from './gunn.as'
                           ~~~~~~~~~~~
    in assembly/index.ts(3,27)

**Comment by wrnrlr** [comment]
IMMO, I think it is a mistake to use magic import rules instead assembly script should follow esm convention.
This should also make it possible to import urls like Deno

**Comment by MaxGraey** [comment]
did you try add `--extension as` to asc or `"extension": "as"` in asconfig.json?

**Comment by wrnrlr** [comment]
Yes you are right, I missed that option. Thx for your help!
