### ISSUE TITLE
How to define a function with variable number of parameters in AS?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1868]
I find that such as Array.map can pass variable number params:
```ts
  map<U>(fn: (value: T, index: i32, array: Array<T>) => U): Array<U> {
    var length = this.length_;
    var out = changetype<Array<U>>(__newArray(length, alignof<U>(), idof<Array<U>>()));
    var outStart = out.dataStart;
    for (let index = 0; index < min(length, this.length_); ++index) {
      let result = fn(load<T>(this.dataStart + (<usize>index << alignof<T>())), index, this);
      store<U>(outStart + (<usize>index << alignof<U>()), result);
      if (isManaged<U>()) {
        __link(changetype<usize>(out), changetype<usize>(result), true);
      }
    }
    return out;
  }
```

The function that map accepts is ordinary ternary function, but why can it be possible to pass only part of the parameters?

**Comment by dcodeIO** [comment]
When `map` is called with a function expression like

```ts
someArray.map(value => { ... })
```

what the compiler will have to do is to compile the function expression `value => { ... }` that is being passed to it, but before doing so it looks at the contextual type in this place, which is `(value: T, index: i32, array: Array<T>) => U`. In this particular case, the given function has less arguments, but it is trivial to amend it, which is what the compiler does to make this more convenient. That then looks like only passing part of the parameters, while the function expression actually compiled with two unused dummy parameters.

Does that answer your question? :)

**Comment by yjhmelody** [comment]
👌, I close it
