### ISSUE TITLE
Is it possible to add a hook `beforeOutput` to transform?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1873]
Is it possible to add a hook `beforeOutput` to transform?
Here we can get the file to be output (mainly wasm), where the user can call some tools such as wasm-opt to optimize again, or need to generate a metadata file, and metadata depends on wasm information, such as the hash value of wasm

**Comment by willemneal** [comment]
Would [`afterCompile`](https://github.com/AssemblyScript/assemblyscript/blob/5427eb9cf7cc165e87c50b3b656b321e1ac25b6e/cli/transform.d.ts#L42) work?  It returns the binaryen module which should include the necessary interface to do as you describe.
https://github.com/AssemblyScript/assemblyscript/blob/5427eb9cf7cc165e87c50b3b656b321e1ac25b6e/cli/transform.d.ts#L42

You'll need to do no optimization in CLI and add no passes.  Then you can perform the passes and optimization yourself in the transform and then emit the binary for the hash data and used `addCustomSection`.

**Comment by yjhmelody** [comment]
> Would [`afterCompile`](https://github.com/AssemblyScript/assemblyscript/blob/5427eb9cf7cc165e87c50b3b656b321e1ac25b6e/cli/transform.d.ts#L42) work? It returns the binaryen module which should include the necessary interface to do as you describe.
> https://github.com/AssemblyScript/assemblyscript/blob/5427eb9cf7cc165e87c50b3b656b321e1ac25b6e/cli/transform.d.ts#L42
> 
> You'll need to do no optimization in CLI and add no passes. Then you can perform the passes and optimization yourself in the transform and then emit the binary for the hash data and used `addCustomSection`.

Sorry, this does not meet my needs.

**Comment by willemneal** [comment]
> Here we can get the file to be output (mainly wasm), 

> where the user can call some tools such as wasm-opt to optimize again, 
The passes used in CLI are applied to the binaryen `module` before the `afterCompile` hook.  So you can do it again here.

> or need to generate a metadata file, and metadata depends on wasm information, such as the hash value of wasm
You can emit the module to bytes and get all the information.  

This is wasteful full since the asc is going to do it again, so perhaps the new hook should be `beforeEmit`, Which passes the type to be emitted and expects that to be returned.

**Comment by MaxGraey** [comment]
> Here we can get the file to be output (mainly wasm), where the user can call some tools such as wasm-opt to optimize again

AssemblyScript uses binaryen. wasm-opt also uses binaryen so it's simply unnecessary do `wasm-opt`. If you required some extra passes you could add `--converge` flag (will apply optimize until fixpoint). Or add some custom / extra passes via `--runPasses` flags

**Comment by yjhmelody** [comment]
> AssemblyScript uses binaryen. wasm-opt also uses binaryen so it's simply unnecessary do `wasm-opt`. If you required some extra passes you could add `--converge` flag (will apply optimize until fixpoint). Or add some custom / extra passes via `--runPasses` flags

This is just one of the points. Some information generated by my transform depends on the wasm code

**Comment by yjhmelody** [comment]
> This is wasteful since the asc is going to do it again, so perhaps the new hook should be beforeEmit, Which passes the type to be emitted and expects that to be returned.
@MaxGraey Hi, Can we add a `beforeEmit` hook. asc do lots of things after `afterCompile`, we still cannot obtain the final generated files.
