### ISSUE TITLE
[Feature Request] Built in to make a type non-nullable

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#1874]
[Consider the following example:](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKLyoqIENhbGN1bGF0ZXMgdGhlIG4tdGggRmlib25hY2NpIG51bWJlci4gKi8KZXhwb3J0IGZ1bmN0aW9uIGZpYihuOiBpMzIpOiBpMzIgewogIHZhciBhID0gMCwgYiA9IDEKICBpZiAobiA+IDApIHsKICAgIHdoaWxlICgtLW4pIHsKICAgICAgbGV0IHQgPSBhICsgYgogICAgICBhID0gYgogICAgICBiID0gdAogICAgfQogICAgcmV0dXJuIGIKICB9CiAgcmV0dXJuIGEKfQoKZnVuY3Rpb24gdGFrZXNHZW5lcmljPFQ+KHQ6IFQpOiB2b2lkIHsKICBpZiAoIWlzTnVsbGFibGU8VD4oKSB8fCB0ICE9IG51bGwpewogICAgICAvLyBAdHMtaWdub3JlCiAgICAgIGlmICAoaXNEZWZpbmVkKHQuY2FsbCkpewogICAgICAgIHQuY2FsbCgpCiAgICAgIH0KICAgIH0KfQoKZnVuY3Rpb24gY2FsbHNHZW5lcmljPFQ+KHQ6IFQpOiB2b2lkIHsKICBpZiAodCAhPSBudWxsKSB7CiAgICB0YWtlc0dlbmVyaWModCk7CiAgfQp9CgpjbGFzcyBUZWUgewogIGNhbGwoKTogdm9pZCB7CiAgICBsZXQgeDogaTggPSAwOwogIH0KfQoKbGV0IHk6IFRlZSB8IG51bGwgPSBuZXcgVGVlKCk7CgpjYWxsc0dlbmVyaWMoeSk7CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==)

```ts

function takesGeneric<T>(t: T): void {
  if (!isNullable<T>() || t != null){
      // @ts-ignore
      if  (isDefined(t.call)){
        t.call()
      }
    }
}

function callsGeneric<T>(t: T): void {
  if (t != null) {
    takesGeneric(t); // Would be nice to have a `notNull<T>` here
  }
}

class Tee {
  call(): void {
    let x: i8 = 0;
  }
}

let y: Tee | null = new Tee();

callsGeneric(y);
```

The type passed to `takesGeneric` is no longer nullable since it's guaranteed to not be null. However, the type passed doesn't reflect this.  A quick fix to this could be to add a new builtin that converts a `type | null` to `type`.  Or in branches where the type is non-null this happens automatically.

**Comment by MaxGraey** [comment]
typescript has type utility called `NotNullable<T>` for that
