### ISSUE TITLE
In the afterCompile phase, can I get all types of information used by a class recursively?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1878]
In the afterCompile phase, can I get all types of information used by a class recursively? If so, what to do, I am confused about Prototype and Non-Prototype Element

**Comment by dcodeIO** [comment]
A prototype is a description of a class that has not yet been resolved, while an instance of a class represents a concrete resolved class. When the goal is to obtain types used during compilation, one will want to iterate over all instances of a class. To give an example, if you have a class `Foo<T>`, then `Foo<T>` is the prototype, while `Foo<i32>` and `Foo<f64>` would be two concrete instances. The same is true if the prototype is not generic, say `Bar`, that then would have a single instance `Bar`. Does this help? :)

**Comment by yjhmelody** [comment]
Yes it is. But it is still not clear how to get all the specific types used by an instance class (including fields and function signatures)

**Comment by dcodeIO** [comment]
Information available in a `Class`, that is not available in their `ClassPrototype` `prototype` include:

* The `base` class, which is again a `Class`
* Implemented `interfaces`, which are again `Interface`s (similar to `Class`)
* Concrete `typeArguments`
* Concrete `members`, including `Field`s, `Function`s (methods) and `Property`s, with their types

A similar distinction exists for resolved `Function`s, which have a `FunctionPrototype` as their `prototype`:

* Concrete `typeArguments`
* Concrete `signature` with `thisType`, if any, `parameterTypes` and `returnType`

These are the most notable ones, but anything else that has a `*Prototype` works similarly.

**Comment by yjhmelody** [comment]
Thanks, i'll try
