### ISSUE TITLE
Breakpoints not available in all parts of code.

### ISSUE THREAD

**Issue by damilolarandolph** [AssemblyScript/assemblyscript#1881]
I am unable to set breakpoints in some parts of my code in debug mode. The source maps are generated and allows me to view the Assemblyscript files in Firefox or Chrome Dev-tools. Though only some parts of source can have breakpoints set.  
Though I have noticed most of the de-compiled web assembly can have breakpoints set.

**Comment by dcodeIO** [comment]
It may be that parts of the source do not trivially map to instructions. For instance, some dead branches are eliminated during compilation so may not have corresponding instructions. Just guessing, though. Can you provide a side-by-side example where it doesn't work?

**Comment by damilolarandolph** [comment]
For an example, I have a function called initARM that places functions in an array. 
![image](https://user-images.githubusercontent.com/43427949/120535075-15218980-c3d2-11eb-8e04-b39975008021.png)
As you can see the numbers are greyed out meaning I can't set breakpoints.

But I can set breakpoints in the imports its assigning to the array 
![image](https://user-images.githubusercontent.com/43427949/120535771-e821a680-c3d2-11eb-8856-e2a619874e8e.png)

This is the exported AND function which is used in the initARM funciton.

**Comment by MaxGraey** [comment]
You can't breakpoint to locals with sourcemaps as I know. For such feature host and language should support DWARF which is not yet support

**Comment by damilolarandolph** [comment]
> You can't breakpoint to locals with sourcemaps as I know. For such feature host and language should support DWARF which is not yet support

Sorry could you explain further ? I don't get it.

**Comment by damilolarandolph** [comment]
> You can't breakpoint to locals with sourcemaps as I know. For such feature host and language should support DWARF which is not yet support

Sorry could you explain further ? I don't get it.

**Comment by damilolarandolph** [comment]
UPDATE: Switching the runtime to stub allows fixes the issue.
