### ISSUE TITLE
A couple questions about how Heap (Page) memory

### ISSUE THREAD

**Issue by AfflatusX** [AssemblyScript/assemblyscript#1884]
Hi - I'm trying to understand how my AS app is consuming the page memory assigned to it (64KB). My WASM app ran out of memory after allocating a couple killobytes (definitely far away from 64KB, it ran out of memory because this is an embedded device with very limited memory).

Two questions - 

1. what uses that 64KB memory? Is it similar to C heap (new ops -> malloc -> heap)?
2. Is there any way to trace memory usage? Something simple as returning remaining memory space in the heap would work.

Thanks in advance!

**Comment by dcodeIO** [comment]
The memory layout is described in [some detail in the docs](https://www.assemblyscript.org/memory.html#memory-regions). It's very similar to C, with static memory upfront, then a shadow stack when using the incremental runtime, which is then followed by the heap.

In memory-restrained environments, it is typically good to either use the `minimal` or `stub` runtimes to avoid space for the shadow stack, or when using `incremental`, to reduce its size using `--stackSize`. Of course, depending on the program, it may be challenging to make best use of the heap when restrained, and I would also note that AS has not been tested a lot in these scenarios, so there is most likely something to improve. In particular, the `incremental` runtime has a heuristic on when the GC kicks in that may not be ideal yet if the limit is very low. There are ways to [tweak the heuristic](https://github.com/AssemblyScript/assemblyscript/tree/main/std/assembly/rt#itcms----runtime-incremental), though, and I'd certainly be interested in the results :)

**Comment by AfflatusX** [comment]
Thanks for the detailed answer!

I ended up forking the project and modified rtrace.ts a little bit so it calls into my native code to handle the tracing. Right now rtrace seems to be passing BLOCK around, which isn't supported by our native binding and runtime.

We're already using minimal. Overall the learnings are:

1. managed class has 16bytes overhead compared to @unmanaged. So we can move things to unmanaged and manually free them for hot objects.
2. in some big loop memory gets allocated but GC doesn't have a chance to recycle, we added a hook when it tries to get more page to run GC first.
3. Looks like the memory manager ran out of blocks before the allocated bytes goes to 64KB. Also, BLOCK size is higher than the actual memory needed to be allocated.

That being said, this is quite amazing how much insights we can get from tracing stuff and really understand how the runtime works.

**Comment by dcodeIO** [comment]
When using the minimal runtime, there is no shadow stack, so when a collection is invoked, objects that are currently "in flight" (on Wasm's execution stack) cannot be marked, which will likely lead to the GC prematurely collecting some objects. The incremental runtime's shadow stack accounts for this, so the GC can run interleaved with the program. In minimal, collection can be invoked whenever there is no managed object on the execution stack, and I typically recommend to call it externally, but it is of course possible to do it in Wasm when being very careful to only do so in exports that are not in turn reached from Wasm. To give a clumsy example:

```ts
function bar(b: string): void {
  // here it's never safe to call collect
}
export function foo(a: string): void {
  // a is on the shadow stack
  bar(a); // b is on the shadow stack
  // here it's safe to assume that the stack is unwound, so collect can be called
  // but only if it is guaranteed that a is the only item on the stack, i.e. foo is not
  // called via baz
}
export function baz(a: string, b: string): void {
  foo(a);
}
```

And yeah, it is expected that there is some fragmentation, and then of course there is also space reserved for static data in front. Note that when optimizing, we also reserve the low 1024b for certain optimizations (lowMemoryUnused in Binaryen, can be disabled with `--memoryBase 0` iirc). Block overhead is 4 bytes, while managed object overhead adds another 16 bytes. Some [docs here](https://github.com/AssemblyScript/assemblyscript/blob/main/std/assembly/rt/common.ts#L48).
