### ISSUE TITLE
Cannot emit DiagnosticCode by `program` in `afterCompile`

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1886]
Hi, I did some information gathering work at this stage, but I can’t print the DiagnosticCode here anymore

**Comment by dcodeIO** [comment]
If I understand correctly, what would be necessary is to add another round of `checkDiagnostics` somewhere below

https://github.com/AssemblyScript/assemblyscript/blob/8a280c4a0ddfb0de6de65fc86c1b04a6a7425f78/cli/asc.js#L861-L865

**Comment by yjhmelody** [comment]
Should we do independent checkDiagnostics for hooks?
Evenshould  we do a separate check for each hook method in applyTransform ?

**Comment by dcodeIO** [comment]
Hmm, I guess ideally we'd have a callback of sorts to print the diagnostic immediately when it is produced, so even if stuff explodes we still have it printed, it's just that this wouldn't play well with the compiler compiled to Wasm right now. But yeah, the more granular this is the less friction we'll have, so I'd be fine with checking after each hook method even.

**Comment by dcodeIO** [comment]
Seems to be solved by the PR, but let me know if there are further issues.
