### ISSUE TITLE
Memory leak when using Array and Map

### ISSUE THREAD

**Issue by AfflatusX** [AssemblyScript/assemblyscript#1887]
consider following code:

```ts
map.set(1, []);
map.get(1).push(2);
map.clear()
```

this leaks about 32 bytes every time this code executes (with explict GC after the call).

However, changing it to:

```ts
const arr: number[] = [];
map.set(1, arr);
map.get(1).push(2);
map.clear()
```

fixed the leak.

ver 0.18.32, using minimal runtime

**Comment by dcodeIO** [comment]
I could need some more information here, like surrounding code for context, and how you detect the leak etc.

**Comment by AfflatusX** [comment]
sure - 

in index.ts:

const map: Map<i32, i32[]> = new Map();

function loop(): void {
  map.set(1, []);
  map.get(1).push(2);
  map.clear()
}

function tick(): void {
  setInterval(() => { 
    loop(); 
    GCAsync();
  }, 1000);
}

on_init() {
  tick();
}


set interval is uses a native timer ( in C code ) that calls back into WASM space every 1 sec.
GCAsync() also uses the native timer to call __collect() after 100ms

I'm doing this to make sure the GC is triggered from host and does not collide with the loop itself.


To measure - I added hook into tlsf.ts to track every alloc and free.

In the leaking version, every loop run increases the total alloc by 32 bytes, in the other version the total malloc bytes stays constant after each tick.

**Comment by dcodeIO** [comment]
How does the respective other code look in full?

**Comment by AfflatusX** [comment]
you mean the native C timer code? I'm using https://github.com/bytecodealliance/wasm-micro-runtime so it's hard to describe lol

**Comment by AfflatusX** [comment]
for GCAsync - 

`function GCAsync() {
  setTimeout(() => { __collect() }, 100);
}`

I checked the log, the tick and gc does kick in at corresponding time.

**Comment by dcodeIO** [comment]
I would expect the current `loop` function to alloc a new empty array (via `[]`) whenever it runs, and that'd be the 32 bytes. Mostly wondering where the `const arr: number[] = [];` would go, since behavior may differ depending on code location.

**Comment by AfflatusX** [comment]
Ah i see - 

`
function loop(): void {
  const arr: number[] = [];
  map.set(1, arr);
  map.get(1).push(2);
  map.clear()
}

`

like this.

**Comment by dcodeIO** [comment]
And this one does no allocation at all?

**Comment by AfflatusX** [comment]
it does allocation, but after GC it gets freed properly.

**Comment by dcodeIO** [comment]
Hmm, would need to check. My intuition so far tells me that this is most likely a false alarm, since allocations that are not referenced anymore should become collected in any case, but that's just my intuition and it's perfectly possible that I'm wrong.

**Comment by AfflatusX** [comment]
Yeah - both of them should behave the same way. Let me know if you can reproduce this.

**Comment by MaxGraey** [comment]
I guess when you define `map.set(1, []);` array alloc in data static section instead heap. That's may a reason why it doesn't collected

**Comment by AfflatusX** [comment]
> I guess when you define `map.set(1, []);` array alloc in data static section instead of heap. That's may a reason why it doesn't collected

Hmm but it gets reported by allocBlock() in tlsf ?

**Comment by AfflatusX** [comment]
I played a little bit more and looks like the "proper" fix is avoid using [] - always do new Array(). The second snippet works but not always (depends on the context I guess)

**Comment by jtenner** [comment]
Attaching the array to the shadow stack via a local fixes the issue. @dcodeIO perhaps array literals aren't being handled correctly with gc?

**Comment by dcodeIO** [comment]
Had this thought as well, but it's the minimal runtime here without a shadow stack. So whatever is not referenced anymore, say from `map`, should be aggressively collected anyhow.

**Comment by jtenner** [comment]
I didn't see that. Yep.
