### ISSUE TITLE
demo project assemblyscript compiller has crashed during initialize

### ISSUE THREAD

**Issue by vbalko** [AssemblyScript/assemblyscript#1888]
I created demo project using instructions on page near.org using npx

then changed direcotry to project one
installed using yarn install
then yarn dev

And then I got this log. I didnt changed sources - neither touched them.

yarn run v1.22.4
$ nodemon --watch contract -e ts --exec "npm run start"
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): contract\**\*
[nodemon] watching extensions: ts
[nodemon] starting `npm run start`

> casper.near@0.0.1 prestart
> npm run build:contract:debug && npm run dev:deploy:contract

> casper.near@0.0.1 build:contract:debug
> node contract/compile.js --debug

> greeter@0.0.1 build:debug
> asb --target debug

▌ Whoops, the AssemblyScript compiler has crashed during initialize :-(
▌
▌ Here is a stack trace that may or may not be useful:
▌
▌ AssertionError: assertion failed
▌     at i.assert (D:\Development\!workspace\!private\near\casper.near\contract\node_modules\assemblyscript\dist\assemblyscript.js:7:737201)
▌     at E.initialize (D:\Development\!workspace\!private\near\casper.near\contract\node_modules\assemblyscript\dist\assemblyscript.js:7:592660)
▌     at Object.t.initializeProgram (D:\Development\!workspace\!private\near\casper.near\contract\node_modules\assemblyscript\dist\assemblyscript.js:7:435441)
▌     at D:\Development\!workspace\!private\near\casper.near\contract\node_modules\assemblyscript\cli\asc.js:817:22
▌     at measure (D:\Development\!workspace\!private\near\casper.near\contract\node_modules\assemblyscript\cli\asc.js:1331:3)
▌     at Object.main (D:\Development\!workspace\!private\near\casper.near\contract\node_modules\assemblyscript\cli\asc.js:815:27)
▌     at compileProject (D:\Development\!workspace\!private\near\casper.near\contract\node_modules\asbuild\dist\commands\build.js:206:9)
▌     at Object.handler (D:\Development\!workspace\!private\near\casper.near\contract\node_modules\asbuild\dist\commands\build.js:107:13)
▌     at Object.runCommand (D:\Development\!workspace\!private\near\casper.near\contract\node_modules\asbuild\node_modules\yargs\build\lib\command.js:196:48)
▌     at Object.parseArgs [as _parseArgs] (D:\Development\!workspace\!private\near\casper.near\contract\node_modules\asbuild\node_modules\yargs\build\lib\yargs.js:1071:43)
▌
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!

[nodemon] app crashed - waiting for file changes before starting...

**Comment by dcodeIO** [comment]
cc @willemneal Some idea what may be happening there?

**Comment by willemneal** [comment]
What version of node are you using?
