### ISSUE TITLE
How to encode number to LEB128 in AS ?

### ISSUE THREAD

**Issue by xiong-pro** [AssemblyScript/assemblyscript#1890]
Hi, I'm trying to encode number to [LEB128](https://en.wikipedia.org/wiki/LEB128) in AssemblyScript.

I have found some libraries, but it seems just work in javascript.
- [@webassemblyjs/leb128](https://www.npmjs.com/package/@webassemblyjs/leb128)
- [wasm-leb128](https://www.npmjs.com/package/wasm-leb128)

Is there any good way to encode/decode LEB128 in AS self ?

**Comment by dcodeIO** [comment]
Perhaps helpful: https://github.com/AssemblyScript/assemblyscript/blob/f3546784ed7dcf2480a7793df4e8d8503af35fb8/lib/parse/assembly/index.ts#L34-L78

**Comment by xiong-pro** [comment]
@dcodeIO Thanks,

- Are these methods decoding LEB-128 to number from memory ?
- But how to encode number to LEB-128 then store to memory ?

thanks again.

**Comment by dcodeIO** [comment]
These are decoding routines, yes. Likewise, the encoding routines would also work in AS, of course.

**Comment by xiong-pro** [comment]
@dcodeIO Thanks for reply, I'm going to do it by myself. 🤣
