### ISSUE TITLE
How to call explicit start function in AS code ?

### ISSUE THREAD

**Issue by xiong-pro** [AssemblyScript/assemblyscript#1892]
Hi, I write some AS code, and compile it to wasm code. (of course)

Then, I use a wasm virtual machine (which maintained by my company) to run it, but it throw error [VM_MEMORY_OUT_OF_BOUNDS]. 😢

Then, I found the reason: **The VM didn't call the explicit start function upon instantiation.**

Then, I use the compile option `--explicitStart` to export the explicit start function, but it still needs the VM to call  the `exports._start` function, but they said can't do it. 🤣

My question: **Can I call the explicit start function directly in my AS code ?**

### Thanks very much !!!

**Comment by xiong-pro** [comment]
@dcodeIO Thanks for reply. If I compile without this option, the explicit start function will auto execute (in normal case), **but "my company's vm" do not auto execute it** ... 😭

**Comment by dcodeIO** [comment]
If the VM cannot execute either an implicit or an explicit start, and if one cannot manually call `_start` before any other exports, that'd be quite a strange setup I think :)

**Comment by xiong-pro** [comment]
@dcodeIO ok, thanks a lot, I will try to communicate more with our VM team. 😢

**Comment by willemneal** [comment]
Having a start section is part of the Wasm standard, so it's strange that if one is present that function isn't run as part of the initialization.

**Comment by MaxGraey** [comment]
It's probably wagon runtime which not maintained and very outdated for compatibility with Wasm spec

**Comment by xiong-pro** [comment]
@willemneal @MaxGraey Thanks for reply, our VM is customized for blockchain (maybe a reason for that).

Since I'm actually a new hand to wasm, and blockchain (smart contracts), I will try to communicate and study more. If there is any progress, I will reply to this issue. Thanks again! 😄
