### ISSUE TITLE
Assertions of conditions not applied during compilation

### ISSUE THREAD

**Issue by negue** [AssemblyScript/assemblyscript#1893]
Firstly - sorry if its the wrong title since I don't know if its even the right term to describe that issue / feature request?

Something like this would work in typescript itself & is allowed by the language service since its valid typescript, but when I try to compile this in assemblyscript without the type cast, it fails:

```ts
if (mapValue != null) {
      if (mapValue instanceof StringMapValue) {
        // doesn't compile without a cast, even by the two checks it should be clear that mapValue is a StringMapValue
        const theStringValue = ( /* <StringMapValue> */ mapValue).value;
        

        functionTodoStuff(key, theStringValue);
        // do something, just an example
      }
    }
```

Issue:
```
ERROR TS2339: Property 'value' does not exist on type 'assembly/index/MapValue'.

         const theStringValue = ( /* <StringMapValue> */ mapValue).value;
                                                                   ~~~~~
 in assembly/index.ts(31,67)

ERROR TS2322: Type 'i32' is not assignable to type '~lib/string/String'.

         functionTodoStuff(key, theStringValue);
                                ~~~~~~~~~~~~~~
 in assembly/index.ts(34,32)
```

I don't know if its a known issue - since also couldn't find anything on the github issues  (maybe also because of not knowing the right term for that)

Full example code https://gist.github.com/negue/19de2ab8183ca37f88d6c2b4c403a06a

**Comment by MaxGraey** [comment]
type guards doesn't support yet. Workaround:
```ts
if (mapValue instanceof StringMapValue) {
  const theStringValue = (mapValue as StringMapValue).value;
}
```

**Comment by negue** [comment]
> type guards doesn't support yet.

oh those would be also called type guards? I see thanks for the clarification  👍 

should I rename the current title to it ? or is there an existing issue for that already ?

---

And yes with the explicit casting it works out.

I guess `Assertion Functions` (which are also a type of a guard?) wouldn't work in assemblyscript either, right ?

**Comment by negue** [comment]
I think this issue can be closed, I'd just like to know if those typeguards are planned (whenever that will be).

Cause this feature would help to save a lot of verbose code :)
