### ISSUE TITLE
How to export function by global syntax ?

### ISSUE THREAD

**Issue by xiong-pro** [AssemblyScript/assemblyscript#1896]
index.ts (entry file)

```
export const apply = (): void => {
  // do something ...
}
```

It will be compiled to (wat file)

```
(export "apply" (global $contract/index/apply))
```

Can see, it's a global, but not a function.

---

My question:

**Can I use global syntax to export a function ?**

(maybe a stupid question, sorry) 🤣

**Comment by MaxGraey** [comment]
It's normal and expected behaviour for expression defined functions. But I agree this may be improvement and store to global only when it pass by name.
