### ISSUE TITLE
Holy to packed array problem

### ISSUE THREAD

**Issue by I-dodo** [AssemblyScript/assemblyscript#1907]
Hello there, I am trying to convert a holy array to a packed array, but this doesn't work...
I already know the array is packed, but when I use a map, it makes it a holy array
```bash
C:\...\node_modules\@assemblyscript\loader\umd\index.js:78
      throw Error(`abort: ${getString(memory, msg)} at ${getString(memory, file)}:${line}:${colm}`);
            ^
Error: abort: Element type must be nullable if array is holey at ~lib/array.ts:103:40
    at abort (C:\...\node_modules\@assemblyscript\loader\umd\index.js:78:13)
    at ~lib/array/Array<~lib/string/String>#__get (wasm://wasm/00028782:0:19225)
    at assembly/data-types/string-pointers/MakePackArray<~lib/string/String> (wasm://wasm/00028782:0:13367)
```
The code is quite simple, but I didn't catch what the error is...
```ts
function MakePackArray<T>(array: T[]): T[]{
    const a: Array<T> = new Array<T>(array.length);
    for (let i = 0; i < array.length; i++){
        const e: T | null = array[i];
        if(e != null)
            a[i] = array[i];
    }
    return a;
}
....
array.map<string[]>(x => MakePackArray(x.mainArray)
```
I also tried to use a filter, but I got `memory access out of bounds`
```ts
function MakePackArray<T>(array: T[]): T[]{
    return array.filter(x => x != null);
}
```
```bash
RuntimeError: memory access out of bounds
    at ~lib/rt/itcms/Object#get:color (wasm://wasm/00029fbe:0:1566)
    at ~lib/rt/itcms/__link (wasm://wasm/00029fbe:0:1968)
```
Does someone know what the problem might be?

**Comment by MaxGraey** [comment]
First example is wrong. It doesn't do what you expect.
Second approach (filter) is correct and should work. See [playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmZ1bmN0aW9uIE1ha2VQYWNrQXJyYXk8VD4oYXJyOiBUW10pOiBUW117CiAgcmV0dXJuIGFyci5maWx0ZXIoeCA9PiB4ICE9IG51bGwpOwp9Cgpjb25zdCBhcnI6IChzdHJpbmcgfCBudWxsKVtdID0gWydhJywgbnVsbCwgJ2InLCAnYycsIG51bGwsICdkJ107CgpleHBvcnQgZnVuY3Rpb24gdGVzdCgpOiBpMzIgewogIHJldHVybiBNYWtlUGFja0FycmF5KGFycikubGVuZ3RoOyAvLyBleHBlY3QgNAp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIG91dHB1dC52YWx1ZSArPSBgdGVzdCgpOiBhY3R1YWwgJHtleHBvcnRzLnRlc3QoKX0sIGV4cGVjdDogNFxuYAogIH0pCjwvc2NyaXB0Pg==)

Could you provide more context for second approach? Because I can't reproduce it

**Comment by I-dodo** [comment]
I tried to provide a similar context, but the filter approach doesn't work as I expect either...
*[Example](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCm5hbWVzcGFjZSBjb25zb2xlIHsKICAgIGRlY2xhcmUgZnVuY3Rpb24gbG9nKHN0cjogc3RyaW5nKTogdm9pZDsKfQoKZnVuY3Rpb24gTWFrZVBhY2tBcnJheTxUPihhcnJheTogVFtdKTogVFtdIHsKICAgIGFycmF5ID0gYXJyYXkuZmlsdGVyKHggPT4geCAhPSBudWxsKTsKCiAgICBpZihBcnJheS5pc0FycmF5KGFycmF5KSl7CiAgICAgIGNvbnNvbGUubG9nKGFycmF5LnRvU3RyaW5nKCkpCiAgICB9CgogICAgLy8jIHRoaXMgY3VzZWluZyBhIGVycm9yLCBidXQgd2h5PwogICAgZm9yIChsZXQgaSA9IDA7IGkgPCBhcnJheS5sZW5ndGg7IGkrKykgeyAKICAgICAgICBjb25zdCBlOiBUID0gYXJyYXlbaV07IC8vdGhpcyBjdXNlaW5nIGEgZXJyb3IKICAgICAgICBjb25zb2xlLmxvZygodHlwZW9mIGUgPT0gJ251bWJlcicpLnRvU3RyaW5nKCkpOwogICAgfQoKICAgIHJldHVybiBhcnJheTsKfQoKY2xhc3MgVG9NYXAgewogICAgcHVibGljIGFycmF5OiBzdHJpbmdbXSA9IG5ldyBBcnJheTxzdHJpbmc+KDIpOwogICAgY29uc3RydWN0b3IoKSB7CiAgICAgICAgdGhpcy5hcnJheVswXSA9ICJmaXJzdCI7CiAgICAgICAgdGhpcy5hcnJheVsyXSA9ICJzZWNvbmQiOwogICAgfQp9Cgpjb25zdCBhcnI6IFRvTWFwW10gPSBbbmV3IFRvTWFwKCksIG5ldyBUb01hcCgpXTsKCmV4cG9ydCBmdW5jdGlvbiB0ZXN0KCk6IGkzMiB7CiAgICByZXR1cm4gTWFrZVBhY2tBcnJheShhcnIubWFwPHN0cmluZ1tdPih4ID0+IE1ha2VQYWNrQXJyYXkoeC5hcnJheSkpKS5sZW5ndGg7IC8vIGV4cGVjdCAyCn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpOwpsZXQgY29weUV4cG9ydHM7CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAKICBtb2R1bGU6IHsKICAgICAgImNvbnNvbGUubG9nIihwdHIpIHsKICAgICAgICBjb25zdCB2YWx1ZSA9IGNvcHlFeHBvcnRzLl9fZ2V0U3RyaW5nKHB0cik7CgogICAgICAgIGNvbnNvbGUubG9nKHZhbHVlKTsKICAgICAgfQogIH0KIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb3B5RXhwb3J0cyA9IGV4cG9ydHM7CiAgICBvdXRwdXQudmFsdWUgKz0gYHRlc3QoKTogYWN0dWFsICR7ZXhwb3J0cy50ZXN0KCl9LCBleHBlY3Q6IDRcbmAKICB9KQo8L3NjcmlwdD4=)*

*Comment this part, if I want some output...
```ts
  for (let i = 0; i < array.length; i++) { 
      const e = array[i]; // this cuseing a error, but why?
      console.log((typeof e == 'number').toString())
  }
```

**Comment by MaxGraey** [comment]
This part will produce OOB:
```ts
class ToMap {
    public array: string[] = new Array<string>(2);
    constructor() {
        this.array[0] = "first";
        this.array[2] = "second"; // <- here
    }
}
```

**Comment by MaxGraey** [comment]
and after fix this. Everything [works as expected](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCm5hbWVzcGFjZSBjb25zb2xlIHsKICAgIGRlY2xhcmUgZnVuY3Rpb24gbG9nKHN0cjogc3RyaW5nKTogdm9pZDsKfQoKZnVuY3Rpb24gTWFrZVBhY2tBcnJheTxUPihhcnJheTogVFtdKTogVFtdIHsKICAgIGFycmF5ID0gYXJyYXkuZmlsdGVyKHggPT4geCAhPSBudWxsKTsKCiAgICBpZihBcnJheS5pc0FycmF5KGFycmF5KSl7CiAgICAgIGNvbnNvbGUubG9nKGFycmF5LnRvU3RyaW5nKCkpCiAgICB9CgogICAgLy8jIHRoaXMgY3VzZWluZyBhIGVycm9yLCBidXQgd2h5PwogICAgZm9yIChsZXQgaSA9IDA7IGkgPCBhcnJheS5sZW5ndGg7IGkrKykgeyAKICAgICAgICBjb25zdCBlOiBUID0gYXJyYXlbaV07IC8vdGhpcyBjdXNlaW5nIGEgZXJyb3IKICAgICAgICBjb25zb2xlLmxvZygodHlwZW9mIGUgPT0gJ251bWJlcicpLnRvU3RyaW5nKCkpOwogICAgfQoKICAgIHJldHVybiBhcnJheTsKfQoKY2xhc3MgVG9NYXAgewogICAgcHVibGljIGFycmF5OiBzdHJpbmdbXSA9IG5ldyBBcnJheTxzdHJpbmc+KDIpOwogICAgY29uc3RydWN0b3IoKSB7CiAgICAgICAgdGhpcy5hcnJheVswXSA9ICJmaXJzdCI7CiAgICAgICAgdGhpcy5hcnJheVsyXSA9ICJzZWNvbmQiOwogICAgfQp9Cgpjb25zdCBhcnI6IFRvTWFwW10gPSBbbmV3IFRvTWFwKCksIG5ldyBUb01hcCgpXTsKCmV4cG9ydCBmdW5jdGlvbiB0ZXN0KCk6IGkzMiB7CiAgICByZXR1cm4gTWFrZVBhY2tBcnJheShhcnIubWFwPHN0cmluZ1tdPih4ID0+IE1ha2VQYWNrQXJyYXkoeC5hcnJheSkpKS5sZW5ndGg7IC8vIGV4cGVjdCAyCn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpOwpsZXQgY29weUV4cG9ydHM7CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAKICBtb2R1bGU6IHsKICAgICAgImNvbnNvbGUubG9nIihwdHIpIHsKICAgICAgICBjb25zdCB2YWx1ZSA9IGNvcHlFeHBvcnRzLl9fZ2V0U3RyaW5nKHB0cik7CgogICAgICAgIGNvbnNvbGUubG9nKHZhbHVlKTsKICAgICAgfQogIH0KIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb3B5RXhwb3J0cyA9IGV4cG9ydHM7CiAgICBvdXRwdXQudmFsdWUgKz0gYHRlc3QoKTogYWN0dWFsICR7ZXhwb3J0cy50ZXN0KCl9LCBleHBlY3Q6IDRcbmAKICB9KQo8L3NjcmlwdD4=)

**Comment by I-dodo** [comment]
Sorry, I don't know why this giving me `memory access out of bounds` (not the error in the example), maybe because I got the string as input from js?. But it is weird cause the toString method working fine, and the length is correct.

For now, I am just using lists. If I catch the error, I will re-open with the playground example.
Thanks anyway :)
