### ISSUE TITLE
How to allocate memory of a certain class size?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1912]
How to allocate memory of a certain class size? Just like __new, or similar to C language malloc(sizeof(T)). Currently instantiate needs to pass parameters, but I want to fill all the memory data myself (or not all classes support parameterless constructors).

**Comment by MaxGraey** [comment]
`__new(offsetof<SomeClass>(), idof<SomeClass>())`

**Comment by yjhmelody** [comment]
Thank you very much, I almost forgot this function.

**Comment by yjhmelody** [comment]
Will the following function make more sense if it is built-in in the standard library?
```ts
export function instantiateUnsafe<T>(): T {
    return changetype<T>(__new(offsetof<T>(), idof<T>()));
}
```
