### ISSUE TITLE
readonly props can be assignable in a constructor.

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1915]
The following is valid in TS because constructors are allowed to "construct" values:

```ts
class Foo {
	readonly length: i32 = 0

	constructor() {
		this.length = 1 + 2 // currently an error (wrong)
	}

	method() {
		this.length = 1 + 2 // currently an error (good)
	}
}
```

[Playground reproduction](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY2xhc3MgRm9vIHsKCXJlYWRvbmx5IGxlbmd0aDogaTMyID0gMAoKCWNvbnN0cnVjdG9yKCkgewoJCXRoaXMubGVuZ3RoID0gMSArIDIKCX0KfQoKLyoqIENhbGN1bGF0ZXMgdGhlIG4tdGggRmlib25hY2NpIG51bWJlci4gKi8KZXhwb3J0IGZ1bmN0aW9uIGZpYihuOiBpMzIpOiBpMzIgewogIGNvbnN0IGY6Rm9vID0gbmV3IEZvbygpCgogIHZhciBhID0gMCwgYiA9IDEKICBpZiAobiA+IDApIHsKICAgIHdoaWxlICgtLW4pIHsKICAgICAgbGV0IHQgPSBhICsgYgogICAgICBhID0gYgogICAgICBiID0gdAogICAgfQogICAgcmV0dXJuIGIKICB9CiAgcmV0dXJuIGEKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCiAgICBmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgICAgIG91dHB1dC52YWx1ZSArPSBgZmliKCR7aX0pID0gJHtleHBvcnRzLmZpYihpKX1cbmAKICAgIH0KICB9KQo8L3NjcmlwdD4=)

**Comment by MaxGraey** [comment]
TS here unsound. if you're remove init value constructor's code will compile:
```ts
class Foo {
  readonly length: i32; // don't assign 0

  constructor() {
    this.length = 1 + 2 // ok
  }
}
```

**Comment by trusktr** [comment]
[typescript version](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oCcCmYAm8AdiAJ7QjaEDmALgBYBc0hArgLYBG2m0AvNABYATKnTRgRCDUwtgNeJgAUAShRiM9AJYQAdBWr0+0AIzQA1NBEYAvqlsTCU6ADMjhbAHc4iaKgcR4Cj14KkVnPUpaOlUAehjoAGZRcP0oowFoOOhuTAVoRSpEPGUgA)

But I guess it is redundant to have the field value only to set it in the constructor. So it's a matter of keeping compatibility with TS. It wouldn't unsound if the constructor sets it (just strange that a dev sets two values)

**Comment by trusktr** [comment]
@MaxGraey What is unsound about it?
