### ISSUE TITLE
bug: constructor parameter members initialized in wrong order

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1918]
Given the code

```ts
class Foo {
  c: number = this.a + this.b
  constructor(public a: number, public b: number) { }
}

const f = new Foo(1, 2)
```

the value of `f.c` should be `3`, but it is `0`.

This [assemblyscript playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY2xhc3MgRm9vIHsKICBjOiBpMzIgPSB0aGlzLmEgKyB0aGlzLmIKICBjb25zdHJ1Y3RvcihwdWJsaWMgYTogaTMyLCBwdWJsaWMgYjogaTMyKSB7fQp9CgoKLyoqIENhbGN1bGF0ZXMgdGhlIG4tdGggRmlib25hY2NpIG51bWJlci4gKi8KZXhwb3J0IGZ1bmN0aW9uIGZpYihuOiBpMzIpOiBpMzIgewogIGNvbnN0IGYgPSBuZXcgRm9vKDEsIDIpCgogIHJldHVybiBmLmMgLy8gd2Ugc2hvdWxkIHNlZSAzLCBidXQgd2Ugc2VlIDAKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCiAgICBmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgICAgIG91dHB1dC52YWx1ZSArPSBgZmliKCR7aX0pID0gJHtleHBvcnRzLmZpYihpKX1cbmAKICAgIH0KICB9KQo8L3NjcmlwdD4=) example shows `0`.

This equivalent [TypeScript playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1rAFzQHYFcBbAIwFMAnaAXmgBcALASwgDoxoBqOp149TeLgi1y+YLXjkAFAAd8xEI2DQwOAiQoAaaHIVLoxNUTLkAlCmgBfVNdTBBw6ADNqeUgHc4iKQEZtAJlNUOwd4EFIWEHgAcyknFmBzAHok6CjomAAiAGZMoA) example shows the expected `3`.

**Comment by dcodeIO** [comment]
Initialization order should be:
* Set provided values of `this.a` and `this.b` + implement "TS2333: 'this' cannot be referenced in constructor arguments." to account for parameter initializes like `public a: number = this.c`, which would be invalid
* Execute field initializers, here set `this.c`
* Execute constructor body

**Comment by dcodeIO** [comment]
Interesting oddity: Locally I get a "TS2729: Property is used before its initialization"  on `c: i32 = this.a + this.b` at `.a` and `.b`, while in the TS playground I don't. Any ideas? :)

**Comment by trusktr** [comment]
> Interesting oddity: Locally I get a "TS2729: Property is used before its initialization" on `c: i32 = this.a + this.b` at `.a` and `.b`, while in the TS playground I don't. Any ideas? :)

I see you merged it, so I assume you already figured the answer to that?

**Comment by dcodeIO** [comment]
I still don't know why that's different in their playground and locally, but let me know if you have an idea :) Was suspecting a differing config option, but couldn't find the one that is responsible.
