### ISSUE TITLE
About encode(utf16/ucs2->utf8)

### ISSUE THREAD

**Issue by iwojima** [AssemblyScript/assemblyscript#192]
Dear team,

Thank you for your contribution, we are developing a wasm virtual machine. and we need support Javascript , to write a JS code to convert to wast , so we find your project.

but we found the encode of string look like "utf16/ucs2" in compiled wasm file  . It's difficult to recognize them in our virtual machine. for example , we defined a string as below:

_var str = "123";_

after compiling , it will be:

_(data (i32.const 8) "\03\00\00\001\002\003")_

we had tried to convert the string to utf8 , but convert function we defined can be passed by the compiler . can you give us any advice to fix the issue? or have you any way to convert string from "utf16/ucs2" to "utf8" ?

Thanks!

**Comment by MaxGraey** [comment]
Hi @iwojima,
Thanks for your interest. AssemblyScript's String class provide two additional (non-standard for web API) methods for managing zero-terminated UTF8 strings which using for EOS contracts which run on WAVM VM.

[`String#lengthUTF8`](https://github.com/AssemblyScript/assemblyscript/blob/671121bf702273c930d39999f02643d4f52b2e3d/std/assembly/string.ts#L411)
[`String#toUTF8`](https://github.com/AssemblyScript/assemblyscript/blob/671121bf702273c930d39999f02643d4f52b2e3d/std/assembly/string.ts#L435)

Hope this help

**Comment by yuanjunliang** [comment]
How can I import thie String Class and use it.
Import file 'assembly/assemblyscript.ts' not found when I import assemblyscript and build it

**Comment by MaxGraey** [comment]
You don't need explicit importing objects from std like `String`, `Array`, typed arrays, `Map`, `Set`, `Symbol` and etc.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
