### ISSUE TITLE
How to add a gc callback listener to an object when it's be GCed(free)?

### ISSUE THREAD

**Issue by JavanZhu** [AssemblyScript/assemblyscript#1920]
Hi all!
My AssemblyScript wasm app call some native API which implemented by wasm runtime, 
and some native_api_free() API must be called manually to free some native resource by AssemblyScript wasm 
app when there is no need to use it, otherwise it will cause memory leak problem. 
```
export function _start(): void {
  // call native api which implemented by webassembly runtime
  var stringInstance = covertToString(nativeApi());
  // add a listener to listen this object's lifecycle
  stringInstance.addGCListener(gcCallbackMethod(stringInstance));
}

function gcCallbackMethod(inst: string) {
  // when this object is being free, call nativeAPIFree() to free some native resource so that developer not need to free it manually.
  nativeApiFree(inst);
}

```

For some reason, it's hard to free it manually.  Is it possible to add a GC callback listener to a new AssemblyScript object? So when it is free(GCed), we can receive a GC callback message about this object, then call native_api_free() to free some native resources. Thanks.

**Comment by MaxGraey** [comment]
It will available via finalizers I guess:. See related thread: https://github.com/AssemblyScript/assemblyscript/issues/1299
But currently this dosn't support yet.

**Comment by jtenner** [comment]
Aspect caches strong results and frees them using rtrace. But that requires Javascript host code.

**Comment by JavanZhu** [comment]
> It will available via finalizers I guess:. See related thread: #1299
> But currently this doesn't support yet.

Thank you very much for your quick reply, this is helpful.

**Comment by JavanZhu** [comment]
Hi @jtenner, thank you for your suggestion. 
> But that requires Javascript host code.

I understand that means we should execute AssemblyScript on runtime like chrome, which we AssemblyScript module(wasm) from javascript? Currently my wasm app(written by AssemblyScript) run on [wasm-micro-runtime](https://github.com/bytecodealliance/wasm-micro-runtime). not sure I understand correctly, thanks.
