### ISSUE TITLE
What does "interface fields" mean ?

### ISSUE THREAD

**Issue by xiong-pro** [AssemblyScript/assemblyscript#1922]
Hi, what does "interface fields" mean?

![image](https://user-images.githubusercontent.com/74411555/123216056-b85e4e00-d4fb-11eb-85da-21f263ec8f2b.png)

I wrote code and it works:

```
class Cat {
  name: string;

  constructor(name: string) {
    this.name = name;
  }
}
```

**Comment by willemneal** [comment]
In TS you can have the following interface.

```ts

interface Foo {
  name: string;
}

```

This means that you can have a class that has the matching field, like your example.

However, in AS interfaces can only contain methods, thus to get around this you must implement fields as getters and setters.  Furthermore, and this should be added to the documentation, interfaces in AS are currently nominal not structural, so you need to add `implements Foo` in the class declaration.  I hope that this too is removed in the future.

Full example:
```ts

interface HasName {
  name: string;
}

class Cat implements HasName {
  constructor(private _name: string){}

  get name(): string { return this._name; }
}
```
