### ISSUE TITLE
Exported generic function or class has no concrete instances.

### ISSUE THREAD

**Issue by kadiryazici** [AssemblyScript/assemblyscript#1925]
`assemblyscript": "^0.19.3`
 
 I was following documentation of assemblyscript and I got error on this function.

```ts
export function addOrSomethingElse<T>(a: T, b: T): T {
   if (isString<T>()) {
      return 'something else'; // eliminated if T is not a string
   } else {
      return a + b; // eliminated if T is a string
   }
}
```

```
WARNING AS232: Exported generic function or class has no concrete instances.

 export function addOrSomethingElse<T>(a: T, b: T): T {
                 ~~~~~~~~~~~~~~~~~~
 in assembly/index.ts(11,17)

```

**Comment by dcodeIO** [comment]
When `addOrSomethingElse` is not used inside of the module with some `T`, there won't be a concrete Wasm function to export (nothing to compile). The warning indicates this condition.

**Comment by kadiryazici** [comment]
> When `addOrSomethingElse` is not used inside of the module with some `T`, there won't be a concrete Wasm function to export (nothing to compile). The warning indicates this condition.

So we are not able to export a function with generics, they are only for using inside functions right?

**Comment by dcodeIO** [comment]
If there is a concrete use of, say, `addOrSomethingElse<i32>` somewhere inside of the module to indicate, there will be an export of it under that name. But without a concrete use, the compiler can only guess.

**Comment by willemneal** [comment]
@dcodeIO is there a way to silence this warning?

**Comment by willemneal** [comment]
#1979 This should allow for silencing the warning.
