### ISSUE TITLE
asinit links tsconfig.json to global node_modules, should link to local instead.

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1928]
I see this in the `package.json` generated by `asinit`:

```json
{
	"extends": "../../../.npm-packages/lib/node_modules/assemblyscript/std/assembly.json",
	"include": ["./**/*.ts"],
}
```

But `.npm-packages` is my global node modules folder in my user home directory.

I believe that `asinit` should instead point to the local `node_modules` folder to keep the project self-contained so it doesn't randomly break.

It should always be this:

```json
{
	"extends": "../node_modules/assemblyscript/std/assembly.json",
	"include": ["./**/*.ts"],
}
```

where `../` is relative to the generated `assembly` folder.

**Comment by dcodeIO** [comment]
It points to the compiler installation of the particular `asinit` that has been executed. In this case, it seems that you are executing the global one, not the local one.

**Comment by trusktr** [comment]
That may be true, but how does one get started without any existing project? Most likely with a global install. The idea would be that even if it is global, it creates a local project that is fully standalone. This is what many generators for different web projects do.

I can see however that someone might want to automatically link to global installs (f.e. special deployment setups and CI), and maybe there can be an option for that, but I don't think that is a good default for the average use case.

I do believe most people want to initialize a full self-contained project. Otherwise, pushing it to git, then having soeone else clone it, will fail, because their system can have a totally different configuration.

**Comment by dcodeIO** [comment]
So I guess what `asinit` should do is, since it also adds `assemblyscript` as a dependency, just assume that the user will run `npm install` afterwards and use the local path. Correct?

**Comment by trusktr** [comment]
Yeah, exactly! :+1:
