### ISSUE TITLE
About  `idof<T>()` and `instanceof`

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1930]
What is the difference in performance and expressiveness between `idof<T>()` and `instanceof` in determinng the type of generic parameter (the type determined at compile time).

**Comment by xiong-pro** [comment]
BTW, what's the difference between `==` and `===` in AS ?

**Comment by romdotdog** [comment]
@xiong-pro https://www.assemblyscript.org/basics.html#triple-equals

**Comment by willemneal** [comment]
Good question.  From my understanding `idof<T>` will return the integer id of the type and then it compiles to a comparison at runtime, whereas `instanceof` can eliminate the runtime check in some cases.
