### ISSUE TITLE
Implement builtin function by transform

### ISSUE THREAD

**Issue by mooooooi** [AssemblyScript/assemblyscript#1931]
i want to implement a function like built-in called "familyof", it will return constant value after compilation.
```typescript
function familyof<T>() {}

function EmbeddedFamilyOf<T>() {
    return familyof<T>()
}
```

I have some question:
1. When to do? (after parse, after init or after compile)
2. How can i get the real **Type argument** in Function(EmbeddedFamilyOf)

Thanks!

**Comment by willemneal** [comment]
Can you explain more of what the `familyOf` does?

**Comment by LittleMoi** [comment]
> Can you explain more of what the `familyOf` does?

Continue with #1360 . `familyOf<T>()` is similar to `idof<T>()`. It's return value depends on  class decorator `@family`.

**Comment by LittleMoi** [comment]
I have saw the source code of **AssemblyScript** about built-in function. Has any possible way to explode the hook between compile functions?
