### ISSUE TITLE
How to overload operators in a generic class ?

### ISSUE THREAD

**Issue by xiong-pro** [AssemblyScript/assemblyscript#1933]
Hi, I wrote a generic class, and try to overload the `==` operator.

```ts
class Foo<T> {
  name: string = '';

  // the value may be string or integer
  constructor(value: T) {
    if (isString<T>()) {
      this.name = value;
    }
    if (isInteger<T>()) {
      this.name = value.toString();
    }
  }

  @operator('==')
  protected eq<U>(right: Foo<U>): bool {
    return this.name == right.name;
  }
}

const f1 = new Foo<string>('abc')
const f2 = new Foo<u32>(123)

if (f1 == f2) {
  // do something ...
}
```

But it thrown an error.

```
ERROR AS212: Decorator '@operator' is not valid here.

   @operator('==')
   ~~~~~~~~~~~~~~~
```

I guess it's because the `eq<U>`, but don't know how to write the code. 😢

**Comment by xiong-pro** [comment]
![image](https://user-images.githubusercontent.com/74411555/123659753-994a1e00-d865-11eb-9df9-a61734b0eadf.png)

**Comment by xiong-pro** [comment]
I have installed the `source-map-support`, but still can't see the actual code location in the sources.

**Comment by romdotdog** [comment]
I do indeed get the AssertionError when trying to compile. Do you see these two TypeScript errors and have you tried to fix them?
![image](https://user-images.githubusercontent.com/70765447/123692688-bc041480-d81c-11eb-8029-d6b8c771d3d5.png)

**Comment by dcodeIO** [comment]
Operator overloads cannot be generic. This would work, using two concrete instances of the same type:

```ts
  @operator('==')
  protected eq(right: Foo<T>): bool {
    return this.name == right.name;
  }
```

We certainly need a better error message there, though.

**Comment by xiong-pro** [comment]
@dcodeIO Thanks for reply. My demand is, the Foo can be instantiated from different types (string and integer), so the operator `==` should use two concrete instances of the different type.

**Comment by xiong-pro** [comment]
@romdotdog yes, I often see these TS errors, and use `@ts-ignore` comments. 😂

**Comment by dcodeIO** [comment]
I may misunderstand this, but if you want to compare two `Foo`s both using the same `T`, then my code snippet above is what you'd do. If you indeed want to compare two `Foo`s of different `T`s, then you'd need something like this which cannot be an operator overload because the types are incompatible:

```ts
  static hasSameName<T1,T2>(left: Foo<T1>, right: Foo<T2>): bool {
    return left.name == right.name;
  }
```

**Comment by xiong-pro** [comment]
@dcodeIO thanks, I have tried this before, but just think overload operators is more pretty ... 🤣

Seeing the `bug` label, will it be fixed in the future ?

**Comment by dcodeIO** [comment]
The assertion being hit is a bug, but the limitation is not, at least right now. My fix is linked above, but it only produces a better error message.

**Comment by xiong-pro** [comment]
@dcodeIO OK, but why not to support it? Seems to work in TS. 😢
