### ISSUE TITLE
Import extern wast

### ISSUE THREAD

**Issue by lrettig** [AssemblyScript/assemblyscript#194]
Hello,

I'd like to be able to link against a function defined in another module -- either the `wast` or a precompiled `wasm` binary. Is this possible today? (If it's not possible at compile time I suppose I'd have to wait for dynamic linking to become possible per https://github.com/AssemblyScript/assemblyscript/issues/84.)

Thanks

**Comment by lrettig** [comment]
> Of course you could also use two WASM modules, with one of them being an import of the other one, using the same technique, but without linking them statically to a single binary.

Could you expand upon this a little bit? In particular the "without linking them statically to a single binary" part, since it seems like that's what you're recommending with `wasm-merge`. Thanks!

**Comment by dcodeIO** [comment]
What I meant was to use the exports of one of the modules as the imports of the other module. For example, if you have two modules `foo` and `bar`:

```js
var foo = new WebAssembly.Instance(fooModule, {});
var bar = new WebAssembly.Instance(barModule, { foo: foo.exports });
```

**Comment by lrettig** [comment]
Got it, that makes sense, but I think that means it needs to be run in the browser/in a JS environment which we're not doing with Ewasm. Thanks! It looks like my only options here are some form of static linking using `wasm-merge`, rewriting the darn import in AS itself, or adding support for it in the runtime environment.

**Comment by lrettig** [comment]
How hard would it be to add support for some form of "inline Wast" within AS?

**Comment by dcodeIO** [comment]
There is [some form](https://github.com/AssemblyScript/assemblyscript/blob/master/src/builtins.ts#L2700) already, but it doesn't cover everything yet and might need other improvements. In general, if Binaryen had an API to compile only an expression and integrate it into the IR, that'd also allow us to do something like:

```ts
function myFunc(): i32 {
  return <i32>`(i32.const 1)`!;
}
```

That's of course just a very basic example to get the idea, here misusing the `!` non-null assertion postfix operator.

**Comment by dcodeIO** [comment]
Another option would be to support something like a `keccak256.wat` alongside a `keccak256.d.ts` to be imported as if it was a normal source file, but that might be more complicated than it looks because there isn't really any `.d.ts` support currently. Would be great to have, though.

**Comment by cdetrio** [comment]
wasm-merge was deleted from binaryen recently, fyi https://github.com/WebAssembly/binaryen/issues/2174

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because it has been lingering for quite a while and it seems unlikely that it will be picked up any time soon due to missing support on the Binaryen side. If this is important to someone who is interested in making this work, I suggest adding the relevant mechanism to Binaryen first, and once that's there open a new issue here.
