### ISSUE TITLE
Value type array in struct

### ISSUE THREAD

**Issue by LittleMoi** [AssemblyScript/assemblyscript#1941]
In as, the array in class(unmanaged or not) will record a pointer (the size is 4words-usize)). Should we support the "value type array" as member?

For C++, we can write it in the simplest way:
```cpp
struct IamStruct {
    int numArr[3];
};
```

For AS, I think it can write with:
```typescript
class IamStruct {
    numArr: ValueArray<i32, 3>
}

interface ValueArray<Type,  Length extends usize> {}
```

In compiler, the parser can read the length of `ValueArray`. So it can imitate C++

**Comment by MaxGraey** [comment]
Generics doesn't support values as parameter unlike to C++ templates for example.

**Comment by LittleMoi** [comment]
> Generics doesn't support values as type parameter unlike to C++ templates for example.

It can only convey information to the compiler. What do you mean by generics as AS? The example is working well in TypeScript.

**Comment by MaxGraey** [comment]
Oh, right TS support this. But semantically it different than C++. Hmm. need to think about this more. @dcodeIO wdyt?

**Comment by SebastianSpeitel** [comment]
Wouldn't this be nearly equal to a `StaticArray` property?

**Comment by LittleMoi** [comment]
> Wouldn't this be nearly equal to a `StaticArray` property?

Yes, They are almost the same. From the memory point of view, StaticArray is a reference type. But it cannot determine the length by definition. If exec the code `offsetof<IamStruct>()`, the result is alway 4.
