### ISSUE TITLE
unable to import from installed library in node_modules without relative path

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1954]
#1679 got closed by the _super ugly stupid_ stale bot (:robot::boom:• • • • :boom::gun:), so continuing here:

I just tried this on 0.19.5 and I still get an error:

```ts
import {...} from 'asdom/assembly/index'
```

```
> asc assembly/index.ts --target debug --exportRuntime --exportTable

ERROR TS6054: File '~lib/asdom/assembly/index.ts' not found.

 } from 'asdom/assembly/index'
        ~~~~~~~~~~~~~~~~~~~~~~
 in assembly/index.ts(9,8)

FAILURE 1 parse error(s)
```

This works though:

```ts
import {...} from '../node_modules/asdom/assembly/index'
```

Reproduction:

```sh
git clone https://github.com/lume/asdom.git
cd asdom
git checkout unable-to-import
npm install
cd example
npm install
npm run dev // ERROR
```

----

The following works, but TypeScript shows red squigglies and intellisense breaks because AssemblyScript projects are not set up by default to satisfy TypeScript node resolution:

```js
import {...} from 'asdom' // red squigglies all over!
```

The following doesn't work in AS, but it is proper and TypeScript will see the correct imports and we will get working intellisense:

```js
import {...} from 'asdom/assembly/index' // Intellisense works, but not AS
```

**Comment by trusktr** [comment]
Updated the reproduction to checkout a particular branch.

**Comment by dcodeIO** [comment]
If `assembly` is the base directory there, I think as working (for AS) import would be

```ts
import {...} from 'asdom/index'
```

while `asdom/assembly/index` would attempt to find `asdom/assembly/assembly/index.ts`. Perhaps that's the culprit we have been looking at here for a while, in that leaving out the `assembly` would allow it to compile, but is not TS compatible?

**Comment by yjhmelody** [comment]
@trusktr  May be similar to this question https://github.com/MaxGraey/as-string-sink/pull/1

**Comment by willemneal** [comment]
Why not just?

```ts
import {} from "asdom"
```

**Comment by trusktr** [comment]
> but is not TS compatible?

Yep, that. Types not found in VS Code. Requires an `exports` field in package.json to also be compatible with Node-style imports, which TypeScript [doesn't support yet](https://github.com/microsoft/TypeScript/issues/33079).



> Why not just?
> 
> ```ts
> import {} from "asdom"
> ```

A few reasons:

1. Some things are not exported from the index for various reasons.
2. That is still not compatible with TypeScript by default, breaks VS Code intellisense out of the box.
3. For TS/JS-portable code, importing from index files is bad practice: it imports everything by default and does not tree-shake by default like AS compiler does. So by default (for example with native ES Modules) one will import _everything_ eve if they use only 1% of the library.

**Comment by willemneal** [comment]
Does `types`: `assembly/index.ts` work for 2?

> Some things are not exported from the index for various reasons.

So really this issue here is that we can't do `asdom/submodule`?

Also it sounds like tree shaking is very bad for TS/JS.

**Comment by JairusSW** [comment]
I have the same thing.
```js
import { console } from '../node_modules/as-console/assembly/wasi'
```
Should be:
```js
import { console } from 'as-console/wasi'
```
The `../node_module` won't work well for people using different package managers (pnpm for example). :'(

**Comment by dcodeIO** [comment]
Seems to go into the direction of finding a better convention, and deprecating `ascMain` - no? :)

**Comment by willemneal** [comment]
You could keep `ascMain` for the cases where people don't want `assembly/index.ts` but regardless of having it `as-package/subpackage` should resolve to `dirname(entry of as-package)/subpackage`.

**Comment by trusktr** [comment]
Not stale.

**Comment by dcodeIO** [comment]
It's not purely a bug, as it is kinda by design, but the design itself is kinda a bug, so I guess it is one. We'd need to revert the baseDir computation based on ascMain, which would be a breaking change.

**Comment by dcodeIO** [comment]
I've spent some time looking at this problem now, and came to the conclusion that removing `ascMain` is most likely the most sensible approach. Regardless of whether some of its current problems can be fixed, it will very likely never integrate with existing TS tooling. Without such integration, there'll always be red squigglies all over, either because types cannot be obtained, or wrong types are obtained where TS would do something different than AS.

Hence going to remove the feature, with documentation soon recommending to simply do `import from "myPackage/assembly"` or any other inner path, as it is an approach that always works.

As a possible path forwards in the future, Node.js nowadays recognizes the `exports` property in `package.json` (`main` is considered legacy iiuc), looking like

```json
  "exports": {
    ".": {
      "import": "./path/to/index.js",
      "require": "./path/to/index.cjs",
      "types": "./path/to/index.d.ts"
    },
```

where, perhaps, if typical tooling would support it, there could be an `"assembly"` entry. Likely not going to happen anytime soon, though :)
