### ISSUE TITLE
Optimize table storing of indirect functions with same type and body

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#1955]
```ts
export function test1(a: i32, b: i32): i32 {
  return ((a: i32, b: i32): i32 => a - b)(a, b);
}

export function test2(a: i32, b: i32): i32 {
  return ((a: i32, b: i32): i32 => a - b)(a, b);
}

export function test3(a: i32, b: i32): i32 {
  return ((a: i32, b: i32): i32 => a - b)(a, b);
}
```
create three table entries which store 3 the same elements:
```wat
(table $T0 4 anyfunc)
(elem (i32.const 1) $f0 $f0 $f0)
```

Isn't better handle such cases when type of indirect calls and their bodies the same and use only single entry for all indirect calls?

**Comment by dcodeIO** [comment]
Looks like something that is tricky to optimize due to `table.set` or when the table is exported and can otherwise be modified. Changing the deduplicated element would change all the sites.

**Comment by MaxGraey** [comment]
Do you think it should be done as binaryen optimization?

**Comment by dcodeIO** [comment]
Yeah, I think this would best be done in Binaryen, as it already has the infrastructure to deduplicate functions. Can only be done, however, when the table is guaranteed to never change.

**Comment by trusktr** [comment]
Based on that ^ it sounds like it is out of scope for AS.
