### ISSUE TITLE
Overriding class method more than once does not work as expected

### ISSUE THREAD

**Issue by kbjr** [AssemblyScript/assemblyscript#1956]
If a sub-class overrides a method, and a sub-class of that class overrides it again, the sub-sub-class method doesn't seem to get called as expected.

```typescript
export class Foo {
	public to_string() : string {
		return 'foo';
	}
}

export class Bar extends Foo {
	public to_string() : string {
		return 'bar';
	}
}

export class Baz extends Bar {
	public to_string() : string {
		return 'baz';
	}
}

export const foo: Foo = new Baz();

export function foo_test() : void {
	trace(`foo.to_string(): ${foo.to_string()}`);
}
```

In the above example, despite `foo` actually being an instance of baz (being created with `new Baz()`), the call to `foo.to_string()` actually returns `"bar"` when it would normally be expected to return `"baz"`. Looking at the assembly shows where `Foo#to_string` potentially branches to call `Bar#to_string`:

```wat
(func $assembly/test/Foo#to_string@virtual (param $0 i32) (result i32)
  (local $1 i32)
  block $default
   block $case0
    local.get $0
    i32.const 8
    i32.sub
    i32.load
    local.set $1
    local.get $1
    i32.const 39
    i32.eq
    br_if $case0
    br $default
   end
   local.get $0
   call $assembly/test/Bar#to_string
   return
  end
  local.get $0
  call $assembly/test/Foo#to_string
 )
```

But `Bar#to_string` has no such branching, it just returns a constant, so the second override of `Baz#to_string` never gets called.

```wat
(func $assembly/test/Bar#to_string (param $0 i32) (result i32)
  i32.const 13408
 )
```

**Comment by MaxGraey** [comment]
Why Baz should have this branching?

In playground everything work as [expected](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKZXhwb3J0IGNsYXNzIEZvbyB7CglwdWJsaWMgdG9fc3RyaW5nKCkgOiBzdHJpbmcgewoJCXJldHVybiAnZm9vJzsKCX0KfQoKZXhwb3J0IGNsYXNzIEJhciBleHRlbmRzIEZvbyB7CglwdWJsaWMgdG9fc3RyaW5nKCkgOiBzdHJpbmcgewoJCXJldHVybiAnYmFyJzsKCX0KfQoKZXhwb3J0IGNsYXNzIEJheiBleHRlbmRzIEJhciB7CglwdWJsaWMgdG9fc3RyaW5nKCkgOiBzdHJpbmcgewoJCXJldHVybiAnYmF6JzsKCX0KfQoKZXhwb3J0IGNvbnN0IGZvb0JhejogRm9vID0gbmV3IEJheigpOwpleHBvcnQgY29uc3QgZm9vQmFyOiBGb28gPSBuZXcgQmFyKCk7CgpleHBvcnQgZnVuY3Rpb24gZXhwZWN0X2JheigpOiBzdHJpbmcgewogIHJldHVybiBmb29CYXoudG9fc3RyaW5nKCk7Cn0KCmV4cG9ydCBmdW5jdGlvbiBleHBlY3RfYmFyKCk6IHN0cmluZyB7CiAgcmV0dXJuIGZvb0Jhci50b19zdHJpbmcoKTsKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3QgeyBleHBlY3RfYmF6LCBleHBlY3RfYmFyLCBfX2dldFN0cmluZyB9ID0gZXhwb3J0czsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKTsKCiAgICBvdXRwdXQudmFsdWUgKz0gJ2V4cGVjdDogYmF6LCBhY3R1YWw6ICcgKyBfX2dldFN0cmluZyhleHBlY3RfYmF6KCkpICsgJ1xuJzsKICAgIG91dHB1dC52YWx1ZSArPSAnZXhwZWN0OiBiYXIsIGFjdHVhbDogJyArIF9fZ2V0U3RyaW5nKGV4cGVjdF9iYXIoKSkgKyAnXG4nOwogIH0pCjwvc2NyaXB0Pg==)

**Comment by trusktr** [comment]
Looks like it is working as per the playground.
