### ISSUE TITLE
Expresson based class decladarion causes the compiler to crash 

### ISSUE THREAD

**Issue by xiong-pro** [AssemblyScript/assemblyscript#1957]
[1] compiled error (of course)

```ts
export default class {
  public bar(a: u32): string {
    return a.toString();
  }
}
```

![image](https://user-images.githubusercontent.com/74411555/124772911-09942600-df6f-11eb-9fd6-4add573b6e5f.png)

[2] compiled crash !!! 😢

```ts
export default class {
  public bar(a: u32): string {
    return `${a}`;
  }
}
```

![image](https://user-images.githubusercontent.com/74411555/124773094-334d4d00-df6f-11eb-8d88-45d92f29d07c.png)

**Comment by trusktr** [comment]
As per @dcodeIO on Discord:

> Class expressions are not yet supported

**Comment by trusktr** [comment]
Seems there's a bug with the template string preventing the diagnostic error (the browser tab freezes in an infinite loop?). But maybe that'll resolve itself once class expressions are supported.

**Comment by romdotdog** [comment]
[Crash no longer happens.](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKZXhwb3J0IGRlZmF1bHQgY2xhc3MgewogIHB1YmxpYyBiYXIoYTogdTMyKTogc3RyaW5nIHsKICAgIHJldHVybiBgJHthfWA7CiAgfQp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQgdHlwZT0ibW9kdWxlIj4KY29uc3QgZXhwb3J0cyA9IGF3YWl0IGluc3RhbnRpYXRlKGF3YWl0IGNvbXBpbGUoKSwgeyAvKiBpbXBvcnRzICovIH0pCmNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQpmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAp9Cjwvc2NyaXB0Pg==)
