### ISSUE TITLE
Implement debugging for AssemblyScript Compiler

### ISSUE THREAD

**Issue by ApsarasX** [AssemblyScript/assemblyscript#1969]
I plan to add some features to the AssemblyScript Compiler, but I found that I cannot use the [debugging features of VS Code ](https://code.visualstudio.com/docs/editor/debugging) to debug the AssemblyScript Compiler.

In website of AssemblyScript, there is one page that describes [how to debug the AssemblyScript module](https://www.assemblyscript.org/debugging.html), but this is not what I want, what I want is the debugging for AssemblyScript compiler.

**Comment by willemneal** [comment]
My method for debugging the compiler:
1.  Ensure that `dist/assemblyscript.js` doesn't exist.
1. Add breakpoints where needed or add `debugger` above the line you want to break at.
1. When invoking the compiler or test add `node --inspect-brk`.  This should pause node and print saying that it's listening on port 9229.
1. Add the following configuration: 
 ```json
{
  "version": "0.2.0",
   "configurations": [
      {
       "type": "node",
       "request": "attach",
       "name": "Attach",
       "port": 9229,
       "skipFiles": [
         "<node_internals>/**"
       ]
     }
   ]
}
```

1. Run --> Start Debugging.
