### ISSUE TITLE
Cannot use static field on a type which is a alias of another class

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1970]

**Comment by willemneal** [comment]
[Example](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY2xhc3MgRm9vIHsKICBzdGF0aWMgb25lKCk6IGkzMiB7IHJldHVybiAxOyB9Cn0KCnR5cGUgRmFhID0gRm9vOwoKLyoqIENhbGN1bGF0ZXMgdGhlIG4tdGggRmlib25hY2NpIG51bWJlci4gKi8KZXhwb3J0IGZ1bmN0aW9uIGZpYihuOiBpMzIpOiBpMzIgewogIHZhciBhID0gMCwgYiA9IEZhYS5vbmUoKTsKICBpZiAobiA+IDApIHsKICAgIHdoaWxlICgtLW4pIHsKICAgICAgbGV0IHQgPSBhICsgYgogICAgICBhID0gYgogICAgICBiID0gdAogICAgfQogICAgcmV0dXJuIGIKICB9CiAgcmV0dXJuIGEKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCiAgICBmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgICAgIG91dHB1dC52YWx1ZSArPSBgZmliKCR7aX0pID0gJHtleHBvcnRzLmZpYihpKX1cbmAKICAgIH0KICB9KQo8L3NjcmlwdD4=)

**Comment by MaxGraey** [comment]
minimal example:
```ts
class Foo { static a(): i32 { return 1; }}
type Boo = Foo;
var b = Boo.a();
```

**Comment by dcodeIO** [comment]
```ts
type Boo = Foo;
```

This is not an alias, this is a type alias. It's invalid in TS as well: `'Boo' only refers to a type, but is being used as a value here.(2693)`. Thinking this a little further would lead us to any generic `T.a()`, which makes the challenge here a little clearer perhaps.

**Comment by MaxGraey** [comment]
Btw that's true. In other hand this `const Boo = Foo` also not supported

**Comment by trusktr** [comment]
Closing, as this is how TypeScript works be design (and AS aims to conform to TypeScript as much as possible).

Sidenote 1, if you want to make a type alias of the constructor type, then it would actually be the following using the `typeof` operator in TypeScript:

```ts
type Boo = typeof Foo;
```

But, sidenote 2, AS does yet not allow the ability to reference class constructors, let alone support `typeof` on constructors.

**Comment by trusktr** [comment]
Issue for tracking constructor references: https://github.com/AssemblyScript/assemblyscript/issues/1991
