### ISSUE TITLE
Compiler stuck when using more complicated types are used

### ISSUE THREAD

**Issue by neutrino2211** [AssemblyScript/assemblyscript#1974]
I wrote the below code to test if I could use assemblyscript to optimise my custom element work style.

```ts
// The entry file of your WebAssembly module.

export function add(a: i32, b: i32): i32 {
  return a + b;
}

export function widget() : (state: {num: i32}) => string {
  return (state: {num: i32}) => `Hello ${state.num}`;
}
```

### What I expected

I expected the compiler to generate a wasm file and its corresponding wat file

### What happened

The compiler got stuck on generating the files for minutes

I tried the following code and it worked, which tells me that it's the whole ```{num: i32}``` that it does not like

```ts
// The entry file of your WebAssembly module.

export function add(a: i32, b: i32): i32 {
  return a + b;
}

export function widget() : (state: i32) => string {
  return (state: i32) => `Hello ${state}`;
}
```
Is there a way of writing those types that the compiler can easily handle?

**Comment by MaxGraey** [comment]
inline object types doesn't support yet. So instead:
```ts
export function widget() : (state: {num: i32}) => string {
  return (state: {num: i32}) => `Hello ${state.num}`;
}
```
You can write this:
```ts
class State {
  num: i32
}
export function widget() : (state: State) => string {
  return (state: State) => `Hello ${state.num}`;
}
```
