### ISSUE TITLE
feat: `BaseClass|null` should be castable to `SubClass|null`

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1976]
This type cast is ok in TypeScript:

```ts
class Foo {}
class Bar extends Foo {
  n: i32 = 345
}

let a: Foo | null = null
let b = a as Bar | null
```

[TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAlgzAJigXigOwK4FsBGEBOUAUEQMYA2AhgM7VQBiA9o1AN4C+ZVtUAQpYQgAPYBDQATOkxasiUdAC5YiFFDgAWAKxFORchGBRKS6VAA+6DOXKrM1vQag5VlI3X6ELd8kA) (no error)

[AS playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY2xhc3MgRm9vIHt9CmNsYXNzIEJhciBleHRlbmRzIEZvbyB7CiAgbjogaTMyID0gMzQ1Cn0KCi8qKiBDYWxjdWxhdGVzIHRoZSBuLXRoIEZpYm9uYWNjaSBudW1iZXIuICovCmV4cG9ydCBmdW5jdGlvbiBmaWIobjogaTMyKTogaTMyIHsKICBsZXQgYTogRm9vIHwgbnVsbCA9IG51bGwKICBsZXQgYiA9IGEgYXMgQmFyIHwgbnVsbAogIHJldHVybiAxMjMKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCiAgICBmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgICAgIG91dHB1dC52YWx1ZSArPSBgZmliKCR7aX0pID0gJHtleHBvcnRzLmZpYihpKX1cbmAKICAgIH0KICB9KQo8L3NjcmlwdD4=) (runtime error)

The error is:

```
Uncaught (in promise) RuntimeError: memory access out of bounds
```

Though depending on the program the stack trace can be different so I didn't include that part. Only the error message is the same.

---

Workaround for the time being:

```ts
class Foo {}
class Bar extends Foo {
  n: i32 = 345
}

let a: Foo | null = null
let b: Bar | null = a == null ? null : a as Bar
```

[AS playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY2xhc3MgRm9vIHt9CmNsYXNzIEJhciBleHRlbmRzIEZvbyB7CiAgbjogaTMyID0gMzQ1Cn0KCmRlY2xhcmUgZnVuY3Rpb24gbG9nKHM6IEJhciB8IG51bGwpOiB2b2lkCgovKiogQ2FsY3VsYXRlcyB0aGUgbi10aCBGaWJvbmFjY2kgbnVtYmVyLiAqLwpleHBvcnQgZnVuY3Rpb24gZmliKG46IGkzMik6IGkzMiB7CiAgbGV0IGE6IEZvbyB8IG51bGwgPSBudWxsCiAgbGV0IGI6IEJhciB8IG51bGwgPSBhID09IG51bGwgPyBudWxsIDogYSBhcyBCYXIKCiAgbG9nKGIpCgogIHJldHVybiAxMjMKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsKICBtb2R1bGU6IHtsb2c6IGNvbnNvbGUubG9nfQp9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCiAgICBmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgICAgIG91dHB1dC52YWx1ZSArPSBgZmliKCR7aX0pID0gJHtleHBvcnRzLmZpYihpKX1cbmAKICAgIH0KICB9KQo8L3NjcmlwdD4=) (no error)

But is the workaround good? Is there a way to make the result actually `Bar | null` in memory shape (whatever that may be)?

It seems the workaround will carry the issue up the call stack to end users (f.e. in the case of `return Bar | null`), meaning end users of an API will also have to apply the workaround anywhere they receive and subsequently use such a value.

**Comment by ramonGonzEdu** [comment]
This seems very dangerous because `Bar` might have a property that `Foo` does not have. Going from a subclass to a superclass is fine as they are supposed to share all properties/methods, but you should not be able to cast to a subclass.

**Comment by ramonGonzEdu** [comment]
```ts
class Foo {}
class Bar extends Foo {
  n: number = 345
}

let a: Foo = new Foo
let b: Bar = a as Bar

console.log(b.n);
```
The above snippet returns undefined when compiled thru typescript which would be a memory error on AssemblyScript

**Comment by dcodeIO** [comment]
In AS there is a runtime check on dynamic upcasts that if the cast would be invalid produces an error right on the cast. I believe the bug above is that it doesn't work properly when a `null` is in play.

**Comment by trusktr** [comment]
> In AS there is a runtime check on dynamic upcasts that if the cast would be invalid produces an error right on the cast

That `unexpected upcast` runtime error is useful, preventing the upcast from going down the wrong class branch at runtime. :+1: 

@ramonGonzEdu The above example is contrived, but in general there are APIs like the DOM's `document.querySelector(selectorString)` that have a return type of `Element | null`, and we would like to be able to use any found element that is a subclass of `Element`.

This is a more realistic example:

```ts
// I know that the result will be an HTMLParagraphElement (that extends from Element)
const audio = document.querySelector('.my-audio') as HTMLAudioElement

log(audio instanceof HTMLAudioElement) // 1

audio.pause() // I can use the method that I expect to exist.
```

**Comment by dcodeIO** [comment]
Should be fixed in https://github.com/AssemblyScript/assemblyscript/pull/2042 afaict, but feel free to re-open if there are remaining issues :)
