### ISSUE TITLE
[wasm-validator error in function assembly/index/getNamedArg]

### ISSUE THREAD

**Issue by HansWestman74** [AssemblyScript/assemblyscript#1982]
Hi, when upgrading from 0.9.1 to the latest version 0.19.7, I started getting compiler errors like:

```
wasm-validator error in function assembly/index/getNamedArg] unexpected false: local.get must have a valid type - check what you provided when you constructed the node, on 
(local.get $8)
[wasm-validator error in function assembly/index/getNamedArg] unexpected false: local.get must have a valid type - check what you provided when you constructed the node, on 
(local.get $8)
[wasm-validator error in function assembly/index/getNamedArg] unexpected false: vars must be defaultable, on 
unreachable
```

The function getNamedArg makes use of <Uint8Array>unreachable() and looks like this

```
export function getNamedArg(name: String): Uint8Array {
    let arg_size = getNamedArgSize(name);
    if (arg_size == null) {
      Error.fromErrorCode(ErrorCode.MissingArgument).revert();
      return <Uint8Array>unreachable();
    }
    let nameBytes = encodeUTF8(name);
    let arg_size_u32 = changetype<u32>(arg_size.value);
    let data = new Uint8Array(arg_size_u32);
    let ret = externals.get_named_arg(nameBytes.dataStart, nameBytes.length, data.dataStart, arg_size_u32);
    const error = Error.fromResult(ret);
    if (error !== null) {
      error.revert();
      return <Uint8Array>unreachable();
    }
    return data;
}
```

This used to compile. How can I fix this compiler error?

Cheers,

Hans

**Comment by willemneal** [comment]
Do you have a repo you can share?

**Comment by HansWestman74** [comment]
Wow! Thanks for the quick reply!!

Here is the full repo:

https://github.com/casper-network/casper-node

The assemblyscript code I'm trying to upgrade to the latest 0.19.7 assemblyscript version is in the folder 

casper-node/smart_contracts/contract_as

**Comment by HansWestman74** [comment]
Hi again, 

I realized that my reply could be more helpful. So a separated out the code that gives the error in this repo:

https://github.com/HansWestman74/as-upgrade

To reproduce the error messages simply run

`npm run asbuild`

in as-upgrade folder.

**Comment by willemneal** [comment]
Ah found the error. My first glance at the code yesterday I saw `return <..>unreachable();`, however, `unreachable` will prevent the function from returning since it will cause Wasm to abort to the host.  In TS this is represented as a `never` type so you're IDE should be fine with it. 

The returns were in fact causing the issue as it was compiling wasm code that didn't type check correctly.  I made a PR to that repo with the fix: https://github.com/HansWestman74/as-upgrade/pull/1

**Comment by HansWestman74** [comment]
Awesome! Your explanation makes perfect sense.

Thanks!!!

**Comment by HansWestman74** [comment]
Hi again,

Thanks for your previous amazing help! After removing all unreachable returns I ran onto another issue: our Rust engine that executes the Assemblyscript generated wasms no longer recognizes the wasm start. Has there been breaking changes in how the wasm start is organized? If so where is a good place in the documentation to read and understand this issue better?

Another question: the --validate flag is deprecated right? Right now the compiler warns me about --validate.

**Comment by willemneal** [comment]
What VM are you using?

**Comment by MaxGraey** [comment]
> Another question: the --validate flag is deprecated right?

Yes

**Comment by HansWestman74** [comment]
The wasm are fed to a local testing environment  built in Rust. The Error Unsupportedwasmstart is emitted here

https://github.com/casper-network/casper-node/blob/release-1.3.0/execution_engine/src/core/runtime/mod.rs 

on line 81
.
Is there some compiler option in asc to not generate a wasm start?

**Comment by MaxGraey** [comment]
You're uses wasmi. Better address this question to their repo

**Comment by MaxGraey** [comment]
Btw you can add `--explicitStart` to asc. In this case you should manually call `exports._start()`

**Comment by HansWestman74** [comment]
We are trying to support Assemblyscript generation of smart contract wasms. Right now we are supporting Rust which generate wasms without a start section. Is it possible to generate wasms without a start section in Assemblyscript ?

**Comment by MaxGraey** [comment]
Yes, see my comment below about `--explicitStart`
