### ISSUE TITLE
ERROR() triggered at compile time when program does not reach it

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1993]
This is more of like a "we know, there's lots of things to implement", not a bug. But here's a case where the ERROR line will not be used, but compiler doesn't yet know

[Minimal example](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKYWJzdHJhY3QgY2xhc3MgQmFzZSB7CiAgdXNlRm9vKCk6IGkzMiB7CiAgICB0aGlzLmZvbygpCiAgfQogIGZvbygpOiBpMzIgewogICAgRVJST1IoJ1N1YmNsYXNzIHNob3VsZCBpbXBsZW1lbnQgYWJzdHJhY3QgZm9vKCkgbWV0aG9kLicpCiAgfQp9CgpjbGFzcyBTdWIgZXh0ZW5kcyBCYXNlIHsKICBmb28oKTogaTMyIHsgcmV0dXJuIDEyMyB9Cn0KCmV4cG9ydCBmdW5jdGlvbiBmaWIobjogaTMyKTogaTMyIHsKICBjb25zdCBzID0gbmV3IFN1YgogIHJldHVybiBzLnVzZUZvbygpCn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQogICAgZm9yIChsZXQgaSA9IDA7IGkgPD0gMTA7ICsraSkgewogICAgICBvdXRwdXQudmFsdWUgKz0gYGZpYigke2l9KSA9ICR7ZXhwb3J0cy5maWIoaSl9XG5gCiAgICB9CiAgfSkKPC9zY3JpcHQ+)

```ts
abstract class Base {
  useFoo(): i32 {
    this.foo()
  }
  foo(): i32 {
    ERROR('Subclass should implement abstract foo() method.')
  }
}

class Sub extends Base {
  foo(): i32 { return 123 }
}

export function fib(n: i32): i32 {
  const s = new Sub
  return s.useFoo()
}
```

The key is that `abstract` is the indicator that the line can't be reached because the base class can't be instantiated directly, and if a subclass overrides the `foo` method then the base method is never actually reached.

**Comment by MaxGraey** [comment]
`ERROR` is compile time so if it not dead code (three shacked or compile time branch eliminated) it will trigger compile time error. Just use `throw new Error` for your case

**Comment by trusktr** [comment]
That code is dead code: the subclass overrides the base class method, therefore the base class method is never user (dead).
