### ISSUE TITLE
overriding of class fields does not work (duplicate identifier error)

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#1994]
Input:

```ts
abstract class ASPKGElement {
    protected useShadow: boolean = true
}

class NavBar extends ASPKGElement {
    protected useShadow: boolean = false
}
```

[TS example](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgggZQAoGkBxAUWQFMBbMgO0TIA8IaATDACQBUBZAGVMpqIA3gCgE4hAAcoAeybwyzBAFcwZbAAtgzGQHcAXAhAyZ5YNQQBeBNGVkRAXxEiUaDADlgANwBCwKAgMTNSsWHhE-FS0CKISUrLyTEqq6lo6BkYmZhbWAGbAyGqOQA) with no error

[AS example](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKYWJzdHJhY3QgY2xhc3MgQVNQS0dFbGVtZW50IHsKICAgIHByb3RlY3RlZCB1c2VTaGFkb3c6IGkzMiA9IDAKfQoKY2xhc3MgTmF2QmFyIGV4dGVuZHMgQVNQS0dFbGVtZW50IHsKICAgIHByb3RlY3RlZCB1c2VTaGFkb3c6IGkzMiA9IDEKfQoKZXhwb3J0IGZ1bmN0aW9uIGZpYihuOiBpMzIpOiBpMzIgewogIGNvbnN0IHMgPSBuZXcgTmF2QmFyCiAgcmV0dXJuIHMudXNlU2hhZG93Cn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQogICAgZm9yIChsZXQgaSA9IDA7IGkgPD0gMTA7ICsraSkgewogICAgICBvdXRwdXQudmFsdWUgKz0gYGZpYigke2l9KSA9ICR7ZXhwb3J0cy5maWIoaSl9XG5gCiAgICB9CiAgfSkKPC9zY3JpcHQ+) with error

I think this is an `enhancement` issue, right?

**Comment by trusktr** [comment]
[Workaround](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKYWJzdHJhY3QgY2xhc3MgQVNQS0dFbGVtZW50IHsKICAgIHByb3RlY3RlZCB1c2VTaGFkb3c6IGkzMiA9IDAKfQoKY2xhc3MgTmF2QmFyIGV4dGVuZHMgQVNQS0dFbGVtZW50IHsKICAgIGNvbnN0cnVjdG9yKCkgewogICAgICBzdXBlcigpCiAgICAgIHRoaXMudXNlU2hhZG93ID0gMQogICAgfQp9CgpleHBvcnQgZnVuY3Rpb24gZmliKG46IGkzMik6IGkzMiB7CiAgY29uc3QgcyA9IG5ldyBOYXZCYXIKICByZXR1cm4gcy51c2VTaGFkb3cKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCiAgICBmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgICAgIG91dHB1dC52YWx1ZSArPSBgZmliKCR7aX0pID0gJHtleHBvcnRzLmZpYihpKX1cbmAKICAgIH0KICB9KQo8L3NjcmlwdD4=) :

```ts
abstract class ASPKGElement {
    protected useShadow: i32 = 0
}

class NavBar extends ASPKGElement {
    constructor() {
      super()
      this.useShadow = 1
    }
}
```

**Comment by dcodeIO** [comment]
See #2158, which now allows declaring duplicate fields to some extent.
