### ISSUE TITLE
[Bug Or Question] __Long__ or __isLong__?

### ISSUE THREAD

**Issue by ApsarasX** [AssemblyScript/assemblyscript#1997]
https://github.com/AssemblyScript/assemblyscript/blob/886a4a6af908ef3eb5fc475c2b0fcafb67c75ba8/src/glue/js/i64.d.ts#L6

But in https://github.com/dcodeIO/long.js/blob/ce11b4b2bd3ba1240a057d62018563d99db318f9/src/long.js#L77-L79
```js
Long.prototype.__isLong__;

Object.defineProperty(Long.prototype, "__isLong__", { value: true });
```

Is this a mistake? What is the purpose of `__Long__` field?

**Comment by trusktr** [comment]
@ApsarasX It seems you are looking at unrelated repositories. `long.js` has nothing to do with `AssemblyScript` (even if one might be inspired from the other), and therefore `__isLong__` in `long.js` seems to not have anything to do with `__Long__` in AssemblyScript.
