### ISSUE TITLE
Small code makes parser hang

### ISSUE THREAD

**Issue by Y--** [AssemblyScript/assemblyscript#1999]
Hi!

If you try to paste this small snipped in the [AS editor](https://www.assemblyscript.org/editor.html), and try to look at the WASM generated, the page becomes unresponsive:
```ts
export function foo() {
  if (idof<Foo>() == idof<Bar>) {
    baz();
  } else {
    `Some string`
  }
}
```

Note that:
* the code is not correct (it is missing the parenthesis to call `idof` in `idof<Bar>`)
* if you remove the string template, from the `else` branch, the issue disappear
* if you fix the `idof` call, the issue disappear

Let me know if you need any additional detail on this.

Thanks!

**Comment by dcodeIO** [comment]
Looks like an endless loop not properly skipping over the missing parenthesis. Thanks for your report!

**Comment by yjhmelody** [comment]
@dcodeIO I also encountered endless loop before, but it was a more borderline situation, see #1801

**Comment by HerrCai0907** [comment]
> @dcodeIO I also encountered endless loop before, but it was a more borderline situation, see #1801

They are same issue. After parser error, template string will cause infinite loop. But It's a question why parser error....
```
class Foo<CB = (data: u32) => void> {                           => Error: TS1003: Identifier expected
    private foo(): void {
        throw new Error(``);
    }
}
```
but the below is correct
```
type T = (data: u32) => void;
class Foo<CB = T> { 
    private foo(): void {
        throw new Error(``);
    }
}
```
