### ISSUE TITLE
Contribution guide(?)

### ISSUE THREAD

**Issue by tsirlucas** [AssemblyScript/assemblyscript#2]
I don't know how the project is running and if you guys need help with anything, but I've noticed that there is some features in TS/JS that we do not have in AssemblyScript like the JSON parser and stringify. Is there some special reason or it's just because no one implemented it yet? I mean, I've read on an issue that you guys don't want to implement Array.push because you don't want to deal with dynamic arrays, etc.

What would be the best approach: Create a PR adding the feature or create a separated lib like a pollyfill?

I'm trying to study the project to understand how could I help, so a contribution guide and a list of what is needed would be nice.

**Comment by tsirlucas** [comment]
Just one more question: Whats exactly the difference between this repo and the original one? I mean, would that JSON integration work with the old compiler? I keep asking about the JSON integration because I'm trying to migrate a lib to AssemblyScript as experiment... I want to know what are the limitations and benefits in a real-world project today. Anyway, thanks for the fast answer and great explanation!

**Comment by dcodeIO** [comment]
The [prototype compiler](https://github.com/AssemblyScript/assemblyscript) has some, though limited, support for [strings](https://github.com/AssemblyScript/assemblyscript/blob/master/std/string.ts). String (or more precisely: class) support there is based on linking your code with [a memory management runtime compiled from C](https://github.com/AssemblyScript/runtime) (basically dlmalloc) and requires manually `free`ing no longer needed memory.

Other notable differences are that the prototype compiler is based on TypeScript (written in TypeScript), while this one here is standalone (written in "portable" AssemblyScript) so it can be compiled to WebAssembly eventually. In the new one I am avoiding using/linking with non-AssemblyScript code. The [other issue](https://github.com/AssemblyScript/next/issues/1) from above has some thoughts on memory management in the new compiler.

**Comment by tsirlucas** [comment]
Hey @dcodeIO, thanks again for the answer and explanation!

 I'm actually migrating the [elasticlunr](https://github.com/weixsong/elasticlunr.js) library to AssemblyScript and it uses the JSON during the indexing process.

I will keep my research and maybe try to isolate the slower but simpler things and migrate them to AssemblyScript. I think this will help me understand how far along the project is and how should I start my studies over the compiler so I'm able to contribute.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
