### ISSUE TITLE
Custom transformers

### ISSUE THREAD

**Issue by TomMarius** [AssemblyScript/assemblyscript#20]
Is AssemblyScript planning to support TypeScript-like custom transformers?

**Comment by dcodeIO** [comment]
If I understand this correctly, custom transformers do not look AOT-compatible. More like something that requires the language to be highly dynamic.

**Comment by dcodeIO** [comment]
On a second thought, something similar might be possible if there was an API to plug in custom built-ins that have full access to the compiler's type information and transform such code at compile time.

**Comment by dcodeIO** [comment]
See also: https://github.com/AssemblyScript/assemblyscript/wiki/Limitations

**Comment by TomMarius** [comment]
Custom transformer is a function plugged into the compilation process. It takes the AST of the program and returns a new (or the same) AST. It has nothing to do with anything dynamic; other statically typed languages have this sort of plugin functionality as well.

**Comment by dcodeIO** [comment]
I see, thanks. AssemblyScript has an [AST representation](https://github.com/AssemblyScript/assemblyscript/blob/master/src/ast.ts) as well, so transforming it prior to the final compilation step shouldn't be a big deal. There is also the [Program that wraps the higher level IR](https://github.com/AssemblyScript/assemblyscript/blob/master/src/program.ts) created from the AST. That's where [built-in functionality](https://github.com/AssemblyScript/assemblyscript/blob/master/src/builtins.ts) is combined with the processed source information, which is the last step before compilation is finally performed.

**Comment by dcodeIO** [comment]
Regarding the commit above, there is now a way to provide transforms with the `--transform` option to `asc`. This basically loads a node module that then exports hooks the compiler will call on specific occasions. The only hook for now is `afterParse` which calls the transform with the parser instance that contains the parsed sources, prior to instantiating and initializing a program from it. It's relatively easy to add more hooks, of course, but I didn't want to go overboard with that so let me know if there's something specific you'd need.

**Comment by dcodeIO** [comment]
Closing this for now as the infrastructure is in place. Just let me know if more hooks are necessary :)
