### ISSUE TITLE
AssemblyScript Loader

### ISSUE THREAD

**Issue by marcus-sa** [AssemblyScript/assemblyscript#200]
I've been trying this project out for a few days, and I must say, usage wise I'm pretty confused.
First of all there's no NPM package for https://github.com/AssemblyScript/assemblyscript/tree/master/lib/loader available as shown in the docs that there should be.

https://github.com/AssemblyScript/assemblyscript/blob/671121bf702273c930d39999f02643d4f52b2e3d/lib/loader/index.d.ts#L48 
Should be `Promise<Response>` and not `Response`.

https://github.com/AssemblyScript/assemblyscript/blob/671121bf702273c930d39999f02643d4f52b2e3d/lib/loader/index.d.ts#L6 
Should be optional.

We need some examples, because I'm really confused on how some things should be done.
E.g using `module.getString` and `module.newString`, because when I try to log something from my `AssemblyScript` file all it logs is a number which makes sense.
But what are the purpose of these two functions?
The docs definitely needs to be updated.

**Comment by dcodeIO** [comment]
Thanks, I updated the declaration to `Promise<Response>`. Regarding documentation, there is [an example here](https://github.com/AssemblyScript/assemblyscript/tree/master/lib/loader#allocatingobtaining-strings-tofrom-memory). Doesn't that explain the usage sufficiently?

Essentially, `newString` allocates a new string in WASM memory returning a pointer to it, while `getString` reads such a segment to a JS string when provided with its pointer.

**Comment by marcus-sa** [comment]
https://github.com/marcus-sa/assemblyscript-starter/blob/master/public/main.ts
Surely it does, but you'd have to wait for the initialized stream to complete before the module is available, otherwise it'll throw undefined, so I'd have to end up wrapping the stream in a callback like this and wait for it to finish before defining the imports.
https://github.com/marcus-sa/assemblyscript-starter/blob/master/public/main.ts

**Comment by dcodeIO** [comment]
Well, you could also use `await` to simplify this

```ts
// (async function() {
  var myModule = await ASLoader.instantiateStreaming(...);
  ...
// })();
...
```

or make use of the Promise as usual:

```ts
ASLoader.instantiateStreaming(...).then(myModule => {
  ...
});
```

**Comment by marcus-sa** [comment]
Already tried that, sadly it doesn't work.

**Comment by MaxGraey** [comment]
In node.js `instantiateStreaming` [not working yet](https://github.com/nodejs/node/issues/21130)

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
