### ISSUE TITLE
 `Function.call` is not working as expected.

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#2000]
Seems that `Function.call` is not working as expected. [playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY2xhc3MgRm9vIHsKICBuOiBpMzIgPSA0NTYKfQoKZnVuY3Rpb24gZm9vKHRoaXM6IEZvbyk6IGkzMiB7CiAgcmV0dXJuIHRoaXMubgp9CgoKZXhwb3J0IGZ1bmN0aW9uIGZpYihuOiBpMzIpOiBpMzIgewogIGNvbnN0IGYgPSBuZXcgRm9vCiAgcmV0dXJuIGZvby5jYWxsKGYpCn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQogICAgZm9yIChsZXQgaSA9IDA7IGkgPD0gMTA7ICsraSkgewogICAgICBvdXRwdXQudmFsdWUgKz0gYGZpYigke2l9KSA9ICR7ZXhwb3J0cy5maWIoaSl9XG5gCiAgICB9CiAgfSkKPC9zY3JpcHQ+)

The code

```ts
class Foo {
  n: i32 = 456
}

function foo(this: Foo): i32 {
  return this.n
}

export function fib(n: i32): i32 {
  const f = new Foo
  return foo.call(f)
}
```

results in

```
ERROR TS2339: Property 'n' does not exist on type 'module'.
```

**Comment by MaxGraey** [comment]
It's not relate to `Function.call`

This should works:
```ts
class Foo {
  n: i32 = 456

  foo(): i32 {
    return this.n;
  }
}

// export function foo(this: Foo): i32 {
//   return this.n;
// }

export function fib(n: i32): i32 {
  const f = new Foo
  const foo = f.foo;
  return foo.call(f);
}
```

**Comment by trusktr** [comment]
Oh, so currently it is only supported on methods, not plain functions.
