### ISSUE TITLE
The compiler crashes when it encounters a class with a static function and an instance field that share the same name.

### ISSUE THREAD

**Issue by irateAnimal** [AssemblyScript/assemblyscript#2006]
```typescript
class BuggedClass {
   snacks:string[]=[];
   static snacks(v:BuggedClass):void {}
}
let inst = new BuggedClass()
BuggedClass.snacks(inst);
```
When this code is compiled, the compiler misses an assertion at `assemblyscript/src/program.ts:4624:3`, for compiler version 0.19.8.
If the static function is never called, no error is thrown.

**Comment by romdotdog** [comment]
In your example, both the snacks field and the static function have an internal name of `BuggedClass.snacks`.
The fix would be to have static functions or fields to have different internal names.
cc: @dcodeIO
