### ISSUE TITLE
wat project error

### ISSUE THREAD

**Issue by blooddy** [AssemblyScript/assemblyscript#201]
if I try to add a block of data, an error appears when starting. before this was not.
`(module
  (memory $memory (export "memory") 0)
  (data (i32.const 1) "\01")
)`
https://webassembly.studio/?f=3x9neo7h78e

`Uncaught (in promise) LinkError: WebAssembly Instantiation: data segment is out of bounds`

**Comment by dcodeIO** [comment]
Not related to AssemblyScript, but it should work when changing the initial number of pages to 1 instead of 0.

```wat
(module
  (memory $memory (export "memory") 1)
  (data (i32.const 1) "\01")
)
```

**Comment by blooddy** [comment]
no. it's simple example. i'm using assemblyscript and then add data to wasm.

**Comment by dcodeIO** [comment]
Ok, just increase the initial number of pages in this case. AssemblyScripts emits a fitting number of pages, which is `0` without any data, so when you add more memory to it (one pages is 64kb), you'll have to increase it accordingly.

**Comment by blooddy** [comment]
i'm sorry! you're right
