### ISSUE TITLE
Performance loss with custom collections

### ISSUE THREAD

**Issue by alexvictoor** [AssemblyScript/assemblyscript#2015]
Hello,
When migrating my project ([HdrHistogramJS](https://github.com/HdrHistogram/HdrHistogramJS)) from AssemblyScript version 0.12 to version 0.19.9 I have noticed a huge performance loss (some benchmark tests are 3x slower).  
I have tried to isolate the root cause and unless I am wrong this performance loss comes from the usage of a custom collection class. 
The following code runs almost 3x slower on my laptop using AssemblyScript 0.18 (and above) than AssemblyScript 0.17:
```
class CustomStorage<T, U> {
  [key: number]: number;
  array: T;
  constructor(size: i32) {
    this.array = instantiate<T>(size);
  }

  @operator("[]") private __get(index: i32): U {
    // @ts-ignore
    return unchecked(this.array[index]);
  }

  @operator("[]=") private __set(index: i32, value: U): void {
    // @ts-ignore
    unchecked((this.array[index] = value));
  }
}

export function bench(): void {
  const s = new CustomStorage<Uint32Array, u32>(10000)
  for (let index = 0; index < 10000; index++) {
    unchecked(s[index] = index);
  }
  let result: u64 = 0;
  for (let index = 0; index < 10000; index++) {
    unchecked(result += s[index]);
  }
}
```
On my laptop, running bench() 1000 times, takes 20ms using AssemblyScript 0.17 and 55ms using AssemblyScript 0.19.9.
Is there any API change I have missed?
Thanks in advance for your help

**Comment by romdotdog** [comment]
try removing `unchecked` in the bench function

**Comment by MaxGraey** [comment]
Did you try inline all functions?
```ts
class CustomStorage<T, U> {
  [key: number]: number;
  array: T;
  @inline constructor(size: i32) {
    this.array = instantiate<T>(size);
  }

  @inline @operator("[]") private __get(index: i32): U {
    // @ts-ignore
    return unchecked(this.array[index]);
  }

  @inline @operator("[]=") private __set(index: i32, value: U): void {
    // @ts-ignore
    unchecked((this.array[index] = value));
  }
}
```

Also I recommend use `const s = new CustomStorage<StaticArray<u32>, u32>(10000)`

**Comment by MaxGraey** [comment]
It seems all this changes should increase performance:
[See benchmark playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmNsYXNzIEN1c3RvbVN0b3JhZ2UxPFQsIFU+IHsKICBba2V5OiBudW1iZXJdOiBudW1iZXI7CiAgYXJyYXk6IFQ7CiAgY29uc3RydWN0b3Ioc2l6ZTogaTMyKSB7CiAgICB0aGlzLmFycmF5ID0gaW5zdGFudGlhdGU8VD4oc2l6ZSk7CiAgfQoKICBAb3BlcmF0b3IoIltdIikgcHJpdmF0ZSBfX2dldChpbmRleDogaTMyKTogVSB7CiAgICAvLyBAdHMtaWdub3JlCiAgICByZXR1cm4gdW5jaGVja2VkKHRoaXMuYXJyYXlbaW5kZXhdKTsKICB9CgogIEBvcGVyYXRvcigiW109IikgcHJpdmF0ZSBfX3NldChpbmRleDogaTMyLCB2YWx1ZTogVSk6IHZvaWQgewogICAgLy8gQHRzLWlnbm9yZQogICAgdW5jaGVja2VkKCh0aGlzLmFycmF5W2luZGV4XSA9IHZhbHVlKSk7CiAgfQp9CgpAZmluYWwKY2xhc3MgQ3VzdG9tU3RvcmFnZTI8VCwgVT4gewogIFtrZXk6IG51bWJlcl06IG51bWJlcjsKICBhcnJheTogVDsKICBAaW5saW5lIGNvbnN0cnVjdG9yKHNpemU6IGkzMikgewogICAgdGhpcy5hcnJheSA9IGluc3RhbnRpYXRlPFQ+KHNpemUpOwogIH0KCiAgQGlubGluZSBAb3BlcmF0b3IoIltdIikgcHJpdmF0ZSBfX2dldChpbmRleDogaTMyKTogVSB7CiAgICAvLyBAdHMtaWdub3JlCiAgICByZXR1cm4gdW5jaGVja2VkKHRoaXMuYXJyYXlbaW5kZXhdKTsKICB9CgogIEBpbmxpbmUgQG9wZXJhdG9yKCJbXT0iKSBwcml2YXRlIF9fc2V0KGluZGV4OiBpMzIsIHZhbHVlOiBVKTogdm9pZCB7CiAgICAvLyBAdHMtaWdub3JlCiAgICB1bmNoZWNrZWQoKHRoaXMuYXJyYXlbaW5kZXhdID0gdmFsdWUpKTsKICB9Cn0KCmV4cG9ydCBmdW5jdGlvbiBiZW5jaDEoKTogdm9pZCB7CiAgY29uc3QgcyA9IG5ldyBDdXN0b21TdG9yYWdlMTxVaW50MzJBcnJheSwgdTMyPigyMDAwMDAwKTsKICBmb3IgKGxldCBpbmRleCA9IDA7IGluZGV4IDwgMjAwMDAwMDsgaW5kZXgrKykgewogICAgdW5jaGVja2VkKHNbaW5kZXhdID0gaW5kZXgpOwogIH0KICBsZXQgcmVzdWx0OiB1NjQgPSAwOwogIGZvciAobGV0IGluZGV4ID0gMDsgaW5kZXggPCAyMDAwMDAwOyBpbmRleCsrKSB7CiAgICB1bmNoZWNrZWQocmVzdWx0ICs9IHNbaW5kZXhdKTsKICB9Cn0KCmV4cG9ydCBmdW5jdGlvbiBiZW5jaDIoKTogdm9pZCB7CiAgY29uc3QgcyA9IG5ldyBDdXN0b21TdG9yYWdlMjxTdGF0aWNBcnJheTx1MzI+LCB1MzI+KDIwMDAwMDApOwogIGZvciAobGV0IGluZGV4ID0gMDsgaW5kZXggPCAyMDAwMDAwOyBpbmRleCsrKSB7CiAgICBzW2luZGV4XSA9IGluZGV4OwogIH0KICBsZXQgcmVzdWx0OiB1NjQgPSAwOwogIGZvciAobGV0IGluZGV4ID0gMDsgaW5kZXggPCAyMDAwMDAwOyBpbmRleCsrKSB7CiAgICByZXN1bHQgKz0gc1tpbmRleF07CiAgfQp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CgpmdW5jdGlvbiBydW4obmFtZSwgZm4sIG91dHB1dCkgewogIC8vIHdhcm0tdXAKICBmb3IgKGxldCBpID0gMDsgaSA8IDMwOyBpKyspIGZuKCk7CgogIGxldCB0ID0gcGVyZm9ybWFuY2Uubm93KCk7CiAgZm9yIChsZXQgaSA9IDA7IGkgPCAxMDA7IGkrKykgZm4oKTsKICB0ID0gcGVyZm9ybWFuY2Uubm93KCkgLSB0OwogIG91dHB1dC52YWx1ZSArPSBgJHtuYW1lfTogJHt0LnRvRml4ZWQoNCl9bXNcbmA7Cn0KCmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0Jyk7CgogICAgY29uc29sZS5sb2coZXhwb3J0cy5iZW5jaDEsIGV4cG9ydHMuYmVuY2gyKTsKCiAgICBydW4oJ2JlbmNoMScsIGV4cG9ydHMuYmVuY2gxLCBvdXRwdXQpOwogICAgcnVuKCdiZW5jaDInLCBleHBvcnRzLmJlbmNoMiwgb3V0cHV0KTsKICB9KQo8L3NjcmlwdD4=)

My results on Chrome:
```
bench1: 1141.0000ms
bench2: 314.1000ms
```

where `bench1` is your original code and `bench2` is optimized (StaticArray + inlines)

**Comment by alexvictoor** [comment]
Thank you both for your quick responses!
Indeed this changes help a lot. Out of curiosity, why StaticArray performs better than UintArray ?
Unfortunately, running a wider bench on my codebase, the results are now better but I have still a performance loss. I guess I have at least another problem  not related at all to the code sample posted before :-(
Let me know if you have some other perf tips in mind... 
I was wondering if among all the ways to cast numbers with AssemblyScript some are faster than others? I have the feeling that maybe this [decode](https://github.com/HdrHistogram/HdrHistogramJS/blob/master/assembly/ZigZagEncoding.ts#L85) method that implicitly cast u8 numbers to i64 might be not as efficient as it should :(
Thanks again

**Comment by MaxGraey** [comment]
I recommend try `DataView` instead [ByteBuffer](https://github.com/HdrHistogram/HdrHistogramJS/blob/320a1693cf410ac209a8ad77335622d96105221d/assembly/ByteBuffer.ts#L12)

**Comment by MaxGraey** [comment]
Something like this:
https://github.com/GODcoin/godcoin-js/blob/master/src/bytebuffer.ts

**Comment by alexvictoor** [comment]
I am closing this issue, I have now pretty good performances :) 
The remaining gap was due to some methods that needed to be 'inlined'.
Thanks again for the tips!

**Comment by MaxGraey** [comment]
Btw what is optimization flag you're using? `-O3` or `-O3z`

**Comment by alexvictoor** [comment]
@MaxGraey I am using `-O3`
Using `-O3z` I do not get as good performances. On the main use case I want to optimise I get 30% less throughput...

**Comment by MaxGraey** [comment]
Yeah, `-O3` is better for performance. Currently it's using by default for `--optimize`
