### ISSUE TITLE
BYO memory functions

### ISSUE THREAD

**Issue by jnordberg** [AssemblyScript/assemblyscript#2017]
The wasm context I'm executing in provides memory utils to modules (`memcpy`, `memmove`, `memcmp`, and `memset`) it would be great if there was some way to tell AssemblyScript to use them instead of bundling its own.

**Comment by dcodeIO** [comment]
This is kinda possible by implementing a custom runtime, and replacing the memory manager while reusing the GC. We could also add pull it upstream to the list of supported runtimes if it is general enough :)

See: https://www.assemblyscript.org/garbage-collection.html#custom-runtime

**Comment by jnordberg** [comment]
Something like adding `__memcpy`, `__memmove` etc requirements to the runtime and pulling in the helpers from utils/memory in the default runtime(s)?

**Comment by dcodeIO** [comment]
Something like that, yeah. Importing these instead of using TLSF, and wrapping them in the functions the compiler expects.

**Comment by dcodeIO** [comment]
Oh, wait, I may have misunderstood. I thought this also was about the allocator, but it's just about the utility. Hmm, that would be a little different.

**Comment by MaxGraey** [comment]
I recommend enable build memories as well `--enable bulk-memory`. Binaryen will turn on optimizations which will transform `memcopy(src, dst, 4)` to simple `i32.store(dst, i32.load(src))` and etc. This will be much faster than call host function. For the rest cases it will use your host memcpy, memset

**Comment by jnordberg** [comment]
I just tried this but looks like the stdlib version is still being used, should this work right now? Or would a compiler change be necessary?

conf

```
    "options": {
        "runtime": "stub",
        "use": [
            "~lib/util/memory/memcpy=assembly/env/__as_memcpy",
            "~lib/memory/memcpy=assembly/env/__as_memcpy"
        ]
    }
```

and in env.ts

```ts
declare function memcpy(dst: i32, src: i32, len: u32): i32
export function __as_memcpy(dst: i32, src: i32, len: u32): void {
    memcpy(dst, src, len)
}
```

**Comment by dcodeIO** [comment]
I *think* the first one should work, hmm. Perhaps a bug, not sure.

**Comment by MaxGraey** [comment]
with `--enable bulk-memory` trick with `--use` will not work anymore. You should patch wasm module instead. Which may be tricky. Another option and probably most right option is enable `bulk-memory` also in host side (runtime) if it supports. Which wasm VM you're using?

**Comment by MaxGraey** [comment]
@dcodeIO May be it should `"--use memory.copy=__as_memcpy",`?

**Comment by dcodeIO** [comment]
Could also try this one, but I had assumed that using the earlier one would just replace the implementation, and `--enable bulk-memory` can used on top.

**Comment by jnordberg** [comment]
Here's a minimal repro for `--use ~lib/util/memory/memcpy=replacement` not working

[as-memutil.zip](https://github.com/AssemblyScript/assemblyscript/files/6925441/as-memutil.zip)

**Comment by jnordberg** [comment]
Still an issue AFAIK
