### ISSUE TITLE
Maybe there is a bug for String.UTF8.encode and String.UTF8.decode

### ISSUE THREAD

**Issue by victortanjh** [AssemblyScript/assemblyscript#2021]
my test function is :
function putData():void{
    let buf1 = String.UTF8.encode("bench_key_**10000**",true)
    let str1 = String.UTF8.decode(buf1)
    let buf2 = String.UTF8.encode(" the arg is " + str1, true);
}
when executing this function ,then it will crash.
if I change this function to be:
function putData():void{
    let buf1 = String.UTF8.encode("bench_key_**9999**",true)
    let str1 = String.UTF8.decode(buf1)
    let buf2 = String.UTF8.encode(" the arg is " + str1, true);
}
or change it to be:
function putData():void{
    let buf1 = String.UTF8.encode("bench_key_**10000**",true)
    let str1 = String.UTF8.decode(buf1, **true**)
    let buf2 = String.UTF8.encode(" the arg is " + str1, true);
}
it will not crash.

But I do not know why.

Can anyone explain this phenomenon?  Thank you very much.

**Comment by romdotdog** [comment]
Here's a more minimal example
```ts
String.UTF8.encode("aaaaaaaaaaaaaaaaaaaaaaaaaaa\0", true);
__alloc(0); // String.UTF8.encode("");
```

It seems it's this check that is failing
https://github.com/AssemblyScript/assemblyscript/blob/861126150663568d1afdac8b08fac52adef1b523/std/assembly/rt/tlsf.ts#L203
