### ISSUE TITLE
Marshalling C# string to AssemblyScript

### ISSUE THREAD

**Issue by rygo6** [AssemblyScript/assemblyscript#2023]
I am trying to work out how to marshal a string from C# to AssemblyScript, but seem to be failing here. 

This is my C# struct which I am writing to unmanaged memory:
```
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode, Pack = 1), Serializable]
    public class WasmString
    {
        public readonly int Length;
        public readonly string Buffer;
        public WasmString(string buffer)
        {
            Buffer = buffer;
            Length = Encoding.Unicode.GetByteCount(buffer);
        }
    }
```

This is the C# method which is getting called and marshals the struct+string to the wasm memory.
```
    private int GetPlatform(InstanceContext ctx)
    {
        int offset = 0;
        WasmString version = new WasmString("VERSION_STRING_TEST");
        Marshal.StructureToPtr(version, ctx.GetMemory(0).Data + offset, true);
        return offset;
    }
```

Here is my struct equivalent in AssemblyScript:
```
@unmanaged class WasmString {
  length: i32;    
  buffer: usize;    
  getString(): string {
    return String.UTF16.decodeUnsafe(changetype<usize>(this) + offsetof<WasmString>("buffer"), this.length)
  }
}
```

This is how I am making the call to marshal the string from AssemblyScript:
```
  let platformPtr = getPlatformExtern();
  let platform = changetype<WasmString>(platformPtr);
  print(platform.getString());
```

So my struct is successfully being written and marshaled, as the `length` field does come over correctly.

But my string itself is not decoded correctly. Comes out as just like 2 Chinese characters.

I believe this is all set up so that C# should be writing UTF16 (Unicode) chars, which AssemblyScript is trying to decode. 

I've played a bit with trying to calculate the buffer offset differently in the `getString` method like this:
```
@unmanaged class WasmString {
  length: i32;    
  getString(): string {
    return String.UTF16.decodeUnsafe(changetype<usize>(this) + sizeof<i32>(), this.length)
  }
}
```
But that didn't work either.

Any help would be appreciated.

**Comment by MaxGraey** [comment]
Hmm, I'm not sure I understand how you try to interop between C# and AssemblyScript (wasm) via standard C# marshalling which on;y works for native dll and COM objects. First of all you should use some of Wasm VM like wasmtime or wasmer. And they, will provide you their own mechanisms for interop between C# and WebAssembly module

**Comment by dcodeIO** [comment]
Fwiw, in `String.UTF16.decodeUnsafe(changetype<usize>(this) + offsetof<WasmString>("buffer"), this.length)` there seems to be the assumption that the string lives inline in the struct's memory, but rather looks like one level of indirection? Perhaps the following works?

```ts
@unmanaged class WasmString {
  length: i32;    
  buffer: usize;    
  getString(): string {
    return String.UTF16.decodeUnsafe(this.buffer, this.length)
  }
}
```

**Comment by rygo6** [comment]
@dcodeIO the [StructLayout(LayoutKind.Sequential)] attribute on the C# struct does make it layout the data sequentially I believe. 

So the `buffer` I expect references the first 4 bytes of the string and is not really a pointer. I was only putting the `buffer` field there so I could use the `offsetOf` function to get the offset.

But technically I think this is more correct and what I expected to work:
```
@unmanaged class WasmString {
  length: i32;    
  getString(): string {
    return String.UTF16.decodeUnsafe(changetype<usize>(this) + sizeof<i32>(), this.length)
  }
}
```

But that doesn't work, and also just tried changing it to your suggestion which does not work either.


@MaxGraey I am using Wasmer, specifically WasmerSharp. They describe this here:
https://migueldeicaza.github.io/WasmerSharp/articles/intro.html
Of writing into wasm memory and passing the offset to WebAssembly. Which I believe is all being done correctly since the `length` value of my struct comes through properly. I just suspect the string is in the wrong format, or I am severely misunderstanding something about calculating the offsets of data in a struct and am trying to decode the wrong memory.

Is AssemblyScript UTF16 the same thing as standard Unicode or is there some other particulars about UTF16 byte formatting in AssemblyScript?

Also I am assuming in my offset calculation:
```
return String.UTF16.decodeUnsafe(changetype<usize>(this) + sizeof<i32>(), this.length)
```
That should be giving me the pointer to the start of the structs memory and then moving sizeof<i32> forward in the memory?

**Comment by dcodeIO** [comment]
Could you dump the memory of the struct that became marshalled? I think that should hint at what's going on.

**Comment by MaxGraey** [comment]
C# strings have different memory layout. They are also support memory compaction for ASCII string only so I don't think it could be mapped 1:1 without explicit encode / decode for webassembly

**Comment by rygo6** [comment]
@MaxGraey the StructLayout and MarshalAs attributes were made so that you can set different options on a Struct to control how it gets laid out in unmanaged memory. Which turns out I was just using those wrong.

This is my solution that is working:
```
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode, Pack = 1), Serializable]
    public class WasmString
    {
        // Const is not serialized to struct, but needs to be Const to use in MarshalAs Attribute.
        public const int MaxCapacity = 64;   
        
        public readonly int Length;
        public readonly int Capacity;
        
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = MaxCapacity)]
        public readonly string Buffer;

        public WasmString(string buffer)
        {
            Buffer = buffer;
            Length = Encoding.Unicode.GetByteCount(buffer);
            Capacity = MaxCapacity;
        }
    }
```

```
@unmanaged class WasmString {
  length: i32;    
  capacity: i32;    
  buffer: usize[];   
  getString(): string {
    return String.UTF16.decodeUnsafe(changetype<usize>(this) + offsetof<WasmString>("buffer"), this.length)
  }
}
```

I thought that the StructLayout attribute caused strings to be inlined into the Structs unmanaged memory as a default behavior. But discovered unless you explicitly put `[MarshalAs(UnmanagedType.ByValTStr, SizeConst = MaxCapacity)]` on the string then you will still get a pointer to the string written into your structs unmanaged memory.
