### ISSUE TITLE
Option to assume zero-filled imported memory

### ISSUE THREAD

**Issue by aduros** [AssemblyScript/assemblyscript#2026]
When using `memory.data()` with `--importMemory` the actual zero-filled data ends up in the output wasm.

```typescript
const buffer = memory.data(65535);
```
```wat
(data (;0;) (i32.const 1024) "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00...
```

This makes perfect sense from a safety standpoint, since we can't assume the state of imported memory. However, it can lead to some pretty huge binaries. In my use case I'm importing memory, but everything after `--memoryBase` is guaranteed to be initialized to zero. `wasm-opt` has a `--zero-filled-memory` option for this, it would be really nice if it was exposed via an option to `asc`?

Thanks for the project and considering :smile:

**Comment by MaxGraey** [comment]
Make sense. But first we have to provide public API for [Binaryen](https://github.com/WebAssembly/binaryen/pull/4071).
