### ISSUE TITLE
Missing overloads due to virtual stub finalization order

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#2034]
Concrete class discovery when finalizing virtual stubs still has an ordering issue on cross dependencies (as it seems, we recently fixed chained dependencies), leading to some overloads to be missed in certain cases, in turn running into an assertion when the virtual stub is called. One situation I have seen looks roughly like the following (probably not 100% accurate), but only runs into issues depending on compilation and finalization order:

```ts
class Base {
  abstract foo();
  abstract bar();
}

class A extends Base {
  foo() { new B().foo(); }
  bar() { ... }
}

class B extends Base {
  foo() { new A().bar(); }
  bar() { ... }
}

// somewhere deep:
someBase.foo(); // ?
```

A potential fix could be to add a separate discovery phase before finalizing.

cc @Scutterman

**Comment by Scutterman** [comment]
Sorry I didn't respond to this sooner. I managed to get a minimal repo of the error if that's still helpful.
https://github.com/Scutterman/assemblyscript-virtual-bug
