### ISSUE TITLE
why i return string or object,but get number

### ISSUE THREAD

**Issue by liaozeen** [AssemblyScript/assemblyscript#2043]
![image](https://user-images.githubusercontent.com/20197607/130305120-91e1d281-0e23-4e68-bfda-38d5b2251857.png)

**Comment by romdotdog** [comment]
Those returned numbers are pointers to the heap. You can either use [the runtime](https://www.assemblyscript.org/status.html#interop-with-js) or [as-bind](https://github.com/torch2424/as-bind) to reconstruct complex structures created in wasm.

**Comment by dcodeIO** [comment]
Perhaps also useful: [Exports and imports / On values crossing the boundary](https://www.assemblyscript.org/exports-and-imports.html#on-values-crossing-the-boundary)
