### ISSUE TITLE
Is there any way to get the callback of the AssemblyScipt object being destructor?

### ISSUE THREAD

**Issue by LukiYLS** [AssemblyScript/assemblyscript#2048]
My requirement is this, AssemblyScirpt compiled by Wasm will bridge to the new C++ objects, so I need to notify C++ to release the objects created by C++ when the AssemblyScirpt object is released.

**Comment by LukiYLS** [comment]
As mentioned by #383

**Comment by dcodeIO** [comment]
There is a rough mechanism in place that is meant as the internal stepping stone to eventually implement `FinalizationRegistry`. While unsafe and not yet convenient, a global `__finalize` function can be provided that is called with an object's pointer when it is collected. Here's the respective test case to get an idea how implementing it manually for now could look:

https://github.com/AssemblyScript/assemblyscript/blob/454529dcc4597e7b5bdd338ff101e97d3e18b05b/tests/compiler/rt/finalize.ts#L1-L13

**Comment by LukiYLS** [comment]
> There is a rough mechanism in place that is meant as the internal stepping stone to eventually implement `FinalizationRegistry`. While unsafe and not yet convenient, a global `__finalize` function can be provided that is called with an object's pointer when it is collected. Here's the respective test case to get an idea how implementing it manually for now could look:
> 
> https://github.com/AssemblyScript/assemblyscript/blob/454529dcc4597e7b5bdd338ff101e97d3e18b05b/tests/compiler/rt/finalize.ts#L1-L13

Why can't external objects appear in __finalize
`
@global
function __finalize(ptr: usize): void {
    if (Context.HasObject(ptr)) {
        changetype<TSObject>(ptr).Finalize();
    }
}`

There will be an error

ERROR TS2304: Cannot find name 'ViewContext'.

 let Context = ViewContext.GetInstance()
               ~~~~~~~~~~~
 in view/view_context.ts(77,15)

FAILURE 1 compile error(s)

**Comment by LukiYLS** [comment]
> There is a rough mechanism in place that is meant as the internal stepping stone to eventually implement `FinalizationRegistry`. While unsafe and not yet convenient, a global `__finalize` function can be provided that is called with an object's pointer when it is collected. Here's the respective test case to get an idea how implementing it manually for now could look:
> 
> https://github.com/AssemblyScript/assemblyscript/blob/454529dcc4597e7b5bdd338ff101e97d3e18b05b/tests/compiler/rt/finalize.ts#L1-L13

I found a problem, the ptr changes every time after resize

how to solve this problem?

**Comment by dcodeIO** [comment]
From the mention of "resize" I assume that these are the backing buffers of the respective arrays. When resized, a new backing buffer is allocated and the old one is left for the GC. The array object itself remains if it is still referenced, it's just the buffers.

**Comment by LukiYLS** [comment]
After memory.grow, I can find the object through **changetype** in the __finalize function, and then call the object's destructor function

```
// @ts-ignore 
 @global function __finalize(ptr: usize): void { 
   let object = changetype<Object>(ptr)
   object.finalize()
 } 
```

In this way, I find that sometimes an exception is thrown

**Comment by dcodeIO** [comment]
Not every `ptr` free'd is an `Object`. Looking at the class id might help:

```ts
import { OBJECT, TOTAL_OVERHEAD } from "rt/common";

@global function __finalize(ptr: usize): void { 
  var obj = changetype<OBJECT>(ptr - TOTAL_OVERHEAD)
  if (obj.rtId == idof<Object>()) {
    ...
  }
}
```
