### ISSUE TITLE
Publish assemblyscript and @assemblyscript/loader to npm

### ISSUE THREAD

**Issue by xtuc** [AssemblyScript/assemblyscript#206]
The loader here https://github.com/AssemblyScript/assemblyscript/blob/dc0f271fc239a3d27d67ffdefe4a61343a5bb2ba/lib/loader/package.json#L2

is not available on npm: https://www.npmjs.com/package/@assemblyscript/loader.

**Comment by xtuc** [comment]
And what's the difference with https://www.npmjs.com/package/assemblyscript-loader?

**Comment by dcodeIO** [comment]
Both the `assemblyscript` and the `assemblyscript-loader` package on npm are outdated and belong to the old prototype. Master isn't on npm yet, neither the compiler nor the new loader.

**Comment by xtuc** [comment]
Ok. Also it seems that array utils have not been implemented from the prototype. 

Should we leave this open?

**Comment by dcodeIO** [comment]
Sure, changed the title to keep track of it. Once it's known that GC isn't completely broken, I think we can go ahead and publish a first version of the new compiler and utilities.

**Comment by MaxGraey** [comment]
And follow semver convention?

**Comment by dcodeIO** [comment]
Afaik, all `0.X` versions are treated like an "unstable" major version. So going with `0.5.0` should be fine, unless I'm mistaken.

**Comment by xtuc** [comment]
Yes, that's my understand of semver too. Thanks for the work!

**Comment by MaxGraey** [comment]
Currently GC require manual importing anyway. As I understand when allocator and gc will be provide explicitly by default this flag will be appear

**Comment by JounQin** [comment]
If the npm versions are outdated, then why are you not publishing the latest versions to npm?

**Comment by cdetrio** [comment]
> Sure, changed the title to keep track of it. Once it's known that GC isn't completely broken, I think we can go ahead and publish a first version of the new compiler and utilities.

It's one year later, is the GC still completely broken?

**Comment by MaxGraey** [comment]
@cdetrio GC was completely rewritten and use ARC for acyclic references and GC for cyclic references and should work more or less stable for now

**Comment by MaxGraey** [comment]
Closed in favour #750
