### ISSUE TITLE
Typo in return before class construction crashes compiler

### ISSUE THREAD

**Issue by endercrest** [AssemblyScript/assemblyscript#2082]
Ran into a scenario where I had a typo in a return statement that caused the compiler to crash. Expected the code below to provide a useful error instead of crashing the compiler.

Code: 
```typescript
class Test {}

export function test() {
  retun new Test();
}
```

WebAssembly Studio: https://webassembly.studio/?f=8qsn9gum0sr

Error: 
```
[info]: Task build is running...
[error]: Task build failed: assertion failed
```

**Comment by dcodeIO** [comment]
Taking a quick look, the problem is at

https://github.com/AssemblyScript/assemblyscript/blob/250dc70b42531b89e23a8b01a9f659b6181f5e44/src/parser.ts#L4398

where the `new` token is incorrectly handled as a non-starting token.
