### ISSUE TITLE
rewrite __visit of class only effect in ~/lib

### ISSUE THREAD

**Issue by HerrCai0907** [AssemblyScript/assemblyscript#2083]
This project will crash if class A define in folder `assembly/` but can run correctly if class A define in `node_modules/xxx/assembly` and imported.
```
function foo(): A {
    let b = [11, 2].concat([3]);
    let a = new A(changetype<usize>(b));
    return a;
}
export function test(): void {
    let a = foo();
    __collect();
    trace(changetype<i32[]>(a.obj)[0].toString());
}
```

```
@final export class A {
    obj: usize;
    constructor(ptr: usize) {
        this.obj = changetype<usize>(ptr);
    }
    @unsafe private __visit(cookie: u32): void {
        trace("gc A");
        if (this.obj != 0) __visit(this.obj, cookie);
    }
}
```

**Comment by dcodeIO** [comment]
This is currently intended since `__visit` is unsafe and an internal mechanism. Perhaps reusing the `@unsafe` decorator there instead, as in your second snippet (which currently doesn't do what the snippet expects), would be an improvement?

**Comment by HerrCai0907** [comment]
reusing the `@unsafe` decorator looks like a good idea, because when I use `@unsafe` decorator, it means I know what I'm doing now.
