### ISSUE TITLE
Automatically changetype for extended/inherited methods/functions - Upcast runtime error

### ISSUE THREAD

**Issue by otaviopace** [AssemblyScript/assemblyscript#2088]
Given the following example:

```typescript
class A {
  static build(): A {
    return new A()
  }
}

class B extends A { }

let b: B = B.build() // compile time error
let b = B.build() as B // run time error, because it thinks is doing an upcast
let b = changetype<B>(B.build()) // works, but not the most pleasant
```

A possible solution is to write wrappers like these:
```typescript
class B extends A {
  static build(): B {
    return changetype<B>(A.build())
  }
}
```

But writing these by hand for every inherited method/function would be very cumbersome and defeat the purpose of using `extends X`.

Do you think it would make sense for the compiler to do this automatically? I never contributed to the project, if you think this would be a good addition/fix and show me the way/path I can try to do it 🙂 

Also, a bit more about this case:

```typescript
let b = B.build() as B
```

From my understanding because downcasting is not safe (only allowed with the `changetype` helper function), the error given to the user is related to `upcast`ing, that's probably because it's the only safe cast allowed right? Do you think there's a way to make the compiler realize this is safe to use `as T`/`<T>`?

**Comment by dcodeIO** [comment]
Unless I'm missing something, on a first glimpse returning an `A` and `changetype`ing it to `B` seems unsound, since it is indeed an upcast and the object is not guaranteed to be a `B`. To make it sound, the wrappers would have to `new B` I think?

**Comment by otaviopace** [comment]
Good point on the sound part. I didn't understand what you meant about using `new B` in the wrappers, can you elaborate more please?

**Comment by dcodeIO** [comment]
What I meant is that if `B` inherits a static method from `A` that returns `A`, a wrapper would only help if it would both `new` and return `B` where the original function `new`ed `A` and returned `A`. That would be sound type-wise, but otherwise wrong.

**Comment by MaxGraey** [comment]
Also I don't recommend use `changetype` in this scenarios. `changetype` is unsound and should be used in low-level cases like deref to `usize` for example

**Comment by otaviopace** [comment]
@dcodeIO yes I see.

@MaxGraey how do you recommend doing code like this?

We have libraries with inheritance like this and `changetype` is the only way we found to explain to our users on how they can use the inherited methods, and it is quite confusing to some of them.

Thats why we're considering doing the wrappers ourselves by hand, but again, that would be very cumbersome.

**Comment by MaxGraey** [comment]
```ts
class A {
  static build<T>(): T {
    return instantiate<T>();
  }
}

class B extends A { }

let b = B.build<B>();
```

**Comment by otaviopace** [comment]
Oh I see, but doing the parameterized type on a super type is not the most intuitive user experience in my opinion.

@MaxGraey yes, doing `new A() as B` is indeed illegal, my problem is that you can't do `new B() as A` in AssemblyScript, you have to use `changetype` because it's not considered safe.

**Comment by MaxGraey** [comment]
> my problem is that you can't do new B() as A in AssemblyScript, you have to use changetype because it's not considered safe.

[That's should work](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY2xhc3MgQSB7CiAgc3RhdGljIGJ1aWxkKCk6IEEgewogICAgcmV0dXJuIG5ldyBBKCkKICB9CiAgZm9vKCk6IHN0cmluZyB7CiAgICByZXR1cm4gIkEiCiAgfQp9CgpjbGFzcyBCIGV4dGVuZHMgQSB7CiAgZm9vKCk6IHN0cmluZyB7CiAgICByZXR1cm4gIkIiCiAgfQp9Cgpjb25zdCBiID0gbmV3IEIoKSBhcyBBOwoKYXNzZXJ0KGIuZm9vKCkgPT0gIkIiKTsKIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQogICAgb3V0cHV0LnZhbHVlICs9IGBPayFgOwogIH0pCjwvc2NyaXB0Pg==)

In your example I see only `new A() as B` CASE.

**Comment by otaviopace** [comment]
Sorry, I've written it incorrectly, I mean that doing: `B.build() as A` is not allowed, I wanted that.

[Editor link](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmNsYXNzIEEgewogIHN0YXRpYyBidWlsZCgpOiBBIHsKICAgIHJldHVybiBuZXcgQSgpCiAgfQogIGZvbygpOiBzdHJpbmcgewogICAgcmV0dXJuICJBIgogIH0KfQoKY2xhc3MgQiBleHRlbmRzIEEgewogIGZvbygpOiBzdHJpbmcgewogICAgcmV0dXJuICJCIgogIH0KfQoKY29uc3QgYiA9IEIuYnVpbGQoKTsKCmFzc2VydChiLmZvbygpID09ICJCIik7CiMhaHRtbAo=).

**Comment by dcodeIO** [comment]
`B.build() as B` is illegal type-wise, though, since it returns `A` which is not guaranteed to be an `instanceof B`. If it in fact is an `instanceof B`, only then the cast works.

**Comment by MaxGraey** [comment]
> Sorry, I've written it incorrectly, I mean that doing: B.build() as A is not allowed, I wanted that.

It shouldn't be possible because you're trying upcast of superclass to subclass instance which shouldn't work in most of cases. I admit that this might have worked before, provided the form of the classes was no different and lang has some unsoundness, but it was wrong and dangerous. With structural typing this is also possible in some cases, but AS at cuttent stage is a nominal language with an OOP model. In such languages, such a procedure is dangerous and forbidden

**Comment by otaviopace** [comment]
@dcodeIO It doesn't work on the "legal" cases, whereas `B` in `as B` is a subtype of `A`. The only way to work is by using `changetype`.

**Comment by otaviopace** [comment]
@MaxGraey I don't see how allowing a cast such as `B.build() as B` is a problem. IMO this should fail if the return type of `build` (in this case `A`) is not a supertype of the `as` part, `B`.

**Comment by dcodeIO** [comment]
A legal case would be `B.build() as A`, which will always work since the value is guaranteed to be an `instanceof A`, statically even. In the case of `B.build() as B` the compiler will insert a runtime check that the cast is OK, which is the error you are seeing since the returned value is not `instanceof B`.

**Comment by MaxGraey** [comment]
>  I don't see how allowing a cast such as B.build() as B is a problem

B.build() actually return `A` not `B`. So basically you have `new A() as B` case which is illegal

**Comment by otaviopace** [comment]
In `B.build() as A` the cast is unnecessary, `build` already returns `A`. What I think it should be possible is to cast it to `B`.

This should be allowed in my understanding (please teach me if I'm having the wrong vision/perception on the subject) because `B` is a subtype of `A`. The cast is legal/valid.

**Comment by otaviopace** [comment]
In this example:

> ```ts
> function somethingReturningSomeA(): A { ... }
> 
> var a = somethingReturningSomeA();
> if (a instanceof B) {
>   let b = a as B;
>   ...
> } else {
>   // handle the case where it is not a B
> }
> ```

This `if`:
```typescript
if (a instanceof B) {
```

will never be true.

**Comment by otaviopace** [comment]
I'm not sure if we should talk on Discord though hahah.

I think I might have to learn something on the subject with you guys 😄

**Comment by dcodeIO** [comment]
If it is never a `B`, why are you trying to cast it to a `B` then even though it is wrong? :)

**Comment by otaviopace** [comment]
That's the problem, I don't see why this is wrong if we have the following inheritance: `A < B`.

**Comment by otaviopace** [comment]
It should fail in runtime / be illegal if the cast is being done whereas this is not true: `A < B`.

**Comment by MaxGraey** [comment]
@dcodeIO I think we should handle this case on compile time and output proper compile time error

**Comment by dcodeIO** [comment]
There, a `B` is always an `A`, but an `A` is not necessarily a `B`.

**Comment by MaxGraey** [comment]
but with `changetype` it's little bit tricky

**Comment by otaviopace** [comment]
> There, a `B` is always an `A`, but an `A` is not necessarily a `B`.

Indeed you're correct. The `Animal` example is great.

I think what's confusing is that usually in most of the languages I've used what happens if you do a cast like this that isn't necessarly safe is:

- If the class/type inheritance is satisfied, the cast works and the programs continues sucessfully
- If the type hierarchy is incorrect, the program fails at runtime (depending on the language you can catch with tools such as `try`/`catch`

Sorry for making this discussion so long, I really appreciate all of your help to make me understand the subject ❤️ .

**Comment by otaviopace** [comment]
> I think what makes this a little confusing is that the same cast works in TypeScript because it implements a structural type system. In such a type system, if the shapes of two classes are the same, the type checker will not complain (TS doesn't actually insert runtime casts since there are none in JS but only checks in the IDE). AssemblyScript, however, is more like Java or similar languages in this regard and implements a nominal type system.

Honestly I didn't do much `TypeScript` coding, doesn't Java work as the example I gave? (tries casting at runtime, if it works 🎉 , if not it breaks at runtime 💥 ).

**Comment by MaxGraey** [comment]
In Java or C# or other OOP langs you can't do this as well:
https://stackoverflow.com/questions/47803691/java-upcasting-to-a-superclass-and-calling-function-from-the-subclass

**Comment by otaviopace** [comment]
🤔  It seems that this works:

```java
public class A {
    public static A build() {
        return new A();
    } 
}

public class B extends A {
}

public class MyClass {
    public static void main(String args[]) {
        B b = (B)B.build();
    }
}
```

Let me double check.

**Comment by MaxGraey** [comment]
> It seems that this works:

It may works until you call some method which exists in B but not exists in A. But it's depend on runtime implementation.

**Comment by MaxGraey** [comment]
Yeah. This failed in runtime with error:
```
Exception in thread "main" java.lang.ClassCastException: class A cannot be cast to class B (A and B are in unnamed module of loader 'app')
    at Main.main(Main.java:12)
```

**Comment by otaviopace** [comment]
Okay, I guess I have this wrong perception from a dynamic language I've used in the past.

Thanks again for the help, I'm closing this!
