### ISSUE TITLE
Loader cannot access the subarray correctly

### ISSUE THREAD

**Issue by limerhyme** [AssemblyScript/assemblyscript#2091]
I am trying to use Loader to access the TypedArray of wasm.
I can access the original array, but there is a problem when accessing its subarray.
When I get the subarray with `__getArrayView`, it appears as an empty array.
I guess that it is probably a problem of Loader, since subarray is working correctly inside wasm.
I think it would be useful to have access in this way.

MWE: [AssemblyScript Editor](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1ub25lJnJ1bnRpbWU9aW5jcmVtZW50YWwmZXhwb3J0UnVudGltZQpsZXQgYXJyOiBJbnQzMkFycmF5IHwgbnVsbCA9IG51bGwKbGV0IHN1YmFycjogSW50MzJBcnJheSB8IG51bGwgPSBudWxsCgpleHBvcnQgZnVuY3Rpb24gZ2EoKTogSW50MzJBcnJheSB7CiAgaWYgKCFhcnIpIHsKICAgIGFyciA9IG5ldyBJbnQzMkFycmF5KDEwKQogIH0KICByZXR1cm4gYXJyIGFzIEludDMyQXJyYXkKfQoKZXhwb3J0IGZ1bmN0aW9uIGdiKCk6IEludDMyQXJyYXkgewogIGlmICghc3ViYXJyKSB7CiAgICBzdWJhcnIgPSBnYSgpLnN1YmFycmF5KDUpCiAgfQogIHJldHVybiBzdWJhcnIgYXMgSW50MzJBcnJheQp9CgpleHBvcnQgZnVuY3Rpb24gZ2MoKTogdm9pZCB7CiAgY29uc3QgcyA9IGdiKCkKICBzWzBdID0gNDIKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignI291dHB1dCcpCiAgICBvdXRwdXQudmFsdWUgPSAnJwogICAgdHJ5IHsKICAgICAgY29uc3QgcHRyID0gZXhwb3J0cy5fX3BpbihleHBvcnRzLmdhKCkpCiAgICAgIGV4cG9ydHMuZ2MoKQogICAgICBjb25zdCBhcnIgPSBleHBvcnRzLl9fZ2V0QXJyYXlWaWV3KHB0cikKICAgICAgb3V0cHV0LnZhbHVlICs9IGBhcnI6IGxlbmd0aD0ke2Fyci5sZW5ndGh9LCBieXRlTGVuZ3RoPSR7YXJyLmJ5dGVMZW5ndGh9LCBkYXRhPSR7YXJyfVxuYAogICAgICBjb25zdCBzcHRyID0gZXhwb3J0cy5fX3BpbihleHBvcnRzLmdiKCkpCiAgICAgIGNvbnN0IHN1YmFyciA9IGV4cG9ydHMuX19nZXRBcnJheVZpZXcoc3B0cikKICAgICAgb3V0cHV0LnZhbHVlICs9IGBzdWJhcnI6IGxlbmd0aD0ke3N1YmFyci5sZW5ndGh9LCBieXRlTGVuZ3RoPSR7c3ViYXJyLmJ5dGVMZW5ndGh9LCBkYXRhPSR7c3ViYXJyfVxuYAogICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgIG91dHB1dC52YWx1ZSA9IGAke2Vycn1gCiAgICB9CiAgfSkKPC9zY3JpcHQ+)
```ts
// module.ts
let arr: Int32Array | null = null
let subarr: Int32Array | null = null

export function ga(): Int32Array {
  if (!arr) {
    arr = new Int32Array(10)
  }
  return arr as Int32Array
}

export function gb(): Int32Array {
  if (!subarr) {
    subarr = ga().subarray(5)
  }
  return subarr as Int32Array
}

export function gc(): void {
  const s = gb()
  s[0] = 42
}
```
```html
// index.html
<textarea id="output" style="height: 100%; width: 100%" readonly></textarea>
<script>
loader.instantiate(module_wasm, { /* imports */ })
  .then(({ exports }) => {
    const output = document.querySelector('#output')
    output.value = ''
    try {
      const ptr = exports.__pin(exports.ga())
      exports.gc()
      const arr = exports.__getArrayView(ptr)
      output.value += `arr: length=${arr.length}, byteLength=${arr.byteLength}, data=${arr}\n`
      const sptr = exports.__pin(exports.gb())
      const subarr = exports.__getArrayView(sptr)
      output.value += `subarr: length=${subarr.length}, byteLength=${subarr.byteLength}, data=${subarr}\n`
    } catch (err) {
      output.value = `${err}`
    }
  })
</script>
```
Expected Behavior:
```
arr: length=10, byteLength=40, data=0,0,0,0,0,42,0,0,0,0
subarr: length=5, byteLength=20, data=42,0,0,0,0
```
Actual behavior (the subarray appears as an empty array):
```
arr: length=10, byteLength=40, data=0,0,0,0,0,42,0,0,0,0
subarr: length=0, byteLength=0, data=
```

**Comment by MaxGraey** [comment]
`__getArrayView` is unsafe due to provide only view in linear memory. It can be used if you know what you are doing and can guarantee that no memory allocation (explicit or implicit) by AssemblyScript will happen between receiving a pointer and the actual use (reading, copying, processing) of that buffer view. In all other cases it is better to use __getArray or __getUint32Array and its friends. In this case it will be a copy of that representation, which is always safe even if the linear memory is changed and the buffer associated with this memory is detached.

**Comment by limerhyme** [comment]
@MaxGraey Thank you for your reply.
I would like to discuss how to access (i.e. read/write) the subarray.
In fact, this still happens even if I replace `__getArrayView` with `__getArray` or `__getInt32Array` 😢  (see [this example](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1ub25lJnJ1bnRpbWU9aW5jcmVtZW50YWwmZXhwb3J0UnVudGltZQpsZXQgYXJyOiBJbnQzMkFycmF5IHwgbnVsbCA9IG51bGwKbGV0IHN1YmFycjogSW50MzJBcnJheSB8IG51bGwgPSBudWxsCgpleHBvcnQgZnVuY3Rpb24gZ2EoKTogSW50MzJBcnJheSB7CiAgaWYgKCFhcnIpIHsKICAgIGFyciA9IG5ldyBJbnQzMkFycmF5KDEwKQogIH0KICByZXR1cm4gYXJyIGFzIEludDMyQXJyYXkKfQoKZXhwb3J0IGZ1bmN0aW9uIGdiKCk6IEludDMyQXJyYXkgewogIGlmICghc3ViYXJyKSB7CiAgICBzdWJhcnIgPSBnYSgpLnN1YmFycmF5KDUpCiAgfQogIHJldHVybiBzdWJhcnIgYXMgSW50MzJBcnJheQp9CgpleHBvcnQgZnVuY3Rpb24gZ2MoKTogdm9pZCB7CiAgY29uc3QgcyA9IGdiKCkKICBzWzBdID0gNDIKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignI291dHB1dCcpCiAgICBvdXRwdXQudmFsdWUgPSAnJwogICAgdHJ5IHsKICAgICAgY29uc3QgcHRyID0gZXhwb3J0cy5fX3BpbihleHBvcnRzLmdhKCkpCiAgICAgIGV4cG9ydHMuZ2MoKQogICAgICAvL2NvbnN0IGFyciA9IGV4cG9ydHMuX19nZXRBcnJheVZpZXcocHRyKQogICAgICAvL291dHB1dC52YWx1ZSArPSBgYXJyOiBsZW5ndGg9JHthcnIubGVuZ3RofSwgYnl0ZUxlbmd0aD0ke2Fyci5ieXRlTGVuZ3RofSwgZGF0YT0ke2Fycn1cbmAKICAgICAgY29uc3Qgc3B0ciA9IGV4cG9ydHMuX19waW4oZXhwb3J0cy5nYigpKQogICAgICAvL2NvbnN0IHN1YmFyciA9IGV4cG9ydHMuX19nZXRBcnJheVZpZXcoc3B0cikKICAgICAgLy9vdXRwdXQudmFsdWUgKz0gYHN1YmFycjogbGVuZ3RoPSR7c3ViYXJyLmxlbmd0aH0sIGJ5dGVMZW5ndGg9JHtzdWJhcnIuYnl0ZUxlbmd0aH0sIGRhdGE9JHtzdWJhcnJ9XG5gCiAgICAgIGNvbnN0IHMxID0gZXhwb3J0cy5fX2dldEFycmF5KHNwdHIpCiAgICAgIG91dHB1dC52YWx1ZSArPSBgczE6IGxlbmd0aD0ke3MxLmxlbmd0aH0sIGJ5dGVMZW5ndGg9JHtzMS5ieXRlTGVuZ3RofSwgZGF0YT0ke3MxfVxuYAogICAgICBjb25zdCBzMiA9IGV4cG9ydHMuX19nZXRJbnQzMkFycmF5KHNwdHIpCiAgICAgIG91dHB1dC52YWx1ZSArPSBgczI6IGxlbmd0aD0ke3MyLmxlbmd0aH0sIGJ5dGVMZW5ndGg9JHtzMi5ieXRlTGVuZ3RofSwgZGF0YT0ke3MyfVxuYAogICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgIG91dHB1dC52YWx1ZSA9IGAke2Vycn1gCiAgICB9CiAgfSkKPC9zY3JpcHQ+)).
Let me ask a new question to clarify the issue:
**Q**. In my example, how can I use Loader to read data from the subarray returned by the `gb` function? Or, is this kind of operation not allowed?

**Comment by MaxGraey** [comment]
Yeah. It seems I know what's wrong. [Here](https://github.com/AssemblyScript/assemblyscript/blob/main/lib/loader/index.js#L283) we should set byteOffset derived from AS typedarray
