### ISSUE TITLE
see "Import '~lib/fs-extra' not found." when run asbuild 

### ISSUE THREAD

**Issue by linzg2002** [AssemblyScript/assemblyscript#2094]
As a beginner of assemblyscript, I just created a project with WASME and want to include some npm libraries into the  project. 
The first library I choosed is fs-extra. I added it by `npm i @types/fs-extra`. 
To be simple,  I just add an import line to my index.ts like `import {writeFile} from "fs-extra";`
But when run `npm run asbuild`, the error pops like 
```
ERROR: Import '~lib/fs-extra' not found.
    at parseBacklog (/mnt/d/projects/new-filter2/node_modules/assemblyscript/cli/asc.js:498:34)
    at Object.main (/mnt/d/projects/new-filter2/node_modules/assemblyscript/cli/asc.js:554:16)
    at asc.ready.then (/mnt/d/projects/new-filter2/node_modules/assemblyscript/bin/asc:21:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
Am I using the assemblyscript in the right way? Could somebody give any advice? In general, I'd just like to access the local files within my assmeblyscript project. Is it possible?
Looking forward of your kind reply, thanks.

**Comment by romdotdog** [comment]
Only AS libraries may be imported from AS. fs-extra is a node.js library, not an AS library.

**Comment by linzg2002** [comment]
@romdotdog thanks for your reply. Is there any reference doc about entire AS libraries can be used?
About read fs, I am curious about hwo to write the JS function to the return the file's contents. As in the function itself, will it still need to import some utility library to do the file operation? So must the library be AS library aslo?
It will be great if some code snippet can be referred.

**Comment by MaxGraey** [comment]
>  Is there any reference doc about entire AS libraries can be used?

https://www.assemblyscript.org/built-with-assemblyscript.html

Although, of course, not everything is there.

> About read fs, I am curious about hwo to write the JS function to the return the file's contents. As in the function itself, will it still need to import some utility library to do the file operation?

See as-wasi: https://github.com/jedisct1/as-wasi

**Comment by linzg2002** [comment]
@MaxGraey Many thanks, I will have a try,
