### ISSUE TITLE
A extends B<A>: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mooooooi** [AssemblyScript/assemblyscript#2095]
```typescript
@unmanaged
export class Struct<T> {
  constructor(offset?: number) {
    if (offset == null) {
      offset = heap.alloc(offsetof<T>());
    }
    // @ts-ignore
    return changetype<T>(offset);
  }

  clone(): T {
    const ptr = heap.alloc(offsetof<T>());
    return changetype<T>(ptr);
  }

  dispose(): void {
    heap.free(changetype<usize>(this));
  }
}

@unmanaged
export class Entity extends Struct<Entity> {
  id: i32;
  version: i32;
}
```

**Comment by MaxGraey** [comment]
that's `constructor(offset?: number) {` not valid in AS

**Comment by mooooooi** [comment]
How able the (example)[https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmNsYXNzIEE8VD4gewogIGNvbnN0cnVjdG9yKCkgewogICAgY29uc3QgdFNpemUgPSBzaXplb2Y8VD4oKTsKICAgIGNvbnN0IHB0ciA9IGhlYXAuYWxsb2ModFNpemUpOwogICAgcmV0dXJuIGNoYW5nZXR5cGU8VD4ocHRyKTsKICB9Cn0KCmNsYXNzIEIgZXh0ZW5kcyBBPEI+IHsKICBoOiBpMzIgPSAwCn0KCmZ1bmN0aW9uIG1haW4oKTogdm9pZCB7CiAgbGV0IGIgPSBuZXcgQigpCiAgYi5oID0gMTIzCn0KCgptYWluKCkKIyFodG1sCg==] ?
