### ISSUE TITLE
Importing functions from other files

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#21]
Hello! I'm currently working on a large project (for fun) in Assembly script.

And I couldn't quite figure out how to split out my code into multiple files, to be imported/exported in an index.ts.

[Here is a link to my assemblyscript files in my repo](https://github.com/torch2424/wasmBoy/tree/master/wasm)

I know the project is still very new, and if it is not implemented yet, no worries! Thanks for making this awesome project!

P.S I'm hoping I can find time to contribute, because I'm really looking forward to using this in more projects in the future 😄

**Comment by dcodeIO** [comment]
Exports and imports should just work, that is if you are using current master.

**Comment by torch2424** [comment]
Hello!

Thanks for the super quick reply!

So I pulled the latest mater on [January, 23rd](https://github.com/torch2424/wasm-playground/commits/master), has it changed since then?

and if it is not too much to ask, could you post a quick code example?

And again, thanks for all the hard work!

**Comment by dcodeIO** [comment]
> has it changed since then?

It's constantly changing, but I haven't touched imports/exports recently.

> could you post a quick code example?

There's [this test](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/reexport.ts) for example.

**Comment by torch2424** [comment]
Oh that's perfect thanks! Do you mind if I contribute a simple project example under [the examples](https://github.com/AssemblyScript/assemblyscript/tree/master/examples) displaying exports and imports? Maybe something like a small Fibonacci sequence or something.

Also on the topic of that, I know [Maps] are incomplete, but if I were to expose them like sets in [assembly definitions](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly.d.ts) could I use the functionality they currently have?

And you solved this issue, I'll close it after your next reply, thank you for your time!

**Comment by dcodeIO** [comment]
> Maybe something like a small Fibonacci sequence or something.

Not sure, I am trying to provide somewhat meaningful examples and exports and imports are already mentioned in the showcase test.

> I know Maps are incomplete, but if I were to expose them like sets in assembly definitions could I use the functionality they currently have?

You can try, but be warned that these aren't real set/map implementations, just untested fillers using arrays under the hood. Also note that string keys won't work yet because operator overloads aren't evaluated yet.

**Comment by torch2424** [comment]
Ahhh makes sense, cool, thank you! I'll be sure to look through the tests if I need to figure something out.

If I come up with another contribution idea, I'll make an issue to discuss.

Again, thanks for your help! Closing this!
