### ISSUE TITLE
Is it possible to read/create an image file and send it to JS?

### ISSUE THREAD

**Issue by drachehavoc** [AssemblyScript/assemblyscript#211]
I'm trying to create/read an image file and write this in a canvas on the JS side.

I'm thinking in write the file to memory and send a pointer to JS, wich will read and write it into a DOM canvas,

is it possible? how? anyone can write a code example?

_sorry for my English, I'm Brazilian and Portuguese is my main language._

**Comment by dcodeIO** [comment]
The [Game of Life example](https://github.com/AssemblyScript/assemblyscript/tree/master/examples/game-of-life) computes a pixel buffer in WebAssembly memory, and then copies that, without further ado, to an image buffer on a canvas. The only oddity to take care of there is that i32 RGB values are little endian on the WASM side, so the AssemblyScript code processes pixels in BGRA order so these become ARGB on the JS side. Is that about what you are looking for?

**Comment by drachehavoc** [comment]
It's exactly the kind of thing I'm trying to do, but I do not understand that example, I need a simple tutorial.

can you help me?

**Comment by dcodeIO** [comment]
I can't provide a step by step tutorial unfortunately, but if you have specific questions regarding the example, feel free to ask.

**Comment by drachehavoc** [comment]
I will try harder to understand "the game of life".

tks.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
