### ISSUE TITLE
How to debug in Intellij with NodeJS?

### ISSUE THREAD

**Issue by Dudeplayz** [AssemblyScript/assemblyscript#2119]
Hi,
I have an AssemblyScript program I like to debug. But with the existing documentation, I can't figure out how to do that. I'm using Intellij and NodeJS.
Hopefully, someone can help me, I can't solve my problems without it.

**Comment by dcodeIO** [comment]
Haven't used Intellij in a while, but would assume that the process should be about the same as debugging JS, since JS loads the Wasm module and then it runs in the same process.

**Comment by Dudeplayz** [comment]
Ok, I have to test it again. But how do I load the source map? I'm instantiating by loading the file from filesystem. Some documentation/guide would be very helpful. Also for others I think.

**Comment by dcodeIO** [comment]
The last time I checked, on Node.js it requires adding an absolute path to the source map to the Wasm, which can be done by using the `--sourceMap path/to/source.map` argument (with a path). In browsers that's not necessary since the `fetch` carries relative location information.

**Comment by Dudeplayz** [comment]
Ok, I now have understand the documentation and the --sourceMap parameter. In the wasm file, it seems to be specified correctly now. But when I set a Breakpoint in IntelliJ and start the debug, it doesn't halt at the breakpoint. I'm able to jump into the root AssemblyScript file from the JS method call. But I can't jump in another method from there.
