### ISSUE TITLE
Question about some figures of memory layout

### ISSUE THREAD

**Issue by kyasbal-1994** [AssemblyScript/assemblyscript#213]
I've read some part of this page to read array directly from memory with javascript.
https://github.com/AssemblyScript/assemblyscript/wiki/Memory-Layout-&-Management

```
╒═══ Array<T> ══╕
 7 6 5 4 3 2 1 0  bits
├─┴─┴─┴─┴─┴─┴─┴─┤
│    .buffer    │ points at the backing ArrayBuffer (private)
├───────────────┤
│    .length    │ number of array elements of size sizeof<T>()
└───────────────┘
````
As far as I see this figure, this `.buffer` only have a byte. But I don't think that is correct and reasonable.
I think `.buffer` or several other fields denoted as a byte in some figures must have 4 bytes.

Is this a correct assumption?

**Comment by dcodeIO** [comment]
Oh, yes, these fields are 32-bits.

**Comment by kyasbal-1994** [comment]
Thank you for fixing that. Now it seems to be fine at all. I will close this issue. Thanks.
