### ISSUE TITLE
Why is the supplied code behaving like explaint?

### ISSUE THREAD

**Issue by Dudeplayz** [AssemblyScript/assemblyscript#2131]
Hi,
I have the following function:
```
export function compute(pc : u32, opcode : u16) : u32{
  return pc + (((opcode & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0));
}
```
The function is called from JS site with the parameters `compute(65, 63457)`.
The result of this function call is `65597`. If I change the `opcode` to `u32` the result is `61`, which is the result I expect to get. For me, it looks like some type-overflow. I can also fix it by doing the following things:

`return pc + (((opcode as u32 & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0));`
`return pc + (((opcode & 0x1f8 as u32) >> 3) - (opcode & 0x200 ? 0x40 : 0));`
`return pc + (((opcode & 0x1f8) >> 3 as u32) - (opcode & 0x200 ? 0x40 : 0));`
`return pc + (((opcode & 0x1f8) >> 3) as u32 - (opcode & 0x200 ? 0x40 : 0));`

Modifying the right statement with `as u32` does nothing.

The strange thing is if I do this:

```
export function compute() : u32{
  const pc : u32 = 65;
  const opcode : u16 = 63457
  return pc + (((opcode & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0));
}
```
... it also works.

So can someone explain to me what happens here?

**Comment by dcodeIO** [comment]
Execution order there is `(opcode & 0x1f8) >> 3` = 60, `opcode & 0x200 ? 0x40 : 0` = 64, then computing `60 - 64` in an `u16` context, wrapping around to `65532`. Then, in `u32` context, `65 + 65532` = 65597.

The difference in the second sample results from the compiler inlining `const opcode : u16 = 63457`, where something seems to go wrong. Need to investigate. Changing the `const` to a `let` produces the same result as the former.

**Comment by MaxGraey** [comment]
That's because your code with `u16` basically equal to this:
```ts
pc + ((((opcode & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0)) & 0xFFFF);
```
let's simplify this to
```ts
pc + (a - b);
```
if `a` and `b` are `u16` all operations associated with this vars also will be `u16`. In this case it's `-`.

It little bit different from C/C++ which always course (ucast) small types to 32-bit. AssemblyScript and Rust always preserve type for all operations.

**Comment by MaxGraey** [comment]
If you want to take same effect without change input type you could use this:
```ts
export function compute(pc : u32, opcode : u16) : u32{
  return pc + (((opcode & 0x1f8) >> 3) as u32 - (opcode & 0x200 ? 0x40 : 0) as u32);
}
```

**Comment by MaxGraey** [comment]
However issue with constant case is real issue.

**Comment by Dudeplayz** [comment]
> That's because your code with `u16` basically equal to this:
> 
> ```ts
> pc + ((((opcode & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0)) & 0xFFFF);
> ```
> 
> let's simplify this to
> 
> ```ts
> pc + (a - b);
> ```
> 
> if `a` and `b` are `u16` all operations associated with this vars also will be `u16`. In this case it's `-`.
> 
> It little bit different from C/C++ which always course (ucast) small types to 32-bit. AssemblyScript and Rust always preserve type for all operations.

Hello @MaxGraey 
thanks for the explanation, but I have a few questions left:
1. Why does this overflow does not happen if the opcode is u32? Then it is still `pc + (a-b)` in that case `(a-b)` should also get a turnaround?
2. Why works
 ```typescript
return pc + (((opcode & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0 as u32))
```
but not
```typescript
return pc + (((opcode & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0) as u32)
```
3. How are these statements evaluated? From right to left always using the left type?

**Comment by MaxGraey** [comment]
> but not
> return pc + (((opcode & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0) as u32)

Becouse wrap to u16 make sense only for `((opcode & 0x1f8) >> 3)` in this sample.
`(opcode & 0x200 ? 0x40 : 0) as u32` or `(opcode & 0x200 ? 0x40 : 0) as u16` is doen't matter in both cases it will be same result

**Comment by Dudeplayz** [comment]
@MaxGraey and what is different between the first statement and the third (added later)?

**Comment by MaxGraey** [comment]
However `return pc + (((opcode & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0 as u32))` case is interesting. That's should behave the same as below one.

**Comment by dcodeIO** [comment]
The `as u32` case wraps around twice, but on `u32` range:

```
65 + (60 - 64) = 65 + 4294967292 = 61
        ^^^        ^^^
```

**Comment by Dudeplayz** [comment]
@dcodeIO now I got it. Thanks!

Next question:
What is the difference between
```typescript
return pc + (((opcode & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0) as u32)
```
and
```typescript
return pc + (((opcode & 0x1f8) >> 3) - <u32>(opcode & 0x200 ? 0x40 : 0));
```
?

**Comment by Dudeplayz** [comment]
> However `return pc + (((opcode & 0x1f8) >> 3) - (opcode & 0x200 ? 0x40 : 0 as u32))` case is interesting. That's should behave the same as below one.

And why behave the third:
```typescript
return pc + (((opcode & 0x1f8) >> 3) - ((opcode & 0x200 ? 0x40 : 0) as u32))
```
also like the first one?
