### ISSUE TITLE
How to get jest running with assemblyscript/loader

### ISSUE THREAD

**Issue by Dudeplayz** [AssemblyScript/assemblyscript#2139]
Hi,
I have a project, where I try to use some existing jest tests to test the wasm compiled code. Unfortunately, I don't get it working. I tried different jest configurations and always get the following error:

```bash
    C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\@assemblyscript\loader\index.js:352
    export async function instantiate(source, imports = {}) {
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      3 | exports.was = exports.writeHooks = void 0;
      4 | const fs = require("fs");
    > 5 | const loader = require("@assemblyscript/loader");
        |                ^
      6 | exports.writeHooks = {};
      7 | // @ts-ignore
      8 | exports.was = loader.instantiateSync(fs.readFileSync(__dirname + "/../build/untouched.wasm"), {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1723:14)
      at Object.<anonymous> (src/index.js:5:16)

```

The project can be found here: https://github.com/wokwi/avr8js-research/tree/test-compile-WASM-instructions
To reproduce run:
```bash
npm install
npx asbuild
npx jest
```

Using node.js version `14.18.0` and npm version `8.1.2`.

**Comment by MaxGraey** [comment]
Just use `const loader = require("@assemblyscript/loader/umd");` or update node.js to recent LTS

**Comment by Dudeplayz** [comment]
Upgrading to the latest release v16.13.0 didn't fix the issue. Also, I want to mention, that the normal program execution works without problems, also in the last LTS. It is just the jest runtime that produces this error.

**Comment by MaxGraey** [comment]
I'm not sure I understand your config. In the same file you're mixed commonjs and esm import of the same loader:
```ts
import {ASUtil, ResultObject} from "@assemblyscript/loader";
```
and later
```ts
const loader = require("@assemblyscript/loader");
```
https://github.com/wokwi/avr8js-research/blob/test-compile-WASM-instructions/src/index.ts#L2

**Comment by Dudeplayz** [comment]
Oh. Your right, that's wrong. I changed it fully to ESM:
```typescript
import type * as MyModule from "../build/module";
import {ASUtil, ResultObject, instantiateSync} from "@assemblyscript/loader";
import {readFileSync} from "fs";

export const writeHooks = {}

// @ts-ignore
export const was: ResultObject & { exports: ASUtil & typeof MyModule } = instantiateSync<typeof MyModule>(readFileSync(__dirname + "/../build/untouched.wasm"), {
    /* imports */
    index: {
        log: (ptr: number) => console.log('WASM-Log: ' + was.exports.__getString(ptr)),
        callWriteHook(value: number, oldValue: number, addr: number, mask : number): boolean {
            return writeHooks[addr](value, oldValue, addr, mask)
        }
    }
})
```

Still doesn't work :/

**Comment by MaxGraey** [comment]
I guess jest should config properly for support ESM:
https://github.com/facebook/jest/issues/10025

**Comment by MaxGraey** [comment]
https://kulshekhar.github.io/ts-jest/docs/guides/esm-support/

**Comment by Dudeplayz** [comment]
I tried everything you mentioned. I didn't get it running... Really annoying.

**Comment by Dudeplayz** [comment]
If I try to use the umd path you mentioned, I get this error:
```bash
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './umd/' is not defined by "exports" in C:\Users\xxred\IdeaProjec
ts\avr8js-research\node_modules\@assemblyscript\loader\package.json
```

**Comment by Dudeplayz** [comment]
The problem still exists... haven't found a solution.

**Comment by Dudeplayz** [comment]
I got it running by importing `"@assemblyscript/loader/umd"` in the jest configuration. But how do I get it running to always use the normal `"@assemblyscript/loader`? I currently have to copy the class for jest and put the umd package there. That's cumbersome, is there an alternative?

**Comment by ppedziwiatr** [comment]
Exactly same issue here.
If I use the `import loader from '@assemblyscript/loader';` import, Jest throws and exception:
![image](https://user-images.githubusercontent.com/84311757/154847630-082aaa67-c08e-4a03-8594-faf0b771eaa2.png)


If I switch to `import loader from '@assemblyscript/loader/umd';`, Jest works fine, but ts-node throws an error:
![image](https://user-images.githubusercontent.com/84311757/154847674-47391299-7d6f-46c3-943d-5f215c7d74ba.png)

**Comment by ppedziwiatr** [comment]
Ok, I've made it work in both jest (ts-jest) and ts-node and - after reading `import loader from '@assemblyscript/loader'` https://medium.com/@martin_hotell/tree-shake-lodash-with-webpack-jest-and-typescript-2734fa13b5cd.

1. add 
```
"transformIgnorePatterns": [
    "<rootDir>/node_modules/(?!@assemblyscript/.*)"
  ],


  transform: {
    '^.+\\.(ts|js)$': 'ts-jest'
  }
  ```
  to `jest.config.js` ("js" must be added to "transform").
  2. add `"allowJs": true` to `tsconfig.js`
