### ISSUE TITLE
Can't retreive keys from a Map

### ISSUE THREAD

**Issue by redfave** [AssemblyScript/assemblyscript#2142]
AS Version: 0.19.20

Currently I'm playing around with AS, but I struggle to use the Map. The [documentation says](https://www.assemblyscript.org/stdlib/map.html#methods), the `keys()` method of a `Map` is supposed to return an `Array`. But it seems currently it is instead an `IterableIterator`. When I try to compile my code, I get one of the following two error messages, depending on whether I comment out `const pixelIndex = pixelKeys[i];` or not.

`TS2339: Property 'length' does not exist on type 'IterableIterator<number>'.`

`TS7053: Element implicitly has an 'any' type because expression of type 'number' can't be used to index type 'IterableIterator<number>'. No index signature with a parameter of type 'number' was found on type 'IterableIterator<number>'.`

```ts
    const pixelToVisit = initPixelMap(height, width);
    ....
    const pixelKeys = pixelToVisit.keys();
        for (let i= 0; i< pixelKeys.length;i++) {
            const pixelIndex = pixelKeys[i];
               ......
        }

function initPixelMap(height: u16, width: u16): Map<i32, Point> {
    const pixelMap = new Map<i32, Point>();
    for (let w: u16 = 0; w < width; w++) {
        for (let h: u16 = 0; h < height; h++) {
            const pixelInfo = new Point(w,h,height, width);
            const pixelIndex = h * width * 4 + w * 4;
            pixelMap.set(pixelIndex, pixelInfo);
        }
    }
    return pixelMap;
}
```

**Comment by MaxGraey** [comment]
> TS2339: Property 'length' does not exist on type 'IterableIterator<number>'.

It's TS error happened becouse you probably use non-proper definitions. AS has own definitions which extended in `tsconfig.json` if you created you project via scaffold script.

**Comment by redfave** [comment]
Thanks for the quick response. I've already added a `tsconfig.json` to my `/assembly` folder containing the AS code. I'm pretty sure it works, otherwise I guess I wouldn't be able to use AS specific types like u8 or f32 in my code.

**Comment by MaxGraey** [comment]
check your `/assembly/tsconfig.json`. You error is TS error. Here playground with your example which [properly compiled and run](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY2xhc3MgUG9pbnQgeyAKICBjb25zdHJ1Y3RvcigKICAgIHB1YmxpYyB4OiB1MTYsIAogICAgcHVibGljIHk6IHUxNiwKICAgIHB1YmxpYyBoOiB1MTYsIAogICAgcHVibGljIHc6IHUxNgogICkge30KfTsKCmZ1bmN0aW9uIGluaXRQaXhlbE1hcChoZWlnaHQ6IHUxNiwgd2lkdGg6IHUxNik6IE1hcDxpMzIsIFBvaW50PiB7CiAgICBjb25zdCBwaXhlbE1hcCA9IG5ldyBNYXA8aTMyLCBQb2ludD4oKTsKICAgIGZvciAobGV0IHc6IHUxNiA9IDA7IHcgPCB3aWR0aDsgdysrKSB7CiAgICAgICAgZm9yIChsZXQgaDogdTE2ID0gMDsgaCA8IGhlaWdodDsgaCsrKSB7CiAgICAgICAgICAgIGNvbnN0IHBpeGVsSW5mbyA9IG5ldyBQb2ludCh3LCBoLCBoZWlnaHQsIHdpZHRoKTsKICAgICAgICAgICAgY29uc3QgcGl4ZWxJbmRleCA9IChoICogd2lkdGggKyB3KSAqIDQ7CiAgICAgICAgICAgIHBpeGVsTWFwLnNldChwaXhlbEluZGV4LCBwaXhlbEluZm8pOwogICAgICAgIH0KICAgIH0KICAgIHJldHVybiBwaXhlbE1hcDsKfQoKY29uc3QgbWFwID0gaW5pdFBpeGVsTWFwKDMyLCAzMik7CmFzc2VydChtYXAua2V5cygpLmxlbmd0aCA9PSAzMiAqIDMyKTsKIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQogICAgb3V0cHV0LnZhbHVlICs9IGBPayFcbmAKICB9KQo8L3NjcmlwdD4=)

**Comment by redfave** [comment]
You are right, it must be my project config, as my AS code compiles in the online playground.
I need to take a second look at my config files, Webpack and the as-loader doesn't seem to play well together in my scenario.
