### ISSUE TITLE
Question about node modules import

### ISSUE THREAD

**Issue by CocoJam** [AssemblyScript/assemblyscript#215]
I am quite new to assemblyscript and webassemble overall.
I am having some trouble importing a node module, which is not under the ts formate.
I have made a d.ts with tsconfig.json files to port it, and it works when I use tsc to compile it but when I use asc to compile the ts file it responds "Import file 'XX.ts' not found".

**Comment by dcodeIO** [comment]
The way this currently works is by `declare`ing the functionality of the JS module within the WebAssembly module. Let's say you have a simple JS module like the following:

```ts
// declaration in AssemblyScript
declare namespace myJsModule {
  export function add(a: i32, b: i32): i32;
}
```

This will generate a WebAssembly import that you'd then provide as an import when instantiating the module, like so:

```js
// instantiation in JavaScript
var myJsModule = require("myJsModule ");
WebAssembly.instantiate(myWasmModuleBuffer, { myJsModule: myJsModule });
...
```

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
