### ISSUE TITLE
Type coercion woes

### ISSUE THREAD

**Issue by jjrv** [AssemblyScript/assemblyscript#2163]
I tried to sort a list of objects with an `f64` field, but the sort comparator doesn't like it.

```TypeScript
ERROR AS200: Conversion from type 'f64' to 'i32' requires an explicit cast.
([1, 2] as f64[]).sort((a, b) => a - b);
```

Simply casting `f64` to `i32` in the comparator might erroneously round to zero, so I tried a known trick to get the sign:

```TypeScript
([1, 2] as f64[]).sort((a, b) => +(a > b) - +(a < b));
```

Compiled as TypeScript it works fine, but as AssemblyScript it fails to sort correctly! That's because:

```TypeScript
trace('-1 !=', 1, -true);
```

prints:

```
trace: -1 != 4294967295
```

It's extremely confusing that booleans get coerced to unsigned ints. That is not the case in C++ for example:

```C++
#include <cstdio>

int main(void) {
    printf("%f\n", (double)-true);
    return 0;
}
```

prints `-1`.

**Comment by MaxGraey** [comment]
> ERROR AS200: Conversion from type 'f64' to 'i32' requires an explicit cast.
([1, 2] as f64[]).sort((a, b) => a - b);

That's because comparator expect `i32` type as a result. Btw you could skip this in AS and just use:
`([1, 2] as f64[]).sort()`. See this tweet: https://twitter.com/AssemblyScript/status/1146047188746809347/photo/1

In case when you're required compare floating points in nested structure you could use this approach:
```ts
[1.0, 2.0].sort((a, b) => i32(a > b) - i32(b < a));
```
But much better use this:
```ts
import { COMPARATOR } from "util/sort";

[1.0, 2.0].sort((a, b) => COMPARATOR<f64>()(a, b));
```

In this case it will properly sort even NaNs.

For signed integers you could use usual approach:
```ts
[1, 2].sort((a, b) => a - b);
// or simpler
[1, 2].sort();
```

**Comment by MaxGraey** [comment]
> It's extremely confusing that booleans get coerced to unsigned ints. That is not the case in C++ for example:

C++ always upcast small types like `uint8_t` or `bool` to native `int32_t` during some unary or binary operations.

**Comment by jjrv** [comment]
Yes, automatically upcasting `bool` to `i32` would make perfect sense, while `u32` is quite a surprise.

**Comment by MaxGraey** [comment]
Current behaviour for subtracting of bools is cast to bool. Basically all small integers behaves similar. So we god this:
```rust
(a > b) - (a < b)  ->   (bool(a > b) - bool(a < b))  != 0
  bool   -  bool    ->    bool
```
where `bool` is `u8` under the hood. So if you got `-1` it will cast to `true` (`1`).
In general, I'm in favour of bool being a completely different type from integer, and not supporting arithmetic operations like `-`, `+`, etc. I think this will change in the near future. This brings the behaviour of the bool closer to the boolean which is natural for TypeScript.
