### ISSUE TITLE
Uint8Array.wrap throws "memory access out of bounds" error

### ISSUE THREAD

**Issue by DiriectorDoc** [AssemblyScript/assemblyscript#2168]
I'm really new to assemblyscript, and webassembly in general, so it frustrates me a lot that I can get simple code to work the way I want it to.

This is my only code, and it throws an error:

```TypeScript
export function test(buffer: ArrayBuffer): Uint8Array {
    return Uint8Array.wrap(buffer)
}
```
test:
```javascript
console.log(myModule.test(Uint8Array.from([1, 1]).buffer));
```

What could I possibly be doing wrong?

**Comment by dcodeIO** [comment]
The issue originates from `myModule.test(Uint8Array.from([1, 1]).buffer)`, where a JavaScript object (here: an ArrayBuffer) is passed to WebAssembly directly, which currently does not do what one would expect.

See also: [On values crossing the boundary](https://www.assemblyscript.org/exports-and-imports.html#on-values-crossing-the-boundary)

The solution here is to utilize the [AssemblyScript loader](https://www.assemblyscript.org/loader.html), providing a `__newArrayBuffer` helper (among others) to copy the JS-side ArrayBuffer to a Wasm-side ArrayBuffer, like so:

```ts
myModule.test(myModule.__newArrayBuffer(Uint8Array.from([1, 1]).buffer))
```

The same is true for other higher data types like strings and normal arrays. The only values that can be naturally passed between the two worlds are simple numbers.

**Comment by DiriectorDoc** [comment]
**Solved**

Thank you so much.
