### ISSUE TITLE
Native binary generation program.

### ISSUE THREAD

**Issue by sirlordt** [AssemblyScript/assemblyscript#2174]
Please make this language capable of generate native programs like golang or rust lang. For Linux/Windows/Mac.

AssemblyScript -> Webassembly -> Native Platform Binary Image.

With the clear and simple syntax of AssemblyScript and the speed of rust lang. This language can easily replace Java / C# / C / C ++ / Rust/ Golang and take over the world.

Of course if additional can use libraries of Rust / C / C++ in 6 month we have new most loved language Ja ja ja ja.

**Comment by MaxGraey** [comment]
You can already do this using e.g. wasm2c (wasm -> c compiler):
https://github.com/wasm3/embedded-wasm-apps

or InNative:
https://github.com/innative-sdk/innative
