### ISSUE TITLE
Compile assemblyscript into javascript

### ISSUE THREAD

**Issue by tonio0720** [AssemblyScript/assemblyscript#2175]
Is it difficult to compile assemblyscript into simple javascript with same type/class as wasm.
I can simply do `tsc` but this doesnt create `valueOf` and `wrap` method for classes.
I am using assemblyscript in my project and i want to use javascript as a fallback for platform where i cant use webassembly (like chrome extension).
For now, i have write almost the same exact code for assemblyscript and javascript to make this happen.

Please consider it!

**Comment by MaxGraey** [comment]
See portability section in docs: https://www.assemblyscript.org/portability.html

**Comment by tonio0720** [comment]
Thanks!! this is great!
But, I had to add `wrap` function to every Class I made, and if this is done automatically that would be awesome.

```
import * as portable from './assemblyPortable';

Object.keys(portable).forEach((key) => {
    if (portable[key]?.constructor && key[0] === key[0].toUpperCase()) {
        portable[key].wrap = (n: any) => n;
    }
});
```

**Comment by MaxGraey** [comment]
wrap and other polyfills contains here: https://github.com/AssemblyScript/assemblyscript/blob/main/std/portable/index.js

**Comment by guest271314** [comment]
Is there a complete, working example of porting to JavaScript?
