### ISSUE TITLE
Wasmer, unexpected commas in function names

### ISSUE THREAD

**Issue by adrien-zinger** [AssemblyScript/assemblyscript#2180]
Hi!
I'm currently having an issue and I would like to know if I can help.

Today I tried to use json-as (that seems to work) except that using wasmer with rust, when I try to create an instance with the output wat file, there is an unexpected comas found.

Here is the AssemblyScript that I compiled:

```ts
import { JSON } from "json-as";

class Animal {
    name: string
    sound: string
}

export function main(_args: string): i32 {
  let animal: Animal = { name: "dog", sound: "wof wof" };
  let serialized = JSON.stringify(animal);
  //print(`serialized animal: ${serialized}`);
  let animal2 = JSON.parse<Animal>(serialized);
  //print(`Hello! I'm a ${animal.name} and I make ${animal.sound} to talk.`);
  return 0;
}
```

with this command line:
```bash
asc assembly/caller_json.ts --exportRuntime --transform json-as/transform --textFile build/caller_json.wat --binaryFile build/caller_json.wasm
```

And in the .wat I can see some unexpected commas in function names like this between `String` and `~lib`:
```wat
(func $~lib/map/Map<~lib/string/String,~lib/string/String>#set (param $0 i32) (param $1 i32) (param $2 i32)
```

Unfortunately It's not the first time I saw that problem and I guess that it's not a normal behavior :smile: I tried to enter in your code to understand how it works. I'm interested in any explanation!

Please can you tell me if I can do something for you. Thank you for your awesome job! :clap:

**Comment by dcodeIO** [comment]
So far the compiler has emitted commas to make generic type parameter lists human readable, and hopes were that it doesn't lead to problems (it doesn't on the Web afaict). Seems that's not the case serverside, hmm. Too sad these are disallowed just so.

See also: https://github.com/AssemblyScript/assemblyscript/issues/1068

**Comment by adrien-zinger** [comment]
Hi, yes the .wasm works well! For another solution, I've tried to replace the %2C in type.ts with %3C and "< ", but after compiling I still have a comma in the function name, maybe I didn't linked well with the compiled asc.

https://github.com/AssemblyScript/assemblyscript/blob/09beb42dcdec58cda9098abcf4dae80405e58e92/src/types.ts#L917-L926

Not sure if you was talking about this :slightly_smiling_face:, I didn't understood where should binaryen emit quotes.

Whatever, I think I'll just use the wasm after all. It would be nice to also have a working .wat.

Thank you!
