### ISSUE TITLE
Provide a way to make sure imports for a module are not optimised away

### ISSUE THREAD

**Issue by andyherbert** [AssemblyScript/assemblyscript#2182]
Currently references to imports in a module are removed if they are not referenced in the code, but for embedded runtimes such  as wasmtime for rust the code panics if too many imports are given to an instance. My use case is that I am providing a runtime for WASM to interface with my host application, and in the likely event that someone writing a module that decides not to use a particular hook, the host application panics.

**Comment by MaxGraey** [comment]
Unused imported host methods removed by binaryen (not assemblyscript). Binaryen also uses by emscripten and wasm-pack (rust util). So most likely the problem is on your side. I'm sure wasmtime can check if a method exists on the wasm side or not and gracefully handle it.

**Comment by andyherbert** [comment]
I resolved this issue by specifying named imports in wasmtime instead of anonymous references. Thanks for you help.
