### ISSUE TITLE
process.env (wasi) not working

### ISSUE THREAD

**Issue by andersson09** [AssemblyScript/assemblyscript#2194]
Hey,

First of all great language! I'm enjoying experimenting with it.

I noticed a subtle bug in the 'environ_get' wasi binding where I believe the first input should be a pointer to pointer (ptr<ptr<char>> rather than ptr<usize>) as it does in args_get. This causes process.env.get() to stop working.. of course I could be wrong!

https://github.com/AssemblyScript/assemblyscript/blob/main/std/assembly/bindings/wasi_snapshot_preview1.ts

Thanks!

**Comment by dcodeIO** [comment]
There is a test case [here](https://github.com/AssemblyScript/assemblyscript/blob/main/tests/compiler/std-wasi/process.ts) that works for me. [Here's](https://github.com/AssemblyScript/assemblyscript/blob/main/tests/compiler/std-wasi/process.json) the respective WASI configuration object passed to Node's WASI constructor.

Also, looking at the definition

```ts
/** Read environment variable data. */
// @ts-ignore: decorator
@unsafe
export declare function environ_get(
  /** Input: Pointer to a buffer to write the environment variable pointers. */
  environ: ptr<usize>,
  /** Input: Pointer to a buffer to write the environment variable string data. */
  environ_buf: usize
): errno;
```

the `environ` field is a pointer to an untyped pointer (usize). Perhaps it would be more accurate to annotate as `ptr<ptr<u8>>`, but the effect should be the same.

**Comment by andersson09** [comment]
> There is a test case [here](https://github.com/AssemblyScript/assemblyscript/blob/main/tests/compiler/std-wasi/process.ts) that works for me. [Here's](https://github.com/AssemblyScript/assemblyscript/blob/main/tests/compiler/std-wasi/process.json) the respective WASI configuration object passed to Node's WASI constructor.
> 
> Also, looking at the definition
> 
> ```ts
> /** Read environment variable data. */
> // @ts-ignore: decorator
> @unsafe
> export declare function environ_get(
>   /** Input: Pointer to a buffer to write the environment variable pointers. */
>   environ: ptr<usize>,
>   /** Input: Pointer to a buffer to write the environment variable string data. */
>   environ_buf: usize
> ): errno;
> ```
> 
> the `environ` field is a pointer to an untyped pointer (usize). Perhaps it would be more accurate to annotate as `ptr<ptr<u8>>`, but the effect should be the same.

Yep you are correct. Also just checked using wasmtime and it worked, something is wrong with my code even though my tests are working for getenv in c.
