### ISSUE TITLE
idof<T>() for functions always returns 0

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#2196]
I am responsible for maintaining serialization software which relies on asserting runtime type information is validated.

```ts
let funcref: () => void = (): void => {};

assert(changetype<OBJECT>(changetype<usize>(funcref) - TOTAL_OVERHEAD).rtid == idof<() => void>());
```

This assertion fails, but is probably one of the most important lines in ASON that validates the deserialized value is correct. In this case, `0` is usually the type of an `ArrayBuffer`  (or at least it used to be.)

Should I avoid checking type information for callbacks? (Which I believe to be dangerous.) Or is this a bug?

**Comment by dcodeIO** [comment]
Is this perhaps the only function type used indirectly in the binary? Afaik classes and functions do not share their id space, so I would expect the only function to have id 0.
