### ISSUE TITLE
Start function indirection

### ISSUE THREAD

**Issue by lexaknyazev** [AssemblyScript/assemblyscript#2199]
It seems that when the _start function_ has 200 or more instructions it gets moved to another function and the native start function contains only a single call. Why is that so?

For example:
```ts
// repeat 67 times
store<u8>(0, 0);
```
produces
```wat
(module
 (type $none_=>_none (func))
 (memory $0 0)
 (export "memory" (memory $0))
 (start $~start)
 (func $start:assembly/foo
  i32.const 0
  i32.const 0
  i32.store8
  i32.const 0
  i32.const 0
  i32.store8
;; 65 more times
 )
 (func $~start
  call $start:assembly/foo
 )
)
```

**Comment by dcodeIO** [comment]
This looks a bit as if Binaryen is hitting an inlining limit, probably due to function size, yet in this case it wouldn't matter since the function is used exactly once. So far just a guess, though.
