### ISSUE TITLE
define memory

### ISSUE THREAD

**Issue by blooddy** [AssemblyScript/assemblyscript#22]
is it possible to define memory non zero?
https://webassembly.github.io/spec/core/syntax/modules.html#data-segments

**Comment by dcodeIO** [comment]
Static strings become data segments currently, and static arrays are planned. With the latter, you could basically define the entire memory programmatically, for example using `u8[]`.

**Comment by dcodeIO** [comment]
Static arrays of basic types should be supported now, while dynamic ones using array literals are still to do.

**Comment by dcodeIO** [comment]
Dynamic array literals are supported as well now. Closing for now.
