### ISSUE TITLE
How to transform compiled Wasm

### ISSUE THREAD

**Issue by lrettig** [AssemblyScript/assemblyscript#220]
Hello,

Opening this issue to get your feedback. For Ewasm I need to be able to do the following, in this order:

1. Run a transform over the AST
2. Compile to Wasm
3. Take the first AST, and the compiled Wasm code, and wrap the compiled code in some more logic, then compile this

Step (1) corresponds to converting from my DSL to Ewasm-compatible code, step (2) corresponds to compiling this, and step (3) corresponds to generating the init code required to initialize the contract storage and deploy the contract to Ethereum.

I cannot do this as two sequential transforms since the second depends on the binary output of the first. I also cannot do this outside the AS compiler since step (3) needs to operate on the AST from (1).

Up to now I've been able to do everything without modifying the core AS code but I don't think this will be possible without some modifications. I intend to fork the code and do the following. Let me know if you have any better ideas--in particular, a way this could be done generically that could make it into the master codebase and be useful to others!

- add a new commandline option `--transformArgs`
- pass `options.transformArgs` into the transform function when it's called
- create a second transform function
- call `asc` twice, once with the existing transform, then a second time with `--transform transformNew --transformArgs path/to/untouched.wasm -b build/untouchedWrapper.wasm`

The second transform function can read the compiled binary, perform the necessary steps, and produced the wrapped binary.

**Comment by xtuc** [comment]
FYI we are doing similar transforms using github.com/xtuc/webassemblyjs in Webpack, see https://github.com/webpack/webpack/blob/master/lib/wasm/WebAssemblyGenerator.js

**Comment by dcodeIO** [comment]
My understanding of this is that one would use Binaryen or a similar toolchain library to do non-AssemblyScript-specific post-transforms. It might still be that asc gains some sort of introspection to link against (and call into) existing binaries, which would come with limited transform capabilities, but there are no immediate plans.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by DanielMazurkiewicz** [comment]
@dcodeIO 

Got here, because was looking for almost same reasons as @lrettig :-) 

1. How to pass command line arguments to transform, don't know if can access it some way, but if not, I think from cmd it could look like that (without breaking any current logic):
```
--transform <transform1> arg1 arg2 arg3 argX --transform <transform2> arg1 arg2 argX
```

Having access to entire asc command line would be also nice.

And the second thing is that it would be VERY convenient to have control over emitted files. I know webpack could do stuff, but if there was another transform hook, like:
```
beforeFilesEmit(files: Record<string, buffer>, cmdOptions: CmdOptions)
//where record key is a path to a file
```
then live would be much easier :-D ;-)
