### ISSUE TITLE
Storing a blob of binary data

### ISSUE THREAD

**Issue by lrettig** [AssemblyScript/assemblyscript#221]
Hello,

I have a big blob of binary data that I want to store in memory. Normally when writing Wast I would just do:

`(data (i32.const 0) "\000\001\002...")`

Is there an equivalent way of doing this in AS? What I'm trying to avoid is the following:

```
store<u8>(somePointer, val[0], 0)
store<u8>(somePointer, val[1], 1)
store<u8>(somePointer, val[2], 2)
...
```

because it results in much more verbose code.

Thanks.

**Comment by MaxGraey** [comment]
@lrettig Just define static array, like:

```ts
const arr: u8[] = [0, 1, 2, 3, 4];
```
It becames
```wat
...
(data (i32.const 17) "\01\02\03\04")
...
```

**Comment by Born2Go** [comment]
I tried @MaxGraey example and the actual output was:

> (i32.const 8) "\05\00\00\00\00\00\00\00\00\01\02\03\04\00\00\00")
> (data (i32.const 24) "\08\00\00\00\05\00\00\00")

it seems that in my compilation we have: 
8 bytes size - \05\00\00\00\00\00\00\00
then the actual data:
\00\01\02\03\04
followed by?????
\00\00\00 and (data (i32.const 24) "\08\00\00\00\05\00\00\00")

this seems a lot more bytes than needed, am I doing anything wrong??

**Comment by MaxGraey** [comment]
Just add `-O3` flag for compiler

**Comment by Born2Go** [comment]
I added the -O3 flag and now those 8 prefix bytes are reduced to just one (the size of the array)
but... all those trailing bytes are never gone, what exactly are they?

I tried with -t and -b and the decompiled binary and the textual representation show those strange trailing bytes

**Comment by MaxGraey** [comment]
I got this:

```ts
(data (i32.const 8) "\05")
(data (i32.const 17) "\01\02\03\04")
(data (i32.const 24) "\08\00\00\00\05"))
```
Which looks normal

**Comment by Born2Go** [comment]
It is exactly what I got, I just don't understand what are those trailing bytes:
> (data (i32.const 24) "\08\00\00\00\05"))
what they represent? why they are there?
to me it seem that we only needed the number of bytes (5) and the data itself (0,1,2,3,4)

**Comment by MaxGraey** [comment]
`(data (i32.const 8) "\05")` is `byteLength` of ArrayBuffer store.
`(data (i32.const 24) "\08\00\00\00\05"))` is `08` - pointer to buffer, `00\00\00\05` - is actually `length` of Array.

See this [layout](https://github.com/AssemblyScript/assemblyscript/wiki/Memory-Layout-&-Management#arrays) actually you should focus to `Array<T> layout` and `ArrayBuffer layout`

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
