### ISSUE TITLE
Optionally skip zero-init of static data regions with imported memory

### ISSUE THREAD

**Issue by lexaknyazev** [AssemblyScript/assemblyscript#2212]
By combining the `--memoryBase` option and multiple `memory.data` calls, it is possible to fill the initial memory with sparse data. For example:

1. Skip first 2048 bytes with `--memoryBase 2048`
2. Fill next 512 bytes with `memory.data<u64>([...])`
3. Skip next 1024 bytes with `memory.data(1024)`
4. ...

This approach works well and usually creates _data segments_ only for the filled regions. However when the memory is imported (with `--importMemory` option) the _data segments_ are also added for skipped regions to ensure that they are initialized to zeros. Therefore, the compiled module may get very large.

For example, compiling the following source with `--importMemory` results in over 1 MiB module:
```ts
memory.data(1024 * 1024);
```

It would be nice if an application could opt-in to skip zero initialization, e.g., when the app overwrites that memory region anyway, by extending the API like this:
```ts
declare namespace memory {
  /* ... */
  export function data(size: i32, align?: i32, skipInit?: bool): usize;
  /* ... */
}
```

**Comment by dcodeIO** [comment]
There is a compiler option to assume that imported memory is initilized with zeroes:

```
--zeroFilledMemory    Assume that imported memory is zero filled (requires --importMemory).
```

Does providing it help in this case?

**Comment by lexaknyazev** [comment]
Yes, works like a charm!

It was requested for the almost the same reasons in #2026.
