### ISSUE TITLE
Select with one power-of-two result

### ISSUE THREAD

**Issue by lexaknyazev** [AssemblyScript/assemblyscript#2214]
The following function
```ts
export function foo(c: boolean): u32 {
    return c ? 0 : 1;
}
```
gets compiled to
```wat
 (func $module/foo (param $0 i32) (result i32)
  local.get $0
  i32.eqz
 )
```

However, changing `1` to, for instance, `16` yields the following code that pushes 3 values to the operand stack before consuming them:
```wat
 (func $module/foo (param $0 i32) (result i32)
  i32.const 0
  i32.const 16
  local.get $0
  select
 )
```

Since `eqz` is guaranteed to always return `0` or `1`,  it should be possible to just shift its value when one result is a constant power of two and another result is zero, thus using only 2 slots of the operand stack.
```wat
 (func $module/foo (param $0 i32) (result i32)
  local.get $0
  i32.eqz
  i32.const 4
  i32.shl 
 )
```

**Comment by dcodeIO** [comment]
This one looks like a potential optimization for Binaryen to perform. Perhaps it can be added there?
