### ISSUE TITLE
Assemblyscript code won't run in Wasmer or Wasmtime

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [AssemblyScript/assemblyscript#2215]
This is my first time using AssemblyScript (or WASM at all for that matter), so if this is an issue with the human, rather than the computer, please do excuse me.

Anyway, I have written a simple test program like so:
![image](https://user-images.githubusercontent.com/38588376/154804692-7cca1d1c-ca81-4ef0-875d-8bcfac89a519.png)

But when I try to run it, this error occurs:
![image](https://user-images.githubusercontent.com/38588376/154804844-61cf0eb3-cd17-4436-8852-80dc79ed61b5.png)

Any help would be much appreciated. Thanks!

**Comment by romdotdog** [comment]
Does this guide help you?
https://docs.wasmtime.dev/wasm-assemblyscript.html

**Comment by ThatBlockyPenguin** [comment]
Aha!
Using this code from the Wasmtime docs:
```
import "wasi"

import {Console} from "as-wasi"
Console.log('Hello World!\n');
```
The code runs in both Wasmer and Wasmtime.
![image](https://user-images.githubusercontent.com/38588376/155424645-3665f05a-b58a-4b60-847a-1368689b4202.png)

Thank you so much for your help!
