### ISSUE TITLE
sourceMap missing some function

### ISSUE THREAD

**Issue by HerrCai0907** [AssemblyScript/assemblyscript#2216]
In the sourceMap generated by debug build, I cannot find the mappings about Foo.func1

```typescript
let offset: usize = 0;

export class Foo {
  static func1(): ArrayBuffer | null {
    offset = 0
    const buf = new ArrayBuffer(100)
    return null;
  }
  static func2(): i32 {
    const ptr = changetype<usize>(0);
    offset += 1;
    for (let i: i32 = 0; i < 15; i++) {
      offset += 1;
    }
    return 1;
  }
}

```

**Comment by HerrCai0907** [comment]
I trace the argument of `module.setDebugLocation` in compile. Both function already emit the debug location to `binaryen`. So maybe misuse or bug of `binaryen`?

**Comment by dcodeIO** [comment]
I am not aware of a bug in this area, but might of course be that something isn't working as it should. One obvious case where the relevant debug info would not be present is when the function is never called, so everything attached to it is omitted, but you probably already checked that, hmm.

**Comment by HerrCai0907** [comment]
> I am not aware of a bug in this area, but might of course be that something isn't working as it should. One obvious case where the relevant debug info would not be present is when the function is never called, so everything attached to it is omitted, but you probably already checked that, hmm.

I have tried to fix it about 2 days, assemblyscript compile frontend works as expectation and emit the info to Binaryen. But because of compatibility between ESM and CJS, I cannot debug the latest version together. Is there any plan to use latest binaryen.js with ESM grammar?
