### ISSUE TITLE
[Question] Rest parameter for variable arguments?

### ISSUE THREAD

**Issue by fsImageries** [AssemblyScript/assemblyscript#2217]
Hi everyone,
I just have a question about the status of rest parameters in function definitions.

I'm writing a class where I want to have a getter function which can take a variable length of input arguments, like so:
```
export class TestAccess{
    data: i32[]

    constructor(){
        this.data = [1,2,3,4,5,6,7,8,9,10]
    }
    
    getOP(...args:i32[]):i32[]{
        const ret = new Array<i32>()

        for (let i = 0; i < args.length; i++){
            ret[i] = this.data[args[i]]
        }

        return ret
    }
}
```

It would be called like so:
```
const A = new TestAccess()

A.getOP(a,b,...,n)
```

But that fails with the error:
```
Type 'i32' is not assignable to type '~lib/array/Array<i32>'
```

It obviously works when you call it like that:
```
const A = new TestAccess()

A.getOP([a,b,...,n])
```

So my question is really just about if that's possible and I'm just doing something wrong or if it's really not implemented in that fashion right now?

Thanks everyone.
Also really awesome project, I'm having a blast working with assemblyscript. Please keep up the great work :)

**Comment by dcodeIO** [comment]
> So my question is really just about if that's possible and I'm just doing something wrong or if it's really not implemented in that fashion right now?

You are not doing anything wrong, rest parameters are in fact not implemented yet. Quite a few open questions there.
