### ISSUE TITLE
Optional chain not support yet?

### ISSUE THREAD

**Issue by abcfy2** [AssemblyScript/assemblyscript#2220]
```ts
event.transaction.to?.toHex() || "null",
```

Error:

```
⠋ Compile subgraphERROR TS1109: Expression expected.

       event.transaction.to?.toHex() || "null",
                            ~
 in src/mapping.ts(22,28)
```

**Comment by dcodeIO** [comment]
That's correct, optional chaining is not implementer yet, unfortunately.

**Comment by abcfy2** [comment]
Would you please support this feature? Thanks.

**Comment by incrypto32** [comment]
@dcodeIO This will be an absolutely excellent feature to be implemented in the upcoming versions. Would love to see this one implemented

**Comment by romdotdog** [comment]
Not really. I believe there are still some logistics issues associated with this feature.
Closing in favor of the more-detailed #1992
