### ISSUE TITLE
Support BigInt literals (i.e. 1n)

### ISSUE THREAD

**Issue by leighmcculloch** [AssemblyScript/assemblyscript#2242]
I've noticed that AssemblyScript has support for BigInt's as of this comment https://github.com/AssemblyScript/assemblyscript/issues/117#issuecomment-531556954 by @dcodeIO. However, it appears that bitint literals are not supported, i.e. specifying a number in the form `1n` which is equivalent to `BitInt(1)`.

This is the error I get when I try to use an `n` literal in AssemblyScript:

```
ERROR TS1351: An identifier or keyword cannot immediately follow a numeric literal.

 const v = 0n;
            ^
```

For portability, and the ability to bring TypeScript into AssemblyScript it would be helpful if the `n` suffix was supported. I imagine the simplest form would be to assume that any number suffixed with an `n` is an `i64` or `u64`.

**Comment by dcodeIO** [comment]
The respective comment refers to conversion at the boundary, which transforms `bigint` values in JS to `i64` values in AS. There is no `bigint` type respectively `BigInt` class in AS, yet. Do you have a use case not sufficiently covered by `i64`s?

**Comment by leighmcculloch** [comment]
Ah yes, that's a good point, I was thinking of bigints as their utility as a u64, but they could have much higher number of bits depending on the runtime.

The specific use case is I have some code shared between AssemblyScript and TypeScript that needs to use 64-bit integers. On the AssemblyScript side I'm using u64 and i64, and then on the TypeScript side I'm injecting these definitions: 
```ts
type u64 = bigint;
type i64 = bigint;
```

**Comment by dcodeIO** [comment]
Hmm, yeah, currently a little tricky when literals are involved. What the compiler does is provide a target-specific `i64_new` method that is implemented to return an `i64` in Wasm, respectively producing a [Long](https://github.com/dcodeIO/long.js) in JS, from the `i32` low and high values, which can be represented in both JS and AS as `number`s. I do agree that something less hacky would be preferable, just not sure if we should reuse `n` notation (yet).

**Comment by leighmcculloch** [comment]
If AS supports an arbitrary BigInt then the `n` notation would be more appropriate, and we could say that BigInts coerce to u64. That would make it easier to make code using u64s portable.

**Comment by leighmcculloch** [comment]
Or, if the decision has already been made to map BigInts to i64, the `n` notation sort of makes sense today, since we've said that the arbitrary limit of BigInt in AS is not arbitrary, it's 64 bits. Having a limit is not horrible, since even some browsers have limits, albeit not normally this low.

**Comment by MaxGraey** [comment]
> If AS supports an arbitrary BigInt then the n notation would be more appropriate, and we could say that BigInts coerce to u64 or at least support the explicit cast. That would make it easier to make code using u64s portable.

Portability is more of a nice bonus of having a stricter subset of TS, but it's definitely not the primary goal for which we are willing to break the code we already have. However, being as close as possible to WebAssembly and reflecting its type system is just one of our goals. As you know, WebAssembly has i64/u64 types. We plan to implement `BigInt` and `bigint` literals ([See our roadmap](https://github.com/AssemblyScript/assemblyscript/wiki/Status-and-Roadmap#bigint)). Closing this.
