### ISSUE TITLE
exports.__new is not a function

### ISSUE THREAD

**Issue by kefniark** [AssemblyScript/assemblyscript#2244]
## Description
Hi there,

Beginner with AssemblyScript, I followed the getting started, and I kept the default configuration and structure.
The sample works well when I use numbers, but at the moment I try to use more advance type, I run into issues.

Not sure to get how the communication between JS and Wasm land is handled and why it's not working.
And getting the same result in test and browser.

## Trying to pass a string
```ts
// in assembly/index.ts
export function create(msg: string): void {
  console.log(msg)
}
```

It compiles but when I run the following code

```ts
import { create } from '../build/release.js'

create('Hello World') // <= this crash
```

> file://build/release.js:46
      pointer = exports.__new(length << 1, 1) >>> 0,
                        ^
  TypeError: exports.__new is not a function

## Trying to return Object reference
```ts
class Test {
  param: string
  
  constructor(val: string) {
    this.param = val
  }

  toString(): string {
    return this.param
  }
}

export function create(): Test {
  return new Test()
}
```

> file://build/release.js:59
      else refcounts.set(exports.__pin(pointer), 1);
                                 ^
  TypeError: exports.__pin is not a function

**Comment by dcodeIO** [comment]
Looks like compilation is missing the `--exportRuntime` option. Did you create the project with `asinit`?

**Comment by kefniark** [comment]
Thanks, indeed adding the flag fix the issue.
And yes I used `asinit` as explained in https://www.assemblyscript.org/getting-started.html#setting-up-a-new-project

**Comment by dnsmichi** [comment]
We ran into the same problem when trying AssemblyScript for the first time in our #EveryoneCanContribute cafe meetup yesterday. Thanks for posting the solution :-) 

- Recording: https://www.youtube.com/watch?v=H1O2j4w78j8
- Blog: https://everyonecancontribute.com/post/2022-07-12-cafe-53-webassemply-assemblyscript-first-steps-gitpod/
- Demo project: https://gitlab.com/everyonecancontribute/dev/learn-wasm-assemblyscript

We tried to pass a string to a function, concat some text, and have it returned to be printed in the HTML frontend. 

assembly/index.ts
```
export function hello_from(n: string): string {
  let out = `Hello from ${n}`

  return out 
}
```

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
<script type="module">
import { hello_from } from "./build/release.js";

var e = document.getElementById("hello_from1");
if (e) {
    e.innerHTML = hello_from("the other side!")
}
e = document.getElementById("hello_from2");
if (e) {
    e.innerHTML = hello_from("GitLab 🦊")
}
e = document.getElementById("hello_from3");
if (e) {
    e.innerHTML = hello_from("the #EveryoneCanContribute cafe meetup ☕")
}

</script>
</head>
<body>
    Hello: 
    <div id="hello_from1"></div>
    <div id="hello_from2"></div>
    <div id="hello_from3"></div>
</body>
</html>

```

I'm not sure whether this should be the default for the getting started documentation or the `asinit` command. It is a bit tricky to find as a beginner who does not know what compiler options are, and it can be overwhelming. I'll think about extending https://github.com/AssemblyScript/website/tree/main/src#the-journey-ahead or other ways.

**Comment by MaxGraey** [comment]
Thanks for feedback @dnsmichi! Really appreciate. We are aware that this can cause difficulties for new users. But 
`--exportRuntime` add quite a lot of extra code which is only needed if there are compound (managed) types was lowered. The ideal is actually to automatically determine if the exported runtime functions like `__pin`, `__unpin` and `__new` is needed for the host during binding generation. And this is what we would like to do in the near future.
