### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by jerrygreen** [AssemblyScript/assemblyscript#2248]
Unfortunately `0.20.0` to `0.20.3` versions have this crucial error when I try to import `assemblyscript/asc`:

```text
$ node --trace-warnings
Welcome to Node.js v14.15.2.
Type ".help" for more information.
> var asc = import('assemblyscript/asc')
undefined
> (node:8260) UnhandledPromiseRejectionWarning: SyntaxError: missing ) after argument list
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:8260) SyntaxError: missing ) after argument list
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
(node:8260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

![image](https://user-images.githubusercontent.com/13215662/161620487-c0939f0c-d3bf-4ab0-9ce3-fb5d7c837e14.png)

And if I try to import directly the dist files as a workaround, from `assemblyscript/dist/asc`, then I'm stuck into another error, "Cannot find module", - similar to #2241.

P.S. While older versions aren't usable either, due to #2247, now I'm considering if I should wait for a fix of the current problem, or maybe use bash equivalent of `asc` from js through execSync/child_process, as a temporary workaround of this issue (which sounds ridiculous but I think it should work), or maybe I should use older versions with this older bug where I should provide all the "additional options"

**Comment by dcodeIO** [comment]
The syntax error is likely a duplicate of #2230. From what I can tell, upgrading to at least Node.js 16 and importing `assemblyscript/dist/asc.js` from TypeScript sources until TS adds support for Node.js' new exports feature could do the trick.

**Comment by jerrygreen** [comment]
Indeed, `node@16` works.

Just tried it with `assemblyscript@0.20.3` and `node@16.14.2`, and yes, with little hack with `assemblyscript/dist/asc.js`, it indeed works. Thanks.

**Comment by BatiGencho** [comment]
@jerrygreen When I try importing assemblyscript/dist/asc.js with  v0.20.3 inside a react project, I get the following errors: 

Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)

ANy ideas ?

**Comment by BatiGencho** [comment]
After many attempts, I am now getting:

`ERROR in ./node_modules/assemblyscript/dist/asc.js 367:41-57
Module not found: Error: Can't resolve 'module' in '/home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/dist'
resolve 'module' in '/home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/dist'
  Parsed request is a module
  using description file: /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/dist/node_modules doesn't exist or is not a directory
      /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/node_modules doesn't exist or is not a directory
      /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules
        single file module
          using description file: /home/evgeni/Documents/development/massa/create-react-app-massa/package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.js doesn't exist
            .web.ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.ts doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.ts doesn't exist
            .web.tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.tsx doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.jsx doesn't exist
        /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module doesn't exist
      /home/evgeni/Documents/development/massa/node_modules doesn't exist or is not a directory
      /home/evgeni/Documents/development/node_modules doesn't exist or is not a directory
      /home/evgeni/Documents/node_modules doesn't exist or is not a directory
      looking for modules in /home/evgeni/node_modules
        single file module
          using description file: /home/evgeni/package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.js doesn't exist
            .web.ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.web.ts doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.ts doesn't exist
            .web.tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.web.tsx doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.jsx doesn't exist
        /home/evgeni/node_modules/module doesn't exist
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules
        single file module
          using description file: /home/evgeni/Documents/development/massa/create-react-app-massa/package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.js doesn't exist
            .web.ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.ts doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.ts doesn't exist
            .web.tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.tsx doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.jsx doesn't exist
        /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module doesn't exist`

**Comment by BatiGencho** [comment]
and:

Compiled with problems:X

ERROR in ./node_modules/assemblyscript/dist/asc.js 367:41-57

Module not found: Error: Can't resolve 'module' in '/home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/dist
