### ISSUE TITLE
Importing assemblyscript/asc in a create-react-app project faills

### ISSUE THREAD

**Issue by BatiGencho** [AssemblyScript/assemblyscript#2249]
When I try importing `asc` from `assemblyscript/dist/asc.js` with v0.20.3 inside a react project, even trying to console.log the asc object leads to react erroring straight away:

`Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)`

Any ideas ?

**Comment by dcodeIO** [comment]
Looks like a message from webpack [experiments](https://webpack.js.org/configuration/experiments/).

**Comment by BatiGencho** [comment]
@dcodeIO 

After many attempts and using `import asc from "assemblyscript/dist/asc.js";`, I am now getting:

ERROR in ./node_modules/assemblyscript/dist/asc.js 367:41-57
Module not found: Error: Can't resolve 'module' in '/home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/dist'
resolve 'module' in '/home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/dist'
  Parsed request is a module
  using description file: /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/dist/node_modules doesn't exist or is not a directory
      /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/node_modules doesn't exist or is not a directory
      /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules
        single file module
          using description file: /home/evgeni/Documents/development/massa/create-react-app-massa/package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.js doesn't exist
            .web.ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.ts doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.ts doesn't exist
            .web.tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.tsx doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.jsx doesn't exist
        /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module doesn't exist
      /home/evgeni/Documents/development/massa/node_modules doesn't exist or is not a directory
      /home/evgeni/Documents/development/node_modules doesn't exist or is not a directory
      /home/evgeni/Documents/node_modules doesn't exist or is not a directory
      looking for modules in /home/evgeni/node_modules
        single file module
          using description file: /home/evgeni/package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.js doesn't exist
            .web.ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.web.ts doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.ts doesn't exist
            .web.tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.web.tsx doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/node_modules/module.jsx doesn't exist
        /home/evgeni/node_modules/module doesn't exist
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules
        single file module
          using description file: /home/evgeni/Documents/development/massa/create-react-app-massa/package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.js doesn't exist
            .web.ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.ts doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.ts doesn't exist
            .web.tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.tsx doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module.jsx doesn't exist
        /home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/module doesn't exist
        
       
It just seems that what used to be under /cli/asc is not a module anymore. And I am not talking about importing it here, but actually making a reference ot asc afterwards e.g. console.log(asc). Can someone in your team look at it  please. Thanks a lot

**Comment by BatiGencho** [comment]
React is showing me: 

Compiled with problems:X

ERROR in ./node_modules/assemblyscript/dist/asc.js 367:41-57

Module not found: Error: Can't resolve 'module' in '/home/evgeni/Documents/development/massa/create-react-app-massa/node_modules/assemblyscript/dist

**Comment by trusktr** [comment]
Sounds like you changed from one error to another. Whatever you changed, I recommend going back to the state when you had the top level await problem, then enabling top level await. Does that work?

**Comment by BatiGencho** [comment]
@trusktr I was getting the previous error with a create-react-app (latest version has webpack 5 in it). Unfortunately, webpack configs are not exposed and I had to use create-react app- wired which allowed me to overwrite existing webpack configs and add the top-level-await. Then I got the atuff above. Can someone in the community try importing asc in a react template to

**Comment by AurelienFT** [comment]
I have successfully used the module by using craco instead of react-script to override the `webpack.config.js` with this `craco.config.js` : 

```
const webpack = require('webpack');

module.exports = {
    webpack: {
      configure: {
        experiments: {
          topLevelAwait: true,
        },
        resolve: {
            fallback: {
                fs: require.resolve("browserify-fs"),
                stream: require.resolve("stream-browserify"),
                path: require.resolve("path-browserify"),
                buffer: require.resolve("buffer/"),
                util: require.resolve("util/"),
                url: require.resolve("url/"),
                module: false
            },
        },
        plugins: [
            new webpack.ProvidePlugin({
                Buffer: ['buffer', 'Buffer'],
            }),
        ]
      },
  }
};
```

You just need to install the listed packages in the requires and it works

**Comment by BatiGencho** [comment]
We already have a create-react-app repo where I have setup everything. As is also in there. FE cannot make  a use of the AS compiler if that is what you are looking fot - it needs too much webassembly memory and it fails, that's why it is meant to be used as a cli. Otherwise other AS lib features might be importable for sure. Remember there is a repo called massa-sc-utils that makes haevy use of the as compiler !
