### ISSUE TITLE
External Method Overloading

### ISSUE THREAD

**Issue by mrchantey** [AssemblyScript/assemblyscript#2261]
It looks like the following compiles but is not supported:

```
@external('myModule', 'doSomething')
export declare function doSomething_1( value: u32 ): void

@external('myModule', 'doSomething')
export declare function doSomething_2( value: Uint32Array ): void
```

The result seems to be that the compiler will pick one and cast all calls to that type. 
In my case the integers were coming out on the js side as very strange arrays 😅

I understand acutally implementing this may be a bigger discussion, but perhaps we should be throwing a compiler error?
Also maybe it deserves a mention in the [docs](https://www.assemblyscript.org/compiler.html#using-esm-bindings) for chumps like me.

**Comment by dcodeIO** [comment]
Technically it is possible to have multiple imports of the same name in Wasm, but as soon as bindings come into play, matters become a bit more complicated due to JS's dynamic nature. In the example above, both `doSomething_1` and `doSomething_2` pass a 32-bit integer value under the hood, yet share the same `doSomething` import name. The bindings can do one of the following now:
1. Try to rename one of them and basically ignore the `@external` annotation.
2. Honor the annotation, but then there is no way to distinguish between the two. All JS sees is a number.
Ideas?

**Comment by mrchantey** [comment]
I'm [currently](https://github.com/mrchantey/koora/blob/213e11a63f9ab2f7799894d5eafd6ceb8d31a200/packages/core/src/utils/classUtils.ts#L2) creating `doSomething_1` and `doSomething_2` on the host which both point to the same `doSomething`. 
```typescript
myModule.doSomething_1 = myModule.doSomething
myModule.doSomething_2 = myModule.doSomething
```

Perhaps we can build something similar into the bindings generator, something like:

"Ah I've found two external calls with the same name. I'll create two JS bindings which each transform the data to match the AS signature, and they will pass that to the single import."

In my case working on WebGL calls, the following binding glue is generated:
```typescript
bufferData__1(target, srcData, usage) {
  // src-as/WebGL2/imports/_types/bufferData_1(u32, ~lib/typedarray/Float32Array, u32) => void
  target = target >>> 0;
  srcData = __liftTypedArray(Float32Array, srcData >>> 0);
  usage = usage >>> 0;
  __module0.bufferData__1(target, srcData, usage);
},
```
If I understand correctly its only the last line that would need to drop the suffix: 
`__module0.bufferData(target, srcData, usage);`

**Comment by trusktr** [comment]
@mrchantey let's chat about WebGL bindings. Prior art:

Bindings for a single instance of Webgl context: https://github.com/battlelinegames/ASWebGLue

I've been making a better version of manual bindings for DOM in general, and gave started moving ASWebGLue over, to allow things like `c = document.createElement('canvas'); gl = c.getContext('webgl'); ...` in AS code: https://github.com/lume/asdom

But I haven't tried the generation of functions with generated names like you're making. Perhaps we can work to coalesce on the best binding methods.

**Comment by mrchantey** [comment]
Sure, yeah i did something similar, nothing too fancy, something like:

1. Perform a couple of find-and-replace tweaks to convert `lib.dom.ts` definitions into `@external` assemblyscript definitions, result is [here](https://github.com/mrchantey/koora/blob/main/packages/core/src-as/WebGL2/imports/_types.ts)
2. Note overload counts as needed and iterate to add the suffixes, source [here](https://github.com/mrchantey/koora/blob/main/packages/core/src/utils/classUtils.ts)
3. Go back to the `@external` definitions and manually add the number suffixes to the overload types (that was the error prone part)
4. Perform an 'autobind' on the webgl context before passing it as an import, source [here](https://github.com/mrchantey/koora/blob/b47c34272ed0af8141e4d395d76f021f5534289c/packages/core/src/loader/KooraLoader.ts#L28)

I've gone in another direction with my project so wont be contributing heavily, but more than happy to discuss.
