### ISSUE TITLE
Checking if an optional parameter is undefined?

### ISSUE THREAD

**Issue by DanielNetzeriAm** [AssemblyScript/assemblyscript#227]
Trying to implement a simple function to slice arrays, and I want to check if the end parameter which is optional is undefined or not, 

```
export function slice(array: Array<string>, start: number, end?: number): Array<string> {
  let length = array == null ? 0 : array.length
  if (!length) {
    return []
  }
  start = start == null ? 0 : start
  end = end === undefined ? length : end
...
```

and getting the following error 

> ERROR TS2304: Cannot find name 'undefined'.
> end = end === undefined ? length : end
> in assembly/index.ts(27,16)

is there a type for undefined or am I doing something wrong here? (clearly I am).

regardless of this question, is there any place I can read simpler examples for the AssemblyScript? been struggling to understand how to user Array's and Objects with the memory allocation.

I'm trying to create an open sourced Lodash like library using WASM.

**Comment by dcodeIO** [comment]
In AssemblyScript, everything must have a strict type, hence it doesn't have `undefined` ([see](https://github.com/AssemblyScript/assemblyscript/wiki/Limitations)). You can use a default value, though. For example, this is what `Array#slice` does: https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/array.ts#L264

Examples: https://github.com/AssemblyScript/assemblyscript/tree/master/examples

**Comment by DanielNetzeriAm** [comment]
got you, What do you about extending the array.ts class to use enhanced functions and features taken from the lodash library? that seems like the only way to use Generics for an array

**Comment by dcodeIO** [comment]
Depends. If it is very useful in a way that benefits largely from being backed by low-level code, extending what the ECMAScript standard has might be an option. If it's more like "nice to have" functionality, maybe extending `Array<T>`, i.e. `MyArray<T> extends Array<T>`, yourself (which is possible in AssemblyScript) might be a better option.

**Comment by MaxGraey** [comment]
Close due to inactivity
