### ISSUE TITLE
Instantiating class that extends Array<generic> results in type conflict

### ISSUE THREAD

**Issue by JairusSW** [AssemblyScript/assemblyscript#2275]
Hello!
The title should say it all. This is in AssemblyScript `v0.20.4` and the latest release of `as-json` on the github master

```js
import "wasi"
import { JSON } from "./index";
class Arr extends Array<string> { }

const array: Arr = ["a", "b", "c"]

console.log(JSON.stringify(array))
```
The above code results in an error like:
```
$ asc assembly/test.ts --target test
ERROR TS2322: Type '~lib/array/Array<~lib/string/String>' is not assignable to type 'assembly/test/Arr'.

 const array: Arr = ["a", "b", "c"]
                    ~~~~~~~~~~~~~~~
 in assembly/test.ts(5,20)

FAILURE 1 compile error(s)
Done in 3.50s.
```

**Comment by dcodeIO** [comment]
The implicit cast in

```ts
const array: Arr = ["a", "b", "c"]
```

from `Array<string>` to `Arr` is an upcast, but not every `Array<string>` is necessarily an `Arr` (here these just so happen to be structurally compatible, but AS is nominal). Becomes more clear when adding a field to `Arr`, like

```ts
class Arr extends Array<string> {
  something: i32;
}
```
where an `Array<string>` from an array literal does not contain the field. Allowing the cast would produce an `Arr` that really is an `Array<string>` where an attempt to access the field would read OOB.

Not sure about your use case, but an alias would work in this particular example:

```ts
type Arr = Array<string>;
```

**Comment by JairusSW** [comment]
Thanks for the quick reply!
It makes sense
I'll close this now then :D
