### ISSUE TITLE
The problem of "AssertionError: assertion failed" when "run asbuild" without defining a constructor for the class is not precisely explained.

### ISSUE THREAD

**Issue by jaran-Www** [AssemblyScript/assemblyscript#2276]
If I use a class as a type without defining a constructor for the class, instead of prompting that I should define a constructor, the following intent-obscure prompt appears
![image](https://user-images.githubusercontent.com/64885588/165439406-264519bb-2813-42b7-88dc-12f5bd00fda4.png)
![image](https://user-images.githubusercontent.com/64885588/165438853-1da1b548-e6f3-42a9-8f52-b2c6a6d5cb14.png)

**Comment by dcodeIO** [comment]
Looks like this should work without a constructor, then using the copy strategy instead of passing by reference. From a quick test, the provided snippet of code seems to work, though. Can you provide a few more details to trigger the problem?
