### ISSUE TITLE
How to disable a compilation warning?

### ISSUE THREAD

**Issue by roaminroe** [AssemblyScript/assemblyscript#2277]
When compiling the following code, I get a warning when using AS 0.20.x
```ts
export namespace A {

}
```

```sh
WARNING AS235: Only variables, functions and enums become WebAssembly module exports.
```

Is there a way to disable those warnings? (like an `// @as-ignore` or something?) (I understand the warning, I would just like to know if it can be disabled somehow)

**Comment by dcodeIO** [comment]
The only way to suppress the warning currently is to remove the `export` modifier. That may not always be possible, for example when `A` is not only exported from the entry file but also imported in an internal file, so I guess a new command line option to specify a list of warnings would be the way to approach this.

**Comment by roaminroe** [comment]
Got it! 
Right, in my case I cannot remove the `export`, this is not a blocking issue, but that'd be awesome if there could be a way to suppress these warnings!

**Comment by MobButcher** [comment]
I also want to express interest in this feature. I need to export a class from one AssemblyScript module to use it in another AssemblyScript module, otherwise typing info won't pick up.

**Comment by romdotdog** [comment]
This would be beneficial for one of my projects also.

**Comment by VladChernenko** [comment]
You can use <code>assemblyscript@v0.19.9</code> to avoid warnings. I've also bumped with problems with class exports, so quicky checked version in package.json <a href="https://github.com/torch2424/wasm-by-example/blob/master/examples/classes/demo/assemblyscript/package.json">here</a>
