### ISSUE TITLE
Enhancement: Generate test coverage report after npm test

### ISSUE THREAD

**Issue by JesseCodeBones** [AssemblyScript/assemblyscript#2289]
Currently, the project do not have test coverage feature, and we donot know if the test is enough or not.
So I suggest if we can have test coverage feature, it is better for us to control test or CI flow in the future.
I will introduce C8 here:
Here is the website and documentation of C8:
https://www.npmjs.com/package/c8
C8 can generate html report, text report, cobertura report and etc.
Here is report screenshot:
![image](https://user-images.githubusercontent.com/56120624/167804775-f2d25814-8256-4333-9733-ef84a43037a4.png)
![image](https://user-images.githubusercontent.com/56120624/167805015-e29b5bf5-8ef0-4655-846f-80d067e9740a.png)
it also report directly during test run:
![image](https://user-images.githubusercontent.com/56120624/167805219-687c1e8e-9568-4ebc-998c-bff6f860eb84.png)
The report will generated under `./coverage` folder, of cause it should be git ignored.

**Comment by JesseCodeBones** [comment]
I created one PR, please kindly review and decide if we need this feature, thank you:
https://github.com/AssemblyScript/assemblyscript/pull/2290

**Comment by JesseCodeBones** [comment]
I skiped the lib folder and created a new PR, please kindly check, thanks.

**Comment by dcodeIO** [comment]
Optional code coverage has been added in #2517 in spirit of #2294. There's some [documentation](https://github.com/AssemblyScript/assemblyscript/tree/main/tests#coverage). Do you want to keep this issue open to track further progress, or can we close?

**Comment by JesseCodeBones** [comment]
@dcodeIO 
I will close it, for the test progress, I think it is suitable to divide them with different functionalities.
