### ISSUE TITLE
Enhancement: optimize tests of parameter type parser according to test coverage report

### ISSUE THREAD

**Issue by JesseCodeBones** [AssemblyScript/assemblyscript#2296]
Hi Guys,
I tried to enhance the test coverage, there is some missing part according to coverage report.
I might commit several commits or PRs under this issue, please let me know if it is not suitable.
Thank you.
Regards

**Comment by JesseCodeBones** [comment]
Phase: 1
File: src/parser.ts
Functions: [parseTypeParameter, parseParameters]
PR: https://github.com/AssemblyScript/assemblyscript/pull/2297

**Comment by JesseCodeBones** [comment]
I found it could be a issue for test:  
```// 1003: Identifier expected.
function extendsfunctiontype(this: ()=>void):void {}```  
the result is we get 1003 but we still can see it is compiled as below:
`function extendsfunctiontype(): void {}`  (that means it is included into AST now)
I am not sure if it is reasonable, because extends from anonymous function type is meaningless.
can you help to look at it? thank you.

**Comment by dcodeIO** [comment]
The parser/compiler try to recover from errors that will ultimately cause compilation to fail, so more than one error can be diagnosed. Here, the recognizable parts of the AST are still produced during parsing, but their compilation is not attempted.

**Comment by JesseCodeBones** [comment]
@dcodeIO 
Hi DcodeIO,
I tried to fix the test coverage to 90.37%.

![image](https://user-images.githubusercontent.com/56120624/170420734-2d4faac6-b9ea-4be8-a955-115451503737.png)

and I find a small issue here.
at parser.js line 2097, `parseClassMember` function.
the error message should be `private modifier cannot be used here` instead of `protected modifier cannot be used here`
Can you advice is we can fix it in this PR or we need another issue and another PR? thank you.

```
        } else if (flags & CommonFlags.PRIVATE) {
          this.error(
            DiagnosticCode._0_modifier_cannot_be_used_here,
            tn.range(accessStart, accessEnd), "**protected**"
          ); // recoverable
        }
```

**Comment by dcodeIO** [comment]
I guess this can be one PR, along the lines of "fix: X and add additional tests". Does this sound OK?

**Comment by JesseCodeBones** [comment]
@dcodeIO 
OK, I will prepare it, thank you.

**Comment by JesseCodeBones** [comment]
@dcodeIO 
Hi dcodeIO,
I noticed this issue has been closed, do we have plan to enhancement this part? Thank you.
Regards
