### ISSUE TITLE
[info] Assembleash playground support AS Next now

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#23]
If some looking for playground for current assemblyscript version so [Assembleash](https://maxgraey.github.io/Assembleash/#AssemblyScript) support it except standard library and definitions

**Comment by dcodeIO** [comment]
Also added to the [wiki](https://github.com/AssemblyScript/assemblyscript/wiki/Built-with-AssemblyScript), thanks!
