### ISSUE TITLE
Unclear way to free memory that was allocated by `new`

### ISSUE THREAD

**Issue by kyasbal-1994** [AssemblyScript/assemblyscript#230]
Hi, I think it is very important to write about this topic explicitly.

---

```ts
class Vector2{
   public x:u32;

   public y:u32;
}
```

When you created such a class shown above, you may use `new` keyword to create an instance like the code below.

```ts
for(let i:u32 = 0; i < 10000000; i++){
   let v = new Vector2();
   // Some of code using vector2 here
}
```

However, AssemblyScript has no GC feature at this point, the v allocated for each loop iteration will not be released. You can confirm this phenomenon with inspecting `exports.memory.buffer.byteLength` from javascript. To remove class instance explicitly like C++ languages, AssemblyScript require you to write release code explicitly.

This can be done with `memory.free` method. This method receive a pointer to release. We can retrive a pointer to the instance by calling `changeType<usize>(instance)`.

```ts
for(let i:u32 = 0; i < 10000000; i++){
   let v = new Vector2();
   // Some of code using vector2 here
   memory.free(changeType<usize>(v));
}
```

---

I don't think this way is so clear since the memory.free can't receive class instance variable directly. Even that, it is very hard to notice how it shoud be done.

**Comment by dcodeIO** [comment]
Yeah, using `new` anticipates a GC to be present. An initial implementation is [here](https://github.com/AssemblyScript/assemblyscript/pull/196). One day this will be the default.

Without a GC, this is essentially simply equivalent to:

```ts
var v = changetype<Vector2>(memory.allocate(offsetof<Vector2>()));
...
memory.free(changetype<usize>(v));
```

**Comment by Macmee** [comment]
hi @dcodeIO am I safe now to import and use `import "collector/itcm";` for my project, or should I instead implement my own form of manual reference counting on top of tlsf until itcm has matured? Thanks!

**Comment by dcodeIO** [comment]
The itcm GC is still somewhat experimental and hasn't been tested a lot yet. If you are fine with investigating and reporting potential bugs, you can use it, of course.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
