### ISSUE TITLE
'asc' will not exit with exit code 1 after compile failing

### ISSUE THREAD

**Issue by HerrCai0907** [AssemblyScript/assemblyscript#2311]
environment: 
- node v16.14.2 
- Linux ubuntu 5.13.0-44-generic

npx asc assembly/index.ts  && echo "should not be printed"
ERROR TS2304: Cannot find name 'c1'.

   c1;
   ~~
 in assembly/index.ts(5,3)

FAILURE 1 compile error(s)
should not be printed

**Comment by trusktr** [comment]
I noticed I get exit code `0` on some failures too. I don't have a reproduction right now. Do you?

**Comment by HerrCai0907** [comment]
It can be re-produced by `npx asinit .` and then write some wrong code. 
Then using `npm run adbuild && echo "do not echo"`, You will find "do not echo" is printed in console

**Comment by HerrCai0907** [comment]
It can be re-produced by `npx asinit .` and then write some wrong code. 
Then using `npm run adbuild && echo "do not echo"`, You will find "do not echo" is printed in console
