### ISSUE TITLE
binding code crashes after instantiate trying to extract exports

### ISSUE THREAD

**Issue by Pyrolistical** [AssemblyScript/assemblyscript#2320]
I generated some raw bindings but when I tried to run it, I ran into this bug
https://github.com/AssemblyScript/assemblyscript/blob/main/src/bindings/js.ts#L602

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiate, the return value of is a promise of an object containing instance and module.

It is the instance that has the `exports` field.

**Comment by Pyrolistical** [comment]
I see what is going on. WebAssembly.instantiate has a really bad API.

According to mdn:

> The primary overload takes the WebAssembly binary code, in the form of a [typed array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays) or [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer), and performs both compilation and instantiation in one step. The returned Promise resolves to both a compiled [WebAssembly.Module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module) and its first [WebAssembly.Instance](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Instance).

> The secondary overload takes an already-compiled [WebAssembly.Module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module) and returns a Promise that resolves to an Instance of that Module. This overload is useful if the Module has already been compiled.

The raw binding expects that later.

An instanceof assertion that module is a [`WebAssembly.Module`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module) at the start of the binding would have detected this

**Comment by 0xorial** [comment]
@Pyrolistical you are my savior!
