### ISSUE TITLE
Typo: suboptimial should be suboptimal 

### ISSUE THREAD

**Issue by HerrCai0907** [AssemblyScript/assemblyscript#2332]
When I use --converge, compile throw a Error `Last converge was suboptimial`. Should it be `Last converge was suboptimal.`?

**Comment by romdotdog** [comment]
https://github.com/AssemblyScript/assemblyscript/blob/291f9b632e2735449fe9b9a141f84dabce7cd856/cli/index.js#L838
Yes, it should be suboptimal.
