### ISSUE TITLE
Calling more than one function defined in host application causes memory exceptions.

### ISSUE THREAD

**Issue by rybakatchya** [AssemblyScript/assemblyscript#2334]
I am building assemblyscript to wasm and embedding it in a c# application via wasmersharp. I am having a bit of an issue though.

```
import { print } from "./imports/env";
import { test_int } from "./imports/env";

export function mainz() : i32
{
   print("33");
   test_int(32);
   return 1;
}
```

the following assembly script causes a segmentation violation exception in wasmer when test_int(32); is called. 

This made me feel like my implementation of the test_int function was incorrect. However if i comment out the print("33"); function then test_int function works fine. But if I then make a call to test_int(32) twice within mainz() it causes another segmentation violation.

I am also getting similar behavior when calling print() twice within mainz() if I call print once it works fine but when calling print twice within mainz() I get a memory access violation.

I do not believe my implementation of either of these functions are whats causing the issue here but just in case here is how they are defined on the host application. 

```csharp
        static void Print(InstanceContext ctx, int ptr)
        {
            Console.WriteLine(ScriptEngine.ReadString(ctx, ptr));
        }

        static void TestInt(InstanceContext ctx, int data)
        { 
            Console.WriteLine(data.ToString());
        }
        
        public static string ReadString(InstanceContext ctx, int ptr)
        {
            // The byte length of the string is at offset -4 in AssemblyScript string layout.
            var memoryBase = ctx.GetMemory(0).Data;
            var result = "";
            unsafe
            {
                var len = Marshal.ReadInt32(memoryBase + ptr - 4);
                result = Encoding.Unicode.GetString((byte*)memoryBase + ptr, len);

                
            }
            return result;
        }
```
Is this an error with assembly script or a problem with wasmer?

**Comment by dcodeIO** [comment]
A segmentation violation exception sounds like something that cannot be caused by the Wasm module (if anything goes wrong within, one would see a trap / call to `abort`). As such this looks like something going wrong on the host side. What's the exact exception message? Have you tried logging the value of `memoryBase` (perhaps comparing to `memory.DataLength`) to see if something is off?

**Comment by rybakatchya** [comment]
> A segmentation violation exception sounds like something that cannot be caused by the Wasm module (if anything goes wrong within, one would see a trap / call to `abort`). As such this looks like something going wrong on the host side. What's the exact exception message? Have you tried logging the value of `memoryBase` (perhaps comparing the accessed offset to `memory.DataLength`) to see if something is off?

If I call print() followed by test_int in main (like in the posted example) or if I call test_int twice in a row, the exact exception message I get is "error calling method Call error: "unhandled trap at 1e4357c0163 - code #c0000005: segmentation violation". The print call does work and goes through then the exception happens as soon as test_int is attempting to get invoked on the host. (This even happens if the test_int host function is just an empty function with no body). 

If I call print() twice I get the exact exception message I get is error calling method Call error: WebAssembly trap occured during runtime: memory out-of-bounds access. Again the first call is fine and then the second call is where the exception is thrown. 

if i only call print or test_int there is no error and functions work fine. 

these errors also happen if the host functions are empty with no body

The value of memory base doesn't seem off to me but what exactly would off look like?
