### ISSUE TITLE
Static type checking for function's arguments

### ISSUE THREAD

**Issue by NekoMaru76** [AssemblyScript/assemblyscript#2345]
```ts
function F(arg1: Arg1, arg2: Arg2): Ret {
    //
}

isValidCall(F, arg1, arg2);//: bool
```

**Comment by MaxGraey** [comment]
Could you explain in more detail what is going on here and what you expect?

**Comment by NekoMaru76** [comment]
```ts
function isValidCall(f: CallableFunction, ...args: auto[]): bool;
```

Check does it is possible to call the `f` function with the arguments `args`.

**Comment by MaxGraey** [comment]
Hmm, still not clear. Could you write this implementation on JS at least? I just understand that you are trying to dynamically validate static code (function's signature), which often makes no sense in an AOT compiled environment. Maybe you need something else? What are you trying to solve? What is initial problem?
