### ISSUE TITLE
[Feature request] Allow disabling abort information with an option

### ISSUE THREAD

**Issue by Semisol** [AssemblyScript/assemblyscript#2358]
Currently, `env.abort` outputs file names to the binary even if it is overriden to not do anything, for example:
```
function abort(message: usize, fileName: usize, line: u32, column: u32): void {
    unreachable()
}
```

Adding an option (for example `--disable-abort-information`) would be useful in reducing release file size and possibly not leaking information about the project structure.

**Comment by MaxGraey** [comment]
Foremost, you can disable assertions (`--noAsserts` option). Also, you can completely disable aborts via `--use abort=` option.

Besides, please read documentation: https://www.assemblyscript.org/concepts.html#special-imports

**Comment by romdotdog** [comment]
Hm, I think it would still be useful to both not leak information and not allow undefined behavior. I wouldn't call this closed.

**Comment by romdotdog** [comment]
From the link:

> The respective implementations of `abort`, `trace` and `seed` can be overridden with, for example, `--use abort=assembly/index/myAbort`, here redirecting calls to `abort` to a custom `myAbort` function in `assembly/index.ts`.
