### ISSUE TITLE
can we use third party npm packages?

### ISSUE THREAD

**Issue by haider-rs** [AssemblyScript/assemblyscript#2364]
I have installed a npm package. and imported in my index.ts file in assembly, when when I try to run npm run asbuild it throws this error. is it possible to use third party packages in assemblyscript?

thanks

**My index.ts file:**

```
import * as web3 from "@solana/web3.js";

export function add(a: i32, b: i32): i32 {
  return a + b;
}
```

**Error**

```
ERROR TS6054: File '~lib/@solana/web3.js.ts' not found.

 import * as web3 from "@solana/web3.js";
                       ~~~~~~~~~~~~~~~~~
 in assembly/index.ts(2,23)

FAILURE 1 parse error(s)
```

**Comment by MaxGraey** [comment]
No, you can't use js/ts packages from npm which don't [adopted for AssemblyScript within AS sources](https://www.assemblyscript.org/concepts.html#typescript-like). You should can you use it outside as sources and import some method inside AS using bindings: https://www.assemblyscript.org/compiler.html#host-bindings

**Comment by Haider-Ali-DS** [comment]
cool, thank you for reply, by any chance can you give me more reference / links to host bindings?

**Comment by MaxGraey** [comment]
Just add `--binding esm` to `asc`. For importing from host specific functions, you should also declare it in AS code using `declare` keyword:
```ts
@external("env", "print")
declare function print(str: string): void;

@external("env", "getArray")
declare function getArray(): Array<i32>;
```
See mode details in https://www.assemblyscript.org/compiler.html#host-bindings

**Comment by Haider-Ali-DS** [comment]
thank you!
