### ISSUE TITLE
await in startup script

### ISSUE THREAD

**Issue by gergelyk** [AssemblyScript/assemblyscript#2377]
While invoking `asc --help` I'm getting "SyntaxError: Unexpected reserved word" pointing to `await`:

https://github.com/AssemblyScript/assemblyscript/blob/d5599823cc7af3b858967477a4c3520f5c7784b0/bin/asc.js#L22

Is it legal to use such dynamic import in a top-level script? Or as JS newbie I must be missing something.

node version: v12.22.12

**Comment by MaxGraey** [comment]
Minimal requirements for asc is node.js v16
