### ISSUE TITLE
The generated code was incorrect when create array using []

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#239]
The code [https://webassembly.studio/?f=c3bofizosgn](https://webassembly.studio/?f=c3bofizosgn)

Expeced the result: 
```shell
1
2
```

In fact got result
```shell
1
3
```

The generated wast text of createArray:
```wast
 (func $main/createArray (; 11 ;) (type $ii) (param $0 i32) (result i32)
  (local $1 i32)
  (local $2 i32)
  ;;@ main.ts:9:2
  (set_local $1
   ;;@ main.ts:9:18
   (i32.const 16)
  )
```

The various of `var arr` scope should be function scope,  but set up  to `i32.const 16` which is static scope.

**Comment by MaxGraey** [comment]
[Fixed](https://webassembly.studio/?f=d0hsqgtonib)
