### ISSUE TITLE
SyntaxError: Unexpected token '.' on attempt to run `npm start`

### ISSUE THREAD

**Issue by AntonKornus** [AssemblyScript/assemblyscript#2391]
Hello!
I was following your "Getting started" [guide](https://www.assemblyscript.org/getting-started.html#getting-started) step by step and faced with next error on attempt to run `npm start` : `Unexpected token '.'`

Here is screenshot of error:
![Снимок экрана (61)](https://user-images.githubusercontent.com/13347945/181602606-e1ba0bad-584a-4d65-a85a-f3f63b4b9d91.png)

Also log file mentioned on screenshot:
[2022-07-28T17_37_22_030Z-debug-0.log](https://github.com/AssemblyScript/assemblyscript/files/9212997/2022-07-28T17_37_22_030Z-debug-0.log)

I'm using `Windows 11` and have tried with `node 16.16.0` and with the latest `18.7.0`

**Comment by dcodeIO** [comment]
Could be nvm-windows somehow interacting with npm, as [discussed here](https://github.com/npm/cli/issues/4234). On a glimpse, seems like the same issue to me.

**Comment by AntonKornus** [comment]
> Could be nvm-windows somehow interacting with npm, as [discussed here](https://github.com/npm/cli/issues/4234). On a glimpse, seems like the same issue to me.

Somewhy it works with `node 16.13.2`
