### ISSUE TITLE
AssemblyScript in Web Workers?

### ISSUE THREAD

**Issue by armandn** [AssemblyScript/assemblyscript#2400]
Sorry if this is not the proper place to ask.

Assuming a relatively complex computation that may take seconds/minutes to complete, how could an AssemblyScript running in a web worker send updates to the main thread? 

In Javascript, this is simply a matter of using `postMessage()`. How would AssemblyScript use postMessage()?

**Comment by MaxGraey** [comment]
WebAssembly doesn't provide any job with workers. It only specifies some atomic operations and allow read / write for shared memory. Also note AssemblyScript doesn't have thread safety yet for worning with SharedArrayBuffer. But you still can works in old fashion with message passing between web workers which load individual wam instances and syn all job on JS side. See example: https://blog.feather.systems/mandelbrot.html
