### ISSUE TITLE
Question: no one use the compileElement function of compiler.ts

### ISSUE THREAD

**Issue by JesseCodeBones** [AssemblyScript/assemblyscript#2402]
Hi Maintainer,

It is strange for function `compileElement` of compiler.ts  
It is not exported from the file and no function in the ts file calling it, is it a dead code block or it is on purpose?

It is added from this [commit](https://github.com/JesseCodeBones/assemblyscript/commit/0c64f21250ef8a8fb61f2c64d3691bae1515fc75#diff-041bb58b49fbc5e7fdf9b8d09f0f0ae8d524d727947bcfa3e3d1c91b8a35aeee)  
but no one call it from the first place.

Regards

**Comment by MaxGraey** [comment]
Yeah, looks like dead code which was not cleaned up after some global refactoring
