### ISSUE TITLE
Can the `cookie` parameter of `__visit` be removed?

### ISSUE THREAD

**Issue by ApsarasX** [AssemblyScript/assemblyscript#2408]
I'm reimplementing the incremental runtime of AssemblyScript in C. 

And I found that some visiting functions(`__visit` `visitRoots` `visitStack`) of GC all have `cookie` parameters, but they are only passed without using it.

So what is the function of `cookie` parameter?

Can I remove it?

<img width="596" alt="截屏2022-08-05 15 39 02" src="https://user-images.githubusercontent.com/24390069/183027122-46c0118e-f221-41c2-a9dd-b3eea9cba27b.png">

**Comment by dcodeIO** [comment]
The cookie parameter has remained from previous implementations, where multiple operations during visiting were possible (increment / decrement reference count). Hasn't been removed in anticipation of potential future cases where, besides marking, other operations could be useful. Probably doesn't matter much once Wasm GC becomes a thing.
