### ISSUE TITLE
How to make function decorator with transfrom?

### ISSUE THREAD

**Issue by Umenokin** [AssemblyScript/assemblyscript#2418]
Hello,

I am trying to write a transform class for custom function decoration.

What I want is to take this:
```
@handler
export function handle(Request req): Response {}
```

And turn it into something like:
```
import {processRequest} from 'sdk';

// Ideally name handle to something like inner_handler and remove export just in case
export function handle(requestPtr: usize, requestSize: usize): usize {
  processRequest(requestPtr: usize, requestSize: usize, inner_handler);
}
```

Basically:
1. Transform should remove `export` from `handle`
2. Rename `handle` to say `inner_handle`
3. add a simple wrapper function which will import request data from the host
4. Call decorated function with the new `inner_handle` name
5. Export wrapper function instead of the one user wrote.

It is tough to find any information online. Can you recommend any examples or a small code snippet?
The way I see it:
1. Find decorated FucntionPrototype
2. Rename it and remove the export flag
3. Add a new FunctionPrototype with the body I need
4. Add this prototype to the body.

**Comment by MaxGraey** [comment]
There are some helper lib with useful examples:
https://github.com/willemneal/visitor-as

I hope this helps

**Comment by Umenokin** [comment]
Thanks @MaxGraey ! But to be honest not so much. I was able to find the element I did which I assume this library helping with? Like so:
```
afterInitialize(program) {
    program.elementsByName.forEach((el) => {
      if (!(el instanceof FunctionPrototype)) {
        return;
      }

      if (!this.hasDecorator(el, 'handler')) {
        return;
      }
```
But now, it is not clear how can to inject the code I need into the program. I checked as-json sources but they adding new method to decorated class while I need to inject a function into program and modify they one which is decorated.

**Comment by MaxGraey** [comment]
For your case you should use `afterParse(parser) {...}` and manipulate with AST

**Comment by MaxGraey** [comment]
Github has a lot of examples. Ask project for example:
https://github.com/ask-lang/ask/blob/main/ts-packages/transform/src/visitors/transform.ts#L207

**Comment by Umenokin** [comment]
Thanks a lot @MaxGraey it seems I am getting close!

**Comment by Heath123** [comment]
This works (not sure if it's the best way to do it but it works):
```ts
import { ClassPrototype, IdentifierExpression } from "assemblyscript"
import { Transform } from "assemblyscript/transform"

let decoratorCallbacks = {}

function processDecorators(program) {
  program.elementsByName.forEach((element) => {
    if (!(element instanceof ClassPrototype)) return
    if (!element.decoratorNodes) return

    // Loop over all the decorators
    for (const node of element.decoratorNodes) {
      if (!(node.name instanceof IdentifierExpression)) continue

      const name = node.name.text
      if (decoratorCallbacks[name]) {
        decoratorCallbacks[name](element)
      }
    }
    
  })
}

decoratorCallbacks["reverse"] = function (element) {
  console.log("Reversing", element.name)
  element.instanceMembers = new Map(Array.from(element.instanceMembers).reverse())
}

class MyTransform extends Transform {
  afterInitialize (program) {
    processDecorators(program)
  }
}
export default MyTransform
```

**Comment by stwiname** [comment]
@Umenokin did you figure this out in the end?
