### ISSUE TITLE
is there a way to yield WebAssembly module exports from other than entry file?

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [AssemblyScript/assemblyscript#2421]
is there a way to yield WebAssembly module exports from other than entry file? (maybe some decorator that would force it once file will be included in dep tree?)

https://www.assemblyscript.org/concepts.html#module-exports

**Comment by MaxGraey** [comment]
No, you should reexport or use that file as second entry. `asconfig` supports multiple entries

**Comment by DanielMazurkiewicz** [comment]
I wanted to ship a library with multiple optional such exports that will be used from JS side as callbacks and didn't wanted to put on lib user to do reexport it manually as it can be easily determined just by if the file is included in dependency tree or not.

Do you think we can add this as feature request?

**Comment by MaxGraey** [comment]
I don't really understand what you want. And why aren't a few entry files satisfactory to you? If you can demonstrate similar functionality in other languages, it might be easier to understand

**Comment by DanielMazurkiewicz** [comment]
```ts
import "./host"

//@ts-ignore
@external("env", "e")
@external.js(`
    let width = doc.documentElement.clientWidth;
    let height = doc.documentElement.clientHeight;
    onresize(width, height);

    wnd.onresize = evt => {
        width = doc.documentElement.clientWidth;
        height = doc.documentElement.clientHeight;

        onresize(width, height)
    }
`)
declare function useWndOnResize(): void

useWndOnResize()

//@ts-ignore
@wasm.export()
export function onresize(xSize: u32, ySize: u32): void  {
    console.log(`${xSize} ${ySize}`)
}
```

**Comment by MaxGraey** [comment]
See [this comment](https://github.com/AssemblyScript/assemblyscript/issues/1848#issuecomment-856342642). Globally export decorator is really bad pattern. It will lead to the fact that everything will be exported that you need and do not need, besides without analyzing all the files will be difficult to find out who is doing it except entry file

**Comment by DanielMazurkiewicz** [comment]
> is really bad pattern

it is, and it is due to poor design of wasm/js we have to deal with. But the issue can be easily mitigated by throwing compilation error when facing exports with same name from different places and there should be a recommendation that it should be used only for low level bindings. 

> without analyzing all the files will be difficult to find out who is doing

adding option to track that and print to console seem like piece of cake

> everything will be exported that you need and do not need

no, only needed stuff will get exported if you'll be including only files you need

**Comment by MaxGraey** [comment]
Also we have `@global` decorator which may use for constants / variables which contain sensitive data. And you can imagine a situation where you import someone else's code that checks for such a variable and exports it externally from a section of code that external lib control. That way you can get data out that you don't want to share at all. Of course, it could be farfetched, but I've cited a very real case which can be implemented right now, you just need to add the ability to export globally.

**Comment by MaxGraey** [comment]
Can you give me an example of a language where this is done? I would at least appreciate how they solved all these design and security problems there

**Comment by DanielMazurkiewicz** [comment]
> Can you give me an example of a language (with module & namespace system) where this is done?

nope

If safety of AS wasm module is your concern then you should not allow @external.js in a first place, as you can easily get with it any data out of wasm module without any mentioned sophisticated vectors of attack with 3 lines of code :-)

**Comment by MaxGraey** [comment]
> with it any data out of wasm module without any mentioned sophisticated vectors of attack with 3 lines of code :-)

AS mostly used in blockchain space now. With bindings to Rust/C++. As for JS bindings, you can import "eval" there. This can be done without the external.js decorator. So I don't really understand your irony

**Comment by MaxGraey** [comment]
This discussion has incidentally been in the past. So I'm closing this issue
