### ISSUE TITLE
Can't call the fact method of subclass,  when the method return the the super class type.

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#243]
The code [https://webassembly.studio/?f=u0j2rkrcq49](https://webassembly.studio/?f=u0j2rkrcq49)

Expected output:
1
2
In fact, the output:
1
1

**Comment by dcodeIO** [comment]
Also somewhat related to GC, in that there are no virtual methods / no virtual lookup table yet. In your fiddle

```ts
(<A>something).getAge(); // calls A#getAge
(<B>something).getAge(); // calls B#getAge
```

**Comment by MaxGraey** [comment]
Superseded by #693
