### ISSUE TITLE
Unreachable code of compiler.ts for PROPERTY_PROTOTYPE

### ISSUE THREAD

**Issue by JesseCodeBones** [AssemblyScript/assemblyscript#2436]
Hi Maintainer,
The functions: `compileAssignment`, `compileCallExpression` and `compilePropertyAccessExpression`. they all have switch case branch:
```ts
case ElementKind.PROPERTY_PROTOTYPE: {
  let propertyPrototype = <PropertyPrototype>target;
  let propertyInstance = this.resolver.resolveProperty(propertyPrototype);
  if (!propertyInstance) return module.unreachable();
  target = propertyInstance;
  // fall-through
}
```  
but during the `resolver.ts` the `PrototypeProperty` type will be resolved as `PROPERTY` type, so the switch case branch will never be entered.
can you help to verify if I am wrong? should we remove this branch if it is unreachable? thank you.
Regards

**Comment by MaxGraey** [comment]
@dcodeIO could you take a look?

**Comment by dcodeIO** [comment]
If this isn't used, we could either replace it with an `assert` so all cases remain covered by the `switch`, or document it for now. I'd somewhat prefer the latter option because it's not a lot of code and rather trivial, in case it'll one day be used.

**Comment by JesseCodeBones** [comment]
@dcodeIO 
Agree with you, can you advise how could we document it? with a warning?

**Comment by JesseCodeBones** [comment]
I will ignore this part from report, close this issue for now
