### ISSUE TITLE
Compile the super statement having no parameter failure.

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#245]
The code [https://webassembly.studio/?f=2tvvj50exc2](https://webassembly.studio/?f=2tvvj50exc2)

Expect compile the code successfully.
But get some errors.

```shell
ERROR TS1110: Type expected.

     super();
            ^
 in main.ts(9,11)


ERROR TS1005: '=>' expected.

     super();
            ^
 in main.ts(9,11)
```

**Comment by dcodeIO** [comment]
This should have been fixed meanwhile. Feel free to reopen if that's not entirely correct.
