### ISSUE TITLE
[Bug] Parser gets confused when parsing `null | T`

### ISSUE THREAD

**Issue by dosisod** [AssemblyScript/assemblyscript#2455]
Given the following AssemblyScript file:

```typescript
class C {
  x: u8 | null;
  y: null | u8;
}
```

I get the following errors:

```
$ asc tmp.ts
ERROR TS1005: 'null' expected.
   :
 3 │ y: null | u8 = null;  // Error, TS1005: 'null' expected.
   │           ~~
   └─ in tmp.ts(3,13)

FAILURE 1 parse error(s)
```

I would expect both lines to work.

Compiling the following TypeScript code (note the added `!`'s) it works just fine:

```typescript
class C {
  x!: number | null;
  y!: null | number;
}
```

It would seem that `| null` is only allowed at the end. The solution seems easy enough, seems to be somewhere near [src/parser.ts (line 530ish)](https://github.com/AssemblyScript/assemblyscript/blob/11094c50524bbd0e15f0c3da477b3e9d16e0abc5/src/parser.ts#L530-L534) if I had to guess. I am not familiar with this codebase, but I wouldn't mind making a PR this if need be!

Possible related: #2300

**Comment by MaxGraey** [comment]
This `y: u8 | null = null` doesn't support yet. Only references can be nullable. So it's not error

**Comment by MaxGraey** [comment]
However, this definitely a parser issue:
```ts
class C {
  y: null | string;
}
```
