### ISSUE TITLE
How can i call a host function correctly?

### ISSUE THREAD

**Issue by duxiaofeng-github** [AssemblyScript/assemblyscript#2462]
My company has a rust wasm runtime, it is hosted on a VM. I want to run a wasm compiled by assemblyscript in it.

My wasm needs to call a host function called `geode_get_timestamp(): i64`, how can I access this host function in assemblyscript correctly?

**Comment by MaxGraey** [comment]
Just declare this function and it will be imported:
```ts
declare function geode_get_timestamp(): i64;
```
or (if it's not a default "env" namespace)
```ts
@external("yourNamespace", "geode_get_timestamp")
declare function geode_get_timestamp(): i64;
```
For more info see documentation:
https://www.assemblyscript.org/concepts.html#module-imports

**Comment by duxiaofeng-github** [comment]
@MaxGraey thanks! i initialed a new project and added some code, as you said on index.ts, and built it to wasm successfully(by using `npm run asbuild`)

but when i run it on the rust runtime, it says `wasmi error: Instantiation: Module index not found`. any idea?

```
export declare function geode_get_timestamp(): i64;

export function start_service(): i32 {
  geode_get_timestamp();

  return 0;
}
```

**Comment by MaxGraey** [comment]
I have no idea. Ask at the repository wasmi

**Comment by duxiaofeng-github** [comment]
@MaxGraey thanks

it's a namespace issue. an external function declared in index.ts will transpile to `import "index" "geode_get_random_number"`(code in wat) and the external function is in the "env" module, so i rewrite it by using the "@external" decorator, everything is fine.

```
@external("env", "geode_get_random_number")
declare function geode_get_random_number(): i32;

export function start_service(): i32 {
  geode_get_random_number();

  return 0;
}
```
