### ISSUE TITLE
how can i get a string pointer

### ISSUE THREAD

**Issue by duxiaofeng-github** [AssemblyScript/assemblyscript#2463]
as this question mentioned: https://github.com/AssemblyScript/assemblyscript/issues/2462, i have another function called geode_log, it takes two parameters, the first one is a log string pointer, the second one is the log length.

So, how can i convert a string to a pointer and get its length?

i google it and find an answer, using `String.UTF8.encode` and `changetype`, but I ran it on rust wasm runtime, and an error came out: `wasmi error: Validation: Unknown opcode 252`, does anyone have any idea?

```
@external("env", "geode_log")
declare function geode_log(logPtr: i32, logLength: i32): i32;

function log(log: string): i32 {
  const logEncoded = String.UTF8.encode(log);

  return geode_log(changetype<i32>(logEncoded), logEncoded.byteLength);
}

export function start_service(): i32 {
  log("1");

  return 0;
}
```

**Comment by MaxGraey** [comment]
> wasmi error: Validation: Unknown opcode 252

I guess wasmi doesn't support bulk-memory feature. Just recompile with `--desable bulk-memory` flag
