### ISSUE TITLE
how can i call the start function

### ISSUE THREAD

**Issue by duxiaofeng-github** [AssemblyScript/assemblyscript#2464]
i run my wasm on wasmi, and wasmi will call a specific function called start_service, and it needs to return an i32 to the host to tell the host the service started successfully.

Also, wasmi doesn't allow the start function to run, so i need to use --exportStart init to export the start function to the init function (this start function is generated by the asc by default). But i need to invoke it manually at first on the start_service function as the (doc)[https://www.assemblyscript.org/concepts.html#accessing-memory-during-instantiation] describes.

so, how can i do that, any idea?

```
export function start_service(): i32 {
  // this function will be called by the host and I need to call the start(init) function here, but how?
  return 0;
}
```

**Comment by MaxGraey** [comment]
When you add `--exportStart start_service` all the logic in built-in  `strat` will prepend to `start_service`

**Comment by MaxGraey** [comment]
Please join to our Discord server and ask questions here. Issue tracker mostly need for bugs, issues, feature requests. For more specific questions, it is better to ask in Discord, where you will get a much faster answer and you will not create unnecessary noise for the watchers. Thanks!

**Comment by duxiaofeng-github** [comment]
@MaxGraey 

it seems that it will not be prepended to my export start_service, it said that the name is conflicted

```
> asc assembly/index.ts --target debug --disable bulk-memory --use abort=assembly/index/myAbort --exportStart start_service

ERROR AS110: Start function name 'start_service' is invalid or conflicts with another export.
   :
 1 │ [native code]
   │ ~~~~~~~~~~~~~
   └─ in ~lib/native.ts(1,1)

FAILURE 1 compile error(s)
```

**Comment by MaxGraey** [comment]
Hmm, in this case keep `start_service` as is and use `--exportStart _start` (WASI) style of naming for start function. Than on host just make a two calls:
```rust
_start();
start_service();
```

**Comment by duxiaofeng-github** [comment]
> Please join to our Discord server and ask questions here. Issue tracker mostly need for bugs, issues, feature requests. For more specific questions, it is better to ask in Discord, where you will get a much faster answer and you will not create unnecessary noise for the watchers. Thanks!

it's bad to discuss things on discord because the answer can't be crawled by google. I'm wondering why i can't find the answer even for the simple questions, that's why xD

**Comment by duxiaofeng-github** [comment]
can i call the _start function on start_service function?

**Comment by MaxGraey** [comment]
no

**Comment by duxiaofeng-github** [comment]
@MaxGraey so the only way i can do it that i need to create a string and get its pointer to avoid the start function come out? can i?

**Comment by MaxGraey** [comment]
`start` function always required if you're using GC-related objects. That's where runtime initialization happens.

**Comment by MaxGraey** [comment]
For example, you could use this approach:
```ts
import { log } from "./env";

log("Hello from AssemlyScript");
```
instead:
```ts
import { log } from "./env";

export function start_service(): i32 {
  log("Hello from AssemlyScript");
}
```
And use `--exportStart start_service`. But don't use and export `start_service` function actually. builtin `start` will be mimic to your `start_service`.

**Comment by duxiaofeng-github** [comment]
@MaxGraey thanks a lot for helping me. i know what you mean, but i can't decide the way how the host will execute my code, they will only call start_service, so either i call the _start function on start_service, or i allocate memory by myself on assemblyscript.

the first way, i think i need to change some assemblyscript code to modify the way of the compiler generating the wasm code.

the second one, i think maybe it's easier to achieve

**Comment by duxiaofeng-github** [comment]
and your code above can't work because of the return value, exportStart won't generate the return i32, so it will fail on the host call

**Comment by duxiaofeng-github** [comment]
```
function log(log: string): i32 {
  const logLength = String.UTF8.byteLength(log);
  const logPtr = heap.alloc(logLength);

  store<string>(logPtr, log);

  return geode_log(logPtr, logLength);
}
```

i'm trying to use this code instead, but i'm not sure if it's correct
