### ISSUE TITLE
Can No Longer Export an Export that Exports from Another File

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#248]
Hello! It has been a while haha! 😄 

So after going through and realizing this issue: https://github.com/torch2424/wasmBoy/issues/135

I got to catch up on a whole lot of AssemblyScript! 😄 So I went through and made the few updates I needed, and realized not all my functions were correctly exporting.

For instance, see this:

`Wasmboy Core, index.ts that exports all of our wasminstance exports:`
https://github.com/torch2424/wasmBoy/blob/943d79c3cbf525c00a3d73aa2a26a27b7cb24342/core/index.ts

`Another file within the core, that exports a function from another file:`
https://github.com/torch2424/wasmBoy/blob/943d79c3cbf525c00a3d73aa2a26a27b7cb24342/core/joypad/index.ts

I found that the Wasm instance exports, e.g `wasmInstance.exports.myExportFunctionHere` were not available. Meaning, I can no longer export functions from a file, that export a function from another file.

It was a quick an easy fix for me, but figured I might as well make an issue. Also, my apologies for the confusing title, it was the only thing I could think of, and gave me a good laugh. Thanks!

**Comment by torch2424** [comment]
Yes exactly :)

If you have trouble reproducing let me know, as I may have renamed some exports, using `export {myFunc as myAwesomeFunc} from './myfile'`.

**Comment by dcodeIO** [comment]
[Test](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/rereexport.ts) [case](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/rereexport.untouched.wat). Let me know if there are still any issues :)

**Comment by torch2424** [comment]
Rad thanks I'll update and everything 😄
