### ISSUE TITLE
bindings are cooler than loader, except they don't allow imports and are hard to use with web workers.

### ISSUE THREAD

**Issue by MichaelJCole** [AssemblyScript/assemblyscript#2488]
I'm upgrading a project from awhile ago.

I was using the loader and now hacking up the autogenerated bindings.  The autogenerated bindings look way better for passing arrays.

The bindings code is cool, but it breaks a couple things:  imports and web workers

Web Workers can't fetch(), so the module has to be passed from the DOM thread over onmessage to the web worker. 
The Web Worker needs access "instantiate" function and wants to pass imports.  

The other problem is because it awaits automatically, it doesn't accept imports and can't be included in the Web Worker because it fetch()es.  

I made these changes and it's an awesome template though, thanks!

**Comment by dcodeIO** [comment]
Have you tried the "raw" bindings? These basically only provide an `instantiate` function for programmatic usage and as such allow more freedom in the actual implementation. Should solve the await/imports related challenges. Regarding fetch, that seems unfortunate. Did you previously bundle the binary in a JS file, or how did it work before?

**Comment by MichaelJCole** [comment]
Awesome, thank you!

**Comment by MichaelJCole** [comment]
Hmmm...  get the same output if I try `--bindings raw`
```
npx asc assembly/nBodyWasm.ts --target release --bindings raw --outFile output/nBodyWasm.wasm
```

**Comment by dcodeIO** [comment]
The output is similar, but omits the final instantiation that would `fetch` / `await` / obtain imports and provide exports. In fact, the `instantiate` function is used by the ESM bindings, but is the only export exposed by RAW bindings.
