### ISSUE TITLE
Proposal: Ability to compile to WebGL / WebGPU Shader

### ISSUE THREAD

**Issue by Awendel** [AssemblyScript/assemblyscript#2497]
One of the most popular libraries for GPGPU in the javascript eco-system is:

https://github.com/gpujs/gpu.js/

It works by taking a javascript function and compiles it to a WGSL shader at runtime.

It does so quite well, despite javascript not having any types.

Typescript of course would be a better foundation for compiling into shader format,
but AssemblyScript would be even better, since it is even more refined in terms of types and constraints.

Hence one could leverage the existing infrastructure to offer compile targets into WebGL shader and WebGPU shader formats.

Compiling could be done statically via cli utilities etc.

One would just have to include type definitions that match the types available in the respective shader environments.
For Math library stuff, I believe gpu.js should serve as a great foundation for translating calls etc.

I believe this proposal would increase the target group for this library substantially, since it targets web developers who are familiar with typescript etc, but don't want to use static languages directly, hence it seems like an organic extension of its founding principles.

**Comment by MaxGraey** [comment]
Automatic compilation to GPU or even automatic multi-threading is a very complex thing. GPU.js uses classic GPGPU tricks. But if we're talking about Compute Shaders for WebGPU for example, you need to execute scatter/gather commands intelligently, use non-blocking or atomic methods, etc. There are quite a few languages and DSLs that do this. For example Halide. This is a rather vast and complex area. Given that we have a very small team I wouldn't go into that just yet. The best we can do now is to translate AS into WGSL source code for functions with @wgsl decorators. Something like this:
```ts
@wgsl.fragment
@wgsl.location.out(0, "outColor", f32x4)
function simpleShader(): f32x4 {
   return f32x4(0.0, 1.0, 0.0, 1.0);
}
```
which will transpile to:
```hlsl
[[location(0)]] var<out> outColor : vec4<f32>;
      
[[stage(fragment)]]
fn main() -> void {
  outColor = vec4<f32>(0.0, 1.0, 0.0, 1.0);
  return;
}
```

**Comment by MaxGraey** [comment]
> One could begin just doing it very modular

AssemblyScript already supports [transforms](https://www.assemblyscript.org/compiler.html#transforms) which allows adding hooks between different compiler's stage. For example, get access to AST. It's already using a lot for DSL like approaches. So you can already start to experiment.

The only thing missing so far are specific v128 types such as f32x4, i64x2 and so on. At this moment there is only generalized v128 type which requires explicit operation call like:
```ts
const a: v128 = f32x4(0, 0, 0, 1);
const b: v128 = f32x4(1, 0, 0, 0);
const c = f32x4.add(a, b);
```
instead:
```ts
const a: f32x4 = f32x4(0, 0, 0, 1);
const b: f32x4 = f32x4(1, 0, 0, 0);
const c = a + b;
```

**Comment by Awendel** [comment]
Thanks for the nudge, seems like a great way to get started and run some experiments.

I guess it's up to you as the maintainers to decide whether additional output targets would make sense at some point as part of the AssemblyScript core library, or whether it's best if someone else starts a seperate project, explicitly targetting web shaders and perhaps using AssemblyScript as a dependency / backend for the translation logic.

If the latter is the case, feel free to close the issue.

**Comment by MaxGraey** [comment]
I think having built-in tools for translation in WGSL from some DSL (or limited set of AS language) is consistent with our main goal of being Web-cetric. Tighter integration with WebGPU definitely makes sense. It's just not a priority right now.

**Comment by PaperPrototype** [comment]
It would be insane if you could write games 100% in AssemblyScript.

I don't know much on the topic but I was hoping the syntax would be more something like:

```ts
export function fragment(): @wgsl.loc(0, "res") f32x4 {
   return f32x4(0.0, 1.0, 0.0, 1.0);
}
```
