### ISSUE TITLE
use TypedArray.wrap on static data linear memory

### ISSUE THREAD

**Issue by hudsonansley** [AssemblyScript/assemblyscript#2503]
I am passing memory to a module on instantiation, and I'd like to use TypedArray views into the memory within the as module code, passing in info for about "input" arrays start, length, and then accessing an array also written to the memory that will be the "output" of the as function processing of the input arrays, but I have not been able to find how to get a reference to the modules memory buffer with as to pass to, e.g., Uint16Array.wrap()

I could use load/store, but would prefer using array syntax.

E.g.:
```
    const ary = Uint16Array.wrap(<myModule.memory>);
    ary[index] = value;
```
instead of
```
    store<u16>(index << 1, value);
```
but I don't know how to reference the memory in my module's as code. I suspect this is something obvious I'm missing...

**Comment by dcodeIO** [comment]
Typed arrays, or here `Uint16Array`, are managed objects with more than just their data in memory. There is a GC header and so on, and casting memory to such a managed object won't work. The recommended way to work with just memory is indeed to use `load` and `store`. A slightly more convenient abstraction can be built on top of it using unmanaged classes, if desired

```ts
@unmanaged class CArray<T> {
  constructor(ptr: usize) {
    return changetype<CArray<T>>(ptr);
  }
  @operator("[]") __get(index: i32): T {
    return load<T>(changetype<usize>(this) + index * sizeof<T>());
  }
  @operator("[]=") __set(index: i32, value: T): void {
    store<T>(changetype<usize>(this) + index * sizeof<T>(), value);
  }
}
```

and used like

```ts
const cArray = new CArray<u16>(ptrToMemory);
cArray[...]
```

though there is no `.length` or likewise attached, of course, as it just references into raw memory.

**Comment by hudsonansley** [comment]
Thanks for the explanation and the helper class! 
I'm still a bit confused about WRAP though. I thought it was intended to "wrap" raw memory with an object that would conform to TypedArray and not alter the backing memory. Looking at this line in the docs for TypedArray.wrap
```Wraps a raw buffer to be viewed as a sequence of values of the typed array's value type.```
To me that sounds like it could create a TypedArray view into the backing linear memory if I just had a reference to that buffer object.
Also, load and store implicitly have a reference to the backing linear memory, so is there a global reference (or something) to this raw memory buffer?
Thanks for helping me understand this

**Comment by MaxGraey** [comment]
`<TypedArray>.wrap` is just a temporal workaround for second overloaded constructor signature of Typed array. We only support this one:
```
class <TypedArray> {
  constructor(length: i32) {...}
}
```
But original `TypedArray` also may accept `ArrayBuffer`. Due to current language limitation, we can't define a second signature for this. So static method `wrap` was introduced
