### ISSUE TITLE
Trailing comma in type alias causes TS1003 identifier expected compiler error

### ISSUE THREAD

**Issue by 0xJem** [AssemblyScript/assemblyscript#2509]
[Sample code](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmV4cG9ydCB0eXBlIFByaWNlTG9va3VwID0gKAogIHRva2VuQWRkcmVzczogc3RyaW5nLAogIGJsb2NrOiBpMzIsCiAgY3VycmVudFBvb2w6IHN0cmluZywKKSA9PiBzdHJpbmcgfCBudWxsOwoKZXhwb3J0IHR5cGUgUHJpY2VMb29rdXAyID0gKHRva2VuQWRkcmVzczogc3RyaW5nLCBibG9jazogaTMyLCBjdXJyZW50UG9vbDogc3RyaW5nKSA9PiBzdHJpbmcgfCBudWxsOwojIWh0bWwK)

This causes a TS1003 error on the comma after the third parameter:
```js
export type PriceLookup = (
  tokenAddress: string,
  block: i32,
  currentPool: string,
) => string | null;
```

```
ERROR TS1003: Identifier expected.
;;    :
;;  4 │ currentPool: string,
;;    │                    ^
;;    └─ in module.ts(4,22)
;; 
;; ERROR TS1012: Unexpected token.
;;    :
;;  4 │ currentPool: string,
;;    │                    ^
;;    └─ in module.ts(4,22)
```

This compiles fine:
```js
export type PriceLookup2 = (tokenAddress: string, block: i32, currentPool: string) => string | null;
```

Functionally, there is no difference between these. However, eslint/prettier will often cause example 2 to be wrapped into the format of example 1, so it would be nice for this to not error.

**Comment by MaxGraey** [comment]
Basically problem with trilling comma. This will work:
```ts
export type PriceLookup = (
  tokenAddress: string,
  block: i32,
  currentPool: string // removed last comma
) => string | null;
```

**Comment by 0xJem** [comment]
Yep, I realise that. It's a common rule in prettier/eslint to add the trailing comma (hence linting doesn't pick up on this). Does the AS compiler (transpiler?) _in general_ report problems with trailing commas? If so, I'll amend our linting rules. It would be nice for that to be mentioned somewhere, though!

**Comment by MaxGraey** [comment]
AS supports trailing commas even in cases where [TS fails](https://github.com/AssemblyScript/assemblyscript/blob/main/tests/parser/trailing-commas.ts#L31). We just accidentally miss this case.

**Comment by 0xJem** [comment]
Yes, I just confirmed that trailing commas are generally supported. e.g this works:
```js
  pushArray(
    records,
    getERC20TokenRecordsFromWallets(timestamp, contractAddress, contract, rate, blockNumber),
  );
```
