### ISSUE TITLE
Can the internal SORT<T>(ptr, len, comparator) function be used to sort memory directly?

### ISSUE THREAD

**Issue by hudsonansley** [AssemblyScript/assemblyscript#2512]
I am working on an AssemblyScript function that manipulates memory directly (setting --memoryBase and using that area) and I am currently using a TypedArray to set values and then sort, and then I copy that to the linear memory. It occurred to me that if I could store the values directly into the memory and sort it in place, that should save some time, and I saw the SORT function in https://github.com/AssemblyScript/assemblyscript/blob/main/std/assembly/util/sort.ts looks like it would do that for me.
Is it possible to use that SORT from an AssemblyScript module function? If so, it would be great to see some example code...
Related, an example of how to use memcopy in AssemblyScript would be great too...

**Comment by dcodeIO** [comment]
It should be possible to call `SORT` yourself, like so:

```ts
import { SORT, COMPARATOR } from "util";
SORT<i32>(ptr, len, COMPARATOR<i32>()); // or provide a custom comparator
```

Whether that's a good idea depends a little on the use case I guess. In some cases, `SORT` allocates temporary buffer on the heap for example. Also note, since this is internal, that there is no guarantee that the function will not be changed, renamed or removed.

**Comment by dcodeIO** [comment]
@MaxGraey Makes me realize that we should probably mark such helpers as `@unsafe`.

**Comment by MaxGraey** [comment]
I would prefer to add a non-standard static method "compare" for all builtin types. This has been suggested more than once in JS, but as usual it was dissolved in the noise of opinions:
https://es.discourse.group/t/builtin-ord-compare-method-for-primitives/724
