### ISSUE TITLE
How to define an array for a Uint8Array?

### ISSUE THREAD

**Issue by joticajulian** [AssemblyScript/assemblyscript#2518]
I would like to define a Uint8Array somehow in this way
```
let x = new Uint8Array([0,1,2,3,4,5,6])
```
but I see it's not possible.

what is the best way to do it without having to assign the elements one by one? (`x[0]=0; x[1]=1; ...`)

**Comment by MaxGraey** [comment]
```ts
const x = new Uint8Array(7)
x.set([0,1,2,3,4,5,6]);
```

**Comment by joticajulian** [comment]
Ok, thanks. It works!

However, the VS code is showing this error
```
  Argument of type 'number[]' is not assignable to parameter of type 'ArrayBufferView'.
  Type 'number[]' is missing the following properties from type 'ArrayBufferView': buffer, byteOffset, byteLength
  ts(2345)
```
do I have to use a specific extension in VS code?

**Comment by MaxGraey** [comment]
I don't see any errors in playground: https://bit.ly/3xNAx3x
Make sure you have latest AS version and proper `tsconfig.json`. Usually this config prepared by `npx asinit .` command

**Comment by joticajulian** [comment]
thanks I will check.
