### ISSUE TITLE
Missing CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by ryohey** [AssemblyScript/assemblyscript#2526]
CODE_OF_CONDUCT.md linked in CONTRIBUTING.md does not exist in main branch.
It was removed in the PR #2157, but was not intended?.
CODE_OF_CONDUCT.md is added at 5d05d978a3b63978981fa57b037b8b9dad9480f5

**Comment by dcodeIO** [comment]
This file has meanwhile been moved to the dedicated top-level organization repository ([here](https://github.com/AssemblyScript/.github/blob/master/CODE_OF_CONDUCT.md)). It's linked from the repo itself on the right sidebar, but seems we missed updating it in CONTRIBUTING.md.
