### ISSUE TITLE
Generated ESM bindings and --importMemory flag

### ISSUE THREAD

**Issue by scanline** [AssemblyScript/assemblyscript#2529]
Say I start a new AssemblyScript project using the `asinit` command. This will give me the default entry point
**./assembly/index.ts** which looks like this:
```
export function add(a: i32, b: i32): i32 {
  return a + b;
}
```

Compiling the sample will generate the following **index.js** file alongside the .wasm file:
```
async function instantiate(module, imports = {}) {
  const { exports } = await WebAssembly.instantiate(module, imports);
  return exports;
}
export const {
  add
} = await (async url => instantiate(
  await (async () => {
    try { return await globalThis.WebAssembly.compileStreaming(globalThis.fetch(url)); }
    catch { return globalThis.WebAssembly.compile(await (await import("node:fs/promises")).readFile(url)); }
  })(), {
  }
))(new URL("module.wasm", import.meta.url));

```

Actually running this project using the provided **index.html** works like a charm.

If I now modify the compiler options and add the `--importMemory` flag, try to view **index.html** once more it stops working though and crashes with the following error:
`Uncaught TypeError: WebAssembly.instantiate(): Import #0 module="env" error: module is not an object or function`

Looking back at the generated **index.js** file it's no wonder though - it's exactly the same as without `--importMemory`.

Interposed question: does this happen by intention?

If not, could the generated bindings file look a bit more like this:
```
async function instantiate(module, imports = {}) {
	const memory = new WebAssembly.Memory({
		initial: 1
	});
	const adaptedImports = {
		env: Object.assign(Object.create(globalThis), imports.env || {}, {
			memory
		})
	};

	const {
		exports
	} = await WebAssembly.instantiate(module, adaptedImports);

	return exports;
}
export const {
	memory,
	add
} = await (async url => instantiate(
	await (async () => {
		try {
			return await globalThis.WebAssembly.compileStreaming(globalThis.fetch(url));
		} catch {
			return globalThis.WebAssembly.compile(await (await import("node:fs/promises")).readFile(url));
		}
	})(), {}
))(new URL("module.wasm",
	import.meta.url));
```

Bonus question: I'm setting the initial memory size to 1 page here. Now I'm wondering if the value should reflect the `--initialMemory` compiler option.

**Comment by MaxGraey** [comment]
When you add `--importMemory` you should use `--bindings raw` and explicitly call `WebAssembly.compileStreaming` with import object that contain custom `WebAssembly.Memory`. Something like:
```ts
const memory = new WebAssembly.Memory({
  initial: 17 // pages
});
...  = await WebAssembly.instantiateStreaming(fetch("./release.wasm"), { env: { memory } })
```

**Comment by scanline** [comment]
Thanks for taking the time Max!

Well, now I'm wondering: Is my approach simply false or is the method you've outlined just another way of doing the same thing? What are the advantages?
I'm still thinking though that if someone decides for `--bindings esm` - alongside `--importMemory`, the generated bindings file should give something that just works and not throw an error like `Import #0 module="env" error: module is not an object or function`

**Comment by dcodeIO** [comment]
The combination of ESM bindings with `importMemory` or `importTable` merely forces their creation on the JS side, with no added benefit, since ESM bindings instantiate immediately so there is no way to provide a custom memory or table anyhow. Hence this case isn't covered currently, but should be almost trivial to support fwiw.
