### ISSUE TITLE
AssemblyScript compiler crashing due to unknown reason

### ISSUE THREAD

**Issue by raddad772** [AssemblyScript/assemblyscript#2534]
Hi there. I'm doing an experimental port of JSMoo, my pure JavaScript multi-system emulator, to AssemblyScript. Just doing baby steps, getting general structure in place for the NES emulator portion. I'm getting a weird crash I can't track down the reason for.

I'm sorry that I can't just provide a code sample that reproduces the crash, because I can't figure out why it's even crashing. I tried commenting out a ton of my code and it didn't make a difference.

You can clone my repo: https://github.com/raddad772/jsmoo
commit b323962 exhibits the issue.

If you go to the assemblyscript directory in the repo, just run 

npm run asbuild

and it'll crash.

Here's the crash log

```
C:\dev\personal\jsmoo\assemblyscript>npm run asbuild

> asbuild
> npm run asbuild:debug && npm run asbuild:release


> asbuild:debug
> asc assembly/index.ts --target debug


▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌
▌ C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\std\portable\index.js:198
▌     throw new AssertionError(message);
▌           ^
▌
▌ AssertionError: assertion failed
▌     at Z.assert (C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\std\portable\index.js:198:11)
▌     at Pn.finishResolveClass (C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\src\resolver.ts:3344:13)
▌     at Pn.resolveClass (C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\src\resolver.ts:3138:10)
▌     at Pn.resolveClassInclTypeArguments (C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\src\resolver.ts:3567:17)
▌     at Pn.resolveNamedType (C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\src\resolver.ts:253:29)
▌     at Pn.resolveType (C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\src\resolver.ts:155:21)
▌     at Pn.finishResolveClass (C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\src\resolver.ts:3259:32)
▌     at Pn.resolveClass (C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\src\resolver.ts:3138:10)
▌     at Pn.resolveClassInclTypeArguments (C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\src\resolver.ts:3567:17)
▌     at Pn.resolveNamedType (C:\dev\personal\jsmoo\assemblyscript\node_modules\assemblyscript\src\resolver.ts:253:29)
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!
```

I'd like to say that if it printed the actual name it was trying and failing to resolve, this would probably be easily within my capability to troubleshoot, but I am not experienced with node.js and do not have an environment to contribute to assemblyscript set up.

Thanks

**Comment by dcodeIO** [comment]
The `assert` in question is

https://github.com/AssemblyScript/assemblyscript/blob/f1592988cc2ae8ffebb077790ebe9a0fbd8a56aa/src/resolver.ts#L3344

where a field type of an unusual size is encountered. Hints towards either an unsupported field type that isn't properly diagnosed, say using `externref` which currently cannot be a field type, or a follow-up issue from a field type that failed to resolve in a previous step, perhaps producing/leaving a `void` type. Impossible to tell for sure without more context, though.

A strategy to find out whether there was a foregoing diagnostic swallowed by the assertion is to defuse the assert at this particular place in the compiler (say monkey-patch the type to `i32` if the assert would fail) so prior diagnostics can show up.

**Comment by dcodeIO** [comment]
Looks like the `funcref` fields here: https://github.com/raddad772/jsmoo/blob/b3239620a56424c20b822269920283ab01809cd8/assemblyscript/assembly/system/nes/nes_common.ts#L9-L23

Reference types cannot be stored into memory. We certainly need a better diagnostic for these.

**Comment by raddad772** [comment]
Thanks!
Definitely should have some kind of diagnostic about this
How does one do a function reference in AssemblyScript then? This is to be filled in later.
I'm also looking to make sure this is equivalent to a bound function, but I can change these to take an object as first parameter.

example I'd like:

PPU_read: function(addr: u32, val: u32, has_effect: u32): u32;

later on, in another object referring to it, JavaScript equivalent of what I'd like:

this.bus.PPU_read = this.read.bind(this);

**Comment by dcodeIO** [comment]
Can use a normal function type:

```ts
class Bus {
  PPU_read: (addr: u32, val: u32, has_effect: u32) => u32;
}
```

**Comment by raddad772** [comment]
I'm having a little trouble because I need to pass this object to objects that use it. So the classic circular definition issue.

In C, this would be solved by declaring it with a header, or a function pointer you later cast.
In JavaScript, it just doesn't care, ha.
What's the AssemblyScript way to handle this?

Ex.

class foo {
    fptr: (bar_instance: bar, a: u32) => u32;
}

class bar {
    foo_instance: foo
    d: u32
    constructor(foo_instance: foo) {
        this.foo_instance = foo_instance;
        this.foo_instance.fptr = func;
        this.d = 4;
     }
}

function func(bar_instance: bar, a: u32) => u32 {
    return a+bar.d;
}

**Comment by dcodeIO** [comment]
Almost compiles, with a few fixes:

```ts
class foo {
    fptr!: (bar_instance: bar, a: u32) => u32;
}

class bar {
    foo_instance: foo
    d: u32
    constructor(foo_instance: foo) {
        this.foo_instance = foo_instance;
        this.foo_instance.fptr = func;
        this.d = 4;
     }
}

function func(bar_instance: bar, a: u32): u32 {
    return a + bar_instance.d;
}

let f = new foo();
let b = new bar(f);
console.log(b.foo_instance.fptr(b, 2).toString());
```

**Comment by raddad772** [comment]
Excellent thanks for the help getting started! I'm liking AssemblyScript so far, especially since JSMoo extensively uses code generation, and I plan on re-targeting it.

**Comment by mariusa** [comment]
not stale
