### ISSUE TITLE
Inappropriate compile error: 'xxx | null' is not assignable to type 'xxx'

### ISSUE THREAD

**Issue by spikewoodman** [AssemblyScript/assemblyscript#2545]
Im getting a compile error which I believe is inappropriate. I've distilled the problem down to its simplest form;

```
class Child {
    sibling: Child | null;

    constructor() {
        this.sibling = null;
    }
}

class Parent {
    child: Child | null;

    constructor() {
        this.child = null;
    }

    newChild(el: Child): void {
        if (this.child === null) {
            this.child = el;
        } else {
            this.child.sibling = el;
//          ^^^^^^^^^^ ERROR TS2322: Type 'assembly/test/Child | null' is not assignable to type 'assembly/test/Child'.
        }
    }
}

const p = new Parent();
p.newChild(new Child());`
```

The RHS of the assignment is NOT a 'Child | null'; it is 'Child' only. The LHS is a 'Child | null', which should be fine. This code compiles and runs fine using the typescript compiler.

```

stevens-MacBook-Pro:xml-parser-ts spike$ npm run asbuild:test

> xml-parser-ts@1.0.0 asbuild:test
> asc assembly/test.ts --target test

ERROR TS2322: Type 'assembly/test/Child | null' is not assignable to type 'assembly/test/Child'.
    :
 20 │ this.child.sibling = el;
    │ ~~~~~~~~~~
    └─ in assembly/test.ts(20,13)

FAILURE 1 compile error(s)
stevens-MacBook-Pro:xml-parser-ts spike$ 
```

I'm using the latest version (0.22.0) of the asc compiler but I've tested it on several other major versions; v0.21, 0.20, 0.18... 0.10, all with the same results. I'm using node v16.18.0.

**Comment by dcodeIO** [comment]
Working code:

```ts
    newChild(el: Child): void {
        let child = this.child;
        if (child) {
            child.sibling = el;
        } else {
            this.child = el;
        }
    }
```

The issue originates in TypeScript being unsound when checking and narrowing properties like `if (this.child)`, since `Child#child` can, for example, be a property that immediately sets itself to `null` again, or code between the check and its first use could. Hence, AS is more strict, only narrowing non-nullable types on locals, which is why introducing one produces the desired effect.

**Comment by spikewoodman** [comment]
Thanks for your prompt reply. The message would seem a little misleading; altho it highlights the dereferenced pointer part, it specifically mentions 'assignment'. I can see how the this.child deref could become unsafe in the circumstance you describe. Will this likely be address in future or is it a feature of the compiler to spot this?

Thanks in getting me moving again

**Comment by spikewoodman** [comment]
Thanks for the help. I think the message could be improved since it mentions the assignment, although it also highlight the deref part. Is this likely something will be fixed in future or will we always need to do the extra step in this scenario?
cheers

**Comment by dcodeIO** [comment]
I guess the question is what is preferable. If we did it like TypeScript, accesses to `this.child` would have to do a null check to be sure, coming at an additional cost, and if the check indeed fails, a runtime error would crash the program. In its current form, a program potentially containing such unsoundness fails on compilation, which imo is preferable.
