### ISSUE TITLE
Compilare error on import wasi in version `0.23.1`

### ISSUE THREAD

**Issue by ludusrusso** [AssemblyScript/assemblyscript#2560]
I'm having this compilar error with latest version of assemblyscript:

```
> as-test@1.0.0 asbuild:release
> asc assembly/index.ts --target release

ERROR TS6054: File '~lib/wasi.ts' not found.
   :
 1 │ import "wasi";
   │        ~~~~~~
   └─ in assembly/index.ts(1,8)

FAILURE 1 parse error(s)
```

This is the code:

```ts
import "wasi";

console.log("hello " + add(1, 2).toString());

function add(x: i32, y: i32): i32 {
  return y + x;
}
```

And import:

```
    "as-wasi": "^0.5.1"
    "assemblyscript": "^0.23.1"
```

Note that with older version it works correcly. I've tried with this:

```
    "as-wasi": "^0.4.6",
    "assemblyscript": "^0.19.9"

```

What I'm missing??

**Comment by dcodeIO** [comment]
WASI support has moved to a separate package since 0.21, see: https://github.com/AssemblyScript/wasi-shim#usage

**Comment by mariusa** [comment]
Is `as-wasi` package still required, or the shim is a complete replacement? (wasi-shim would be good to clarify in README)

I'm unable to use `Console.readAll`

Thanks
