### ISSUE TITLE
Error when accessing array by index inside map function

### ISSUE THREAD

**Issue by rjmat97** [AssemblyScript/assemblyscript#2571]
I'm ubnable to access an external array value by index within a map function. 

Here I'm attempting to write  a python style zip function that zip two lists together. But on compilation it's throwing an error. I'm not entirely sure why this is happening since accessing arrays using indices outside the map function seem to work.

```
export function zip(list1:Array<string>, list2:Array<string>):string[][]{
  return list1.map<string[]>((i:string,d:i32):string[] => [i, list2[d]])
}
```

![image](https://user-images.githubusercontent.com/47947817/202644690-36b4ee7a-e476-4f0b-ab0b-e1b224961fcd.png)

**Comment by CountBleck** [comment]
Well, it's in the error. Closures aren't implemented (yet). That means code like this will not work:
```ts
function foo(): () => void {
    const someVariable = 123
    return (): void => {
        // You aren't allowed to access someVariable inside the callback...
        someExampleFunction(someVariable) // causes an error
    }
}
```

As a workaround, you could do something like this:
```ts
// This code should be placed outside any function in the file
let tempList: string[] = []

export function zip(list1: string[], list2: string[]): string[][] {
    tempList = list2
    return list1.map((i: string, d: i32): string[] => [i, tempList[d]])
}
```

**Comment by rjmat97** [comment]
That worked, thanks for your prompt response.
