### ISSUE TITLE
console.log: support primitives arguments, not just string

### ISSUE THREAD

**Issue by mariusa** [AssemblyScript/assemblyscript#2581]
Hi, 

What do you think about having console.log work more like in JavaScript?

eg accept any parameter types, or at least primitives:
```js
ERROR TS2322: Type 'i32' is not assignable to type '~lib/string/String'.
     :
 139 │ console.log(42)
     │             ~~
     └─ in assembly/testjs.ts(139,13)
```

and also a variable number of parameters
```console.log('abc', 43, 3.14, ['an', 'array'])```

Thanks

**Comment by kedicesur** [comment]
Also as of now `console.log` only accepts a single `string` type argument as well. So `console.log("test", "boru");` throws `ERROR TS2554: Expected 1 arguments, but got 2.`

**Comment by mariusa** [comment]
Of course, we can work around with ```console.log(`${var1} ${var2}`)```
I think this would be a lower priority vs. `Object.keys()` or `JSON.parse()` / `stringify()`

**Comment by mariusa** [comment]
not stale

**Comment by JairusSW** [comment]
This would not be hard to implement

**Comment by JairusSW** [comment]
I did something similar here: https://github.com/JairusSW/as-console
Honestly, should just slap together the `Object.keys()` and `Object.values()` api

**Comment by mariusa** [comment]
not stale
