### ISSUE TITLE
Implementing a custom TypedArray by extending `ArrayBufferView` [Question]

### ISSUE THREAD

**Issue by kedicesur** [AssemblyScript/assemblyscript#2583]
I have implemented a `BitArray` by extending the `DataView` object which works just fine. However both to lift the overhead of `DataView` and also to learn more I decided to trash `DataView` and rephrase it into a lower level by extending the `ArrayBufferView`. My original code, despite I think was just fine, kept throwing so I decided to get some influence from `./node_modules/assemblyscript/std/assembly/typedarray.ts`.  Now this version also throws exactly the same. It might be a silly mistake of mine but I just can not sort it out. Just the initial part which is sufficient to reproduce the code is as folows;

```javascript
import { ArrayBufferView } from "../node_modules/assemblyscript/std/assembly/arraybuffer";

class BitArray extends ArrayBufferView {
  [key: number]: bool;

  length : u64;

  constructor(l : u64) {
    const byteLength : i32 = <i32>(((<u64>l + 63) & 0xffffffffffffffc0) >>> 3);

    super(byteLength,alignof<u64>());
    this.length = l;
  }

  get size() : u64 {
    return <u64>this.byteLength << 3;
  }

  @operator("[]")
  private __get(index: u64): bool {
    const INNER_INDEX : u8  = index & 63,
          BLOCK_INDEX : u32 = (index >> 6) + <bool>INNER_INDEX;

    if (BLOCK_INDEX << 3 > this.byteLength) throw new RangeError("Index out of range");
    return <bool>((load<u64>(this.dataStart + <usize>BLOCK_INDEX) >>> (64 - INNER_INDEX)) & 1);
  }
}
/*
export function new_BitArray(l : f64) : usize {
  const ba = new BitArray(<u64>l);
  return ba.dataStart;
}
*/
```

At the JS side;

``` javascript
import * as AS from "../build/release.js";

const a = AS.new_BitArray(524289),
      b = AS.new_BitArray(128);

console.log(a);
console.log(b);
```

So I suppose if I don't export any functions by commenting out as above, then ASC wouldn't even compile as mentioned in the AS Book

> AssemblyScript does not compile a module linearly, but starts at the module's exports and only compiles what's reachable from them, often referred to as [tree-shaking (opens new window)](https://en.wikipedia.org/wiki/Tree_shaking). As such, dead code is always validated syntactically, but not necessarily checked for semantic correctness.

So far so good. When I do `npm run asbuild` I get this
```
ERROR AS212: Decorator '@builtin' is not valid here.
      :
 2495 │ @builtin
      │ ~~~~~~~~
      └─ in node_modules/assemblyscript/std/assembly/builtins.ts(2495,3)

ERROR AS212: Decorator '@builtin' is not valid here.
      :
 2499 │ @builtin
      │ ~~~~~~~~
      └─ in node_modules/assemblyscript/std/assembly/builtins.ts(2499,3)

FAILURE 2 compile error(s)
```

So it can't even validate this code. Yet when I uncomment the `export function new_BitArray(l : f64) : usize {...` part it throws like;

```

▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ AssertionError: assertion failed
▌     at Y.assert (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/std/portable/index.js:198:11)
▌     at Wr.compileCallExpressionBuiltin (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/compiler.ts:6143:5)
▌     at Wr.compileCallExpression (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/compiler.ts:5999:23)
▌     at Wr.compileExpression (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/compiler.ts:3367:21)
▌     at Wr.compileCallDirect (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/compiler.ts:6288:28)
▌     at Wr.compileCallExpression (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/compiler.ts:6016:21)
▌     at Wr.compileExpression (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/compiler.ts:3367:21)
▌     at zx (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/builtins.ts:3372:23)
▌     at Wr.compileCallExpressionBuiltin (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/compiler.ts:6128:49)
▌     at Wr.compileCallExpression (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/compiler.ts:5999:23)
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```
I have a few questions;

1. Obviously why is this happening?
2. When creating an `ArrayBuffer` with `changetype<ArrayBuffer>(__new(someByteLength, idof<ArrayBuffer>())` is there a way to set the internal allignment of the created array buffer to 64 bits (3)?
3. I noticed that the TypedArray class definitions are assigned with mapped types like `[key: number]: u64;` etc. Why do we still use a TypeScript type `number` here?

**Comment by dcodeIO** [comment]
Do the errors go away when changing

```diff
-import { ArrayBufferView } from "../node_modules/assemblyscript/std/assembly/arraybuffer";
+import { ArrayBufferView } from "arraybuffer";
```

so the compiler recognizes that the imported file is from stdlib and not custom?

**Comment by kedicesur** [comment]
@dcodeIO Great..! The `ERROR AS212: Decorator '@builtin' is not valid here.` error when the exported function is commented out has disappeared. It's validating. Yet when the exported is uncommented it now throws something else

```
▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ AssertionError: assertion failed
▌     at Y.assert (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/std/portable/index.js:198:11)
▌     at wi.getArrayValueType (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/program.ts:4644:5)
▌     at compileRTTI (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/builtins.ts:10421:32)
▌     at Wr.compile (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/compiler.ts:604:54)
▌     at Module.HI (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/src/index-wasm.ts:352:32)
▌     at Module.Un (/media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/cli/index.js:724:31)
▌     at async file:///media/omer/P300/Mega/Private/Projects/AS/class-test/node_modules/assemblyscript/bin/asc.js:33:22
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

I thought, perhaps i am semi implementing `BitArray` as an extension to `ArrayBufferType` so I also exported `@operator("[]=")` as well but nothing changed. Also I have a feeling like trying to code at this level might yield some hard to decypher errors to be thrown (for me) so sorry for that.

Regarding the alignment of `ArrayBuffer` I think you got it right. I mean the WASM level memory alignment. I had imagined perhaps I could do `memory.data<ArrayBuffer>([...Array.from({length: byteLength}, _ => 0)], 3): usize` :) But I suppose the whole contiguous memory of the module gets a single alignment in the first place.  Still I would perhaps prefer it to be 64 bits though.

Thank you.

**Comment by kedicesur** [comment]
Thanks. Now it's almost fine by the exception of one curious behaviour. In order to eliminate the overhead of passing an object (the `Internref` class in `release.js`) I just would like to pass a `usize` reference to the JS side. I will implement the `FinalizationRegistry` work myself to trigger GC at the AS side or perhaps directly on the exported `memory` if possible. So the plan is to pass the `BitArray`'s pointer to JS side as it's unique reference and I already know that the offset to reach it's buffer (48 bytes in this case). So when needed I can pass that reference back to AS to perform `load` and `store` operations on the correct `BitArray'`s buffer. However

```javascript
// JS SIDE
import * as AS from "../build/release.js";

const a = AS.new_BitArray(524289),
      b = AS.new_BitArray(128);

console.log(a);
console.log(b);

// AS SIDE
export function new_BitArray(l : f64) : usize {
  const ba : BitArray = new BitArray(<u64>l);
  return changetype<usize>(ba);
}
```
yields the same pointer for both as
```
35952
35952
```
when I simply throw in a console log to the exported `new_BitArray` function as 
```javascript
export function new_BitArray(l : f64) : usize {
  const ba : BitArray = new BitArray(<u64>l);
  console.log(`${changetype<usize>(ba)}`);
  return changetype<usize>(ba);
}
```
It just works fine and yields. Note that both figures are different than the previous ones.
```
37728
103376
37728
103376
```
Why does `changetype<usize>(ba).toString()` have such a global effect? What would be the correct way to pass `BitArray`'s pointer to JS side as `<usize>` or `<i32>`?

**Comment by dcodeIO** [comment]
One cause for returning the same pointer twice (after a `new`) I can imagine is if the first object becomes collected, and the second allocation reuses its space. That's what `__pin`,`__unpin` together with `FinalizationRegistry` prevent, though. The mechanism there is that upon `new`, the GC might step, so since `usize`-typed variables are not tracked by GC, these pointers must be dealt with by pinning etc.

**Comment by kedicesur** [comment]
Great... So I guess stringifying a pointer `__pin()`s it somewhere somehow. So perhaps we shouldn't log pointers to avoid repinning or unintentional pinning.
I did like

```javascript
export function new_BitArray(l : f64) : usize {
  const ba : BitArray = new BitArray(<u64>l);
  return __pin(changetype<usize>(ba));
 calc.}
```
and got two separate pointers.

Just an irrevelant sidenote: Wouldn't it be a good idea to provide a `https://www.assemblyscript.org/x` namespace for AS fans like me to publish third party AS packages to be imported from. Just like [Deno](https://deno.land/x) does.
