### ISSUE TITLE
Threading proposal

### ISSUE THREAD

**Issue by raddad772** [AssemblyScript/assemblyscript#2589]
I have an idea for threading I’d like to explore. 

The basic features are: 
- Variant of “minimal” runtime. Users would be responsible for invoking GC when appropriate
- Modify so stacks are relocatable and allocated ahead of time, allowing for multiple stacks in a sharedarraybuffer
- shared allocation and freeing behind a lock
- a thread pool-based API to give basic pthreads-like functionality, akin to what Emscripten does

I have a lot of investigation to do on the exact details, but I thought I’d post this here for discussion first.

I see many potential downsides of course:

- users may share references to memory owned by other threads. They will just have to be careful. OR, garbage collector could be multi-thread aware in its reference counting, not sure how likely this is
- A lock around allocation and deallocation can degrade performance. Users would have to take care to use preallocated space inside their performance-sensitive inner loops if they are allocating or deallocating a lot there. 
- Depending on how GC is done - per thread or globally - user may have to pause all threads to make it happen.

Regardless of these downsides, any kind of threading support would be great for AssemblyScript, and I’m potentially willing to do the work myself. We can put warnings about those right in the  documentation that describes the way to activate this runtime and enable thread support.

Hopefully in the future when wasm gc happens, code using this proposed API and runtime will be forward-compatible. 

Thoughts?

**Comment by kedicesur** [comment]
We can still implement threaded WASM code through Workers API. What would be the major gain if this gets implemented natively in AS?
