### ISSUE TITLE
How to use WebSocket with AssemblyScript ?

### ISSUE THREAD

**Issue by scorsi** [AssemblyScript/assemblyscript#259]
Hi,

I would like to know how to use WebSocket directly with AssemblyScript ?

Thank you,
scorsi,

**Comment by MaxGraey** [comment]
Currently this not easy and performant especially for listeners. After [this](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md#reference-types-for-webassembly) and [this](https://github.com/WebAssembly/host-bindings/blob/master/proposals/host-bindings/Overview.md#host-bindings-proposal-for-webassembly) it will be more fancy. So I recommend do any stuffs with WebGL, WebSockets and etc on js host side

**Comment by scorsi** [comment]
Are WebGL and WebSockets just not available in AssemblyScript or in WebAssembly in general (and so in all other wasm transpilled language as Rust and C) ?

Do you know how long this will take to be available (I'm talking about the both link you gave) ? Is it easy to dive in and do it without any knowledge ?

Thanks,

**Comment by MaxGraey** [comment]
Yes, WebAssembly cannot implicitly access to Web API and provide import mechanism for bind js environment. emscripten (C++) and Rust's wasm-bindgen provide some code generated glue code for js and wasm side. For example not any C++ library works as is for wasm target and shouldprovide some adaptation, current libraries already provide this:  https://github.com/emscripten-ports.

You could do this manually for your case like (this just as idea and not sure exactly works):
AS side
```ts
import "allocator/tlsf";
@external("env", "createWebSocket")
declare function createWebSocket(path: string): void; 
export class WebSocket {
    constructor(path: string) {
       createWebSocket(path);
    }
    
    onOpen(): void {
       // some code
    }
}
```

Node.JS side:
```js
const loader = require("@assemblyscript/loader");

let module = null;
let webSocket = null;
const imports = {
   env: {
      createWebSocket(str) {
         webSocket = new WebSocket(module.newString(str));
         webSocket.onopen = () => {
            module.WebSocket.onOpen();
         }
      }
   }
}

module = loader.instatiateBuffer(fs.readFileSync("main.wasm"), imports);
```

**Comment by scorsi** [comment]
Yeah I was thinking building something like this after your first message : create the WebSocket in the JS part and do stuff in the AssemblyScript part.

I will try this and come back with some tested and functional code. (I will also try to benchmark this with a standard JS way)

Thank you,

**Comment by scorsi** [comment]
As promised, I finished a quick WebSocket handling with AssemblyScript :)
The websocket creation is done in JS side and actually, it can only handle one websocket (generaly, we don't need more than one websocket ^^).

The code will actually run on browser without any dependencies (no need AssemblyScript loader and thus webpack or anything else). The javascript part can be lightweight if you use NodeJS and the AssemblyScript loader.

Thanks @MaxGraey !

Hope this code could help.

`index.ts`
```typescript
import "allocator/tlsf";
// @ts-ignore
export { memory };

declare namespace console {
    function log(s: string): void;
}

// @ts-ignore
@external("env", "websocketSend")
declare function websocketSend(data: string): void;

export function websocketOnOpen(): void {
    console.log("Opened");
    websocketSend("Hello server")
}

export function websocketOnClose(): void {
    console.log("Closed");
}

export function websocketOnMessage(data: string): void {
    console.log("Received: " + data);
}
```

`index.js`
```javascript
let instance = null;
let exports = null;

const hasBigInt64 = typeof BigUint64Array !== "undefined";
let mem, I8, U8, I16, U16, I32, U32, F32, F64, I64, U64;

const checkMem = () => {
    if (mem !== exports.memory.buffer) {
        mem = exports.memory.buffer;
        I8 = new Int8Array(mem);
        U8 = new Uint8Array(mem);
        I16 = new Int16Array(mem);
        U16 = new Uint16Array(mem);
        I32 = new Int32Array(mem);
        U32 = new Uint32Array(mem);
        if (hasBigInt64) {
            I64 = new BigInt64Array(mem);
            U64 = new BigUint64Array(mem);
        }
        F32 = new Float32Array(mem);
        F64 = new Float64Array(mem);
    }
};

const newString = (str) => {
    const dataLength = str.length;
    const ptr = exports["memory.allocate"](4 + (dataLength << 1));
    const dataOffset = (4 + ptr) >>> 1;
    checkMem();
    U32[ptr >>> 2] = dataLength;
    for (let i = 0; i < dataLength; ++i)
        U16[dataOffset + i] = str.charCodeAt(i);
    return ptr;
};

const freeString = (ptr) => {
    exports["memory.free"](ptr);
};

const getString = (ptr) => {
    checkMem();
    const dataLength = U32[ptr >>> 2];
    let dataOffset = (ptr + 4) >>> 1;
    let dataRemain = dataLength;
    const parts = [];
    const chunkSize = 1024;
    while (dataRemain > chunkSize) {
        let last = U16[dataOffset + chunkSize - 1];
        let size = last >= 0xD800 && last < 0xDC00 ? chunkSize - 1 : chunkSize;
        let part = U16.subarray(dataOffset, dataOffset += size);
        parts.push(String.fromCharCode.apply(String, part));
        dataRemain -= size;
    }
    return parts.join("") + String.fromCharCode.apply(String, U16.subarray(dataOffset, dataOffset + dataRemain));
};

let websocket = null;

if ('WebAssembly' in window) {
    fetch('build/optimized.wasm')
        .then(response => response.arrayBuffer())
        .then(buffer => WebAssembly.instantiate(buffer, {
            console: {
                log(strPtr) {
                    console.log(getString(strPtr));
                }
            },
            env: {
                websocketSend(strPtr) {
                    websocket.send(getString(strPtr));
                },
                abort(mesg, file, line, colm) {
                    mesg = mem ? getString(mesg) : "";
                    file = mem ? getString(file) : "<instantiate>";
                    throw Error("abort: " + mesg + " at " + file + ":" + line + ":" + colm);
                }
            }
        }))
        .then(obj => {
            instance = obj.instance;
            exports = instance.exports;
            console.log(obj);

            websocket = new WebSocket("ws://localhost:8080");
            websocket.onopen = (event) => {
                instance.exports.websocketOnOpen();
            };
            websocket.onclose = (event) => {
                instance.exports.websocketOnClose();
            };
            websocket.onmessage = (event) => {
                let data = newString(event.data);
                instance.exports.websocketOnMessage(data);
                freeString(data);
            };
        })
        .catch(console.error);
} else {
    alert("Your browser doesn't support Web Assembly. You may need " +
        "to enable it in your browser's flags.");
}
```

**Comment by whaqzhzd** [comment]
Hello, the good news is that the interoperability between JS and WASM is getting faster and faster. There are reasons to believe that it will be better
https://hacks.mozilla.org/2018/10/calls-between-javascript-and-webassembly-are-finally-fast-%F0%9F%8E%89/

**Comment by VivianoRiccardo** [comment]
Is possible using no blocking socket. I m involved in a wasm project and i need websocket inside wasm script so i have implenented it https://github.com/VivianoRiccardo/WebSpark/tree/master/tests/ws_over_wasm
