### ISSUE TITLE
`Number.toString()` and Little Endianness confusion.

### ISSUE THREAD

**Issue by kedicesur** [AssemblyScript/assemblyscript#2592]
The value stored as `u8` at the head of `.dataStart` gets stringified as the 8th byte when loaded as `<u64>` from the head of the `.dataStart`. In other words when `bswap` is employed it gets stringified correctly as shown below;

```javascript
export function testString(ptr: usize) : void {
  const VIEW : View = changetype<View>(ptr);
  memory.fill(VIEW.dataStart, u8.MIN_VALUE, VIEW.byteLength);
  store<u8>(VIEW.dataStart,1);
  console.log(load<u64>(VIEW.dataStart).toString(2).padStart(64,"0"));        // 0000000000000000000000000000000000000000000000000000000000000001
  console.log(bswap(load<u64>(VIEW.dataStart)).toString(2).padStart(64,"0")); // 0000000100000000000000000000000000000000000000000000000000000000 <- Correct
}
```
Is this a normal behaviour?

**Comment by CountBleck** [comment]
I don't quite understand what you mean. You're storing `1` into the first byte of the array. Since you're reading a `u64` and Wasm is always little-endian, the first byte is the least significant byte as far as I know. Therefore, that looks correct. `bswap` reinterprets the number as big-endian, and that sample output looks correct as well (the top 8 bits show "1").

**Comment by kedicesur** [comment]
@CountBleck Yes I agree since x64 architecture should be little endian. What troubled me was, if I am not mistaken the [`memory.compare`](https://www.assemblyscript.org/stdlib/globals.html?#memory) function seemingly compares a series of bytes as if they carry big endian stored values. Just wanted to make sure.

> `function memory.compare(lhs: usize, rhs: usize, n: usize): i32`
> Compares the first `n` bytes of `left` and `right` and returns a value that indicates their relationship:
> 
> - Negative value if the first differing byte in `lhs` is less than the corresponding byte in `rhs`.
> - Positive value if the first differing byte in `lhs` is greater than the corresponding byte in `rhs`.
> - Zero​ if all `n` bytes of `lhs` and `rhs` are equal.

**Comment by dcodeIO** [comment]
Regarding `memory.compare`: This particular function operates on individual `u8`s from left to right, so there endianness isn't a factor since endianness is only relevant for multi-byte values, say `u/i16` and larger.

**Comment by kedicesur** [comment]
@dcodeIO Right. I was hoping to be able use it to compare multi-byte values (`n = 2, 4, 8 or even 16`) at a lower level even without loading. Had it been scanning from right to left or had a counterpart like `memory.compareRight` perhaps it could have been more useful. Thanks anyways.

**Comment by JairusSW** [comment]
Couldn't it also use 64 bit comparisions to compare four bytes at a time?
