### ISSUE TITLE
Get compile error in 'for' loop to iterate a Interface map type 

### ISSUE THREAD

**Issue by DeanHH** [AssemblyScript/assemblyscript#2606]
```typescript
export interface StringMap<T> {
	[key: string]: T;
}
sortPathConstraintAttachment1 (skin: Skin, slotIndex: number, slotBone: Bone) : void {
	let attachments:StringMap<Attachment> = skin.attachments[slotIndex];
	if (!attachments) return;
	for (let key in attachments) {
		this.sortPathConstraintAttachmentWith(attachments[key], slotBone);
	}
}
```
302 │ for (let key in attachments) {
     │             ^
     └─ in SpineCore/Skeleton.ts(302,15)

It seems I have to change to get keys array, and then iterate it to make it pass compiling.
```typescript
sortPathConstraintAttachment (skin: Skin, slotIndex: number, slotBone: Bone) : void {
	let attachments:StringMap<Attachment> = skin.attachments[slotIndex];
	if (!attachments) return;
	let keys:Array<string> = attachments.keys;
	for (let i = 0, n = keys.length; i < n; i++){
		this.sortPathConstraintAttachmentWith(attachments[keys[i]], slotBone);
	}
}
```
Do we have any better way to avoid compile error?

**Comment by CountBleck** [comment]
As far as I know, no. Iterators are not supported yet.

On a sidenote, you could probably wrap `skin.attachments[slotIndex]` and `attachments[keys[i]]` in `unchecked()`. Also, if there is a `.values` property/getter, you could use that and avoid the `keys[i]` altogether.

**Comment by DeanHH** [comment]
> Contributor



> As far as I know, no. Iterators are not supported yet.
> 
> On a sidenote, you could probably wrap `skin.attachments[slotIndex]` and `attachments[keys[i]]` in `unchecked()`. Also, if there is a `.values` property/getter, you could use that and avoid `attachments[...]` altogether.

Thanks, hopefully there will be any plan to support this feature.
