### ISSUE TITLE
"Gc is not a function" TypeError on 0.26.2

### ISSUE THREAD

**Issue by atesgoral** [AssemblyScript/assemblyscript#2617]
Getting an error upon importing the latest `asc` in the browser:

```
Uncaught TypeError: Gc is not a function
    at module.ts:77:37
    at module.ts:86:66
```

Following the in-browser compilation example, with the following importmap:

```html
  <script type="importmap">
  {
    "imports": {
      "binaryen": "https://cdn.jsdelivr.net/npm/binaryen@111.0.0/index.js",
      "long": "https://cdn.jsdelivr.net/npm/long@5.2.1/index.js",
      "assemblyscript": "https://cdn.jsdelivr.net/npm/assemblyscript@0.26.2/dist/assemblyscript.js",
      "assemblyscript/asc": "https://cdn.jsdelivr.net/npm/assemblyscript@0.26.2/dist/asc.js"
    }
  }
  </script>
```

Blows up on this line (not even compiling or instantiating):

```js
 import asc from "assemblyscript/asc";
```

0.26.1 is working fine. This issue started on 0.26.1.

Browser: Chrome Version 108.0.5359.124 (Official Build) (x86_64)

**Comment by dcodeIO** [comment]
The import map for v0.26.2 should match [this one](https://cdn.jsdelivr.net/npm/assemblyscript@0.26.2/dist/importmap.json):

```json
{
  "imports": {
    "assemblyscript": "https://cdn.jsdelivr.net/npm/assemblyscript@0.26.2/dist/assemblyscript.js",
    "assemblyscript/asc": "https://cdn.jsdelivr.net/npm/assemblyscript@0.26.2/dist/asc.js",
    "binaryen": "https://cdn.jsdelivr.net/npm/binaryen@111.0.0-nightly.20230111/index.js",
    "long": "https://cdn.jsdelivr.net/npm/long@5.2.0/index.js"
  }
}
```

When comparing with the above, the Binaryen version is off (wants `111.0.0-nightly.20230111` but only got `111.0.0` which is older).

**Comment by CountBleck** [comment]
What happens if you change the binaryen version to `111.0.0-nightly.20230111`?

**Comment by atesgoral** [comment]
That was it! It works with the above import map.
