### ISSUE TITLE
Operator overload is not supported anymore in some cases

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#2618]
```ts
class A {
    @operator("==")
    eq(other: this | null): bool {
        return true;
    }
}
class B extends A {
    @operator("==")
    eq(other: this | null): bool {
        return false;
    }
}
```
It works in old code(0.19).
But now the compiler report error about it directly.

**Comment by dcodeIO** [comment]
The problem isn't with operator overloads, but with `B` extending `A` and overriding `eq` with an unsound type, namely taking a `B` instead of an `A` as of the overridden method. Might not be obvious if there are just two classes, but as soon as there is another

```ts
class C extends A {
    @operator("==")
    eq(other: this | null): bool {
        return false;
    }
}
```

and one does

```ts
let c = new C();
let a = <A>c; // ok since C extends A
a.eq(new B()); // ok since B extends A
```

one would virtually call `c.eq(other: C)` with a `B`, which is invalid. The fix is to change the type of `B#eq` to accept an `A` as well.

**Comment by yjhmelody** [comment]
Ok, I found the compiler only check `operator overload` when in actual use the type instance.

**Comment by yjhmelody** [comment]
What do you mean about `unsound type`. 

And ..  Add your code won't make this code compiling pass, because my part still not work.

**Comment by dcodeIO** [comment]
The working version is

```ts
class A {
    @operator("==")
    eq(other: A | null): bool {
        return true;
    }
}
class B extends A {
    @operator("==")
    eq(other: A | null): bool {
        return false;
    }
}
```

which guarantees soundness by not employing covariance on `other` in `eq`.

**Comment by yjhmelody** [comment]
But I want to compare B with B. I do not care about comparing B with A.

**Comment by dcodeIO** [comment]
What about...?

```ts
class B extends A {
    @operator("==")
    eq(other: A | null): bool {
        if (other instanceof B) {
          // compare B with B
        } else {
          return false;
        }
    }
}
```

**Comment by HerrCai0907** [comment]
And I am also interesting about this operator overload mechanism and it is the test case

```ts
class A {
  @operator("==")
  eq1(other: this | null): bool {
    return true;
  }
}
class B extends A {
  @operator("==")
  eq2(other: this | null): bool {
    return false;
  }
}


let a = new A();
let b = new B();
trace(`a == a : ${a == a}`);
trace(`a == b : ${a == b}`);
// trace(`b == a : ${b == a}`); compile error: Type 'assembly/index/A' is not assignable to type 'assembly/index/B | null'.
trace(`b == b : ${b == b}`);
```

The result is:
a == a : true     // using eq1
a == b : true     // using eq1
b == b : false   // using eq2

So the `t1 == t2` operator actually is same as `t1.eq(t2)` and it will not inherit parent operator overload

**Comment by yjhmelody** [comment]
@HerrCai0907 Very awkward, doesn't support a certain level of function overload(even for constructor).
It's not easy to know if these eq variants is static or dynamic, since there is no syntax to distinguish between them. But I think they are dynamic.

**Comment by yjhmelody** [comment]
Ping
