### ISSUE TITLE
The best practice to compare a value  whose type is`T| null` with `null`?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#2619]
I found some features break changes about `null` comparing.

**Comment by dcodeIO** [comment]
Can you provide an example of what you are trying to accomplish, respectively that shows the issue?

**Comment by yjhmelody** [comment]
@dcodeIO  Inconsistency between if statement and comparison operator for null values.

```ts
// works
export class Option<T>
    constructor(protected _val: T | null = null) {}

    @inline
    get isSome(): bool {
        if (this._val) {
            return true;
        } else {
            return false;
        }
    }

    @inline
    get isNone(): bool {
        if (this._val) {
            return false;
        } else {
            return true;
        }
    }
}

// not works anymore in new version
export class Option<T>
    constructor(protected _val: T | null = null) {}

      @inline
    get isSome(): bool {
        return this._val != null
    }

    @inline
    get isNone(): bool {
      return this._val == null
    }
}
```

I thought the condition expression `this._val` is a syntax sugar of `this._val != null` when this expression return a nullable value in `if` condition. But I was wrong. I need to know its strict semanitc definition.

**Comment by dcodeIO** [comment]
What exactly isn't working in the second case? What's the type of `T` there?

**Comment by yjhmelody** [comment]
Type 'assembly/box/Box<~lib/string/String> | null' is not assignable to type 'assembly/box/Box<~lib/string/String>'.
    :
 27 │ return this._val != null
    │        ~~~~~~~~~
    └─ in assembly/reference/option.ts(27,16)

**Comment by dcodeIO** [comment]
Tried reproducing this by making an `Option<string>` and an `Option<string | null>`, but I am not seeing this diagnostic. How would I go about reproducing the issue?

**Comment by yjhmelody** [comment]
For `Option`, `Option<string>` and `Option<string | null>` are differnt type.

**Comment by dcodeIO** [comment]
I am unfortunately unable to reproduce the issue. Can you provide a code snippet that, say [when run here](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKY2xhc3MgT3B0aW9uPFQ+IHsKICBjb25zdHJ1Y3Rvcihwcm90ZWN0ZWQgX3ZhbDogVCB8IG51bGwgPSBudWxsKSB7fQoKICBAaW5saW5lCiAgZ2V0IGlzU29tZSgpOiBib29sIHsKICAgIHJldHVybiB0aGlzLl92YWwgIT0gbnVsbAogIH0KCiAgQGlubGluZQogIGdldCBpc05vbmUoKTogYm9vbCB7CiAgICByZXR1cm4gdGhpcy5fdmFsID09IG51bGwKICB9Cn0KbGV0IG8gPSBuZXcgT3B0aW9uPHN0cmluZz4oImEiKTsKby5pc1NvbWU7Cm8uaXNOb25lOwojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0IHR5cGU9Im1vZHVsZSI+CmNvbnN0IGV4cG9ydHMgPSBhd2FpdCBpbnN0YW50aWF0ZShhd2FpdCBjb21waWxlKCksIHsgLyogaW1wb3J0cyAqLyB9KQpjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKZm9yIChsZXQgaSA9IDA7IGkgPD0gMTA7ICsraSkgewogIG91dHB1dC52YWx1ZSArPSBgZmliKCR7aX0pID0gJHtleHBvcnRzLmZpYihpKX1cbmAKfQo8L3NjcmlwdD4=), produces the diagnostic?

**Comment by yjhmelody** [comment]
Ok
