### ISSUE TITLE
Question: How to get the the generic type of Array?

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#262]
The requirement is to create obj by generic type.  
```typescript
class A { }
function createObj<T>(): T {
    var isArr = isArray<T>();
    if (isArr) {
        let arr = {} as T;
        // Is there a way to create an instance of A and push the instance to the `arr`
       return arr;
    }
    // other logic
}
createObj<Array<A>>();
```

**Comment by dcodeIO** [comment]
`<T>{]` should work to create an instance using the default constructor (the one without arguments). Doesn't it?

**Comment by LiaoPeng** [comment]
@dcodeIO  Thanks for you reply.
The above code, the generic `T` represented `Array<A>`.  Is there a way to create an instance of `A` in function `createObj<T>():T`.  I want to create an array with some elements.

**Comment by dcodeIO** [comment]
At this point I think that there must be a constructor with zero arguments for it to work, that is until [this TODO](https://github.com/AssemblyScript/assemblyscript/blob/master/src/compiler.ts#L6526-L6527) has been addressed.

**Comment by LiaoPeng** [comment]
@dcodeIO Thanks for you reply.
// TODO: if the constructor requires parameters, check whether these are given as part of the object literal and use them to call the ctor while not generating a store.

1. If the constructor requires parameters, the `{}` not providers parameters.  Not generating a store, so creating an instance without using constructor.  It maybe lead to create an unsafe instance if the constructor has some restrictions. eg:
```typescript
class A{
      year: i32;
      constructor(a: i32) {
              if ( a < 1900) {
                   this.year = 1900;
              }
             this.year = a;
      }
}
In that case calling the ctor with default value maybe a choice.

**Comment by MaxGraey** [comment]
@dcodeIO Could we close this for now?

**Comment by dcodeIO** [comment]
Yeah, seems this is pretty similar to https://github.com/AssemblyScript/assemblyscript/issues/262, which is our tracking issue now.

**Comment by trusktr** [comment]
#262 is this very issue. Did you mean #258?

**Comment by trusktr** [comment]
Just my sentiment here, but stuff like `isArray<T>()` is a bit awkward and straying away from the TypeScript language. My IDE treats it as an error, and plus isn't portable.

Is there another way to allow the same thing in AS, while being compatible with TypeScript?

**Comment by MaxGraey** [comment]
`isArray(expr)` is portable, `isArray<T>()` - isn't. Also you could use `Array.isArray(arr)`
