### ISSUE TITLE
Transform: renaming a function

### ISSUE THREAD

**Issue by sydhds** [AssemblyScript/assemblyscript#2623]
I'm unable to rename a function in a transform with the following code:

```javascript
import * as assemblyscript from "assemblyscript";
import { Transform } from "assemblyscript/transform";
import binaryen from "binaryen";

class MyTransform3 extends Transform {
  afterParse(parser) {
    this.log("[mytransform3.js] afterParse called, baseDir = " + this.baseDir);
  }
  afterInitialize(program) {
    this.log("[mytransform3.js] afterInitialize called");

    var elements = program.elementsByName;

    let f = program.elementsByName.get("assembly/test/transform_2/myadd");
    this.log("f:");
    this.log("is f undefined?: ", f === undefined);
    this.log(f.name, " - ", f.internalName);
    // f.unset(assemblyscript.CommonFlags.EXPORT);

    f.name = "myadd42";
    f.internalName = "assembly/test/transform_2/myadd42";
    // Object.assign(program.elementsByName, {"assembly/test/transform_1/myadd42": f});
    program.elementsByName.set("assembly/test/transform_2/myadd42", f);

    let f2 = program.elementsByName.get("assembly/test/transform_2/myadd42");
    this.log("f2:");
    this.log("is f2 undefined?: ", f2 === undefined);
    this.log(f2.name, " - ", f2.internalName);
  }
  afterCompile(asModule) {
    this.log("[mytransform3.js] afterCompile called");
  }
}

export default MyTransform3;
```

Is this a bug or I'm doing something wrong?

**Comment by dcodeIO** [comment]
There are multiple lookup tables that would need to be updated. One is `elementsByName`, which contains mappings of the internal names to elements, but there are other ways to get to an element, for example by searching for `myadd` relative to the file `transform_2.ts`. A possible starting point could be to look at the element's `.parent` property, and update the parent-to-child mapping there as well. Note, though, that relationships can become complex once there are resolved instances, so there might be more to do.

**Comment by sydhds** [comment]
Thanks I've managed to rename a function successfully! 

I'm also trying (after the rename) to make it non exportable with the following code:

```javascript

[...]    
let f = program.elementsByName.get(key);
[...]
f.unset(assemblyscript.CommonFlags.EXPORT);
```

but it does not work; Is this the correct way to do this?


 

> There are multiple lookup tables that would need to be updated. One is `elementsByName`, which contains mappings of the internal names to elements, but there are other ways to get to an element, for example by searching for `myadd` relative to the file `transform_2.ts`. A possible starting point could be to look at the element's `.parent` property, and update the parent-to-child mapping there as well. Note, though, that relationships can become complex once there are resolved instances, so there might be more to do.

**Comment by dcodeIO** [comment]
This one is similar I believe, with the collection of interest likely being `Program#moduleExports`. When the program is initialized, `moduleExports` has already been populated, so in order to suppress the export, it has to be removed there. Another mapping to look at might be `File#exports`.

**Comment by sydhds** [comment]
Thanks for the info. I'm closing the issue now!
