### ISSUE TITLE
else if does not compile

### ISSUE THREAD

**Issue by nippur72** [AssemblyScript/assemblyscript#264]
I have this vali TS code:
```ts
      if (reg_code === 0)
         b = op_array[bit_number]( b);
      else if (reg_code === 1)
         c = op_array[bit_number]( c);
      else if (reg_code === 2)
         d = op_array[bit_number]( d);
      else if (reg_code === 3)
         e = op_array[bit_number]( e);
      else if (reg_code === 4)
```
but it gives me
```
ERROR TS1109: Expression expected.

       else if (reg_code === 1)
```
Is that expected behaviour?

**Comment by dcodeIO** [comment]
I think that's due to calling an array element as a function at `op_array[bit_number](b);`. Duplicate of: https://github.com/AssemblyScript/assemblyscript/issues/257

**Comment by nippur72** [comment]
sorry for the duplicate, it's hard to search when you don't know how to call it :-)
