### ISSUE TITLE
When using `wasi-shim`, `asc` generates invalid JavaScript

### ISSUE THREAD

**Issue by ChrisWhealy** [AssemblyScript/assemblyscript#2644]
### Bug description

I'm using [`as-wasi`](https://github.com/jedisct1/as-wasi) with [`wasi-shim`](https://github.com/AssemblyScript/wasi-shim) to create some server-side AssemblyScript code that will read a file from the local file system.

However, after discovering that some adjustments are needed before this demo will work (see [this StackOverflow question](https://stackoverflow.com/questions/75362866/server-side-assemblyscript-how-to-read-a-file) for details), I got the `.wasm` module to compile and it can be run using `wasmtime`.

However, it cannot be run via NodeJS due to the fact that the JavaScript code generated by `asc` in files `./build/debug.js` and `./build/release.js` contains an invalid  import statement:

```js
import * as __import0 from "wasi_snapshot_preview1";
```

```bash
Uncaught Error Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'wasi_snapshot_preview1' imported from /Users/chris/Developer/WebAssembly/file_reader/build/debug.js
```

Now, this statement need only be:

```js
import { WASI } from "wasi"
```

However, this `WASI` instance needs to be used in a way that is quite different from that seen in the generated coding.

E.G. a new WASI instance must be created, then the `start()` function called passing in the WASM module instance

### Steps to reproduce

1. Get the (slightly out-of-date) WASI demo shown on the [WASM by Example](https://wasmbyexample.dev/examples/wasi-hello-world/wasi-hello-world.assemblyscript.en-us.html) website work by applying the answers provided to the question [using AssemblyScript to read a file](https://stackoverflow.com/questions/75362866/server-side-assemblyscript-how-to-read-a-file)
1. This program can be run successfully using `wasmtime` or `wasmer`
1. The JavaScript code generated by `asc` (in `./build/debug.js` for instance) cannot be run using Node via `./tests/index.js` because of the invalid import statement in the generated code.

This generated code can be hacked manually to produce something that works, but this is a redundant exercise because not only does it involve extensive modifications to the code, but these changes will be overwritten the next time `asc` is run.

### AssemblyScript version

v0.27.0

**Comment by dcodeIO** [comment]
This is not necessarily a bug, rather an unfortunate ambiguity:

* In a Non-Web VM, WASI is simply there.
* In a browser, WASI is absent.
* Under Node.js, it is neither, but is a built-in module one imports to either
  * ...instantiate the module from JS, but then one doesn't need JS bindings
  * ...instantiate any other WASI module from within AS code via JS bindings <- current expectation

The workaround is not necessarily obvious but simple: Do not use JS bindings when targeting WASI, but write a few lines of code to instantiate the (now) WASI-only module, that doesn't need bindings, using Node's `wasi` module.

**Comment by ChrisWhealy** [comment]
Fair enough &mdash; but if `asc` generates JavaScript that is designed to be run using `node tests`, should this coding not be useable without the need for a workaround?

**Comment by ChrisWhealy** [comment]
Absolutely!  The more explanation that can be provided, the better &mdash; especially in situations like this where an expectation exists that it should "just work".

As a technical author myself, may I suggest this documentation should include two vital elements:

1. It must be written from the perspective of a non-expert.
   The age-old problem with technical documentation is that it is written by experts for experts - which makes it both perfectly correct, and at the same time, of little or no use to a non-expert.  This is because experts so easily forget how hard they had to work in the past to gain their expertise, and consequently when they write, they take for granted details or concepts that are quite opaque to most non-experts
1. Illustrate the technology using worked examples that are ***actually useful***
   By this I mean not simply adding up two numbers or writing `"Hello world"` to standard out, but something that could serve as a template for a real-life application, such as opening a text file, processing its contents, then writing an output file.

At the end of the day, generating WASM code using AS is ***so*** much easier than writing directly in WebAssembly Text, and therefore AS is a natural solution for generating lightweight WASM modules.  However, the current awkwardness of performing a basic task like integrating with the host environment or OS unfortunately creates a major obstacle to the widespread adoption of AS as a general purpose solution.

I know that the WASM-scism is in danger of polarising the community, and I don't want to be distracted with any type of he-said-you-said-she-said-they-said squabbles.

Please pardon my frustration, but we just need a solution that works...

Here endeth the lesson   😃
