### ISSUE TITLE
nonnull type could not work for some cases?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#2645]
### Bug description

```ts
type Baz = string | null;

function foo<T>(v: nonnull<T>): T {
    return v;
}

let s1: Baz = "";
expect(foo<Baz>(s1)).toBe(s1);
```

I want to prevent user pass a nullable type. But compiler do not report any error. 

### Steps to reproduce

Use the above code

### AssemblyScript version

0.25

**Comment by dcodeIO** [comment]
I am getting the desired error there when running the [code snippet in recent AS](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKdHlwZSBCYXogPSBzdHJpbmcgfCBudWxsOwoKZnVuY3Rpb24gZm9vPFQ+KHY6IG5vbm51bGw8VD4pOiBUIHsKICAgIHJldHVybiB2Owp9CgpsZXQgczE6IEJheiA9ICIiOwpmb288QmF6PihzMSk7CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQgdHlwZT0ibW9kdWxlIj4KY29uc3QgZXhwb3J0cyA9IGF3YWl0IGluc3RhbnRpYXRlKGF3YWl0IGNvbXBpbGUoKSwgeyAvKiBpbXBvcnRzICovIH0pCmNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQpmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgKytpKSB7CiAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAp9Cjwvc2NyaXB0Pg==). Might not have been part of v0.25, yet.

**Comment by yjhmelody** [comment]
Ok.
For 0.19, compiler panic.
For 0.25 it will not report error.
For 0.27, nonull will works.
