### ISSUE TITLE
Cannot find global type 'CallableFunction'

### ISSUE THREAD

**Issue by ckaznocha** [AssemblyScript/assemblyscript#2646]
### Bug description

Opening an assemblyscript project with vscode results in the error "Cannot find global type 'CallableFunction'" from the `tsconfig.json`. It looks like this is caused by the `noLib` being true and no global definition for `CallableFunction` in the assemblyscript d.ts files. This only started for me after I updated to the latest version of vscode which I'm under the impression comes with a bundled version of typescript.

I found some folks on so are having the same problem with no resolution but I wasn't able to find an issue here so creating one.

https://stackoverflow.com/questions/74438208/cannot-find-global-type-callablefunction-error-in-tsconfig-json-file

### Steps to reproduce

Open an assemblyscript project with vscode v1.75.0 then edit any ts file.

### AssemblyScript version

v0.26.7

**Comment by dcodeIO** [comment]
Seems we'll need to declare a mock `CallableFunction` in [std/index.d.ts](https://github.com/AssemblyScript/assemblyscript/blob/main/std/assembly/index.d.ts), where the `noLib` environment is declared, so TS tooling can pick it up. Might be as simple as copy-pasting the interface TS uses.

**Comment by ckaznocha** [comment]
Thanks for posting this workaround @neodon! I tried it in a project and can confirm it suppresses the new errors from the `tsconfig.json`.
