### ISSUE TITLE
v0.27.0 + `wasi-shim` generates invalid wasm `section 12`

### ISSUE THREAD

**Issue by roaminro** [AssemblyScript/assemblyscript#2648]
### Bug description

I am trying to use the `wasi-shim` with AS v0.27.0 and I'm running into a weird issue. (I'm trying to migrate a project that was written in v0.19.23)

The project I'm working on uses the Fizzy WASM VM, and when I load a WASM file compiled with 0.19.23 (and WASI) it works just fine, however, if I compile the same code using 0.27.0 and the wasi-shim, I get this error from the VM: `unknown section encountered 12` when it tries to parse the WASM bytecode.

Looking at the Fizzy VM code, it looks like a section code 12 is not supported [Fizzy Supported Codes](https://github.com/wasmx/fizzy/blob/5b99b52e77024376dada16091ddbad1215ab9608/lib/fizzy/types.hpp#L376), but I have no idea of what that means...

Would you happen to know what could be causing this `section code 12` to be generated in the WASM bytecode?

### Steps to reproduce

Compile the following code with AS v0.27.0 and `wasi-shim`:

```ts
export namespace env {
  @external("env", "invoke_system_call")
    export declare function invokeSystemCall(sid: u32, ret_ptr: u32, ret_len: u32, arg_ptr: u32, arg_len: u32, ret_bytes: u32): i32;
}

const a = new Uint8Array(1024)

env.invokeSystemCall(1, a.dataStart as u32, 1024, a.dataStart as u32, a.byteLength, a.dataStart as u32);
```

Load it into the Fizzy VM (which I guess you won't be able to do...)

### AssemblyScript version

v0.27.0

**Comment by dcodeIO** [comment]
Section 12 would be the DataCount section. Does it work when compiling with `--disable bulk-memory`?

**Comment by roaminro** [comment]
Thanks for the quick answer!!!

Using `--disable bulk-memory` did the trick indeed! 

I guess the FizzyVM doesn't support that feature yet... Thanks again for the quick turn qround with that issue!
