### ISSUE TITLE
Index signature is missing in type ... & Issues with dynamic keys

### ISSUE THREAD

**Issue by acceleratemedia** [AssemblyScript/assemblyscript#2650]
### Bug description

Forgive me if this isn't a bug; if it's not and I simply don't know how to use to assemblyscript I appreciate any guidance that can be offered.

I've been having issues writing scripts where I am assigning dynamic keys to objects. I'm getting errors saying that an index signature is missing; but form what I understand I have properly defined an index signature. What I'm sharing here is the most easy example I've come across (of many) to demonstrate this issue.

In this example, the code is for a football draft helpe. In the draft, there are teams (represented in the code by the MvpBoardTeam class). Each team has available roster spots to fill. These are kept track of throughout the draft by the TeamFillNumber class. Each team's roster spots fill numbers are aggregated into a class that holds all teams' fill numbers in the LeagueFillNumbers class indexed by the ID of the team.

At the start of code execution, we instantiate the league fill numbers for the draft. This happens by feeding in the teams to the LeagueFillNumber class, and it creates a new set of TeamFillNumbers for each team and then assigns it as a property keyed by the team's ID.

When I try to compile this, I receive the following error:

`ERROR TS2329: Index signature is missing in type 'assembly/index/LeagueFillNumbers'.`

I've had this same issue and error at least 3 other times when trying to create a dynamic property on an object. I've looked up index signatures in TypeScript and I believe I am using them properly but I may be misunderstanding something.

### Steps to reproduce

Install a new project using the instructions here ( https://www.assemblyscript.org/getting-started.html#setting-up-a-new-project ). Update the index.ts file with the following:

```typescript
// The entry file of your WebAssembly module.
export function add(a: i32, b: i32): i32 {
  const leagueFillNumbers = new LeagueFillNumbers([
    {
      id: 1,
      mvp_board_scoring_id: 1,
      name: 'test1',
      draft_position: 0,
      user_owned: true,
      sync_team_id: 'a',
      create_time:  '0000-00-00 00:00:00',
      update_time:  '0000-00-00 00:00:00'
    },
    {
      id: 2,
      mvp_board_scoring_id: 1,
      name: 'test2',
      draft_position: 0,
      user_owned: false,
      sync_team_id: 'b',
      create_time:  '0000-00-00 00:00:00',
      update_time:  '0000-00-00 00:00:00'
    }
  ]);

  return a + b;
}

class LeagueFillNumbers {
    [key: i32]: TeamFillNumbers
    constructor(
        mvpBoardTeams: Array<MvpBoardTeam>
    ){
        for(let i = 0; i < mvpBoardTeams.length; i++){
            this[mvpBoardTeams[i].id] = new TeamFillNumbers();
        }
    }
}

class TeamFillNumbers {
    [key: string]: i32
    constructor(){
        const fantasyPositions: Array<string> = PositionHelper.getFantasyPositionList();
        for(let i = 0; i < fantasyPositions.length; i++){
            this[fantasyPositions[i]] = 0;
        }
    }
}

class MvpBoardTeam {
    id: i32
    mvp_board_scoring_id: i32
    name: string
    draft_position: i32
    user_owned: bool
    sync_team_id: string
    create_time:  string
    update_time: string
}
```
On the command line run `npm run asbuild`. The following output displays:

```

> test@1.0.0 asbuild
> npm run asbuild:debug && npm run asbuild:release


> test@1.0.0 asbuild:debug
> asc assembly/index.ts --target debug

ERROR TS2329: Index signature is missing in type 'assembly/index/LeagueFillNumbers'.
    :
 41 │ this[mvpBoardTeams[i].id] = new TeamFillNumbers();
    │ ~~~~
    └─ in assembly/index.ts(41,13)

FAILURE 1 compile error(s)
```

### AssemblyScript version

0.27.0

**Comment by acceleratemedia** [comment]
I created a [topic on StackOverflow](https://stackoverflow.com/questions/75390154/assemblyscript-compilation-error-ts2329-index-signature-is-missing-in-type/75424374#75424374) for this and did get one response so far but it didn't make it clear whether I was doing something wrong or the issue was with Typescript / Assemblyscript.

**Comment by CountBleck** [comment]
You should be using a Map. AS doesn't suppprt dynamic keys, and you shouldn't do this in TS either honestly.

**Comment by acceleratemedia** [comment]
Thanks for this insight @CountBleck. For my above instance, I understand that I should replace both of the classes for TeamFillNumbers and LeagueFillNumbers with maps using the positions and team ids as key, respectively.

Since I'm new to AS and limited in TS I'm curious is this 'common knowledge' or something that's documented somewhere? I just didn't come across it in my searching, and the TS error that was being thrown definitely had me going down the wrong path.

Now that you mention that dynamic keys are not supported, I have a follow up question if you are willing to share more of your insight. The original code I was trying to run which resulted in my error `Index signature is missing in type ...` was in a dynamic sorting function. In my StackOverflow topic linked above, the example is:

```typescript
const sortPlayersByField = function(
    players: Array<PlayerData>,
    field: String = 'fantasy_points',
    secondaryField: String = ''
): Array<PlayerData>{
    const sortFunc = function(
        a: PlayerData,
        b: PlayerData
    ): i32{
        if(!a[field] && !b[field]){ return 0; }
        if(!a[field]){ return 1; }
        if(!b[field]){ return -1; }
        // --- And so on
    }
    players.sort(sortFunc)
    return players;
}
```

I now see that I could use a Map to do this and do `a.get(key)` and `b.get(key)` and compare those values, rather than trying to use a dynamic key on the PlayerData object. But, PlayerData really doesn't have dynamic keys. It is a good example of an object whose definition will be consistent. 

Say I have functionality where I'd like a user to be able to sort by points, games, or other properties that may be on that PlayerData object. Based on our discussion, I see one of two ways to do it:

(1) Change PlayerData to a Map. This doesn't seem logically like the best approach though since it seems strictly defining that object makes sense. That class is used in type definitions in many places in the code, and the PlayerData objects are frequently accessed with the `player.property` notation. Changing PlayerData to a map "feels wrong" compared to how I've got it set up now.

(2) Create a very complex sort function that checks the sort `field` and writes a conditional for each property. Something like:
```typescript
if(field == 'sortFieldOne'){
    if(a.sortFieldOne > b.sortFieldOne) { return -1}
    // --- Continue for other value comparisons
}
if(field == 'sortFieldTwo'){
    if(a.sortFieldTwo > b.sortFieldTwo) { return -1}
    // --- Continue for other value comparisons
}
// --- And continue like so for every possible sort field
```
This also just feels wrong. For data sets with potentially hundreds of sortable fields this would get very unwieldy.

So, is there something I'm missing? is there some way to get the value of an object's property without using `object[prop]`? Or is sorting by a dynamic field based on user input something I shouldn't be trying to do in AssemblyScript? All of my attempts to do this result in the same error `ERROR TS2329: Index signature is missing in type ...`.

**Comment by MaxGraey** [comment]
Are you really need a dynamic keys for `PlayerData`. Because if it will known at compile time all stuff simplified:
```ts
class PlayerData {
   constructor(
      public sortFieldOne: i32,
      public sortFieldTwo: i32,
   ) {}
}

function sortPlayersByField1(
    players: PlayerData[],
): PlayerData[] {
    function sortFunc(a: PlayerData, b: PlayerData): i32 {
        if(!a.sortFieldOne && !b.sortFieldOne){ return 0; }
        if(!a.sortFieldOne){ return 1; }
        if(!b.sortFieldOne){ return -1; }
        // --- And so on
    }
    return players.sort(sortFunc);
}
```

```ts
function sortPlayersByField2(
    players: PlayerData[],
): PlayerData[] {
    function sortFunc(a: PlayerData, b: PlayerData): i32 {
        if(!a.sortFieldTwo && !b.sortFieldTwo){ return 0; }
        if(!a.sortFieldTwo){ return 1; }
        if(!b.sortFieldTwo){ return -1; }
        // --- And so on
    }
    return players.sort(sortFunc);
}
```

**Comment by acceleratemedia** [comment]
Thanks @MaxGraey. PlayerData itself does not need dynamic keys; it is strictly defined:

```typescript
class PlayerData {
    player_id: i32
    hasStats: boolean
    rank: i32
    floor_points: number
    consensus_points: number
    fantasy_points: number
    // --- And so on
}
```
What I would like to use dynamic keys for is in the sorting. Since a user can choose one of dozens of columns to sort by, I'd prefer to use a dynamic key in a single sorting function.

We seem to agree that PlayerData should be a class, and not a map. But, it appears the only way to effectively write a sorting function with a dynamic field to be sorted by would be to use a map. The other option would be to do what you've outlined, which is to create a new sorting function for each field that needs to be sorted by. 

I can do this, but I'm just wondering if there's a more effective way to do this than to have to maintain dozens of sorting functions which are all the same exact code except for the property on PlayerData that is being sorted by.

**Comment by MaxGraey** [comment]
You can't dynamically get access to class fields like in TS. Especially because you have different types and offsets (in memory layout) of fields. The only option is to create individual functions to sort each field separately. You can resort to automatic codogen using [transforms](https://www.assemblyscript.org/compiler.html#transforms) or use own external scripts for that.

**Comment by acceleratemedia** [comment]
Thanks @MaxGraey. I've been looking into transforms as you suggested. I'm a neophyte to typescript, so I'm looking for some more guidance if you can provide it.

First, I'm assuming that transforms are a typescript thing. Looks like maybe they're generic to any type of code compilation (I've also read about Babel transforms) - but I'm assuming that that AssemblyScript is referencing is what I'm reading up about Typescript transforms.

I've gone through a couple dozen resources but I found a few that I think have me on the right track:

https://github.com/itsdouges/typescript-transformer-handbook - Seems like a thorough introduction to transforms.
https://blog.logrocket.com/using-typescript-transforms-to-enrich-runtime-code-3fd2863221ed/ - An article with an example transform
https://github.com/JairusSW/as-json/blob/master/transform/src/index.ts - This JSON package for assemblyscript that we have been using to helps us format some of our classes as JSON strings so we can console.log them.

If I'm looking to implement a transform as you suggested to automatically generate the code for dozens of search functions, will these resources put me on the right track? Or am I going down the wrong road?

**Comment by MaxGraey** [comment]
TypeScript's transformers and AssemblyScript transformers are completely different things

**Comment by acceleratemedia** [comment]
Thanks @MaxGraey. Unfortunately, with what little experience I have, the link that you provided doesn't give me much to go on insofar as how to use a transform in AssemblyScript. If none of those things that I shared are good examples, are there any other good sources to learn from other than that AssemblyScript documentation you shared?

At the bottom of that section it says:

"Transforms are a very powerful feature, but may require profound knowledge of the compiler to utilize them to their full extent, so reading through the compiler sources is a plus."

Where can I start looking into the compiler sources? Just trying to get an idea of how to get started here. Appreciate your help so far.
