### ISSUE TITLE
Unclear how to pass array references back and forth

### ISSUE THREAD

**Issue by jameshfisher** [AssemblyScript/assemblyscript#2656]
### Question

My goal is to implement something like numpy in JavaScript, using WebAssembly for hot loops, e.g. for a "dot product" procedure. For this to be efficient, it seems like I'll need to allocate arrays in WebAssembly memory, and just pass references to those back and forth.

I see clues about how to do this in AssemblyScript, like [this page talks about an `arrayref` type](https://www.assemblyscript.org/types.html), and [this example claims that things are passed by reference](https://github.com/AssemblyScript/examples/blob/main/loader/assembly/index.ts#L33-L45). But I can't come up with a working example, or see any documentation about the semantics.

Here's my naive test code that seems to show that `Float32Array` is copied over FFI, rather than having references passed:

```ts
// Desired behavior: allocate new array, return reference/pointer to it
export function newArray(length: i32): Float32Array {
  return new Float32Array(length);
}

// Desired behavior: take reference to array, return that reference
export function arrayReturn(arr: Float32Array): Float32Array {
  return arr;
}
```

```js
import { newArray, arrayReturn } from "../build/debug.js";

const arr1 = newArray(10);
const arr2 = arrayReturn(arr1);

// If arr1 and arr2 are references to the same memory, this will affect both
arr1[3] = 42;

// But it does not - arr2 is unaffected
console.log(arr1);
console.log(arr2);
```

How do I "make this work", i.e. pass references instead of making copies at the FFI?

**Comment by MaxGraey** [comment]
Currently when arrays cross the wasm <-> js border it passes by values (copy data) instead pass by reference. That's why `arr1` and `arr2` is not the same

**Comment by jameshfisher** [comment]
Thanks @MaxGraey, that makes sense. Although [the comments in this official example](https://github.com/AssemblyScript/examples/blob/8b23ca8fa2f27cf9a39e5dfe4989d9eeba87d48f/loader/assembly/index.ts#L31-L62) tell me that `Int32Array` is passed by reference (in both directions). Am I misunderstanding it, or is it wrong, or ...? Is there any way to adjust my example above to make it pass by reference?

**Comment by MaxGraey** [comment]
It's quite outdated example which uses `loader` instead autogenerated glue code which is using today

**Comment by jameshfisher** [comment]
Thanks @MaxGraey. Cool - passing pointers in the FFI is fine for me! E.g. following C, can I do something like 

```ts
export function newArray(length: i32): Ptr<Float32Array> {
  const arr = new Float32Array(length);
  return &arr;
}
```

Maybe I'm being stupid, but I can't see any examples of how to do this in AssemblyScript?!

**Comment by MaxGraey** [comment]
Maybe I misspoke, but when I meant pointer, it was essentially just an offset in linear memory. When you return `Float32Array` on AssemblyScript side for WebAssembly it lover to some `u32` number which is offset of buffer in `WebAssembly.Memory`. AS doesn't have pointers as concept like in C/C++

**Comment by dcodeIO** [comment]
The prior mechanism provided by the loader to make a view instead of a copy might be of interest here:

https://github.com/AssemblyScript/assemblyscript/blob/b7452165b88e6c76823818146d128a34630dc31d/lib/loader/index.js#L228-L241

While the bindings always copy defensively, it is still possible to borrow this code from the loader and instead of returning the `Float32Array` from Wasm, return `changetype<usize>(theFloat32Array)` (essentially a raw pointer), then using the loader code to make a live view.

**Comment by guest271314** [comment]
You can pass JSON back and forth without necessarily having to be concerned with maintaining references on either side of the communication channel; or write to and read from a single local or remote file.
