### ISSUE TITLE
Function parameter defaults broken

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#266]
Hello!

So I was doing some more WasmBoy updates, after I noticed a strange bug. 

Function parameter defaults no longer work, and always use the default instead of the passed value. Also, in some of my testing, I noticed it only happens on the first call.

For example:

**wasm.ts**
```
export function add(
  x: i32 = 0, 
  y: i32 = 0
  ): i32 {
  return x + y;
}
```

**some.js**
```
// Instantiate wasm, and get the exports
exports.add(12, 12)
```

You would expect to get back **24**, but you will get **0**. I also tested this in WebAssembly Studio, as well as my local AS environment.

Let me know if need to explain more or anything. Thanks! 😄

**Comment by dcodeIO** [comment]
What happens if you do:

```ts
exports._setargc(2);
exports.add(12, 12);
```

The reasoning there is that the WASM function doesn't know the number of actual parameters provided, because there is no equivalent to `arguments.length` on the WASM side. Hence there's this little helper to set the number of provided arguments to a variable length arguments function beforehand.

While this looks inconvenient, it's the only way to properly handle non-zero optional arguments. The trampoline that is exported instead of the actual function on the WASM side essentially looks like this:

```ts
function add$trampoline(x: i32, y: i32): i32 {
  switch (_argc) {
    case 0: x = 0;
    case 1: y = 0;
    case 2: break;
    default: unreachable();
  }
  return add(x, y);
}
```

**Comment by MaxGraey** [comment]
What slightly optimize this?
```ts
function add$trampoline(argc: i32, x: i32, y: i32): i32 {
  switch (argc) {
    case 0: x = 0; // default of x
    case 1: y = 0; // default of y
    case 2: break;
    default: unreachable();
  }
  return add(x, y);
}
```

```js
function varargsCall(fn) {
 const alen = arguments.length;
 switch (alen) {
   case 0: return fn.call(null, alen - 1);
   case 1: return fn.call(null, alen - 1, arguments[1]);
   case 2: return fn.call(null, alen - 1, arguments[1], arguments[2]);
   case 3: return fn.call(null, alen - 1, arguments[1], arguments[2], arguments[3]);
   case 4: return fn.call(null, alen - 1, arguments[1], arguments[2], arguments[3], arguments[4]);
   default: return fn.apply(null, [arguments.length - 1, ...Array.prototype.slice.call(arguments, 1)]);
 }
}

exports.add = varargsCall.bind(null, exports.add);
```

**Comment by torch2424** [comment]
Ahhh I see. 

For my use case, I added optional arguments on only a single function, just because it was the main configuration one, but to my knowledge, my lib or others that use the wasm module pass all of the configuration options.

Thanks for the suggestions though! Perhaps this issue could be a reminder to document the behavior? Unless I had the wrong idea to begin with.

**Comment by dcodeIO** [comment]
Now documented in [Limitations](https://github.com/AssemblyScript/assemblyscript/wiki/Limitations) :)

**Comment by torch2424** [comment]
Would you mind if I added an "Initializer" code example in the Wiki you just linked? 

I think without the context of this issue, "initializer" wouldn't mean much to a "drive by" reader if that makes sense.

**Comment by torch2424** [comment]
Code example was added to docs 😄 Closing...
