### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Topthinking** [AssemblyScript/assemblyscript#2667]
### Bug description

![image](https://user-images.githubusercontent.com/13382821/224084082-9cd94acd-86bd-4e29-9ce0-56b2d8370407.png)

### AssemblyScript version

0.27.1

**Comment by HerrCai0907** [comment]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/77575210/224087844-89b6532a-52f6-4484-892d-81d5f4cb0acc.png">
Assemblyscript doesn't depend on this package, maybe there are some other dependencies in your project need this package

**Comment by dcodeIO** [comment]
Not seeing the package in question in [package-lock](https://github.com/AssemblyScript/assemblyscript/blob/main/package-lock.json) as well, so I'd also suspect that this is not an AS bug. I might be wrong, though, since in https://github.com/AssemblyScript/assemblyscript/pull/2643 Max updated the dependencies - which is typically something I do to be sure and keep package-lock in sync with my machine as the source of truth. If it's an AS bug, then it would be related to that particular PR.

**Comment by MaxGraey** [comment]
Hmm, I checked install process with npm 8.1.0 and AS installed successfully. However, it has some warns
```sh
> npm i assemblyscript

npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 100 packages, and audited 101 packages in 9s

3 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (2 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

**Comment by MaxGraey** [comment]
@Topthinking try to install in pure directory (without any existing package.json and node_modules). Perhaps your error relate to another package(s) which already installed
