### ISSUE TITLE
How to remove exported `_start` function

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#2672]
### Question

I want to compile a project to wasm code without exported `start` functions(it is disabled forcely).
But the logic of `start` seems should be called before use other exported wasm functions.
So how to elimate the start function.

```wat
  ;; some init logic in start
  i32.const 1804
  global.set $~lib/rt/stub/offset
```

**Comment by yjhmelody** [comment]
Could support a `asc` config to lazy call `start` function once when call other exported function?
Maybe behave like `@lazy` decorator.

**Comment by yjhmelody** [comment]
Any plan to remove `start` function by `asc` cmd?

**Comment by dcodeIO** [comment]
The alternatives have implications for both performance and code size, so would need good arguments to be included. On that basis, I wonder why the runtime used doesn't instead stick to the spec / convention?

**Comment by athei** [comment]
> I wonder why the runtime used doesn't instead stick to the spec / convention?

Can we discuss here?
https://github.com/paritytech/substrate/issues/13621#issuecomment-1475347626
