### ISSUE TITLE
Create assemblyscript library

### ISSUE THREAD

**Issue by scorsi** [AssemblyScript/assemblyscript#269]
Hey guys,

I'm looking to create a React-like framework for AssemblyScript. How could I import my project into another assemblyscript project (the user one) ?

I was thinking about creating my library then compile it to wasm and to use/import it with the loader, bridge all methods to the other.

Example:
```javascript
if ('WebAssembly' in window) {
    fetch('MY_REACT_LIKE_LIBRARY.wasm')
        .then(response => response.arrayBuffer())
        .then(buffer => WebAssembly.instantiate(buffer, {
            // AUTOMATIC JAVASCRIPT IMPORT
        }))
        .then(reactLikeLibrary => {
            fetch('USER_AS_PROJECT.wasm')
                .then(response => response.arrayBuffer())
                .then(buffer => WebAssembly.instantiate(buffer, {
                    // AUTOMATIC IMPORT OF 'MY_REACT_LIKE_LIBRARY.wasm' LIBRARY
                    // + USER IMPORT
                }))
                .then(userProject => {
                    const instance = userProject.instance;
                    // CALL MAIN FUNCTION
                    instance.exports.main()
                })
                .catch(console.error);
        })
        .catch(console.error);
} else {
    alert("Your browser doesn't support Web Assembly. You may need " +
        "to enable it in your browser's flags.");
}
```
(Of couse, this code will be bundled with the library and be more like the assemblyscript loader)

Is there a clever solution for doing this ? Import directly the code from the user AS code (like npm package : without carring sources in the directory) ?

Thanks,

**Comment by ddibiase** [comment]
You're going to recreate React for use with WebAssembly? Seems like a hefty, long-term effort. I'm working on doing the same thing however I'm leveraging an existing library written in TypeScript to make porting a lot easier.

**Comment by scorsi** [comment]
I'll not simply recreate React, I would to create something different, faster and lightweight.

Do you have any idea how I can do that ? I was thinking about using RustWasm or Emscripten which allow external library import (and rocks with that).

**Comment by dcodeIO** [comment]
> I would like to create something different, faster and lightweight (with bindings for DOM manipulation and WebSocket)

I'd suggest to wait for WASM GC/reference types for that, unless performance is negligible.

> I was thinking about using RustWasm or Emscripten which allow external library import (and rocks with that)

Sure, but while it helps with the convenience part, existing tooling usually involves a significant performance hit due to copying stuff around etc, so you might be disappointed by the results you get. That is, in a React-like case with a lot of interop, while computationally expensive things without too much interop can actually be fast today.

**Comment by scorsi** [comment]
Well, I know that all the interop between JS and WASM will slower the framework. I just want to dive into all the rendering mechanisme before WASM GC/reference types are available.

Do you know how I can make and import library easily with AS ?

**Comment by MaxGraey** [comment]
@scorsi Did you see already created libraries for AssemblyScript [here](https://github.com/AssemblyScript/assemblyscript/wiki/Built-with-AssemblyScript#libraries)?

**Comment by scorsi** [comment]
Oh thanks @MaxGraey ! This will hope for sure.
And nice job btw.
