### ISSUE TITLE
Compile error trying to use process.time()

### ISSUE THREAD

**Issue by brian-hay** [AssemblyScript/assemblyscript#2691]
### Question

New to AS so it's likely me doing something wrong.

When I try to export a function using `process.time()` I receive a compile error:
```
import { process } from 'process';

export function start(): void {
  const time: i64 = process.time();
}
```

```
ERROR AS200: Conversion from type 'f64' to 'i64' requires an explicit cast.
    :
 32 │ return Date_binding.now();
    │        ~~~~~~~~~~~~~~~~~~
    └─ in ~lib/process.ts(32,12)
```

**Comment by dcodeIO** [comment]
You are doing everything right, this looks like a bug.

https://github.com/AssemblyScript/assemblyscript/blob/b248254811e656fd053bef51e8dc704cb439ad01/std/assembly/process.ts#L31-L33

Should be

```ts
  export function time(): i64 {
    return <i64>Date_binding.now();
  }
```

because `now` returns an `f64` (a number from JS).

**Comment by dcodeIO** [comment]
Side note: I am not quite sure why `process.time` exists in the first place, though, given that Node doesn't have it and there is `Date.now` doing the same. Probably better to use `Date.now` instead.

**Comment by brian-hay** [comment]
Thanks @dcodeIO for jumping on this so quick!
