### ISSUE TITLE
dont support "for..in object" ?

### ISSUE THREAD

**Issue by charlesooo** [AssemblyScript/assemblyscript#2695]
### Question

```
let obj={a:1,b:2}
for (let key in obj) {
  console.log(key)
}
```
debug ts file get errors:

```
ERROR TS1110: Type expected.
: 
26 │ for (let key in obj) {
│             ^
└─ in assembly/styles.ts(26,13) 

ERROR TS1005: ';' expected. 
: 
26 │ for (let key in obj) {
│          ~~~
└─ in assembly/styles.ts(26,10) 
```
new to as,
anyone knows why? 
and is there any way to deep clone an object in as ? trying for a day, and get nowhere

**Comment by CountBleck** [comment]
Nope, `for`-`in` is not supported. There is no way to iterate over the keys of an object. There isn't a built-in way to deep-clone objects either...

What's your end goal? Note that AssemblyScript is strictly typed.

**Comment by charlesooo** [comment]
undersood, thanks
