### ISSUE TITLE
Is there a way to compile mutable variables from the global scope not as WASM-global but as part of the memory?

### ISSUE THREAD

**Issue by osipov-mit** [AssemblyScript/assemblyscript#2698]
### Question

The compiled wasm now only supports one-time launch due to the `start` function that overwrites the global variables every time. So all global variables will be reseted the next time you run the program. Our use-case requires multiple launches with access to the changed state of the program. It could be solved by storing mutable variables in memory (e.g. by constant addresses defined at compile time)

**Comment by CountBleck** [comment]
You can use `const ptr = memory.data(size)` to get a pointer, and it can be used for primitives (excluding strings and Arrays). It won't work with objects. You'd also have to manually `load`/`store` values.

There's also an `--exportStart nameOfExport` (if I'm getting the name right) to export the start function (useful for WASI). You might be interested in that.

**Comment by osipov-mit** [comment]
Thank you for the response @CountBleck. 
I understand when it comes to primitives but what about objects?

**Comment by MaxGraey** [comment]
You can write you own [transform](https://www.assemblyscript.org/compiler.html#transforms) which scan all mutable globals and rewrite / modify it to `memory.data`. As well as all its usages. Like:
Before:
```ts
let globInt: u32 = 0;
let globFloat: f64 = 0.0;

export function init(a: u32, b: f64) {
  globInt = a;
  globFloat = b;
}

export function getGlobInt(): u32 {
  return globInt;
}
```
After transform:
```ts
let globIntPtr: usize = memory.data<u32>([0]);
let globFloatPtr: usize = memory.data<f64>([0]);

export function init(a: u32, b: f64) {
  store<u32>(globIntPtr, a);
  store<f64>(globFloat, b);
}

export function getGlobInt(): u32 {
  return load<u32>(globIntPtr);
}
```

**Comment by CountBleck** [comment]
@MaxGraey Such a transform would also have to work with namespaces.

Do you know of a Binaryen pass that lowers globals (except `externref` and co.) into memory locations?

**Comment by MaxGraey** [comment]
Nope. But it's not hard to write for Binaryen.
You can check similar transform here via Rust and warlus: 
https://github.com/kettle11/tangle/blob/main/wasm_guardian/src/lib.rs

**Comment by HerrCai0907** [comment]
Maybe you can export another function as start function (for example in our project is _start) and think of ~start as initialization function. I think it more easy than developing a transform.

**Comment by CountBleck** [comment]
I don't think that'd prevent globals from being reinitialized. `--exportStart _start` might be the way to go.

**Comment by HerrCai0907** [comment]
It should not use `--exportStart _start`.

this is a example:
```ts
let v: i32[] = [];
v.push(1);
declare function log(v: i32): void;
export function _start(): void {
  v.push(100);
  log(v.length);
}
```

```js
import { readFileSync } from "fs";
const wasm = await WebAssembly.compile(readFileSync("build/debug.wasm"));
const e = await WebAssembly.instantiate(wasm, {
  index: { log: (v) => console.log(v) },
});

e.exports._start();
e.exports._start();
e.exports._start();
```

and the output should be 2, 3, 4.

What is needed is in runtime, create a instance and call user-defined start function(here is _start). If this instance is not destroyed, the value of global will not be reinitialized.

**Comment by CountBleck** [comment]
Oh, you're probably right...
