### ISSUE TITLE
Porting existing TypeScript app for AssemblyScript compiles

### ISSUE THREAD

**Issue by ddibiase** [AssemblyScript/assemblyscript#270]
Hi there, some questions/curiosities (and possibly feature requests). Most are related to porting from a previous TypeScript project:

1. How should we handle Promises or a Promise framework when dealing with a porting project?
2. Can AS handle parsing JSON natively?
3. Any suggestions for handling large porting projects?

Thanks.

**Comment by MaxGraey** [comment]
1. Promise is not implemented yet. But this not should very hard.
2. JSON is not implemented as well. But this part is not easy especially `JSON.stringify`.
3. Avoid dynamic runtime stuffs and replace it to compile time (generics for example) if possible or import this parts from js host.
