### ISSUE TITLE
Console log (and similar) should conform to WASI

### ISSUE THREAD

**Issue by ashtonmeuser** [AssemblyScript/assemblyscript#2703]
### Feature suggestion

Currently, [`console.log`](https://www.assemblyscript.org/stdlib/console.html#static-members) and friends e.g. `console.error` create Wasm module imports like `"env"."console.log": [I32] -> []` and `"env"."console.error": [I32] -> []` which are completely unique to AssemblyScript. They should instead conform to WASI's `"wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]` import which can accomplish the same thing while being more likely to be supported by runtimes.

For example, `console.log` should call `wasi_snapshot_preview1.fd_write` with a file descriptor (first argument) of 1 (STDOUT), `console.error` should call with FD 2 (STDERR).

Related to https://github.com/AssemblyScript/assemblyscript/issues/2585.

**Comment by CountBleck** [comment]
Use [`@assemblyscript/wasi-shim`](https://github.com/AssemblyScript/wasi-shim). WASI support was intentionally removed from the compiler, and honestly, this change just wouldn't make sense when the browser is the target.
