### ISSUE TITLE
incorrect compilation

### ISSUE THREAD

**Issue by Yaffle** [AssemblyScript/assemblyscript#2706]
### Bug description
```ts
export function fib(a: f64): f64 {
   return a * f64(2.0)**f64(-52)
}
```
the output looks like the constains is 2.2204460492503128e-16 which does not equal original constant

**Comment by CountBleck** [comment]
What's the `a` you're using? I do notice a small error between JS and AS, but only when the module is compiled in release mode (likely due to Binaryen's precompute).

**Comment by Yaffle** [comment]
@CountBleck  it will fail for any a, as the generate code has constant 2.2204460492503128e-16

**Comment by MaxGraey** [comment]
It [compiles to](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKZXhwb3J0IGZ1bmN0aW9uIGZpYihhOiBmNjQpOiBmNjQgewogIHJldHVybiBhICogZjY0KDIuMCkqKmY2NCgtNTIpCn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdCB0eXBlPSJtb2R1bGUiPgpjb25zdCBleHBvcnRzID0gYXdhaXQgaW5zdGFudGlhdGUoYXdhaXQgY29tcGlsZSgpLCB7IC8qIGltcG9ydHMgKi8gfSkKY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCmZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICBvdXRwdXQudmFsdWUgKz0gYGZpYigke2l9KSA9ICR7ZXhwb3J0cy5maWIoaSl9XG5gCn0KPC9zY3JpcHQ+)
```wat
(func $module/fib (param $0 f64) (result f64)
  local.get $0
  f64.const 2.220446049250313e-16
  f64.mul
 )
```
Which is correct for this source:
```ts
export function fib(a: f64): f64 {
   return a * f64(2.0) ** f64(-52)
}
```

**Comment by CountBleck** [comment]
That constant does not match what Node.js produces, and the result of `fib(2)` differs between debug and release regardless.

**Comment by MaxGraey** [comment]
It's only in Chrome:

[playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKZXhwb3J0IGZ1bmN0aW9uIGZpYihhOiBmNjQpOiBmNjQgewogICByZXR1cm4gYSAqIGY2NCgyLjApICoqIGY2NCgtNTIpCn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdCB0eXBlPSJtb2R1bGUiPgpjb25zdCBleHBvcnRzID0gYXdhaXQgaW5zdGFudGlhdGUoYXdhaXQgY29tcGlsZSgpLCB7IC8qIGltcG9ydHMgKi8gfSkKY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ291dHB1dCcpCgpmdW5jdGlvbiBmaWJfanMoYSkgewogICByZXR1cm4gYSAqIDIuMCAqKiAtNTIKfQoKZm9yIChsZXQgeCBvZiBbMCwgMSwgMl0pIHsKICBvdXRwdXQudmFsdWUgKz0gYGZpYl9hcygke3h9KSA9ICR7ZXhwb3J0cy5maWIoeCl9XG5gCiAgb3V0cHV0LnZhbHVlICs9IGBmaWJfanMoJHt4fSkgPSAke2ZpYl9qcyh4KX1cblxuYAp9Cjwvc2NyaXB0Pg==)
```
fib_as(0) = 0
fib_js(0) = 0

fib_as(1) = 2.2204460492503128e-16
fib_js(1) = 2.220446049250313e-16

fib_as(2) = 4.4408920985006257e-16
fib_js(2) = 4.440892098500626e-16
```

For Firefox it's ok:
```
fib_as(0) = 0
fib_js(0) = 0

fib_as(1) = 2.220446049250313e-16
fib_js(1) = 2.220446049250313e-16

fib_as(2) = 4.440892098500626e-16
fib_js(2) = 4.440892098500626e-16
```

For Safari also
```
fib_as(0) = 0
fib_js(0) = 0

fib_as(1) = 2.220446049250313e-16
fib_js(1) = 2.220446049250313e-16

fib_as(2) = 4.440892098500626e-16
fib_js(2) = 4.440892098500626e-16
```

I think it's bug or incorrect "optimization" of Chrome.

**Comment by CountBleck** [comment]
Oh, @MaxGraey, you're right. I checked Python, C, and Java to make sure.

There's just one problem: this "optimization" occurs at compile-time, according to the WAT (and the differing seven bytes ending in the fourth-to-last byte in the Wasm).

## Firefox
<img width="856" alt="Screen Shot 2023-06-12 at 15 25 21" src="https://github.com/AssemblyScript/assemblyscript/assets/79281724/8e812b7a-0c1c-4275-836b-c83b1ad7644f">

```js
  return await WebAssembly.compile(new Uint8Array([0,97,115,109,1,0,0,0,1,6,1,96,1,124,1,124,3,2,1,0,5,3,1,0,0,7,16,2,3,102,105,98,0,0,6,109,101,109,111,114,121,2,0,10,16,1,14,0,32,0,68,0,0,0,0,0,0,176,60,162,11]));
  //                                                                                                                                                                                      ^^^^^^^^^^^^^^^
```

## Chrome
<img width="882" alt="Screen Shot 2023-06-12 at 15 25 48" src="https://github.com/AssemblyScript/assemblyscript/assets/79281724/3d4d9e3f-aa92-4d65-afba-484325dcb1d2">

```js
  return await WebAssembly.compile(new Uint8Array([0,97,115,109,1,0,0,0,1,6,1,96,1,124,1,124,3,2,1,0,5,3,1,0,0,7,16,2,3,102,105,98,0,0,6,109,101,109,111,114,121,2,0,10,16,1,14,0,32,0,68,255,255,255,255,255,255,175,60,162,11]));
  //                                                                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Chrome *compiles-in* the incorrect `...3128e-16` constant to the binary.
The only way I know for a user to avoid this *right now* is to use Bun (which uses JSC and not V8).

**Comment by MaxGraey** [comment]
I guess make sense to report to https://bugs.chromium.org/p/v8/issues

**Comment by MaxGraey** [comment]
> don't know why you think it is optimization issue

In AS uses binaryen.wasm which use internal optimizations to fold into this `2.2204460492503128e-16` constant. It should be deterministic on all browsers because WebAssembly also deterministic. Chrome only one browser which do this slightly imprecise. This means it's problem of V8

**Comment by CountBleck** [comment]
To put it shortly, the compilation is producing different results on V8 (Node.js and Chromium-based browsers) compared to SpiderMonkey (Firefox) and JSC (Safari).

This is therefore a bug in V8 and not AssemblyScript. As @MaxGraey said above, the bug likely occurs from V8 optimizing the WebAssembly code present in Binaryen.js (which is the optimizer AS uses).

For now, I'll just close the issue.

**Comment by MaxGraey** [comment]
I'm sorry, it's not binaryen / WebAssembly. If left and right are constants then constant folding happens on the JavaScript side. Most engines, especially v8 use speculative optimizations for integer constants in the right hand side, we are trying to fix this like (https://github.com/AssemblyScript/assemblyscript/blob/main/src/util/math.ts#L11). But unfortunately for v8 even this does not always help to improve accuracy as this case shows

**Comment by Yaffle** [comment]
@MaxGraey , oh,
for power of 2 it can be avoided, but it may have other bugs I think.
ideally, it should use same pow implementation as in your runtime library

**Comment by Yaffle** [comment]
@MaxGraey it is also buggy when x is negative:
(-3)**11

**Comment by MaxGraey** [comment]
> (-3)**11
Hmm, yeah. it return `NaN` instead `-177147`.
PR welcomed

**Comment by Yaffle** [comment]
@MaxGraey  Thanks, too complex, may be next time

**Comment by MaxGraey** [comment]
Np, I already made quick fix for negative bases: https://github.com/AssemblyScript/assemblyscript/pull/2709
