### ISSUE TITLE
the AssemblyScript compiler has crashed during initialize

### ISSUE THREAD

**Issue by sirius651** [AssemblyScript/assemblyscript#2713]
### Bug description

I got below error when trying to compile assembly script.

```
 Whoops, the AssemblyScript compiler has crashed during initialize :-(
▌
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌
▌ AssertionError: assertion failed
```

### Steps to reproduce

`$ ASK_CONFIG=./askconfig.json asc --config asconfig.json incrementer.ts`

### AssemblyScript version

v0.27

**Comment by MaxGraey** [comment]
This is an abnormal compiler crash. Without an example of the source code that caused it we cannot solve the problem

**Comment by CountBleck** [comment]
We'd also need the full stack trace, and not just "Assertion failed". Every line starting in `▌` should be sent here.
