### ISSUE TITLE
Cannot import the ASC module (or anything) via normal package install

### ISSUE THREAD

**Issue by bananu7** [AssemblyScript/assemblyscript#2724]
### Bug description

The library seems unusable when installed via npm and imported (for web packaging use). After running it fails with

```
SyntaxError
Unexpected identifier '$csbImport'
```

The CDN version works.

### Steps to reproduce

The easiest is to create a sandbox, add `assemblyscript` as dependency, then import and try to use it, like so:https://codesandbox.io/s/elastic-dream-82ywym?file=/src/index.js

(the example wouldn't work, but it's the one taken directly from docs)

### AssemblyScript version

0.27.1

**Comment by CountBleck** [comment]
Is there a stack trace or a filename I can look at? I've never heard of this `$csbImport`...

**Comment by bananu7** [comment]
> Is there a stack trace or a filename I can look at? I've never heard of this `$csbImport`...

I haven't ran it locally yet, but that's what the codesandbox presents:

![image](https://github.com/AssemblyScript/assemblyscript/assets/2399997/94350006-bc02-4722-af1e-f6aaa5f92239)

**Comment by CountBleck** [comment]
Actually, the `csb` in `$csbImport` probably stands for "CodeSandbox", so this doesn't look like an issue with AS...

**Comment by bananu7** [comment]
Well, when trying to build it locally, the issue i get is a bunch of those:

```
✘ [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/assemblyscript/dist/asc.js:7:6198:
      7 │ ...ypeof globalThis.process<"u"?globalThis.process:0)==="[object process]",X,fn,v,j,hn;ht?(X=await import("fs"),fn=await import("module"),v=await import("path"),j=globalThis.process,hn=awa...
 ```

**Comment by CountBleck** [comment]
Top-level await only works with ESM. Your bundle must target ESM and not an IIFE, and the `<script>` tag that's using your bundle must use `type="module"`.

**Comment by CountBleck** [comment]
Since this is more of a configuration issue than an issue with AS, I'll close this.
