### ISSUE TITLE
 npm run asbuild ERR!

### ISSUE THREAD

**Issue by NoRainLand** [AssemblyScript/assemblyscript#2732]
### Bug description

[look here!](https://stackoverflow.com/questions/76851841/npm-run-asbuild-err)

### Steps to reproduce

[look here!](https://stackoverflow.com/questions/76851841/npm-run-asbuild-err)

### AssemblyScript version

v0.27.8

**Comment by CountBleck** [comment]
Try using Node v16.

**Comment by MaxGraey** [comment]
Don't use `asbuild` and try to install node v16

**Comment by CountBleck** [comment]
Using `npm run asbuild` should be fine (it's generated via `asinit` and just invokes `asc`). I suspect the Node version's just too low.
