### ISSUE TITLE
Bindings code uses same id and align for different input variables when they are of same TypedArray class

### ISSUE THREAD

**Issue by foo123** [AssemblyScript/assemblyscript#2734]
### Bug description

A function which accepts multiple  Uint8ClampedArray inputs results in bindings code not being able to provide correct id and align for the second Uint8ClampedArray input

### Steps to reproduce

```typescript
export function displacementmapfilter(im:Uint8ClampedArray, w:i32, h:i32, mode:i32, map:Uint8ClampedArray, mapW:i32, mapH:i32, startX:f32, startY:f32, X:i32, Y:i32, SX:f32, SY:f32, color:i32):Uint8ClampedArray
{
     // do something 
     return im;
}
```

Bindings (raw) use same id and align for the different inputs `im` and `map`

```js
  const adaptedExports = Object.setPrototypeOf({
    displacementmapfilter(im, w, h, mode, map, mapW, mapH, startX, startY, X, Y, SX, SY, color) {
      // src/asm/displacementmapfilter/displacementmapfilter(~lib/typedarray/Uint8ClampedArray, i32, i32, i32, ~lib/typedarray/Uint8ClampedArray, i32, i32, f32, f32, i32, i32, f32, f32, i32) => ~lib/typedarray/Uint8ClampedArray
      im = __retain(__lowerTypedArray(Uint8ClampedArray, 4, 0, im) || __notnull());
      map = __lowerTypedArray(Uint8ClampedArray, 4, 0, map) || __notnull();
      try {
        return __liftTypedArray(Uint8ClampedArray, exports.displacementmapfilter(im, w, h, mode, map, mapW, mapH, startX, startY, X, Y, SX, SY, color) >>> 0);
      } finally {
        __release(im);
      }
    },
  }, exports);
```

Which results in code not working correctly. I had to manually set the id and align to the values `8, 4` in order for the code to return correct results.

### AssemblyScript version

0.27.9

**Comment by MaxGraey** [comment]
> Which results in code not working correctly

How exactly does it show up?

Both inputs have `Uint8ClampedArray` type which should have same `id` (currently `4`) and same alignment in log2 scale (which is `0` for byte)

**Comment by dcodeIO** [comment]
I'm also not seeing an issue with the generated bindings code. Using `8, 4` instead of `4, 0` would instead target whatever class has id 8 (not Uint8ClampedArray) with an alignment of 16 bytes.

**Comment by CountBleck** [comment]
It looks correct to me. The "align" parameter is really `log2(BYTES_PER_ELEMENT)`. And the ID seems to be correct according to `idof<Uint8ClampedArray>()`.

**Comment by MaxGraey** [comment]
Here simplified example in playground which return absolutely correct result (input == output):
[playground](
https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmV4cG9ydCBmdW5jdGlvbiB0ZXN0KAogIGE6IFVpbnQ4Q2xhbXBlZEFycmF5LCAKICBiOiBVaW50OENsYW1wZWRBcnJheSwKKTogVWludDhDbGFtcGVkQXJyYXkgewogIHJldHVybiBhOwp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQgdHlwZT0ibW9kdWxlIj4KY29uc3QgZXhwb3J0cyA9IGF3YWl0IGluc3RhbnRpYXRlKGF3YWl0IGNvbXBpbGUoKSwgeyAvKiBpbXBvcnRzICovIH0pCmNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQoKY29uc3QgYSA9IFVpbnQ4Q2xhbXBlZEFycmF5Lm9mKDEsIDI1NSwgMjU2KTsKY29uc3QgYiA9IG5ldyBVaW50OENsYW1wZWRBcnJheSgpOwpvdXRwdXQudmFsdWUgKz0gYGlucHV0OiAke2F9XG5gOwpjb25zdCByZXN1bHQgPSBleHBvcnRzLnRlc3QoYSwgYik7Cm91dHB1dC52YWx1ZSArPSBgb3V0cHV0OiAke3Jlc3VsdH1cbmA7Cgo8L3NjcmlwdD4=)

**Comment by MaxGraey** [comment]
But I should mention. If you're using `null` or `undefined` for second input on JS side, you will catch runtime error like "value can't be a null". So you should use non-null typed array. If you want use `null` for second array it should be implicitly declared as `map: Uint8ClampedArray | null`.

**Comment by foo123** [comment]
Class id maybe corret but align is certainly wrong, because it does not work as expected. Note that before map input there are two i32 inputs. I counted their offestes and this is how I computed the align value of 4 which worked (gives correct results).

All inputs are passed with values (no null).

**Comment by foo123** [comment]
If you try to use the map input it appears scrambled as output. whole code of filter is this:

```typescript
// The entry file of your WebAssembly module.
export function displacementmapfilter(im:Uint8ClampedArray, w:i32, h:i32, mode:i32, map:Uint8ClampedArray, mapW:i32, mapH:i32, startX:f32, startY:f32, X:i32, Y:i32, SX:f32, SY:f32, color:i32):Uint8ClampedArray
{
    const IGNORE:i32 = 0, WRAP:i32 = 1, CLAMP:i32 = 2, COLOR:i32 = 3;
    let alpha:i32, red:i32, green:i32, blue:i32,
        bxx:i32 = w-1, byy:i32 = h-1,
        i:i32, j:i32, k:i32,
        x:i32, y:i32, ty:i32, ty2:i32, yy:i32, xx:i32,
        mapOff:i32, dstOff:i32, srcOff:i32,
        imLen:i32=im.length, srcx:i32, srcy:i32,
        mapLen:i32 = map.length, mapArea:i32 = mapLen>>>2,
        ww:i32 = mapW < w ? mapW : w,
        hh:i32 = mapH < h ? mapH : h,
        applyArea:i32 = (ww*hh)<<2;

    
    SX *= 0.00390625; SY *= 0.00390625;
    let stx:i32 = i32(startX*f32(bxx));
    let sty:i32 = i32(startY*f32(byy));
    let styw:i32 = sty*w;
    let bx0:i32 = -stx, by0 = -sty;
    let bx:i32 = bxx-stx, by:i32 = byy-sty;

    let imcpy:Uint8ClampedArray = new Uint8ClampedArray(imLen);/*imcpy.set(im);*/
    for (i=0; i<imLen; ++i) imcpy[i] = im[i];

    let displace:Int16Array = new Int16Array(mapArea<<1);
    for (j=0,i=0; i<mapArea; i+=4)
    {
        displace[j++] = i32(f32( (map[i   +X]) - 128 ) * SX);
        displace[j++] = i32(f32( (map[i   +Y]) - 128 ) * SY);
    }

    if (COLOR == mode)
    {
        alpha = (color >>> 24) & 255;
        red = (color >>> 16) & 255;
        green = (color >>> 8) & 255;
        blue = color & 255;
        for (x=0,y=0,ty=0,ty2=0,i=0; i<applyArea; i+=4,++x)
        {
            // update image coordinates
            if (x>=ww) {x=0; ++y; ty+=w; ty2+=mapW;}

            // if inside the application area
            if (y<by0 || y>by || x<bx0 || x>bx) continue;

            xx = x + stx; yy = y + sty; dstOff = (xx + ty + styw)<<2;

            j = (x + ty2)<<1; srcx = xx + displace[j];  srcy = yy + displace[j+1];

            // color
            if (srcy>byy || srcy<0 || srcx>bxx || srcx<0)
            {
                im[dstOff] = red;  im[dstOff+1] = green;
                im[dstOff+2] = blue;  im[dstOff+3] = alpha;
                continue;
            }

            srcOff = (srcx + srcy*w)<<2;
            // new pixel values
            im[dstOff] = imcpy[srcOff];   im[dstOff+1] = imcpy[srcOff+1];
            im[dstOff+2] = imcpy[srcOff+2];  im[dstOff+3] = imcpy[srcOff+3];
        }
    }
    else if (IGNORE == mode)
    {
        for (x=0,y=0,ty=0,ty2=0,i=0; i<applyArea; i+=4,++x)
        {
            // update image coordinates
            if (x>=ww) {x=0; ++y; ty+=w; ty2+=mapW;}

            // if inside the application area
            if (y<by0 || y>by || x<bx0 || x>bx) continue;

            xx = x + stx; yy = y + sty; dstOff = (xx + ty + styw)<<2;

            j = (x + ty2)<<1; srcx = xx + displace[j];  srcy = yy + displace[j+1];

            // ignore
            if (srcy>byy || srcy<0 || srcx>bxx || srcx<0) continue;

            srcOff = (srcx + srcy*w)<<2;
            // new pixel values
            im[dstOff] = imcpy[srcOff];   im[dstOff+1] = imcpy[srcOff+1];
            im[dstOff+2] = imcpy[srcOff+2];  im[dstOff+3] = imcpy[srcOff+3];
        }
    }
    else if (WRAP == mode)
    {
        for (x=0,y=0,ty=0,ty2=0,i=0; i<applyArea; i+=4,++x)
        {
            // update image coordinates
            if (x>=ww) {x=0; ++y; ty+=w; ty2+=mapW;}

            // if inside the application area
            if (y<by0 || y>by || x<bx0 || x>bx) continue;

            xx = x + stx; yy = y + sty; dstOff = (xx + ty + styw)<<2;

            j = (x + ty2)<<1; srcx = xx + displace[j];  srcy = yy + displace[j+1];

            // wrap
            srcy = srcy>byy ? srcy-h : (srcy<0 ? srcy+h : srcy);
            srcx = srcx>bxx ? srcx-w : (srcx<0 ? srcx+w : srcx);

            srcOff = (srcx + srcy*w)<<2;
            // new pixel values
            im[dstOff] = imcpy[srcOff];   im[dstOff+1] = imcpy[srcOff+1];
            im[dstOff+2] = imcpy[srcOff+2];  im[dstOff+3] = imcpy[srcOff+3];
        }
    }
    else //if (CLAMP == mode)
    {
        for (x=0,y=0,ty=0,ty2=0,i=0; i<applyArea; i+=4,++x)
        {
            // update image coordinates
            if (x>=ww) {x=0; ++y; ty+=w; ty2+=mapW;}

            // if inside the application area
            if (y<by0 || y>by || x<bx0 || x>bx) continue;

            xx = x + stx; yy = y + sty; dstOff = (xx + ty + styw)<<2;

            j = (x + ty2)<<1; srcx = xx + displace[j];  srcy = yy + displace[j+1];

            // clamp
            srcy = srcy>byy ? byy : (srcy<0 ? 0 : srcy);
            srcx = srcx>bxx ? bxx : (srcx<0 ? 0 : srcx);

            srcOff = (srcx + srcy*w)<<2;
            // new pixel values
            im[dstOff] = imcpy[srcOff];   im[dstOff+1] = imcpy[srcOff+1];
            im[dstOff+2] = imcpy[srcOff+2];  im[dstOff+3] = imcpy[srcOff+3];
        }
    }
    return im;
}
```

**Comment by CountBleck** [comment]
Alignment has nothing to do with the order of arguments. One question: do you see any difference between the behavior of this code in AS and its behavior in regular TS with the portable std?

**Comment by MaxGraey** [comment]
I don't understand how increasing `align` may fix something. Here codegen for `__lowerTypedArray`
[```](https://github.com/AssemblyScript/assemblyscript/blob/321ed3d44c34f9a57d9513769f5ba8447d3293a9/tests/compiler/bindings/raw.release.js#L324)
As you can see, `align` affect only on `length` of input array and doesn't affect to offset at all

**Comment by CountBleck** [comment]
@foo123 Since you say it works with a larger alignment, do you have a test case we can look at? What inputs are you using, what's the garbage output, and what's the correct output?

**Comment by dcodeIO** [comment]
Are you perhaps compiling with `--noAssert`? Asking because a larger `align` would effectively allocate more space, and if `--noAssert` is used and the array is otherwise not large enough, there'd be no error on an out of bounds access, whereas with a larger alignment data would coincidentally fit.

**Comment by foo123** [comment]
I am making a new version of my [FILTER.js](https://github.com/foo123/FILTER.js) library to have some filters in wasm. Right now I havent uploaded anything online. Yes I use noAssert as an option. But I can make a fiddle probably with the problem

**Comment by CountBleck** [comment]
Try compiling without `--noAssert` and try running your code then.

**Comment by foo123** [comment]
Ok let me try and get back..

**Comment by foo123** [comment]
Byw the correct output of the displacement filter is shown there(12th image of che)

**Comment by CountBleck** [comment]
We can't really test that for ourselves...

**Comment by foo123** [comment]
No it is scrambled again, but this time differently scrambled

![Snap 2023-08-21 at 19 24 30](https://github.com/AssemblyScript/assemblyscript/assets/1263582/314574ac-5caa-432b-b11f-ab0d2802ff8b)

**Comment by foo123** [comment]
Ok let me make a fiddle and get back at you

correct output should be this:

![Snap 2023-08-21 at 19 26 13](https://github.com/AssemblyScript/assemblyscript/assets/1263582/ff349f31-7cd8-49e0-8801-9061700f7ac9)

**Comment by dcodeIO** [comment]
Seems as if the filter only processed to about 1/4th of total pixels. At least the upper portion seems to be the same of what is expected. Could be a loop stopping too early maybe, and when the array is larger (due to larger `align`) that doesn't happen.

**Comment by foo123** [comment]
The ts code is an exact replica of the working js code already used by the lib. so a bug in the ts code is unlikely.

Barebones test case is uploaded https://foo123.github.io/tests/displacementmapfilter/

**Comment by foo123** [comment]
It was a typo in the ts code that caused the map to be aligned incorrectly. Thank you for your time.

BTW any option to disable adding sourceMapUrl in exported wasm? (right now I remove it manually)

**Comment by CountBleck** [comment]
> disable adding sourceMapUrl

Probably `sourceMap: false`, but I haven't tested that.

**Comment by foo123** [comment]
@CountBleck  I already have that option as false, but still sourcemap is added. Anyway assemblyscript is a great tool. Cheers!
