### ISSUE TITLE
Support to custom heap

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#2739]
### Feature suggestion

<del>It seems that there is no way to configure an allocator defined from host. </del>

I found `--runtime` could configure this but maybe need more docs to know the details.

**Comment by CountBleck** [comment]
Whoops, I forgot about `--runtime`. You should have functions `__alloc`, `__free`, `__realloc`, `__new`, `__renew`, `__link`, `__visit`, `__collect`, and maybe one more (I don't remember off the top of my head) marked `@global` and `@unsafe`. Consult [rt/tlsf.ts](https://github.com/AssemblyScript/assemblyscript/blob/v0.27.12/std/assembly/rt/tlsf.ts) (allocator) and [rt/itcms.ts](https://github.com/AssemblyScript/assemblyscript/blob/v0.27.12/std/assembly/rt/itcms.ts) (garbage collector) in the standard library to see what you need. You'll also see another GC in [rt/tcms.ts](https://github.com/AssemblyScript/assemblyscript/blob/v0.27.12/std/assembly/rt/tcms.ts), and a GC and allocator in [rt/stub.ts](https://github.com/AssemblyScript/assemblyscript/blob/v0.27.12/std/assembly/rt/stub.ts), if you want more reference material.
