### ISSUE TITLE
project maintaining / feature roadmap

### ISSUE THREAD

**Issue by HerrCai0907** [AssemblyScript/assemblyscript#2745]
### Question

The commit frequency is going down in this project.
<img width="886" alt="image" src="https://github.com/AssemblyScript/assemblyscript/assets/77575210/d4544175-3252-40bd-b24f-4e42364269b4">

The major contributor @dcodeIO @MaxGraey contributed minimal activity.
But it looks like huge of features are still missing for AS liking closure, promise, async/await, union type, and there are lots of not reviewed PR.

I am wondering what is the feature for this project? Will this project still be maintained and welcome further feature contribute or be close to disactive.

**Comment by dcodeIO** [comment]
What do you think of adding additional maintainers to the project with commit rights? Is there interest?

**Comment by HerrCai0907** [comment]
Thanks, I'm honored to be the maintainer.

**Comment by CountBleck** [comment]
What I'm slowly working on, in my free time, is a GC lowering pass in which allocation and such is performed through functions provided by the user. That way, the current ITCMS implementation could be used for AS, while some other language might choose to use, I don't even know, some multithreaded compacting GC that needs atomic read and write barriers.

I'm going a bit slowly on it (high school takes up time, motivation's hard) but I should eventually have something I could PR upstream.

**Comment by CountBleck** [comment]
Another thing that has crossed my mind is whether it would be feasible to have our parser pass test262's parser tests.

**Comment by HerrCai0907** [comment]
> have our parser pass test262's parser tests.

Is it possible? We don't support lots of js/ts language feature, it will be hard to filter suitable test cases.

**Comment by CountBleck** [comment]
We should ideally be able to parse such code to some extent and display proper diagnostics.
-------- Original Message --------
