### ISSUE TITLE
crash when compile PropertyAccessExpression

### ISSUE THREAD

**Issue by HerrCai0907** [AssemblyScript/assemblyscript#2747]
### Bug description

 Whoops, the AssemblyScript compiler has crashed during compile :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ /Users/q540239/oss/assemblyscript/std/portable/index.js:216
▌     throw new AssertionError(message);
▌           ^
▌ 
▌ AssertionError: assertion failed
▌     at Y.assert (/Users/q540239/oss/assemblyscript/std/portable/index.js:216:11)
▌     at Kn.resolveFunction (/Users/q540239/oss/assemblyscript/src/resolver.ts:2826:7)
▌     at jr.compilePropertyAccessExpression (/Users/q540239/oss/assemblyscript/src/compiler.ts:9039:46)
▌     at jr.compileExpression (/Users/q540239/oss/assemblyscript/src/compiler.ts:3401:21)
▌     at jr.compileExpressionStatement (/Users/q540239/oss/assemblyscript/src/compiler.ts:2482:17)
▌     at jr.compileStatement (/Users/q540239/oss/assemblyscript/src/compiler.ts:2196:21)
▌     at jr.compileTopLevelStatement (/Users/q540239/oss/assemblyscript/src/compiler.ts:2160:25)
▌     at jr.compileFile (/Users/q540239/oss/assemblyscript/src/compiler.ts:1099:12)
▌     at jr.compile (/Users/q540239/oss/assemblyscript/src/compiler.ts:548:14)
▌     at Module.G0 (/Users/q540239/oss/assemblyscript/src/index-wasm.ts:358:32)
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!

### Steps to reproduce

```typescript

namespace A {
  export function bar<T>(): void {}
}

A.bar;

```

### AssemblyScript version

v0.27.9

**Comment by CountBleck** [comment]
See #2738.
