### ISSUE TITLE
Compiling release without sourceMap create a sourcemap named "false"

### ISSUE THREAD

**Issue by DaGaMx** [AssemblyScript/assemblyscript#2751]
### Bug description

I am new to AssemblyScript and followed your tutorial:
https://www.assemblyscript.org/getting-started.html#setting-up-a-new-project

I checked the output files in a hex editor and was wondering that the release ends with "sourceMappingURL" "false".
Then I saw that a file named "false" is generated in the output folder.

### Steps to reproduce

Execute this:
npx asc "C:\test\assembly\index.ts" --target release -o "C:\test\assembly\output\release\index.wasm" -Ospeed --noAssert --optimizeLevel 3

In the output folder "C:\test\assembly\output\release\" will be a file named "false".
The output file "C:\test\assembly\output\release\index.wasm" will contain a reference to that source map.

As far as I understand the compiler manual, the source map should only be generated if I specify --sourceMap.

### AssemblyScript version

v0.27.10

**Comment by woruyu** [comment]
Ask a question:
I follows your step to run `npx asc "C:\test-as\assembly\index.ts"  --target release -o "C:\test-as\assembly\output\release\index.wasm" -Ospeed --noAssert --optimizeLevel 3` but I can't get a file named "false". And I guess the reason that you get the source map is in asconfig.json, the sourceMap field is true.

**Comment by DaGaMx** [comment]
Sorry, there was a minor thing I changed in comparison to your "Getting started" manual.
If I do the same steps like in the manual, then I get the "./index.wasm.map" entry like you.
But if I update the asconfig.json to this:
`{
  "targets": {
    "debug": {
      "outFile": "build/debug.wasm",
      "textFile": "build/debug.wat",
      "sourceMap": true,
      "debug": true
    },
    "release": {
      "outFile": "build/release.wasm",
      "textFile": "build/release.wat",
      "sourceMap": false,
      "optimizeLevel": 3,
      "shrinkLevel": 0,
      "converge": false,
      "noAssert": false
    }
  },
  "options": {
    "bindings": "esm"
  }
}`
Then I get the false entry and the false file.

This also happens if I compile using "npm run asbuild".
