### ISSUE TITLE
Inefficient WAT emitted for an assignment within a conditional

### ISSUE THREAD

**Issue by rotemdan** [AssemblyScript/assemblyscript#2754]
### Bug description

I was trying to learn WAT and WebAssembly better, and then I noticed this code emitted by the AssemblyScript playground. 

I apologize if this is already fixed, but I'm not deeply familiar with AssemblyScript, and there's no version number indicated in the playground.

### Steps to reproduce

Given the input:
```asc
export function test(): i32 {
  let x = 0
  
  for (let i = 0; i < 10; i++) {
    if (x > 5) {
      x += ((x - 5) * x) / 3
    }
  }

  return x
}
```

It emits the WAT function:
```wat
(func $input/test (result i32)
  (local $0 i32)
  (local $1 i32)
  loop $for-loop|0
   local.get $1
   i32.const 10
   i32.lt_s
   if
    local.get $0
    local.get $0
    i32.const 5
    i32.sub
    i32.mul
    i32.const 3
    i32.div_s
    local.get $0
    i32.add
    local.get $0
    local.get $0
    i32.const 5
    i32.gt_s
    select
    local.set $0
    local.get $1
    i32.const 1
    i32.add
    local.set $1
    br $for-loop|0
   end
  end
  local.get $0
 )
```

Based on my understanding, it seems to perform the operations for `x += ((x - 5) * x) / 3` unconditionally, and then discards the result if the `select` operation chooses not to accept it. 

I would expect it to perform the operations in the body of the conditional only if the condition succeeds. Otherwise, it wastes many cycles on unnecessary operations (here, due to the integer division, it would take 20 to 30 extra cycles instead of 1 - 3 without it, which is major).

Maybe this is this some sort of optimization that isn't being applied correctly? I noticed that if I add an additional multiplication operation to `x += ((x - 5) * x) / 3`, like, say, change it to `x += ((x - 5) * x * x) / 3`, then the emitted WAT executes the conditional body only if the condition succeeds (as expected).

Again, I apologize if this was already fixed but I'm not that familiar with this project. I just wanted to let you know!

### AssemblyScript version

Latest version in the playground

**Comment by CountBleck** [comment]
AS's debug output seems sane, so this would be a Binaryen issue if anything. If you can reproduce this by using `wasm-opt` with `-O3` on the debug WAT, then it's their bug.

**Comment by MaxGraey** [comment]
> Otherwise, it wastes many cycles on unnecessary operations (here, due to the integer division, it would take 20 to 30 extra cycles instead of 1 - 3 without it, which is major).

Division by constant is quite cheap operation, which takes only 3-4 circles. See [this](https://ridiculousfish.com/blog/posts/labor-of-division-episode-iii.html) for more detail. And native machine [codegen](https://godbolt.org/z/oh6cqEaE6)

**Comment by rotemdan** [comment]
Thanks for the quick response. I didn't know the WAT is emitted by Binaryen, I assumed it is generated by AssemblyScript directly (that's a reasonable assumption I guess). Nevertheless, if this was my language I would probably wouldn't  potentially inefficient code to be emitted in any case. Maybe it's just a personal thing.

I'm not sure why this optimization is effective in here. 

It's possible that this compilation approach occurs with even more expensive computations. I'll try to do some further trial-and-error.

It looks like some sort of optimistic computation that is done with some assumptions on the instruction pipeline. I would imagine maybe something like this would be done at the JIT stage, not at this high-level, since it's not possible to predict which architecture is used and what are its capabilities.

Anyway, I don't know what sort of intermediate representation you're passing to Binaryen (and probably not familiar with it) so I guess I can't really file a well-written bug report to them, unfortunately.

**Comment by MaxGraey** [comment]
> It looks like some sort of optimistic computation that is done with some assumptions on the instruction pipeline. I would imagine maybe something like this would be done at the JIT stage, not at this high-level, since it's not possible to predict which architecture is used and what are its capabilities.

Division by constant is architecture-agnostic approach. It just replace division by 1 wide multiplication and one or two shifts. It usually done on higher level of IR in MVs. Also it quite linear peephole optimization, unlike transform branch into unconditional move (select). That's why this optimization done by compiler (binaryen) and not by VM. Also note Wasm runtimes are quite diverse and some of them doesn't use JIT optimizations due to use in blockchain or embedded devices.

**Comment by rotemdan** [comment]
I'm not a hardware person. Common sense tells me that it's not beneficial to perform unnecessary operations when they are clearly not needed. The decision made by the compiler in this simple case is most likely not optimal.

Maybe given a lots of assumptions about the architecture, it may turn out to be possibly "harmless" (though I'm still doubtful about that), but for me, personally "harmless" is not good enough. I simply wouldn't accept it if it were my own language.

**Comment by CountBleck** [comment]
> Nevertheless, if this was my language I would probably wouldn't want potentially inefficient code to be emitted in any case. Maybe it's just a personal thing.
I think it's sensible to hand off optimization to the official WebAssembly optimizer and let the experts handle it.

> Anyway, I don't know what sort of intermediate representation you're passing to Binaryen
Binaryen IR is very similar to Wasm instructions, but in a tree-based form. Also, just demonstrating that `wasm-opt` takes in WAT and returns suboptimal output would be enough for a bug.

**Comment by CountBleck** [comment]
> Maybe given a lots of assumptions about the architecture

Aren't most modern architectures pipelined, superscalar, out-of-order and all? I'm not a hardware person either. It also makes sense for AS (although AS doesn't make these choices) to optimize for architectures where it is most used.

**Comment by rotemdan** [comment]
I'm not a low-level programming person, and my knowledge of WAT and WASM is limited (I'm literally a beginner in this area. Only today I started learning the opcodes!) but it seems the `select` operation has to decide if to apply the new value or to keep the old one? Wouldn't that be possibly blocking in relation to the loop (and thus it may be impacted by the extra computations)? Can the loop continue even if it hadn't made that decision? Possibly..? I don't know.

Anyway, I can't really open a well-written issue on the Binaryen repository since I don't know what is the exact input that AssemblyScript is passing to it, (in the sense of an intermediate representation), getting that information may require access to the internals of AssemblyScript, which is currently beyond my capabilities. They will probably need the exact input to understand what is happening. Giving them the AssemblyScript code may not be really that helpful.

**Comment by MaxGraey** [comment]
> They will probably need the exact input to understand what is happening. Giving them the AssemblyScript code may not be really that helpful.

I'm a contributor to Binaryen as well. Binaryen uses some cost model for op codes for selectify branches and this cost model is quite balanced for a while. Also note, some VMs may lower `select` op to branch back according to their internal cost model for low level IR.

So I see no reason for further discussion. If you consider the cost model binaryen is not perfect in general, then you should provide sufficient evidence for it and open issue in their repo

**Comment by rotemdan** [comment]
I benchmarked a modified version of the code: The release build was 5.6x slower than the debug build. 

Here are the details:

I created a new project based on the official instructions, on latest Node.js (`20.0.8`). The tool installed ASC release `0.27.10`.

Here is the modified code:
```asc
export function test(): i32 {
  let x = 23847

  for (let i = 0; i < 100000000; i++) {
    if (i > 99999990) {
      x += ((x - 5234) * x) / 13
    }
  }

  return x
}
```

Here is the test code:
```js
import { test as testDebug } from "../build/debug.js";
import { test as testRelease } from "../build/release.js";

{
	const startTime = Date.now();
	const result = testDebug();
	const duration = Date.now() - startTime;

	console.log('Debug build result:');
	console.log(result);
	console.log('Debug build duration (ms):');
	console.log(duration);
}

console.log('');

{
	const startTime = Date.now();
	const result = testRelease();
	const duration = Date.now() - startTime;

	console.log('Release build result:');
	console.log(result);
	console.log('Release build duration (ms):');
	console.log(duration);
}
```

Output:
```
Debug build result:
418831474
Debug build duration (ms):
255

Release build result:
418831474
Release build duration (ms):
1410
```

The debug build took 255ms, and the release build took 1410ms.

Here is the generated WAT for both:

`debug.wat`:
```wat
(module
 (type $none_=>_i32 (func (result i32)))
 (global $~lib/memory/__data_end i32 (i32.const 8))
 (global $~lib/memory/__stack_pointer (mut i32) (i32.const 32776))
 (global $~lib/memory/__heap_base i32 (i32.const 32776))
 (memory $0 0)
 (table $0 1 1 funcref)
 (elem $0 (i32.const 1))
 (export "test" (func $assembly/index/test))
 (export "memory" (memory $0))
 (func $assembly/index/test (result i32)
  (local $x i32)
  (local $i i32)
  i32.const 23847
  local.set $x
  i32.const 0
  local.set $i
  loop $for-loop|0
   local.get $i
   i32.const 100000000
   i32.lt_s
   if
    local.get $i
    i32.const 99999990
    i32.gt_s
    if
     local.get $x
     local.get $x
     i32.const 5234
     i32.sub
     local.get $x
     i32.mul
     i32.const 13
     i32.div_s
     i32.add
     local.set $x
    end
    local.get $i
    i32.const 1
    i32.add
    local.set $i
    br $for-loop|0
   end
  end
  local.get $x
  return
 )
)
```

Release WAT:
```wat
(module
 (type $none_=>_i32 (func (result i32)))
 (memory $0 0)
 (export "test" (func $assembly/index/test))
 (export "memory" (memory $0))
 (func $assembly/index/test (result i32)
  (local $0 i32)
  (local $1 i32)
  i32.const 23847
  local.set $0
  loop $for-loop|0
   local.get $1
   i32.const 100000000
   i32.lt_s
   if
    local.get $0
    local.get $0
    i32.const 5234
    i32.sub
    local.get $0
    i32.mul
    i32.const 13
    i32.div_s
    i32.add
    local.get $0
    local.get $1
    i32.const 99999990
    i32.gt_s
    select
    local.set $0
    local.get $1
    i32.const 1
    i32.add
    local.set $1
    br $for-loop|0
   end
  end
  local.get $0
 )
)
```

Here is a zip file with the project:
[AssemblyScriptTest.zip](https://github.com/AssemblyScript/assemblyscript/files/12774036/AssemblyScriptTest.zip)

Please let me know if there is any issues with this test code.

Since some of you are involved in the Binaryen project, we can work together in investigating what is this the cause of this behavior:

* The cost model for the `select`-ifying of the conditional may need to be reevaluated.
* It doesn't seem that the V8 runtime is de-optimizing the `select` instruction here. (Also, based on my understanding that's technically a difficult thing thing to do since there is potentially an unbounded numbers of push and pop operations on the stack that may occur before `select` is executed - The 'branches' of the operation are not clearly delineated in the WAT source and the JIT may need a large and complex lookbehind to achieve this.

I'll need some assistance in finding the exact intermediate representation that is passed to Binaryen, so they can know for sure what is the input passed to them. I don't possess the knowledge to do that. I can't just give them the AssemblyScript code.

Thank you for your collaboration.

**Comment by MaxGraey** [comment]
```js
for (let i = 0; i < 100000000; i++) {
    if (i > 99999990) {
```

It's quite synthetic test. If you're replacing `99999990` to `10` or `100000000 / 2`. The result of performance will be different. But even better use something like `if (i & 1)` (odd / even) or randomized condition

**Comment by rotemdan** [comment]
Thanks for the feedback. The goal of the predicate I chose is to emulate what happens when the conditional almost always evaluates to false. The reason is that it can give a good sense of the time it takes to execute the iteration for that particular case, in order to accurately compare between the debug and release versions. 

It isn't really that synthetic. It's not uncommon that a loop executes, but the condition succeeds only a small number of times. For example, when searching a list for a particular value(s), and performing an operation when the condition succeeds.

**Comment by MaxGraey** [comment]
> It isn't really that synthetic. It's not uncommon that a loop executes

I disagree. The common scenario is usually this:
```ts
for (let i = 0; i < n; i++) {
  if (i == 0) {
     // stuff
  }
}
```
or
```
for (let i = 0; i < n; i++) {
  if (i >= k) {
  }
}
```

When `n` and `k` usually unknown in compile time and unknown for instruction cache prediction on hardware side

**Comment by HerrCai0907** [comment]
The interesting thing is I test those code in my aarch64 MACOS.
The result is totally different with @rotemdan. I guess maybe you use x84-64?
```
Debug build result:
418831474
Debug build duration (ms):
49

Release build result:
418831474
Release build duration (ms):
48
```
According to the test result, I agree with @rotemdan, that the cost module has some problem. This replacement is meaningless in aarch64 and harmful in x86.

I also check the result of gcc and clang for aarch64, they both use conditional jump instruction instead of CSEL(conditional select instructions)
https://godbolt.org/z/hT3a3YYK1

But I think maybe you can discuss instruction optimization related topic in [binaryen](https://github.com/WebAssembly/binaryen).

**Comment by CountBleck** [comment]
Yeah, whatever it is, it's a Binaryen problem and should be discussed there.
