### ISSUE TITLE
Graph build error with no details , maybe caused by bigdecimal

### ISSUE THREAD

**Issue by lyl472324464** [AssemblyScript/assemblyscript#2758]
### Bug description

if (mktData.priceOrderbook != null) 
This line can not be compiled. mktData.priceOrderbook is BigDecimal | null.

### Steps to reproduce

 "@graphprotocol/graph-cli": "^0.45.0",
    "@graphprotocol/graph-ts": "^0.29.0",

I want to build this file.
export function updateMarketPositionsFromSplit(
  conditionalTokenAddress: string,
  event: PositionSplit,
): void {
  let userAddress = event.params.stakeholder.toHexString();
  let conditionId = event.params.conditionId.toHexString();
  let condition = Condition.load(conditionId) as Condition;
  // Assume half split of price if no trading at all.
  let outcomeTokenPrices = [0.5, 0.5];
  // const collateralToken = condition.collateralToken.toString();
  const collateralToken = event.params.collateralToken.toHexString();
  const outcomeSlotCount = condition.outcomeSlotCount as number;

  for (
    let outcomeIndex = 0;
    outcomeIndex < outcomeTokenPrices.length;
    outcomeIndex += 1
  ) {
    const market = getMarket(
      conditionalTokenAddress,
      conditionId,
      collateralToken,
      outcomeSlotCount,
      outcomeIndex,
    );

    // // Retrieve last traded price from exchange matching.
    let mktData = MarketData.load(market);
    if(mktData != null && mktData.priceOrderbook != null) {
      outcomeTokenPrices[outcomeIndex] = parseFloat(mktData.priceOrderbook.toString());
    }
    // if (mktData != null && mktData.priceOrderbook != null) {
    //   outcomeTokenPrices[outcomeIndex] = mktData.priceOrderbook;
    // }
    // let position = getMarketPosition(userAddress, market);
    // // Event emits the amount of collateral to be split as `amount`
    // position.quantityBought = position.quantityBought.plus(event.params.amount);

    // // Distribute split value proportionately based on share value(according to the Exchange)
    // let splitValue = timesBD(
    //   event.params.amount,
    //   outcomeTokenPrices[outcomeIndex],
    // );
    // position.valueBought = position.valueBought.plus(splitValue);
    // updateNetPositionAndSave(position);
  }
}

The compiler told me to comment line by line. I did it until it comes to if(mktData != null && mktData.priceOrderbook != null), the error appears. And I tried to move mktData != null  out, there is no error. So the error is caused by mktData.priceOrderbook != null. I dont know why

### AssemblyScript version

assemblyscript@0.19.10 and assemblyscript@0.19.23

**Comment by CountBleck** [comment]
It's likely caused by using `null` with the `==` overload, like in #2742 (the brief discussion was on Discord, sorry). We don't support 0.19.x though, since it's about a year old (and we're on 0.27.x now).

If you can replicate the issue with the latest version, then I can fix it.
