### ISSUE TITLE
Operator overload

### ISSUE THREAD

**Issue by HerrCai0907** [AssemblyScript/assemblyscript#2761]
`new A() == new B()` and `new B() == new A()` will call different operator overload functions if both A and B have overload function declarations.

It needs more clear rules to handle it.
In my opinion there are two solutions:
1. Diagnose when confused overload resolution.
2. Define priorities and do overload resolution according to priorities.

**Comment by CountBleck** [comment]
Number one seems more plausible, since a cast would fix it.
