### ISSUE TITLE
Returning Large ArrayBuffers and Typed Arrays from AssemblyScript is slow due to buffer copy

### ISSUE THREAD

**Issue by koush** [AssemblyScript/assemblyscript#2776]
### Question

The default behavior of the marshalling/binding is to "lift" (slice) the result from the WebAssembly.Memory region.

For example, in my web assembly blur function, this is the generated code:

```ts
      return __liftTypedArray(Uint8Array, exports.blurRGBOnce(buffer, width, height) >>> 0);
```

Where `__liftTypedArray` is defined as:

```ts
  function __liftTypedArray(constructor, pointer) {
    if (!pointer) return null;
    return new constructor(
      memory.buffer,
      __getU32(pointer + 4),
      __dataview.getUint32(pointer + 8, true) / constructor.BYTES_PER_ELEMENT
    ).slice();
  }
```

When processing 30fps video, this results in extremely large allocations and subsequently garbage collections. Running a CPU profile indicated 80% of the time was spent copying and in GC, and not in the actual blur function.

By creating and reading into ArrayBuffers in the heap via `__new`, and *also* returning the ArrayBuffer pointers via `changetype` I can use the web assembly memory directly without a copy. I understand that this Memory instance may become invalid if `grow` is called, but that's something I am consciously managing. 

My question: Is there a way to generate the TypedArray marshalling to operate in an unsafe mode so these excessive alloc/gc/copy can be avoided, as I am doing manually right now? I did not see anything in the docs related to this.

**Comment by lortonx** [comment]
Use pointers instead of buffers. And on the host side, work with memory directly. This way you will achieve zero copies of binary data arrays.

So I developed a game server that transmits large game packets to the host, passing only a pointer and the length of the array.

Also, I'm not sure if this will help you, maybe there are ways to pass arrays in a simpler way.

Sorry for the short answer

**Comment by koush** [comment]
Yep, that’s what I’m doing. What I’m wondering is if there’s a way to generate unsafe zero copy bindings that reference the heap, and if not, I can add it.
