### ISSUE TITLE
Comparision with constant can't compile when constant is left operand

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#279]
```ts
export function test(x: i32): bool {
  return 0 < x;
}
```
Error: `ERROR TS2365: Operator '<' cannot be applied to types 'bool' and 'i32'.`

But this works:
```ts
export function test(x: i32): bool {
  return x > 0;
}
```

**Comment by dcodeIO** [comment]
Category: Faszinating that this hasn't surfaced earlier :) Seems to prefer the contextual type over the larger rhs type.

**Comment by MaxGraey** [comment]
May be, because negative values works:
```ts
export function test(x: i32): bool {
  return -1 < x; // ok, but not `1`
}
```

**Comment by dcodeIO** [comment]
The issue there is with signedness it appears (`bool` is unsigned). The same happens with `i32` and `u32`.

**Comment by dcodeIO** [comment]
Have this fixed locally by allowing assignments of bool values to all sorts of integers, which should be safe. Hence, the LHS of your first snippet becomes an `i32` before comparison.
