### ISSUE TITLE
Blazor Web App (Server) .NET8.0 call Web API with MVC

### ISSUE THREAD

**Issue by chongzc123** [AssemblyScript/assemblyscript#2809]
### Question

Hello Guys,
My project's objective is to create own API Endpoint to call third-party API Endpoint and then perform CRUD operations.
The flow is like users press button and call specified API Endpoint and then call third-party API Endpoint to perform CRUD Operations such as create, delete, read and so on.
Now I am facing a problem is there are no output being displayed in my project when I click the button.
Will be very appreciate if anyone can provide me the guildeline and tutorial. Thank you.

**Comment by CountBleck** [comment]
Are you opening an issue on the right project?
