### ISSUE TITLE
crash when shifting BigInt

### ISSUE THREAD

**Issue by johannbarbie** [AssemblyScript/assemblyscript#2828]
### Bug description

compiler crashes when trying to compile code

### Steps to reproduce

code:
```
function testBigIntOperations(): void {
  let value: BigInt = BigInt.fromI32(1);
  // Test each operation individually
  let shifted: BigInt = value >> BigInt.fromI32(8);
  let anded: BigInt = value & BigInt.fromI32(0xFF);
}
```

### AssemblyScript version

v0.19.23

**Comment by CountBleck** [comment]
It looks like `BigInt`, if it existed in prior versions, has been removed from the current version of AS, and we don't backport fixes.
