### ISSUE TITLE
Reset the bump allocator?

### ISSUE THREAD

**Issue by tareksander** [AssemblyScript/assemblyscript#2843]
### Question

I don't expect my modules to allocate much dynamic memory, if any, but I'd like to reset it between runs (so I don't have to create a new memory each time). Is this possible?

**Comment by dcodeIO** [comment]
There is [`heap.reset()`](https://www.assemblyscript.org/stdlib/heap.html#static-members) when using the stub runtime. Must make sure that there aren't any pointers into then-zeroed memory, of course, say in globals, perhaps initialized during `start`.
