### ISSUE TITLE
Correct usage of "this" in assemblyscript

### ISSUE THREAD

**Issue by johnhill396** [AssemblyScript/assemblyscript#2849]
### Question

I'm working on an AssemblyScript application. The way the code is structured requires passing an instance of a class in the constructor of another class. For example:
```
class Something {

  constructor(private context: MyContext) { }

  testMethod(): void {
    //Some logic which uses variables and methods from context class  
    let a: this.context.getSomething();
  }
}

class MyContext {
  
  //Is below a correct usage of 'this'?
  somethingObj: Something = new Something(this);

  myMethod(): void {
    //Some logic which uses somethingObj
    this.somethingObj.testMethod()
  }
  
}
```
I'm able to build and run the code successfully. But, is the above field somethingObj in MyContext class correctly using 'this' keyword? Could this somehow lead to some runtime errors around out of bounds memory access?

**Comment by CountBleck** [comment]
I'm pretty sure this is okay.

**Comment by HerrCai0907** [comment]
It is ok. But you should note that `this` is not initialized at this moment.

**Comment by johnhill396** [comment]
> It is ok. But you should note that `this` is not initialized at this moment.

yeah, that's what I was worried about. Could that cause any issues at runtime? Any best practices around it?

**Comment by MaxGraey** [comment]
You can just use this as alterative:
```ts
class MyContext {
  somethingObj: Something!; // use exclamation mark

  myMethod(): void {
    this.somethingObj = new Something(this)
    this.somethingObj.testMethod()
  }
}

```
