### ISSUE TITLE
Namespaces issues after compilation to webassembly module 

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [AssemblyScript/assemblyscript#285]
Below code

```typescript
export declare namespace Draw {
  export function point(x: i32, y: i32): void;
  export function line(x1: i32, y1: i32, x2: i32, y2: i32): void;

  namespace shape {
    export function triangle(x1: i32, y1: i32, x2: i32, y2: i32, x3: i32, y3: i32): void;
  }
}

export function __test(v: i32): void {
  Draw.shape.triangle(v, v, v, v, v, v);
}
```

will produce webassembly that requires:
```javascript
[ { module: 'env', name: 'abort', kind: 'function' },
  { module: 'Draw', name: 'point', kind: 'function' },
  { module: 'Draw', name: 'line', kind: 'function' },
  { module: 'shape', name: 'triangle', kind: 'function' } ] // <--- NOTE HERE a problem
```
would expect something like that:

```javascript
{ module: 'Draw', name: 'shape.triangle', kind: 'function' }
```

and exports:

```javascript
[ { name: 'memory', kind: 'memory' },
  { name: 'Draw.point', kind: 'function' },
  { name: 'Draw.line', kind: 'function' }, 
                      // <--- MISSING Draw.shape.triangle
  { name: '__test', kind: 'function' }]
```

**Comment by dcodeIO** [comment]
Currently it uses the inner most namespace as the imported module name, yeah, but it makes sense to change it to the way you propose whenever the outer namespace is already exported.

Regarding the export, that might be because the inner namespace isn't `export`ed from the parent namespace.

**Comment by DanielMazurkiewicz** [comment]
> Regarding the export, that might be because the inner namespace isn't exported from the parent namespace.

indeed, that was an issue

**Comment by dcodeIO** [comment]
As a solution to the namespace issue, I am currently thinking about changing the default behavior to be the following:

* The imported module name is the file name without extension by default.
* The imported element name is the internal name of the element.

Hence, if there was a file `env.ts` with the following contents

```ts
declare function doSomething(): void;
declare namespace do {
  function something(): void;
}
```

that'd result in the imports

* **env** , **doSomething** and
* **env** , **do.something**

unless the `@external` decorator is used which allows overriding the element name if one parameter is specified, or both the module and element name if two parameters are specified.

Wdyt?

**Comment by DanielMazurkiewicz** [comment]
That sounds like a good solution - sort of standardization of imports and exports while keeping imports flexibility with @external. I like it!
