### ISSUE TITLE
ECMAScript compatibility

### ISSUE THREAD

**Issue by alveko** [AssemblyScript/assemblyscript#286]
What subset of the ECMAScript language spec is currently supported?

For example, some methods of String are missing such as match, replace, search, toLower, toUpper, etc, and some have different names like trimEnd/Start vs trimLeft/Right.

Is the there a doc or table listing what's currently supported and what's not?

Why some pieces are missing, is it just "to be implemented" or "never to be implemented"?

Thanks!

**Comment by MaxGraey** [comment]
At the moment we are trying to follow the same specification as TypeScript and as far as I know the latter is in turn based on ECMAScript 6 and ECMAScript 2015. However AssemblyScript is AOT without `any`, `undefined` and other dynamic behaviours so it has some limitations in that scope.

Methods like `match`, `replace` and `search` required regexps which not yet implemented.
`trimEnd/Start` should rename to `trimLeft/Right` that's good catch.

**Comment by dcodeIO** [comment]
In a nutshell: We are trying to stick to the relevant standards as much as possible unless a feature cannot be implemented efficiently (yet), which is the case with some super dynamic language features of JS and language constructs that rely on GC support. Everything else is most likely TODO.

**Comment by alveko** [comment]
What's in the todo list? Such list in one simple doc would help one assess how mature the project is and how much is remaining.

BTW, really interesting project!  Who and where is using it as of now?

**Comment by MaxGraey** [comment]
> What's in the todo list? 
Currently new website with documentation work in progresss. Some general info you could find [in wiki](https://github.com/AssemblyScript/assemblyscript/wiki/Status-and-Roadmap)

>  Who and where is using it as of now?
There are not too many ready-made projects for this project. Here are some of them:
- [wasmBoy - A WebAssembly Gameboy Emulator](https://github.com/torch2424/wasmBoy)
- [xoroshiro128starstar - An AssemblyScript port of xoroshiro128starstar.c](https://github.com/krisselden/xoroshiro128starstar)
- [bignum.wasm](Fixed length big numbers like u128, i256, fp128 and etc for AssemblyScript)
- couple of blockchain projects choose AssemblyScript as prime or experimental language for its smart contracts
   1. [eWasm (Ethereum 2.0)](https://twitter.com/ethereumecf/status/1044977387635642368)
   2. [EOS.io](https://github.com/EOSArgentina/gameoflife-ts)
   3. [Holochain](https://github.com/holochain/hdk-assemblyscript)
   4. [GraphProtocol](https://github.com/graphprotocol/graph-cli)
   and others

**Comment by dcodeIO** [comment]
Regarding feature support, if someone wants to make a list, it should be sufficient to click through the files in [std/assembly](https://github.com/AssemblyScript/assemblyscript/tree/master/std/assembly) to get an overview of what's implemented and what's not.

**Comment by MaxGraey** [comment]
Now we have current status for standard built-in objects:  
https://github.com/AssemblyScript/assemblyscript/wiki/Status-and-Roadmap
