### ISSUE TITLE
It looks like it doesn’t support iOS14?

### ISSUE THREAD

**Issue by yoyo837** [AssemblyScript/assemblyscript#2871]
### Question

`WebAssembly.validate(buffer)` On iOS 14 this returns `false`.

<img width="523" alt="image" src="https://github.com/user-attachments/assets/3ae30f09-24f4-422c-8760-395ddd7aa0bb">

**Comment by HerrCai0907** [comment]
The reason is bulkmemory, sign extensions, (maybe also no-traping-floating-conversion). 
Please use `--disable-sign-extension --disable-nontrapping-f2i --disable-bulk-memory` to disable this wasm2.0 feature.

**Comment by yoyo837** [comment]
Thanks for your reply, I did it using `options.disable` in the `asconfig.json` configuration file.
