### ISSUE TITLE
Where do I find documentation on the compilation process?

### ISSUE THREAD

**Issue by michele-nuzzi** [AssemblyScript/assemblyscript#2882]
### Question

Hi I would love to learn more about the compilation process of assemblyscript.

So far was able to understand how the Tokenizer and the Parser work together, and I'm able to get the AST of simple programs.

But from here I'm stuck. How does the AST get compiled to IR? ideally I would like to extract the IR out of the process.

And from there I would also love to understand how the Compiler goes from the IR to a module and finally emit the result.

I would love to learn more and potentially contribute to the project once comfortable enough, but can't find any documentation on these low level parts.

**Comment by CountBleck** [comment]
The "IR" in `program.ts`​ is a representation of the types, functions, variables, classes, etc. in each file, but there isn't an intermediate representation for *actual code* between the AST and the Wasm output. The AST representing statements and expressions ends up being compiled directly to Wasm, as you can see in `compiler.ts​` and every `compileXXXX`​ method.
