### ISSUE TITLE
Heap allocation results in a crash in GC or the guest function call hanging

### ISSUE THREAD

**Issue by epsylonix** [AssemblyScript/assemblyscript#2886]
### Bug description

I've encountered an issue when a guest-exported function that does any runtime heap allocations either crashes in GC or call hangs forever. The guest is called from a Wasmtime-go runtime v25.0.0 embedded into a Go service and guest compiled to Wasm with `AssemblyScript v0.27.30` and `@assemblyscript/wasi-shim` v0.1.0. 

### Steps to reproduce

Here is how the module is compiled:
```
npx asc assembly/index.ts --runtime=incremental --exportRuntime --maximumMemory=8000 -O --noAssert
```

I've experimented with different values for `--maximumMemory` and `--initialMemory` but it doesn't seem to make any difference. More details on `--noAssert` option below.

Here is the minimal example that reproduces the issue:

```TypeScript
export function allocate_array(): void {
  let buffer = new Uint8Array(957);
}
```

Using `wasm2wat` I can see the compiler doesn't optimize away the unused variable.

When a `956` number is used in the function above with `--noAssert` compiler option used, the guest-function call completes immediately and many calls in a loop show the linear memory doesn't grow so I suppose the GC is collecting the allocated data successfully. However incrementing  it by 1 to `957` results in the call hanging.

Initially I assumed that it might be hitting the max memory limit but increasing the number significantly results in an immediate crash with `unreached` instruction reached so it looks like if it was the memory limit issue it wouldn't freeze but would crash instead. 

`Wasmtime` supports configuring `fuel` consumption for a guest so I found the specific value where several thousand sequential calls with array size set to `956` do not run out of fuel (`store.SetFuel(1000000000)`) then when I increase the array size by 1 to `957` the first call completes immediately but the second one results in all fuel being consumed after a couple of seconds. When the the fuel limit is increased 50 times (`store.SetFuel(50000000000)`), it fails after running for about 10 seconds with the fuel limit reached. So my guess is that it doesn't block but is actively doing something and it takes forever.

I found that removing `--noAssert` fails immediately in GC with `abort:  in ~lib/rt/itcms.ts(160:16)` and it turns out any runtime allocation, e.g. `new Uint8Array(1)`, results in the crash in the same place unless `--noAssert` is used.

Here is Wasmtime config used for the reference:
```go
wasiConfig := wasmtime.NewWasiConfig()

wasiConfig.InheritStdout()
wasiConfig.InheritStderr()

wasmtimeConfig := wasmtime.NewConfig()
defer wasmtimeConfig.Close()
engine := wasmtime.NewEngineWithConfig(wasmtimeConfig)

store := wasmtime.NewStore(engine)
store.SetWasi(wasiConfig)

linker := wasmtime.NewLinker(engine)
err := linker.DefineWasi()
if err != nil {
	panic(err)
}

module, err := wasmtime.NewModuleFromFile(engine, wasmPath)
if err != nil {
	panic(err)
}

instance, err := linker.Instantiate(store, module)
if err != nil {
	panic(err)
}

allocateArray := instance.GetExport(store, "allocate_array").Func()
for range 1000 {
	_, err := allocateArray.Call(store)
	if err != nil {
		panic(err)
	}
}
```
Exactly the same config used for a guest implemented in Go runs successfully so it looks like this is not caused by some limits on the Wasmtime configuration side.
Also I would like to note that calling `__alloc` and `__free` from the host works without issues.

Can it be a misconfiguration issue? Could you please advise me on how to debug it further?

### AssemblyScript version

v0.27.30

**Comment by epsylonix** [comment]
It's difficult to test this without `wasi-shim` because out of the box `AssemblyScript` compiles Wasm modules that require Web APIs to be exported by the host and this they are not provided by most embeddable Wasm runtimes.

**Comment by CountBleck** [comment]
I can repro this with Node.js's WASI (uvwasi), but it appears this is a bug with your code:

```js
import {readFileSync} from "node:fs"
import {WASI} from "node:wasi"

const wasi = new WASI({version: "preview1"})
const {instance} = await WebAssembly.instantiate(
    readFileSync("./bleh.wasm"),
    wasi.getImportObject()
)
const {memory, allocate_array} = instance.exports

console.log("Starting...", memory.buffer)
// wasi.start(instance)
// for (let i = 0; i < 1e5; i++) allocate_array()
allocate_array()
console.log("Called once")
allocate_array()
console.log("Done!", memory.buffer)
```

I get the same behavior as you *if I don't call `wasi.start()`* (i.e. the `_start` export).

This means you probably forgot to call the `_start` export in your code.

**Comment by epsylonix** [comment]
Thank you for looking into it! Yes, indeed, this was the case. 

My assumption was that while `_start` is exported by default, any exported function can be called by the host instead. There is no direct equivalent of `wasi.start(instance)` in Wasmtime and apparently it doesn't call it by default on `#Instantiate(...)`. 

Looking at the WASI spec the only mention of the `_start` function I found is this one https://github.com/WebAssembly/WASI/blob/8ba6586166291d507411e0ba027560a88f7a79e1/legacy/application-abi.md?plain=1#L20-L23:

> `_start` is the default export which is called when the user doesn't select a
>   specific function to call. Commands may also export additional functions,
>   (similar to "multi-call" executables), which may be explicitly selected by the
>   user to run instead.

Is it specified anywhere that before calling any function in the guest, the `_start` function has to be called first? It would be great if this were documented somewhere.

As far as I can tell the spec also defines the `start` section which is called automatically when the module is instantiated. I'm new to Wasm so excuse me if this is a stupid question but why AssemblyScript compiler doesn't put the intialization code there instead of putting it into `_start`?

Thank you!

**Comment by CountBleck** [comment]
wasi-shim explicitly puts all initialization code in `_start` because (to my knowledge) that's what we're supposed to use for WASI.

I don't think WASI runtimes generally like the start section being used. In fact (I ran into this while looking into your code), uvwasi errors when a WASI import is called before calling `wasi.start(instance)`. That same scenario would occur if top-level code calling WASI APIs is placed in the start section and not `_start`.

I remember there being discussion about this in the WebAssembly org somewhere, but [this](https://github.com/WebAssembly/tool-conventions/blob/main/BasicModuleABI.md) talks about `_initialize`, which IIRC is the default export of a WASI "reactor".

**Comment by epsylonix** [comment]
Ok, thank you for the explanation!
