### ISSUE TITLE
Weird Importing Bug I found on WasmBoy

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#29]
Hello!

So here is that weird importing bug I found. So I [made a branch](https://github.com/torch2424/wasmBoy/tree/weird-import-bug) with an [exact commit](8cd492f0ec1b8c96d45466adf0a9d0f42fff4bd6) on [WasmBoy](https://github.com/torch2424/wasmBoy) where I noticed that I am exporting a function from a file (`wasm/memory/index.ts`) from another file (`wasm/memory/load.ts`) that exports said function. I then tried to import the function into another random file (`wasm/graphics/graphics.ts`), and I get the following error:

![screen shot 2018-02-15 at 8 11 50 pm](https://user-images.githubusercontent.com/1448289/36293220-7b833232-128c-11e8-89f7-650632fc055a.png)

I have no clue what is causing this, but as you mentioned you don't mind looking into it :) Thanks for the help, and sorry if it is something dumb on my end haha!

**Comment by dcodeIO** [comment]
Thanks a lot! With the fix above the wasm build should now work in that branch.

**Comment by torch2424** [comment]
The fix totally worked!

![screen shot 2018-02-16 at 3 12 40 am](https://user-images.githubusercontent.com/1448289/36305171-51c16636-12c7-11e8-9455-bd23e71fe2f4.png)
![screen shot 2018-02-16 at 3 12 33 am](https://user-images.githubusercontent.com/1448289/36305175-54d16c54-12c7-11e8-8211-b5b44cd077da.png)

Thanks! That was super quick :)

And of course please do! I'd actually really appreciate it! it's far from done / shippable, there's still a lot to do, but it is coming together! :) I've been advocating for Assemblyscript with a few developer friends recently if I may say haha!

I also found one last REALLY weird bug. And it has to do with memory, so I opened an issue at #30, but feel free to close it if you are certain it's not on your end (it probably isn't)
