### ISSUE TITLE
add "assembly script" assembly script tags

### ISSUE THREAD

**Issue by pannous** [AssemblyScript/assemblyscript#290]

**Comment by MaxGraey** [comment]
What do mean?

**Comment by pannous** [comment]
if you search gh for "Assembly Script" AssemblyScript isn't found, because tags are missing

**Comment by pannous** [comment]
https://github.com/search?q=Assembly%20Script

**Comment by dcodeIO** [comment]
Thanks, [finds it now](https://github.com/search?q=Assembly%20Script).
