### ISSUE TITLE
assemblyscript loader needs adapation (chrome)

### ISSUE THREAD

**Issue by t57ser** [AssemblyScript/assemblyscript#295]
Chrome limits the use of WebAssembly.Instance to files <= 4KB
I had to copy and adapt the assemblyscript loader to be able to use it correctly.

This issue has also been mentioned here: https://github.com/AssemblyScript/assemblyscript/issues/240

From the current docs:
> 
> // From a module provided as a buffer, i.e. as returned by fs.readFileSync
> const myModule = loader.instatiateBuffer(fs.readFileSync("myModule.wasm"), myImports);
> 
> // From a response object, i.e. as returned by window.fetch
> const myModule = await loader.instantiateStreaming(fetch("myModule.wasm"), myImports);
> 

Note that although instantiateStreaming is a promise, the underlying implementation still calls the "instantiate" function which calls WebAssembly.Instance

My proposal would be to change all exposed loader instantiate functions to async and replace the underlying instantiate function to use:
`
var instance = await WebAssembly.instantiate(module, imports);
`
### Note:
This change would break the current docs and loader.

**Comment by dcodeIO** [comment]
Yeah, I think we'll need to fix this. It's just the way it is because it was easier to share code between the synchronous and asynchronous APIs, but there might be other ways to achieve the same.

**Comment by dcodeIO** [comment]
Please let me know if this fixes it for you :)

**Comment by t57ser** [comment]
This is what I get when using `loader.instantiateStreaming`
```
TypeError: Cannot read property 'memory' of undefined
    at postInstantiate (index.js:43)
    at Object.instantiateStreaming (index.js:189)
```
I tried to adapt the code to see where the issue might be.
First step:
```
async function instantiateStreaming(response, imports) {
	const a = await WebAssembly.instantiateStreaming(response, imports);
	console.log(a);
  return postInstantiate(
    preInstantiate(imports || (imports = {})),
    a
  );
}
```
I moved the await outside of the return to see what the result was.
I got a new error before I could continue:
```
LinkError: WebAssembly Instantiation: Import #0 module="env" function="abort" error: function import requires a callable
```
This got solved by adding:
```
env: {
	memory: new WebAssembly.Memory({ initial: 1 }),
	abort: () => null,
},
```
Apparently the abort function is required?

The result is the following:
`{instance: Instance, module: Module}`
Meaning that the instance passed to `postInstantiate` is actually supposed to be a.instance.

Chrome version: 69.0.3497.100 (Official Build) (64-bit)
I hope that helps

**Comment by t57ser** [comment]
The way I solved it for my project was:

```
async function instantiateBuffer(buffer, imports) {
  var module = new WebAssembly.Module(buffer);
  return await instantiate(module, imports);
}
exports.instantiateBuffer = instantiateBuffer;

async function instantiateStreaming(response, imports) {
  var module = await WebAssembly.compileStreaming(response);
  return await instantiate(module, imports);
}
exports.instantiateStreaming = instantiateStreaming;
```
I made the instantiate and co async and only changed the instance:
```
async function instantiate(module, imports) {
...
// Instantiate the module and obtain its (flat) exports
  var instance = await WebAssembly.instantiate(module, imports);
```

**Comment by dcodeIO** [comment]
I see, yeah, I forgot about `a.instance` there. Does it work now? :)

**Comment by t57ser** [comment]
Yes, it appears to work now. Thanks.
