### ISSUE TITLE
Support type inference?

### ISSUE THREAD

**Issue by dtysky** [AssemblyScript/assemblyscript#3]
Hi.

In current time we know that typescript has a great ability to do type inference and we benefit a lot from it, etc:

```ts
export function test(i: number) {
    return i++;
}
```

Typescript will know that the result of `test` is `number`.

Lot of my projects are all strictly typed using type inference, but not explicit declaration, they could not pass your type checking.

Not only the typescript, c++, c#, and many modern languages are supporting type inference, and they could be compiled to wasm now or future. So could `asc` support it?

Thanks.

**Comment by dcodeIO** [comment]
Sure. There is [limited](https://github.com/AssemblyScript/assemblyscript/wiki/Limitations#limited-type-inference) type inference for variable declarations with an initializer already.

**Comment by dcodeIO** [comment]
Thanks, now covered by: https://github.com/AssemblyScript/assemblyscript/issues/61

**Comment by jarble** [comment]
I wish the AssemblyScript compiler were capable of generating type annotations for functions that did not include them. But this might require a run-time type-checking tool, like Python's [MonkeyType](https://github.com/Instagram/MonkeyType).

**Comment by jarble** [comment]
It is also possible to infer parameter types and return types at runtime using the v8 JavaScript engine's [type profiler](https://medium.com/fhinkel/runtime-type-information-for-javascript-b134faac3c0a).
