### ISSUE TITLE
Random Indexes of Memory get Cleared

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#30]
Hello!

So I am not entirely sure if this is on [my end](https://github.com/torch2424/wasmBoy) or yours, even more unsure than #29 , but I'm really stumped on the issue.

So, If I noticed that pieces of memory I have in my wasm memory `this.wasmByteMemory = new Uint8Array(this.wasmInstance.exports.memory.buffer)`, will get reset back to zero.

Like for example, if I'm expecting values in 0xF9A0, 0xF9A1, 0xF9A2, 0xF9A3. Everything will be fine in the game and then randomly, one of the indexes, `0xF9A0` will be cleared. And here's the scary part, I put listeners  with a little wasm "consoleLog" I whipped up in front of all of my `store<u8>()` and `store<u16>()` calls, and nothing is written at the address, or near the address to clear the data back to zero.

After spending a few hours on this, and realizing I don't have a deep understanding of how wasm memory works, I thought it may be a variable overflowing into the memory buffer itself? It seems highly unlikely, and again it may be on my end. Sometimes it happens when an event happens in the game, and sometimes it doesn't 🤔 

Anyways, if you need more context let me know, and thanks again for all of the help!

EDIT: I thought of more context, you can relate too haha! On tetris, whenever you clear a line, the side brick borders, will replace themself with a 0 zero tile. Like what's up with that? haha!

**Comment by dcodeIO** [comment]
> Like for example, if I'm expecting values in 0xF9A0, 0xF9A1, 0xF9A2, 0xF9A3. Everything will be fine in the game and then randomly, one of the indexes, 0xF9A0 will be cleared

One thing that comes to my mind is that a larger store could causes this, like for example the high 8 bits of a `store<u16>` also setting the 8 bits of the adjacent `u8` to zero. If so, that could either be a compiler bug emitting the wrong-sized instruction, or (here) an actual `store<u16>` where it should be a `store<u8>`.

**Comment by dcodeIO** [comment]
Appears the game over screen also triggers quite a few heisenberg zeroes:

![zeroes](https://user-images.githubusercontent.com/1136893/36315055-013b47d4-1337-11e8-8450-b3f9239bc706.jpg)

**Comment by torch2424** [comment]
Yeah exactly! I checked the sixteen bit stores with the same idea as you. But mostly, I was asking becuase I thought the wasn't itself could possibly overflow into it's own memory? But I guess not. If that is not the case, then I'll go ahead and close this, because I had a feeling it is something weird on my end haha! Thank you!
