### ISSUE TITLE
[Question] Try catch support

### ISSUE THREAD

**Issue by t57ser** [AssemblyScript/assemblyscript#302]
Is there any support for using try/catch in AS?
Currently the compiler says "Operation not supported".
I've found this old issue: https://github.com/AssemblyScript/prototype/issues/103
Though when looking at the webassembly link: https://github.com/WebAssembly/exception-handling/blob/master/proposals/Exceptions.md
it is talking about try/catch blocks. What's the state for it in Assemblyscript?

**Comment by t57ser** [comment]
Thanks for the clarification :)

**Comment by bowenwang1996** [comment]
Does that mean we cannot detect whether an exception occurred? For example, if I want to write a test and assert that an exception has occurred, is there anyway to do that?

**Comment by MaxGraey** [comment]
You could throw exceptions but can't catch or rethrow it currently. Current WebAssembly MVP cupport only global traps but [this feature extension](https://github.com/WebAssembly/exception-handling/blob/master/proposals/Exceptions.md) will allow support fully featured try/catch/finally in near future

**Comment by dcodeIO** [comment]
Background: Doing `throw new Error("something")` currently compiles to an `unreachable` instruction that cannot be safely recovered from. You can catch an `unreachable` on the JS side of course, but it's not safe because the internal state might be broken as soon as that occurs. Or, short: Don't use exceptions yet.

**Comment by bowenwang1996** [comment]
I see. So what's the recommended way of handling non-fatal exceptions?

**Comment by dcodeIO** [comment]
So far I've used return values to indicate the outcome of an operation that might fail. Fanciest one can do probably is

```ts
enum Status {
  OK,
  ERROR_A,
  ERROR_B
}

function doSomething(): Status {
  ...
}
```

**Comment by MaxGraey** [comment]
Languages like Go and Rust havan't support exceptions and usually use Optional types or tuples / objects during return result. You could follow same approack like:
```ts
function parseArray<T>(str: string): T[] | null {
   if (isValid(str)) return parseArr(str)
   return null;
}

// or
class Result<T> {
   value: T | null = null;
   error: string | null = null;
}

function getRequestResult(url: string): Result {
    let body = ...
    if (body == null) {
      return { value: null, error: "can't request from url" };
    } else {
      return { value: body, error: null };
    }
}
```

**Comment by thebakersteve** [comment]
> Unfortunately, the exception-handling spec hasn't landed yet and we are waiting for it as well. What AS does currently is converting `throw` statements to a an `abort(...); unreachable();` (simply put), which cannot be caught.

It's so funny that I'm stuck because the language doesn't have the most basic exception handling. Do you get that? your language can't do try-catch..why work on anything else other than this?

**Comment by fucksophie** [comment]
Reopen this issue, there's still no try/catch support.

**Comment by mattjohnsonpint** [comment]
Essentially, `throw` in AssemblyScript is not at all like `throw` in TypeScript or JavaScript. It's more like `panic` on Go, and there is no equivalent of Go's  `recover`.
