### ISSUE TITLE
TypeScript compatibility

### ISSUE THREAD

**Issue by alveko** [AssemblyScript/assemblyscript#305]
What's currently supported and what's not in terms of the TypeScript spec, see [1]?\
It's understood that the dynamic features are not there. What about the rest?

Based on other issues, nested object initialization is not currently supported.
I also get issues with ```interface```, see [2].

[1] https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md
[2] a simple ts file
```
export interface xevent {
    x: i32;
}

export function foo(e: xevent): xevent {
    return e;
}
```
leads to
```
ERROR TS2304: Cannot find name 'xevent'.

 export function handle(e: xevent): xevent {
                           ~~~~~~
 in dummy.ts(5,26)

ERROR: Compile error
    at Error (native)
    at Object.main (/wp/assemblyscript/cli/asc.js:472:21)
    at Object.<anonymous> (/wp/assemblyscript/bin/asc:3:60)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
```

**Comment by MaxGraey** [comment]
Casting interface to object not support yet. Currently you can use `class` instead `interface` for that stuff.
```ts
export class xevent {
  x: i32;
}

export function foo(e: xevent): xevent {
  return e;
}
```

**Comment by alveko** [comment]
Where/when does the casting happen in this example?

**Comment by dcodeIO** [comment]
Regarding interfaces: While we have a custom GC now, it's not yet fully functional and lacks some properties that'd be necessary to properly support interfaces, like virtual lookup tables and runtime class ids on instances. While this can be done, I'd favor implementing higher level features on top of the proposed higher level specs once these land (no ETA on the GC spec yet), just because improving the custom GC is a lot of work and it's likely that it'll be thrown away again later anyway.

**Comment by MaxGraey** [comment]
Yes, for interfaces like that:
```ts
interface IFoo {
    boo(): i32;
}
```
with methods this required vtable. But for interfaces which just declare objects without methods like
```ts
interface IFoo {
   x: i32;
   s: string;
   f: f64;
}
```
Implementation could much trivial for declare objects.

**Comment by sqykly** [comment]
Does this affect `abstract` classes and overrides as well?  That's a pretty severe limitation.  Surely the C++ and Java implementations have this worked out; is there a reason this is harder with TypeScript than those other languages, or should I stroll over to their source code and bring back a working example to model yours after?
