### ISSUE TITLE
Minor fixes to CheatSheet docs

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#31]
In [this wiki page](https://github.com/AssemblyScript/assemblyscript/wiki/WebAssembly-to-TypeScript-Cheat-Sheet):

Instead:

```
i32.rotl | rotl<i32>(value)
i32.rotr | rotr<i32>(value)
```

Should be probably this:

```
i32.rotl | rotl<i32>(value, shift)
i32.rotr | rotr<i32>(value, shift)
```

**Comment by dcodeIO** [comment]
Oh, right, thanks!

**Comment by jpryne** [comment]
Can these instructions be expressed by AssemblyScript? If not, I'd like to propose an extension, one comprised of additional commands that can be called from AssemblyScript & will compile to the corresponding WASM instructions. For example:

```javascript
export function rotateLeft(x: i32, y: i32): i32 {
  return rotr(x,y);
}
```
would compile to:

```wasm
  (func $main/rotateLeft (export "rotateLeft") (type $t1) (param $p0 i32) (param $p1 i32) (result i32)
    get_local $p0
    get_local $p1
    i32.rotr)
```

Happy to work on this, provided I can ask questions about implementation.  Move to new issue?
