### ISSUE TITLE
Error parsing the wast text and optimized the wast failed

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#310]
[AssemblyScript code](https://webassembly.studio/?f=mryyivlz6xk)

It's wast result
```
(module
 (type $v (func))
 (type $iiiiv (func (param i32 i32 i32 i32)))
 (memory $0 1 65535)
 (data (i32.const 8) "\07\00\00\00m\00a\00i\00n\00.\00t\00s")
 (table 1 anyfunc)
 (elem (i32.const 0) $null)
 (import "env" "abort" (func $~lib/env/abort (param i32 i32 i32 i32)))
 (export "memory" (memory $0))
 (export "table" (table $0))
 (export "testBreak" (func $main/testBreak))
 (start $start)
 (func $main/testBreak (; 1 ;) (; has Stack IR ;) (type $v)
  (local $0 i32)
  (local $1 i32)
  ;;@ main.ts:4:8
  (block $break|0
   (loop $repeat|0
    (br_if $break|0
     ;;@ main.ts:4:28
     (i32.ge_s
      (get_local $0)
      ;;@ main.ts:4:34
      (i32.const 32)
     )
    )
    (set_local $1
     ;;@ main.ts:5:12
     (if (result i32)
      ;;@ main.ts:5:16
      (i32.eq
       (get_local $0)
       ;;@ main.ts:5:23
       (i32.const 12)
      )
      ;;@ main.ts:6:23
      (i32.add
       (get_local $0)
       ;;@ main.ts:6:29
       (i32.const 32)
      )
      (block
       ;;@ main.ts:4:38
       (set_local $0
        (i32.add
         (get_local $0)
         (i32.const 1)
        )
       )
       (br $repeat|0)
      )
     )
    )
   )
  )
  ;;@ main.ts:10:8
  (if
   ;;@ main.ts:10:15
   (i32.ne
    (get_local $1)
    ;;@ main.ts:10:23
    (i32.const 44)
   )
   (block
    (call $~lib/env/abort
     (i32.const 0)
     (i32.const 8)
     (i32.const 10)
     (i32.const 8)
    )
    (unreachable)
   )
  )
 )
 (func $start (; 2 ;) (; has Stack IR ;) (type $v)
  ;;@ main.ts:13:4
  (call $main/testBreak)
 )
 (func $null (; 3 ;) (; has Stack IR ;) (type $v)
  (nop)
 )
)
```

[Than I transfered the code to wasm.](https://webassembly.studio/?f=0ir2ldoaig2)
I got a error. (A)

![image](https://user-images.githubusercontent.com/4305499/47702730-d2ff9c80-dc58-11e8-8598-8f859e5b0ede.png)

```
test.wat:8:3: error: imports must occur before all non-import definitions
```

[So I changed the location of `imports`;](https://webassembly.studio/?f=syfj1ibxe9o)Then I got the below error. (B)

```
test.wat:10:25: error: undefined table variable "$0"
 (export "table" (table $0))
```

[So I removed the `export table`.](https://webassembly.studio/?f=v8z9930q98a) I got the below error.(C)

```
test.wat:49:9: error: type mismatch in if false branch, expected [i32] but got []
       (br $repeat|0)
```

The error A and error B are new exceptions.  I think it related the wast spec.
The error C is related the issue number [179](https://github.com/AssemblyScript/assemblyscript/issues/179)

**Comment by dcodeIO** [comment]
Looks like Binaryen's .wat output can't be processed by what WebAssembly Studio is using to compile .wat files anymore, presumably WABT. @kripken ?

**Comment by MaxGraey** [comment]
binaryen.js and wat.js which used in WebAssembly Studio is pretty old now. Need update them

**Comment by kripken** [comment]
A fix for the import order is in https://github.com/WebAssembly/binaryen/pull/1715

I'm less sure about the `undefined table variable` error, which is the next to appear after fixing the imports.  @binji , the situation is this:
```
 (table 1 anyfunc)
 (export "table" (table $0))
```
The table is named in the export, using the implicit name which is not given before. That works for functions, I'd guess it should work for tables too, could this be a wabt bug?

**Comment by dcodeIO** [comment]
For reference, the original if-block before optimizations looks like the following, so the type mismatch happened during optimization passes I think.

```wat
    (if
     (i32.eq
      (get_local $1)
      (i32.const 12)
     )
     (block
      (set_local $0
       (i32.add
        (get_local $1)
        (i32.const 32)
       )
      )
      (br $break|0)
     )
    )
```

**Comment by kripken** [comment]
Thanks @binji - I misread `$0` as `0`, oops :) yeah, that's a binaryen printing bug. Fixed in the same PR, we just were not printing the table name.

**Comment by kripken** [comment]
The `if` issue is because binaryen has an `unreachable` type, which is used for one arm of that `if`, while wasm does not have that type.

To get wasm text that is valid wasm wat, you can replace `--print` with `--generate-stack-ir --print-stack-ir`, as stack IR is always valid wat. Added docs for this in https://github.com/WebAssembly/binaryen/pull/1716
