### ISSUE TITLE
[Feature] Add DataView implementation

### ISSUE THREAD

**Issue by LinusU** [AssemblyScript/assemblyscript#315]
Currently using the following small work around in order to port a script that uses `DataView`, but would be very nice with native support:

```ts
class DataView {
  source: Uint8Array
  buffer: ArrayBuffer
  byteOffset: u32
  byteLength: u32

  constructor (source: Uint8Array) {
    this.source = source
    this.buffer = source.buffer
    this.byteOffset = source.byteOffset
    this.byteLength = source.byteLength
  }

  getUint32 (byteOffset: u32, littleEndian: boolean): u32 {
    return (this.source[byteOffset] << 24) & (this.source[byteOffset + 1] << 16) & (this.source[byteOffset + 2] << 8) & (this.source[byteOffset + 3])
  }

  getUint16 (byteOffset: u32, littleEndian: boolean): u32 {
    return (this.source[byteOffset] << 8) & (this.source[byteOffset + 1])
  }
}
```

If someone could point me in the right direction I would be happy to try and implement this ☺️

**Comment by dcodeIO** [comment]
Sure, go ahead :)

The place to add standard library components is in [std/assembly](https://github.com/AssemblyScript/assemblyscript/tree/master/std/assembly), a `dataview.ts` in this case. By `export class DataView { ... }` in this file the implementation becomes available in the environment.

The standard [DataView constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView#Syntax) seems to take an ArrayBuffer, though.. Possible optimizations here could be to annotate the getters as `@inline`, and to reuse the `loadUnsafe` etc. helpers from `internal/arraybuffer` for low-level access to the buffer directly, similar to what typed arrays already do.

**Comment by LinusU** [comment]
> The standard DataView constructor seems to take an ArrayBuffer, though..

Yeah, sorry, I just had some problems with that so quickly worked around it 😁 

Anything I submit will, of course, follow spec 100% 🙌 

I'll take a look at the other typed arrays and will try to get something together 👍
