### ISSUE TITLE
TypeError: memory_allocate is not a function

### ISSUE THREAD

**Issue by LinusU** [AssemblyScript/assemblyscript#318]
It seems like my compiled wasm file doesn't export e.g. `memory.allocate`. I'm getting the following error when trying to use e.g. `newArray(...)`:

```text
     TypeError: memory_allocate is not a function
      at Object.newArray (node_modules/assemblyscript/lib/loader/index.js:114:15)
```

Logging out the exported names shows this:

```text
{ memory: Memory [WebAssembly.Memory] {},
  table: Table [WebAssembly.Table] {},
  decodeBmp: [Function: 32] }
```

(`decodeBmp` is the function I'm exporting with `export function decodeBmp (...) { ... }`)

I'm probably missing something simple? 🤔 😄

**Comment by dcodeIO** [comment]
Looks like your version of the loader is outdated. That changed to `memory.allocate`.

**Comment by LinusU** [comment]
`memory_allocate` is just the name of the local variable, it's trying to read `memory.allocate`:

<img width="433" alt="screenshot 2018-11-07 at 19 07 20" src="https://user-images.githubusercontent.com/189580/48154385-6459b900-e2c0-11e8-9e32-4e044f0e7f61.png">

(the `console.log` is added by me)

**Comment by dcodeIO** [comment]
Ah, try `export { memory }` on the TS site.

**Comment by LinusU** [comment]
Yes 🙌, that fixed it!

Should we add this to the documentation somewhere, or have I simply missed it?

**Comment by dcodeIO** [comment]
There is a mention in the loader's README at **newString**, but maybe that should be more prominent
