### ISSUE TITLE
package-lock.json isn't in sync

### ISSUE THREAD

**Issue by LinusU** [AssemblyScript/assemblyscript#319]
Currently the package-lock.json isn't in sync, which makes `npm` modify it anytime I install, and which breaks `npm ci`:

```text
npm ERR! 
npm ERR! Invalid: lock file's binaryen@51.0.0 does not satisfy binaryen@51.0.0-nightly.20181010
npm ERR! Invalid: lock file's @types/node@10.9.4 does not satisfy @types/node@^10.11.7
npm ERR! Invalid: lock file's browser-process-hrtime@0.1.2 does not satisfy browser-process-hrtime@^1.0.0
npm ERR! Invalid: lock file's ts-loader@4.5.0 does not satisfy ts-loader@^5.2.1
npm ERR! Invalid: lock file's typedoc@0.11.1 does not satisfy typedoc@^0.13.0
npm ERR! Invalid: lock file's typescript@3.0.3 does not satisfy typescript@^3.1.2
npm ERR! Invalid: lock file's webpack@4.18.1 does not satisfy webpack@^4.20.2
npm ERR! Invalid: lock file's webpack-cli@3.1.0 does not satisfy webpack-cli@^3.1.2
npm ERR! 
```

A good way to prevent this from happening again is to use `npm ci` instead of `npm install` on Travis (which is the default on Travis when not overriding the install step)

I can submit a PR to fix and update Travis script 👍

**Comment by dcodeIO** [comment]
Iirc there has been some issue with `npm ci` a while ago. @MaxGraey, do you remember what this was?

**Comment by MaxGraey** [comment]
Yeah, we have some non-deterministic failure with `npm ci` in the past. But may be this issue of CI or `npm` and this already fixed? Who know?

**Comment by LinusU** [comment]
Hmm, I think that the vast majority of projects on Travis is running with `npm ci` these days, ever since they switched it on by default. Do you remember approximately when this was? 🤔

**Comment by MaxGraey** [comment]
This happened in the mid of Jun 2018

**Comment by dcodeIO** [comment]
FYI: I updated my local npm and rebuilt package-lock from scratch, but noticed that there are still some `http://registry...` things in the lock file, for whatever reason. Forcefully replaced all `http://` to `https://` now in my commit. Let's see how this turns out.

**Comment by LinusU** [comment]
Hmm, that's interesting, I wonder if it has something to do with having npm installed for a long time and then having cached `http` to the registry at some point 🤔 

I see that my branch also had some `http`s in there 🤔
