### ISSUE TITLE
Fiddle for Mandelbrot Set fails to build

### ISSUE THREAD

**Issue by terotests** [AssemblyScript/assemblyscript#324]
Chrome Version 70.0.3538.77 (Official Build) (64-bit)

After Build & Run:

https://webassembly.studio/?f=pne1undq5g

Failed to load WASM: WebAssembly Instantiation: Import #0 module="Math" error: module is not an object or function (ad blocker, maybe?)

**Comment by MaxGraey** [comment]
Just change `JSMath: Math` to `Math: Math` in `env`.
Fixed fiddle: https://webassembly.studio/?f=m6hbiw9wyq
