### ISSUE TITLE
[Feature] Same file for TS and AS

### ISSUE THREAD

**Issue by LinusU** [AssemblyScript/assemblyscript#325]
I'm trying to create a library which can be compiled to both WebAssembly, and to regular JavaScript as a fallback. Currently, I can use almost exactly the same code, apart from some small memory management stuff which makes it a bit annoying.

I'm currently working around this by having to files: `index.ts` with the actual implementation, and `wasm.ts` which contains the AssemblyScript specific parts.

**`wasm.ts`**

```typescript
import 'allocator/arena'
import { decodeBmp, getLastWidth, getLastHeight, getLastColorDepth, reset } from './index'

export { memory }
export { decodeBmp, getLastWidth, getLastHeight, getLastColorDepth, reset }
```

In order for TypeScript to compile the other file, I also need to add `"exclude": ["wasm.ts"]` to my `tsconfig.json`.

I think it would be great if we could control the memory allocator with just a flag, and that would also export the memory bindings to JS (`export { memory }`). That would allow me to compile the same file to both JS and WASM, without any extra configuration 🙌 

You can see this in action in my `wasm` branch: https://github.com/LinusU/decode-bmp/tree/wasm

**Comment by dcodeIO** [comment]
I think it should be possible to provide two entry files to `asc`. One with the common code, and one extra with the AS specific code that isn't used when compiling to JS, i.e.:

```
$> asc index.ts wasm-only/index.ts
```

**Comment by LinusU** [comment]
That's neat, but I think that my biggest problem isn't to exclude the other file from TypeScript, but rather that I have to keep the two entry points in sync. Whenever I add or remove an export from `index.ts`, I have to go and make the same change to `wasm.ts`.

It's also the small inconvenience of having to have more than one file 😁 it would be so clean to have the exact same code base compile both to JS and WASM 😍 

Thanks for the suggestion though, it takes me one step closer 👍

**Comment by dcodeIO** [comment]
I'd expect this to become more convenient once picking sensible defaults becomes an option, which will most likely happen once GC and friends are available. With the lack of GC, and the need for a memory manager in some (but not all) cases, it makes sense to explicitly include memory utilities where needed only, because if these'd always be exported, these would also always become compiled into the binary even if not needed.
