### ISSUE TITLE
Fix failing dtoa tests

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#337]
Within https://github.com/AssemblyScript/assemblyscript/pull/336, a couple of failing dtoa-related tests surfaced. Tracking issue so we don't forget.

**Comment by dcodeIO** [comment]
@MaxGraey Do you know if this is still an issue?

**Comment by MaxGraey** [comment]
yeah

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) with the new tracking issue now being https://github.com/AssemblyScript/assemblyscript/issues/843.
