### ISSUE TITLE
Enhancement Suggestion: Extended Commands to match WASM Instructions

### ISSUE THREAD

**Issue by jpryne** [AssemblyScript/assemblyscript#341]
I'd like to propose an extension, one comprised of additional commands that can be called from AssemblyScript & will compile to the corresponding WASM instructions. For example:

```javascript
export function rotateLeft(value: i32, shift: i32): i32 {
  return rotr(value, shift);
}
```
would compile to:

```wasm
  (func $main/rotateLeft (export "rotateLeft") (type $t1) (param $p0 i32) (param $p1 i32) (result i32)
    get_local $p0
    get_local $p1
    i32.rotr)
```

Happy to work on this, provided I can ask questions about implementation.

**Comment by dcodeIO** [comment]
No worries, you are welcome :)
