### ISSUE TITLE
[Feature Request] wasm2asc 

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#344]
Currently [wasm2c](https://github.com/WebAssembly/wabt/tree/master/wasm2c) can create a C file and header file from a wasm module.  Given the close nature to the underlying wasm types it seems like it would be easy to create type definition file from a binaryen module.

Is there already a way to do this that I'm missing?  If not, what do you suggest?

**Comment by MaxGraey** [comment]
AssemblyScript has [partially implement decompiler](https://github.com/AssemblyScript/assemblyscript/blob/master/src/decompiler.ts). But not sure about it status. @dcodeIO ?

**Comment by dcodeIO** [comment]
Yeah this *should* be relatively straight forward, but the decompiler is still missing operator precedence rules and a few other things. Haven't got around to it :)
