### ISSUE TITLE
On binary operation common type inference

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#35]
Copying a note here from the compiler sources for discussion:

```
TODO: Currently, the common type of any binary expression is the first operand's type. This
differs from C and other languages where comparing an int to a long, in this order, upcasts
left to a long before comparison, instead of failing when trying to downcast right to an int.
NOTE that if we change the current behaviour, some examples, tests and wiki pages will have
to be updated, while compound binary operations must retain the previous behavior.
```

While I like the current behavior because it rather emits an error instead of doing possibly unwanted implicit type-conversions plus how easy it is to annotate the operation's type on the left operand (`<i32>left < right` guaranteeing `i32.lt_s`), it certainly is non-standard and there might be valid reasons to do it like C instead. Feel free to discuss.

**Comment by torch2424** [comment]
Let me start by saying, I am definitely not a language or compiler guru, but I actually have been bitten by this a lot of times.

Most of the languages I use, usually follow the pattern that the snippet described above and it kind of becomes second nature. And after developing a good amount of code, it took a while for me to realize what was going on, and how.i would need to be even more explicit.

While I do agree the current pattern looks nice and is the most explicit, it should either follow the standard pattern, or be in some sort of FAQ and easy to learn and understand by newcomers :)

**Comment by torch2424** [comment]
By easy to learn, I mean easy to find in the docs

**Comment by dcodeIO** [comment]
Ok, this is now a lot more like C, with the rules outlined [in the wiki](https://github.com/AssemblyScript/assemblyscript/wiki/Types#assignability). Let me what you think :)

**Comment by torch2424** [comment]
Oh rad! Thank you! 😄 

If I could say, underneath the intro paragraph, could you provide some examples?

Like, for instance,

```
let integer8: i8 = -24;
let float32: f32 = integer8; // -24.00
let unsginedInteger8: u8 = integer8; // Whatever unsigning a integer gets you. 
```

**Comment by dcodeIO** [comment]
Ok, added an example. Hope it helps :)

**Comment by dcodeIO** [comment]
Closing for now :)

**Comment by torch2424** [comment]
Sorry for the late reply, had a buddy come by from out of town this weekend. The example is perfect! Thank you! 😄
