### ISSUE TITLE
Error when using asc.compileString()

### ISSUE THREAD

**Issue by fmkang** [AssemblyScript/assemblyscript#354]
We are trying to use AssemblyScript live in browser and we were happy to find the `asc.compileString()` function. However, we always get errors even with the example code. After going through the asc.js, we found the following problems:

The `compileString()` function passes custom `readFile` and `writeFile` functions that read from and write into objects instead of files, but the `main()` function converts relative path to absolute path before it reads file:

```JavaScript
let sourceText = readFile(path.join(baseDir, sourcePath) + ".ts");
```

If I compile from a string, it is supposed to read from`sources["input.ts"]`, but this line will convert it to "[working directory]/input.ts", which does not exist in the `sources` object, so I always get "ERROR: Entry file "input.ts" not found."

We can fix this by ourselves, but the output (writeFile) part also has similar problem. It's too difficult to locate it so we ask official fixes.

There is another problem: If you're trying to use any options, `main()` even can't recognize correct input file name. The example provided by Wiki has `{ optimize: 2 }` and the `main()` function tries to read from "2.ts" instead of "input.ts". It seems because "optimize" is defined as a boolean option in asc.json. However, if I write `{ optimize: true }` to use a boolean option, `compileString()` will mess it up. The function converts it to argument "--optimize true" but it should be "--optimize".

We hope you could fix this soon because we're kind of urgent.

**Comment by dcodeIO** [comment]
There is actually a test for `compileString` included [here](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/browser-asc.js#L76). This assumes that the distribution files in `dist/` are used, though, and it doesn't work properly in pretty much every other case, which should in fact be improved.

**Comment by MaxGraey** [comment]
See this example:
https://repl.it/repls/BlankSinfulDegrees

**Comment by fmkang** [comment]
It works, thanks.

Would you tell me what are the differences between `assemblyscript/cli/asc.js` and `assemblyscript/dist/asc.js`? I thought it is only minimized. The [Wiki](https://github.com/AssemblyScript/assemblyscript/wiki/Using-the-compiler) tells me to use `const asc = require("assemblyscript/cli/asc");` though.

**Comment by fmkang** [comment]
Okay, seen your updates. Thank you all.

**Comment by MaxGraey** [comment]
@fmkang Great! So I will close this issue but you free to reopen it in future
