### ISSUE TITLE
Feature request: Expose program and AST modules for use in transforms

### ISSUE THREAD

**Issue by Jannis** [AssemblyScript/assemblyscript#356]
There don't seem to be good ways to write `--transform` scripts right now. The AST is pretty complex and the `ast` and `program` modules are not exported anywhere.

It would be nice if they were exported so that e.g.
```js
const assemblyscript = require('assemblyscript')

module.exports = {
  afterParse: parser => {
    let source = parser.program.sources.find(source => ...)
    let stmt = assemblyscript.ast.Node.createImportStatement(...)
    source.statements.push(stmt)
  }
}
```
and similar are possible in transform scripts.

**Comment by dcodeIO** [comment]
Hmm, the `index.ts` file is the intended entry file of the compiler compiled to WebAssembly (eventually), and it is still TBD whether it makes sense to export everything in the WASM case. What you can do already today is to run the compiler from the sources (`npm run clean`) and import the respective components in TypeScript, just as the compiler itself does, i.e. from `src/compiler.ts`.

A lot of this is likely to change once the compiler actually compiles to WebAssembly and the reference-types/GC specs become supported, which might then hint us into the direction to take for making the JS and WASM versions truely interoperable.

**Comment by dcodeIO** [comment]
Yeah, it's quite rought still. We could also just add all the things to `index.ts` and think about a way to disable certain exports only when compiling to WebAssembly later. Should also be ok since we don't know how a WASM version will look.

**Comment by Jannis** [comment]
Great, thanks! We'll give this a spin tomorrow.

**Comment by Jannis** [comment]
I've been trying this and I can confirm the full API is now available to the transform script. We can close the issue.

Out of curiosity: what would be the best way to add some code to a source in a transform script? Specifically, we'd like to automatically add
```ts
import 'allocator/arena'
export { allocate_memory }
```
so developers don't need to worry about that.

I've been trying this:
```js
const { CommonFlags, Node, Range } = require('assemblyscript')

module.exports = {
  afterParse: parser => {
    // Identify the main source file
    let source = parser.program.sources.find(source => source.isEntry)

    // Create import statement
    let expr = Node.createStringLiteralExpression('allocator/arena', new Range(source, 0, 0))
    let stmt = Node.createImportStatement(null, expr, new Range(source, 0, 0))
    source.statements.push(stmt)

    ...
  },
}
```
but the ranges are off, obviously, and the import statement never ends up in the build output. Is there a cleaner / simpler / better way?

**Comment by dcodeIO** [comment]
You could try to add a completely new source file to the list of source files that contains your custom code, and is an entry file, like so:

```ts
parser.parseFile(`...custom source code...`, "custom/path.ts", true);
```

**Comment by Jannis** [comment]
I just realize if we can provide multiple entry sources... then we can also just pass a `memory.ts` to `asc.main()` or the `asc` CLI to export `allocate_memory`. We don't need to use transforms for this.

Thanks @dcodeIO and @MaxGraey!
