### ISSUE TITLE
where is assemblyscript artwork assets?

### ISSUE THREAD

**Issue by kazupon** [AssemblyScript/assemblyscript#364]
I would tried to find assenblyscript artwork assets. but i could not find those. 😞 
I want to use logo in speaking slide about assemblyscript for meetup event.
If you have the those, I hope share as artwork repo in assemblyscript organaization. 😀 

ref the below artwork assets repo:
https://github.com/vuejs/art

**Comment by dcodeIO** [comment]
Here's what we currently have: https://github.com/AssemblyScript/assemblyscript/tree/master/media :)

**Comment by kazupon** [comment]
Ah, Thanks!
I didn’t check the repository carefully. 😓
