### ISSUE TITLE
Convert number to string

### ISSUE THREAD

**Issue by vgrichina** [AssemblyScript/assemblyscript#369]
Is there any reason why with standard library possible to convert `Array` to string but not e.g. `i32`?

There seem to be internal functions to convert number to string, but nothing external.

**Comment by dcodeIO** [comment]
The missing building block here is something like am I32 class that'd be bound to the i32 basic type, that'll then provide the implementation of `toString` and wiring this to any occasion where a basic value is implicitly converted to a string, i.e. `"value: " + someValue`. One missing feature to make this work is to use any basic value, e.g. also f32, as the explicit `this` type of such a class respectively its methods.

**Comment by vgrichina** [comment]
> missing building block here is something like am I32 class that'd be bound to the i32 basic type

Is main problem that compiler currently doesn't have mechanism to do this binding in general?  How hard is it to implement? 
What if instead using actual class we just transform calls like `a.toString()` to function calls like `__I32_toString(a)`?

Maybe also there is some easy way to access internal methods like `dtoa` that I'm not aware of?

**Comment by dcodeIO** [comment]
Being worked on in https://github.com/AssemblyScript/assemblyscript/pull/373
