### ISSUE TITLE
Feature: Github Pages website for examples to avoid cloning and building

### ISSUE THREAD

**Issue by dbkaplun** [AssemblyScript/assemblyscript#37]

**Comment by dcodeIO** [comment]
Or, maybe, fiddles of the examples in [WebAssembly Studio](https://webassembly.studio), then linking to them? :)

**Comment by dcodeIO** [comment]
Game Of Life fiddle: https://webassembly.studio/?f=60bnkjkt9wd

**Comment by dcodeIO** [comment]
Both the game of life and mandelbrot examples now have a demo page and a respective fiddle. Is that sufficient to consider this issue solved? :)

**Comment by dbkaplun** [comment]
Looks good! Great job to everyone who was involved!
