### ISSUE TITLE
WebGL examples

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#371]
Any AS WebGL examples?

**Comment by jbousquie** [comment]
this one is a AS + BabylonJS example : http://jerome.bousquie.fr/BJS/test/SPSWasm/spsWasm.html
40K animated solid particles

**Comment by rjkz808** [comment]
@jbousquie hello! Can you please share the source code of this example? It would be very interesting to look into it 😄

**Comment by jbousquie** [comment]
It's here : http://jerome.bousquie.fr/BJS/test/SPSWasm/index.ts
http://jerome.bousquie.fr/BJS/test/SPSWasm/spsWasm.js

**Comment by MaxGraey** [comment]
@jayphelps Seems pretty old AssemblyScript version was used. Currently you don't import memory allocator. Also AS has `Mathf.sin` / `Mathf.cos` and `Mathf.sincos` already.

Also this
```ts
function angle_shift(x: f32): f32 {
    let gamma: f32 = f32( NativeMath.mod(f64(x) + PI64, twoPI64) );
    if (gamma < 0) {
        gamma += PI2
    }
    return (gamma - PI);
}
```
could be slightly optimized to:
```ts
// wrap to [-pi...pi]
function angle_shift(x: f32): f32 {
   if (Mathf.abs(x) <= Mathf.PI) return x;

  const pi  = Math.PI;
  const pi2 = 2 * Math.PI;

   let y = f64(x) + pi;
   let m = y - pi2 * Math.floor(y / pi2);
   if (m >= pi2) return 0;
   if (m < 0) return pi2 + m == pi2 ? -pi : f32(m + pi);
   return f32(m - pi);
}
```

**Comment by jbousquie** [comment]
yep,this is from late 2018

**Comment by rjkz808** [comment]
Thank you!
