### ISSUE TITLE
Fix super constructor not being called / required to be called

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#375]
This is a tracking issue for `super(...)` calls in constructors, which doesn't work currently for no good reason.

**Comment by dcodeIO** [comment]
Also: Document limitations of virtual (here: overloaded) members, i.e.

```ts
class A {
  foo(): i32 { return 0; }
}
class B extends A {
  foo(): i32 { return 1; }
}

(new B() as A).foo() == 0
```

**Comment by jtenner** [comment]
I know I'm not able to contribute much, but I have replicated the problem with calls to `super()` as an example here:

https://webassembly.studio/?f=01c69xlgk6my

Currently it reports as a syntax error.

Leaving out the `super()` call and using `// @ts-ignore` at least allows developers to bypass the constructor being required to call `super()`, but then the constructor never gets called. Workarounds involve creating and calling a `super.init()` function that must be called in the child class.

**Comment by MaxGraey** [comment]
@dcodeIO Is this issue still present?
