### ISSUE TITLE
Confusing Error in Binaryen: Assertion failed: undefined

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#380]
After running yarn to build my project I received a cryptic error and am unsure what the problem is.

The output seems to display the contents of a minified node function, instead of a helpful message that might indicate something is wrong. Any idea where the problem might be?

```
yarn run v1.12.3
$ run-p asbuild:untouched asbuild:optimized
$ asc assembly/index.ts -b build/optimized.wasm -t build/optimized.wat --sourceMap --validate --optimize --use Math=JSMath
$ asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug --use Math=JSMath
Assertion failed: undefined
Assertion failed: undefined

C:\Users\jtenner\Desktop\projects\canvas-as\node_modules\binaryen\index.js:7
if(n){p=__dirname+"/";var da,ea;a.read=function(b,d){var g=q(b);g||(da||(da=require("fs")),ea||(ea=require("path")),b=ea.normalize(b),g=da.readFileSync(b));return d?g:g.toString()};a.readBinary=function(b){b=a.read(b,!0);b.buffer||(b=new Uint8Array(b));assert(b.buffer);return b};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof fa))throw b;});process.on("unhandledRejection",t);a.quit=



abort("Assertion failed: undefined"). Build with -s ASSERTIONS=1 for more info.
```

**Comment by jtenner** [comment]
Update: Apparently uninstalling and installing assemblyscript fixes the issue. Why would I need to reinstall `asc`?

**Comment by dcodeIO** [comment]
The cryptic output can happen when [Binaryen compiled to JS](https://github.com/AssemblyScript/binaryen.js) runs into an assertion in what was C++ code, and there's not a whole lot of additional information because it's not a debug build. Though, when reinstalling the compiler solved the problem, my guess is that your AssemblyScript and binaryen.js versions deviated from what's compatible somehow, and the reinstall fixed that.

**Comment by jtenner** [comment]
Thanks for the quick reply! Since my issue is solved, it seems like there's nothing left to do except close the issue.
