### ISSUE TITLE
Un-exported function errors wasn't thrown when compiling.

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#382]
The [asc code](https://webassembly.studio/?f=az7c0g5kdeg)

```
function illegal(): void {
  var a = x;
}
```
Expect: compile failed.
In fact: successfully

As the `AssemblyScript` is compiling language, all of the grammar errors should be thrown at the compiling period even though the function maybe not used in runtime or exported.

**Comment by MaxGraey** [comment]
Actually It's hard to implement and unnecessary during compiler design which compile everything lazily. So it will signal proper error when you make this function exportable or use in other method which will later exported. Close it
