### ISSUE TITLE
Define custom abort function in the module?

### ISSUE THREAD

**Issue by kyegupov** [AssemblyScript/assemblyscript#388]
I need to create wasm modules that would adapt to some rigid environment (i.e. the set of things I can import is known and fixed). I'd like to use exceptions (idiomatic!), but they are implemented via an `abort()` hook currently.

It seems (https://github.com/AssemblyScript/assemblyscript/blob/ebae7cbd7310eb880e16b7e67b325f36ab1ddbc5/src/program.ts#L663) I should be able to implement my custom abort at the AS side, but so far I have failed (`@global export function abort` doesn't seem to do the trick).

Is there a way? Am I missing something? This should be documented in the Wiki, probably.

**Comment by singpolyma-shopify** [comment]
Maybe this will help on your search? https://github.com/AssemblyScript/assemblyscript/commit/73417a9a060d1585349b0208fcfd326b80defbfb

**Comment by dcodeIO** [comment]
What happens if you do this on the command line together with having a global abort function: `asc ... -use abort=abort` ?
