### ISSUE TITLE
Is there any intelligent code hint plugins for webstorm or vscode?

### ISSUE THREAD

**Issue by yyh1102** [AssemblyScript/assemblyscript#390]
A better code hint maybe improve the experience for developing assemblyscript~

**Comment by willemneal** [comment]
vscode has good typescript support and assembly script is still valid typescript.  For what it's worth, I use atom and it has type docs and explores type declarations.

**Comment by MaxGraey** [comment]
try use this:
```ts
/// <reference path="../node_modules/assemblyscript/index.d.ts" />
```

**Comment by MaxGraey** [comment]
@yyh1102 yes this not works in WebAssembly Studio but you asked about desktop editors like vscode.

**Comment by vgrichina** [comment]
@jtenner I think making some patches to https://github.com/Microsoft/monaco-typescript is going to give biggest bang for buck.
There are likely only small changes needed (to ignore some warnings) and it's going to cover VSCode + variety of web IDEs using Monaco.

**Comment by jtenner** [comment]
The question is how do you differentiate between code written for assemblyscript and code written in typescript?

**Comment by vgrichina** [comment]
> The question is how do you differentiate between code written for assemblyscript and code written in typescript?

There is `tsconfig.json` for that.

**Comment by ExE-Boss** [comment]
Unstale

**Comment by ExE-Boss** [comment]
Well, differentiating between the&nbsp;different `int`&nbsp;types depends on&nbsp;https://github.com/Microsoft/TypeScript/issues/202.

**Comment by dcodeIO** [comment]
Interesting that this has actually be discussed at TypeScript. Not too optimistic that this'll ever happen, though. My expectation at this point is that we'll have to create our own language service eventually, possibly switching to an `.as` extension.

**Comment by ExE-Boss** [comment]
Is there a way to tell <a href='https://github.com/apps/stale'>@stale[bot]</a> not to close an issue?

**Comment by dcodeIO** [comment]
It's currently configured to automatically mark issues without further activity as stale and close them after a while if no new activity happens, unless tagged as `enhancement`, `bug` or likewise. So far I considered this issue a question, but looks its more of an enhancement request now?

**Comment by trusktr** [comment]
Is there currently a way to to tell TypeScript (not AssemblyScript) not to complain about `decorators are not valid here`?

I'm using Atom with the atom-typescript plugin, so that I can get all the IDE features.

But I'd like to write portable code. How can I write that in valid TS form?

In my JS I have:

```ts
await WebAssembly.instantiateStreaming(response, {
  env: {
    get() { return 5 },
  }
}))
```

which works in AS if I write

```ts
@external("env", "get")
declare function get(): i32;
```

But if I try to write

```ts
declare namespace env {
	function get(): i32;
}
```

then it gives the runtime error

```
Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="index" error: module is not an object or function
```

This part isn't clear. I was trying to do it intuitively the same as with `console.logi`. Is `env` different and doesn't work the same?

**Comment by dcodeIO** [comment]
We use `// @ts-ignore`, which will ignore the next line in AS, but not sure if a missing decorator like that will compile with tsc.

**Comment by trusktr** [comment]
Ah, true, it won't compile anyways. So looks like the trick of putting those imports in a separate file (like in https://github.com/AssemblyScript/assemblyscript/issues/384#issuecomment-496296642) may be the way to do it.

I will also look at exporting `getFour` from a module. Then maybe a Babel or Gulp step before `asc` can supply the `@external` code.

**Comment by onionhammer** [comment]
If it's not valid TypeScript, should it be valid AssemblyScript? I thought AS was a subset of TS?

**Comment by MaxGraey** [comment]
in some parts it's stricter subset (no `any` and `undefined`) in some part it's superset (more integer float types, operator overloading, builtin decorators over functions and declarations and etc)

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because it is more a question, with a solution being discussed [elsewhere](https://github.com/AssemblyScript/assemblyscript/issues/1003) as part of creating a custom language server.
