### ISSUE TITLE
An error occurs on "allocator/tlsf.ts" while call newArray on TypedArray with byteLength larger than (2**20-8)

### ISSUE THREAD

**Issue by darren-211** [AssemblyScript/assemblyscript#395]
aborted by:

![image](https://user-images.githubusercontent.com/12593297/50570793-d5ef4880-0dd3-11e9-8517-6d5210ebb027.png)

my assembly code:
```typescript
// assembly/index.ts -> build/main.wasm
import 'allocator/tlsf';

export { memory };

export function sum(a: Int32Array): i32 {
    let rtn = 0;
    for (let i = 0, l = a.length; i < l; i++) {
        rtn += a[i];
    }
    return rtn;
}
```

my testing code:
```typescript
import * as loader from '../loader';  // copied from @assemblyscript/loader
import ASModule from '../build/main';  // generated by asc -d

(async () => {
    const Module = await loader.instantiateStreaming<typeof ASModule>(fetch('build/main.wasm'));

    const arr = new Int32Array(Array(2 ** 20 / 4).fill(1));

    const arrPtr = Module.newArray(arr);  // ** aborted here
    console.log('ptr', arrPtr);
    const s = Module.sum(arrPtr);
    console.log('sum: ', s);
    Module.freeArray(arrPtr);
})();
```

version of assemblyscript:
```json
{
"_from": "github:AssemblyScript/assemblyscript",
"_id": "assemblyscript@0.5.0"
}
```

While I change the memory manager from `tlsf` to `arena`, no aborting any more.

**Comment by dcodeIO** [comment]
ArrayBuffers have a maximum byte length of `(1 << 30) - 8` ([see](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/internal/arraybuffer.ts#L9)) to match the maximum bucket size of 32-bit TLSF. Trying to allocate more than that will result in an `unreachable`, but from your code snippet it doesn't seem like that should happen here. Hmm...

**Comment by jtenner** [comment]
@darren-211 how many times do you perform this operation? Does it fail after a bunch of calls, or after the first call?

**Comment by darren-211** [comment]
@jtenner  It fails at the first call. 
@dcodeIO 
And you can check on my code repo: https://github.com/darren-211/asc-array-demo.
