### ISSUE TITLE
UTF-16 string length issue

### ISSUE THREAD

**Issue by ShrewdSpirit** [AssemblyScript/assemblyscript#399]
Hello. I've defined a string and it seems assemblyscript converts them to utf16 in bytecode. I'm using wasm for scripting my engine (I don't use JS for host).

I have this code:
```ts
@external("env", "printstr")
declare function printstr(val: string, len: i32): void;

function str(v: string): void {
    printstr(v, v.length)
}

export function main(): void {
    ...
    str("hello world")
}
```

And `(data (i32.const 80) "\0b\00\00\00h\00e\00l\00l\00o\00 \00w\00o\00r\00l\00d\00")` is the generated data for my string. My issue is the length of the above string I'm receiving is 11 and even with `lengthUTF8` gives me 12 which is not the exact size of that data in memory. I can't decode the string when I don't have the exact size of string data.

Any ideas how to solve this?

**Comment by ShrewdSpirit** [comment]
This seem to work but at the cost of a new allocation for a string that's already there
```ts
export function logs(v: string): void {
        let buffer = new Uint8Array(v.length)
        for (let i: i32 = 0; i < v.length; i++) {
            buffer[i] = v.charCodeAt(i)
        }
        internals.printstr(buffer.buffer.data, buffer.buffer.byteLength)
    }
```

**Comment by MaxGraey** [comment]
```ts
export function logs(str: string): void {
  internals.printstr(str.toUTF8(), str.lengthUTF8); // length + null termination
  // or without null terminalion length:
  // internals.printstr(str.toUTF8(), str.lengthUTF8 - 1);
}
```

**Comment by ShrewdSpirit** [comment]
@MaxGraey oh I didn't notice toUTF8 returns the offset of utf8 string. Thanks for the help
