### ISSUE TITLE
is graphics rendering possible?

### ISSUE THREAD

**Issue by goldenratio** [AssemblyScript/assemblyscript#4]
Hi,

I am looking to render graphics in canvas element via WASM, instead of JavaScript. Is this possible with AssemblyScript?

For example, in game of life demo - rendering is done via javascript, is it possible to move it to assembly code?

**Comment by ColinEberhardt** [comment]
No, WebAssembly does not have direct DOM access. The only way to render to canvas, or update any HTML is via importing JavaScript functions into your wasm module.

**Comment by goldenratio** [comment]
clear now thanks.

**Comment by jiyinyiyong** [comment]
Does WebAssembly have Canvas API?

**Comment by ColinEberhardt** [comment]
No, it doesn’t have support directly. All WebAssembly can do is perform computations, reading and writing to memory. For everything else, you’ll need to import JavaScript functions that provide an interface into DOM / canvas etc ...

**Comment by dcodeIO** [comment]
Things like these will become more efficient once [host-bindings](https://github.com/WebAssembly/host-bindings) lands. From an AssemblyScript point of view, this could then look like [in this String experiment](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/parser/string-binding.ts), being part of stdlib, so it "just works".

**Comment by goldenratio** [comment]
what about webgl? can we use that for rendering in WASM. Recently I have been looking into rust lang. It seems to be possible. 
Related RUST + GL + WASM repo https://github.com/kvark/wasm-triangle
Some more info on reddit https://www.reddit.com/r/rust_gamedev/comments/7mc7yk/is_there_any_wasm_friendly_2d_rendering_lib/drto3p9/

**Comment by dcodeIO** [comment]
It's just like with the game of life example: They are importing their own helpers to make it possible. You can do the same in AS.

**Comment by goldenratio** [comment]
@dcodeIO  thanks! :) you made it really clear for me.
