### ISSUE TITLE
AssemblyScript Playground

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#40]
Finally I get some progress with my playground. Now support only AssemblyScript. Still need better syntax highlight for s-expression (wast), I working on that. 

Try it and tell me plz about your experience:

[https://maxgraey.github.io/assembleash/#AssemblyScript](https://maxgraey.github.io/Assembleash/#AssemblyScript)

**Comment by dcodeIO** [comment]
Regarding s-expr, maybe you can use something from this file: https://github.com/dcodeIO/AssemblyScript/blob/gh-pages/assets/language-wast-sexpr.js

**Comment by MaxGraey** [comment]
Actually I already start implementing [wast syntax for ace.js](https://github.com/MaxGraey/assembleash/blob/master/grammars/wast_highlight_rules.js)

**Comment by MaxGraey** [comment]
Partially done:

![screenshot](https://camo.githubusercontent.com/35fd7e21d4ad4ea0e1920a987d96647b1f431571/68747470733a2f2f7777772e64726f70626f782e636f6d2f732f33366d65786937636a63377a7668672f617373656d626c656173682d73637265656e73686f742e6a70673f7261773d31)
