### ISSUE TITLE
Does AS support reflect-metadata?

### ISSUE THREAD

**Issue by yyh1102** [AssemblyScript/assemblyscript#400]
`reflect-metadata` is very useful in decorator design~ Have it been supported in AS? If it supports, how can i get the reflect type of static type like `i32/u32` and `i64/u64`?

**Comment by dcodeIO** [comment]
There's no reflection support yet, unfortunately. There are a few [builtins](https://github.com/AssemblyScript/assemblyscript/wiki/Built-ins#compile-time-type-checks) that might be helpful to determine specific conditions of a type, though.

**Comment by yyh1102** [comment]
Are there any solutions that i can get a reference or something like that representing a specific static type at runtime? 
For example: 
```javascript
let a:u8 = 1;
```
Because `u8` is a type alias of `number` in AS, at runtime i get the type `Number`, not the `u8`.

**Comment by MaxGraey** [comment]
`u8` isn't type alias of `number` in AS but in portable TS this is true. Actually `u8` internally represent as `i32` in wasm and use additional emulations for handling conversion and overflowing.

**Comment by yyh1102** [comment]
Thanks for reply! What i want to do is below: 
I have a function:
```javascript
function hi(a:string,b:u8){...}
```
And actually the arguments of the func are not limited in types or amounts, so there may be many different function signatures.

I wanna get the parameters' types as a array, and serialize the arguments according to `sizeof<T>(type)` . In other sides, deserialize the arguments from a bytes array, with the specific static type. 

How can i do that using AS?

**Comment by dcodeIO** [comment]
There is no way to obtain an array of types, but what you can do is, for example:

```ts
function hi<A,B,C>(a: A, b: B, c: C): void {
  if (isInteger<A>() && sizeof<A>() == 1) { // matching i8, u8
    ...
  }
  ...
}
```

The branches on `isInteger<A>()` etc. will be evaluated statically, so code that doesn't match the condition will not be compiled. Might not fit your use case, of course.

**Comment by MaxGraey** [comment]
or simpler if you need more concrete type matching:
```ts
function hi<A,B,C>(a: A, b: B, c: C): void {
  if (A instanceof u8) {
    // A is type of u8
  }
  if (A instanceof i8) {
    // A is type of i8
  }
}
```

**Comment by yyh1102** [comment]
Thanks you two so much! @MaxGraey @dcodeIO Maybe i can hav a try~

Are there any plans to support reflect mechanism?
