### ISSUE TITLE
Initializing array with a literal re-uses same modifiable object among runs

### ISSUE THREAD

**Issue by vgrichina** [AssemblyScript/assemblyscript#401]
Let's say you have code like:

```typescript
function doSomething(): Array<string> {
  let arr: Array<string> = [];
  arr.push("foo");
  return arr;
}
```

Expected behavior is that function always returns `["foo"]`.
However in AssemblyScript a new element will be added to array on each call.

**Comment by MaxGraey** [comment]
Duplicate #303
