### ISSUE TITLE
u32 converted by asc to i32

### ISSUE THREAD

**Issue by jhazz** [AssemblyScript/assemblyscript#402]
Why ASC compiler forcely converts all u32 constants, parameters to i32 ?

Source file: https://github.com/jhazz/gs/blob/master/assembly/gs/test.as.ts

```ts
export const UNSIGNED_VALUE1: u32 =100000;
export const UNSIGNED_VALUE2: u32 =0xffffffff; // Should be 4294967295
export const UNSIGNED_VALUE3: u32 =-1;
```

compiled to https://github.com/jhazz/gs/blob/master/build/test.wat

```wat
(module
 (type $v (func))
 (memory $0 0)
 (table $0 1 anyfunc)
 (elem (i32.const 0) $null)
 (global $assembly/gs/test.as/UNSIGNED_VALUE1 i32 (i32.const 100000))
 (global $assembly/gs/test.as/UNSIGNED_VALUE2 i32 (i32.const -1))
 (global $assembly/gs/test.as/UNSIGNED_VALUE3 i32 (i32.const -1))
 (global $HEAP_BASE i32 (i32.const 8))
 (export "memory" (memory $0))
 (export "table" (table $0))
 (export "UNSIGNED_VALUE1" (global $assembly/gs/test.as/UNSIGNED_VALUE1))
 (export "UNSIGNED_VALUE2" (global $assembly/gs/test.as/UNSIGNED_VALUE2))
 (export "UNSIGNED_VALUE3" (global $assembly/gs/test.as/UNSIGNED_VALUE3))
 (func $null (; 0 ;) (type $v)
 )
)
```

The same problem with other code. All parameters are changed from usize to u32 and it does not helps:
https://github.com/jhazz/gs/blob/master/assembly/gs/gs.as.ts
compiled to 
https://github.com/jhazz/gs/blob/master/build/gs.wat

**Comment by MaxGraey** [comment]
because wasm support only four plain types: `i32`, `i64`, `f32` and `f64`. But wasm has unsigned instruction set for `i32`/`i64` so behaviour of `u32/u64` resolved on instruction level.

**Comment by jhazz** [comment]
Ok. But what is the source of problem? 
Please watch this:
https://github.com/jhazz/gs/blob/master/assembly/gs/gs.as.ts#L46

```ts
export function getAligned(offset:u32):void{
    logger(align(offset));
    logger(alignToBlock(offset));
    logger(alignToPage(offset));
}
```
Chrome console prints via `logger()` good values for 8-byte aligned `offset`, then prints block-aligned `offset` value but then, instead of page-aligned `offset` value shows `undefined` value???. 

Firefox break execution of function around begin of this block:
https://github.com/jhazz/gs/blob/master/build/gs.wat#L70
```wat
  block $assembly/gs/gs.as/alignToPage|inlined.0 (result i32)
   get_local $0 
   get_global $assembly/gs/gs.as/PAGE_MASK
   i32.add
   get_global $assembly/gs/gs.as/PAGE_MASK
   i32.const -1
   i32.xor
   i32.and
  end
  call $assembly/gs/gs.as/logger
```

Do you have any idea?

**Comment by MaxGraey** [comment]
I don't think it's problem on AS side. Just check this fiddle:
https://webassembly.studio/?f=l00wnrt4vs

**Comment by jhazz** [comment]
Yes, problem to in the AssemblyScript. Please forgive me for inattention. 
Smart `FireFox console` collapses identical output text. And since the function has a return type of `void`, I see `undefined` in the output console.
This is how it looks. I hope others do not make such mistakes.

![2019-01-08_13-01-56](https://user-images.githubusercontent.com/3178444/50812687-4b17cc00-1346-11e9-8572-e1781d6e6012.png)

Thank you very much for the adoption of my files to the WebAssembly Studio.
It is very smart and cool! I think, I can work in this from home.
