### ISSUE TITLE
Docs on layout / alignment of classes?

### ISSUE THREAD

**Issue by singpolyma-shopify** [AssemblyScript/assemblyscript#403]
Are fields aligned like a C struct?  Packed?  The wiki page on layout doesn't mention object types right now.

**Comment by MaxGraey** [comment]
all ref types has 8-byte alignment.

**Comment by singpolyma-shopify** [comment]
@MaxGraey so, like a C struct on 64-bit architecture?

**Comment by MaxGraey** [comment]
yes, as any pointer in C/C++ on 64-bit platform

**Comment by singpolyma-shopify** [comment]
Hmm... when I generate code for access to the second field in a class like:

```
class Thing {
    something: u8;
    other: String;
}
```

It looks like it only uses an offset of 4 to get to `other`, which would be 32-bit alignment as I would have expected, and not 64-bit alignment.

**Comment by MaxGraey** [comment]
Yes, because AS not using packing for emulation types like `i8/u8/i16/u16` and use `i32` internally. But if you create class like:
```ts
log(changetype<u32>(new Thing()));
log(changetype<u32>(new Thing()));
log(changetype<u32>(new Thing()));
```
it output:
```
8
16
24
```

**Comment by dcodeIO** [comment]
Also added a paragraph here: https://github.com/AssemblyScript/assemblyscript/wiki/Memory-Layout-&-Management#classes
