### ISSUE TITLE
Passing string/array from host to AS

### ISSUE THREAD

**Issue by ShrewdSpirit** [AssemblyScript/assemblyscript#405]
I'm trying to pass complex structures to module. My host is a custom one. I can call functions from AS to host and vice versa. But the main issue I have is the AS side for passing structures back and forth. I'm using tlsf allocator and I can read and write to module's memory from host.

The primary solution I have for passing arrays from host to module is call an exported module function from host that allocates an array and returns the offset back to host and use other exported module functions to do primary array manipulations from host. This solution is fine in my case, but the real problem is with strings. I have no idea how to allocate an empty string from AS and dynamically expand it as needed (Considering its offset and length being used from host)

Also I'm concerned about the way such structures are freed on AS side. Is there a GC or automatic free?

**Comment by dcodeIO** [comment]
One thing you could do at this point is to `import { allocateUnsafe } from "internal/string"` and use that to construct a string in memory. While this is the safest way to do it (works with experimental GC), you could of course also allocate a raw chunk of memory as long as you are using only TLSF (and no GC), and adhere to [string layout in memory](https://github.com/AssemblyScript/assemblyscript/wiki/Memory-Layout-&-Management#strings). The latter is [what the loader is doing](https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/index.js#L84).
