### ISSUE TITLE
[Documentation] Building Unclear or Outdated

### ISSUE THREAD

**Issue by ctsstc** [AssemblyScript/assemblyscript#412]
https://github.com/AssemblyScript/assemblyscript#building

The scripts listed in the build section do not exist after following the setup. Is there something else that needs to be ran before those scripts exist in the package.json, or is this an outdated section?

## package.json Scripts That Do Not Exist

- `npm run build`
- `npm run clean`
- `npm run check`
- `npm test` - exists with basic install but doesn't do what's described.
- `npm run all`

**Comment by dcodeIO** [comment]
These scripts actually exist. Make sure that you are installing from master on GitHub, not from npm.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
