### ISSUE TITLE
out of bounds

### ISSUE THREAD

**Issue by whaqzhzd** [AssemblyScript/assemblyscript#413]
I am trying to write a WebGL program using assemblyscript. I am having a problem now.

If I don't assign a value to a member variable in the initialize
but assign it directly after the declaration
https://github.com/iceclam/iceclam/blob/master/backend/assembly/websys/gl/gl_webgl_rendering_context.ts#L333

I will get an invalid value of 0
https://github.com/iceclam/iceclam/blob/master/backend/test/webapi/common.ts#L20

If I assign values ​​to all member variables here, I will prompt out out of bounds
If a few values ​​are valid
https://github.com/iceclam/iceclam/blob/master/backend/assembly/websys/gl/gl_webgl_rendering_context.ts#L333

so I have two questions that are very doubtful.
1: why do I assign invalid values ​​directly, I have to assign values ​​in the initialization function.
2: why do I assign values ​​to all member variables in the initialization function, I will prompt out out of bounds

**Comment by MaxGraey** [comment]
I can't see your constructor for `WebGLRenderingContext`. Just `initialize` method which I'm not sure calling in somewhere. You can do better and more appropriate:

```ts
export class WebGLRenderingContext extends CommandBuffer {
   public readonly ACTIVE_ATTRIBUTES: GLenum = 0x8B89;
   public readonly ACTIVE_TEXTURE: GLenum = 0x84E0;
   ...
}
```

**Comment by whaqzhzd** [comment]
I used to do this. But the value I got is always 0

**Comment by whaqzhzd** [comment]
until I give up, choose to assign values ​​in the initialization function, I can get the correct value.

**Comment by whaqzhzd** [comment]
call the initialization function here
https://github.com/iceclam/iceclam/blob/master/backend/assembly/websys/web/html_canvas_element.ts#L60

**Comment by whaqzhzd** [comment]
not sure if this error caused by T extends WebElement
https://github.com/iceclam/iceclam/blob/master/backend/assembly/websys/web/html_canvas_element.ts#L58

**Comment by MaxGraey** [comment]
Are you sure problem in that part? I created minimal fiddle:
https://webassembly.studio/?f=igzosflhsgb

It will be great if you can isolate your problem part in WAS

**Comment by whaqzhzd** [comment]
yes, I also doubt myself, I tried to find a way to reproduce the problem in studio, but failed.
but I am convinced of this problem, because I printed the value and asked my friend to run the value, the result is the same, both are 0.

**Comment by whaqzhzd** [comment]
![image](https://user-images.githubusercontent.com/16913061/51035286-791a3c00-15e4-11e9-95c2-708580e668e5.png)
![image](https://user-images.githubusercontent.com/16913061/51035290-7f101d00-15e4-11e9-941f-fb44d4e4bcef.png)
This is the first case, I assign a value in the initialization function, you can see the output x and output the correct value.

**Comment by whaqzhzd** [comment]
Then we comment out the assignment in the initialization function and change it to direct assignment.
![image](https://user-images.githubusercontent.com/16913061/51035424-e4640e00-15e4-11e9-9ec3-d9c3b44cf380.png)
![image](https://user-images.githubusercontent.com/16913061/51035429-e928c200-15e4-11e9-964e-20d5a06cb00c.png)
![image](https://user-images.githubusercontent.com/16913061/51035435-ee860c80-15e4-11e9-98bf-96f48afa6d9e.png)
After outputting x, a value of 0 is output.

**Comment by whaqzhzd** [comment]
log code is here
https://github.com/iceclam/iceclam/blob/master/backend/test/webapi/common.ts#L19

**Comment by MaxGraey** [comment]
I can't reproduce this on WAS:
https://webassembly.studio/?f=f77lyzxvj79

**Comment by whaqzhzd** [comment]
@MaxGraey hi。I reproduced this problem.
https://webassembly.studio/?f=vk4kayjktek

**Comment by whaqzhzd** [comment]
I can probably describe the problem, just delete the inherited commandbuffer, there is the correct value, although I don't know why, I hope this discovery can help you.

**Comment by MaxGraey** [comment]
Why you use `f32` in CommandBuffer for offsets and id?

**Comment by whaqzhzd** [comment]
can't use f32? I just use him simply. Can I solve the problem if I switch to i32 or other types?

**Comment by whaqzhzd** [comment]
oh. correct. I flipped through the issues. Call super for constructors and constructors. I am not using it now. Missed here. Thank you for your help, I can continue to write my as+webgl.

**Comment by whaqzhzd** [comment]
Just say, if there is any best practice, please let me know. Greatful
随便说一句，如果有什么最佳实践，请告诉我。不胜感激
