### ISSUE TITLE
Allow enough memory for --memoryBase

### ISSUE THREAD

**Issue by singpolyma-shopify** [AssemblyScript/assemblyscript#414]
When `--memoryBase` is passed, the `memory` declaration in WASM should be big enough to fit at least the static segment before this base address, even if there is no linear memory used by the program.

**Comment by dcodeIO** [comment]
Hmm, to my understanding [this](https://github.com/AssemblyScript/assemblyscript/blob/master/src/compiler.ts#L313) should be [the case](https://github.com/AssemblyScript/assemblyscript/blob/master/src/compiler.ts#L396), unless there's a bug.
