### ISSUE TITLE
conditional compilation

### ISSUE THREAD

**Issue by whaqzhzd** [AssemblyScript/assemblyscript#416]
Is there a plan to support conditional compilation?

**Comment by MaxGraey** [comment]
What you mean? AS support constant propagation which simplify expressions and branch ellimination with constants. Also AS support [builtin constants which reflect current compiler options/flags](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/index.d.ts#L40). Also you can define your own constants via cli commands.

**Comment by whaqzhzd** [comment]
```js
#if conditional　1
　code...　1
#elif conditional 　2
　code...　2
```
If condition 1 is met, the conditional branch will be deleted and its implementation will be compiled.
thank you for telling me that I can define constants.

**Comment by whaqzhzd** [comment]
https://webassembly.studio/?f=1t69jv07ozy
Yes, I tried it. The unreachable code has been completely removed, thank you.
