### ISSUE TITLE
Can i use function overload?

### ISSUE THREAD

**Issue by yyh1102** [AssemblyScript/assemblyscript#421]
Does AS support function and class constructor overload? like code below:
```typescript
class Hello{
    constructor(v: string)
    constructor(v: u64) {
        // ....
    }
}
```

But when i compile it i got an error:
```
ERROR TS2391: Function implementation is missing or not immediately following the declaration.

     constructor(v: string)
                          ~
```

**Comment by dcodeIO** [comment]
TypeScript doesn't support this out of the box, but I could imagine that we'd want to support it nonetheless at some point simply because of the lack of an alternative.

**Comment by MaxGraey** [comment]
As I know typescript support this. but only on `d.ts` files. The main problem is handling this case:
```ts
class Hello {
    v: string | u64;
    constructor(v: string)
    constructor(v: u64) {
        this.v = v;
    }
}
```
So most right way is using union types for that:
```ts
class Hello{
    v: string | u64;
    constructor(v: string | u64) {
        this.v = v;
    }
}
```
But union types required multi-values.
But if both overloaded params are references this probably possible for now:
```ts
class Hello{
    constructor(public v: string | u64[]) {
        // ....
    }
}
```

**Comment by yyh1102** [comment]
But AS does not support union types, what i can do to reach the same target as constructor is using different static construct function:
```typescript
class Hello{
    static createWithString(v:string){}
    static createWithU64(v:u64){}
}
```
or some helper creating function:
```typescript
createHelloWithStr(v:string){}
createHelloWithU64(v:u64){}
```
But these code are too ugly~

**Comment by MaxGraey** [comment]
You could do this nicer:
```ts
class Hello {
    public msg: string;
    static from<T>(arg: T): Hello {
       let hello = new Hello();
       // any integer i32/u32/i64/u64 or use "arg instaceof u64" for focus only on u64 type
       if (isInteger<T>()) {
           hello.msg = arg.toString();
       } else if (arg instanceof string) {
          hello.msg = arg as string;
       }
       return hello;
    }
}

var helloWorld = Hello.from("world");
var helloInt32 = Hello.from(0xFF);
var helloInt64 = Hello.from(<i64>-1);
```

**Comment by yyh1102** [comment]
Yeah that's better @MaxGraey Thanks~

**Comment by vincent-tr** [comment]
> You could do this nicer:

This approach is very nice.
I'm looking for a way to lock down allowed argument types set.

With yyh1102's solution, it's by design:
```ts
class Hello {
  static createWithString(v:string){}
  static createWithU64(v:u64){}
}

Hello.createWithString('abc'); // OK
Hello.createWithU64(<u64>(42)); // OK
Hello.createWithStringArray(['abc', 'def']); // obviously not OK
```

With the template solution, is there a way to forbid the last one at compile time like above?

```ts
class Hello {
  static from<T>(arg: T): Hello {
    if (arg instanceof string) {
      const hello: Hello = /* something with arg as string */;
      return hello;
    } else if (arg instanceof u64) {
      const hello: Hello = /* something with arg as u64 */;
      return hello;
    } else {
      // Can we fail at compile time instead here? like c++ static_assert
      throw new Error('Bad argument type');
    }
  }
}

Hello.from('abc'); // OK
Hello.from(<u64>(42)); // OK
Hello.from(['abc', 'def']); // Will compile, but fail at runtime
```

**Comment by MaxGraey** [comment]
You could try to use `ERROR('Bad argument type')` instead `throw new Error('Bad argument type')`. It's [builtin error in compile time](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/diagnostics.ts#L3)

**Comment by dcodeIO** [comment]
Note, though, that it also triggers if the branch it lives in cannot be eliminated at compile time. Typically works with simple checks that can be statically proven, but is not suitable when used in the `else` clause of a check involving an upcast for example, since upcasts become runtime checks, so the `else` branch still compiles, in turn triggering the `ERROR`.

**Comment by vincent-tr** [comment]
Nice design, I was not aware of this builtin compile-time error function.

I understand regarding the dead branch elimination process, it makes perfect sense. As I understand it may also depend on compiler optimization level.
At some point it will be also hard to get easily where the bad template instanciation has been issued, but that's another story.

Thanks a lot for your answers :)

**Comment by MaxGraey** [comment]
> As I understand it may also depend on compiler optimization level.

Only for DCE on backend of compiler. But AS uses early branch and function dead elimination on frontend as well. But only for very obvious cases. In this case that eliminations independent on opt level
