### ISSUE TITLE
Namespaces for types don't work

### ISSUE THREAD

**Issue by vgrichina** [AssemblyScript/assemblyscript#423]
See https://studio.nearprotocol.com/?f=XfZ2mUv for working example.

Basically if you have:
```ts
namespace Outer {
  export class Inner {

  }
}
```
it doesn't look that any references to `Inner` actually work. 

E.g. none of these compile so far:

```ts
let cannotDeclareVariable: Outer.Inner = null;

function cannotReturn(): Outer.Inner {
}

function cannotTakeAargument(arg: Outer.Inner): void {
}
```

Do you have any suggestion on how to fix this?

**Comment by vgrichina** [comment]
Note that if I have a type in separate module and try to do:

```ts
import * as Outer from "./outer";
```

I also get compilation problem when I try to use `Outer.Inner`.

**Comment by vgrichina** [comment]
@dcodeIO looks like first issue is gone, but issue remain with:

```
import * as Outer from "./outer";
```

**Comment by dcodeIO** [comment]
What's the complete code there? Asking because the `Outer` namespace isn't exported in your example, and it should look somewhat like this to work:

```ts
// a.ts
export namespace Outer {
  export class Inner {
  }
}
```
```ts
// b.ts
import * as A from "./a";

A.Outer.Inner; // ?
```
```

**Comment by vgrichina** [comment]
@dcodeIO sorry, here's working example:

https://studio.nearprotocol.com/?f=utg1efv31

**Comment by dcodeIO** [comment]
Thanks, I see now. Doesn't seem that there's a super easy fix for this. The elements map only contains the filespace, but there are no (recursive) aliases of its children which could be looked up by a simple string search. What we'd need instead is a multi-level map to be able to resolve symbols at specific points in the tree without having to rely on a global map, hmm...

**Comment by vgrichina** [comment]
@dcodeIO what does happen when I have, say:

```
import { Inner } from "./outer";
```

and then use `Inner` anywhere. How is `Inner` resolved?

**Comment by vgrichina** [comment]
@dcodeIO BTW, looks like this only fails for variable declaration, but works for usage in function types and params.

These seem to compile fine:

```ts
function cannotReturn(): Outer.Inner {
}

function cannotTakeAargument(arg: Outer.Inner): void {
}
```

but this fails:
```
let cannotDeclareVariable: Outer.Inner = null;
```

**Comment by dcodeIO** [comment]
Will keep this in mind while switching to symbol tables in https://github.com/AssemblyScript/assemblyscript/pull/424. Going to implement proper tree-based lookups there.

**Comment by vgrichina** [comment]
@dcodeIO this one actually also looks related:
https://github.com/AssemblyScript/assemblyscript/issues/429

**Comment by dcodeIO** [comment]
Closing in favor of https://github.com/AssemblyScript/assemblyscript/issues/473, which is our tracking issue for similar related issues now.
