### ISSUE TITLE
Cannot find global `TypedPropertyDescriptor` when using decorators

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#425]
Normally when a difference occurs between `TypeScript` and `AssemblyScript`, we can just use `// @ts-ignore: reason`, and it satisfies the TypeScript compiler issue.

In the case of this kind of error, the problem is reported at the end of the file with no way of turning off this particular issue. 

As a proposed solution, it's possible to add the following type to an `as.d.ts` file locally. This removes the error nicely.

```ts
interface TypedPropertyDescriptor<T> {
  enumerable?: boolean;
  configurable?: boolean;
  writable?: boolean;
  value?: T;
  get?: () => T;
  set?: (value: T) => void;
}
```

However, this removes the error too.

```ts
interface TypedPropertyDescriptor<T> {}
```

Is it possible to include this interface in the [index.d.ts](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/index.d.ts)?

**Comment by dcodeIO** [comment]
Yeah, noticed this as well (more of a TS issue). Should go into `std/assembly/index.d.ts`, probably just the simple version without any fields to silence the error.

**Comment by MaxGraey** [comment]
Create PR for this: https://github.com/AssemblyScript/assemblyscript/pull/426

**Comment by dcodeIO** [comment]
Resolved in https://github.com/AssemblyScript/assemblyscript/pull/426
