### ISSUE TITLE
Figure out how to ship a generated .d.ts with dist files

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#434]
Files in [dist](https://github.com/AssemblyScript/assemblyscript/tree/master/dist) are just build artifacts with a source map currently but don't come with pre-generated type definitions, which would eliminate the need to ship the full sources with an eventual npm package. Challenge here is that while `tsc` is able to generate definitions along a compile step, it splits these up into multiple files so these need to be combined somehow, and possibly wrapped with something commonjs to "just work".

**Comment by Jack-Works** [comment]
What about adding a default auto-generated file `index.d.ts`?
> index.d.ts
```ts
/// <reference path="node_modules/assemblyscript/std/types/assembly/index.d.ts" />
export * from './assembly/index'
```

Result as:

![image](https://user-images.githubusercontent.com/5390719/56876334-39833d00-6a79-11e9-9263-0bc15ca66443.png)

**Comment by deepsweet** [comment]
it seems like `--outFile` + `--declaration` will produce a single `.d.ts` file.

>Concatenate and emit output to single file. The order of concatenation is determined by the list of files passed to the compiler on the command line along with triple-slash references and imports.

**Comment by dcodeIO** [comment]
Unfortunately this doesn't just work with `outDir`, which we are using. Generates multiple declaration files that must be merged somehow. Gave [dts-generator](https://github.com/SitePen/dts-generator) a try now (see commit above), modifying it slightly to fit our needs and fix an issue with `--main` emitting an invalid alias. Let me know if something appears off.

**Comment by webmaster128** [comment]
Is single file a requirement? If you have an index.ts [like this](https://github.com/iov-one/iov-core/blob/v2.0.0-alpha.7/packages/iov-bcp/src/index.ts) in the source you get an definition index [like that](https://github.com/iov-one/iov-core/blob/v2.0.0-alpha.7/packages/iov-bcp/types/index.d.ts) using outDir, which pulls in all the other declaration file. The user then only imports the folder and get access to all exports listed in index.ts.

By the way, you can have [a separate directory for the declaration output files](https://github.com/iov-one/iov-core/blob/v2.0.0-alpha.7/packages/iov-bcp/tsconfig.json#L5-L6), from where you can easily move them around as an entire folder.

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because it has been solved, at least to the extend possible without pulling in additional dependencies, and seems to work well enough.

**Comment by taxilian** [comment]
For others who get here without having found the solution elsewhere:

https://www.assemblyscript.org/compiler.html#command-line-options

Either use the `-d <filename.d.ts>` option or in asconfig.json add `tsdFile: "filename.d.ts"` as a sibling to e.g. "binaryFile" and/or "textFile", etc.

Hope that saves someone else some time =] Awesome project, kudos to those involved
