### ISSUE TITLE
Versioning and publishing

### ISSUE THREAD

**Issue by motss** [AssemblyScript/assemblyscript#442]
I'm new here and am interested in this project to help explore more on WASM and perhaps using WASM in production.

Just realized that this project does not have any versioning or tags in the Github repo and it has been deprecated in NPM. I'm just curious on what the rationals are behind not doing tags for versioning and publishing to NPM.

Plus, WebAssemblyStudio is down. Is this project still being maintained? Should I walk away and look  for alternative?

**Comment by MaxGraey** [comment]
> Plus, WebAssemblyStudio is down. Is this project still being maintained? Should I walk away and look for alternative?

WebAssemblyStudio is maintained by wasdk group. I created [PR](https://github.com/wasdk/WebAssemblyStudio/issues/403) for this issue.

**Comment by dcodeIO** [comment]
Regarding npm: The current version of the compiler hasn't been published on npm yet and it is currently recommended to `npm install AssemblyScript/assemblyscript` from GitHub directly. Rationale is that stuff is still changing and breaking rapidly and the compiler isn't yet ready for general use unless you are interested in spending some time on improving it and fixing compiler bugs yourself as you go.

**Comment by MaxGraey** [comment]
@motss WebAssembly Studio should work now

**Comment by vgrichina** [comment]
@motss I maintain https://github.com/nearprotocol/NEARStudio
https://studio.nearprotocol.com

It's somewhat geared toward smart contract development though.

**Comment by MaxGraey** [comment]
AssemblyScript published on npm and recommended install ways:
```
npm i --save-dev assemblyscript
```
or
```
npm i --save-dev assemblyscript@nightly
```
