### ISSUE TITLE
Website with docs, etc

### ISSUE THREAD

**Issue by vgrichina** [AssemblyScript/assemblyscript#451]
It looks like there are at least 2 different website projects:
https://github.com/AssemblyScript/website-next
https://github.com/AssemblyScript/website-wiki

Both of them actually look pretty decent and I think it'll be nice to have something live on https://assemblyscript.org. 
I guess there should be some continuous deployment process setup for generating docs automatically based on wiki and `std` source code.

**Comment by MaxGraey** [comment]
Docs now available [here](https://docs.assemblyscript.org/)
