### ISSUE TITLE
import externs

### ISSUE THREAD

**Issue by pannous** [AssemblyScript/assemblyscript#46]
how can one import unresolved externs, like in wast:
`(import "console" "log" (func $log_i32 (param i32)))`

**Comment by dcodeIO** [comment]
To achieve the same as in text format above:

```ts
namespace console {
  export declare function log(v: i32): void;
}
```

**Comment by pannous** [comment]
works, wonderful, thanks.

I just need to adopt utf-16 now 
console.logs("HAHA")
  // ACK 0x06 ;)

**Comment by dcodeIO** [comment]
Should now also be possible to rely on 'ambient' flags being passed around properly, like in:

```ts
declare namespace console {
  export function log(v: i32): void;
}
```

**Comment by WolfieWerewolf** [comment]
Great question and answer... thank you both.
