### ISSUE TITLE
SIMD operations and types?

### ISSUE THREAD

**Issue by elviras9t** [AssemblyScript/assemblyscript#468]
There are not enough SIMD operations in AssemblyScript and the corresponding data types. I propose to add either Intrinsics (and adding a standard library with classes), or immediately make data types with SIMD operations.

```ts
// 'simd' is wrapper class with data and operator overloads, also can be casted
// 'i32x4h' is static class with type info and typed operations (if float, so float ops)
export function simd_add(x: simd<i32x4h>, y: simd<i32x4h>): simd<i32x4h> {
  return x + y;
}
```

**Comment by MaxGraey** [comment]
Currently AssemblyScript doesn't implement SIMD but in future names will have simpler type names conventions:
```ts
i32x4
u16x8
f32x4
f64x2
```
which in same type could be just aliases for tuples. `type i32x4 = [i32, i32, i32, i32]`.

**Comment by elviras9t** [comment]
Does (or will) AssemblyScript support SIMD intrinsics (with abstract `v128` type)?

**Comment by MaxGraey** [comment]
Of course. AS always provide low-level intrinsic api for wasm

**Comment by dcodeIO** [comment]
Related: https://github.com/AssemblyScript/assemblyscript/pull/469
