### ISSUE TITLE
WebAssembly module and JavaScript context communication

### ISSUE THREAD

**Issue by elviras9t** [AssemblyScript/assemblyscript#471]
I want to ask question. Can AssemblyScript do export module with function that return pointer to object, which can be managed by wrapper? And create object with pointer inside of AssemblyScript module? It may actual for SIMD-based module for JavaScript/TypeScript.  

```js
// JS wrapper may manager
let a = module.create_f32_ptr(0.0);
let b = module.create_f32_ptr(1.0);
let c = module.create_f32_ptr(); // create indefined
let c_ = module.add_f32(a,b,c); // just return 'c' pointer
let printable = module.get_f32(c_); // extract real value from pointer
```

**Comment by dcodeIO** [comment]
Looks like this can be solved with a

```ts
export class F32Wrapped {
  constructor(public value: f32) {}
  add(other: F32Wrapped): F32Wrapped { return new F32Wrapped(this.value + other.value); }
}`
```

When you return an instance of F32Wrapped to JS, you'll receive the pointer pointing at `value`. When you pass the pointer back to WASM, it will use it as an instance of `F32Wrapped` normally.

**Comment by elviras9t** [comment]
If used original TypeScript, how to make WebAssembly module class as `extends basetype`?

**Comment by dcodeIO** [comment]
In my example, you'd get `module.F32Wrapped.constructor`, `module.F32Wrapped.add` automatically.

**Comment by jtenner** [comment]
@dcodeIO would it be useful to supply a generic way to solve this sort of problem?

```ts
export class Box<T> {
  constructor(value: T) { this.value = value; }
  value: T = null;
}
```

**Comment by elviras9t** [comment]
Here is both TypeScript files, but first is AssemblyScript. I found issue with `a.add(b,c)` there `c` doesn't change value (and probably, passing wrong pointer). Here used AssemblyScript loader. 

```ts
// The entry file of your WebAssembly module.
import "allocator/buddy";


// imported function for logging
export class f32x4 {
  constructor(protected a: f32){
    
  };

  @inline public get(): f32{ return this.a; };
  @inline public set(a: f32): f32x4 { this.a = a; return this; };
  @inline public add(b: f32x4, c: f32x4): f32x4 {return c.set(this.get()+b.get());};
  @inline public sub(b: f32x4, c: f32x4): f32x4 {return c.set(this.get()-b.get());};
}
```

```ts
// client-side code
(async () => {

    const imports = {
        env: { abort(msgPtr, filePtr, line, column) {
            throw new Error(`index.ts: abort at [${ line }:${ column }]`);
        }}
    };

    interface simetypeFn<T> {
        new (value: T): simetype<T>;
    };

    abstract class simetype<T> {
        constructor(value: T){};
        public abstract add(b: simetype<T>, c: simetype<T>): simetype<T>;
        public abstract get(): T;
    };



    const fs = require("fs");
    const loader = require("@assemblyscript/loader");
    const module = await loader.instantiateStreaming(fetch("simdwizard/build/optimized.wasm"), imports);
    let f32x4 = <simetypeFn<number>>module.f32x4;

    // create simd object pointers inside webassembly program
    let a = new f32x4(1.0);
    let b = new f32x4(1.0);
    let c = new f32x4(1.0);
    a.add(b,c);

    console.log(c.get());

})();
```

**Comment by MaxGraey** [comment]
```ts
let a = new f32x4(1.0);
let b = new f32x4(1.0);
let c = new f32x4(1.0);
a.add(b,c);
```
You can't do this currently. Because you allocate objects in javascript GC and pass references instead pointers which should be aasociated with wasm linear memory. Something like this will be available only after [reference types](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md) and [wasm gc](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md) proposals.

Currently you should expose some object creation helper from AS:
```ts
import "allocator/buddy";
export { memory };

export function allocf32x4(value: f32): usize { // or return just `f32x4` but I cast to usize for for illustrative purposes. 
    return changetype<usize>(new f32x4(value));
}
```

And call this on your host side like:
```ts
let a = module.allocf32x4(1.0);
let b = module. allocf32x4(1.0);
let c = module. allocf32x4(1.0);
a.add(b, c);
```

**Comment by elviras9t** [comment]
I mean, if use loader of AS modules, have those issues. Yes, these limitations has when doesn't using that loader.
