### ISSUE TITLE
Rework resolver infrastructure

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#473]
There are multiple issues outlining problems when trying to resolve members (of namespaces), both from within and from outside static scopes. This is caused by our lookup maps not being easily traversable respectively not including aliases for all possible scenarios.

* <del>https://github.com/AssemblyScript/assemblyscript/issues/423 shows what's the issue from outside</del>
* https://github.com/AssemblyScript/assemblyscript/issues/429 describes a mismatch between what's looked up
* <del>https://github.com/AssemblyScript/assemblyscript/issues/144 describes issues with the non-standard way we look up types</del>
* <del>https://github.com/AssemblyScript/assemblyscript/issues/127 shows what's happening from the inside</del>

So, this is a tracking meta issue for all those kinds of problems that should most likely be solved by reworking how our IR is linked with proper nested lookups, possibly also transitioning to symbol tables to avoid having to hash strings over and over again.

There are also multiple other issues that result from a different limitation of the resolver (can't resolve every kind of expression without first compiling it):

* <del>https://github.com/AssemblyScript/assemblyscript/issues/439 displays catastrophic backtracking</del>
* https://github.com/AssemblyScript/assemblyscript/issues/255 can't resolve conditional expressions
* https://github.com/AssemblyScript/assemblyscript/issues/207 can't call method on new expression

The latter are not directly tracked here but mentioned in case it turns out that there are ways to tackle them in one go.

**Comment by dcodeIO** [comment]
Alright, the first batch of resolver rework is merged now. This fixes #423, #144, #127 and potentially #429. Symbol tables have been prepared, but not yet switched to symbols yet.

The other issues mentioned haven't been solved, yet, and remain to do for follow-up PRs.

**Comment by vgrichina** [comment]
@dcodeIO what's proper way to determine if `DeclarationStatement` is top-level export after these changes?

**Comment by dcodeIO** [comment]
Maybe something like:

```ts
if (declaration.is(CommonFlags.EXPORT)) {
  let source = declaration.range.source;
  if (source.isEntry && source.statements.includes(declaration)) {
    ...
  }
}
```

**Comment by vgrichina** [comment]
BTW, what is `MODULE_EXPORT` vs `EXPORT` difference?

**Comment by vgrichina** [comment]
Looks like #429 not fixed yet, I'll try to give repro later.

**Comment by dcodeIO** [comment]
The `EXPORT` flag represents the presence of an `export` token on the declaration, while the `MODULE_EXPORT` flag marks everything that becomes an actual module export, i.e. to apply proper integer wrapping on exported WASM functions. But: The latter flag is [applied right after program initialization is complete](https://github.com/AssemblyScript/assemblyscript/blob/master/src/program.ts#L823) and not yet available in the parsing stage. An `afterInitialize` hook that is called once program IR is set up might help, that would have been my next suggestion, but except full information there's not much that can be modified at this stage in the compilation progress.

**Comment by MaxGraey** [comment]
@dcodeIO it seems all issues in top message already solved. But I understand that improvements on resolver still going on?
