### ISSUE TITLE
Function declared with return type should emit error when nothing return

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#475]
**EDITED**

This examples successfully compile:
```ts
export function foo(): i32 { return; }
```
But expected:
```
error TS2355: A function whose declared type isn't 'void' must return a value.
```

**Comment by dcodeIO** [comment]
It looks like these functions aren't actually compiled due to not being referenced / exported. This yields the proper diagnostics for example:

```ts
export function foo(): i32 {}
```

**Comment by MaxGraey** [comment]
For sure! So this is only relevant for the second case.
