### ISSUE TITLE
Printing Stack Trace is not possible

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#484]
I am currently in the process of developing a testing library, and whenever I call the provided `assert()` function, the `env.abort` function reports the filename where the `assert()` function is located.  This is unfortunately not the place where the `expect()` function was called, and the output is not meaningful to developers.

Can we use this as a tracking issue to develop meaningful stack traces?

**Comment by willemneal** [comment]
This is hard because AS has such a minimal runtime and this will probably become provided by wasm when there is exception support.  So perhaps this should be a special debug version that does trace the stacks.

**Comment by jtenner** [comment]
I actually found a solution for this. It was very hacky though.

**Comment by vgrichina** [comment]
@jtenner what did you end up doing?

**Comment by jtenner** [comment]
In `as-pect` I wrote some glue code that runs functions with the following signature:

```
type NoPropsNoReturnCallback = () => void;
```

Then in my glue code, I did stuff like this:

```ts
  /**
   * This is a web assembly utility function that wraps a function call in a try catch block to
   * report success or failure.
   *
   * @param {number} pointer - The function pointer to call. It must accept no parameters and return
   * void.
   * @returns {1 | 0} - If the callback was run successfully without error, it returns 1, else it
   * returns 0.
   */
  tryCall(pointer: number): 1 | 0 {
    if (pointer === -1) return 1;

    var func = this.wasm!.getFunction(pointer);
    try {
      func();
    } catch (ex){
      this.stack = this.getErrorStackTrace(ex);
      return 0;
    }
    return 1;
  }
```
Now in order to LOG the current stack trace, I had to call into javascript to get it, throw an error, then filter the lines that contain `wasm` in the string.

```ts
  /**
   * Gets a log stack trace.
   */
  getLogStackTrace(): string {
    try {
      throw new Error("Get stack trace.");
    } catch (ex) {
      return ex.stack.toString()
        .split("\n")
        .slice(1)
        .filter(wasmFilter)
        .join("\n");
    }
  }
```

It was hacky, and I'm not proud of it.

**Comment by vgrichina** [comment]
@jtenner interesting, so basically WASM runtimes embedded into JS VMs already provide wasm-side stack traces?

**Comment by jtenner** [comment]
Yes. That was as good as I could get it. I'm currently working on using generated sourcemaps to display more relevant information, but it appears that sourcemaps are broken on the master branch, at least pre-resolver commit.
