### ISSUE TITLE
Using asc typing error

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#485]
![image](https://user-images.githubusercontent.com/3761339/52650338-0dafdc80-2eb8-11e9-92b6-b1109b51556f.png)

Copying and pasting the example in the wiki results in a typescript tooling error.

**Comment by dcodeIO** [comment]
Looks like `.toBuffer` shouldn't have made it into the declaration, yeah. It's used internally when working with an in-memory stream only.
