### ISSUE TITLE
Replace throw new Error("not implemented") by compiler errors

### ISSUE THREAD

**Issue by vgrichina** [AssemblyScript/assemblyscript#487]
It's very hard to debug "not implemented" message without context on what in source code triggered it.

See e.g. https://studio.nearprotocol.com/?f=ucpigts4w

**Comment by dcodeIO** [comment]
There are just a few occasions of throwing in the compiler itself and these usually don't trigger at all. Last time I checked this error was thrown by an outdated Binaryen build (possibly related to a caching issue on jsdelivr).

**Comment by MaxGraey** [comment]
@vgrichina 
See fixed version:
https://studio.nearprotocol.com/?f=pwkqd78je

Actually `10 ** dnaDigits` always calculate as `Math.pow(10, dnaDigits)`and return `f64` type so it equivalent to `1.0e17`. But even if you assign it to `u64` later you modulate it with `u32`. So I commented this lines.

@dcodeIO need better describe this errors by compiler

**Comment by dcodeIO** [comment]
Oh, so, this is actually something thrown by us?

**Comment by MaxGraey** [comment]
@dcodeIO 
this should throw error:
```ts
const m = 16;
var a = 10 ** m;
var t: u32 = 1234;
var r = t % a;
```
But currently compile without errors.
But if we change `u32` to `u64`. We do error:
```ts
const m = 16;
var a = 10 ** m;
var t: u64 = 1234;
var r = t % a;
```
```
> ERROR TS2365: Operator '%' cannot be applied to types 'u64' and 'f64'.

 var r = t % a;
```

**Comment by vgrichina** [comment]
@dcodeIO @MaxGraey there are quite a few cases in compiler code like that (where `throw new Error("not implemented")` is used).

All of them should ideally at least point out source code line with problem, even if it's hard to provide meaningful message at the moment IMO.

**Comment by jtenner** [comment]
Can't you just use

```
assert(false, "not implemented.");
```

**Comment by dcodeIO** [comment]
Looking through the sources after the resolver PR again, it seems that there are no "not implemented"s left that aren't intended stubs or part of the unfinished decompiler.
