### ISSUE TITLE
Loader helpers could be namespaced

### ISSUE THREAD

**Issue by JamesMilnerUK** [AssemblyScript/assemblyscript#490]
At the moment the loader helpers put themselves onto the returned module, with a lot of potential for naming clashes. It seems like it would be sensible to namespace them somehow rather them attaching them onto the returned module?

To understand what I'm talking about:

```javascript

instantiateStreaming(fetch("build/optimized.wasm"))
    .then(wasmModule => { // Type: ASUtil
         // wasmModule.getString  - Loader helper
         // wasmModule.add - Our exported function

```

**Comment by dcodeIO** [comment]
Related, and most likely fixed within: https://github.com/AssemblyScript/assemblyscript/pull/411

**Comment by JamesMilnerUK** [comment]
@dcodeIO did you end up reverting that in the end? Looking at it those functions would be namespaced to `memory` or `table` respectively.

**Comment by dcodeIO** [comment]
Yeah, had to revert it unfortunately. I am also fine with adding this to the existing loader, i.e. entirely avoiding low-level TypeScript hell, if someone is interested in doing so.
