### ISSUE TITLE
How to interact with JS references (f.e. DOM)?

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#492]
It's not completely clear. I know there's at least one example (f.e. canvas-as).

It'd be nice if there was a specific section regarding this in the Wiki, containing the most recommended approach.

**Comment by MaxGraey** [comment]
I don't think this is necessary with MVP without "reference proposal". Without `anyref` we could care about a lot of things and glue code which produce overhead. Instead of that better approach leave all interaction with DOM on host currently and just call some intensive computation from wasm. But if you want see advanced interop usage I recommend see `as2d` project: https://github.com/as2d/as2d

**Comment by jtenner** [comment]
I will do a very large writeup on the plane today that describes how to do things efficiently in the browser. I had also started work on a Dom sys library that wraps dom element references, and indexes them on the browser side. However, I didn't think the solution was viable. Once reftypes and multivalue returns are standardized, things will get way easier. I plan on porting a virtual dom library like preact to assemblyscript.

For now, we wait.

**Comment by MaxGraey** [comment]
@jtenner porting virtual diff for Preact without "references proposal" coudn't get any benefits because preact use single pass approach which required DOM access. See Jason Miller's twit: https://twitter.com/_developit/status/1096420433145008128

**Comment by jtenner** [comment]
If virtual dom is just a bunch of fibers, we can create a buffer of instructions just like as2d does, and ship it to Javascript to be performed.

Need to think on this for a while.

**Comment by taylorgoolsby** [comment]
Is the "reference proposal" you are refering to the same thing as the now [standardized](https://webassembly.org/roadmap/) ["Reference Types" proposal](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md)?
