### ISSUE TITLE
[Bug] i32 variable instanceof f32 compiles to true

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#493]
When testing my assertion library, I found this gem.

```ts
    var i: i32 = 0;
    log<bool>((i instanceof f32) || (i instanceof f64)); // logs the value 1 in the console
```

Expected behavior should return false. 

As a reference for the assertion that lead me to this issue, I have some lines in my code that check to see if the generic parameter is instanceof a float value.

```ts
  it("should throw if value type is not a float", (): void => {
    expectFn((): void => {
      expect<i32>(0).toBeCloseTo(0);
    }).toThrow("integer values should throw on toBeCloseTo assertions");
  });
```

**Comment by MaxGraey** [comment]
Can confirm that. Also this affect to several other types

**Comment by dcodeIO** [comment]
Appears to be caused by using `isAssignableTo` as the check here instead of strict check.
