### ISSUE TITLE
Support `export * as my_variable_name`

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#498]
relates to #27 

The issue above is fixed, but we still get errors for `export * as`...

<img width="424" alt="screen shot 2019-02-20 at 9 52 00 pm" src="https://user-images.githubusercontent.com/1448289/53146620-c7164e00-3559-11e9-973f-42c9cdb692b0.png">

**Comment by torch2424** [comment]
cc @dcodeIO Found some feedback from creating #499

**Comment by dcodeIO** [comment]
Is `export * as ...` actually a thing? Whenever I enter that into vscode, it becomes all red, leaving me with the assumption that the intended use here is `import * as foo from "./bar"; export { foo };`. (but I wondered about that myself)

**Comment by torch2424** [comment]
@dcodeIO You know what, you may be right, maybe I dreamt it that it was valid syntax. 😂 Feel free to close if it is not.

**Comment by torch2424** [comment]
Oh wait yup, it's only a proposal: https://github.com/tc39/proposal-export-ns-from

And can be achieved with: https://stackoverflow.com/questions/42728140/is-it-possible-to-export-as-foo-in-typescript

I'll go ahead and close this, thanks for catching that! 😄
