### ISSUE TITLE
[Feature Request]: Support for nameof<T>() compile time constant

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#513]
It would be great to have a compile time constant that compiles to the string name of the generic type `T` in the function call.

Alternatives might be...

```ts
nameof<T>();
classnameof<T>();
name<T>();
classname<T>();
```

This is useful for debugging, logging, and test libraries.

**Comment by jtenner** [comment]
Any thoughts on this? If given some more information on where this exists in the compiler, I can make the change myself.

**Comment by dcodeIO** [comment]
Sure, we can add such a builtin. Needs to create a static string in memory and evaluate to its offset. With the runtime currently in flux, I'd wait for that to land first though :)

**Comment by jtenner** [comment]
Already fixed. Thanks for your confidence in me. I couldn't have implemented it without your guidance. 👍
