### ISSUE TITLE
Remove expression variant from isInteger, isFloat etc. for consistency

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#531]
Currently, most static type evaluation builtins take either a type argument or an argument, but the second case is unsound in that the expression is evaluated for its type but ultimately ignored. For example, the following code will never execute the expression because the call's result is supposed to evaluate to a constant with no place to put the expression:

```ts
var a: i32 = 0;
if (isInteger(a = 1)) {
  // a is 0
}
// a is 0
```

I therefore propose to remove the second case. Or does anyone actually **have to** use the second case for a good reason, somewhere?

**Comment by jtenner** [comment]
Argument for using expressions in the macro: running AS code transpiled to Javascript can function like AS can. Downside, we lose type information about float VS integer etc

**Comment by dcodeIO** [comment]
Hmm. Well. The obvious alternative is to emit an error or a warning if the expression has side effects. Doesn't eliminate the unsoundness, though.
