### ISSUE TITLE
Managing objects shared with JS

### ISSUE THREAD

**Issue by gliese1337** [AssemblyScript/assemblyscript#534]
I am attempting to implement multiple libraries that involve keeping lots of data for calculations in WASM memory, while "mirror objects" in JS-land hold on to pointers to that data so it can be re-extracted as needed. However, I also need the ability for the JS side to deallocate those objects from time to time. From the _Memory Layout & Management_ page in the wiki, it appears that if I just return an object from an exported AssemblyScript function, the result in JS-land should be a pointer to where that object lives in WASM memory. I can only presume that that is how objects are passed around internally as well, but it is not possible to pass arbitrary objects to `memory.free()`--and since AssemblyScript doesn't recognize `any` or `unknown` types, there's no way to coerce an object into a u32 pointer type to pass to `free`, either. So, *is* there any way to indicate to one of the allocators that an arbitrary object should be freed?

If not, well,  ideally I wouldn't want to use manual memory management anyway, so that *shouldn't* be a big deal. However, the gc options also seem fairly limited. So, if I'm passing references to objects out into JS-land, is there any way to indicate to a garbage collector that those references are in fact roots and should not be collected, and later to indicate when they have been freed on the JS side?

**Comment by dcodeIO** [comment]
Freeing an object (that must not be managed by GC, which I assume is the case here - you aren't using `collector/itcm` right?) can be done through:

```ts
memory.free(changetype<usize>(theObject));
```

or from the JS side if you do

```ts
export { memory };
```

through

```js
myModule["memory.free"](somePointer);
```

This is horribly unsafe of course and special precautions must be taken not to free anything that is still used by the module. There might also be additional references within a to-be-free'd object that must be free'd (e.g. an array's backing arraybuffer) but it might sometimes be hard to determine whether these references are still used. That's where GC comes into play usually.

Nonetheless, if you're fine with doing unsafe stuff like that, the compiler doesn't attempt to limit you currently.

**Comment by gliese1337** [comment]
I see. I may be able to make that work manually, then, but is there any plan for such an interface to GC? Even if I do get the manual approach working, I am hesitant to release something using that approach to the public, since it is, as you say, horribly unsafe.
