### ISSUE TITLE
opencollective-postinstall breaks package installation

### ISSUE THREAD

**Issue by vgrichina** [AssemblyScript/assemblyscript#536]
See e.g. https://gitlab.com/vgrichina/assemblyscript-json/-/jobs/174488016

**Comment by dcodeIO** [comment]
Hmm, this has been added lately while I was trying out their automatic generator. Should work, though, as it's in package.json [here](https://github.com/AssemblyScript/assemblyscript/blob/master/package.json#L18). Or can't it [execute](https://github.com/AssemblyScript/assemblyscript/blob/master/package.json#L56)?

**Comment by MaxGraey** [comment]
@vgrichina could you try latest commit?

**Comment by jtenner** [comment]
Adding `|| exit 0` fixes the problem for me.

**Comment by vgrichina** [comment]
Wasn't this fixed already?

**Comment by MaxGraey** [comment]
It should fixed. Actually we waiting for confirmation from your side. Is it fixed for you?

**Comment by vgrichina** [comment]
I think it is
