### ISSUE TITLE
Enums required explicit initialization

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#541]
```ts
export enum Action {
  A,
  B,
  C
};
```
Output errors:
```
ERROR TS1061: Enum member must have initializer.

   C,
    ^
```
But with two members works:
```ts
export enum Action {
  A,
  B,
};
```
as well as:
```ts
export enum Action {
  A = 0,
  B = 1,
  C = 2,
};
```

**Comment by willemneal** [comment]
Yeah I had the same issue.  I think it would also be a good idea if enums without specific values were set to be globally unique values.  For example your Action enum would have a unique base value.  That way `Action.A` and `OtherAction.A` would not be equal.

**Comment by MaxGraey** [comment]
Not sure this by spec. By the way Typescript diagnostics show pretty strange warnings for this [example](https://www.typescriptlang.org/play/#src=const%20enum%20Action1%20%7B%0D%0A%20%20%20%20A%2C%0D%0A%20%20%20%20B%2C%0D%0A%20%20%20%20C%0D%0A%7D%0D%0A%0D%0Aconst%20enum%20Action2%20%7B%0D%0A%20%20%20%20A%2C%0D%0A%20%20%20%20B%2C%0D%0A%20%20%20%20C%0D%0A%7D%0D%0A%0D%0Aconsole.log(Action1.A%20%3D%3D%20Action2.A)%3B%0D%0Aconsole.log(Action1.B%20%3D%3D%20Action2.B)%3B%0D%0Aconsole.log(Action1.C%20%3D%3D%20Action2.C)%3B)

> "This condition will always return 'false' since the types 'Action1.A' and 'Action2.A' have no overlap."

But it always "true" instead =)

**Comment by dcodeIO** [comment]
Could you explain how this differs from the tests here? https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/enum.ts Or is this related to trailing commas only?

**Comment by MaxGraey** [comment]
Hard to explain. But this is true: https://webassembly.studio/?f=dpedv4jwjt

**Comment by MaxGraey** [comment]
It seems if `enum` hasn't global (in index file) export keyword this happened
