### ISSUE TITLE
tlsf allocator cannot grow its memory

### ISSUE THREAD

**Issue by DieMyst** [AssemblyScript/assemblyscript#548]
I reproduced it in a fork of `json parser` example:
https://github.com/fluencelabs/assemblyscript-json

to check bug run `npm run test`

Memory is initialized in `helpers.ts` as `new WebAssembly.Memory({ initial: 2, maximum: 1000 }`.
In `roundtrip.spec.as.ts` JSON is serialized-deserialized 500 times. 
This parser is leaking, so the memory size grows with each iteration and the program will throw an exception:
```
  Error {
    message: 'Abort called at ~lib/allocator/tlsf.ts [483:2]',
  }
```

There will be no exceptions if increase initial memory pages or change allocator to `buddy` or `arena`.

**Comment by dcodeIO** [comment]
The error looks like it could be caused by memory corruption as well because the failing assertion triggers after memory, obviously with a corrupt header, was obtained. Very strange that it depends on initial page size, though.

Other than that, stuff like this is notoriously hard to debug, and I wish there was a cleaner way to reproduce this than forking an entire repo with custom tooling. I only get a bunch of errors when I try `npm i && npm test` there for instance.

**Comment by dcodeIO** [comment]
When deleting the assemblyscript dependency and instead linking my local copy of master to it, I get this output:

```
[str]: --------{}
  √ Create decoder
  √ Should handle empty object
  √ Should handle empty object with whitespace
  √ Should handle int 32
  √ Should handle int 32 sign
  √ Should handle true
  √ Should handle false
  √ Should handle null
  √ Should handle string
  √ Should handle string escaped
  √ Should handle string unicode escaped 1
[str]: --------{ } {}
[str]: --------{"int":4660}
[str]: --------{"int":-4660}
[str]: --------{"val":true}
[str]: --------{"val":false}
[str]: --------{"val":null}
[str]: --------{"str":"foo"}
[str]: --------"\"\\\/\n\t\b\r\t" "\"\\/\n\t\b\r\t"
[str]: --------"\u0022" "\""
[str]: --------"\u041f\u043e\u043b\u0442\u043e\u0440\u0430 \u0417\u0435\u043c\u043b\u0435\u043a\u043e\u043f\u0430" "Полтора Землекопа"
[str]: --------{"str":"foo","bar":"baz"}
[str]: --------{"str":"foo","obj":{"a":1,"b":-123456}}
[str]: --------[]
[str]: --------[1,2,3]
[str]: --------[[1,2,3],[4,[5,6]]]
[str]: --------{"str":"foo","arr":[{"obj":{"a":1,"b":-123456}}]}
[str]: -------- { "str":"foo","obj": {"a":1, "b" :
 -123456} }  {"str":"foo","obj":{"a":1,"b":-123456}}
  √ Should handle string unicode escaped 2
  √ Should multiple keys
  √ Should handle nested objects
  √ Should handle empty array
  √ Should handle array
  √ Should handle nested arrays
  √ Should handle nested objects and arrays
  √ Should handle whitespace

  19 tests passed
```

**Comment by dcodeIO** [comment]
When changing `allocator/arena` to `allocator/tlsf` in `tests/assembly/roundtrip.spec.as.ts` it fails with

```
  × Should handle whitespace Error thrown in test

  1 test failed

  Should handle whitespace

  assemblyscript-json\tests\utils\helpers.ts:73

   72:         if (msgPtr) {
   73:           throw new Error(
   74:             `Abort called by reason "${ getString(msgPtr, buffer) }" at ${ getString(filePtr, buffer) } [${ li…

  Error thrown in test:

  Error {
    message: 'Abort called by reason "Unexpected control character" at assembly/decoder.ts [202:12]',
  }

  abort (tests/utils/helpers.ts:73:17)
  Object.wrap [as shouldHandleWhitespace] (tests/utils/loader.js:210:12)
```

**Comment by DieMyst** [comment]
Sorry, I forgot to tell that code to reproduce this is not in master branch: https://github.com/fluencelabs/assemblyscript-json/tree/tlsf-bug

And I agree that this format of the issue is not convenient. I'll try to reproduce this in a short example in the coming days.

**Comment by michaelvoronov** [comment]
It seems that it should be
let pagesWanted = max(`2`*pagesBefore, pagesNeeded)
[here](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/allocator/tlsf.ts#L472). (It is related to this issue but doesn't solve it).

**Comment by dcodeIO** [comment]
`memory.grow` takes the additional number of pages to grow by. Hence, growing by the current size of memory doubles it.

**Comment by michaelvoronov** [comment]
Yes, you are absolutely right, thank you for answer!
