### ISSUE TITLE
Support IIFE

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#552]
```ts
(function (): void {})();
(function foo(): void {})();
var result = (function (): i32 { return 1; })(); 
```

**Comment by dcodeIO** [comment]
Can confirm that this isn't implemented yet. Somewhat linked to the resolver not being able to resolve any sort of expression yet, with a special twist in that function expressions, before being compiled, are represented by a declaration only with no signature whatsoever yet that could be wrapped in a function target (here: what we'd expect the resolver to return).

Possible solutions are 1) add special code for this or 2) wait a bit for the compiler to become dual pass (check first, then compile).

**Comment by MaxGraey** [comment]
It's pretty rare case in typescript so probably first approach makes more sense for current. Of course if this not require a lot efforts

**Comment by MaxGraey** [comment]
What about just transpile IIFE? Like transform from this:
```ts
(function (): void {})();
```
to
```ts
function _dummy$1_() {
}
_dummy$1_();
```
and from:
```ts
var result = (function (): i32 { return 1; })(); 
```
to:
```ts
var _dummy$2_ = function (): i32 { return 1; };
var result = _dummy$2_();
```
WDYT?

**Comment by MaxGraey** [comment]
Should support now
