### ISSUE TITLE
mass?

### ISSUE THREAD

**Issue by zaoqi** [AssemblyScript/assemblyscript#555]
```
ERROR TS1005: 'null' expected.

 export type LangValDelayType = LangValType.delay_evaluate_t | LangValType.delay_builtin_func_t
| LangValType.delay_builtin_form_t | LangValType.delay_apply_t
...
```
https://gitlab.com/the-language/the-language/blob/18536043a5b610905abf8db2bad56d6c6f0a8512/core/arch/typescript/lang.ts

**Comment by zaoqi** [comment]
```
npx asinit .
cd assembly/
rm index.ts ; ln -s ../../typescript/lang.ts ./index.ts
npm run asbuild
```

**Comment by MaxGraey** [comment]
AssemblyScript currently not compile any typescript source code due to some limitations that's why it subset. One of them is "union types" except "nullable types" like "type ArrOrNull = Array<i32> | null"
