### ISSUE TITLE
Empty array literal sometimes shared

### ISSUE THREAD

**Issue by singpolyma-shopify** [AssemblyScript/assemblyscript#565]
I'm experiencing a case where this code:

    let new_items: Array<Item> = [];

as a local variable that I `push` to appears to have content from previous runs of the function when I call the function again. (That is, `[]` is acting as a singleton).  Switching only that line to say:

    let new_items = new Array<Item>();

Fixes it.

**Comment by MaxGraey** [comment]
Yes, this known issue

**Comment by dcodeIO** [comment]
This should be fixed in the runtime branch btw
