### ISSUE TITLE
fiddles fails to build as well as Empty AssemblyScript project

### ISSUE THREAD

**Issue by mityok** [AssemblyScript/assemblyscript#568]
Throws en error:
[error]: Task build failed: Module name "assemblyscript/bin/asc" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded

**Comment by MaxGraey** [comment]
This in WebAssembly Studio?

**Comment by mityok** [comment]
Yes, it's in WebAssembly Studio, although the C project complies successfully

**Comment by MaxGraey** [comment]
WAS should be work now
