### ISSUE TITLE
Simple code that causes out-of-bounds load

### ISSUE THREAD

**Issue by singpolyma-shopify** [AssemblyScript/assemblyscript#569]
This code:

```
import "allocator/arena";

export function run(dummy: i32): i32 {
    let sarr: Array<String> = ["tag1", "tag2", "tag3", "tag4", "tag5", "tag6", "tag7", "tag8", "tag9", "tag10"];
    let amap = new Map<String, i32>();
    let arr = new Array<String>();

    for(let i = 0; i < sarr.length; i++) {
	let x = sarr[i];
        arr.push(x);
        amap.set(x, 1);
    }

    return 0;
}
```

Is resulting in an out-of-bounds load for me, panicing the WASM VM.  Commenting out *either* of the `arr.push` or `amap.set` lines makes the panic go away.

**Comment by dcodeIO** [comment]
Gave this snippet a try using my local copy of the [runtime branch](https://github.com/AssemblyScript/assemblyscript/pull/535) and it appears that the issue has been fixed there. I stumbled upon a few problems there, and this might have been one of them.

**Comment by MaxGraey** [comment]
@singpolyma-shopify
Are this issue still present in latest upstream?
I tried reproduce this on browser environment but can't see any issues:
https://webassembly.studio/?f=w24qrg5bygi
