### ISSUE TITLE
Explicitly restrict exporting generic functions for entry file

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#570]
main.ts:
```ts
export function foo<T>(a: T): T {
  return a;
}
```
Currently generate wasm module without `foo` function.
Expected: should be compiler error about exporting generic functions/classes are not allowing.

**Comment by dcodeIO** [comment]
What currently happens is, if a concrete instance of it, let's say `foo<i32>`, is used and thus compiled somewhere in the module, it becomes exported. Not sure if that's useful or not. Restricting generic exports makes sense to me as well.

**Comment by MaxGraey** [comment]
Yeah. May be not restrict as error but print warning. Hmm...
