### ISSUE TITLE
Lazily load library

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#572]
Currently when adding libraries, each file found in the library paths is parsed.  However, this should be done when a file is referenced.  I ran into this problem because the compiler I'm writing for [wasmos](https://github.com/WebAssemblyOS/wasmos) finds all `**/assembly` folders in a projects `node_modules` and adds it as a library path.

**Comment by dcodeIO** [comment]
One reason for this is that there could be `@global` elements in a library file that would be missed otherwise.. Not too happy with this mechanism myself, though.

Related: https://github.com/AssemblyScript/assemblyscript/issues/448

**Comment by willemneal** [comment]
So we could have that each `globals.d.ts` found in the list of libraries is always read in.  Otherwise just  parse in imported files as referenced.  

I'm also experimenting with lerna and moving dependencies like `typescript` to the top level package.  However, different tooling expects there to be local binaries like `ts-node` or `tsc`.

To solve this after the `lerna bootstrap` step, which symlinks all local dependencies, I also symlink each of the contents of  top level `node_modules/.bin/` to each package's `node_modules/.bin`.  

Taking this a step further, in each package I create a hidden directory `node_modules/.assembly/`, and create a symlink for each project's assembly folder.  Then just add `node_modules/.assembly` to the library path.  I realized that when I was adding just the assembly folders it would just treat each `index.ts` in the path to be the same as every `index.ts`.

**Comment by dcodeIO** [comment]
Another solution to this might be to not add everything to lib paths, but to have a fallback handler in case a file is not found in either baseDir or libDir that then looks up the file in node_modules etc.
