### ISSUE TITLE
Compilation problem with exported constant enums with several members

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#574]
This minimal example can't compile currently and throw internal error:

foo.ts:
```ts
export const enum Foo {
  Boo1,
  Boo2,
}
```
main.ts:
```ts
import { Foo } from './foo';

export function test(): i32 {
  return <i32>Foo.Boo1;
}
```
[link to fiddle](https://webassembly.studio/?f=rsaalbs9nbq)

But this become compilable if we removing `const` keyword or if `Foo` enum contain only one field `Boo1` or explicitly assigning values like:
```ts
export const enum Foo {
  Boo1 = 0,
  Boo2 = 1,
}
```

**Comment by DuncanUszkay1** [comment]
Solved with https://github.com/AssemblyScript/assemblyscript/pull/1120#issuecomment-591472322, should be ready to close
