### ISSUE TITLE
`ts-node` marked as devDependency

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#578]
Trying to use the compiler on travis for testing `as-pect` yields this error.

```
Error: Cannot find module 'ts-node'
    at /home/travis/build/jtenner/as-pect/node_modules/assemblyscript/cli/asc.js:36:7
    at Object.<anonymous> (/home/travis/build/jtenner/as-pect/node_modules/assemblyscript/cli/asc.js:50:3)
---
Error: Cannot find module './assemblyscript'
    at eval (eval at <anonymous> (/home/travis/build/jtenner/as-pect/node_modules/assemblyscript/cli/asc.js:42:26), <anonymous>:1:1)
    at /home/travis/build/jtenner/as-pect/node_modules/assemblyscript/cli/asc.js:42:26
    at Object.<anonymous> (/home/travis/build/jtenner/as-pect/node_modules/assemblyscript/cli/asc.js:50:3)
```

**Comment by MaxGraey** [comment]
if you need `ts-node` in your project - just add/install it to your `dependencies`. In AS `ts-node` not need for production, only for dev process

**Comment by jtenner** [comment]
But I don't directly use `ts-node`. I consume the `asc` module just like the example here:

https://github.com/AssemblyScript/assemblyscript/tree/master/cli#api

**Comment by MaxGraey** [comment]
`asc` used `ts-node` [here](https://github.com/AssemblyScript/assemblyscript/blob/master/cli/asc.js#L36) as fallback when `dist` folder is empty. Check your dist folder

**Comment by jtenner** [comment]
What are you talking about? I'm consuming the asc compiler directly as instructed in the readme, and the test fails on Travis after a fresh npm install. I had to manually include `ts-node` as a direct dependency of `as-pect` to fix this.

https://travis-ci.org/jtenner/as-pect/jobs/521256291

I fixed that issue and found a brand new one.

**Comment by jtenner** [comment]
Turns out the real problem was that my local version of assemblyscript did not match the version installed by package-lock.json. Thanks again. I'm going to refrain from submitting issues for a long while. It seems like every issue I raise is my fault :).
