### ISSUE TITLE
Implement NativeMath/NativeMathf.sin/cos/tan

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#58]
Tracking issue for the work @MaxGraey is planning to do.

**Comment by feedthejim** [comment]
What's the status on this issue?

**Comment by MaxGraey** [comment]
In progress. With latest compiler changes I can finish argument reduction with huge lookup table. @dcodeIO wdyt about LUT for now?

**Comment by dcodeIO** [comment]
Can't be avoided here I guess. Should be ok when using that wrap-in-a-function trick so it isn't compiled when not needed.

**Comment by MaxGraey** [comment]
Great!

@feedthejim for now you could implement your own `sin/cos/tan` if you don't need proper precision, another way is just import they from JS host
