### ISSUE TITLE
Example of using shared memory

### ISSUE THREAD

**Issue by kazhoyan** [AssemblyScript/assemblyscript#583]
Could you add a short example of how to pass shared memory object / buffer to AssemblyScript loader from different workers? And if it's different from using SharedArrayBuffer, an example of passing it from main thread to workers.

**Comment by dcodeIO** [comment]
Afaik there should be an example somewhere in [this PR](https://github.com/AssemblyScript/assemblyscript/pull/278), which didn't yet make it into master.

**Comment by kazhoyan** [comment]
Didn't know it's not supported yet.
Still thanks! Like what you do very much with AssemblyScript

**Comment by dcodeIO** [comment]
The individual features from this PR have been merged separately already, like declaring memory as shared and atomic instructions, but there's no example yet :)

**Comment by kazhoyan** [comment]
Eventually made it work by running `node` with `--experimental-wasm-threads`.
(Forgot to mention I'm trying with Node.js first).

But now I'm stuck with `atomic.wait` and `atomic.notify`.
Calling them like this: `atomic.wait<i32>(0, 0, -1)` and `atomic.notify(ptr, 1)`.

So, `asc` builds the binary successfully and without warnings.
But then loading the .wasm with `assemblyscript/lib/loader.instantiateBuffer` fails.
It complains about the atomic's opcode:
`CompileError: WebAssembly.Module(): Compiling wasm function #18:assembly/module/waitTest failed: invalid atomic opcode @+3851`.

Other atomics work, and after removing calls to `wait` and `notify` app runs normally.

I'm using node v11.15.0 and asc v0.6.0 (installed with npm).

**Comment by MaxGraey** [comment]
`atomic.wait` / `atomic.notify` work only in WebWorker (not in main thread). Also `11.15.0` may not support wasm's `wait / notify`

**Comment by dcodeIO** [comment]
Also note that even latest stable node is usually behind a bit on experimental WASM features, but https://github.com/nodejs/node-v8 might help.

**Comment by kazhoyan** [comment]
Just to clarify - it worked with canary node-v8.
I guest stable node simply doesn't support WASM atomics.

Thank you!

**Comment by matthiasg** [comment]
Should it work now ? With node 14 or 15?
