### ISSUE TITLE
asinit scaffolding script command not found after assemblyscript install.

### ISSUE THREAD

**Issue by tarsupin** [AssemblyScript/assemblyscript#584]
Prior to running into the issue, I ran this:

```
$ npm install --save-dev AssemblyScript/assemblyscript

> assemblyscript@0.6.0 postinstall D:\Web\nodeTesla\nexus\client\node_modules\assemblyscript
> opencollective-postinstall || exit 0

Thank you for using assemblyscript!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/assemblyscript/donate

+ assemblyscript@0.6.0
updated 1 package and audited 23 packages in 484.4s
found 0 vulnerabilities
```

I haven't seen any bin files or scripts, and the package.json file wasn't edited other than to includ "assemblyscript": "github:AssemblyScript/assemblyscript". But, per the instructions with scaffolding, I ran "asinit ."

```
$ asinit .
bash: asinit: command not found
```

I get nothing, and I haven't been able to find any script that would in fact provide this scaffolding. Are there instructions not being included?

**Comment by dcodeIO** [comment]
After the steps you have taken, the `asinit` file should be in `./node_modules/assemblyscript/bin/asinit`. Have you tried `npx asinit` instead?

**Comment by tarsupin** [comment]
Yes, it looks like `npx asinit .` works as intended. Thank you.
