### ISSUE TITLE
radix in toString

### ISSUE THREAD

**Issue by bowenwang1996** [AssemblyScript/assemblyscript#586]
Is there plan to support radix in `toString` for integer types?

**Comment by dcodeIO** [comment]
Of course, yeah, is [on todo](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/number.ts#L264) but afaik nobody is currently working on it. Code responsible for this and similar things lives in [std/internal/number](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/internal/number.ts).

**Comment by MaxGraey** [comment]
But this change little bit with upcoming rework runtime (#535) branch

**Comment by darky** [comment]
Is any workaround exists for it?

**Comment by letmaik** [comment]
This is working now, but if you wrap it in a function then the type must not be `number` but one of the explicit ones like `u8`. I think this is a bug.
```js
function hex(n: number): string {
  return '0x' + n.toString(16)
}
```

**Comment by MaxGraey** [comment]
`number` in AssemblyScript is just alias of `f64`. We can't implement conversions from float in hexadecimal format because it's unusable. For example: `(1.2345).toString(16) == "1.3c083126e978d"`. It's not hexadecimal float points, it's something very legacy which we try to avoid

**Comment by letmaik** [comment]
I see, I guess this is the correct approach:
```ts
function hex<T>(n: T): string {
  return '0x' + n.toString(16)
}
```

This compiles and works fine, although I get a typescript error in the editor: "Property 'toString' does not exist on type 'T'."

**Comment by MaxGraey** [comment]
```ts
function hex<T extends number>(n: T): string {
  return '0x' + n.toString(16);
}
```
