### ISSUE TITLE
WASI: Handling things like ioctl and termio to get Terminal size

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#587]
Hello,

Been working on a fun little CLI project, to do [matrix rain effect](https://github.com/torch2424/wasm-matrix) using the wasi bindings, and using [wasa](https://github.com/jedisct1/wasa).

I'm using [Wapm / Wasmer](https://wapm.io/help/guide) to run my Wasm module.

I opened this issue on my project: https://github.com/torch2424/wasm-matrix/issues/1 . Which Essentially comes down to, I can't figure out how to get the terminal size using the current available wasi bindinds.

Let me know if this is an Assemblyscript issue, or something I should open on the actual spec repo: https://github.com/WebAssembly/WASI

Thanks! :smile:

**Comment by dcodeIO** [comment]
As far as I can tell our WASI bindings should be relatively complete (that is: at the time of creating them). Maybe there's another intended way of achieving the same, but I unfortunately lack the experience of actually using the interface / the underlying C APIs. Someone else maybe? :)

**Comment by torch2424** [comment]
Closing in favor of: https://github.com/WebAssembly/WASI/issues/42
