### ISSUE TITLE
TypedArray toString

### ISSUE THREAD

**Issue by bowenwang1996** [AssemblyScript/assemblyscript#590]
Is there a reason why `TypedArray` does not have a `toString` method?

**Comment by dcodeIO** [comment]
I don't think so. Looks like it hasn't been implemented yet.

**Comment by bowenwang1996** [comment]
It seems that now `ArrayBuffer` has a `toString` method but returns `"[object ArrayBuffer]"`. Is it the intended behavior for typed arrays?

**Comment by MaxGraey** [comment]
For `ArrayBuffer` yes. This according spec

**Comment by MaxGraey** [comment]
Need `TypedArray#join` before implementing `TypedArray#toString`

**Comment by bowenwang1996** [comment]
I see. I'll give it a try when I have time.
