### ISSUE TITLE
make String toUTF8 and fromUTF8 more ergonomic

### ISSUE THREAD

**Issue by bowenwang1996** [AssemblyScript/assemblyscript#591]
Right now `toUTF8` returns a pointer and `fromUTF8` takes a pointer and length of the underlying array. It seems more ergonomic to have `toUTF8` return something of an array type, such as `Uint8Array`, and have `fromUTF8` take an array as argument.

**Comment by MaxGraey** [comment]
See reworked api proposal: #564

**Comment by MaxGraey** [comment]
Was improve in [this PR](https://github.com/AssemblyScript/assemblyscript/pull/679)
