### ISSUE TITLE
String fromUTF8 bug

### ISSUE THREAD

**Issue by bowenwang1996** [AssemblyScript/assemblyscript#593]
This code
```typescript
function test(): string {
  let byteArray = new Uint8Array(4);
  byteArray[0] = 131;
  byteArray[1] = 100;
  byteArray[2] = 111;
  byteArray[3] = 103;
  let bytes = byteArray.subarray(1);
  return String.fromUTF8(bytes.buffer.data, bytes.byteLength);
}
```
does not work properly. When run, it says `RuntimeError: unreachable` whereas it is expected to return `'dog'`. Here is the [fiddle](https://webassembly.studio/?f=mibswaqpu3j) for this example.

**Comment by MaxGraey** [comment]
1) `buffer` hasn't `data` field
2) You should expose `allocator` (arena or tlsf)
3) `test` function return pointer and you should decode this pointer to string on host side. See [this](https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/index.js#L7)

Fixed version: https://webassembly.studio/?f=t7v3z7pn0gg

**Comment by bowenwang1996** [comment]
Thanks. I think I am using an older version of assemblyscript.

**Comment by MaxGraey** [comment]
Sorry, actually `ArrayBuffer` has `data` filed)

**Comment by MaxGraey** [comment]
Fully workable version: https://webassembly.studio/?f=8hu0aecaa7l

**Comment by bowenwang1996** [comment]
Why is the length 4 instead 3?

**Comment by MaxGraey** [comment]
I should be 3. Just replace `4` to `byteArray.byteLength` as was before

**Comment by bowenwang1996** [comment]
I see. Thanks a lot!
