### ISSUE TITLE
Field pointers

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#595]
As I work more with Wasi, I find that I need to access the address of fields within classes as they are passed frequently in syscalls.

I tried to make my life easier by writing the following function:

```ts
@inline
function ptr<T>(t: T, field: string): usize {
    return changetype<usize>(t) + offsetof<T>(field);
}
```
However, I got the following compiler error:
```
ERROR TS1141: String literal expected.

     return changetype<usize>(t) + offsetof<T>(field);
                                               ~~~~~
 in packages/assemblyscript/assembly/wasa/fs/fs.ts(287,46)
```

The caller does use a string literal and I thought that by inlinning it it would just have the effect of field becoming a literal.  

I assume that this check happens before the inlinning takes place.  Is there a builtin that already does this?

**Comment by dcodeIO** [comment]
> I assume that this check happens before the inlinning takes place

That's correct, yeah. The `offsetof` builtin is intended to be used as a constant offset argument to load/store. which is an immediate operand, plus there's actually no information about field names in the final binary anymore once compiled. The only alternative to this I see is to use the offset directly instead of the string name.

**Comment by MaxGraey** [comment]
Other possible solution use preprocessing via `--transform` and custom transform and decorator like:
```ts
@inline
function ptr<T>(t: T, @const field: string): usize {
    return changetype<usize>(t) + offsetof<T>(field);
}

ptr(obj, "field")
```
which transform it to:
```ts
ptr(obj, offsetof<Obj>("field"))
```
