### ISSUE TITLE
strings

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#596]
Hello, the [Types](https://github.com/AssemblyScript/assemblyscript/wiki/Types) page in the Wiki doesn't mention `string`. Is that something that should be added there?

I haven't tried AS yet, but I really want to, and I was curious if strings were supported. I noticed some examples of `string` usage in some discussions, but hadn't seen it documented. The only thing I see in the Wiki is the `isString` helper, which means there must be a string type.

Would be happy to help expand the docs when I get some time to try AS out.

**Comment by trusktr** [comment]
I found this [neat article](https://dev.to/neutrino2211/the-js-developers-view-of-wasm-in-2019-36og), showing `wasmModule.getString()` to get them out of the AS module.

Curious if you know, how does the performance of repeated calls to things like `wasmModule.getString()` impact performance?

**Comment by MaxGraey** [comment]
Did you see current status for Strings?
https://github.com/AssemblyScript/assemblyscript/wiki/Status-and-Roadmap#string

**Comment by trusktr** [comment]
Mmmm, cool!

**Comment by trusktr** [comment]
I see `Symbol.hasInstance` is checked off. Does this mean we can implement custom `instanceof` checks even in AS?

**Comment by dcodeIO** [comment]
The performance impact there is that each time you `getString`, the memory region representing the string in WASM memory (a sequence of `u16` character codes) is sliced and assembled to a JS string by means of `Stirng.fromCharCode.apply`. So there is some overhead to that when doing it thousands of times a second, but it's also not super slow.

**Comment by dcodeIO** [comment]
> Off topic: I see Symbol.hasInstance is checked off. Does this mean we can implement custom instanceof checks even in AS?

While that symbol is technically there, it does nothing yet. In fact, there's no semantics to any symbol yet.
