### ISSUE TITLE
TSX

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#597]
Are there any plans for JSX in AS, or any existing TSX projects? A google search didn't turn up much. Basically something similar to `asm-dom` for C or `yew` for Rust?

**Comment by dcodeIO** [comment]
While there are no immediate plans, mostly because it seems too early to think about it, it's of course possible that it will be considered in the future.

**Comment by MaxGraey** [comment]
Fist of all we need DSL parser for this with customization ability like `jsxFactory` in TS. But without `anyref` wasm proposal this not makes sense currently. `asm-dom` and `yew` using are pretty slow compare to js frameworks because have huge overhead during js <-> wasm interop especially for objects

**Comment by trusktr** [comment]
Interesting. Just curious, why not use a tsc transform plugin to compile TS to wasm? Or is that too complicated compared to making a new compiler?

Also, regarding `jsxFactory`, I wouldn't be able to use that even in regular TS, because I'm not planning to generate JSX-spec output (which is inefficient). I'm was thinking about doing something more like

```ts
const input = <input type="text"/>;
```

which could compile to something like

```ts
const input = (() => {
    var __ = document.createElement("input");
    __.type = "text";
    return __;
})();
```

or

```ts
const counter = ReactiveVar(0)
const div = <div>value: {counter()}</div>

// update counter every second
setInterval(() => counter(counter() + 1), 1000)
```

which could compile to something like

```ts
const className = ReactiveVar("foo")
const div = (() => {
    var __ = document.createElement("div");
    var __1 = __.childNodes[1]
    S(() => {
        __1.replaceData(counter()) // re-runs if counter() changes
    });
    return __;
})();

// update counter every second
setInterval(() => counter(counter() + 1), 1000)
```

where `ReactiveVar` is from a dependency-tracking reactive value implementation. There would be no diffing algorithm comparing any trees. The updates would just pass directly to the objects that need updates.

So with that in mind, I think maybe something like `jsxFactory` would not be a good fit due to how it outputs nested function calls.

**Comment by MaxGraey** [comment]
> Interesting. Just curious, why not use a tsc transform plugin to compile TS to wasm?

tsc generally focused on JS output, allow some types and semantics which bad align for AOT compilations. Also it not pretty good solution if you need deep customizations and put some new types inside core. Usually this require forking and hardcoding some stuffs manually. Btw first prototype of AS was based on tsc. @dcodeIO tell you about this unsuccessful experience much more

**Comment by dcodeIO** [comment]
Wouldn't say the prototype was unsuccessful. It's proven an idea. Technically, the only thing relevant to us is TS syntax, though, with nearly every other aspect requiring completely different approaches, so we are much better off with our own compiler. Plus, we may be able to compile the compiler itself to WASM eventually :)

**Comment by MaxGraey** [comment]
Hmm, I thought you struggled more with fork of tsc architecture:) As I remember that was pretty challenging and also needed constant support own fork.

**Comment by dcodeIO** [comment]
Would have been near impossible to continue on that road of course. Maybe I'm just feeling differently about the prototype today, in that it was still valuable experience in a way :)

**Comment by trusktr** [comment]
Thanks for the insight!

> wasm's proposal anyref

I gather that's [this proposal](https://github.com/WebAssembly/reference-types). Is that the proposal that will allows us to work with DOM references in wasm?

**Comment by MulverineX** [comment]
I'm curious what the resolution of this was? @trusktr

**Comment by hariria** [comment]
Yes any updates on this?

**Comment by MulverineX** [comment]
@trusktr regardless of direct DOM references within WASM, is it possible to setup JSX code transform in assemblyscript? There should also be a way to define your own equivalent to `React.createElement` somewhere
