### ISSUE TITLE
inline

### ISSUE THREAD

**Issue by blooddy** [AssemblyScript/assemblyscript#6]
Is it possible to add support for inline functions and constants?

An example of code 
```
const pos:i32 = 10;
store<i32>( pos + 10, 10 );
```
That should be optimized to
```
store<i32>( 20, 10 );
```

**Comment by dcodeIO** [comment]
Inlining like in your example should be fully supported already. Constants are precomputed at compile time and replaced with their constant value where used. When optimizing the module, Binaryen takes care of all the rest, like precomputing expressions comprised of constants and inlining small functions.
