### ISSUE TITLE
Issue with node_modules

### ISSUE THREAD

**Issue by GregTheGreek** [AssemblyScript/assemblyscript#600]
FYI: I couldn't find any relevant information on this topic.

cc: @tueric

I'm trying to do an example by running `js-sha256` but it seems to be erroring out from my `node_modules`. Does AssemblyScript require that the node_modules are also written in AssemblyScript?

```
import { sha256 } from '../node_modules/js-sha256/index.d';

export function hsh(): String{
  return sha256("asf")
}
```

and my errors:
```
> ass-scr@1.0.0 asbuild /playground/assemblyscript
> npm run asbuild:untouched && npm run asbuild:optimized


> ass-scr@1.0.0 asbuild:untouched 
/playground/assemblyscript
> asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug

ERROR TS1005: 'null' expected.

 type Message = string | number[] | ArrayBuffer | Uint8Array;
                        ^
 in node_modules/js-sha256/index.d.ts(1,23)

ERROR TS1109: Expression expected.

 type Message = string | number[] | ArrayBuffer | Uint8Array;
                                ~
 in node_modules/js-sha256/index.d.ts(1,31)

ERROR TS1003: Identifier expected.

 interface Hmac {
                ~
 in node_modules/js-sha256/index.d.ts(37,15)

ERROR TS1003: Identifier expected.

 interface Hash {
                ~
 in node_modules/js-sha256/index.d.ts(94,15)

ERROR: Parse error
```

**Comment by MaxGraey** [comment]
You try to import definition typescript file of library which written on JavaScript. This not work in AssemblyScript.

AssemblyScript is subset of typescript and not support full set of features yet. Some of one just not yet implemented, some of one will never support. I recommend read [this limitations](https://github.com/AssemblyScript/assemblyscript/wiki/Limitations) and [current runtime status](https://github.com/AssemblyScript/assemblyscript/wiki/Status-and-Roadmap).

Complex union types like `string | number[] | ArrayBuffer` not support yet. But nullable types like `string | null` are supported. However only for reference types currently.

**Comment by GregTheGreek** [comment]
@MaxGraey Ok, so then I should assume that some npm packages will not be supported?

**Comment by GregTheGreek** [comment]
Actually let me re-word that question. If I have a package with a declaration file, how would I use it?

**Comment by MaxGraey** [comment]
You can't do this. If you need sha256 for AssemblyScript better write this from scratch. See [wasm-crypto](https://github.com/jedisct1/wasm-crypto) for example. AS required very strict types. Again I recommend discover [wiki](https://github.com/AssemblyScript/assemblyscript/wiki)

**Comment by GregTheGreek** [comment]
ok thank you!
