### ISSUE TITLE
Sharing whole objects between threads instead of buffers

### ISSUE THREAD

**Issue by kazhoyan** [AssemblyScript/assemblyscript#606]
Do you have plans to allow for sharing of objects between threads?

E.g. sharing of references / addresses, or having global / static variables automatically shared - depending on Wasm module's memory configuration.

Treating shared memory as "AssemblyScript objects" instead of a large "linear buffer" will make general programming much more comfortable.

**Comment by kazhoyan** [comment]
Tried sending an object reference as `usize` through API with JS / `ImportsObject.env`.
But even though Wasm modules import the same `WebAssembly.Memory`, their address spaces appear to be different (same addresses contains different data).

**Comment by dcodeIO** [comment]
What you are looking for is shared memory, which will do what you want. I don't think that just using the same memory without enabling it will work. AssemblyScript doesn't do any locking, though, keep that in mind.

**Comment by kazhoyan** [comment]
I enable shared memory: `--enable=threads --importMemory --sharedMemory=... --memoryBase=...`, pass corresponding `WebAssembly.Memory` object when creating Wasm module instance, and run NodeJs with necessary flags.

And it actually works.
But only if I use special builtins that treat it as linear memory, e.g. `atomic.store / load`.
If I pass an AssemblyScript object reference (converted to `usize`) to a worker thread (configured and importing the same `WebAssembly.Memory`), it sees completely different values at that address.

So my question was: does AssemblyScript support different threads referencing the same object?
As opposed to "referencing" the same cell in shared memory buffer.

And if yes, how do you pass that reference between threads? Maybe I'm doing it wrong.

**Comment by dcodeIO** [comment]
Internally, a reference to an object is a typed pointer, an `usize` with a type. So if you have a `var a: string` for example, that is a pointer to the first byte of the string that the compiler simply knows the type of. Now, if memory in two threads uses the *exact same* memory (modifying one modifies both), such a pointer references (points at) the same data if you share it between threads. Hence, this should "just work". One thing to note, though, is that stdlib components aren't yet taking shared memory into account, so allocators for example can have different state (that lives in globals), leading to something as simple as a string concatenation to overwrite memory already allocated for something else by another thread. And similar things.

**Comment by MaxGraey** [comment]
@kazupon you also could use [mutable global with export](https://github.com/WebAssembly/mutable-global/blob/master/proposals/mutable-global/Overview.md#proposed-solution-import-and-export-mutable-globals). But this require also enable `--enable=mutable-global`

**Comment by trusktr** [comment]
Got a simple example of that?

**Comment by bobbinth** [comment]
@dcodeIO - if I instantiate two different WASM modules and pass the same memory object to them, would they still potentially "step on each other's toes" as you mentioned in your last comment in this thread?

**Comment by dcodeIO** [comment]
Unless the modules have been specifically crafted to deal with this situation (no runtime, no static data, doing stuff manually where necessary), most likely. For instance, if there are memory segments declared in one module, these will be inserted into memory upon instantiation which might conflict with the other module's segments. Similarly, both modules will have conflicting dynamic memory managers.

**Comment by bobbinth** [comment]
Got it - thanks! In my use case, I have 2 different WebAssembly modules which need to work with the same data. I was trying to have them share the same memory to avoid copying data back and forth between the modules. But I guess there is no easy way to accomplish this - right?

Is ability to share memory objects between different modules (so that both static and dynamic memory managers are aware of the context) on the short/medium-term roadmap? Or is it something for further down the road?
