### ISSUE TITLE
export * from '...'

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#609]
I have some AS code, which works:

```ts
// index.ts
import {mul} from './mul'
export {mul}
```

and in JS, I can use the exported `mul` function:

```js
const {mul} = (await WebAssembly.instantiateStreaming(response, imports)).instance.exports
mul(2,2)
```

But when I change the export to

```ts
export * from './mul'
```

it compiles just fine, but the object returned from `(await WebAssembly.instantiateStreaming(response, imports)).instance.exports
mul(2,2)` contains no `mul`.

The object only contains `memory` and `table` props.

Is the re-export syntax just not supported yet?

**Comment by dcodeIO** [comment]
Iirc `export *` isn't supported in master, but has been added to dev meanwhile.

**Comment by dcodeIO** [comment]
Recent commits to master should introduce support for this. Feel free to reopen if there are still issues.
