### ISSUE TITLE
cannot find name 'WebAssembly'

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#610]
I'm trying to also use TS in my index.html, so I'm compiling that with `tsc`, but it can't find `WebAssembly`.

Do you know where those types are? I looked at https://www.npmjs.com/package/@types/webassembly-js-api, but that appears to be deprecated, and it mentions that TypeScript already has types... but that doesn't seem to be true.

EDIT: for now I put the following in my TS file:

```ts
// TODO get type defs for WebAssembly
declare const WebAssembly: any
```

**Comment by MaxGraey** [comment]
I also confused why author marked this as deprecated. But you always can rollback to previous npm version

**Comment by trusktr** [comment]
Easy enough to copy the source too.
