### ISSUE TITLE
Source for the loader?

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#616]
I see the loader repo is archived, and in this repo the code is a `.js` with a `.d.ts`. Is there original source or it? Or is that what the archived loader currently is and source not ported over yet?

**Comment by MaxGraey** [comment]
loader not include in sources. Just use `require('assemblyscript/lib/loader')`

**Comment by trusktr** [comment]
I meant, it looks like those "sources" are transpiled `.js` files with accompanying `.d.ts` files, not original `.ts` files.
