### ISSUE TITLE
Converting a number to a string

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#618]
I read https://github.com/AssemblyScript/assemblyscript/issues/369, but I'm not sure how to do it.

I have

```ts
	assert(s.width === 60, 's.width is not 60, got' + s.width)
```

and the compiler says

```
ERROR AS200: Conversion from type 'f64' to '~lib/string/String' requires an explicit cast.

        assert(s.width === 60, 's.width is not 60, got' + s.width)
```

Is it possible?

**Comment by trusktr** [comment]
Alright, tried it with an updated dist, but no luck.

**Comment by trusktr** [comment]
Ok, found a workaround:

```ts
	const a = new Array<f64>(1)
	a.push(s.width)
	assert(s.width === 60, 's.width is not 60, got' + a.toString())
```

**Comment by MaxGraey** [comment]
Currently you should explicitly call `toString()` method

**Comment by trusktr** [comment]
@MaxGraey Ah, that indeed works, but I got confused by my editor showing an error:

<img width="832" alt="Screen Shot 2019-05-29 at 8 18 44 AM" src="https://user-images.githubusercontent.com/297678/58569203-82e6b980-81ea-11e9-922f-a178a09dd087.png">

**Comment by trusktr** [comment]
So I also was trying `new Number(s.width)`, but that constructor doesn't take an argument. Is there some other way to do it without TS having an error?

**Comment by MaxGraey** [comment]
You could fixed this by adding this to your file:
```ts
declare global {
  interface Number {
    toString(): string;
  }
}
```
@dcodeIO It seems we need wrap our definitions to `global` namespace

**Comment by trusktr** [comment]
I tried to put in my code, and got:

```
ERROR TS1109: Expression expected.

        interface Number {
  ~~~~~~~~~
 in src/as/glas/index.ts(8,1)
```

**Comment by trusktr** [comment]
As a workaround, what worked was placing

```ts
interface Number {
	toString(): string
}
```

in a sibling `.d.ts` file.

**Comment by MaxGraey** [comment]
Yes,it better place in separate `d.ts` file

**Comment by trusktr** [comment]
I'm guessing `declare` in a `.ts` file isn't supported yet by the compiler?

**Comment by trusktr** [comment]
@MaxGraey Hello! Should the `toString` be added to the standard library types for numbers so users don't have to do it?

**Comment by MaxGraey** [comment]
I haven't see any problem with master: https://webassembly.studio/?f=7eteo29co4o
