### ISSUE TITLE
ERROR TS2469: The '^' operator cannot be applied to type 'f64'.

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#619]
I've got some code like

```ts
		let hash = this.width || 0
		hash = (hash * 397) ^ (this.height || 0)
		return hash
```

where `this.width` and `this.height` are f64s, and I get the error

```
ERROR TS2469: The '^' operator cannot be applied to type 'f64'.

                hash = (hash * 397) ^ (this.height || 0)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm not expert on bitwise operations. Is this correct? Or is it a TODO feature for AS?

**Comment by dcodeIO** [comment]
Bitwise operations are performed on integers. Here, JavaScript would implicitly convert the floats (numbers) to integers, then do a bitwise XOR, but AssemblyScript doesn't do that because it has WASM's more precise integer types. So, if `this.width` etc. are never used as a floating point value, make them `i32` instead of `number`, or if these are in fact used as a float somewhere else, explicitly convert through `<i32>this.width` before doing bitwise math.

**Comment by MaxGraey** [comment]
or for hashing float numbers better use its integer representation:
```ts
  let hash = reinterpret<u64>(this.width)
  hash = (hash * 397) ^ reinterpret<u64>(this.height)
  return hash as i32
```

**Comment by trusktr** [comment]
Ah, thanks!

I found this piece of code in Babylon.js [here](https://github.com/BabylonJS/Babylon.js/blob/master/src/Maths/math.ts#L3616-L3620), and `this.width` and `this.height` are described to be floats just above that. Seems like that hash function is not good then, as I tried modifying numbers in the decimal places and was getting the same value in the JS console.

**Comment by trusktr** [comment]
Does this work, or does the `f64` cast mess it up?

```ts
	getHashCode(): f64 {
		let hash = reinterpret<u64>(this.width) || 0
		hash = (hash * 397) ^ (reinterpret<u64>(this.height) || 0)
		return f64(hash)
	}
```

**Comment by MaxGraey** [comment]
No, you shouldn't cast this to `f64`. AS allow `u64/i64` as all great and mature system languages, TS/JS doen't allow this and should workarounds for this case. So just extend your mindset and start using full capabilities and new types of this language=)

**Comment by MaxGraey** [comment]
Also `|| 0` is unnecessary

**Comment by trusktr** [comment]
Yeah, seems like `|| 0` in unnecessary even in the JS version. 🤔

Thanks for the input!
