### ISSUE TITLE
Slack invites

### ISSUE THREAD

**Issue by idibidiart** [AssemblyScript/assemblyscript#62]
Hi,

This is in the sidebar:

"Slack (invites on request)"

But there is only the option to sign in when clicking on that link. It says to contact the workspace admin but there is no link to that. How does one request an invite?

**Comment by dcodeIO** [comment]
Currently I use to send out invites whenever an issue or PR is created. Can't find your email address, unfortunately, so maybe just drop me a note via email and I'll make sure you'll get your invite :)

**Comment by idibidiart** [comment]
Thanks. Sent!
