### ISSUE TITLE
How to import std libs?

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#620]
I was able to resolve std modules with a relative path, like

```ts
import {dtoa} from '../../../node_modules/assemblyscript/std/assembly/util/number'

dtoa(123.4)
```

but when I compile this I get errors like

<details>
<summary>errors:</summary>

```
ERROR AS212: Decorator '@builtin' is not valid here.

 @builtin @inline
 ~~~~~~~~
 in node_modules/assemblyscript/std/assembly/builtins.ts(2,0)

ERROR AS212: Decorator '@builtin' is not valid here.

 @builtin @inline
 ~~~~~~~~

 in node_modules/assemblyscript/std/assembly/builtins.ts(6,0)

ERROR TS2304: Cannot find name 'f64'.

 export const NaN: f64 = 0 / 0;
                   ~~~
 in node_modules/assemblyscript/std/assembly/builtins.ts(3,18)

ERROR TS2304: Cannot find name 'f64'.

 export const Infinity: f64 = 1 / 0;
                        ~~~
 in node_modules/assemblyscript/std/assembly/builtins.ts(7,23)

ERROR TS2304: Cannot find name 'node_modules/assemblyscript/std/assembly/builtins/idof'.

   var buffer = __alloc(MAX_DOUBLE_LENGTH << 1, idof<String>());
                                                ~~~~
 in node_modules/assemblyscript/std/assembly/util/number.ts(611,47)
```

</details>

How can I import dtoa, for example?

**Comment by dcodeIO** [comment]
`import { dtoa } from "util/number";`

**Comment by MaxGraey** [comment]
Or just use builtin `parseFloat`/`parseInt`. `dtoa` is internal function

**Comment by trusktr** [comment]
I'm still curious about it anyways.

What's the rule of thumb? How do I know I should start the import with `util/`? Just anything that is in `std/assembly/` is the root of an import specifier?

The module also isn't defined:

<img width="571" alt="Screen Shot 2019-05-29 at 10 11 28 AM" src="https://user-images.githubusercontent.com/297678/58576941-44f19180-81fa-11e9-89ba-b20c879a048e.png">


Am I missing something?
