### ISSUE TITLE
Incompatible const semantics with TypeScript

### ISSUE THREAD

**Issue by gfx** [AssemblyScript/assemblyscript#622]
I have written some AssemblyScript code in https://github.com/msgpack/msgpack-javascript/tree/master/assembly and am confused by the incompatibility of const semantics with TypeScript.

I'd like to use `const` for local, read-only variables just like as I do so in TypeScript. And because its different semantics, I can't enable [prefer-const](https://eslint.org/docs/rules/prefer-const) rule for eslint.

Is this possible to make const semantics to be compatible with TypeScript?

**Comment by dcodeIO** [comment]
This has been implemented in the dev branch recently. Expectation is that it will land in the next week or so.

**Comment by gfx** [comment]
:cool:

Thanks!
