### ISSUE TITLE
Why not u32 or u64 for array index access?

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#626]
I tried accessing an array index with with a `u64`

```ts
const array = [1,2,3,4]
const index: u64 = 2

array[index]
```

```
ERROR AS200: Conversion from type 'u64' to 'i32' requires an explicit cast.
```

So this made me wonder, out of curiousity (and pardon my lack of knowledge):

Why not use u32 (which has twice as many indexes as i32 right?), or even u64, in case computers 20-50 years from now need lots of memory for photo-realistic high-def realtime AR/VR experiences?

**Comment by jtenner** [comment]
Pointers are usize. When the indexes are calculated they need to use `i32` values because that's the native number type.

**Comment by trusktr** [comment]
Interesting. I see it says [here](https://github.com/WebAssembly/design/blob/master/Semantics.md#types) that

> the value types i32 and i64 are not inherently signed or unsigned

How can we treat the i32 as not signed? Is that what u32 does? Because if it is signed, then we have half as many indexes right?

**Comment by dcodeIO** [comment]
Yes, `i32` is signed and `u32` is its unsigned variant. An `i32` can index `2147483647` elements, that's 2GB (current limit of total WASM memory size in most browsers iirc) - 1B  if the element is ´i8/u8`, which is still double of what our memory allocator can allocate as a single chunk in the best case.

**Comment by trusktr** [comment]
Ah thanks. So due to the limit it wouldn't be possible to even support more. Will this limit ever be uplifted?

**Comment by jtenner** [comment]
Eventually, 64-bit wasm will be supported. Yes.

**Comment by trusktr** [comment]
Is the 2gb mem limit related to 32bit vs 64bit?

**Comment by dcodeIO** [comment]
WASM32 memory is limited to a maximum of 4GB (unsigned 32-bit), but reality in browsers is 2GB afaik. I suggest not worrying too much about this yet.
