### ISSUE TITLE
toString doesn't work on getter

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#628]
I have:

```ts
class Vector2 {
	public constructor(
		public x: f64 = 0,
		public y: f64 = 0
	) {}

	get X(): f64 {
		return this.x
	}
	set X(val: f64) {
		this.x = val
	}
}

const v = new Vector2(1, 2)
const x: string = v.x.toString() // works fine
const X: string = v.X.toString() // ERROR TS2339: Property 'toString' does not exist on type 'f64'.
```

The use of `toString` doesn't work on the result of the getter.

**Comment by trusktr** [comment]
As a workaround, I can first save the result in a new var:

```ts
const _X = v.X
const X = _X.toString() // it works
```

**Comment by willemneal** [comment]
This is a bigger issue than just `toString`  and something that I have been meaning to make an issue about.  The problem is the resolution of the property in the expression.  Which is why your fix to separate the resolution into two steps fixed the issue.

**Comment by dcodeIO** [comment]
Related: https://github.com/AssemblyScript/assemblyscript/issues/473

**Comment by trusktr** [comment]
closing as duplicate
