### ISSUE TITLE
Calling 'memory.allocate' requires a memory manager to be present

### ISSUE THREAD

**Issue by ranbuch** [AssemblyScript/assemblyscript#629]
I'm trying to create a function that gets a `pixelData: Array<i8>` and returns `Array<i8>`;

The code looks something like that:
```javascropt
export function getPixelsData(pixelData: Array<i8>): Array<i8> {
  let red = 0 as i8, green = 0 as i8, blue = 0 as i8;
  for (let i = 0; i < pixelData.length; i += 4) {
    red += pixelData[i];
    green += pixelData[i + 1];
    blue += pixelData[i + 2];
  }
  return [red, green, blue];
}
```

But running `npm run asbuild` is printing this warning:
`WARNING("Calling 'memory.allocate' requires a memory manager to be present.");`

Should I ignore this warning?
How can I solve it?

**Comment by MaxGraey** [comment]
You should explicitly import some memory manager like:
```ts
import "allocator/arena"
```
or
```ts
import "allocator/tlsf"
```
