### ISSUE TITLE
wasm-validator error

### ISSUE THREAD

**Issue by jedisct1** [AssemblyScript/assemblyscript#632]
Hi,

I'm trying to port WASA to refcounted assemblyscript.

Unfortunately, `asc` doesn't seem to produce a valid module:

```text
[wasm-validator error in function $assembly/wasa/IO.readString] unexpected false: local.set index must be small enough, on
[i32] (local.tee $13
 [i32] (call $~lib/rt/pure/__retain
  [i32] (call $~lib/rt/__allocArray
   [i32] (i32.const 0)
   [i32] (i32.const 0)
   [i32] (i32.const 4)
   [i32] (i32.const 424)
  )
 )
)
[wasm-validator error in function $assembly/wasa/IO.readString] 1080060731 != 1: local.set type must match function, on
[i32] (local.tee $13
 [i32] (call $~lib/rt/pure/__retain
  [i32] (call $~lib/rt/__allocArray
   [i32] (i32.const 0)
   [i32] (i32.const 0)
   [i32] (i32.const 4)
   [i32] (i32.const 424)
  )
 )
)
```

The code is in the [`dev`](https://github.com/jedisct1/wasa/tree/dev) branch of WASA.

There is something in `IO.readString()` that it doesn't like, but I couldn't figure out what.

**Comment by dcodeIO** [comment]
Thanks, fix in the commit linked above :)

**Comment by dcodeIO** [comment]
Btw, when looking at the code in question

```ts
let s_utf8_buf = changetype<usize>(new ArrayBuffer(s_utf8_len));
...
__release(s_utf8_buf);
```

looks like it will result in a double release. Since the result of the constructor isn't immediately assigned, but goes through a changetype first, the compiler will add an autorelease local that releases the instantiation at the end of the function automatically.

**Comment by dcodeIO** [comment]
Added a few additional notes on [managing lifetimes](https://docs.assemblyscript.org/details/runtime#managing-lifetimes) to the new docs. Let me know if that's missing something that should be covered :)

**Comment by dcodeIO** [comment]
Btw, the `@start` decorator has been replaced with an `--explicitStart` compiler option meanwhile. If specified, the WASM start entry point is skipped and a function named `__start` exported instead. Iirc you guys have been interested in this change :)
