### ISSUE TITLE
Object literals

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#633]
Are those (or will those) be supported?

I didn't have any luck trying to make an object literal, so I'm using Map. I didn't see any mention of object literals in the new docs.

**Comment by dcodeIO** [comment]
There is a mention at https://docs.assemblyscript.org/basics#strict-typing

> Objects must be strictly typed as well:
> ```ts

**Comment by trusktr** [comment]
Ah cool. Thanks. I'm trying to use `Map` to convert some JS object-literal code over, and the JS code that does something like

```js
		if (listeners[eventName] === undefined) {
			listeners[eventName] = []
		}
```


So I'm wondering what to do. In the docs:

> a get with a key that does not exist results in an error, because undefined cannot be represented.

So a get will crash the program.

I guess I need to go through the code base, and make a list of all possible string keys, and initialize them all?

**Comment by trusktr** [comment]
Hmmm, maybe I need to use an array of array tuples, and findIndex?

**Comment by trusktr** [comment]
Oh, but I don't think Array can support multiple item types?

**Comment by trusktr** [comment]
Oh, duh, `Map#has`. nvm

**Comment by lastmjs** [comment]
I would love to see object literal support. Is that something that will be possible in the future? If so, can we reopen this?

**Comment by MaxGraey** [comment]
We have some plans. See this for example: #338 and #299. But even now you could do something like this: https://github.com/ycw/Babylon.Font/blob/master/src_wasm/assembly/index.ts#L477
