### ISSUE TITLE
Function overloads

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#638]
Continuing from https://github.com/AssemblyScript/assemblyscript/issues/421

I am converting a function with the TypeScript signature:

```ts
	lookAt(x: Vector3 | f64, y?: f64, z?: f64): void {
		if (x instanceof Vector3) {
			target.copy(x)
		} else {
			target.set(x, y, z)
		}
```

so it can be called in two ways:

```ts
o.lookAt(1, 2, 3)
// or
const v = new Vector3(1,2,3)
o.lookAt(v)
```

Is it possible to do this in AS?

**Comment by MaxGraey** [comment]
currently union types not supported, but you could use generics:
```ts
lookAt<T>(x: T, y?: f64, z?: f64): void {
  if (x instanceof Vector3) {
    target.copy(x)
  } else {
    target.set(x, y, z)
  }
}
```

**Comment by trusktr** [comment]
That's what I was thinking, but wasn't sure. So if using generics like that, then the `y` and `z` args don't need default values?

**Comment by trusktr** [comment]
And in the `else` block,

```ts
  } else {
    target.set(x, y, z)
  }
```

how will it know about the type of target and if it has a `set` method?

**Comment by trusktr** [comment]
Should I stick `isFloat<f64>(x)` there?

**Comment by dcodeIO** [comment]
> then the y and z args don't need default values?

Default values are always required. There is no `(a?: type)` in AS.

> how will it know about the type of target and if it has a set method?

It won't, but just try to compile that. If there is matching .set method, it will work, and if there isn't the compiler will complain.

> EDIT: Oh, it would be isFloat<T>(x) right?

No, it expects either a type or an expression, not both. Just `isFloat<T>()` here.

**Comment by trusktr** [comment]
Alright, how does this one look?

```ts
	lookAt<T>(x: T, y: f64 = 0, z: f64 = 0): void {
		if (x instanceof Vector3) {
			target.copy(x)
		} else if (isFloat<T>()) {
			target.set(x, y, z)
		}
```

I haven't tried it yet, because I'm still porting the whole file.

Regarding portability, shouldn't `isFloat<T>(x)` be supported, so we can also use a runtime implementation in plain JS?

**Comment by MaxGraey** [comment]
> Regarding portability, shouldn't isFloat<T>(x) be supported, so we can also use a runtime implementation in plain JS?

`isFloat` has [portable version](https://github.com/AssemblyScript/assemblyscript/blob/master/std/portable/index.js#L205)

**Comment by trusktr** [comment]
Oh, then I _should_ call it with both type and arg in the portability case, `isFloat<T>(x)`?

**Comment by MaxGraey** [comment]
if you care about portability better use `isFloat(x)`

**Comment by trusktr** [comment]
What would I miss out on if I do it that way? Does AS inline functions? Would this prevent the unused branch from being pruned?
