### ISSUE TITLE
TODO: mention level of abstract class support in the docs

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#641]
Is there any plan to support abstract classes (or any support)?

I didn't see any mention of "abstract" in https://github.com/AssemblyScript/assemblyscript/wiki/Status-and-Roadmap or https://docs.assemblyscript.org/?q=abstract.

I do see a few occurrences of `abstract` in the std source, but I'm not sure if those are special cases for the compiler. And I see the parser can read it.

**Comment by trusktr** [comment]
I made a test, and looks like it works. Is there anything I should keep in mind?

**Comment by trusktr** [comment]
I see, looks like they work, but they aren't type checked by asc? So, if I have editor support, or use tsc for type checking, then I can catch the cases where a method is not implemented.

Maybe I can get in the habit of running tsc for type checking before compiling with asc.

**Comment by trusktr** [comment]
just marked this TODO so someone (including maybe even me!) can get to it.

**Comment by willemneal** [comment]
fixed by #862
