### ISSUE TITLE
f64.EPSILON vs F64.EPSILON?

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#642]
Why two? For backwards compatibility?

**Comment by dcodeIO** [comment]
This is left over from before the runtime branch. Previously it was possible to use the `--noLib` option that excluded the number wrappers, but it was still desirable to provide the range limits. So yeah, one could argue that it's backwards compatible now. Other than that there are some limits on the basic types that JS does not have, and having all of these in one place and aliasing only the relevant ones on the number wrappers seems fine to me.

**Comment by trusktr** [comment]
Thanks. I'll use `F64.*`, to mirror the JS way.

It might be nice to have an option to rid `f64` (and same for the others) of the runtime stuff, so that we can only call `F64()` and not `f64()` and `f64` can only be used as a type (to strictly match the same pattern as JS). I didn't see an option in `asc -h`

**Comment by trusktr** [comment]
Seems there's one inconsistency: like JS, I can use `F64.EPSILON` (like `Number.EPSILON`), but I can't do `F64(value)` (like `Number(value)`), and have to instead use `f64()`.
