### ISSUE TITLE
array tuples.

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#643]
It is possible to have an array of the form `[f64, f64, f64, string]`?

**Comment by jtenner** [comment]
Technically yes.

It won't be treated as a tuple. It will be treated as a heap allocation, and you have to force the string into a pointer, store it as a float.

`f64[]`

This is a bad idea.

However, when multivalue returns are supported by web assembly specification, then returning tuples like this will be a wonderful way to pass back stack based values.

In the meantime, use a strongly typed heap allocation.

**Comment by trusktr** [comment]
Curious: if I did try that, how would I use the pointer from the `f64[]` array to get the last string value?

**Comment by jtenner** [comment]
Using the array becomes 3 heap allocations instead of 2.

You're barking up the wrong tree. 👍

**Comment by trusktr** [comment]
:)

I like the strongly typed stuff better. I decided to port Three to AS, so f.e. I was porting [these methods](https://github.com/mrdoob/three.js/blob/dev/src/math/Euler.js#L298-L323). The 4th items in those arrays are strings (same type as the above OP). My goal is to keep things as close to the original source as possible.

```ts
	fromArray: function ( array ) {

		this._x = array[ 0 ]; // f64
		this._y = array[ 1 ]; // f64
		this._z = array[ 2 ]; // f64
		if ( array[ 3 ] !== undefined ) this._order = array[ 3 ]; // string

		this.onChangeCallback();

		return this;

	},

	toArray: function ( array, offset ) {

		if ( array === undefined ) array = [];
		if ( offset === undefined ) offset = 0;

		array[ offset ] = this._x; // f64
		array[ offset + 1 ] = this._y; // f64
		array[ offset + 2 ] = this._z; // f64
		array[ offset + 3 ] = this._order; // string

		return array;

	},
```
