### ISSUE TITLE
generics as alternative to union function parameters loses type information

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#646]
F.e., it seems that if I have something like

```ts
function foo<T>(arg: T) {
  if (arg instanceof Foo) { ... }
  else if (arg instanceof Bar) { ... }
  else if (arg instanceof Baz) { ... }
}
```

then on the outside I can call it with anything:

```ts
const w = new Whatever
foo(w) // no type error
```

If there's no unions, how can I limit what can be passed in? Will unions be supported later?

**Comment by jtenner** [comment]
You're stuck with runtime errors. Aspect has been struggling with a few of these problems and instanceof is a runtime check for reference types.

**Comment by jtenner** [comment]
You could use `T extends Subclass` but it depends on your use case.

**Comment by MaxGraey** [comment]
```ts
function foo<T>(arg: T) {
  if (arg instanceof Foo) { ... }
  else if (arg instanceof Bar) { ... }
  else if (arg instanceof Baz) { ... }
  assert("unexpected type")
}
```

**Comment by trusktr** [comment]
Are unions for generic params planned, `T extends Foo | f64`?

**Comment by jtenner** [comment]
All you get is `T extends Foo` for now.

Also, with @MaxGraey's example, be careful you don't use properties. Always do *this*

```ts
if (foo instanceof Bar) {
  let mybar: Bar = changetype<Bar>(foo) ;
  // do something with mybar
}
```

If blocks that have runtime checks for reference types tend to result in compile time errors if you only use the generic `T` parameter. Create a new variable and cast it manually to avoid compiler errors.

**Comment by trusktr** [comment]
By branch elimination, do you mean that a function can be inlined in order for the branches to be eliminated for use at the specific location?

Is there another way instead of instanceof to cause branch elimination with classes?

**Comment by trusktr** [comment]
@MaxGraey I'm get an `AssertionError: assertion failed` when trying to make a simple generic method.

I've made a reproduction at https://github.com/AssemblyScript/assemblyscript/issues/645#issuecomment-500710161

Basically the method is

```ts
	test2<T>(t: T): boolean {
		if (isFloat<T>(t)) {
			return true
		} else if (isString<T>(t)) {
			return true
		}

		return false
	}
```

and the callsite is

```ts
	assert(a.test2(2), 'test2 failed')
	assert(!a.test2(null), 'test2 failed')
```

Did I do it wrong?

**Comment by MaxGraey** [comment]
```ts
assert(a.test2(2), 'test2 failed') // should be failure
assert(!a.test2(null), 'test2 failed') // this should ok
```

`test2(2)` will return `false` because `isFloat<i32>(t) == false`. You should use `isFloat<T>(t) || isInteger<T>(t)`
`test2(null)` is actually `test2<usize>(0)` so the same.

**Comment by jtenner** [comment]
By branch elimination, do you mean that a function can be inlined in order for the branches to be eliminated for use at the specific location?

What happens is if a function call can be determined to be true at compile time, like `isFloat<T>()` then the if branch will be Inlined and the function will be short circuited if it has a return in the block.

I had to do this pattern for nearly every single comparison function in `as-pect`

**Comment by dcodeIO** [comment]
Regarding `instanceof`: Some of these are static, like checking `someVar instanceof i32`, `someObj instanceof string` and `someObj instanceof SomeClass` where the relation to `SomeClass` can be determined statically from the LHS type. For example something like `cat instanceof Animal` usually works because `Cat` is always also `Animal`, but `animal instanceof Cat` doesn't because `animal` might not be a `Cat` but a `Dog`, which needs a runtime check.

**Comment by jtenner** [comment]
In regards to type assertion, always put the assertions that will be Inlined *first*. Then, act defensively against compiler errors as needed.
