### ISSUE TITLE
Integrate with wasm-bindgen?

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#65]
You've probably seen this already, but Alex Crichton has created a really useful tool for constructing Rust (WebAssembly) <=> JS bindings:

https://github.com/alexcrichton/wasm-bindgen

The tool is designed to be language independent.

I was wondering if it is with exploring using this tool for AssemblyScript? Or do you currently have a solution for creating a richer WASM <=> JS interface?

**Comment by xtuc** [comment]
It would make a lot of sense to provide TypeScript bindings. You could integrate a webassembly application in your TypeScript application.
