### ISSUE TITLE
Where's that one performance comparison, with the canvas rendering?

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#651]
I stumbled recently on a comparison of various languages compiled to WebAssembly, rendering to DOM, including untouched and optimized AssemblyScript.

I can't find it.

It was a demo with JavaScript, AssemblyScript, AssemblyScript optimized, C/Emscripten (I think), maybe Rust (don't remember which languages).

In the demo I was able to click to see the same demo running with each language, along with the frame rate.

Do you happen to know which demo I'm talking about? I think it'd be nice to add it into the FAQ, regarding performance.

**Comment by MaxGraey** [comment]
It moved to documentation:
https://docs.assemblyscript.org/community/built-with-assemblyscript#benchmarks

I guess you looking for this [demo](https://jtiscione.github.io/webassembly-wave/index.html)

**Comment by trusktr** [comment]
Yeah, that was it. Thanks!

Interesting, the two fastest ones for me, are the JS and unoptimized AS, both around ~170 fps. The optimized AS goes up to ~230.

Any ideas why optimized AS is slower?

**Comment by trusktr** [comment]
Hmmm, if I click the "Noise" button repeatedly, the frame rate drops while I'm doing it, in all cases. Something may be off there.

**Comment by MaxGraey** [comment]
@trusktr 

> optimized AS goes up to ~230.
> JS and unoptimized AS, both around ~170 fps

> Any ideas why optimized AS is slower?

Wait AS has 230 fps which greater than 170 fps. So obvious AS is faster. May be you messd up Frame Per Second (measure in fps) with Frame Time (measure in ms)?

You produce a lot of issues and usually never close it after answering on your questions. Could you do this more carefully? Thanks)

**Comment by trusktr** [comment]
Dooooh! I overlooked it, I was thinking speed. 

> Could you do this more carefully?

Will do

**Comment by trusktr** [comment]
@MaxGraey You link above (https://docs.assemblyscript.org/community/built-with-assemblyscript#benchmarks) doesn't work anymore. Mind updating that?

**Comment by MaxGraey** [comment]
List of bench examples present in Discord channel like:
https://github.com/jtiscione/webassembly-wave
https://github.com/nischayv/as-benchmarks

**Comment by synxroform** [comment]
This is the most beautiful benchmark that i've ever seen.

**Comment by trusktr** [comment]
On the wave demo, the "optimized" AS option seems to be gone. Where did it go?

**Comment by MaxGraey** [comment]
> On the wave demo, the "optimized" AS option seems to be gone. Where did it go?

Author decided remove untouched version. So all modules are optimized include optimized AS
