### ISSUE TITLE
What tsconfig setting recommended for browsers?

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#652]
portable.json has:

https://github.com/AssemblyScript/assemblyscript/blob/420812f5b2b34deb1442852df9ded321ea97a147/std/portable.json#L6

I'm trying to set up a portable example, but there's no types available.

After extending from portable.json, I added 

```
		"noLib": false,
		"lib": ["dom", "es2018"],
```

but when I try to build, I got an error like the following (among others):

```
src/as/glas/core/Layers.ts:38:15 - error TS2558: Expected 0 type arguments, but got 1.

38      if (isFloat<T>(t)) {
                    ~

src/as/glas/core/Layers.ts:40:23 - error TS2558: Expected 0 type arguments, but got 1.

40      } else if (isString<T>(t)) {
                            ~

src/js/as-loader.d.ts:9:33 - error TS2304: Cannot find name 'Record'.

9 interface ImportsObject extends Record<string, any> {
                                  ~~~~~~

src/js/as-loader.d.ts:81:10 - error TS2583: Cannot find name 'Promise'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.

81  result: Promise<Response>,
            ~~~~~~~
```

What's the best example of a portable project?

**Comment by dcodeIO** [comment]
This is not how it works. The portable subset is the least common denominator of AS and TS, only supporting what's available in both or can be polyfilled by the portable library. Hence no "dom", "es2018", Record or Promise.

See: https://docs.assemblyscript.org/details/portability

**Comment by trusktr** [comment]
> This is not how it works.

That's what I'm trying to find out. :) I read the portability page you linked, but it's missing stuff (maybe I can help update it once I figure it out).

Here's the main problem: I have regular TypeScript code, which is using more than the minimum set between AS and TS. This regular TS code uses the DOM, but it also needs to import the "portable" code, therefore the TypeScript configuration needs to cover both the DOM types and the portable types.

The DOM types (etc) are _not for the portable AS code, but for the **regular TS code** in the same project, and that regular TS code is importing and using the portable AS code_.

So when I try to update the tsconfig on the TS side, it has problems, because the portable types seem only to work with code that _strictly_ uses the portable types without interference from other type definitions.

In practice, it is very likely that portable code should be imported into other code which will depend on types that exist in the non-wasm environment.

For example, users are going to import portable AS code into Node.js or browser projects, and those environments need to have a bunch of other types present. So, simply providing the portable types from the `assemblyscript` module is not enough.

> Hence no "dom", "es2018", Record or Promise.

So you see, the portable AS code is not using those, but the regular TS code that imports the portable AS code is.

The regular TS code may in fact need to use a `Promise` after it has imported the portable AS code. Do you see the issue now?

So the problem is that I have regular code that requires regular types in the environment (f.e. dom), and this regular TS code is unable to import the portable AS code because the portable type definitions conflict, and because other stuff is missing (when I follow the instructions in the portability doc).

> isFloat<T> doesn't work in JS because JS can't evaluate T, hence it must be used with an expression in portable scenarios.

Makes sense. Over at https://github.com/AssemblyScript/assemblyscript/issues/638#issuecomment-500012672, you mentioned

> it expects either a type or an expression, not both. Just isFloat<T>() here.

I see what you mean now, based on the portable types, because the portable types don't expect a generic arg.

But, why not? TypeScript can infer the generic type args, and those type args don't have to do anything, so why not just include them in the portable definitions as well. Wouldn't this let the compiler be able to make optimizations as well as provide an identical interface for portable code?

I might know enough about the compiler, if there's some limitation.

**Comment by dcodeIO** [comment]
The way the compiler, which is a portable project btw, attempts to solve this, is by including different [glue code](https://github.com/AssemblyScript/assemblyscript/tree/master/src/glue) depending on the target with all targets having a common external interface. So one would have a function that compiles to something different depending on the target by means of including another additional file in compilation.

The obvious alternative is to `<reference path="path/to/std/portable/index.d.ts" />` instead and somehow include `path/to/std/portable/index.js` in compilation, but that's not how it's (currently) intended. Let me know how that turns out if you decide to go that route. Perhaps, if it works, there could be another base config for this scenario.

> the portable types don't expect a generic arg. But, why is this the case?

In TypeScript (compiled to JavaScript), `T` can only be used for type checking, but cannot result in actual code, like a static `true` or `false`, which would be necessary to have `if (isFloat<T>()) { ... }`. If `T` would be in the typings, someone would use `isFloat<T>()` but would get `isFloat/*<nothing>*/(/*nothing*/)`.

**Comment by trusktr** [comment]
Cool. I'll try that when I circle back around. What I was trying to do was export a class from AS, then use the class type on the other side by importing the type of the class with `type Foo = import()` syntax.

> someone would use `isFloat<T>()` but would get `isFloat/*<nothing>*/(/*nothing*/)`.

True, which is why I'm wondering why not support `isFloat<T>(something)` using the type and the runtime arg?

**Comment by dcodeIO** [comment]
> True, which is why I'm wondering why not support isFloat<T>(something) using the type and the runtime arg?

Because the type is meaningless and all it can evaluate is the expression. The API of `isFloat` is either a type OR an expression, not both.

**Comment by trusktr** [comment]
Right, that may be true, but I don't see why we can't write `isFloat<T>(foo)`, which makes portable types easy. The compiler can still choose what to do with it, for example, it can still treat `isFloat<T>(foo)` as `isFloat<T>()`, and the docs could explain this.
