### ISSUE TITLE
type imports (TODO)

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#656]
I thought I'd use type imports for cases where I only reference the identifier as a type:

```ts
ERROR TS1003: Identifier expected.

 type Euler = import('./Euler').Euler
              ~~~~~~
 in src/as/glas/math/Vector3.ts(4,13)
```

I'm assuming this is not supported in AS yet.

Does AS execute modules when they are `import`ed the runtime way, like with JS? I wanted to avoid executing modules if all I need is the type.

**Comment by dcodeIO** [comment]
Yeah, this syntax is not supported. `import { Euler } from "./Euler";` will probably do what you want, though, because AS doesn't compile anything that's not actually being used.

**Comment by trusktr** [comment]
> top-level statements

many modules do, and are likely to need, because closures don't work yet. So I thought I'd avoid running top-level code if I don't need to. F.e., a method definition might rely on the types from a module that ultimately isn't being used, so those top-level statements don't need to be executed.

**Comment by MaxGraey** [comment]
> Does AS execute modules when they are imported the runtime way, like with JS? I wanted to avoid executing modules if all I need is the type.

AS never include whole module in runtime and even not parse whole module if you need just some part or some type declaration, so you shouldn't  worry about it and just use top level import

**Comment by trusktr** [comment]
@MaxGraey Wait, but regarding portable code, maybe we want to support it, because JS users don't have the benefit of the static compiler. So type imports are the way to do it.

**Comment by trusktr** [comment]
TypeScript has a new `import type {...} from '...'` syntax, and the option to throw an error if something imported only for use as a type was not imported with `import type` syntax.

See the [Type-Only Imports and Export](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) docs.
