### ISSUE TITLE
Empty array literal doesn't work (in general, need better error messages)

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#663]
I know, error messages are still WIP. AS is an awesome project!

I ran into this: https://github.com/jtenner/as-pect/issues/92 (see the reproduction there).

I didn't know if it was an as-pect issue or an assemblyscript issue, because there wasn't a meaningful error message.

It ended up being that on line 18 of `src/as/glas/core/Object3D.spec.ts` (in the reproduction of the linked issue) I needed to change

```ts
const names: string[] = []
```

to

```ts
const names: string[] = new Array()
```

I'm loving AssemblyScript, but my biggest hurdle so far is error messages that aren't telling me much (as an end-user). Because of this I may be posting issues on GitHub that are actually my fault, for example perhaps I'm trying to use an unsupported feature, but I don't know that it isn't supported.

It'll be nice once the error messages are meaningful.

If it weren't for @willemneal in https://github.com/jtenner/as-pect/issues/92#issuecomment-501709576, I may have been a looooong time before I figured it out what was happening (being a TS/JS user coming over with no experience in Wasm).

**Comment by MaxGraey** [comment]
This issue with empty array literal should be already fixed in AS master. I guess as-pect still use old runtime.

cc @jtenner

**Comment by trusktr** [comment]
Ah cool. I left my self a TODO to change my code back and test it later. I'll close this out then.
