### ISSUE TITLE
__release function in loader

### ISSUE THREAD

**Issue by togekk** [AssemblyScript/assemblyscript#664]
Hi,

I found out there's a function called __release in the loader's README. But I looked at the code in index.js and there's no such function in there. Or is there any other way to release memories?

Thanks

**Comment by dcodeIO** [comment]
The functions `__alloc`, `__retain` and `__release` are provided by the WebAssembly module if a [runtime](https://docs.assemblyscript.org/details/runtime) variant is present that exports them (full or stub).

**Comment by togekk** [comment]
It works now. Thank you so much
