### ISSUE TITLE
[bug] asinit from global install makes tsconfig relative to itself

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#665]
`asinit .` currently creates the following `tsconfig.json`:

```json
{
  "extends": "../../../../Research/wasm/assemblyscript/std/assembly.json",
  "include": [
    "./**/*.ts"
  ]
}
```
While this does work for the local package, it should be relative to node_modules.

**Comment by dcodeIO** [comment]
How this currently works is that when `asinit` is run, the relative path from the then source directory to the compiler containing the asinit script that is being run is obtained, and that used in the generated package.json.

So, if one installs AssemblyScript as a dependency, effectively being placed in `./node_modules/assemblyscript`, and initializes a project in `.`, with sources in `./assembly`, the path will be `../node_modules/assemblyscript/std/assembly.json`.

Could you explain how that doesn't work for you? Is it possible that the wrong `asinit` command from another installation of the compiler is used?
