### ISSUE TITLE
 way to emulate TypedArray.set?

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#667]
I noticed `TypedArray.set` is not implemented yet. Is there a way to achieve similar manually?

For example, I have this code, which currently allocates a new array:

```ts
	copyArray(array: Float32Array): this {
		let newArray = new Float32Array(array.length)

		for (let i = 0, l = array.length; i < l; i++) {
			newArray[i] = array[i]
		}

		this.array = newArray

		return this;
    }
```

But I wanted to try to do something like

```ts
	copyArray(array: Float32Array): this {
		this.array.set(newArray)

		return this;
    }
```

Can I do it manually?

EDIT: I see how REDUCE_RIGHT works (GitHub search results don't show all hits). Gonna study those helper functions.

**Comment by MaxGraey** [comment]
you could use `memory.copy`

**Comment by bowenwang1996** [comment]
You probably want to do `memory.copy(newArray.dataStart, array.dataStart, array.length)`

**Comment by trusktr** [comment]
For some reason I thought `.set` was modifying the context array to have a new range, but I was mistaken.

So I suppose I can just make a loop. Is there anything the following doesn't cover that `memory.copy` does?

```js
	copyArray(array: Float32Array): this {
		if (array.length > this.array.length) throw new Error('Source array is too big.')

		for (let i = 0, l = array.length; i < l; i++) {
			this.array[i] = array[i]
		}

		return this;
    }
```

**Comment by MaxGraey** [comment]
yes, you could use loop, but `memory.copy` will be little bit faster

**Comment by bowenwang1996** [comment]
My understanding is that the loop is slower because it does boundary checks while memory.copy is faster but unsafe.

**Comment by trusktr** [comment]
Thanks!

**Comment by trusktr** [comment]
I'm getting `Property 'dataStart' does not exist on type 'Float32Array'.` In `assemblyscript/src/std/assembly/index.d.ts` I see:

```ts
/** Interface for a typed view on an array buffer. */
interface ArrayBufferView<T> {
  [key: number]: T;
  /** The {@link ArrayBuffer} referenced by this view. */
  readonly buffer: ArrayBuffer;
  /** The offset in bytes from the start of the referenced {@link ArrayBuffer}. */
  readonly byteOffset: i32;
  /** The length in bytes from the start of the referenced {@link ArrayBuffer}. */
  readonly byteLength: i32;
}
```

I'm on the `dev` branch.

**Comment by bowenwang1996** [comment]
https://github.com/AssemblyScript/assemblyscript/blob/addb99eff250af2af0241442d45ff3d23434e6f1/std/assembly/arraybuffer.ts#L10

**Comment by MaxGraey** [comment]
it already in master. dev branch is outdated. But you should know `dataStart` is undocumented propertly. If you prefer avoid undoc props you could use `changetype<usize>(arr.buffer) + byteOffset` instead.

**Comment by trusktr** [comment]
Ah, ok, thanks. I'll just stick with the for loop for now because it's easy.
