### ISSUE TITLE
[Bug] Duplicate Allocation Error?

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#672]
It's hard to pinpoint exactly what the problem is, but it looks like RTrace is reporting a duplicate allocation for some reason.

```ts
describe("an error", () => {
  it("should cause a duplicate allocation", () => {
    let result = new Array<string>(0);
    let source = "1234567890";
    let buff = changetype<ArrayBuffer>(source.toUTF8());

    let len = buff.byteLength - 1;
    let ptr = changetype<usize>(buff);

    for (let i = 0; i < len; i++) {
      result.push(String.fromCharCode(<i32>load<u8>(ptr + i)));
    }
  });
});
```

This `as-pect` testing suite reproduces the error (because I needed to bootstrap the RTrace interface to get the error to report).

I can't paste the entire wat file output here, but this is it with `-O3` optimization.

https://gist.github.com/jtenner/645c8edc7f0795d8ca6e225841e8114a

**Comment by dcodeIO** [comment]
Reducing a little more

```ts
{
  let result = new Array<string>(0);
  let source = "1";
  result.push(source.charAt(0));
  result.push(source.charAt(0));
  result.push(source.charAt(0));
  result.push(source.charAt(0));
  result.push(source.charAt(0));
  // result.push(source.charAt(0));
}
```

leaks what appear to be backing buffers, and uncommenting the last line then leads to a "duplicate alloc".

**Comment by dcodeIO** [comment]
Should be fixed by the commit above. Didn't update dist files yet.

**Comment by jtenner** [comment]
Thank you!
