### ISSUE TITLE
Relocatable binaries

### ISSUE THREAD

**Issue by geloizi** [AssemblyScript/assemblyscript#673]
Is it possible to make the binaries produced by assemblyscript "relocatable"? Such binaries can be merged together using `wasm-ld`.

**Comment by dcodeIO** [comment]
As far as I know this will require some support within Binaryen ('s C-API), generating relocation sections etc, which it currently doesn't support (in the C-API). Iirc it has some support for relocation and uses that with Emscripten, but I'm not sure if other generators can reuse the functionality. Or, I might also be completely wrong. @kripken?

What the compiler does currently is basing loads and stores on a `__heap_base` global that can be adjusted if the heap is moved, with everything before that offset being static data. The memory manager we use is able to work with non-adjacent pages by means of `memory.grow/sbrk` as well, so it should, in theory, be able to share the heap with another memory manager. The docs have [some more information](https://docs.assemblyscript.org/details/memory#memory-regions).

**Comment by kripken** [comment]
Binaryen doesn't yet support relocation sections. I don't think anyone is working on that atm, but it would be nice to have.

(In emscripten, what happens is clang emits relocatable object files, then they are linked wasm wasm-ld, and the result is a normal non-relocatable wasm file, which binaryen is then called on.)
