### ISSUE TITLE
Return multidimention array cause to runtime error

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#674]
Minimal example:
```ts
export function createMatrix(rows: i32, cols: i32): f64[][] {
  return new Array<f64[]>(rows);
}
```
Compiled but cause to runtime unreachable execution
fiddle: https://webassembly.studio/?f=glc7b0zligh

**Comment by dcodeIO** [comment]
`Array<f64>` is a non-nullable reference type, so using the array constructor would create a holey array of `rows` x `null`. This should work:

```ts
Array.create<f64[]>(rows);
```

**Comment by MaxGraey** [comment]
yeah. This `Array.create<f64[]>(rows)` works. But this also require casting to `as f64[][]` at the end. Hmm. Could we improve this somehow?

**Comment by dcodeIO** [comment]
> But this also require casting to as f64[][] at the en

Hmm, that'd be a bug. Signature there is `Array.create<T>(...) -> T[]`, so it should also be `Array.create<f64[]>(...) -> f64[][]`.

**Comment by MaxGraey** [comment]
Real code looks like this:
```ts
export function createMatrix(rows: i32, cols: i32): f64[][] {
   const data: f64[][] = new Array<f64[] | null>(rows);
   for (let i = 0; i < rows; i++) {
      data[i] = new Array<f64>(cols);
      for (let j = 0; j < cols; j++) {
        data[i][j] = Math.random() * 2 - 1;
      }
   }     
   return data as f64[][];
}
```

**Comment by dcodeIO** [comment]
Ah, yeah, that's why `Array.create` exists, so one doesn't have to deal with `null`. It's essentially the same as `new Array` but initializes `.length = 0` so its type doesn't become invalid. Pushing to that array, or doing indexed access on it, will not realloc the buffer because the capacity is already `rows`.

**Comment by MaxGraey** [comment]
Yeah. thanks! I guess need print some warning on compile time about this. wdyt?

**Comment by dcodeIO** [comment]
It should result in an abort with `export const E_HOLEYARRAY: string = "Element type must be nullable if array is holey"` as the message.

**Comment by MaxGraey** [comment]
Yes, if you use loader. But in WAS this just "unreachable execution". Also for new user I guess message "Element type must be nullable if array is holey" is not clarify what's wrong and how this fixed)

**Comment by dcodeIO** [comment]
I tried to integrate notes on this [into the array docs](https://docs.assemblyscript.org/standard-library/array), but maybe that's not enough.

**Comment by MaxGraey** [comment]
Is it possible delay this runtime error? I mean what if we don't throw error in constructor for non-nullable references and will hope that the user will initialize the array completely, without holes?

**Comment by dcodeIO** [comment]
The static analysis necessary to know this at compile time isn't there, and any runtime check could potentially miss the first use of a null value.
