### ISSUE TITLE
[bug] Abort option isn't working

### ISSUE THREAD

**Issue by DieMyst** [AssemblyScript/assemblyscript#676]
For example, there https://webassembly.studio/?f=ayvoyj2s81 if we run `build`, this warning will occur:
```WARN: Unknown option '--use abort='''```
and this error on run:
```[error]: LinkError: WebAssembly Instantiation: Import #0 module="env" function="abort" error: function import requires a callable```

**Comment by dcodeIO** [comment]
The correct syntax there is

```ts
  asc.main([
    ...
    "--use", "abort=",
  ], callback);
```

but this will then lead to an assertion error of `ERROR: missing abort` because the compiler expects that at least some abort routine is present that it can use.

Adding a custom abort to `main.ts` and using that instead of the built-in abort should work, though:

```ts
function myAbort(
  message?: string | null,
  fileName?: string | null,
  lineNumber?: u32,
  columnNumber?: u32
): void {}
```

```ts
  asc.main([
    ...
    "--use", "abort=main/myAbort",
  ], callback);
```

In this case, whenever an `abort` happens, the custom function will be called right before a trap occurs.

**Comment by MaxGraey** [comment]
@dcodeIO I tried `"--use", "abort="` but this caused to `WARN: Unknown option '--use abort='` and doesn't have effect.

https://webassembly.studio/?f=u15n0gyad7

**Comment by dcodeIO** [comment]
When I run "Build" there, I get `ERROR: missing abort`.

**Comment by dcodeIO** [comment]
Might well be that this worked differently in earlier versions of the compiler, and allowing the user to disable the abort routine entirely instead of having to provide an alternative seems like something worth to support.

**Comment by MaxGraey** [comment]
It seems this should be:

```ts
for (let [name, alias] of globalAliases) {
```
instead:
https://github.com/AssemblyScript/assemblyscript/blob/f9a77b132fb792db3350677ec9dd146dab03ea32/src/program.ts#L829

**Comment by dcodeIO** [comment]
Consider `--use Math=NativeMath`. There, `Math` is the alias and `NativeMath` the internal name to be aliased. Should be correct this way.

**Comment by MaxGraey** [comment]
Hmm, but here using `globalAliases[name] = alias`:
https://github.com/AssemblyScript/assemblyscript/blob/0484a6b740b996145f10ad227359be614c190208/src/index.ts#L99

**Comment by dcodeIO** [comment]
Yeah, the naming is off there, but the order is not changed. `name` and `alias` should be switched there I think.

**Comment by dcodeIO** [comment]
PR linked above should fix all of this :)

**Comment by MaxGraey** [comment]
Great! Also need mention how use `abort` properly in docs I guess

**Comment by dcodeIO** [comment]
Added here: https://docs.assemblyscript.org/details/debugging#overriding-abort
