### ISSUE TITLE
[Bug?] Types documentation and implementation mismatch for string#charCodeAt()

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#682]
```
ERROR AS200: Conversion from type 'i32' to 'u16' requires an explicit cast.

       let value: u16 = color.charCodeAt(i);
                        ~~~~~~~~~~~~~~~~~~~
 in assembly/__tests__/ColorParseOperation.spec.ts(8,23)
```

In the index.d.ts file, it's marked at `u16` as I think it should be, but the implementation likely has an `i32` output, which is currently unexpected.

```ts
declare class String {
  charCodeAt(index: u32): u16;
}
```

I can't submit a pull request right this second, but if nobody makes it by the end of tonight, I can probably get around to this.

The question is, what needs to be done?

**Comment by MaxGraey** [comment]
Good catch! Should be `i32` everywhere

**Comment by jtenner** [comment]
Okay. Please let me make the pull request later.

**Comment by jtenner** [comment]
Thanks for the fix.
