### ISSUE TITLE
Overload operator new

### ISSUE THREAD

**Issue by geloizi** [AssemblyScript/assemblyscript#687]
Curios whether it's possible to overload operator `new` for a class? That's what I've tried:

```
class Test {
    @operator("new")
    public static opnew(): Test {
        return changetype<TestEvent>(0);
    }
}
```

**Comment by MaxGraey** [comment]
Why you need overloading `new` operator?

**Comment by geloizi** [comment]
I'm trying to make a library where objects are shared between "host" native and "guest" wasm code. So instead of heap allocation I'd like to create the objects in some shared memory.

**Comment by MaxGraey** [comment]
Just return pointer from constructor like:
```ts
class Test {
   constructor() {
      return changetype<TestEvent>(0);
   }
}
```

**Comment by geloizi** [comment]
:+1:

**Comment by MaxGraey** [comment]
btw may be you will be interested in this [pointer helper](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/std/pointer.ts)
