### ISSUE TITLE
Error in String#trim()

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#694]
Hey guys, there's a problem on this line.

```
ERROR TS2304: Cannot find name 'start'.

     if (!start && size == length << 1) return this;
          ~~~~~
 in ~lib/string.ts(226,9)
```

https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/string.ts#L226

**Comment by MaxGraey** [comment]
Fixed in #692

**Comment by MaxGraey** [comment]
@jtenner fixes in master

**Comment by jtenner** [comment]
This is totally fixed. Thanks!
