### ISSUE TITLE
[Documentation] Recommended way to access imported memory

### ISSUE THREAD

**Issue by Keyholder** [AssemblyScript/assemblyscript#700]
Documentation lacks in subject of actually working with memory that was imported into module. I got it, `--importMemory` flag gives me `(import "env" "memory" (memory $0 1))` in generated `.wat`, but what's next - how do I read or write it?

**Comment by dcodeIO** [comment]
An imported memory becomes the normal singleton memory of the module, so accessing it works exactly the same as accessing a non-imported memory. When imported, the module places its static data etc. in it and keeps everything else that has been provided by the host.

**Comment by dcodeIO** [comment]
Also updated the docs with more information about how to deal with imported memory: https://docs.assemblyscript.org/details/memory#importing-memory

**Comment by Keyholder** [comment]
Hm... So, it means, if I want to pass some pre-populated data bank to AS module, its size have to be fixed at compile time? That's unfortunate.

**Comment by dcodeIO** [comment]
The maximum size of the pre-populated data must be known, yeah, but the memory is still able to grow normally if it needs more at runtime.

**Comment by Keyholder** [comment]
OK, thank you for clarification!

**Comment by MichaelJCole** [comment]
@dcodeIO lol, because this is the first memory I'm trying to access, I'm having a challenge.  An example would be super helpful.

> accessing it works exactly the same as accessing a non-imported memory

From this example, 

https://github.com/gonzaloruizdevilla/image-manipulation-assemblyscript/blob/77578d3e97fb9292012c6428c01f6e3b65ca186a/assembly/index.ts

I'm guessing the `load` and `store` functions described here under accessing low-level memory

https://docs.assemblyscript.org/

**Comment by dcodeIO** [comment]
Yeah, the `load` and `store` functions access values in linear memory (no matter if exported, imported, or none of these) on the lowest level, and the typed arrays, strings and other objects are stored in linear memory. The typed arrays for example are implemented using `load` and `store`.
