### ISSUE TITLE
compiler.js getString() return nothing

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#704]
I called `trace` function in test case.

https://github.com/AssemblyScript/assemblyscript/blob/496be276deecb0afda9f0868371afdba09d9993a/tests/compiler.js#L319

![image](https://user-images.githubusercontent.com/4305499/60570859-00cb5100-9da5-11e9-8df9-4fdbd7fff570.png)

Expect to get log info
`trace:  get trace info 0, 0, 0, 0, 0`
In fact got the below 
`trace:  0, 0, 0, 0, 0`

The  result  of getString was null.

Is there a way I get the string log?

**Comment by MaxGraey** [comment]
trace has maximum 5 arguments:
https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/builtins.ts#L1704

**Comment by LiaoPeng** [comment]
![image](https://user-images.githubusercontent.com/4305499/60571989-2d806800-9da7-11e9-9067-3f4ac7ffbd64.png)

Fixed the arguments.  Still missing the string log `get trace info`.

**Comment by MaxGraey** [comment]
I see. Did you try use `5` instead `12`. Because internal tests using `trace` a lot and it works properly
```ts
  trace: zero_implicit
  trace: zero_explicit
  trace: one_int 1
  trace: two_int 1, 2
  trace: three_int 1, 2, 3
  trace: four_int 1, 2, 3, 4
  trace: five_int 1, 2, 3, 4, 5
  trace: five_dbl 1.1, 2.2, 3.3, 4.4, 5.5
```

**Comment by LiaoPeng** [comment]
I found the `trace` test cases and it worked fine.
It's weird that `trace` function  works fine in `trace.ts` file and works improperly in other file.

![image](https://user-images.githubusercontent.com/4305499/60576022-2b220c00-9daf-11e9-8b58-bc63a2210d67.png)

And the generated optimized wast files are difference.

The optimized wast file in set.ts
```
(module
 (type $FUNCSIG$viiddddd (func (param i32 i32 f64 f64 f64 f64 f64)))
 (type $FUNCSIG$v (func))
 (import "env" "trace" (func $~lib/builtins/trace (param i32 i32 f64 f64 f64 f64 f64)))
 (memory $0 1)
 (data (i32.const 8) "\1a\00\00\00\01\00\00\00\01\00\00\00\1a\00\00\00z\00e\00r\00o\00_\00i\00m\00p\00l\00i\00c\00i\00t")
 (export "memory" (memory $0))
 (start $start)
 (func $start (; 1 ;) (type $FUNCSIG$v)
  i32.const 24
  i32.const 0
  f64.const 0
  f64.const 0
  f64.const 0
  f64.const 0
  f64.const 0
  call $~lib/builtins/trace
 )
 (func $null (; 2 ;) (type $FUNCSIG$v)
  nop
 )
)
```
The generated optimized wast file in trace.ts
```
(module
 (type $FUNCSIG$viiddddd (func (param i32 i32 f64 f64 f64 f64 f64)))
 (type $FUNCSIG$v (func))
 (import "env" "trace" (func $~lib/builtins/trace (param i32 i32 f64 f64 f64 f64 f64)))
 (memory $0 1)
 (data (i32.const 8) "\1a\00\00\00\01\00\00\00\01\00\00\00\1a\00\00\00z\00e\00r\00o\00_\00i\00m\00p\00l\00i\00c\00i\00t")
 (global $~lib/started (mut i32) (i32.const 0))
 (export "__start" (func $start))
 (export "memory" (memory $0))
 (func $start (; 1 ;) (type $FUNCSIG$v)
  global.get $~lib/started
  if
   return
  else   
   i32.const 1
   global.set $~lib/started
  end
  i32.const 24
  i32.const 0
  f64.const 0
  f64.const 0
  f64.const 0
  f64.const 0
  f64.const 0
  call $~lib/builtins/trace
 )
 (func $null (; 2 ;) (type $FUNCSIG$v)
  nop
 )
)
```

Can you check that? Or is there some careful thing  when using `trace` function.

**Comment by MaxGraey** [comment]
Ah. I see. In second case you should call `__start` manually.
cc @dcodeIO

**Comment by dcodeIO** [comment]
I think that's [accessing memory during instrantiation](https://docs.assemblyscript.org/details/memory#accessing-memory-during-instantiation). In our test cases for example, logging in top-level code requires adding `--explicitStart` to `asc_flags` in the respective .json file.

**Comment by LiaoPeng** [comment]
Got it, thanks.
