### ISSUE TITLE
[Feature Request] String.UTF8.decode slice parameters or `Buffer` implementation

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#707]
When attempting to port a zip file implementation, I needed to compare some string values. This line here uses the Buffer api: https://github.com/ronomon/zip/blob/master/index.js#L172

Would be nice to have a few extra parameters on the `decode` function so that the buffer can be sliced:

```ts
String.UTF8.decode(buffer, false, offset + 9, offset + 9 + size - 5);
```

In the meantime, what I need to do is copy the buffer slice to _another buffer_ to use the ergonomic api.

```ts
let temp = buffer.slice(offset + 9, offset + 9 + length);
let str = String.UTF8.decode(temp, false); // I'm unsure if this is correct

// alternatively

let length = size - 5;
let temp = new ArrayBuffer(length);
memory.copy(changetype<usize>(temp), changetype<usize>(buffer) + offset + 9, length);
```

Another valid way of solving this problem would be to use memcompare on buffer slices, which would prevent the need for the utf8 encoder, but I realize that the lack of a node `Buffer` api is the real issue here.

I would offer to help if I was able to port the `Buffer` api, but that would take a very long time, and it might not be in the scope of this project. Thoughts?

**Comment by bowenwang1996** [comment]
`ArrayBuffer` has a `slice` method

**Comment by jtenner** [comment]
Yeah the real issue is `Buffer` support :)

**Comment by dcodeIO** [comment]
One way to do this today is to use the `decodeUnsafe` variant that doesn't take a buffer but a pointer into its data, with a length. Apart from that, I think that adding the necessary parameters as proposed here is relatively straight-forward. Must do additional bounds checks then that might not be unnecessary, ofc. Maybe a special `decodeSlice` method?

**Comment by jtenner** [comment]
Yeah I'm contrantly practicing implementing parsers and I hardly ever need a single array buffer parsed. It's always a single slice of the buffer. Also options are great! Ty

**Comment by jtenner** [comment]
I think I could implement this method myself after I finish Array#flat().

Would you accept a pull request for `decodeSlice(buffer, nullTerminated, start, end)` using slice parameter logic. I.E. Negative indices means from the end of the array.
