### ISSUE TITLE
[Bug] Supplying folder for `--lib` results in no lib files found

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#714]
I tried to follow the error as best as I can and I found the problem inside `listFilesNode()`

```ts
  function listFilesNode(dirname, baseDir) {
    var files;
    try {
      stats.readTime += measure(() => {
        console.log(baseDir, dirname);
        files = fs.readdirSync(path.join(baseDir, dirname)).filter(file => /^(?!.*\.d\.ts$).*\.ts$/.test(file));
      });
      return files;
    } catch (e) {
      return [];
    }
  }
```

When this function is called, `baseDir` is `undefined`.

Can be fixed by calling `libFiles = listFiles(libDir, baseDir);` instead.

Which file should be changed exactly? Is it the `assemblyscript/cli/asc.js` file? If so, I'd be happy to write a pull request with that change.

**Comment by willemneal** [comment]
Yep that's the one.  Though this has me wondering what your use case is?  Could it not be solved with package management, e.i #594?

**Comment by jtenner** [comment]
Use case is I want to supply an assembly folder to export all the assembly root files as globals. This is expected behavior according to @dcodeIO

**Comment by MaxGraey** [comment]
@jtenner Is it still relevant issue?

**Comment by jtenner** [comment]
No this not. This how the assemblyscript/node project sets up tests. I think I submitted the pull request to fix it.
