### ISSUE TITLE
[Bug] TypeError: assemblyscript.getDependee is not a function

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#715]
```
TypeError: assemblyscript.getDependee is not a function
npm ERR! Test failed.  See above for more details.
```

Using fresh install of master. Seems like dist files are outdated. I realize that I could build assemblyscript and link it manually, but this problem will persist currently for users who want a fresh install of master.

**Comment by Bakuenjin** [comment]
Same happened to me.

Users that need a fresh install should install the previous verified commit:
`npm i --save-dev AssemblyScript/assemblyscript#678593d7bd8ee9573eadbd43e3635e0bc0b8e15e`

**Comment by dcodeIO** [comment]
Just updated the dist files. Does it work now?

**Comment by Bakuenjin** [comment]
Everything seems to work now. Thanks!

**Comment by jtenner** [comment]
Confirmed! Thank you.
