### ISSUE TITLE
On default runtime binary size

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#718]
As of https://github.com/AssemblyScript/assemblyscript/issues/717 it seems that bundling the `full` runtime by default leads to confusion regarding binary file size. That's one thing I've been worried about when the runtime landed.

The underlying reason is that the `full` runtime exposes the runtime interfaces externally, so the loader can pick these up, and whatever is reached from the runtime exports becomes compiled. The alternative is to use the `half` runtime by default, which can properly DCE if none of its functionality is used, but will then lead to issues being opened asking why the loader isn't working as expected I guess.

Any ideas?

**Comment by MaxGraey** [comment]
What about scan all exported functions and classes. If we have unmanaged types in arguments and return value like `i32`, `bool`, `f64` we don't need `full runtime` and use `half rantime` as default.

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because it cannot really be fixed. Also, there have been other improvements on this front meanwhile, like stripping cyclic garbage collection logic if it isn't needed.
