### ISSUE TITLE
Breaking changes or broken example

### ISSUE THREAD

**Issue by bakugod** [AssemblyScript/assemblyscript#722]
If you try C&P code from [here] (without build) and compile it to `wasm` you should have Error about __abort function__ and when you fixed it you should have new Error about __memory access out of bounds__.

 I think it was bad example for newbies in wasm. :dog:

Can you rework the example, so that i or anyone else can run it without editing the code on wasm? 

[here]://github.com/AssemblyScript/assemblyscript/tree/master/examples/mandelbrot

**Comment by willemneal** [comment]
Hmm what is your set up?  It works fine for me on firefox on MacOSX with the most up to date commit on master.
