### ISSUE TITLE
wast execution cause `stack underflow`  in class constructor.

### ISSUE THREAD

**Issue by yyh1102** [AssemblyScript/assemblyscript#723]
When i exec this code section like below by wasm interpreter such as wagon:
![image](https://user-images.githubusercontent.com/10328169/61618069-a126de00-ac9e-11e9-995f-de8213b778e2.png)

it will cause `stack underflow` at the op `end`.

And all this code secitons are related to **class constructor**. Is there anything wrong?

**Comment by dcodeIO** [comment]
When compiling with the `--validate` option, does it report an issue? If not, "stack underflow" sounds like something on the interpreter's end.

**Comment by yyh1102** [comment]
Has the same issue. 

Seems that ops like `global.get` or `local.get` are not supported by my interpreter? And i find out that elements type of `table` is not `anyfunc` but `funcref`, which is not supported as well.  Can these ops be converted to those official defines?

**Comment by yyh1102** [comment]
When i post a simple.ts like below to the WebAssembly.studio, i got the error:
![image](https://user-images.githubusercontent.com/10328169/61622414-4e055900-aca7-11e9-8778-1526ca2fe423.png)

code:

```typescript
class Simple {
  val: u64


  constructor(v: u64) {
    this.val = v;
  }

  add(a: u64, b: u64): u64 {
    return a + b
  }
}

const s = new Simple(1);
s.add(1, 2);
```

**Comment by dcodeIO** [comment]
Opened [an issue](https://github.com/WebAssembly/binaryen/issues/2248) on the Binaryen repo to clarify the `funcref` situation.

**Comment by yyh1102** [comment]
Yeah, wagon supports this feature .But got the above original stack underflow.

**Comment by dcodeIO** [comment]
From happening at `end`, it seems that the interpreter attempts to pop a value from the stack that becomes the return of the block encapsulated in the `if`. However, the branch there doesn't push a value to the stack and is of type `none`, which is correct.

```
push 1         local.get $0
pop 1          i32.eqz
               if
push 1           i32.const 12
push 1           i32.const 9
pop 2, push 1    call $~lib/rt/stub/_alloc
pop 1, push 1    call $~lib/rt/stub/__retain
pop 1            local.set $0 ;; stack is empty
               end
push 1         local.get $0
```

Suggesting to open an issue on the wagon repo to clarify.

**Comment by yyh1102** [comment]
Found out that more details of code:
```wast
(func $~lib/arraybuffer/ArrayBufferView#constructor (; 13 ;) (type $FUNCSIG$iiii) (param $0 i32) (param $1 i32) (param $2 i32) (result i32)
  (local $3 i32)
  (local $4 i32)
  (local $5 i32)
  local.get $1
  i32.const 1073741808
  local.get $2
  i32.shr_u
  i32.gt_u
  if
   unreachable
  end
  local.get $1
  local.get $2
  i32.shl
  local.tee $1
  i32.const 0
  call $~lib/rt/stub/__alloc
  local.set $3
  local.get $3
  i32.const 0
  local.get $1
  call $~lib/memory/memory.fill
  local.get $0
  i32.eqz
  if
   i32.const 12
   i32.const 2
   call $~lib/rt/stub/__alloc
   call $~lib/rt/stub/__retain
   local.set $0
  end
  local.get $0
  i32.const 0
  i32.store
  local.get $0
  i32.const 0
  i32.store offset=4
  local.get $0
  i32.const 0
  i32.store offset=8
  local.get $0
  local.tee $4
  local.get $3
  local.tee $5
  local.get $4
  i32.load
  local.tee $4
  i32.ne
  if
   local.get $5
   call $~lib/rt/stub/__retain
   drop
   local.get $4
   call $~lib/rt/stub/__release
  end
```

It throw `stack underflow` when execute at `end`.

**Comment by yyh1102** [comment]
I found out that the error was caused by the metering code. When i delete the metering code, it works.
I gonna metering a line of code which means `useGas(xx)` to the beginning of every block, and implement it by interpreter side. Why it will cause `stack underflow`?

**Comment by dcodeIO** [comment]
Considering such a `useGas(xx)` function call

* it must push `xx` to the stack before the call as it will otherwise consume something else from the stack, leading to an underflow
* if it returns a value, it must `drop` the return value to keep the stack clean, as it will otherwise lead to an "overflow"

**Comment by yyh1102** [comment]
Thanks for your reply. And the issue is caused by the wrong call immediates~ I' ll close this issue.
