### ISSUE TITLE
Maps with Uint8Array keys accessing illegal memory.

### ISSUE THREAD

**Issue by iwasaki-kenta** [AssemblyScript/assemblyscript#729]
I tried create the map: `const balances = new Map<Uint8Array, u64>();`

The two following separate functions are then called, with `_contract_init` being first, and `_contract_balance` being second:

```ts
export function _contract_init(): void {
  const params = Parameters.load();
  balances.set(params.sender_id, 100_000);
}

export function _contract_balance(): void {
  const params = Parameters.load();
  const target = params.bytes(32);

  const balance = balances.has(target) ? balances.get(target) : 0;
  log("Balance: " + balance.toString());
}
```

where `params.sender_id` is a `Uint8Array`, and `target` is also a `Uint8Array`. Upon calling the following line:

`const balance = balances.has(target) ? balances.get(target) : 0;`

The WebAssembly VM running the code crashes reporting that the module attempted to access illegal memory.

My forethoughts are that perhaps Uint8Arrays or other typed arrays may not be viable keys for Map's. Would like to ask if that is true, and if so then it would be good to clarify what are viable key types for Maps in the docs.

Would also like to ask if there may be any way around this, or if a new custom Map type has to be implemented. Curious on how exactly the internals of Map works.

**Comment by willemneal** [comment]
Here is the internal hash function:

```ts
@inline
export function HASH<T>(key: T): u32 {
  // branch-level tree-shaking makes this a `(return (call ...))`
  if (isString(key)) {
    return hashStr(key);
  } else if (isReference<T>()) {
    if (sizeof<T>() == 4) return hash32(changetype<u32>(key));
    if (sizeof<T>() == 8) return hash64(changetype<u64>(key));
  } else if (isFloat<T>()) {
    if (sizeof<T>() == 4) return hash32(reinterpret<u32>(key));
    if (sizeof<T>() == 8) return hash64(reinterpret<u64>(key));
  } else {
    if (sizeof<T>() == 1) return hash8 (<u32>key);
    if (sizeof<T>() == 2) return hash16(<u32>key);
    if (sizeof<T>() == 4) return hash32(<u32>key);
    if (sizeof<T>() == 8) return hash64(<u64>key);
  }
  unreachable();
}
```

Since Uint8Array is a reference, it's address is hashed and is the key.  I'm not sure what Parameters does, but my assumption is that in the second function a new array is created with a different hash.  So I would suggest extending the Map class to be a binary tree, so that the value of the key is used when searching.  Though you could change the hash function used so that it will hash the value of the array, but not sure an 8 byte long hash for a 32 byte long number is safe.  

It also seems that you're using an array as a big number.  I would recommend checking out: [bignum.wasm](https://github.com/MaxGraey/bignum.wasm) as it provides an API for using them, which would aid in comparing them if you decide to use a binary tree.

Also what VM implementation are you running on?  Is there a stack trace?

**Comment by iwasaki-kenta** [comment]
> Here is the internal hash function:
> 
> ```ts
> @inline
> export function HASH<T>(key: T): u32 {
>   // branch-level tree-shaking makes this a `(return (call ...))`
>   if (isString(key)) {
>     return hashStr(key);
>   } else if (isReference<T>()) {
>     if (sizeof<T>() == 4) return hash32(changetype<u32>(key));
>     if (sizeof<T>() == 8) return hash64(changetype<u64>(key));
>   } else if (isFloat<T>()) {
>     if (sizeof<T>() == 4) return hash32(reinterpret<u32>(key));
>     if (sizeof<T>() == 8) return hash64(reinterpret<u64>(key));
>   } else {
>     if (sizeof<T>() == 1) return hash8 (<u32>key);
>     if (sizeof<T>() == 2) return hash16(<u32>key);
>     if (sizeof<T>() == 4) return hash32(<u32>key);
>     if (sizeof<T>() == 8) return hash64(<u64>key);
>   }
>   unreachable();
> }
> ```
> 
> Since Uint8Array is a reference, it's address is hashed and is the key. I'm not sure what Parameters does, but my assumption is that in the second function a new array is created with a different hash. So I would suggest extending the Map class to be a binary tree, so that the value of the key is used when searching. Though you could change the hash function used so that it will hash the value of the array, but not sure an 8 byte long hash for a 32 byte long number is safe.
> 
> It also seems that you're using an array as a big number. I would recommend checking out: [bignum.wasm](https://github.com/MaxGraey/bignum.wasm) as it provides an API for using them, which would aid in comparing them if you decide to use a binary tree.
> 
> Also what VM implementation are you running on? Is there a stack trace?

Ahh interesting, I see. The VM implementation I am using is https://github.com/perlin-network/life.

I'd be interested in contributing this actually. I assume it'll be hard to modify the current Map impl given that it conforms highly to the Map impl described on MDN.

I'll modify up the hash function to support TypedArrays as well for keys s.t. the values are hashed by default before being inserted into the map :+1:.
