### ISSUE TITLE
AS that does not use floats should not compile into Wasm that uses floats

### ISSUE THREAD

**Issue by nearmax** [AssemblyScript/assemblyscript#732]
Floats cannot be used in Wasm contracts that are running on blockchains due to the non-determinism. The way to prevent it is to disallow Wasm that has floats, by inspecting it before execution. Unfortunately, in some cases AssemblyScript that does not use floats can compile to Wasm that uses floats, e.g. when formatting strings. Our [blockchain](https://nearprotocol.com) uses both AssemblyScript and Rust for smart contracts and floats are causing significant issues for us because AssemblyScript prevents us from disabling floats. I think it is a high priority for AssemblyScript to fix it, since the blockchains constitute a very large user-base of AssemblyScript and Wasm.

**Comment by dcodeIO** [comment]
Can you share an example of code that resorts to using floats where it shouldn't?

**Comment by MaxGraey** [comment]
I guess it NaN result for [`parseInt`](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/util/string.ts#L73):
https://webassembly.studio/?f=9dt8hh1mnzm

```wat
f64.const nan (;=nan;)
i32.trunc_s/f64)
```
