### ISSUE TITLE
Can `start` be removed?

### ISSUE THREAD

**Issue by yyh1102** [AssemblyScript/assemblyscript#734]
I found out that `start` is often used to initialize memory or something like that? Can we remove `start` section at compilation period and do those memory things in other ways?

**Comment by willemneal** [comment]
Yes you can use the cli option `--explicitStart`.  By default each entry file's top level statements are placed into start functions with a main start function that calls each of them and is included in the start section of the binary.  However, `--explicitStart` exports a function named `__start`, which can be called after the module has been instantiated by the loader.  

There is also a data section in the binary, which the compiler uses to place any string literals and other static data.  So by the semantics of the wasm loader this section will be read during instantiation and copied into the memory regardless of the start function.

Also be careful with this approach as you shouldn't call any other exported function as things like heap and runtime won't be instantiated until `__start` is called.
