### ISSUE TITLE
Link AssemblyScript  with a module in c/cpp

### ISSUE THREAD

**Issue by geloizi** [AssemblyScript/assemblyscript#741]
Is it possible to link AssemblScript with modules written in other languages, primarily C/C++? The use case - there is a library in C that's I'd like to call from AssemblScript.

**Comment by jtenner** [comment]
This requires linking. I think.

Also, when this feature is supported by wasm runtimes, you'll be able to pass in `@unmanaged` class references to c api functions.

This is my understanding. Maybe I'm mistaken?

**Comment by MaxGraey** [comment]
cross-language communication or FFI in WebAssembly is one of fundamental problems. I guess only WebIDL-binding (declaration) could resolve this issue in general case.

**Comment by geloizi** [comment]
The question is - how to produce a static library using AssemblyScript compiler? This library could be linked with a something else. I do understand that "complicate" data types (like `string`, or `Array`) cannot be passed from AssemblyScript to C, but basic ones (numbers) should work.

**Comment by jtenner** [comment]
Yep. You will just need to know c layout, and use the assemblyscript builtins to your advantage. All of us are waiting for web assembly features to be standardized like webidl, anyref, gc etc.

**Comment by dcodeIO** [comment]
The challenges with proper linking are described at [tool-conventions/Linking](https://github.com/WebAssembly/tool-conventions/blob/master/Linking.md). In particular, Wasm elements must be renumbered and memory and table offsets relocated in a way that the individual parts don't conflict. My expectation is that Binaryen will support static linking eventually, and we'd reuse what it provides by generating the respective reloc sections. Not there yet, though.

**Comment by willemneal** [comment]
This seems like the way to go forward with this:

https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md#walkthrough

Basically have a special section in each binary for how to convert export and imports to and from abstract interface types like strings, arrays, etc.

**Comment by J-Rojas** [comment]
Would love to use AssemblyScript but much of the code that I need to adapt is written in C/C++ and I wouldn't want to write two WASM modules that need JS glue to pass data between them. It would be great to have binaryen be able to link module interfaces written in different languages on the back end.

**Comment by munrocket** [comment]
It's possible right now if you have *really simple C/C++ code* and you can compile it with clang without runtime and memory. [Here](https://github.com/WebAssembly/wabt/issues/1563) concatenation problem described better. Basically we need reference types and multi memories for linking more complex code in one wasm sandbox.
