### ISSUE TITLE
TypedArray.dataStart should be documented

### ISSUE THREAD

**Issue by cdetrio** [AssemblyScript/assemblyscript#743]
It is currently undocumented (see https://github.com/AssemblyScript/assemblyscript/issues/667#issuecomment-502259879).

**Comment by dcodeIO** [comment]
This is an internal pointer and as such non-standard. The way this works is that `byteOffset` is computed from `dataStart - data` and stdlib internals use `dataStart` directly to avoid redundant computation.

A way to compute its value is

```ts
changetype<usize>(view.buffer) + view.byteOffset
```

May I ask what's your use case for this suggestion?

**Comment by cdetrio** [comment]
Okay, good to know. I was using it all over the place as shorthand for `changetype<usize>(view.buffer) + view.byteOffset`, which seems quite verbose for something as common as a pointer to a subarray.

One use case is access the substring of a string encoded in an ArrayBuffer. The convenient way to do this is with a view (either a TypedArray or a DataView) over a subarray of the buffer. An alternative is to use `ArrayBuffer.slice` but that has the overhead of memcpy. It's a bit counter-intuitive that `String.UTF8.decode` only accepts ArrayBuffers, and so to avoid the overhead of memcpy you have to pass view.buffer with the offset to `String.UTF8.decodeUnsafe`. I assume String.substring also returns a copy, but in any case I only want to re-encode the subarray and not the whole string (which might be very big).

Here's a fiddle with the different options as a new user would try them: https://webassembly.studio/?f=6qgyxki0v7p (side note: there is no easy way to use the [loader](https://docs.assemblyscript.org/basics/loader) in webassembly.studio).

Maybe `String.UTF8.decode` could accept a view directly as well as an ArrayBuffer? And a property added to views as shorthand for `changetype<usize>(view.buffer) + view.byteOffset`.

**Comment by MaxGraey** [comment]
Hmm, @jtenner had a similar request about optional arguments `offset` and `length`  for `String.UTF8.decode`.

**Comment by jtenner** [comment]
I believe that is what `decodeUnsafe()` is for. :)
