### ISSUE TITLE
Explicitly passing undefined to optional argument produces different result than ommiting 

### ISSUE THREAD

**Issue by JamesMilnerUK** [AssemblyScript/assemblyscript#747]
I don't believe this is necessarily a bug, more of a gotcha. Here's a small example to demonstrate:

```typescript
export function foo(a: i32, b: i32 = 2): i32 {
	return a + b;
}
```

Here you can ignore that `b` doesn't have the `?` as I had to remove it to get it to compile (see #747 for more details).

Now the test suite showing the difference:

```javascript
test('foo', (t) =>{
    t.equals(wasmModule.foo(1), 3); // PASSES
    t.equals(wasmModule.foo(1, undefined), 3); // FAILS
    t.end();
})
```

Here this differs from ES6 behaviour where even if you pass explicit undefined the default value is still taken:

```javascript
function foo(a, b = 1)
  return a + b;
}

multiply(5, undefined)) // Returns 6
```

Thought it might be useful to bring it to peoples attention. If you would like me to add this to the documentation let me know and I will look into making a PR

**Comment by dcodeIO** [comment]
The reason for failing is that the call uses a trampoline to insert optional arguments, and the trampoline asserts that there are either one or two arguments. Leaving out the third argument should work as expected.
