### ISSUE TITLE
Math.seedRandom causes overflow error

### ISSUE THREAD

**Issue by bowenwang1996** [AssemblyScript/assemblyscript#749]
The following line 
```typescript
Math.seedRandom(0);
```
will cause code to fail with an overflow error. Fiddle example [here](https://webassembly.studio/?f=nvtes6puvcc).

**Comment by MaxGraey** [comment]
`seed` number should be any integer value [except zero](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/math.ts#L1020)

**Comment by bowenwang1996** [comment]
Interesting. I think it worked before with seed = 0.

**Comment by MaxGraey** [comment]
We could do this in theory:
```ts
if (!value) value = -1;
```
instead `assert(0)`
