### ISSUE TITLE
Using separate dependency for the loader

### ISSUE THREAD

**Issue by bobbinth** [AssemblyScript/assemblyscript#750]
What is a good way to use a separate dependency for the loader?

What I'd like to do in my project is to move `assemblyscript` dependency into `devDependencies` but keep the loader in regular dependencies.

**Comment by jtenner** [comment]
@dcodeIO I've been thinking about this. Would it be possible to move the loader itself into an `AssemblyScript/[insert whatever name here]`  package?

**Comment by cdetrio** [comment]
On a related note, if the loader used [es6 exports](https://github.com/cdetrio/assemblyscript/commit/8d3035623a156bdd1d55f0208ca728cfa880840e) then it'd be easy to import into js files in the studio: https://webassembly.studio/?f=dza8o7yp1s

**Comment by dcodeIO** [comment]
Plan so far was to publish the loader as a standalone [@assemblyscript/loader](https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/package.json#L2) package eventually.

**Comment by bobbinth** [comment]
I think this would work very well. Is there anything blocking @assemblyscript/loader package?

**Comment by bobbinth** [comment]
I think this is working now. Thank you very much! I only noticed two minor issues:

1. In the docs [here](https://docs.assemblyscript.org/basics/loader), the example says that loader should be imported as `const loader = require("assemblyscript/lib/loader");` but I think it should actually be `const loader = require("@assemblyscript/loader");`

2. The loader package pulls in `@types/webassembly-js-api` package which conflicts with my TypeScript lib for some reason. So, I have to manually remove `@types/webassembly-js-api` from `node_models` for everything compile. Not sure if this references is needed, or if there is a way to get rid of it.

**Comment by MaxGraey** [comment]
yes `@types/webassembly-js-api`  not need anymore with latest typescript. Will fix

**Comment by MaxGraey** [comment]
Ok, all issues should be fixed now

**Comment by bobbinth** [comment]
Thanks! Is it going to go on NPM as v0.8.1?

**Comment by MaxGraey** [comment]
no, as `v0.8.0-nightly.20191118` after midnight I guess

**Comment by dcodeIO** [comment]
There have been quite a few fixes lately, so I sliced a 0.8.1 version that should be published at 0 UTC. Will show if the release theory works in practice :)

**Comment by bobbinth** [comment]
Seems like working. Thanks again! I'm closing this issue.
