### ISSUE TITLE
memory.copy should be documented

### ISSUE THREAD

**Issue by cdetrio** [AssemblyScript/assemblyscript#753]
See https://github.com/AssemblyScript/assemblyscript/issues/667#issuecomment-502244659 and https://github.com/AssemblyScript/assemblyscript/pull/467

Searching the documentation returns no results for `memory.copy`:

![Screen Shot 2019-08-09 at 7 54 11 AM](https://user-images.githubusercontent.com/997681/62777270-063e4a00-ba7b-11e9-8dfc-5e2226596d9c.png)

**Comment by dcodeIO** [comment]
Added to [Environment / Memory](https://docs.assemblyscript.org/basics/environment#memory).
