### ISSUE TITLE
Strange behaviour of Array#findIndex

### ISSUE THREAD

**Issue by pfortini** [AssemblyScript/assemblyscript#754]
I am having some strange behaviour on the Array#findIndex method. I have a class with the property "state" which is an array of objects containing the property "name".

When trying to implement a "find" method for my class, I got to this error. When using .findIndex I get the return -1, meaning that "name" could not be found. code below:

```typescript
find(name: string): i32 {
	return this.state.findIndex(
		(glob): bool => {
			return glob.name == name;
		}
	);
}
```

However, I know it is there. And if I write a simple loop, as of below, i get the normal result I'd expect
```typescript
find(name: string): i32 {
	for (let i = 0; i < this.state.length; i++) {
		if (this.state[i].name == name) return i;
	}
	return -1;
}
```

Am I missing something crucial here?

**Comment by MaxGraey** [comment]
Could you provide more info? Or better make fiddle in [WebAssembly Studio]. Are you sure you use `==` in your original code?

**Comment by pfortini** [comment]
> Could you provide more info? Or better make fiddle in [WebAssembly Studio]. Are you sure you use `==` (and not `===`) in your original code?

I reproduced the error on WebAssembly Studio, but could not figure out how to share the project. However, this is the whole code you need to reproduce the error:

```typescript

export class glob {
  name: string
  constructor(name: string) {
    this.name = name
  }
}

export class MyClass {
  state: Array<glob>
  constructor() {
    this.state = Array.create<glob>()
  }

  set(name: string): void {
    this.state.push(new glob(name))
  }

  findviaIndex(name: string): i32 {
    return this.state.findIndex((_glob): bool => { return _glob.name == name })
  }

  findviaLoop(name: string): i32 {
    for (let i = 0; i < this.state.length; i++) {
      if (this.state[i].name == name) return i
    }
    return -1
  }
}

export function test(method: i32): i32 {
  let myObj = new MyClass()
  myObj.set("state")
  if (method == 0)  return myObj.findviaLoop("state")
  return myObj.findviaIndex("state")
}
```

calling for test(0) will use the loop method and return 0 as expected, but calling for test(1) will return -1

**Comment by MaxGraey** [comment]
Ahh, I got what is problem. AssemblyScript currently not support capturing lexical environment (closures). That's why `state.findIndex(glob => _glob.name == name)` not works properly but `state.findIndex(glob => _glob.name == "state")` does.

**Comment by pfortini** [comment]
Ohh I see... now I understand it. Perhaps there were even other parts of my code suffering from this and I didn't notice it. Thanks for the help!

**Comment by mariusa** [comment]
3 years later...This still doesn't work `state.findIndex(glob => glob.name == name)` : `ERROR AS100: Not implemented: Closures`

Are these array methods unusable with variables? If so, do we need to implement our own functions, which would do `for (let i=0; ...) ?`

**Comment by sebastiantf** [comment]
Still unusable with closurs
