### ISSUE TITLE
Cannot Extend ArrayBufferView

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#759]
https://github.com/AssemblyScript/assemblyscript/blob/4c938f7689c39e3a1ad813356781e2689fd4ec70/src/program.ts#L3316

Example code I would like to write:

```ts
export class BTree<T> extends ArrayBufferView {
  [key: number]: T;
```

Is there a better way to resolve the getter type than the way it's implemented in the resolver?

If yes, please guide me and I'll try to submit a pull request sometime next week.

**Comment by dcodeIO** [comment]
Not meant to be extended. Would expect any extension so break as soon as the compiler attempts optimizing views by passing by value.

**Comment by jtenner** [comment]
Okay. Let's take my `BTree<i32>` example. I actually want to folow the format Arrays currently are in. Tightly packed in little endian format just like an ArrayBuffer view. It would be nice to extend `ArrayBufferView<T>` and forget about the implementation.

```ts
class BTree<T> extends ArrayBufferView<T> {
  length_: i32 = 0;

  constructor(capacity: i32 = 0) {
    super(capacity);
  }
}
```

**Comment by dcodeIO** [comment]
What you are looking for is a custom collection, similar to `Set<T>`, not ABV.

**Comment by jtenner** [comment]
I'm sure extending array itself is the right call here.
