### ISSUE TITLE
Complex computation slower than JavaScript

### ISSUE THREAD

**Issue by hjlld** [AssemblyScript/assemblyscript#760]
Hello, I'm working on solve a problem that compute the minimum distance between two geometries in 3D space. I choose a brutal force algorithm, it's a complexity `O(nm)` for `nm` distances computed. 

It only relies on + - * / and Mathf.sqrt(), Mathf.abs() computation, all numbers are f32.

Any way I realized it by Javascript( compiled from Typescript ), then I use the same Typescript code to compile it to wasm by AssemblyScript's compiler.

The wasm way also works, but seems even slower than JS.

For example, same two geometries, in JS cost 83 seconds, but in wasm / web worker, need 445 seconds.

Any one could help me to provide any idea or possible reason?

BTW, I use wasm in web workers, but all typedarray are transferable with their buffer, like ` Worker.postMessage( typedarray, [ typedarray.buffer ] )  `, so i don't think the data transfer between main thread and worker thread is the key.

**Comment by MaxGraey** [comment]
> so i don't think the data transfer between main thread and worker thread is the key.
Probably interop between wasm and js is a key. Without full source of code hard to tell what's wrong. Are you use `-O3` and `--noAsset` flags?

**Comment by hjlld** [comment]
No, i don't use any flags, the code for passing typedarray to wasm please see this gist: 

https://gist.github.com/hjlld/db8f3856fb9b8724814c2f3ef722e1d7

and in AS i exported relative type id by:

```
export const Uint32Array_ID = idof<Uint32Array>();

export const ArrayUint32Array_ID = idof<Array<Uint32Array>>();

export const Float32Array_ID = idof<Float32Array>();

export const ArrayFloat32Array_ID = idof<Array<Float32Array>>();
```

**Comment by MaxGraey** [comment]
And you measure `this.wasmModule.CalDistanceOfTwoMeshArray` method? Could you show `CalDistanceOfTwoMeshArray` source code body?

**Comment by hjlld** [comment]
the two geometries i mentioned before, each one have 28052 f32 numbers, which means totally 28052 * 2 numbers passed from JS to wasm make the computation.

@MaxGraey the full computation code is updated in the same gist:

https://gist.github.com/hjlld/db8f3856fb9b8724814c2f3ef722e1d7#file-caldistanceoftwomesharray-ts

**Comment by MaxGraey** [comment]
Several suggestions:
- I saw this `Min([distance1, distance2, distance3])`. Better use `Min(distance1, distance2, distance3)` without creation array, so function looks like:
```ts
@inline
function Min(a: f32, b: f32, c: f32): f32 {
  return Mathf.min(a, Mathf.min(b, c));
}
```

- inline (@inline decorator) any small util functions
- use `-O3` and `--noAssert` compiler flags
- cache `array.length` like:
```ts
for (let i = 0, ilen = meshes1.length; i < ilen; i ++ ) {
        for ( let j = 0, jlen = meshes2.length; j < jlen; j ++ ) {
            ...
        }
}
```
- use `unchecked()` like:
```ts
let mesh = new Mesh( unchecked(positions2[ i ]), unchecked(indices2[ i ]), unchecked(matrices2[ i ] ));
```
and for set index accessors:
```ts
unchecked(vertex1Array[ i ] = 100.0f)
```

**Comment by MaxGraey** [comment]
How you measure?

**Comment by hjlld** [comment]
It's a brutal force algorithm.

0) many geometries/meshes composes one object, problem is to measure closest distance between two objects.

1) one geometry/mesh is composed by many triangles, we compute distances between every triangle of the first object and every triangle of the second object.

2.) for distance between triangles, we calculate distances between every line segment of a triangle and the other triangle.

3) for distance between line segments and triangle, we calculate distances between the two extreme point of the line and the triangle, as well as distances between the line segment and every line segments of the triangle.

4) for distance between a point and a triangle, we calculate distances between this point and every line segments of the triangle.

all computations return the minimum value, it's the closest distance.

**Comment by MaxGraey** [comment]
I mean how you measured performance? Is it `performance.now` which measure `CalDistanceOfTwoMeshArray` only function whole `MeasureNearestDistanceByWASM` function?

**Comment by hjlld** [comment]
I use `performance.now()` before and after `MeasureNearestDistanceByWASM ` function in JS

**Comment by MaxGraey** [comment]
Got it. So you measure also a lot of array's creation and interops which not exists on JS side. You should optimize `MeasureNearestDistanceByWASM` glue code first. This is huge bottleneck

**Comment by hjlld** [comment]
thanks a lot , i'll fix the code and try again.

**Comment by hjlld** [comment]
should every `array[ index ]` be wrapped by `unchecked()` ?

**Comment by MaxGraey** [comment]
Yes, this skip bounds check. But until this [PR](https://github.com/AssemblyScript/assemblyscript/pull/756) which fix some missing unchecked methods for typed arrays is not landed in dist files this `unchecked` hints just ignored. But in next AS update this will be necessary

**Comment by hjlld** [comment]
i'll close this, try to implement a new algorithm. Thanks @MaxGraey  a lot!
