### ISSUE TITLE
Import file '~lib/allocator/tlsf.ts' not found.

### ISSUE THREAD

**Issue by lbittner-pdftron** [AssemblyScript/assemblyscript#763]
Hello!

I am trying to get a basic project running, but cannot seem to get the project to build due to the following error:

```
ERROR: Import file '~lib/allocator/tlsf.ts' not found.
```

My index.ts file looks like so:

```
import "allocator/tlsf";
export { memory };

export function sayHello(hello: string): string {
  return hello + "world";
}
```

and I am running the standard `npm run asbuild` command that ships with the project.

Am I missing something here?

Thanks!

**Comment by jtenner** [comment]
You don't need to import an allocator any more. The tlsf allocator is built into the compiler with the new runtime. Try removing that statement.

**Comment by willemneal** [comment]
Can I ask which directions you were following?

**Comment by lbittner-pdftron** [comment]
@willemneal I was just following some articles I found online and a couple closed issues in this repo. 

I was mainly searching how to accept a string as a function parameter, and since I had a hard time finding any official documentation/examples about that, I resorted to other resources (which I guess were outdated).

I'm brand new to this world, so this was probably just a noob issue.

Thanks guys!

**Comment by willemneal** [comment]
@lbittner-pdftron No worries, it's good to know how new people find information.  The current best resources are https://docs.assemblyscript.org/ and https://wasmbyexample.dev/#, though there is still room for improvement.

And keep asking questions!  If something isn't clear than we need to make it clearer!

**Comment by 9oelM** [comment]
was lost on this as well. This thread saved me.
