### ISSUE TITLE
Cannot import functions using namespace

### ISSUE THREAD

**Issue by lbittner-pdftron** [AssemblyScript/assemblyscript#764]
Hello!

I am trying to use the [namespace import feature](https://docs.assemblyscript.org/basics/exports-and-imports#imports) and am running into the following error:

```
Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #1 module="index" error: module is not an object or function
```

My index.ts looks like so:

```
declare namespace temp {
  export function test(a: string): void;
}
```

And then whenever i call `temp.test("hi");`, it throws the error above.

And my imports look like this:
```js
const imports = {
  env: {
     ...
  },
  temp: {
    test: (s) => {
      console.log(util.getString(s));
    }
  }
};
```

I can get it working with the custom naming option, but would like to use the namespace feature. Am i doing something wrong?

Side note:

I believe there is a typo in the docs [here](https://docs.assemblyscript.org/basics/exports-and-imports#imports).

The sample code looks like this:
```
declare namespace console {
  export function logi(i: i32): void;
  export function logf(f: f64): void;
}
```

But it says "This will import the functions console.logi and console.logf from the `foo` module." . I believe this should say say "the `console` module.

**Comment by dcodeIO** [comment]
In a file **foo.ts**, the following

```ts
declare namespace console {
  export function logi(i: i32): void;
  export function logf(f: f64): void;
}
```

will import

```ts
const imports = {
  foo: {
     "console.logi": ...,
     "console.logf": ...
  }
};
```

Similarly, in the example above it would be an import `"temp.test"`. To make it a function `test` in a module `temp`, the recommended way is to name the file `temp.ts` and declare an exported function `test` within.

```ts
// temp.ts
export declare function test(a: string): void;
```

**Comment by lbittner-pdftron** [comment]
I see, thank you very much for the help!
