### ISSUE TITLE
Different with JS behaviour for NaN || FloatValue

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#770]
JS/TS (expected):
```ts
NaN || 2.0 // -> 2.0
2.0 || NaN // -> 2.0
NaN && 2.0 // -> NaN
2.0 && NaN // -> NaN
```
AS (actual):
```ts
NaN || 2.0 // -> NaN
2.0 || NaN // -> 2.0
NaN && 2.0 // -> 2.0
2.0 && NaN // -> NaN
```

**Comment by jtenner** [comment]
So NaN is treated as truthy because it's not zero.

**Comment by MaxGraey** [comment]
Yeah, but should interpret as falsy.

**Comment by jtenner** [comment]
Could we have a truthy operator?

`@operator.prefix("truthy")`

Return a bool.

**Comment by MaxGraey** [comment]
No, but we have `@operator.prefix("!")`.

**Comment by dcodeIO** [comment]
Yeah, we should make it behave like in JS. Code location is in compiler.ts makeIsFalseish/makeIsTrueish, with the challenge here being that a check like `(x == 0.0) | (x != x)` needs a temporary local but there's no flow context to add one. Obvious alternative is to use a helper function ìsTrue` or so provided by stdlib.

**Comment by willemneal** [comment]
`NaN` in `js` is `("b"+ "a" + + "n" + "a" + "s").toLowerCase()`;
