### ISSUE TITLE
[Question] store values binary

### ISSUE THREAD

**Issue by Linux249** [AssemblyScript/assemblyscript#777]
Hi,

i try to store values in memory but didn't get the aspect behavior: 

When i store a <u32> var like this
```
const v1: u32 = 255 
const v2: u32 = 255 << 24 
// case 1
store<u32>(10, v1) 
load<u8>(10) // => 255
// case 2
store<u32>(10, v2) 
load<u8>(10) // => 255
```

It looks like `store` start writing with the first '1' (in a BIT viewpoint) it finds  in `value`  - what i want is that when `value` starts with 0's is also write these in the memory first. 
Case 2 is what i aspect but in case 1 `load<u8>(10)` should return 0 and `load<u8>(13)`  should return 255. 

How can i store a value like `255` as a 32-BIT value so that the first 3 Bytes are zero and the 4. is '11111111'

**Comment by jtenner** [comment]
The values are stored in little endian. `load<u8>(10)` should return the most significant bits first. Since you shifted it `255 << 24`, it should put the `11111111` right at the start. Right?

**Comment by Linux249** [comment]
> The values are stored in little endian. `load<u8>(10)` should return the most significant bits first. Since you shifted it `255 << 24`, it should put the `11111111` right at the start. Right?

Thanks for your help, the little endian ordering was the point i didn't considered.
