### ISSUE TITLE
Memory access out of bounds

### ISSUE THREAD

**Issue by lbittner-pdftron** [AssemblyScript/assemblyscript#778]
Hi (me again :D),

I am trying to pass an array around using the __allocArray function, and am running into `Memory access out of bounds` errors.

My code (simplified) looks like this:
```js
// js
const pointer = mod.__retain(mod.__allocArray(mod.UINT8_id, myArray));
instance.someFunc(pointer, myArray.length);

// wasm
export const UINT8_id = idof<Uint8Array>();

someFunc(ptr: usize, length: i32):void {
    for(let i = 0; i < length; i++) {
         let value = load<u8>((ptr + 1) << 2); // offset of 4
         // ..do something with value
         store<u8>((ptr + i) << 2, value) // offset of 4
    }
}
```

If I understand everything correctly, the `__retain` should return a pointer to the array layout, which has its data starting at an offset of 4.

What am I doing wrong here?

Thanks!

**Comment by jtenner** [comment]
Yeah the `ptr` property should be an `Uint8Array`. Not a `usize`.

AssemblyScript can treat it like a reference, and JS needs to treat it like a pointer.

You also need to `mod.__release(ptr)` your pointer on JS side unless you need to hold onto the reference for a while.

**Comment by jtenner** [comment]
If you want a pointer to the data, you can use this function instead:

```ts
// wasm
export const UINT8_id = idof<Uint8Array>();

someFunc(ref: Uint8Array, length: i32): void {
    let ptr = ref.dataStart;
    let length = ref.length;
    for(let i = 0; i < length; i++) {
         let value = load<u8>((ptr + 1) << 2); // offset of 4
         // ..do something with value
         store<u8>((ptr + i) << 2, value) // offset of 4
    }
}
```

**Comment by MaxGraey** [comment]
Just `someFunc(ref: Uint8Array): void`. `length` will retrieve from `Uint8Array`

**Comment by MaxGraey** [comment]
Also `load<u8>(ptr + 1)` and `store<u8>(ptr + i, value)`. Because `sizeof<u8>() == 1`

**Comment by lbittner-pdftron** [comment]
Great, thank you guys so much! Should this information be places somewhere in [this readme?](https://github.com/AssemblyScript/assemblyscript/tree/master/lib/loader) I feel like the documentation here is lacking for people who are new at this like me. I also personally think that more examples would be pretty useful.

Thanks again, you guys have been super helpful :)
