### ISSUE TITLE
isInteger<boolean>() returns true.

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#782]
Here is a simple example of the issue: https://webassembly.studio/?f=nv5owy8ws4

If I have the following:

```ts
function isBool<T>(): boolean {
  if (isInteger<T>()){
    return false;
  }
  return isBoolean<T>();
}
```

Then `isBool<boolean>()` returns `false`.  I found this the hard way when checking types.  For now I always check `isBoolean<T>()` first.

**Comment by dcodeIO** [comment]
So far a `bool` is considered a 1-bit [unsigned short integer value](https://github.com/AssemblyScript/assemblyscript/blob/master/src/types.ts#L505), which is why `isInteger<bool>() == true`. Like, a bool can be stored in any larger integral type. Are you suggesting to change this?

**Comment by MaxGraey** [comment]
[my thoughts about this](https://github.com/AssemblyScript/assemblyscript/pull/783#issuecomment-523618057)
