### ISSUE TITLE
Array#push causes memory problems

### ISSUE THREAD

**Issue by bowenwang1996** [AssemblyScript/assemblyscript#788]
`Array#push` calls `ensureSize`, which reallocates on every push (assuming there is no preallocated memory) https://github.com/AssemblyScript/assemblyscript/blob/12aed07918e45feced676a713ee4d5588a49f4f3/std/assembly/array.ts#L17. This causes O(n^2) memory to be allocated when doing push O(n) times.

**Comment by dcodeIO** [comment]
The [stub rt](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/rt/stub.ts#L34) isn't smart about reallocating currently. A potential improvement here might be to double the memory if `size > oldSize`, so subsequent reallocations become nops until doubling again.

**Comment by bowenwang1996** [comment]
Yes I think allocators in other languages do something similar (doubling the size).
