### ISSUE TITLE
Cannot find name 'encodeURIComponent' and 'decodeURIComponent'

### ISSUE THREAD

**Issue by anyexinglu** [AssemblyScript/assemblyscript#791]
Run `asc encode.ts -b encode.wasm -03`, throw Error: "ERROR TS2304: Cannot find name 'encodeURIComponent'"

encode.ts: 

```
/**
 * 加密函数
 * @param str 待加密字符串
 * @returns {string}
 */
export function str_encrypt(str: string): string {
  let c = String.fromCharCode(str.charCodeAt(0) + str.length)

  for (let i = 1; i < str.length; i++) {
    c += String.fromCharCode(str.charCodeAt(i) + str.charCodeAt(i - 1))
  }

  return encodeURIComponent(c)
}

/**
 * 解密函数
 * @param str 待解密字符串
 * @returns {string}
 */
export function str_decrypt(str: string): string {
  str = decodeURIComponent(str)
  let c = String.fromCharCode(str.charCodeAt(0) - str.length)

  for (let i = 1; i < str.length; i++) {
    c += String.fromCharCode(str.charCodeAt(i) - c.charCodeAt(i - 1))
  }
  return c
}

```

![image](https://user-images.githubusercontent.com/8243326/63636635-7ae0cd80-c6a4-11e9-8e7a-a587b8e15cfc.png)

Since window has 'encodeURIComponent' & 'decodeURIComponent', so in js/ts, it shouldn't throw error.

**Comment by MaxGraey** [comment]
`encodeURIComponent`/`decodeURIComponent` not implemented yet. See [our progress list](https://github.com/AssemblyScript/assemblyscript/wiki/Status-and-Roadmap#globals)

**Comment by MaxGraey** [comment]
Also `WARN: Unknown option -03` mean you use `-03` (zero and three) intead `-O3` ('O' and three)

**Comment by anyexinglu** [comment]
> Also `WARN: Unknown option -03` means you use `-03` (zero and three which wrong) instead `-O3` ('O' and three which is valid)

Thanks a lot for your reply!

**Comment by anyexinglu** [comment]
> `encodeURIComponent`/`decodeURIComponent` not implemented yet. See [our progress list](https://github.com/AssemblyScript/assemblyscript/wiki/Status-and-Roadmap#globals)

Seems that the "progress list" has missed `escape` & `unescape.

try it: 

```
const input = escape("我的01");
const output = unescape(input);
export { input, output };
```

it throws "ERROR TS2304: Cannot find name 'escape'" & "ERROR TS2304: Cannot find name 'unescape'"

![image](https://user-images.githubusercontent.com/8243326/63637748-fb0e2f80-c6b2-11e9-86aa-66d0e449e96e.png)

**Comment by MaxGraey** [comment]
Yes, `escape`/`unescape` also not implemented yet. You could do this before pass to wasm method on JS side currently

**Comment by anyexinglu** [comment]
Fine
