### ISSUE TITLE
Compiling hangs forever

### ISSUE THREAD

**Issue by arilotter** [AssemblyScript/assemblyscript#80]
When I run `asc assembly/module.ts -t module.untouched.wat -b module.untouched.wasm --validate --sourceMap --measure`, `asc` pegs my CPU at 100% and doesn't do anything. `module.ts` is a single ~370 line TypeScript file.

**Comment by dcodeIO** [comment]
Can you try to comment some things in your source file in order to find out where it hangs, and paste the remaining snippet? :)

**Comment by MaxGraey** [comment]
Try to rename `module.untouched.wat` and `module.untouched.wasm` to `module.wat` and `module.wasm`

**Comment by dcodeIO** [comment]
> Try to rename module.untouched.wat and module.untouched.wasm to module.wat and module.wasm

Huh, does that fail sometimes?

> The master branch on GitHub - I used $ npm install --save-dev AssemblyScript/assemblyscript

What's your node.js version? Does `asc -v` work and show [exactly this](https://github.com/AssemblyScript/assemblyscript/wiki/Using-the-CLI#using-the-compiler)? Does it also happen when you try to compile an empty .ts file, or remove some of the options?

**Comment by MaxGraey** [comment]
> Huh, does that fail sometimes?

That's only a guess. May be several dots in Linux [cause to problems](https://askubuntu.com/questions/413150/is-it-bad-practice-for-folder-name-to-contain-dot-how-about-file-name-with)

**Comment by arilotter** [comment]
Figured it out! I'd run `increase-memory-limit` in the directory, & it caused the `asc` command to hang - it seems changing the first line of `node_modules/.bin/asc from ```#!/usr/bin/env node``` to ```#!/usr/bin/env node --max-old-space-size=4096``` causes it to hang. Removing the flag lets asc run normally. However, asc then runs out of memory compiling my ts module and throws ```FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory``` - how should I increase the memory limit if not with that flag?

**Comment by MaxGraey** [comment]
Try bigger value for example: ```--max-old-space-size=16000``` and add also ```--optimize_for_size```. But this strange. How many system RAM you have?

**Comment by dcodeIO** [comment]
Just tried out the flag. The smallest power of 2 value that works for me for an empty .ts file is `node --max_old_space_size=64 bin/asc tests/builtins.ts`. The option is actually using underscores in my setup (node v8.9, win64).

**Comment by arilotter** [comment]
Got the argument working - I can't put it in the shebang on Linux with /usr/bin/env, but calling ```node --max_old_space_size=4096 node_modules/.bin/asc assembly/module.ts <etc>``` Runs node with the higher memory limit. Unfortunately, even with 4097mb allocated, I get an out of memory error - a different one this time:
```
#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#
```

I've uploaded my code to a gist, so you can reproduce the high memory usage for yourself. I'm trying to translate a Java program to AssemblyScript, so it's probably a weird construct in my code that's causing the compiler to fail.
https://gist.github.com/arilotter/333cacfe16e16d27e2c125a8d788f95e

**Comment by dcodeIO** [comment]
Some things I noticed while looking over it:

* `export default` isn't supported (yet)
* some functions are missing a return type annotation, mostly `: void`
* at least one function returns a plain object which isn't supported (yet)
* there are quite a few `const` variable declarations that will emit a warning because these aren't actually compile time constants, but that shouldn't be an issue to make it compile
* when using arrays, some sort of memory manager should be imported, for example `import "allocator/arena";`
* basic types like `f32` can't be nullable (seeing a `f32 | null` annotations there)
* at one occasion, a `i32` is assigned to a `f32` variable, that needs an explicit cast

When I fix/comment out the things above, it compiles for me.

**Comment by dcodeIO** [comment]
The issue seems to be related to the kind of line ending used. My guess is that when line endings are just `\n`, that the code that skips over blocks or statements on errors has an infinite loop somewhere.

**Comment by arilotter** [comment]
@dcodeIO  would you mind adding me to Slack? I've got a couple questions

**Comment by dcodeIO** [comment]
The commit above should fix this particular issue with the initial file, though the CRLF/LF issue might still be around somewhere. Feel free to reopen if it resurfaces :)
