### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [AssemblyScript/assemblyscript#801]
I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file. This would allow a canonical address to send funds to. For example, I'm building a project that allows developers to setup one recurring donation that is split between all of their dependencies with an Ethereum address: https://sustainus.io

**Comment by dcodeIO** [comment]
Can try to get Eth and Btc addresses up, just not sure how the rest of the team thinks of it since that's not as transparent as OpenCollective. Objections?

**Comment by MaxGraey** [comment]
It seems this package is not yet mature (just couple of days) https://github.com/lastmjs/sustainus. I'm not sure how this secure, especially when time to time npm produce modules which could [steal your private key in 2019](https://www.theregister.co.uk/2019/06/07/komodo_npm_wallets/) and [2018 years](https://medium.com/learnwithrahul/all-about-the-stealing-of-cryptocurrency-by-a-node-module-8793dd0e9e60)

**Comment by lastmjs** [comment]
Adding the Ethereum address is to FUNDING.yml is not specific to my project, though my project is probably the only one looking there for now.

There is a security trade-off for ease of use, but I don't think it's that big of a deal. Any package you install could steal anything on your machine essentially. People shouldn't be storing large amounts of crypto in Sustainus, and the security can evolve over time. Right now I'm building an MVP to prove the concept

**Comment by MaxGraey** [comment]
@lastmjs Now I see, thanks!
Now it looks like draft concept. I have many questions about how founds will distribute between submodules of some dependent module which put address to FUNDING.yml. Different modules have different complexity and importance for the current project, but now the funds are distributed evenly among everyone, right?

**Comment by lastmjs** [comment]
Right now if you install Sustainus on your machine it scans every dependency and lists those with Ethereum addresses. The payout is distributed evenly for now. That's the simplest way to do it for an MVP. The next step is to allow you to change the weights for each project. For example, the weights for every project will start out at 1x. You could then manually go through the dependencies found and change the weights to whatever you'd like...0x, 1.5x, 2x, 4x. The weights will determine how the split is performed. As the project progresses I might be able to find even more automatic and fair says to determine payouts

**Comment by MaxGraey** [comment]
https://blog.npmjs.org/post/187382017885/supporting-open-source-maintainers

**Comment by lastmjs** [comment]
Ya...I saw that. That's probably going to be amazing
