### ISSUE TITLE
Binaryen assertion fails

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#802]
```
> as-nes-olc@0.0.1-alpha asbuild:untouched C:\Users\Joshua Tenner\projects\as-nes
> asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug

Assertion failed: false, at: binaryen/src/wasm/wasm.cpp,928,getGlobal
Assertion failed: false, at: binaryen/src/wasm/wasm.cpp,928,getGlobal

...

TypeError: Cannot read property 'replace' of undefined
    at defaultCallback (C:\Users\Joshua Tenner\projects\as-nes\node_modules\assemblyscript\cli\asc.js:170:65)
    at Object.main (C:\Users\Joshua Tenner\projects\as-nes\node_modules\assemblyscript\cli\asc.js:594:12)
    at Object.<anonymous> (C:\Users\Joshua Tenner\projects\as-nes\node_modules\assemblyscript\bin\asc:21:26)
```

There's lots of other un-useful stuff that binaryen spits out. Looks like fun, and totally out of my expertise.

**Comment by jtenner** [comment]
https://github.com/WebAssembly/binaryen/blob/master/src/wasm/wasm.cpp#L994

Looks like the problem is here in this function.

**Comment by dcodeIO** [comment]
Can you try to create a reduced repro so I can investigate? If your assumption on the origin is correct, it looks like the compiler it attempting to obtain a global that does not exist, by name.

**Comment by jtenner** [comment]
https://github.com/jtenner/as-nes-olc/blob/master/assembly/index.ts

Hey good luck! It's a 6502 emulator. There's lots of functions here too. I'll try to help isolate it too.

**Comment by jtenner** [comment]
Ah yes.

It looks like the long list of opcode references are what is causing the issue.

So to reproduce:

```ts
let global = [(255 references...)];
```
