### ISSUE TITLE
Referencing arrays in JS

### ISSUE THREAD

**Issue by CarstenHoyer** [AssemblyScript/assemblyscript#804]
I have looked at:
https://github.com/AssemblyScript/assemblyscript/issues/105
https://github.com/AssemblyScript/assemblyscript/issues/263
https://github.com/WebAssembly/design/issues/1231

But I _cannot_ make this thing work as I expect it to.

Given the below code, I would expect the console.logs to output [**1**, 2, 3, 4), [**100,** 2, 3, 4) then [**200,** 2, 3, 4). But what I see is [**1**, 2, 3, 4), [**100**, 2, 3, 4) then [**100**, 2, 3, 4). That indicates that my processF32Array is wrong. I tried different ideas, but none of them seems to reflect any changes on the JS side.

I could use a little help.

JS
```
const module = await loader.instantiateStreaming(fetch("untouched.wasm"), myImports);
const { processF32Array } = module
const myArray = [1,2,3,4];
const myArrayId = module.__retain(module.__allocArray(module.FLOAT32ARRAY_ID, myArray))

const myArrayView = module.__getArrayView(myArrayId);
console.log(myArrayView)

myArrayView[0] = 100;
console.log(myArrayView)

processF32Array(myArrayId);
console.log(myArrayView)
```

WASM:
```
export const FLOAT32ARRAY_ID = idof<Float32Array>()

export function processF32Array(ptr: i32): void {
  const val: f32 = 200
  store<f32>((ptr) << 2, val)
}

**Comment by MaxGraey** [comment]
Try this one:
```ts
export function processF32Array(ptr: i32): void {
  const val: f32 = 200
  store<f32>(ptr + (0 << 2), val)
}
```

**Comment by CarstenHoyer** [comment]
Thanks. Tried it. It stays the same [100, 2, 3, 4].

**Comment by CarstenHoyer** [comment]
Actually, if i make a slight change, I can see the array values get reset, so that indicates that it is not the same array I am working on in JS/WASM.

JS:
```
 const module = await loader.instantiateStreaming(fetch("untouched.wasm"), myImports);
    const { processF32Array } = module
    const myArray = [1,2,3,4];
    const myArrayId = module.__retain(module.__allocArray(module.FLOAT32ARRAY_ID, myArray))
    **let myArrayView = module.__getArrayView(myArrayId);**
    console.log(myArrayView)
    myArrayView[0] = 100;
    console.log(myArrayView)
    processF32Array(myArrayId);
    **myArrayView = module.__getArrayView(myArrayId);**
    console.log(myArrayView)
```
Logs:
Float32Array(4) [1, 2, 3, 4]
Float32Array(4) [100, 2, 3, 4]
Float32Array(4) [1, 2, 3, 4]

**Comment by MaxGraey** [comment]
You should invalidate your `myArrayView` after `processF32Array`. It could be done via calling `myArrayView = module.__getArrayView(myArrayId)` again after `processF32Array`

**Comment by CarstenHoyer** [comment]
Ah, exactly what I just tried above :)

**Comment by CarstenHoyer** [comment]
I wonder if this is the part i misunderstood?

WASM
```
export const FLOAT32ARRAY_ID = idof<Float32Array>()

**Comment by CarstenHoyer** [comment]
No that part looks correct.

**Comment by CarstenHoyer** [comment]
I am not getting any kind of updates. Below I would expect the console.log to be [200]

JS
```
const myImports = {
      env: {
        abort(_msg, _file, line, column) {
          console.error("abort called at main.ts:" + line + ":" + column);
        },
        memory: new WebAssembly.Memory({ initial: 256 })
      },
      imports: { }
    }

    const module = await loader.instantiateStreaming(fetch("optimized.wasm"), myImports);
    const { processF32Array } = module
    const arr = new Float32Array([1]);
    const id = module.__retain(module.__allocArray(module.FLOAT32ARRAY_ID, arr))
    
    processF32Array(id);
    const arr1 = module.__getArray(id)
    console.log(arr1)
```

WASM
```
export function processF32Array(ptr: i32): void {
  const val: f32 = 200
  store<f32>(ptr + (0 << 2), val)
}

SCRIPT
```
asc assembly/index.ts -b build/optimized.wasm -t build/optimized.wat -d build/optimized.d.ts --use Math=JSMath --runtime full -O3 --importMemory --sourceMap --validate --measure

**Comment by CarstenHoyer** [comment]
On the WASM side, it looks like I can do this:

WASM
```
export function processF32Array(arr: Float32Array): void {
  arr[0] = 200
}
```

Now to figure out what to do on the JS side.

**Comment by MaxGraey** [comment]
Yeah, I forgot, you can't access direct to typed array by pointer, it has backing buffer, so you should use:
```ts
export function processF32Array(arr: Float32Array, val: f32): void {
  var index = 0;
  store<f32>(arr.dataStart + (index << alignof<f32>), val);
}
```

**Comment by MaxGraey** [comment]
I guess before doing such low level things better read this part of [documentation](https://docs.assemblyscript.org/details/memory#arraybufferview-layout). Hope this help you
