### ISSUE TITLE
How to intialize v128 with TypedArray Data?

### ISSUE THREAD

**Issue by zamadatix** [AssemblyScript/assemblyscript#805]
It seems all of the v128 initializers require compile time constants but I'm trying to use SIMD on existing data in a TypedArray, how do I go about this? The only other option seems to be v128.load() but that  requires a memory offset and I'm not sure how to get a pointer to an existing TypedArray.

**Comment by jtenner** [comment]
```ts
let dataStart = typedArray.dataStart;
let dataLength = typedArray.dataLength;
```

These two properties should be helpful :).

**Comment by zamadatix** [comment]
That seems to work, thanks :D. Is there a reason this is not in https://docs.assemblyscript.org/standard-library/typedarray? Oddly enough it doesn't show up in my autocomplete hints either.

**Comment by MaxGraey** [comment]
`dataStart` and `dataLength` are private fields and using usually for internal proposes or when you do some unsafe stuffs. See similar issue #743
