### ISSUE TITLE
SIMD Code Not Generating the Same Output as SISD Code

### ISSUE THREAD

**Issue by zamadatix** [AssemblyScript/assemblyscript#811]
Forewarning: This is more likely something I've overlooked about SIMD than an issue with AS but I've spent about 12 hours poking at why it's different to no avail so it's likely outside of my expertise to be certain :).

I have an assemblyScript function which generates a mandelbrot output with 1/4 horizontal scaling (to make comparing to f32x4 code easier) and it generates an appropriate image: 
![image](https://user-images.githubusercontent.com/343550/64129029-8c526580-cd87-11e9-8357-df476b77b8dd.png)

While trying to port this function to a SIMD version I ran into some issues. As written now it should emulate the 1/4 horizontal scaling of the SISD version because it only looks at the first lane. Unfortunately this is the image it generates: 
![image](https://user-images.githubusercontent.com/343550/64129022-7fce0d00-cd87-11e9-8d31-8306ada4c56f.png)

SISD:
```
export function computeMandelbrot(top: f32, right: f32, bottom: f32, left: f32, maxIterations: f32): u32
{
	const canvasArea: f32        = canvasWidth * canvasHeight;
	const floatCanvasWidth: f32  = canvasWidth;
	const floatCanvasHeight: f32 = canvasHeight;
	const rSquareMax: f32        = 4.0;
	const xWidth: f32            = right - left;
	const yHeight: f32           = top - bottom;

	for(let index: f32 = 0.0; index < canvasArea; index += 4.0)
	{
		const xIndex: f32 = index % canvasWidth;
		const yIndex: f32 = index / canvasWidth;

		let xCoordinate: f32 = (xIndex / floatCanvasWidth)  * xWidth + left;
		let yCoordinate: f32 = (yIndex / floatCanvasHeight) * yHeight + bottom;

		let iteration: f32 = 0.0;
		let x: f32         = 0.0;
		let y: f32         = 0.0;
		let rSquare: f32   = 0.0;
		let iSquare: f32   = 0.0;
		let zSquare: f32   = 0.0;

		while(((rSquare + iSquare) < rSquareMax) && (iteration < maxIterations))
		{
			x = rSquare - iSquare + xCoordinate;
			y = zSquare - rSquare - iSquare + yCoordinate;

			rSquare = x * x;
			iSquare = y * y;
			zSquare = (x + y) * (x + y);

			iteration++;
		}

		const color: u8 = <u8>(sqrt(iteration / maxIterations) * 255.0);
		const offset: u32 = <u32>index * 4;

		memory.fill(pixelData.dataStart + offset + 0,  color, 3);
		memory.fill(pixelData.dataStart + offset + 4,  color, 3);
		memory.fill(pixelData.dataStart + offset + 8,  color, 3);
		memory.fill(pixelData.dataStart + offset + 12, color, 3);
	}

	return pixelData.dataStart;
}
```

SIMD:
```
export function computeMandelbrotSimd(top: f32, right: f32, bottom: f32, left: f32, maxIterations: f32): u32
{
	const canvasArea: f32        = canvasWidth * canvasHeight;
	const floatCanvasWidth: f32  = <f32>canvasWidth;
	const floatCanvasHeight: f32 = <f32>canvasHeight;
	const rSquareMaxSimd: v128   = v128.splat<f32>(4.0);
	const xWidth: f32            = right - left;
	const yHeight: f32           = top - bottom;

	for(let index: f32 = 0.0; index < canvasArea; index += 4.0)
	{
		const xIndex: f32 = index % canvasWidth;
		const yIndex: f32 = index / canvasWidth;

		let xCoordinateSimd: v128 = v128.splat<f32>(0.0);
		xCoordinateSimd = v128.replace_lane<f32>(xCoordinateSimd, 0, ((xIndex + 0.0) / floatCanvasWidth)  * xWidth + left);
		xCoordinateSimd = v128.replace_lane<f32>(xCoordinateSimd, 1, ((xIndex + 1.0) / floatCanvasWidth)  * xWidth + left);
		xCoordinateSimd = v128.replace_lane<f32>(xCoordinateSimd, 2, ((xIndex + 2.0) / floatCanvasWidth)  * xWidth + left);
		xCoordinateSimd = v128.replace_lane<f32>(xCoordinateSimd, 3, ((xIndex + 3.0) / floatCanvasWidth)  * xWidth + left);

		let yCoordinateSimd: v128 = v128.splat<f32>(0.0);
		yCoordinateSimd = v128.replace_lane<f32>(yCoordinateSimd, 0, ((yIndex + 0.0) / floatCanvasHeight) * yHeight + bottom);
		yCoordinateSimd = v128.replace_lane<f32>(yCoordinateSimd, 1, ((yIndex + 1.0) / floatCanvasHeight) * yHeight + bottom);
		yCoordinateSimd = v128.replace_lane<f32>(yCoordinateSimd, 2, ((yIndex + 2.0) / floatCanvasHeight) * yHeight + bottom);
		yCoordinateSimd = v128.replace_lane<f32>(yCoordinateSimd, 3, ((yIndex + 3.0) / floatCanvasHeight) * yHeight + bottom);

		let iteration: f32    = 0.0;
		let xSimd: v128       = v128.splat<f32>(0.0);
		let ySimd: v128       = v128.splat<f32>(0.0);
		let rSquareSimd: v128 = v128.splat<f32>(0.0);
		let iSquareSimd: v128 = v128.splat<f32>(0.0);
		let zSquareSimd: v128 = v128.splat<f32>(0.0);

		//while((v128.all_true<u32>(v128.le<f32>(v128.add<f32>(rSquareSimd, iSquareSimd), rSquareMaxSimd))) && (iteration < maxIterations))
		while(((v128.extract_lane<f32>(rSquareSimd, 0) + v128.extract_lane<f32>(iSquareSimd, 0)) < v128.extract_lane<f32>(rSquareMaxSimd, 0)) && (iteration < maxIterations))
		{
			xSimd = v128.add<f32>(v128.sub<f32>(rSquareSimd, iSquareSimd), xCoordinateSimd);
			ySimd = v128.add<f32>(v128.sub<f32>(zSquareSimd, v128.sub<f32>(rSquareSimd, iSquareSimd)), yCoordinateSimd);

			rSquareSimd = v128.mul<f32>(xSimd, xSimd);
			iSquareSimd = v128.mul<f32>(ySimd, ySimd);
			zSquareSimd = v128.mul<f32>(v128.add<f32>(xSimd, ySimd), v128.add<f32>(xSimd, ySimd));

			iteration++;
		}

		const color: u8 = <u8>(sqrt(iteration / maxIterations) * 255.0);
		const offset: u32 = <u32>index * 4;

		memory.fill(pixelData.dataStart + offset + 0,  color, 3);
		memory.fill(pixelData.dataStart + offset + 4,  color, 3);
		memory.fill(pixelData.dataStart + offset + 8,  color, 3);
		memory.fill(pixelData.dataStart + offset + 12, color, 3);
	}

	return pixelData.dataStart;
}
```

**Comment by MaxGraey** [comment]
Last time as I triy wasm's SIMD in Node nightly many instructions was broken.
Also one perf hint. Instead:
```ts
const color: u8 = <u8>(sqrt(iteration / maxIterations) * 255.0);
memory.fill(pixelData.dataStart + offset + 0,  color, 3);
...
```
You could write
```ts
// move 1.0 / maxIterations out of loop
let invMaxIters: f32 = 1.0 / maxIterations;
...
   const gray: u32 = ((sqrt(iteration / maxIterations) * 255.0) as u32) & 0xFF;
   const color = 0xFF000000 | (gray * 0x00101010); // 0x00_00_00_GG -> 0xFF_GG_GG_GG
   const outPtr = pixelData.dataStart + offset << 2;
   store<u32>(outPtr, color, 0 << 2);
   store<u32>(outPtr, color, 1 << 2);
   store<u32>(outPtr, color, 2 << 2);
   store<u32>(outPtr, color, 3 << 2);
```
or try use `v128.store`. But I'm not sure it works

**Comment by MaxGraey** [comment]
Also this approach is really slow:
```ts
for (let index: f32 = 0.0; index < canvasArea; index += 4.0) {
   const xIndex: f32 = index % canvasWidth;
   const yIndex: f32 = index / canvasWidth;
   ...
}
```
float point modulus `index % canvasWidth` forcing call this pretty [complicated function](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/math.ts#L2515). Better do all this stuff in integer arithmetics.

**Comment by zamadatix** [comment]
Thanks for the quad pixel bit twiddling code, I had yet to write that :).

On the index `index % canvasWidth` thing those being f32s was actually an optimazition I made from when they were u32s. I haven't figured out quite "why" yet but changing index and the associated canvas[Height,Width,Area] constants from f32 back to u32 results in the function taking over twice as long (~110ms vs ~230ms) to execute in Chrome and Chrome Canary even though the only thing they are used for (in the entire program) is to compute xIndex and yIndex. I'll probably have to dig into the generated WAT at some point and see what's really going on. That or there is something really weird going on in V8.

I'll keep this one on the backburner and see if updates to V8 result in a change in output. Thanks for taking a look :)

**Comment by MaxGraey** [comment]
> constants from f32 back to u32 results in the function taking over twice as long (~110ms vs ~230ms)

That's strange. Did you try using 2d loop instead one loop?

```ts
// canvasHeight and canvasWidth should be `i32`

let xScale: f32 = xWidth / floatCanvasWidth;
let yScale: f32 = yHeight / floatCanvasHeight;

for (let yIndex = 0; yIndex < canvasHeight; yIndex++) {
  let stride = yIndex * canvasWidth;
  for (let xIndex = 0; xIndex < canvasWidth; xIndex++) {
   let xCoordinate: f32 = <f32>xIndex * xScale + left;
   let yCoordinate: f32 = <f32>yIndex * yScale + bottom;

   ...

   let offset = stride + xIndex;
   const outPtr = pixelData.dataStart + (offset << 2);

   ...

   // store pixel
  }
}
```
I don't think it should be slower existing approach

**Comment by MaxGraey** [comment]
I just created fiddle with demonstration and bench: https://webassembly.studio/?f=qt90fhvvhcj

Results in Chrome 77.0.3865.56:
```
inner loop + int indexes: 1.806884765625ms
one loop + float indexes: 21.871826171875ms
```
As you can see "one loop + float indexes" on 12 times slower than 2 loops (inner / outer) with integers

**Comment by zamadatix** [comment]
Neat site. I ported a simple example, when you hit run it will time both functions and log the results in the console. https://webassembly.studio/?f=i9542v1shsg

|     | Chrome 76 | Chrome 78 | Firefox 68 |
|:---:|:---------:|:---------:|:----------:|
| u32 |  3898 ms  |  3932 ms  |   1894 ms  |
| f32 |  1737 ms  |  1752 ms  |   1893 ms  |

I also extracted the WAT for each (with blank lines added to match up each in a side-by-side compare):
- https://pastebin.com/raw/ZSuC50v2
- https://pastebin.com/raw/w79eVfMp

FF showing roughly the same time is what I'd expect in this case as % only gets called ~1.5 million times while the inner loop runs billions of times so the overall result is pretty unaffected.

Between FF's results and looking at the WAT I'd say the weird timing it's something weird going on in Chrome/V8 and the SIMD difference is probably WASM SIMD not being GA yet.

**Comment by MaxGraey** [comment]
I'm wondering why you still use one loop with division and modulo instead two loops without index separation?=) Your `f32` and `u32` versions use modulo which slow in any case. When you use `u32` integer division also much slower than float point division that's why your `f32` version faster but both version are pretty slow compare to this:
```ts
for (let yIndex = 0; yIndex < canvasHeight; yIndex++) {
    let stride = yIndex * canvasWidth;

    for (let xIndex = 0; xIndex < canvasWidth; xIndex++) {
      let xCoordinate: f32 = <f32>xIndex * xScale + left;
      let yCoordinate: f32 = <f32>yIndex * yScale + bottom;
      ...
    }
  }
```

**Comment by zamadatix** [comment]
If u32 division were actually a cause of slowness the Firefox results wouldn't be within 1 ms of each other. Modulo isn't that bad in u32 land really, i32.rem_u will actually translate to a standard DIV instruction on x86 as that also generates the remained. Overall the two probably represent 20 ms total work on something that took 3,900 ms to run, my guess is it's something about the actual type conversion tripping up some assumption the VM made/can no longer make. I'll probably poke around with it for a while until I figure out exactly what so I can avoid triggering it in other cases.

As for the loops 2 loops would be faster. It might even be faster in the SIMD code but it'd need a branch inside the inner for to handle cases where width wasn't a multiple of 4. Might eat away at some of the gains but it's probably still faster than single loop.

**Comment by MaxGraey** [comment]
For SIMD you need just one additional inner loop:
```ts
let i: i32, j: i32;
for (j = 0; j < height; j++) {
  for (i = 0; i < width; i += 4) {
    // use SIMD code
  }
  for (; i < width; i++) {
   // use scalar code for remind data
  }
}
```

**Comment by dcodeIO** [comment]
Could also do `if (ASC_FEATURE_SIMD) { ... simd .. } else { ... normal ... }` to have both in one file :)
