### ISSUE TITLE
An orphaned increment has occured at block: 3223

### ISSUE THREAD

**Issue by lcoenen** [AssemblyScript/assemblyscript#820]
Hi!

I like Assemblyscript and I would like to re-write the core of my Koos project (http://koos.network). 

But it's really difficult to do without testing. I am trying this dummy code (https://gist.github.com/lcoenen/dae8c9d890ba7dae8eb55a5d84509845), but I get the error indicated in the gist.

It seems similar to #668 and #696, but I couldn't find a solution in those issues.

Here are the version I'm using: 
```
  "devDependencies": {
    "@as-pect/assembly": "^2.3.1",
    "@as-pect/cli": "^2.3.1",
    "@as-pect/core": "^2.3.1",
    "husky": "^3.0.4",
    "assemblyscript": "github:assemblyscript/assemblyscript",
    "assemblyscript-json": "github:fluencelabs/assemblyscript-json#update-as1",
    "assemblyscript-sdk": "github:fluencelabs/assemblyscript-sdk"
  },
```

**Comment by lcoenen** [comment]
Just replacing the constructor by 

```
export class Message<T> {
	public action: string;
	public payload: T;

  constructor(action: string, payload: T) { 
		this.action = action;
		this.payload = payload;
	};
}
``` did the trick. 

So I can keep on working, just thought I would let you know :)

**Comment by MaxGraey** [comment]
this issue should be fixed [here](https://github.com/AssemblyScript/assemblyscript/commit/25b92769119389c581977da12b5147d1449043db)

**Comment by dcodeIO** [comment]
Did you verify that the `"assemblyscript": "github:assemblyscript/assemblyscript"` is updated to current master?

**Comment by lcoenen** [comment]
@dcodeIO I did, I purged `node_modules` and re-installed everything right before the test.

**Comment by MaxGraey** [comment]
Are you use `as-pect`? Did you update `as-pect` to latest version? Becouse before some version it have own assemblyscript dependency

**Comment by MaxGraey** [comment]
Make sure you have `2.4.1` instead `2.3.1`
