### ISSUE TITLE
Callback function needs name gotcha

### ISSUE THREAD

**Issue by lcoenen** [AssemblyScript/assemblyscript#822]
Hi!

Thanks for your work, guys! I like playing with Assemblyscript and they're using it in [fluence](fluence.network), which is a great project.

Just a little gotcha I noticed - I tried to use a callback function like that:

```
/*
 *
 * This will call the translate function until it gets
 * an answer or an error
 *
 */
export function engine(input: string, query: (string) => string): string {
  return 'to be implemented';
}
```

but had the following error:

```
ERROR AS200: Conversion from type '(theQuery: ~lib/string/String) => ~lib/string/String' to '() => ~lib/string/String' requires an explicit cast.

     let answer: string = engine('incoming message', query);
                                                   ~~~~~
 in assembly/__tests__/main.spec.ts(91,50)
```

albeit it is valid Typescript. 

I had to explicitly indicate an arg name for it to work:

```
export function engine(input: string, query: (queryStr: string) => string): string {
  return 'to be implemented';
}
```

**Comment by MaxGraey** [comment]
```ts
function engine(input: string, query: (string) => string): string {
```
This not valid TypeScript and IDE / TS diagnostics should inform about it. See [typescriptlang playground](http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABAUzAcxmZB1ATgtACkwAcQoAuRAZyl0zQBpEBHEZXATysNvvQCUiALwA+GnQYCqfBogDeAKEQrEuZFBC4kAIh0BuRQF9Fi0JFgIU6TMgBKMNAAsoxMGUoT+TVuy482Dk4AZToZSUERcVlBcO8FZVV1TW1EPUMjIA)

**Comment by dcodeIO** [comment]
Should actually be valid TypeScript, but for a different reason. What TS infers there is a `(string: any) => string`, with `string` being the name of the variable, not the type. What happens there is that upon `(string)` the parser still isn't sure whether it is dealing with a parenthesized type or a function type, hence not emitting any diagnostics. That diagnostic needs a fix, but the omitting the type won't work still.
