### ISSUE TITLE
WebAssembly Studio is broken

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#827]
Currently the compiler fails to load because of the following:

```
ReferenceError: _BinaryenSIMDBitselectId is not defined
```

**Comment by dcodeIO** [comment]
Relevant Binaryen commit: https://github.com/WebAssembly/binaryen/commit/0faa68b9dfbe478c6d238a5c55ac61b54a86a3c3#diff-9c51a544919e7650d4fd54cdb78ffbb4R226

**Comment by dcodeIO** [comment]
Should be working again!
