### ISSUE TITLE
Unions of References and TypedArrays

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#828]
The  following doesn't compile
```
class Foo {}
function fooOrUint8Array(foo: Foo | Uint8Array): void {}
```
with the following error:
```
ERROR TS1005: 'null' expected.

 function fooOrUint8Array(foo: Foo | Uint8Array): void {}
                                    ^
 in assembly/main.ts(27,35)
```

Since Uint8Array has a class id, shouldn't this work?

Since WebAssembly.studio is down here is an example with near's fork:

https://studio.nearprotocol.com/?f=1cg9abhe2

**Comment by dcodeIO** [comment]
Wondering a bit, since union types are not supported. What am I missing?

**Comment by willemneal** [comment]
> Instead of any, we can use a union type for the padding parameter:
```ts
/**
 * Takes a string and adds "padding" to the left.
 * If 'padding' is a string, then 'padding' is appended to the left side.
 * If 'padding' is a number, then that number of spaces is added to the left side.
 */
function padLeft(value: string, padding: string | number) {
    // ...
}

let indentedString = padLeft("Hello world", true); // errors during compilation
```

> [A union type describes a value that can be one of several types. We use the vertical bar (|) to separate each type, so number | string | boolean is the type of a value that can be a number, a string, or a boolean.](https://www.typescriptlang.org/docs/handbook/advanced-types.html#union-types)

Were you thinking intersection types?

**Comment by DanielRX** [comment]
@willemneal that's typescript, not assemblyscript? Assembly script doesn't support unions as far as I've seen and tried?

**Comment by willemneal** [comment]
Ah yeah I had forgotten.  Had seen a lot of `| null` like this: https://webassembly.studio/?f=yaok3afximh

And had forgotten.  I managed to get around with generics like this: https://webassembly.studio/?f=nw6ffxidsvr

Perhaps we can add this to the discussion of #816 since with better type resolution this should be possible.

**Comment by trusktr** [comment]
Aren't issues like these good to keep open? I wonder if perhaps Google and other search engines might de-prioritize closed issues. Also searching for open issues (the default) won't show results. I may have then not created #1548 if I had ran into this one first. I thought I searched thoroughly before posting.

**Comment by dcodeIO** [comment]
To anyone coming here for a status update, a more detailed [overview of the current status](https://www.assemblyscript.org/status.html) has meanwhile been added to the AS website. No updates on support for union types so far, though.
