### ISSUE TITLE
How does AssemblyScript compares to Walt?

### ISSUE THREAD

**Issue by emil14** [AssemblyScript/assemblyscript#83]
Hello! And thank you for this great project. I'm asking you about https://github.com/ballercat/walt

Don't sure which one should I take, could you please explain the core difference?

**Comment by MaxGraey** [comment]
Hello @emil14,
walt it seems just syntax sugar over `wat` which has main goal translate to wasm close as possible if I right understood owner: https://github.com/ballercat/walt/issues/11

Main differences:
1) **AssemblyScript** born earlier. Just see first [prototype](https://github.com/AssemblyScript/prototype).
2) AS is a typescript superset and easily transpiled to javascript via `tsc`. `walt` has syntax similar to `flow` but it seems not compatible and I'm not sure has possibility translation to pure js.
3) AS has runtime: `Array`, `ArrayBuffer`, typed arrays, `String`, `Map/Set` and etc. `walt` has very basic stuffs for strings and arrays.
4) AS has memory management. Actually tree types for heap allocations: `arena`, `tlsf` and `buddy`. Also there is working on Garbage Collector. `walt` hasn't provide any memory management.
5) AS has many examples and benchmark. Also one [huge and successful project called wasmBoy](https://github.com/torch2424/wasmBoy).
6) AS supported by several playgrounds: [WebAssembly Studio](https://webassembly.studio/) and [Assembleash](https://maxgraey.github.io/Assembleash/#AssemblyScript).
7) AS build over `binaryen` which provide fast code generation and very smart optimization with many passes from author of emscripten. `walt` hasn't provide accurate build-in optimizations even [Dead code elimination](https://github.com/ballercat/walt/issues/63).

**Comment by torch2424** [comment]
Oh hey, thanks for mentioning wasmBoy @MaxGraey  😄

**Comment by emil14** [comment]
Thank you. It seems like the `AssemblyScript` is better for building complex applications
