### ISSUE TITLE
Potentially eliminating the case of ===

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#856]
It has been suggested various times to align the use of the `===` operator to what JS/TS would do, which came also up again in a recent issue (I don't remember which one), suggesting to replace our special `===` semantics with `changetype<usize>(a) == changetype<usize>(b)` in standard library code, which is about the only place where this is of importance. Overall this change would make `===` and `==` behave exactly the same for string operands and drop the special meaning of `someObject === someObject`, replacing it with something else where necessary.

Considering the general confusion introduced by this, I am leaning towards this solution. Thoughts?

**Comment by dcodeIO** [comment]
This turns out to be a bigger feat than expected. Because `a === null` compiled down to an `i32.eq(a, 0)` that was precomputable by Binaryen, but a `A#__eq(0)` isn't anymore, leading to all sorts of issues that must be solved first. Take for example

```ts
function test(): string {
  if (a !== null) return a; // now results in an "is possibly null" error
  return "";
}
```

This a more general issue under the hood that we already have with anything that implements custom `==` / `!=` overloads, but now surfaces due to applying it to strings in all cases.

**Comment by dcodeIO** [comment]
The easiest solution seems to be to do the identity check as an additional one to overloads that one can't override, looking somewhat like

```ts
// equality
i32.eq(a, b) ? true : A#__eq(a, b)

// inequality
i32.ne(a, b) ? true : A#__ne(a, b)
```

but that will limit what the overloads can do in the identity-equal case and introduces a branch.

**Comment by dcodeIO** [comment]
Currently thinking about moving null checking to the type system, adding a third reference type variant `alwaysNull` to the existing `nullable` and `nonNullable` variants, with the implication that flows then need a way to remember the "actual" type of locals in addition to the declared type at any given point.

**Comment by mbrowne** [comment]
Why not just introduce a new operator? I think this would avoid the confusion and probably be easier to implement too. For example:

```
if (a is b)
```

There could also be a negative form:

```
if (a isnt b)
```

...although of course that would be for convenience/readability, since `if (!(a is b))` would do the same thing.

**Comment by mbrowne** [comment]
...When I wrote the above, I forgot about the fact that `is` is already an operator in TypeScript (used just in types, not actual executable code). But although this could potentially introduce a new confusion, I think it would be less than the confusion of repurposing `===`. Or of course you could also invent some other operator, e.g. `isSame`.

**Comment by cyberixae** [comment]
I'm expecting my AssemblyScript code to compile as TypeScript and produce a JavaScript program that works as a drop in replacement for the WebAssembly module. Both modules should ( eventually ) support loading with `import` and be 100% compatible so that A/B testing of TypeScript/AssemblyScript modules becomes trivial. I think such interoperability is more important than any convenience feature.
