### ISSUE TITLE
Allocated TypedArrays lose backing buffer after creation

### ISSUE THREAD

**Issue by michaeltheory** [AssemblyScript/assemblyscript#859]
I'm allocating various buffers that store data for objects in a 3D engine such as geometry attributes and vectors. I'm finding that after creation, some of them (seems to be the earliest created) lose their backing buffer and their length becomes 0.

GC shouldn't be an issue because I've both used `__retain` and these objects still have multiple references in JS.

I'm creating them with this
```
window.createTypedArray = function(type, val) {
        let ptr = _wasm.lib.__retain(_wasm.lib.__allocArray(_wasm.lib[`${type}_ID`], val));
        let array = _wasm.lib[`__get${type}`](ptr);
        _map[ptr] = {array, val};
        return array;
    };
```

and storing them in `_map` just so I can inspect the state, and almost immediately this happens:
![Screen Shot 2019-09-21 at 4 11 45 PM](https://user-images.githubusercontent.com/29176992/65380188-0ab96d80-dc8b-11e9-9b0c-ad2380ad29f9.png)

I've tried increasing `--memoryBase` but that doesn't seem to help this particular problem.

**Comment by dcodeIO** [comment]
I assume what's happening there is that the module's memory grows automatically, leaving the memory's previous buffer in a detached state, in turn invalidating all views on it. This is quite an unfortunate mechanism with no great workarounds currently. What might help though is to allocate a large chunk of memory upfront so memory grows (and doesn't have to anymore), and free it again immediately:

```ts
__free(__alloc(63*1024*1024, 0));
```

**Comment by michaeltheory** [comment]
Thanks for responding so quickly, the free/alloc solution worked so I can continue with my project.

I will look into the other solution 👍
