### ISSUE TITLE
for array loop - RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by ranbuch** [AssemblyScript/assemblyscript#860]
My `index.ts`:
```javascript
export function foo(data: Array<i32>): Array<i32> {
  for (let i = 0; i < 1; i++) {
    data[i];
  }
  return data;
}
```
compiles fine but throws a runtime error:
`RuntimeError: memory access out of bounds`

This code works fine:
```javascript
export function foo(data: Array<i32>): Array<i32> {
  for (let i = 0; i < 1; i++) {
  }
  return data;
}
```

I'm running it with this `javascript` code:
```javascript
let exportedInterface = module.instance.exports;
console.log(exportedInterface.foo([5]));
```

Obviously this code is doing nothing, I just want to understand how can I access an array cell.

BTW (probably related) the return value is `5` while the expected value is `[5]`. seems like `data` is the value of the first cell on the array instead of the array itself.

Any idea on how to pass an array as a parameter?

Thanks.

**Comment by MaxGraey** [comment]
You can't pass JS array to AS array directly. This WebAssembly limitation. You could use [loader](https://docs.assemblyscript.org/basics/loader)
```js
const loader = require("assemblyscript/lib/loader");
const myModule = await loader.instantiateStreaming(fetch("optimized.wasm"));
var arrPtr = myModule.__retain(myModule.__allocArray([5]));
var resPtr = myModule.foo(arrPtr);
var result = myModule.__getArray(resPtr);
console.log(result);
myModule.__release(arrPtr);
```

**Comment by ranbuch** [comment]
@MaxGraey your code doesn't run well:
```javascript
if ((id >>>= 0) >= count) throw Error("invalid id: " + id);
```
while `id` = `[5]`.

I've tried this:
```javascript
var arrPtr = myModule.__retain(myModule.__allocArray([5, 4, 6, 3]));
```
but this one is throwing here:
```javascript
if (!(info & (ARRAYBUFFERVIEW | ARRAY))) throw Error("not an array: " + id + " @ " + info);
```
`Error: not an array: 5,4,6,3 @ 16`

My realworld usage will be `Uint8ClampedArray` from `ctx.getImageData().data`, will it work?
Do you have any example with images and pixels manipulations or something like that?

Thank you!

**Comment by dcodeIO** [comment]
`__allocArray` expects the runtime id of the kind of array to allocate, like so:

```ts
// wasm
export const Uint8ClampedArray_ID = idof<Uint8ClampedArray>();
```

```ts
// js
var arrPtr = myModule.__retain(myModule.__allocArray(myModule.Uint8ClampedArray_ID, [5]));
...;
```

**Comment by MaxGraey** [comment]
yes. First argument should be `id`.

**Comment by ranbuch** [comment]
Can you maybe share a link to an example with transferring a param and getting the answer back. The [loader](https://github.com/AssemblyScript/assemblyscript/tree/master/lib/loader) documentation assumes I already know a great deal about `assemblyscript`.

I've tried to find reference to the type `WasmImports` on this repository but turns out it's not an existing interface but it just stands for `any`?

I couldn't find an example that uses the `loader` on this repository `examples` folder.
