### ISSUE TITLE
Transform example

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [AssemblyScript/assemblyscript#868]
Looking for transform examples, would appreciate some :-)

**Comment by dcodeIO** [comment]
There are no specific transform examples yet, but this is how it works: The `afterParse` hook of the transform specified with `--transform` is called with the [Parser](https://github.com/AssemblyScript/assemblyscript/blob/master/src/parser.ts#L93) instance when parsing has finished, containing the (yet uninitialized) [Program](https://github.com/AssemblyScript/assemblyscript/blob/master/src/parser.ts#L96) instance that has [an array](https://github.com/AssemblyScript/assemblyscript/blob/master/src/program.ts#L377) of the parsed [Sources](https://github.com/AssemblyScript/assemblyscript/blob/master/src/ast.ts#L1614), with each source node containing its respective [AST](https://github.com/AssemblyScript/assemblyscript/blob/master/src/ast.ts). At this stage, the AST can be traversed and possibly modified, for example by looking for custom decorators that trigger injection of additional code.

**Comment by DanielMazurkiewicz** [comment]
@dcodeIO I think that is already helpful - thank you!

**Comment by MaxGraey** [comment]
You could see [this example](https://github.com/holochain/hdk-assemblyscript/blob/master/transforms/zome_function.js) about usage transform function. But it pretty old and some part could be different for now

**Comment by willemneal** [comment]
@DanielMazurkiewicz This is also a good example: https://github.com/nearprotocol/assemblyscript/tree/master/bindings/src

It's used to add JSON serialization to objects and exported functions.
