### ISSUE TITLE
compiler tests are failing on master

### ISSUE THREAD

**Issue by JamesMilnerUK** [AssemblyScript/assemblyscript#876]
The current tests on `compiler` tests on master do not appear to be passing and are halting on various steps of the testing suite.

**Steps to reproduce**

```
git clone git@github.com:AssemblyScript/assemblyscript.git
cd assemblyscript
npm install
npm run test:compiler
```

**Expected result:**

Tests pass in a reasonable amount of time when running `npm run test` and `npm run test:compiler`.

**Current behaviour**

Various tests fail and blocking for exceptionally long periods of time (1-2 min+).

**Comment by dcodeIO** [comment]
This is normal when there have been changes recently with dist files not being updated yet, but is usually not a problem. The expected procedure to run the compiler tests when using a development install is

```ts
npm run clean
npm run test:compiler
```

See also: https://github.com/AssemblyScript/assemblyscript#instructions

Regarding the blocking behavior, that's the diff algorithm taking forever to evaluate fixture changes. Where necessary, this can be skipped with `npm run test:compiler -- --noDiff`.

**Comment by JamesMilnerUK** [comment]
@dcodeIO thanks for taking the time to point that out. Running `npm run clean` got everything back on track.
