### ISSUE TITLE
AST Node RETURN (kind 40) has wrong text range

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [AssemblyScript/assemblyscript#878]
Calling toString returns just 1 character that represents last char of return expression

**Comment by dcodeIO** [comment]
Respective code location appears to be [here](https://github.com/AssemblyScript/assemblyscript/blob/master/src/parser.ts#L1020), affecting non-void return statements. The change might be as simple as `tn.range(expr.range.start, tn.pos)` when creating such a return node.
