### ISSUE TITLE
Parser identifies ~lib/rt/index-full as SourceKind.USER_ENTRY

### ISSUE THREAD

**Issue by sampaioletti** [AssemblyScript/assemblyscript#889]
While playing with the transform option I noticed the ~lib/rt/index-full source is recognized as SourceKind.USER_ENTRY as is my user generated entry file, I would have thought it would be SourceKind.LIBRARY

If that is the intended classification how would one determine the difference between a user file in this scenario

It is classified as such due to the following
```js
//taken from src/parser.ts:140
//path= ~lib/rt/index-full
path.indexOf(PATH_DELIMITER, LIBRARY_PREFIX.length) < 0 
//results in 7<0=false

```

https://github.com/AssemblyScript/assemblyscript/blob/024d9de925ade5e8c0d48d8e8910367282dfdf57/src/parser.ts#L134-L144

**Comment by dcodeIO** [comment]
This is intended behavior. One can think of this as linking two programs together on source level, based on two entries. What the compiler does there is to parse the runtime entry before the user entry where both can have their own module-level exports (which `LIBRARY` files can't have). Perhaps just `ENTRY` would be a better name to avoid confusion?

**Comment by sampaioletti** [comment]
ah...that does make sense, I assumed (in the context of trying to develop a transform) that was how i could find the users entry file. I had been folloiwng along with

https://github.com/holochain/hdk-assemblyscript/blob/7fd3f11e8180b3c9ce08a05c5cf32fff624c527a/transforms/zome_function.js#L26

and assumed this was the correct way to replace that call in the current api

The renames make sense to me, but I can close if its a non-issue since this is intended behavior

**Comment by willemneal** [comment]
@sampaioletti You should try out my PR: #866, it's in typescript, but it makes transforming much easier.  [Here's an example of using the transformer class for the binding code to Near Protocol's bindings](https://github.com/nearprotocol/near-bindgen-as).  It informed informed the PR  when trying to create a proper tooling setup for working externally on creating transformers.

@dcodeIO  I vote for adding another case.  I too had this issue when filter for user entry files how about `RUNTIME_ENTRY` or `STARTUP_ENTRY`?

**Comment by sampaioletti** [comment]
@willemneal That looks real cool I'll pull it down and give it a try, I think its great that its in TS...i'm not a a js guy so I only do it when i have to (:

I did manage to make a transform that did what i wanted to for my example at
https://github.com/sampaioletti/assemblyscript/tree/rem-allocate/examples/rem-allocate

but i can see the advantages of using your class thanks for the info!
