### ISSUE TITLE
Implement (more) sign extension instructions

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#893]
Current example with `-O3` and `--enable sign-extension`
```ts
export function add(a: i64, b: i16): i64 {
  return a + b;
}
```
produce:
```wat
  get_local $p1
  i32.const 16
  i32.shl
  i32.const 16
  i32.shr_s
  i64.extend_s/i32
  get_local $p0
  i64.add
```
which far from optimal and expected:
```wat
  get_local $p1
  i64.extend_s/i32
  i64.extend16_s
  get_local $p0
  i64.add
```

**Comment by dcodeIO** [comment]
Appears the only [cases](https://github.com/AssemblyScript/assemblyscript/blob/master/src/compiler.ts#L8868) where sign extension ops are used is i8 -> i32 and i16 -> i32 atm.

**Comment by MaxGraey** [comment]
I see. But using this feature for `i8 -> i64`, `i16 -> i64` even more useful given that for this much more operations. But this require some refactoring right?

**Comment by dcodeIO** [comment]
If I remember correctly the instructions `i64.extend8_s`, `i64.extend16_s` and `i64.extend32_s` operate on `i64` inputs, which isn't particularly useful in our case due to having to promote the i32 value to i64 first anyway leading to the same number of operations. Or am I missing something?

**Comment by MaxGraey** [comment]
Yes. So it could expose to 2 operations:
```wat
i64.extend_u/i32
i64.extend16_s
```
instead
```wat
i32.const 16
i32.shl
i32.const 16
i32.shr_s
i64.extend_s/i32
```

**Comment by dcodeIO** [comment]
I believe the second should currently become

```wat
i32.extend16_s
i64.extend_s/i32
```

with sign extension ops enabled, which only differs in extending before promoting instead of promoting before extending. Seems weird that it emits the shifts.

**Comment by MaxGraey** [comment]
Hmm. LLVM for example uses [first version](https://reviews.llvm.org/rL313101#change-HmyF4MXxIf5t). But I agree `i32.extend16_s + i64.extend_s/i32` also make sense. I wonder which is better optimized by VMs currently
