### ISSUE TITLE
continue in nested cycle cause wasm runtime crash

### ISSUE THREAD

**Issue by vird** [AssemblyScript/assemblyscript#897]
I've found really wierd code sample

    export class Struct {
      a : i32;
    }

    export function main():i32 {
      let res:i32 = 0;
      let arr:Struct[] = [];
      arr.push(new Struct());
      arr.push(new Struct());
      // setup UD
      let len = arr.length;
      for(let a_idx=0;a_idx<len;a_idx++) {
        let a = arr[a_idx];
        for(let b_idx=0;b_idx<len;b_idx++) {
          let b = arr[b_idx];
          if (a_idx >= 0) continue; // BUG
          res++;
        }
      }
      return res;
    }

Error report seems not useful

    Uncaught Error: abort:  at ~lib/rt/pure.ts:115:13
        at abort (1_as_loader.coffee:75)
        at :10001/wasm-function[25]:43
        at :10001/wasm-function[39]:79
        at :10001/wasm-function[40]:50
        at :10001/wasm-function[42]:66
        at :10001/wasm-function[25]:61
        at :10001/wasm-function[26]:13
        at :10001/wasm-function[37]:170
        at Object.wrap [as main] (1_as_loader.coffee:280)
        at <anonymous>:1:18

Here is problematic wat https://gist.github.com/vird/a467005edc2f54204785f76e4e2f23a8#file-as_bundle-wat-L4002 with specific line that cause a problem

in debugger
local#1: 2208
local#2: 2208

so program reach unreachable because it tires to release 2 times same pointer.
removing `continue; // BUG` fixes bug (even rewriting to equivalent code without continue)
Replacing Struct to i32 makes issue is not reproducable.

**Comment by MaxGraey** [comment]
It seems this similar issue which recently [fixed here](https://github.com/AssemblyScript/assemblyscript/pull/844)

cc @dcodeIO

**Comment by dcodeIO** [comment]
Issue seems to be that the `continue` performs the releases up all flows with the same continue label, while the outer `for` performs its own releases *after* the internal continue block, in turn leading to a duplicate release of the top-most vars.
