### ISSUE TITLE
Proposal. Improve "reinterpret<T1, T2>" signature.

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#9]
**Current declaration**
```ts
declare function reinterpret<T1 = i32 | i64 | f32 | f64, T2 = i32 | i64 | f32 | f64>(value: T1): T2;
```
**Usage**
```ts
var flt32: f32 = 1.0;
var Int = reinterpret<f32, i32>(flt32);
```

**Proposal declaration**
```ts
declare function reinterpret<D = i32 | i64 | f32 | f64, S = i32 | i64 | f32 | f64>(value: S): D;
```
**Proposal Usage**
```ts
var flt32: f32 = 1.0;
var Int = reinterpret<i32>(flt32); // Usual resolving "S" typename by compiler
```

**Reasons**
1. It's simper and less code.
2. It's clear and alignment to usual casts like ```var Int = <i32>(flt32)```. So it less painful refactoring.

PS Also needs verification for equality sizes of source and destination types

**Comment by dcodeIO** [comment]
Yeah, though about this as well. Though, I suspect that partially resolving just some type arguments isn't compatible with tsc? If this assumption is correct, a working type definition for tsc could be something in the lines of

```ts
declare function reinterpret<T = i32 | i64 | f32 | f64>(value: number): T:
```

Background: asc doesn't use the `.d.ts` files, these are merely there for tsc syntax compatibility and can use `number`. `asc` compiles such things manually in `builtins.ts`.
