### ISSUE TITLE
Is there a reason that this const float fraction isn't just a function?

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#902]
https://github.com/AssemblyScript/assemblyscript/blob/e5c1e0830f375c2d21fc739ea04bd53610252b09/std/assembly/map.ts#L18

The reason that I ask is that the near runtime prohibits using floating point numbers, but here and in set they are used.  I can make a PR to change this to a function, but I was just wondering if there was a reason to have the floats.

**Comment by MaxGraey** [comment]
I guess we easily could split `FILL_FACTOR` and `FREE_FACTOR` to integer pairs (fractions) and use its instead float multiplications. Will make PR for that
