### ISSUE TITLE
Error in loader type definitions

### ISSUE THREAD

**Issue by bobbinth** [AssemblyScript/assemblyscript#905]
I think there are a couple of errors in Loader type definitions. Specifically, in:

* https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/index.d.ts#L57
* https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/index.d.ts#L59

The return types should be `BigInt64Array` and `BigUint64Array` (not `BigInt32Array` and `BigUint32Array`).

**Comment by dcodeIO** [comment]
Good catch, yeah, these are wrong.
