### ISSUE TITLE
Add Version number to custom section

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#907]
Adding this here to track it. With binaryen's support for creating custom sections, it would be a good idea to add the version of the compiler used to generate the binary in a custom section.

**Comment by dcodeIO** [comment]
Related: There's a producers section under tool conventions but that's [a bit controversial](https://github.com/WebAssembly/tool-conventions/issues/93).

**Comment by willemneal** [comment]
Ah I see. I think that we should just have it as an option.  For example, having it for smart contracts where you only need the full binary once.

**Comment by dcodeIO** [comment]
Btw, with the new transforms, it should be possible to append additional custom sections to a binary, incl. potential additional version numbers not just of asc but also other parts of the specific toolchain being used.
