### ISSUE TITLE
How to read the real `byteOffset`?

### ISSUE THREAD

**Issue by zie1ony** [AssemblyScript/assemblyscript#928]
I try to read an array of bytes on my host:
```typescript
@external("env", "read_bytes")
declare function read_bytes(
  ptr: i32,
  size: i32,
): void;

export function call(): void {
    var value = new Uint8Array(3);
    value[0] = 1;
    value[1] = 2;
    value[2] = 3;
    read_bytes(
        value.byteOffset, // returns 0
        value.byteLength
    );

    var value2 = new Uint8Array(3);
    value2[0] = 4;
    value2[1] = 5;
    value2[2] = 6;
    read_bytes(
        value2.byteOffset,  // returns 0
        value2.byteLength
    );
}
```
I expected `byteOffset` to return a point in WASM memory where structure starts, but it doesn't work like that. 

I have the solution, that works fine in Rust:
```rust
let bytes: [u8; 32] = [255u8; 32];
let ptr = bytes.as_ptr();
let size = bytes.len();

unsafe {
    read_bytes(ptr, size);
}
``` 
Is it possible to have something similar in AssemblyScript?

**Comment by MaxGraey** [comment]
[`byteOffset`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/byteOffset) is not pointer. You should use `value.dataStart` or `changetype<usize>(value.buffer) + value.byteOffset`.

**Comment by zie1ony** [comment]
Great, `value.dataStart` works as expected.

I see in docs https://docs.assemblyscript.org/details/memory#arraybufferview-layout there should be also `dataLength` method, but it doesn't compile.
```
ERROR TS2339: Property 'dataLength' does not exist on type '~lib/arraybuffer/ArrayBufferView'.
```
I ended up with:
```typescript
read_bytes(
    value.dataStart,
    value.byteLength
);
```

**Comment by MaxGraey** [comment]
Yes. That chapter required updates.

**Comment by zie1ony** [comment]
I have follow up question here. How to reproduce `Uint8Array` given a pointer and a size? I think of something like `load<Uint8Array>(value.dataStart, value.byteLength)`, but `value.byteLength` needs to know at compile size. And I got lost :(

**Comment by MaxGraey** [comment]
```ts

// for Uint8Array

Uint8Array.wrap(
  changetype<ArrayBuffer>(value.dataStart),
  value.byteOffset, // or `0`
  value.byteLength
)

// for Uint32Array

Uint32Array.wrap(
  changetype<ArrayBuffer>(value.dataStart),
  value.byteOffset, // or `0`
  value.byteLength >> offsetof<u32>()
)
```

**Comment by zie1ony** [comment]
Thank you one more time.
I managed to write smart contract for CasperLabs platform using AssemblyScript and your help.
https://github.com/zie1ony/casperlabs-assemblyscript-transfer-to-account

**Comment by MaxGraey** [comment]
Nice!
