### ISSUE TITLE
Support for http requests

### ISSUE THREAD

**Issue by NHibiki** [AssemblyScript/assemblyscript#943]
Hi, all:

Apology for submitting this issue recklessly. But is there any way to make an http request in AssemblyScript? For example, `fetch` function? If there is not, are there any plans on this?

**Comment by willemneal** [comment]
Hey @NHibiki,  no need to apologize for the issue.  Currently the route for http requests is to add to the [node](https://github.com/AssemblyScript/node) project which aims to provide the same API as node using the [WASI](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-api.md) API which is the main system interface for WebAssembly.  With that any runtime that supports it will provide the functionality needed to implement features like http requests.

However, until then the best way is to just use an import from the js host that will handle the fetch.  The other issue is that currently there is no way to make asynchronous requests (at least easily), so you need to provide a call back function you want called when the request completes.

**Comment by NHibiki** [comment]
Okay, although it is a little bit inelegant 🤣, still thank you very much for your support! And I will keep watching this. Close for now.

**Comment by linzg2002** [comment]
@willemneal what is current status of http requests support with WASI API? If it is still not done, any workaround can be used? 
`
However, until then the best way is to just use an import from the js host that will handle the fetch. 
`
Be honest, I am not very sure about what the above exactly means, could you please give any further advance or example?

**Comment by linzg2002** [comment]
Thanks @willemneal . Will have a try.
