### ISSUE TITLE
webassembly.studio broken due to missing dist/asc.js

### ISSUE THREAD

**Issue by jayphelps** [AssemblyScript/assemblyscript#949]
Creating a new project on webassembly.studio seems to be broken when it tries to load asc.js from the docs.

![image](https://user-images.githubusercontent.com/762949/68625348-e74eba00-04a6-11ea-83df-1eb5e89de6d0.png)

```
require.js:5 GET https://assemblyscript.github.io/assemblyscript/dist/asc.js net::ERR_ABORTED 
raven.js:380 Uncaught Error: Script error for "assemblyscript/bin/asc"
```
I was going to post the issue in their tracker but saw that the URL was hosted on the GH Pages docs, and assume you all probably sanctioned the use of that URL and probably didn't intend to break it.

I tried poking around to see if I could figure out what changed, but couldn't tell which branch the docs are hosted from (no gh-pages branch name). I see the release branch and it seems to still be there: https://github.com/AssemblyScript/assemblyscript/blob/release/dist/asc.js

**Comment by dcodeIO** [comment]
We recently started publishing to npm, and the master branch doesn't host dist files anymore. I guess ideally we'd pull the dist files from npm now by updating `setup.js` within the template to use these paths:

```json
  paths: {
    "binaryen": "https://cdn.jsdelivr.net/npm/binaryen@nightly/index",
    "assemblyscript": "https://cdn.jsdelivr.net/npm/assemblyscript@nightly/dist/assemblyscript",
    "assemblyscript/bin/asc": "https://cdn.jsdelivr.net/npm/assemblyscript@nightly/dist/asc",
  }
```

Does this work for you?

**Comment by jayphelps** [comment]
Sounds good to me. Thanks @MaxGraey for the PR upstream!

**Comment by MaxGraey** [comment]
Should be fixed in https://github.com/wasdk/WebAssemblyStudio/pull/436
