### ISSUE TITLE
Add Action to preview PRs

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#951]
Currently it's difficult to test out new PRs since the master branch's `index.js` now uses ts-node to run the compiler.  They could be easily published to npm with [pika-ci](https://github.com/marketplace/pika-ci-cd), which @jtenner uses for [as-pect](https://github.com/jtenner/as-pect).

**Comment by dcodeIO** [comment]
The master branch is set up in a way now that if you install it (or any fork of it) through npm, you'll get a development install running the code through ts-node without the need to build dist files. That not enough?

**Comment by jtenner** [comment]
So technically aspect uses the dist files? That might be a reason not to install the fork. Pikaci is also nice for repos that aren't monorepos. Assemblyscript might be a reasonable use case.

All it does is run your build script and make it npm installable.

**Comment by willemneal** [comment]
Yeah the issue is, for example, that my transformer depends on the `index.js`, but `asc` still uses the dist files so again we end up with two different loaded compilers.

**Comment by dcodeIO** [comment]
> but asc still uses the dist files

Wondering how it does that, if there are no dist files?

**Comment by willemneal** [comment]
Ah well I was trying to test out my changes so I tried to pull a branch that had updated dist files.  This actually wasn't necessary because I was using `cli/asc.js` and didn't need `dist/asc.js.`  But for applications that need it this would still be a useful feature for testing out PRs in real world applications.
