### ISSUE TITLE
Stand-Alone WebAssembly Runtime Support?

### ISSUE THREAD

**Issue by jhwgh1968** [AssemblyScript/assemblyscript#967]
When I came across AssemblyScript, I decided to try prototyping it as an embedded scripting language for a project I'm working on. It would allow end-users to write code in Typescript (well, a subset of it) while allowing me to ship a WebAssembly runtime like [wasmtime](https://wasmtime.dev/) instead of an entire Javascript interpreter like V8 or SpiderMonkey.

It didn't go well:
```
$ mkdir assemblyscript-demo
$ cd assemblyscript-demo
$ npx asinit .
$ vim assembly/index.ts
$ cat assembly/index.ts 
// The entry file of your WebAssembly module.
export function mymain(): void {
  add(1, 41)
}

export function add(a: i32, b: i32): i32 {
  return a + b;
}
$ npm run asbuild
$ wasmtime --invoke=mymain build/optimized.wasm --wasi-c
Error: failed to process main module `build/optimized.wasm`

Caused by:
    Import module env was not found

$ wasm-dis build/optimized.wasm
(module
 (type $0 (func (param i32 i32) (result i32)))
[...]
 (type $6 (func (param i32 i32 i32)))
 (import "env" "abort" (func $fimport$0 (param i32 i32 i32 i32)))
 (memory $0 1)
[...]
```

This mysterious ``abort`` function is called after certain types of failures, and is always followed by an ``unreachable`` opcode. I have no idea what the giant blob of code containing it does (it seems to be memory related), but I presume it's part of the AssemblyScript standard library.

As far as I can tell, wasi (the libc emulation that is part of wasmtime) does not export an ``abort`` symbol, let alone namespace itself as "env".

Is there some way to turn this off? I doing something wrong?

**Comment by MaxGraey** [comment]
Plz see this issue: https://github.com/AssemblyScript/assemblyscript/issues/927

**Comment by dcodeIO** [comment]
For a bit of background: The `abort` function is called from within WebAssembly is something goes horribly wrong, like an `assert` failed or, at this point, an exception is thrown. It can be overridden at compile time, and one can also [decide to remove](https://docs.assemblyscript.org/details/debugging#overriding-abort) the import completely so an abort only execute `unreachable`.

The giant blob you are seeing is most likely the runtime implementation, consisting of a memory manager, garbage collector, parts of the standard library etc. If one doesn't need full blown memory management and gc, there are some smaller alternatives [listed here](https://docs.assemblyscript.org/details/runtime).

Hope that helps :)

**Comment by indis-io** [comment]
I have been working with AS from Rust, if i cleaned up my port of loader in rust would you like it in this repo? Or you could start a repo for AS Loaders? or...

**Comment by sampaioletti** [comment]
sorry, indis-io is me...i was logged in as the wrong user

**Comment by sampaioletti** [comment]
I also did enough work with go-wagon i might be able to at least get that started.

**Comment by jhwgh1968** [comment]
Based on those directions, I tried:

``npm run asbuild -- --use abort=``

And npm did not pass the extra arguments to ``asc`` the way I expected. But hacking ``package.json`` and manually adding those arguments does indeed work. I will open a separate issue on the npm package file.

Thanks, @dcodeIO!
