### ISSUE TITLE
asinit should include a test script

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#977]
The `asinit` scaffold is a really good idea, and helps people get started quickly. The one thing I feel is missing is an obvious way to test your module code, and for first-time users verify the setup.

I'd like to see a test script that runs a very simple test runner to verify the `add` function. 

I'd be happy to contribute if people think this is a good idea?

**Comment by jtenner** [comment]
Hi @ColinEberhardt. You can check out the as-pect cli located here: https://github.com/jtenner/as-pect

A really quick way to get started:

```
npm install --save-dev assemblyscript @as-pect/cli
npx asinit .
npx asp --init
```

Hope this helps, and if you need any help with bootstrapping tests you can ask anyone in the slack server for help.

**Comment by ColinEberhardt** [comment]
Thanks @jtenner I wasn't aware of as-pect, I'll take a look. One immediate piece of feedback on reading the README, it feels like you need to clearly describe why someone would use as-pect for testing assemblyscript versus standard JS test tools such as Jest. I can't see that described anywhere?

> Hope this helps, and if you need any help with bootstrapping tests you can ask anyone in the slack server for help.

Thank you - much appreciated. I'm pretty confident with WebAssembly so have got a decent dev cycle up and running with AS and Jest. My main observation is that most scaffolding projects tend to be nice and simple, but also verifiable - i.e. you can easily run them, typically via unit tests.

**Comment by jtenner** [comment]
Yeah. As-pect will compile your tests, so you can write them in AssemblyScript instead of needing to bootstrap the tests manually using jest (which I found to be quite painful.)

However, it's not always the case that it's better to bootstrap your tests using as-pect. For example, I have written some CanvasRendingContext2D bindings and use `jest-canvas-mock` to mock a canvas and validate function calls using it.

See here: https://github.com/as2d/as2d

**Comment by ColinEberhardt** [comment]
> Yeah. As-pect will compile your tests, so you can write them in AssemblyScript instead of needing to bootstrap the tests manually using jest (which I found to be quite painful.)

That's cool - and something you should mention right at the top of your README, it isn't obvious that your test cases are compiled and executed as AS!

**Comment by jtenner** [comment]
I just opened an issue with the docs, and will absolutely accept pull requests for clarity on *anything* that seems unclear. Thank you for your help!
