### ISSUE TITLE
Transforms using ExportsWalker are broken in 0.8.1

### ISSUE THREAD

**Issue by jeffcharles** [AssemblyScript/assemblyscript#978]
Given a transform function that uses the `ExportsWalker` class exported by AssemblyScript, when running it using `asc` using 0.8.1, a runtime error occurs.

E.g. given transform file `BarTransform.ts`,
```ts
import { Transform } from "assemblyscript/cli/transform";
import { ExportsWalker } from "assemblyscript";

class FooWalker extends ExportsWalker {
  ...
}

export = class BarTransform extends Transform {
  afterParse(parser: Parser) {
    ...
  }

  afterCompile(module: Module) {
    const walker = new FooWalker(this.program);
    ...
  }
}
```
run with `asc foo.ts -b build/foo.wasm --transform=BarTransform.ts` will yield an error with:
```
ERROR: TypeError: Class constructor o cannot be invoked without 'new'
```

Running the same transform with 0.8.0 works as expected.

Looking at the exports, it appears that the `assemblyscript` package is exporting `ExportsWalker` as an ES6 class in 0.8.1 but as an ES5 function in 0.8.0. I think this is caused by a change in `std/portable.json` where the target was changed from `es5` in 0.8.0 to `esnext` in 0.8.1.

Also relevant, Typescript transform files are transpiled using default compiler settings, one of which is to target es5, which results in Typescript transform files not being able to initialize exported classes from the `assemblyscript` package like `ExportsWalker`. That hasn't changed between versions.

There are two approaches that I think would fix this problem:
1. Use an `es5` target when building the `assemblyscript` package
2. Target `esnext` when transpiling Typescript transform files

**Comment by dcodeIO** [comment]
I guess ideally we'd make all parts use ES6 classes, since in a WebAssembly realm that should be supported. Perhaps specifying a proper target [here](https://github.com/AssemblyScript/assemblyscript/blob/241a7f56f0477b8334e8b42938d94b46ec89648c/cli/asc.js#L222) can help?

**Comment by jeffcharles** [comment]
In our case, it's part of a Node.js runtime since that's the environment we're running the compiler in. That said, ES6 classes are supported back to Node 6 so transpiling TS to ES6 should be fine.

Agreed that that location would be the correct place to add an appropriate compiler target for the transforms. I can open a PR to do that.

That said:
1. Should the target specified in that file match `std/portable.json`? To ensure that the exports walker is usable from the transform.
2. Should a more conservative target like `ES6` be used in both places to ensure more Node.js environments are supported?

**Comment by dcodeIO** [comment]
> Should the target specified in that file match std/portable.json?

The portable definitions are a bit of a special case in that these align with `std/assembly.json`, and one wouldn't normally use these unless one actually wants to write portable code (which is rare). It just so happens that the compiler itself is one such rare occasion and inherits portable, with the relevant config being `src/tsconfig.json` that should override the target I guess.

**Comment by jeffcharles** [comment]
Yeah, I understand that the transforms and portable don't interact so I would need to update `asc.js`. Anyway, would it make sense for `src/tsconfig.json` to override its target to `ES6` along with specifying `ES6` as the target in `asc.js`? AssemblyScript could continue using `esnext` for source transpilation and transform transpilation but my fear is that this could cause some weird behaviour on versions of Node that are not fully up-to-date.

**Comment by dcodeIO** [comment]
Yes, I think that's right. ts-node in `cli/asc.js` (loading transforms) and `src/tsconfig.json` (building what's being imported by transforms) should both specify the same target.
