### ISSUE TITLE
AssemblyScript Forum?

### ISSUE THREAD

**Issue by Choons** [AssemblyScript/assemblyscript#980]
I know this isn't really the proper place for this, but after looking around for a while and not finding one, is there a forum for AssemblyScript?

**Comment by willemneal** [comment]
What kind of forum are you looking for?  You can post questions to StackOverflow or post them here.

**Comment by dcodeIO** [comment]
There's also [the WebAssembly Discord](https://twitter.com/WebAssemblyEU/status/1146804418706362368) that has an AssemblyScript channel. Not exactly a forum, though.

**Comment by Choons** [comment]
Hi guys, yeah a forum for general questions & people showing off interesting stuff they come up with. StackOverflow is indispensible, but not easy to just peruse to see what the AssemblyScript community is doing. I suggest a Discourse forum-- the Three.js forum on Discourse https://discourse.threejs.org/ has been a great resource for me. Also, if AssemblyScript gets the traction I think it can, you guys will want to keep this area just for actual bug reports/resolutions, I would think. Anyway, thanks for AssemblyScript! I really think the future is for javascript and C to kind of merge into "The Language" -- powerful AND easy to understand and use.

**Comment by MaxGraey** [comment]
Thanks @Choons! The era of forums has already passed. In addition to accompany a separate forum to be seen as unpromising. There are StackOverflow, GitHub issues, Discord and Slack chats - that's more than enough.

**Comment by dcodeIO** [comment]
Well, not so sure about that. Even if it's not for everyone, than I'd still rather lean for "sure, why not" as long as it helps someone.

Did take a look at Discourse, but I am not too keen to install and manage it on our own hardware, as that seems to be what they have for open source.

**Comment by Choons** [comment]
Microsoft should host & pay for it since you are giving TypeScript new life!  ;-)

**Comment by munrocket** [comment]
Slack is closed. I can't find any forum about AssemblyScript in documentation.
