### ISSUE TITLE
Consider renaming __start to _start

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#983]
The `--explicitStart` option currently yields an export named `__start`, but it would be nice to align the name with WASI's `_start` function. There's still [some discussion](https://github.com/WebAssembly/WASI/issues/19) going on on the WASI side regarding that name, though, so we might have to reconsider something else later.

**Comment by dorin131** [comment]
Is this a good first issue?
Could I give it a try?

**Comment by dcodeIO** [comment]
I suspect you'd be disappointed of this as a first issue. It's mostly renaming at a couple places, but it's also a breaking change so it might make sense to collect more feedback before going for it.

**Comment by dorin131** [comment]
Do we want then to wait and see what decision WASI comes to and take it from there?

In the meantime, could you point me to a good first issue or task please?
