### ISSUE TITLE
Export class?

### ISSUE THREAD

**Issue by munrocket** [AssemblyScript/assemblyscript#986]
I am get a strange error, when I trying to export Class.
```javascript
type f64 = f64;

export class MyClass {
  a: f64;
  b: f64;
  constructor(a: f64, b: f64) {
    this.a = a;
    this.b = b;
  }
}

// asc ./src/file.ts -b ./dist/file.wasm -O3
//
// ERROR: RangeError: Maximum call stack size exceeded
```
Probably I am doing a strange things and I need to split my class to several small functions. But I don't see this case in [documentation](https://docs.assemblyscript.org/basics/limitations).

**Comment by dcodeIO** [comment]
Seems the error is caused by infinite recursion in `type f64 = f64`.

**Comment by munrocket** [comment]
Thanks for quick answer. You right.

**Comment by MaxGraey** [comment]
@dcodeIO I guess this special case need handled. Because `type f64 = f32` also cause to infinite recursion but this could be useful

**Comment by dcodeIO** [comment]
Yeah, there should either be special logic handling these or at least a proper error.

**Comment by MaxGraey** [comment]
In Typescript this cause to "TS2457: Type alias name cannot be 'number'." error for `type number = number`

**Comment by munrocket** [comment]
All is ok, since we have an issue in github. This issue will be indexed by google and will appear in search engines soon. Probably exists better improvements in AS.
