### ISSUE TITLE
Sourcemaps don't work (Chrome / Firefox)

### ISSUE THREAD

**Issue by vladimir-tikhonov** [AssemblyScript/assemblyscript#996]
Hi,

The sourcemaps produced by the sample project ( `npx asinit .` ) don't seems to work. Chrome allow you to open `index.ts` in debugger, but it's completely empty, whether FF don't even allow you to open `index.ts`. Debugging in chrome doesn't work completely, FF jumps straight to IL code. Both browser successfully request `.map` file as I can see in server's log.
I've tried few versions from npm (from `0.8.0` to `0.8.1-nightly.20191205`), neither of them produce a valid sourcemaps.

My build script:
```bash
asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap build/untouched.wasm.map --validate --debug
```

`index.html`:
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>AssemblyScript demo</title>
    </head>
    <body>
        <script src="index.js"></script>
    </body>
</html>
```

`index.js`:
```js
(async () => {
  const importObject = {
      env: {
          abort(_msg, _file, line, column) {
              console.error("abort called at index.ts:" + line + ":" + column);
          }
      }
  };
  const module = await WebAssembly.instantiateStreaming(
      fetch("build/untouched.wasm"),
      importObject
  );
  const add = module.instance.exports.add;
  console.log( add(3, 4) );
})();
```

`index.ts`:
```typescript
export function add(a: i32, b: i32): i32 {
  return a + b;
}
```

**UPD**: I've stumbled upon https://michaeljcole.github.io/n-body-wasm-canvas/ which is written using AssemblyScript, and it seems that it has the same problem with sourcemaps. If you open `nBodyForces.ts` in Chrome's debugger it will be empty.

**Comment by vladimir-tikhonov** [comment]
Here's the sourcemaps in case you need them. I was able to upload them to https://sokra.github.io/source-map-visualization/ and see the original code, but I'm not competent enough to make any conclusions based on that :) Btw, sourcemaps seems to include some files from `lib`, such as "~lib/rt/common.ts","~lib/shared/typeinfo.ts","~lib/rt/pure.ts","~lib/rt/tlsf.ts", not sure if this is intentional.

[untouched.wasm.map.zip](https://github.com/AssemblyScript/assemblyscript/files/3935212/untouched.wasm.map.zip)

**Comment by dcodeIO** [comment]
From a quick test, it appears that there are two problems.

1. We are currently using the key `sourceContents`, but should use `sourcesContent` when generating the `.map` file in `cli/asc.js`.
2. When I `WebAssembly.instantiateStreaming(fetch("./somedir/some.wasm"), ...)` and `sourceMappingURL="some.wasm"`, my local chrome install always attempts to load `/some.wasm.map`, as if relative source maps in Wasm binaries wouldn't work anymore. Now I'm not sure where this comes from, as I believe some of the "half-working" instances mentioned here do relative source maps and the browser still loads the correct file there, even though contents are broken. Very strange.

**Comment by MaxGraey** [comment]
Should fixed now in master and `assemblyscriopt@nightly`

**Comment by vladimir-tikhonov** [comment]
@MaxGraey great, thanks a lot! I can confirm that it works just fine now (except for different request paths in FF/Chrome)
