### ISSUE TITLE
Idea for x5 optimization for functions that return classes, objects or small arrays

### ISSUE THREAD

**Issue by munrocket** [AssemblyScript/assemblyscript#997]
I noticed that when we create a functions that return Class, Objects or small Array performance become worse than in JS. I was curious why this happens and created a new version of my code and get x7 boost in performance for f64 struct. It can be little bit optimistic because I have too simple structure.

The idea:

When you compile a code it often allocated objects with the same Shapes. It can be a Points, some Tuples or general Objects. All is ok when you create it once or twice in your code, but it can be huge problem when you run this code in loop.

So we can allocate only once a relatively big Turing tape with this objects. And when we invoke a function that return objects with this shapes, we can pass a new index from tape in which we can store result object.

Also we can notice that we can reuse space in this tape for different function scopes. Here a lot of room for your imagination how to do this. For example all methods in one class can have only one temporary cache and another cache for another functions.

Source code:
[before](https://pastebin.com/h3eVzdub), [after](https://github.com/munrocket/double.js/blob/master/wasm/mandel.ts)

Picture with [results](https://munrocket.github.io/double.js/docs/benchmark.html):

![](https://habrastorage.org/webt/7j/-d/fx/7j-dfxi1rn1t6foh-usnemqm4x0.png)

**Comment by MaxGraey** [comment]
Object explosion optimization (when simple objects represent as set of variables and reused) is not yet present.

Btw you could improve speed even more by using global variables instead array. Replace this
```ts
let R = new Float64Array(16)
```
to
```ts
let R0 = 0.0;
let R1 = 0.0;
...
let R15 = 0.0;
```

**Comment by MaxGraey** [comment]
Also I'm not sure you need so many variables. I guess one or two will be enough

**Comment by munrocket** [comment]
Yep, you right with one variable optimization even better. Huge impact.

![](https://habrastorage.org/webt/me/98/iy/me98iykblf7q4dsv9gltwmc257m.png)

**Comment by munrocket** [comment]
This will be not acutal after [Platform-independent Just-in-Time (JIT) compilation](https://github.com/WebAssembly/design/blob/4c6cad51e082675774ed9ea28c7129c293a2445f/FutureFeatures.md#platform-independent-just-in-time-jit-compilation). But we don't know when it will be implemented.
